### ISSUE TITLE
HmIP-SWDO & HmIP-SWDO-I always off

### ISSUE THREAD

**Issue by noxhirsch** [SukramJ/hahomematic#100]
I've noticed that the binary state sensors for the door/window sensors HmIP-SWDO & HmIP-SWDO-I always are "off" (closed).
To test if it is only because the status doesn't update, I opened a window, rebooted Home Assistant - but the binary sensor was still off.

For reference: The old HM-Sec-SCo door/window sensor works perfectly fine.

**Comment by Lemocin** [comment]
Same for HmIP-SWDM-B2

**Comment by SukramJ** [comment]
Fixed with latest release

**Comment by noxhirsch** [comment]
It's working - thank you very much!
