### ISSUE TITLE
Integration does not find any devices, only system variables

### ISSUE THREAD

**Issue by BlazeCodeDev** [SukramJ/hahomematic#1019]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Integration does not find any devices, only system variables

### What version of HomematicIP (local) has the issue?

1.33.1

### What type of installation are you running?

Home Assistant Container

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.67.10.20230225

### What hardware are you running for your system?

Pi3

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Debug log generated while reloading the integration:

[home-assistant_homematicip_local_2023-04-07T14-34-19.770Z.log](https://github.com/danielperna84/hahomematic/files/11179558/home-assistant_homematicip_local_2023-04-07T14-34-19.770Z.log)

### Integration config:

[config_entry-homematicip_local-608e61b0f87da5023a4f9a14eb875825.json (1).txt](https://github.com/danielperna84/hahomematic/files/11179574/config_entry-homematicip_local-608e61b0f87da5023a4f9a14eb875825.json.1.txt)

### Additional information

![image](https://user-images.githubusercontent.com/60486125/230627269-c587c45d-520d-46ce-b18a-9a382114712c.png)

**Comment by SukramJ** [comment]
Delete the cache with service (dev-tools/services)`homematicip_local.clear_cache`, and restart HA.

**Comment by BlazeCodeDev** [comment]
Just tried that, same outcome

**Comment by SukramJ** [comment]
Do you run your HA docker container in host-mode?

**Comment by SukramJ** [comment]
[See](https://github.com/danielperna84/custom_homematic#firewall-and-required-ports)

**Comment by BlazeCodeDev** [comment]
Switching to host mode did the trick. Sorry for bothering you with that and thanks for the quick help!
