### ISSUE TITLE
HmIP-SWDO is always closed in Home Assistant

### ISSUE THREAD

**Issue by ManuVice** [SukramJ/hahomematic#1020]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Happy Easter,
I have 3x HmIP-SWDO. Showing state open/closed in RaspberryMatic is working just fine. But in Home Assistant state is always shown as closed. In the attachment I opend my door with debugging enabled in HA, but there are no logs about that action.
Other entities from RaspberryMatic are working fine in HA.

### What version of HomematicIP (local) has the issue?

1.33.1

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.69.6.20230407

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [X] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[home-assistant_homematicip_local_2023-04-09T08-16-59.626Z.log](https://github.com/danielperna84/hahomematic/files/11185048/home-assistant_homematicip_local_2023-04-09T08-16-59.626Z.log)
[config_entry-homematicip_local-93bd3f75b8cc62055b78f1deafc9f27b.json.txt](https://github.com/danielperna84/hahomematic/files/11185049/config_entry-homematicip_local-93bd3f75b8cc62055b78f1deafc9f27b.json.txt)

### Additional information

The updated log was because of updating RaspberryMatic

![Screenshot 2023-04-09 102229](https://user-images.githubusercontent.com/555893/230762278-6ab827f1-e7d5-473f-b058-5a274d1b0917.png)

**Comment by SukramJ** [comment]
Mine are working fine, so this is not an issue with this integration.
Sounds like your ccu is not sending the events.
Try to restart ccu and HA.

**Comment by ManuVice** [comment]
> Try to restart ccu and HA.

tried several times. It seems I have this problems for months but didnt notice.

**Comment by SukramJ** [comment]
As long as you don‘t receive events from your ccu there is nothing I can do.
Check your ccu logs.

**Comment by ManuVice** [comment]
My bad! Thank you.. it wasnt that hard... was a firewall problem.
