### ISSUE TITLE
HOMEMATICIP_LOCAL-Interface not reachable, No connection to interface RaspberryMatic-BidCos-RF

### ISSUE THREAD

**Issue by bilbo-b** [SukramJ/hahomematic#1023]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I had the custom_component and raspberrymatic addon running for over a year on a raspberry pi4 with HM-MOD-RPI-PCB: 2.8.6 on HAOS (aarch64) with only bidcos-rf components. 
Somewhere around beginning of April possibly after upgrading HAOS, HA or raspberrymatic, I got the above errormessage in HA. When logging into Raspberrymatic, it seems to work fine, I can switch lights on and off or control a thermostat.
I tried further opening the firewall (full access) and fiddling with ports in the configuration of the addon, but did not succeed in controlling Raspberrymatic from HA. I tried to reconfigure the integration, only checking "enable Homematic (Bidcos-RF)" on the second page and as a result always get "Invalid password" for "Admin" and the password that still works on the WebUI of RaspberryMatic.
What could I try to further analyse or what may have changed that I need to accommodate for?

### What version of HomematicIP (local) has the issue?

1.34.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic HA-Addon

### Which version of your homematic backend are you running?

3.69.6.20230407

### What hardware are you running for your system?

Pi4

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.4.4",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.10",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "5.15.84-v8",
    "supervisor": "2023.04.0",
    "host_os": "Home Assistant OS 9.5",
    "docker_version": "20.10.22",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "dwd_weather": {
      "version": "1.2.25",
      "requirements": [
        "simple_dwd_weatherforecast==1.1.5",
        "markdownify==0.6.5"
      ]
    },
    "homematicip_local": {
      "version": "1.34.0",
      "requirements": [
        "hahomematic==2023.3.1"
      ]
    },
    "hacs": {
      "version": "1.32.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "browser_mod": {
      "version": "2.2.1",
      "requirements": []
    },
    "ui_lovelace_minimalist": {
      "version": "v1.3.4",
      "requirements": [
        "aiofiles==0.8.0",
        "aiogithubapi>=22.2.4"
      ]
    },
  "integration_manifest": {
    "domain": "homematicip_local",
    "name": "Homematic(IP) Local",
    "codeowners": [
      "@danielperna84",
      "@SukramJ"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/danielperna84/custom_homematic",
    "homekit": {},
    "integration_type": "hub",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/danielperna84/hahomematic/issues",
    "loggers": [
      "hahomematic"
    ],
    "requirements": [
      "hahomematic==2023.3.1"
    ],
    "ssdp": [
      {
        "manufacturer": "EQ3",
        "manufacturerURL": "http://www.homematic.com"
      }
    ],
    "version": "1.34.0",
    "zeroconf": [],
    "is_built_in": false
  },
  "data": {
    "config": {
      "entry_id": "ee1f2e76dfb35c71f2e62c184477957a",
      "version": 1,
      "domain": "homematicip_local",
      "title": "RaspberryMatic",
      "data": {
        "instance_name": "RaspberryMatic",
        "host": "172.30.33.1",
        "username": "**REDACTED**",
        "password": "**REDACTED**",
        "tls": false,
        "verify_tls": false,
        "callback_host": null,
        "callback_port": null,
        "json_port": null,
        "interface": {
          "BidCos-RF": {
            "port": 2001
          }
        }
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": "DD89A48A26",
      "disabled_by": null
    },
    "platform_stats": {},
    "devices": []
  }
}

**Comment by SukramJ** [comment]
Switch to a password with only allowed characters (`A-Za-z0-9.!$():;#-`).
API and WebUI have different checks.

**Comment by bilbo-b** [comment]
thank you, I had an asterisk in my password, which worked since my initial installation > 1 year ago. I was not aware, that it was not an allowed character. After changing the password to characters in the range mentioned by you, it works.
