### ISSUE TITLE
HmIP-RGBW

### ISSUE THREAD

**Issue by Boarder** [SukramJ/hahomematic#1029]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

The new Controler HmIP-RGBW is not showing up as a light entity.
I didn´t find any why to build a dashboard with a light switch.
<img width="1350" alt="HmIP-RGBW" src="https://user-images.githubusercontent.com/45979973/232503090-4f33eb65-9777-4e17-bbe9-73495fe52882.png">

### What version of HomematicIP (local) has the issue?

1.3.4.1

### What type of installation are you running?

Home Assistant Supervised

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.69.6.20230407

### What hardware are you running for your system?

NUC

### Which config details do you use

- [ ] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
This device is currently not supported. Please create device descriptions as described [here](https://github.com/danielperna84/custom_homematic#homematicip_localexport_device_definition) and add them here too.
Please add some screenshots from ccu web ui.
