### ISSUE TITLE
Device (firmware) version does not update

### ISSUE THREAD

**Issue by IAmKonni** [SukramJ/hahomematic#1030]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I recently updated the firmware of my HmIP-DRBLI4 devices from 1.4.0 to 1.8.2. But in Home Assistant still version 1.4.0 is shown - even after i reloaded the integration.

![image](https://user-images.githubusercontent.com/67658239/232575178-54440195-5fa9-49a9-a0fe-67cba546f842.png)

### What version of HomematicIP (local) has the issue?

1.34.0

### What was the last working version of HomematicIP (local)?

none

### What type of installation are you running?

Home Assistant Container

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.69

### What hardware are you running for your system?

Intel NUC

### Which config details do you use

- [ ] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Use service (dev-tools) [homematicip_local.clear_cache](https://github.com/danielperna84/custom_homematic#homematicip_localclear_cache) and restart HA.

**Comment by IAmKonni** [comment]
Did not know a clear cache is existing. =)
Is it possible to run it automatically, when integration is reloaded via UI?

BTW: problem solved :)
