### ISSUE TITLE
Lost all connections to raspmatic

### ISSUE THREAD

**Issue by DreamScout** [SukramJ/hahomematic#1036]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hi

After i updated to ->1.34.2 HOMEMATICIP_LOCAL-Interface not reachable All Devices
If i try to connect again in settings -> no connection
There is a other IP now in the Settings from hahomematic?! 172.30.33.0
I tried to changed it back to the Hostname from raspberrymatic. Not Working.
After  Full Backup restore from Yesterday Hahomematic get also no connection. Same Problem. Also after multible Reboots.
Raspberrymatic is working. No Problems. Only the HomeMatic RS485 Gateway crashes after few hours. But this is a other issue...

Thx

### What version of HomematicIP (local) has the issue?

1.34.2

### What was the last working version of HomematicIP (local)?

1.34.1

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.69.6.20230407

### What hardware are you running for your system?

Pi4

### Which config details do you use

- [x] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [x] Homematic IP
- [x] Homematic (Bidcos-RF)
- [x] Groups (Heating-Group)
- [x] BidCos-Wired (HM-Wired)

### Diagnostics information

[home-assistant_2023-04-25T03-27-20.089Z.log](https://github.com/danielperna84/hahomematic/files/11316171/home-assistant_2023-04-25T03-27-20.089Z.log)
[supervisor_2023-04-25T03-28-41.691Z.log](https://github.com/danielperna84/hahomematic/files/11316175/supervisor_2023-04-25T03-28-41.691Z.log)
[de838cd8_raspberrymatic_2023-04-25T03-28-30.031Z.log](https://github.com/danielperna84/hahomematic/files/11316176/de838cd8_raspberrymatic_2023-04-25T03-28-30.031Z.log)

**Comment by SukramJ** [comment]
Use the hostname `de838cd8_raspberrymatic` instead of IP as described in the [installation instructions](https://github.com/jens-maus/RaspberryMatic/wiki/HomeAssistant-Integration#homematicip-local-integration-setup).

**Comment by DreamScout** [comment]
I used the de838cd8_raspberrymatic. After update i checked the configs and the there was the ip.
i tried to changed it back to de838cd8_raspberrymatic but it show error "no connection" 
I fixed it now. i put the hass port 8123 in the firewall config from raspberrymatic.
after then i put the de838cd8_raspberrymatic back in the config and now it works.
