### ISSUE TITLE
Name Devices 

### ISSUE THREAD

**Issue by Ghoja** [SukramJ/hahomematic#104]
New Devices are called with the serial number instead of the name:
![image](https://user-images.githubusercontent.com/15338292/147565196-e3aa68ba-05e3-45e5-b6f6-7ee635c6a8bc.png)
![image](https://user-images.githubusercontent.com/15338292/147565289-3f9caaf3-3aef-4086-8b71-db6e7324ecd3.png)

**Comment by SukramJ** [comment]
Please have a look at this [discussion](https://github.com/danielperna84/hahomematic/discussions/92).

**Comment by Ghoja** [comment]
Thank you, that work around would help. 
Is it possible to the serial number as unique id and the name as entity id? https://www.home-assistant.io/faq/
I think openHAB has solved this problem as described. There is possible with my configuration.

**Comment by SukramJ** [comment]
The serial number is part of the unique id.
You don't set an entity_id in HA. HA uses the name to create a unique entity_id.
So, if you have good names, then you have good entity ids.

**Comment by Ghoja** [comment]
ok, thank you
