### ISSUE TITLE
HmIP-RGBW now in home assistant just with one channel

### ISSUE THREAD

**Issue by Rami-Mati** [SukramJ/hahomematic#1044]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

after installing Version 1.35.0 the RGBW show me in HA just one light/channel, I configured it on CCU3 as 4 channels.

### What version of HomematicIP (local) has the issue?

1.35

### What was the last working version of HomematicIP (local)?

1.34.2

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.69.7

### Which config details do you use

- [x] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [x] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
> I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)

Pleas ensure that you read the documentation. Some entities are [deactivated](https://github.com/danielperna84/custom_homematic#deactivated-entities)
You might also read the related [discussion](https://github.com/danielperna84/hahomematic/discussions/1031).
