### ISSUE TITLE
HAHM stopped working with HA 2023.5.0

### ISSUE THREAD

**Issue by pjanning** [SukramJ/hahomematic#1049]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

My integration stopped working sinnce i upgraded to HomeAssistant 2023.5.0. Reboots or releads don't solve this problem.

### What version of HomematicIP (local) has the issue?

1.36.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.69.6

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Anything in the logs that might be useful for us?

```txt
Following error Message: `Error setting up entry PJ-Homematic for hahm
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hahm/__init__.py", line 26, in async_setup_entry
    hass.config_entries.async_setup_platforms(config_entry, HAHM_PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'`
```

**Comment by SukramJ** [comment]
You are using a very old version of this integration, because you did not follow the [migration guide](https://github.com/danielperna84/custom_homematic/wiki/Migration--from-domain-hahm-to-homematicip_local) that was part of release notes to version [1.0.0](https://github.com/danielperna84/custom_homematic/releases/tag/1.0.0) released in march 2022.

So follow the migration guide.
