### ISSUE TITLE
Can't start in 2023.5.0 and 2023.5.1  

### ISSUE THREAD

**Issue by timostr** [SukramJ/hahomematic#1050]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

HomematicIP (local) can't be started in HomeAssistant Core 2023.5.0 and 2023.5.1.
Error message: "Error setting up entry RaspberryMatic for homematicip_local"

Logger: homeassistant.config_entries
Source: custom_components/homematicip_local/__init__.py:56
Integration: Homematic(IP) Local ([documentation](https://github.com/danielperna84/custom_homematic), [issues](https://github.com/danielperna84/hahomematic/issues))
First occurred: 08:23:24 (1 occurrences)
Last logged: 08:23:24

Error setting up entry RaspberryMatic for homematicip_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/homematicip_local/__init__.py", line 56, in async_setup_entry
    hass.config_entries.async_setup_platforms(config_entry, HMIP_LOCAL_PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

It seems that following root cause is the problem:

> The async_setup_platforms function had been marked deprecated a while back, initially set to fail as obsolete in 2023.3. Now it actually fails in 2023.5, as previously announced.
> Since all the messages in this thread are about custom integrations (likely from HACS) the developer of those custom integrations will need to update their integration to use to use await async_forward_entry_setups instead of async_setup_platforms.

### What version of HomematicIP (local) has the issue?

3.69.6.20230407

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic HA-Addon

### What hardware are you running for your system?

Pi4

### Which config details do you use

- [X] Username and password
- [X] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[home-assistant_homematicip_local_2023-05-05T06-44-56.165Z.log](https://github.com/danielperna84/hahomematic/files/11403845/home-assistant_homematicip_local_2023-05-05T06-44-56.165Z.log)

### Anything in the logs that might be useful for us?

```txt
2023-05-05 08:23:04.148 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry RaspberryMatic for homematicip_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/homematicip_local/__init__.py", line 56, in async_setup_entry
    hass.config_entries.async_setup_platforms(config_entry, HMIP_LOCAL_PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

**Comment by SukramJ** [comment]
Update your integration to the latest version.
Looks like you did not update this custom component within the last 4 month.
This has been solved in 1.27.2 from january this year current version is 1.36.0.
