### ISSUE TITLE
Can't start with HA 2023.5.2

### ISSUE THREAD

**Issue by dersch81** [SukramJ/hahomematic#1052]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

After uprading HA to 2023.5.2 and custom_Homeatic to 1.36.0 (in one shot) the integration does not start anymore. Also i'm not using homematic_ip at all but can't deactivate it in the settings anymore. 

### What version of HomematicIP (local) has the issue?

1.36.0

### What was the last working version of HomematicIP (local)?

1.35.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic HA-Addon

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

Logger: homeassistant.config_entries
Source: custom_components/hahm/__init__.py:26
Integration: Homematic(IP) Local ([documentation](https://github.com/danielperna84/custom_homematic), [issues](https://github.com/danielperna84/hahomematic/issues))
First occurred: 12:40:51 (13 occurrences)
Last logged: 14:35:00

Error setting up entry RaspberryMatic for hahm
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hahm/__init__.py", line 26, in async_setup_entry
    hass.config_entries.async_setup_platforms(config_entry, HAHM_PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

### Anything in the logs that might be useful for us?

```txt
Logger: custom_components.hahm.config_flow
Source: custom_components/hahm/config_flow.py:277
Integration: Homematic(IP) Local (documentation, issues)
First occurred: 12:45:32 (16 occurrences)
Last logged: 14:34:57

Unable to connect (<ProtocolError for de838cd8-raspberrymatic:2010/RPC2: 503 Service Unavailable>,).
Unable to connect (<ProtocolError for de838cd8-raspberrymatic:42010/RPC2: 503 Service Unavailable>,).
```

### Additional information

Logger: hahomematic.json_rpc_client
Source: custom_components/hahm/control_unit.py:179
Integration: Homematic(IP) Local ([documentation](https://github.com/danielperna84/custom_homematic), [issues](https://github.com/danielperna84/hahomematic/issues))
First occurred: 14:34:53 (2 occurrences)
Last logged: 14:34:53

login: Unable to open session: {'name': 'JSONRPCError', 'code': 503, 'message': 'service not available'}
post: Error while logging in via JSON-RPC.

**Comment by SukramJ** [comment]
Same issue like #1049

**Comment by dersch81** [comment]
I followed the migration path. But now i can't setup the integration anymore:

![image](https://github.com/danielperna84/hahomematic/assets/13754891/c76fe60b-44d5-4c88-94fe-5711aa700387)

```
Logger: homeassistant.config_entries
Source: config_entries.py:863
First occurred: 16:46:04 (1 occurrences)
Last logged: 16:46:04

Error occurred loading flow for integration homematicip_local: cannot import name 'cleanup_cache_dirs' from 'hahomematic.support' (/usr/local/lib/python3.10/site-packages/hahomematic/support.py)
```

**Comment by SukramJ** [comment]
Did you remove the integration from HA?

**Comment by dersch81** [comment]
Yes after this error happened directly after the migration process i removed it also from hacs and startet from zero again.

**Comment by SukramJ** [comment]
I don't know this error message.
Maybe more information is in the log files.

**Comment by dersch81** [comment]
That'S the only error in the log:

`Error occurred loading flow for integration homematicip_local: cannot import name 'cleanup_cache_dirs' from 'hahomematic.support' (/usr/local/lib/python3.10/site-packages/hahomematic/support.py)`
