### ISSUE TITLE
 P_Boost Living Room Indicator Count

### ISSUE THREAD

**Issue by mikulik86** [SukramJ/hahomematic#1058]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

There is an entity named `P_Boost Living Room Indicator Count (button.raspberrymatic_p_boost_living_room_indicator_count)` in my HA which, even when enabled, is still unavailable.

Am I right to assume that it has something to do with the Boost function of my living room climate entity? Why is it not available?

### What version of HomematicIP (local) has the issue?

1.36.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic HA-Addon

### Which version of your homematic backend are you running?

3.69.7.20230506

### Which config details do you use

- [ ] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
I don't have my crystal ball with me, but I have no idea what kind of device it is. So how can I tell you what your problem is?

**Comment by SukramJ** [comment]
If I have to guess, from the naming scheme it could also be a program that has been disabled in the CCU. So you should activate the program in the CCU. Or?

**Comment by mikulik86** [comment]
There is no Problem per se. I was just trying to figure out if there is an entity which displays the current state of the Boost timer.
Is there?

**Comment by SukramJ** [comment]
The boost mode can be controlled by the climate entity, but the time cannot be displayed.
