### ISSUE TITLE
Error setting up entry "Homematic-CCU2" for hahm after upgrading HA to Core 2023.5.3

### ISSUE THREAD

**Issue by moelloman** [SukramJ/hahomematic#1062]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

After installing HA core from 2023.4.6 to 2023.5.0 and now (2nd try) 2023.5.3 hahm is not starting the connection to my CCU2 with the error message "Error setting up entry Homematic-CCU2 for hahm". 

### What version of HomematicIP (local) has the issue?

1.36.0

### What was the last working version of HomematicIP (local)?

1.36.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU2

### Which version of your homematic backend are you running?

2.61.7

### What hardware are you running for your system?

Pi4

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[home-assistant_hahm_2023-05-16T19-22-59.784Z.log](https://github.com/danielperna84/hahomematic/files/11491310/home-assistant_hahm_2023-05-16T19-22-59.784Z.log)

### Anything in the logs that might be useful for us?

```txt
Error setting up entry Homematic-CCU2 for hahm
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hahm/__init__.py", line 26, in async_setup_entry
    hass.config_entries.async_setup_platforms(config_entry, HAHM_PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

**Comment by SukramJ** [comment]
That why the [issue](https://github.com/danielperna84/hahomematic/issues/1049) is pinned.
