### ISSUE TITLE
UPDATE_DEVICE_FIRMWARE failed: the interface is not able to carry an update

### ISSUE THREAD

**Issue by Aerics84** [SukramJ/hahomematic#1064]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I try to use the new firmware update function and getting the error: UPDATE_DEVICE_FIRMWARE failed: ClientException [(<Fault -7: 'the interface is not able to carry an update'>,)]

### What version of HomematicIP (local) has the issue?

1.37.0

### What type of installation are you running?

Home Assistant Container

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[config_entry-homematicip_local-9651d93b185c38a401e863b25b5d4e21.json.txt](https://github.com/danielperna84/hahomematic/files/11546527/config_entry-homematicip_local-9651d93b185c38a401e863b25b5d4e21.json.txt)

### Anything in the logs that might be useful for us?

```txt
Protokolldetails (WARNUNG)
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht
Logger: hahomematic.client
Source: custom_components/homematicip_local/update.py:147
Integration: Homematic(IP) Local (documentation, issues)
First occurred: 06:47:08 (5 occurrences)
Last logged: 18:30:44

UPDATE_DEVICE_FIRMWARE failed: ClientException [(<Fault -7: 'the interface is not able to carry an update'>,)]
```

**Comment by SukramJ** [comment]
I doesn‘t look like you use HomematicIP. So which device do you use?

**Comment by Aerics84** [comment]
RaspberryMatic 3.69.6.20230407 on a Pi with an HM-CFG-USB.
HA in docker on my Synology with the HACS "Homematic(IP) Local" integration.

**Comment by SukramJ** [comment]
Which device do you want to update?

**Comment by Aerics84** [comment]
HM-CC-RT-DN from 1.4 to 1.5
HM-TC-IT-WM-W-EU from 1.3 to 1.4

**Comment by SukramJ** [comment]
Please go to `developer tools -> state` (`Entwicklerwerkzeuge -> Zustände`) and search for the `update` entity of these devices.
What is the content of the attribute `firmware_update_state`

And is the update button available in the CCU WebUI?

**Comment by SukramJ** [comment]
I googled a bit and it looks like it's not possible (or depends on the version??) to update the device firmware with an `HM-CFG-XXX` adapter.

https://de.elv.com/forum/hm-cc-rt-dn-firmwareupdate-ueber-usb-oder-lan-adapter-8827
https://forum.homegear.eu/t/firmware-upgrade-von-hm-cc-rt-dn-via-hm-cfg-usb-2/414
https://homematic-forum.de/forum/viewtopic.php?t=55138&start=20

Are you able to start the update with the CCU WebUI?

**Comment by SukramJ** [comment]
Auch interessant: https://homematic-forum.de/forum/viewtopic.php?t=15594

**Comment by SukramJ** [comment]
Looks like HM-CFG-USB cannot be supported by this integration for device firmware updates.
