### ISSUE TITLE
Integration can not be used after migration

### ISSUE THREAD

**Issue by dersch81** [SukramJ/hahomematic#1069]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

After coming from a working setup I needed to migrate. Since that i can't activate the Integration anymore

Logger: homeassistant.config_entries
Source: config_entries.py:863
First occurred: 11:58:13 (1 occurrences)
Last logged: 11:58:13

Error occurred loading flow for integration homematicip_local: cannot import name 'cleanup_cache_dirs' from 'hahomematic.support' (/usr/local/lib/python3.10/site-packages/hahomematic/support.py)

![image](https://github.com/danielperna84/hahomematic/assets/13754891/ef020809-34d9-4e87-858b-d2173b236ade)

### What version of HomematicIP (local) has the issue?

1.36.0

### What was the last working version of HomematicIP (local)?

1.35.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic HA-Addon

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Something is broken in your HA setup. 

Cleanup everything:
- Remove the integration from hacs
- Cleanup your custom_components folder
  - Remove hahm
  - Remove homematicip_local

Restart HA

Reinstall it again.

**Comment by dersch81** [comment]
Hi, i did this already several times. Is there anything in addition inside the system except in the custom_components folder?

**Comment by SukramJ** [comment]
If you have already removed the integration in UI, then there should be nothing left.

Maybe it helps to go to the command line and rebuild the container `ha core rebuild`. That might remove old stuff from the ha container.

**Comment by dersch81** [comment]
With your hints i've could get it back in a working state. Thanks
