### ISSUE TITLE
HMIP-RGBW light entity showing no state in single channel mode

### ISSUE THREAD

**Issue by plaxtika** [SukramJ/hahomematic#1076]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

The light entity for the Channels of the HMIP-RGBW not showing any state (on/off dimming)

On click the light goes on and of but the state in HA is „unbekannt“

### What version of HomematicIP (local) has the issue?

1.37.3

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [X] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Your description is not very clear to me.
Please post some screen shots from HA and CCU.
Is it the first version of the custom component you use this device?
In which mode is the device operated?

**Comment by plaxtika** [comment]
![IMG_0567](https://github.com/danielperna84/hahomematic/assets/35133439/2d4e3ff8-c7f5-4b72-9823-fba57903da87)
![IMG_0568](https://github.com/danielperna84/hahomematic/assets/35133439/140cab1e-9614-4433-9e90-4ad9fa0575dc)
![IMG_0569](https://github.com/danielperna84/hahomematic/assets/35133439/84b5cbbb-c889-4141-bc10-af74798bb986)

**Comment by plaxtika** [comment]
I click the on button - light is on, in reality and in ccu3 but the state is it not in HA. 

Yes is the first version i use custom comp. With it. 

The device is in single channel mode.

**Comment by SukramJ** [comment]
Try this:
Execute this service (dev tools/services)`Homematic(IP) Local: Clear the cache` and restart HA.

**Comment by plaxtika** [comment]
Ok i did, no change. Same issue

**Comment by SukramJ** [comment]
I don't know the device in this mode (I don't have one either). But first I'll go on vacation and only then can I take care of it.
