### ISSUE TITLE
Keine Steuerung von Geräten möglich

### ISSUE THREAD

**Issue by Bimboboy007** [SukramJ/hahomematic#1079]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Es lassen sich keine Geräte über die Benutzeroberfläche von HA steuern und auch nicht mit den Steuerelementen das Addons. Weder Rolladen noch Lichter. Normal habe ich immer eine Meldung in HA bekommen wenn ich z.B die CCU neu gestartet habe dies ist aber auch nicht mehr der Fall. Aufgefallen ist mir das Problem erst seit den letzen updates von HA da es sehr lange gedauert hat beim Neustart von HA bis Homematic geladen war. 
Ein Neustart von HA hat das Problem momentan wieder behoben, musste dies heute aber schon einmal durchführen.

### What version of HomematicIP (local) has the issue?

1.37.3

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.69.7.20230506

### What hardware are you running for your system?

Thinker Board S

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[home-assistant_homematicip_local_2023-06-11T21-37-45.221Z.log](https://github.com/danielperna84/hahomematic/files/11715834/home-assistant_homematicip_local_2023-06-11T21-37-45.221Z.log)

### Additional information

<img width="719" alt="Bildschirmfoto 2023-06-11 um 23 56 36" src="https://github.com/danielperna84/hahomematic/assets/80967872/1b5cb693-1637-4c2c-b1c1-89acacfa610c">

**Comment by SukramJ** [comment]
Dein log ist voller Kommunikationsfehler u.a. Shelly, Viessmann,…
Ich denke hier liegt kein Problem in der Integration vor.

**Comment by Bimboboy007** [comment]
Wie schon erwähnt durch den erneuten Neustart von HA sind momentan die Probleme beseitigt.
