### ISSUE TITLE
valve_state has "device_class: humidity"

### ISSUE THREAD

**Issue by mist** [SukramJ/hahomematic#1087]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Since one of the latest updates all my hm_cc_rt_dn's valve_state have the device_class humidity which makes all my room humidities messed up.
I think this came with the latest update.

### What version of HomematicIP (local) has the issue?

1.37.3

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic HA-Addon

### Which version of your homematic backend are you running?

3.69.7.20230506

### What hardware are you running for your system?

Pi4

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[config_entry-homematicip_local-032c09f529d56b16f42b4a519d6aa745.json.txt](https://github.com/danielperna84/hahomematic/files/11849819/config_entry-homematicip_local-032c09f529d56b16f42b4a519d6aa745.json.txt)

### Additional information

sensor.hm_cc_rt_dn_peq1192xxx_valve_state

0 	

state_class: measurement
interface_id: RaspberryMatic-BidCos-RF
address: PEQ1192xxx:4
model: HM-CC-RT-DN
entity_type: generic
parameter: VALVE_STATE
function: null
value_state: valid
unit_of_measurement: %
device_class: humidity
friendly_name: Heizkörper Wohnzimmer links Valve State

**Comment by SukramJ** [comment]
Thanks for reporting
