### ISSUE TITLE
entities renamed to "none"

### ISSUE THREAD

**Issue by ciB89** [SukramJ/hahomematic#109]
after the last update (0.9.2) all of my entities got renamed:

![image](https://user-images.githubusercontent.com/20285334/147796461-b2edec7b-0544-4dcf-8ecc-e7f0bbb8e2ef.png)

I used to have only named the device in homematic but not the channels, so I had changed to channel names to match the device name. So this now makes no sense to me at all that my device/channel names are not represented here - I also deleted and readded the integration to see if that would help but it did not.

By the way, I also used Homematic Manager to rename my devices (although the same option is available in the ccu/raspberrymatic)

**Comment by SukramJ** [comment]
Do you have any  errors in the log?
Do you use username/password?

**Comment by SukramJ** [comment]
Please make a screenshot of your entity names in CCU

**Comment by ciB89** [comment]
> Do you have any errors in the log? Do you use username/password?

Yes, I use user authentication. Is that a problem?

![image](https://user-images.githubusercontent.com/20285334/147817882-0234f6f1-c62a-4a0d-b821-7ff947ee0d66.png)

**Comment by ciB89** [comment]
There are some errors in the logs, but not sure if related:

```
Logger: hahomematic.json_rpc_client
Source: /usr/local/lib/python3.9/site-packages/hahomematic/json_rpc_client.py:133
First occurred: 01:48:28 (1150 occurrences)
Last logged: 11:22:12

json_rpc.post: Exception while logging in via JSON-RPC.
NoneType: None
```

```
Logger: hahomematic.json_rpc_client
Source: /usr/local/lib/python3.9/site-packages/hahomematic/json_rpc_client.py:109
First occurred: 01:48:28 (1150 occurrences)
Last logged: 11:22:12

json_rpc.login: Unable to open session: 404
```

```
Logger: hahomematic.json_rpc_client
Source: /usr/local/lib/python3.9/site-packages/hahomematic/json_rpc_client.py:202
First occurred: 01:48:28 (1150 occurrences)
Last logged: 11:22:12

json_rpc_client._post: Status: 404
```

**Comment by SukramJ** [comment]
Authentication is required for json

What did you enter in the config_flow?
Which CCU/RM Version do you use?

**Comment by ciB89** [comment]
I use latest stable of raspberrymatic home assistant addon. I entered the correct authentication data - I mean everything works fine (except for the names). 

 Ah, I remember I left the rpc port blank during setup because I did not know what to put there - could that be the issue?

**Comment by SukramJ** [comment]
Instanzname, host/ip, Username/Password should be enough.
Which Installation method did you use for HA (Hassio, supervised, python)?
Did you open the jsonport (80/443) on raspi-addon config page?

**Comment by SukramJ** [comment]
Try to recreate the integration.

**Comment by ciB89** [comment]
> Instanzname, host/ip, Username/Password should be enough. Which Installation method did you use for HA (Hassio, supervised, python)? Did you open the jsonport (80/443) on raspi-addon config page?

I use supervised. I have not opened port 80/443 - but port 80 is in use anyway by home assistant or am I mistaken?

**Comment by ciB89** [comment]
In the addon page port 80/443 are for webUI - can I simply use a different port and use the same port while setup for the integration?

**Comment by ciB89** [comment]
So I set up the integration again and set the port for the json-rpc to 88 (as I can confirm that http://192.168.x.xx:88/api/homematic.cgi gives me the HomeMatic JSON API)

I appears that the errors in the logs are gone now, the names haven't changed though.

**Comment by ciB89** [comment]
I also had to add the port 88 to the firewall within the CCU, now it works.

**Comment by ciB89** [comment]
One last question: My actual device is called `climate.arbeitszimmer_1` instead of `climate.arbeitszimmer` - why is that? The sensors are correct, e.g. `number.arbeitszimmer_level`

**Comment by SukramJ** [comment]
Port 88 seems to be specific for Raspi-Addon. I don't use the Adddon, but good to know.
climate.arbeitszimmer_1 is correct because the relevant sensors are one channel named Arbeitszimmer:1
I always name channel 1 like the device in my CCU.

**Comment by ciB89** [comment]
> Port 88 seems to be specific for Raspi-Addon. I don't use the Adddon, but good to know. 

I changed the port in the addon from the webUI to 88 since the default here was 80. I assume this also is responsible for the json rpc server.

> climate.arbeitszimmer_1 is correct because the relevant sensors are one channel named Arbeitszimmer:1

But why is the climate device only named like this, but not the sensors? There seems to be some inconsistencies.

**Comment by SukramJ** [comment]
It 's not that simple. Naming could very complex.

Please read the initial paragraph of [Homematic Devices supported by custom entity](https://github.com/danielperna84/hahomematic/wiki/Homematic-Devices-supported-by-custom-entity)
The vast majority of entities is auto-generated, so if a new device arrives on the market, there is no need to update this lib.
The naming strategy tries to exclude channels in naming if possible. Here it is possible to check the corresponding paramsets for duplicates.

More complex entities like climate are custom-entities, which need to be defined out of auto-generated entities.
There could be multiple custom-entities per device like for HmIP-BSM (3 switches = 1pysical + 2virtual) and also the names must be unique.
Custom-Entities have simpler naming strategy: Use the channel name(your case) or use the device name + channel no.
Climate has always one device but esp. HmIP switches and lights have a multiple of 3 different channels.
I don't think we should cover every edge, because this would make the code for naming things complexer.

Just change the channel in CCU (my preference) or edit entity_id and name in HA.
I hope that helps.

**Comment by ciB89** [comment]
I see. Thank you for the explanation.
