### ISSUE TITLE
Send data to HM-OU-CFM-TW via homematicIP(local) does not work

### ISSUE THREAD

**Issue by marc4s** [SukramJ/hahomematic#1093]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I had pyhomematic before and could use the audio output of HM-OU-CFM-TW as expected. I switched recently to homematicIP(local) and I am unable to use it anymore in this way.

my yaml code looks like this
`alias: GefrierschrankTuerAudioAlarm
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.hmip_swdm_gefrierschrank_00155d899120ae
    to: "on"
    for:
      hours: 0
      minutes: 1
      seconds: 15
condition: []
action:
  - service: homematicip_local.set_device_value
    data:
      address: REQ0454943
      channel: 2
      param: SUBMIT
      value: 1,1,108000,002
      value_type: string
mode: single
`

the Channel2 is available as switch. If I switch it on the audiofile 001 will be successful played.

but the yaml code does not work. Thanks for a hint how to fix it.

![Bildschirmfoto vom 2023-07-05 21-04-28](https://github.com/danielperna84/hahomematic/assets/93420756/c23f46f5-12a1-4b06-8481-5dda1a9d5cb2)
![Bildschirmfoto vom 2023-07-05 21-02-41](https://github.com/danielperna84/hahomematic/assets/93420756/2ea436dd-eb5f-4cb1-869b-aa6a021938f1)

### What version of HomematicIP (local) has the issue?

1.37.6

### What was the last working version of HomematicIP (local)?

unknown

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic HA-Addon

### Which version of your homematic backend are you running?

3.69.7.20230626

### What hardware are you running for your system?

homematic yellow

### Which config details do you use

- [X] Username and password
- [X] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by danielperna84** [comment]
Have a look at the [examples](https://github.com/danielperna84/custom_homematic#examples-in-yaml). One notable difference is, that with the new integration you have to use the Home Assistant *device_id* instead of the address in HomeMatic.

**Comment by marc4s** [comment]
the migration did this autmatically? and it also does not work

`alias: GefrierschrankTuerAudioAlarm
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.hmip_swdm_gefrierschrank_00155d899120ae
    to: "on"
    for:
      hours: 0
      minutes: 1
      seconds: 15
condition: []
action:
  - service: homematicip_local.set_device_value
    data:
      device_id: 6729f981cfdc02ff7779375129c399a4
      channel: 2
      param: SUBMIT
      value: 1,1,108000,002
      value_type: string
mode: single
`
![Bildschirmfoto vom 2023-07-05 21-48-52](https://github.com/danielperna84/hahomematic/assets/93420756/5d747712-517e-434e-b281-a539384bd883)

**Comment by marc4s** [comment]
thanks for the examples.
param is now parameter

with this it is working now. thanks a lot!
