### ISSUE TITLE
HM-Sec-RHS - german translation not used

### ISSUE THREAD

**Issue by MasterAndi** [SukramJ/hahomematic#1096]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

The Entity shows the state of the HM-Sec-RHS with the english words: closed, tilted, open and does not use the german translation
"closed": "Geschlossen",  "open": "Offen", "tilted": "Gekippt"

i deleted the device from HA and restarted HA but the state is still in english.

in the developer tools the _device_class_ for the entity is _enum_

### What version of HomematicIP (local) has the issue?

1.38.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.69.7

### What hardware are you running for your system?

Pi3

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[config_entry-homematicip_local-ed210ea08ee453b93ba1fba60ea24ce2.json.txt](https://github.com/danielperna84/hahomematic/files/11981419/config_entry-homematicip_local-ed210ea08ee453b93ba1fba60ea24ce2.json.txt)

### Additional information

![grafik](https://github.com/danielperna84/hahomematic/assets/84271286/eebf0f97-e533-4e7a-abe8-26db0214f5b4)

**Comment by SukramJ** [comment]
Thanks for reporting. Will be fixed in next release.
