### ISSUE TITLE
GET_ALL_SYSTEM_VARIABLES failed

### ISSUE THREAD

**Issue by DennisWilken** [SukramJ/hahomematic#1097]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

The system variables are unavailable in Homeassistant, and I get the error "GET_ALL_SYSTEM_VARIABLES failed: ClientException" (see down below in the logs section)

The error first occurred today after upgrading home assistant from 2023.7.0 to 2023.7.1. I updated Homematic(IP) Local to version 1.38.0 for the 2023.7.0 update. So I assume the last working version was 1.37.6

However, this could be more than an upgrade issue. I have experienced the same error before using 2023.6 or even earlier versions. Apart from the system variables problem, my CCU occasionally crashed without any logs written. Therefore, I moved my CCU and home assistant to Proxmox and started with a fresh CCU installation. Afterwards, everything worked smoothly - until today. I installed Raspberrymatic and Homeassistant in Proxmox via the installation script and haven't made any further changes. All ports are still the default. There are no firewalls or network restrictions. I migrated to the new domain some time ago, as required. In the process of debugging, I deleted the custom component as well as the cache folder from home assistant's config folder - not sure if there are remains of previous versions elsewhere. I set the security settings on the CCU to relax to ensure the CCU is not blocking any connections. 

Please tell me this is just a stupid mistake on my side :-) I appreciate your help!

### What version of HomematicIP (local) has the issue?

1.38.0

### What was the last working version of HomematicIP (local)?

1.37.6

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.69.7

### What hardware are you running for your system?

Proxmox (everything)

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[config_entry-homematicip_local-bf53122f51b383768bb573b2dd7602b8.json.txt](https://github.com/danielperna84/hahomematic/files/11984126/config_entry-homematicip_local-bf53122f51b383768bb573b2dd7602b8.json.txt)

### Anything in the logs that might be useful for us?

```txt
Logger: hahomematic.json_rpc_client
Source: custom_components/homematicip_local/control_unit.py:839
Integration: Homematic(IP) Local (documentation, issues)
First occurred: 12:15:45 PM (731 occurrences)
Last logged: 6:20:46 PM

GET_ALL_SYSTEM_VARIABLES failed: ClientException [('POST: error: {\'name\': \'JSONRPCError\', \'code\': 200, \'message\': \'internal error:\\nlist element in braces followed by "r," instead of space\\n while executing\\n"foreach sv $svList {\\n if { 1 != $first } then { append result "," } else { set first 0 }\\n array set _sv_ $sv\\n set type $_sv_(TYPE)\\n \\n append resu..."\\n (file "/www/api/methods/sysvar/getall.tcl" line 75)\\n invoked from within\\n"source [file join $env(DOCUMENT_ROOT) "api/methods/$method(SCRIPT_FILE)"]"\'}',)]
```

**Comment by SukramJ** [comment]
Sorry, but looks like a problem in your CCU/RM due to the internal error. Better you ask in a HomeMatic/CCU/RM forum.
