### ISSUE TITLE
no Switch entities after update to 2023.7.1

### ISSUE THREAD

**Issue by FranknStone** [SukramJ/hahomematic#1098]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

custom_components.homematicip_local.switch.HaHomematicSwitch'>) is implicitly using device name by not setting its name. Instead, the name should be set to None, please report it to the custom integration author.

This message i found in ha log.
No switch entities are found in ha with homematic but other entities from homematic are working fine.

### What version of HomematicIP (local) has the issue?

newest with ha 

### What was the last working version of HomematicIP (local)?

2023.7.1

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

	3.69.7.20230626

### What hardware are you running for your system?

Pi3

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.components.binary_sensor
Source: custom_components/homematicip_local/generic_entity.py:147
Integration: Binärsensor (documentation, issues) 
First occurred: 7. Juli 2023 um 17:19:20 (2 occurrences) 
Last logged: 20:22:36

Error adding entities for domain binary_sensor with platform homematicip_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 504, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 579, in _async_add_entity
    entity_name = entity.name
                  ^^^^^^^^^^^
  File "/config/custom_components/homematicip_local/generic_entity.py", line 147, in name
    return entity_name.replace(
           ^^^^^^^^^^^^^^^^^^^^
TypeError: replace() argument 2 must be str, not UndefinedType
```

**Comment by SukramJ** [comment]
Update the integration
