### ISSUE TITLE
HmIP-WKP not working as expected

### ISSUE THREAD

**Issue by eikowagenknecht** [SukramJ/hahomematic#1101]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

So I now own a HmIP-WKP and I suspect it is not fully supported by this integration yet. I'm happy to help with this and do tests for example.

After setting it up in the CCU (includig a "dummy" program to make sure the key presses are passed to the addon), I see the following behavior in Home Assistant:

- When I enter a valid code and then press the "lock" button , the corresponding "lock" entity changes to True and stays there forever
- When I do this again, nothing changes

The same goes for "unlock". So after unlocking and locking once, the state looks like this:
![image](https://github.com/danielperna84/hahomematic/assets/1475672/e85dda86-f4b0-47c6-8c2e-d873782bd7f4)

So I can not act on the 2nd, 3rd, ... keypress of a type because nothing changes any more.

Even in devtools, no changes can be seen after the 1st press:

![image](https://github.com/danielperna84/hahomematic/assets/1475672/0c46ffaf-a1fe-48cc-9b17-b6205c741773)

The device entity also can not react to this in automations because of this.

Also, there are no events. I think it would be nice to have events to react to instead of entity states (just like the other hmIP entities send something on homematic.keypress when pressed).

### What version of HomematicIP (local) has the issue?

1.39.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic HA-Addon

### Which version of your homematic backend are you running?

3.69.7.20230626

### What hardware are you running for your system?

Pi4

### Which config details do you use

- [ ] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[config_entry-homematicip_local-2565974ba7d32a6a80e7f2f4a43e1f7e.json.txt](https://github.com/danielperna84/hahomematic/files/12024847/config_entry-homematicip_local-2565974ba7d32a6a80e7f2f4a43e1f7e.json.txt)

**Comment by SukramJ** [comment]
Der HmIP-WKP ist aktuell nur generisch in der Integration verfügbar.
Wiederholte Nachfragen bei WKP Benutzern haben leider nicht dazu geführt, das ich die benötigten Gerätebeschreibungen zum Testen bekommen habe. Also fangen wir damit mal an.
Exportiere bitte die Gerätebeschreibungen mit dem [Export Service](https://github.com/danielperna84/custom_homematic#homematicip_localexport_device_definition) und erstelle dazu am Besten einen PR im Repo [pydevcccu](https://github.com/danielperna84/pydevccu).
Dann kann ich mir das Gerät mal anschauen.

**Comment by eikowagenknecht** [comment]
Gerne, die Daten bekommst du gleich!

**Comment by eikowagenknecht** [comment]
https://github.com/danielperna84/pydevccu/pull/43

**Comment by SukramJ** [comment]
Es gibt zwei neue Events: `PRESS_LOCK` und `PRESS_UNLOCK`. Die entsprechenden Entitäten werden dann verschwinden, und statt dessen sind dann Events nutzbar.
Den Paramater `SABOTAGE_STICKY` werde ich entfernen.

Was ist mit den folgenden Parametern:

- Blocked Permanent
- Blocked Temporary
- Code Id
- Code State
- User Authorization XXX

Werden diese benötigt, und wenn ja welche `device_class` sollte verwendet werden?
[Liste der binary_sensor device classes](https://developers.home-assistant.io/docs/core/entity/binary-sensor#available-device-classes)
[Liste der sensor device classes](https://developers.home-assistant.io/docs/core/entity/sensor#available-device-classes)

**Comment by eikowagenknecht** [comment]
Hier eine kurze Beschreibung der Parameter:
- SABOTAGE_STICKY gibt an, ob es einen Sabotageversuch gab (Abnehmen / Öffnen des Keypads). Ich würde ihn drin lassen. Wenn es einen Sabotageversuch gab, muss das Keypad erst in der WebUI wieder freigeschaltet werden, damit es wieder genutzt werden kann. Wenn das auch über HA gehen könnte: Prima. Wenn nicht, kein großer Verlust, da es hoffentlich nicht oft vorkommt.
- Blocked Temporary wird nach einer einstellbaren Zahl von Fehleingaben gesetzt und sollte dann nach einiger Zeit wieder zurückgesetzt werden.
- Blocked Permanent wird nach noch mehr Fehleingaben gesetzt (auch einstellbar in WebUI), hier muss dann ebenfalls über die WebUI wieder entsperrt werden.
- User Authorization XXX. Man kann 8 User anlegen und diese über die WebUI aktivieren / deaktivieren. Das kann auch automatisch über das Wochenprogramm festlgelegt werden, so dass User nur zu bestimmten Zeiten Zugang haben sollen. Diese Attribute spiegeln wieder, ob der entsprechende User gerade aktiviert oder deaktiviert ist.
- Code Id und Code State: Scheint eine Beschreibung des letzten Status des Keypads zu sein.Bisher habe ich die IDs gesehen:
  - Nach längerer Wartezeit: 32 / idle
  - Druck auf Sperren / Entsperren ohne vorherige PIN Eingabe: 3 / known_code_id_received
  - Falscheingabe: 32 / unknown_code_detected
  - Nach korrekter PIN Eingabe, egal ob lock oder unlock: <User Nummer (1-8)> / known_code_id_received

Zu den Device Classes:
- Blocked Temporary / Blocked Permanent / Sabotage: Hier könnte BinarySensorDeviceClass.PROBLEM oder BinarySensorDeviceClass.TAMPER passen.

Für die anderen konnte ich keinen passenden Eintrag in den Listen sehen,

**Comment by SukramJ** [comment]
Probiere bitte die Version 1.39.1b0.

**Comment by eikowagenknecht** [comment]
Sieht super aus:

![image](https://github.com/danielperna84/hahomematic/assets/1475672/871b1702-45c6-4398-8953-4c0c4dab1536)

![image](https://github.com/danielperna84/hahomematic/assets/1475672/ae106c97-a8e8-410e-9ca1-8a9fa5270ea5)

![image](https://github.com/danielperna84/hahomematic/assets/1475672/2e3b73b9-5cb3-4683-9d19-0e6c636c7fa5)

Vielen Dank für die wieder einmal superschnelle Anpassung!

**Comment by SukramJ** [comment]
Gern geschehen.
Macht es ggf. Sinn Entitäten noch zwischen Sensor, Konfiguration und Diagnose zu verschieben?

**Comment by SukramJ** [comment]
Ich denke das Ticket kann geschlossen werden

**Comment by eikowagenknecht** [comment]
> Gern geschehen. Macht es ggf. Sinn Entitäten noch zwischen Sensor, Konfiguration und Diagnose zu verschieben?

Kann ich tatsächlich schwer einschätzen, ich habe bisher keinen offiziellen Guide o.ä. dazu gesehen und den Eindruck, dass jede Integration das unterschiedlich handhabt. Mir persönlich ist die Ansicht nicht sonderlich wichtig, da ich entweder Automatisierungen oder gecustomizete UI Ansichten nutze.
