### ISSUE TITLE
Illuminance sensor of HM-Sen-MDIR-WM55 shown as humidity due to missing device_class attribute

### ISSUE THREAD

**Issue by Athemis** [SukramJ/hahomematic#1104]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

The state of the illuminance sensor of my HM-Sen-MDIR-WM55 is shown as humidity, probably by the absence of any `device_class` attribute instead of `device_class=illuminance` (see below).

### What version of HomematicIP (local) has the issue?

1.39.1

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.69.7.20230626

### What hardware are you running for your system?

Pi4 (HA OS); Pi3B+ (RaspberryMatic)

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[config_entry-homematicip_local-54c8423f1aef0047d4b94e7082449179.json.txt](https://github.com/danielperna84/hahomematic/files/12042908/config_entry-homematicip_local-54c8423f1aef0047d4b94e7082449179.json.txt)

### Additional information

```state_class: measurement
interface_id: RaspberryMatic-BidCos-RF
address: PEQ1640574:3
model: HM-Sen-MDIR-WM55
entity_type: generic
parameter: BRIGHTNESS
function: null
value_state: valid
icon: mdi:invert-colors
friendly_name: HM-Sen-MDIR-WM55 PEQ1640574 Helligkeit

**Comment by SukramJ** [comment]
Es gibt keine Geräteklasse für Helligkeit in HA und Helligkeit (Brightness /keine Einheit) ist nicht dasselbe wie Beleuchtungsstärke (Illuminance/Einheit Lux).
Der Wert wird auch nicht integrationsseitig als Humidity angezeigt.
Sollte dir das Icon nicht gefallen, so kannst du das in der Benutzeroberfläche ändern.

**Comment by Athemis** [comment]
Ah, ok. War mir nicht bewusst, dass der gar keine Lux ausgibt. Bin nur drüber gestolpert, dass ich den Sensor in einem Blueprint nicht einbinden konnte, der einen Helligkeitssensor für die Lichtsteuerung nutzt und entsprechend die Sensoren nach Geräteklasse filtert. Da taucht der HM-Sensor dann natürlich nicht auf. Trotzdem danke!
