### ISSUE TITLE
Homegear receives no events

### ISSUE THREAD

**Issue by Ra72xx** [SukramJ/hahomematic#1125]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Since a few days, with no change in configuration that I' aware of, I'm always getting the error:

`HOMEMATICIP_LOCAL-Ping/Pong Mismatch on Interface: There is a mismatch between send ping events and received pong events for HA instance Homegear. Looks like you are running multiple instances of HA with the same instance name configured for this integration. Re-add one instance! Otherwise one HA instance will not receive update events from your CCU.
`

The setup is:
- Homeassistant in podman container, host networking mode.
- Homegear in podman container, exposed port 2001 (I'm only using classic Homematic)

I tried:
- Using Homegear container with host network mode
- Experimenting with callback port setting (lcoalhost, hostname, host.containers.internal, etc.)
- Uninstalling and reinstalling the integration
- Restarting everything, from containers to the whole server

While uninstalling and reinstalling, I also found out that the entities are still stored somehow in the entity registry of HA. And when reinstalling, only hte devices get their names from Homegear, the entities are named after their serial number. I don't know if this is intended or a side effect of the error above.

### What version of HomematicIP (local) has the issue?

1.39.2

### What was the last working version of HomematicIP (local)?

unknown, didn't notice because out of heating season

### What type of installation are you running?

Home Assistant Container

### What type of installation are you running for your homematic backend?

Homegear

### Which version of your homematic backend are you running?

last current stable

### What hardware are you running for your system?

standard x86-64 PC Ubuntu 23.04

### Which config details do you use

- [ ] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Thanks for reporting.
I don't use Homegear so it's hard to support for me.
I remove ping/pong for Homegear for the next release.

Regarding the left over entities:
I've never had this problem, and cannot reproduce it.

Try this:
- Remove the Integration
- Check and delete left over entities.
- ReAdd the integration.
- Afterwards a remove of the integration should have no left overs.

**Comment by Ra72xx** [comment]
Well, that does not really help:
Removing the Ping/Pong does not really help, because the problem is that Homeassistant does not receive any more entity updates.
Deleting left over entities does not really work, because, there are literally hundreds remaining in the .storage-folder, I don't know how to remove them all. I see you mean a "double removal"?! 
I guess the leftover entites are the problem, because e.g. I have several "Sv_socketpath" entries in the files below .storage, but I don't know how they were created and how to get rid of them.

**Comment by SukramJ** [comment]
> does not receive any more entity updates.

Then you should write, that you instance does not receive updates!
The ping/pong mechanism is an additional check.

Can't you delete the entities via the HA UI entity overview? If necessary, deactivated entities must first be activated before they can be deleted.

Entites assigned to a running integration will not be removed.

**Comment by SukramJ** [comment]
Some explaining screenshots might be helpful to see whats in your .storage folder.

**Comment by Ra72xx** [comment]
I removed the complete integration several times. I was also able to remove stale entries from the page "developper tools -> statistics", but the different config files in the folder .storage did always still contain lots data about the integration, even after it was removed. 
Upon finding several similiar entries for "Sv_socketpath" in these files, I speculate that some old config remnants interfere with every new installation. As there are hundreds of entries regarding homematicip_local in different files in .storage even after it has been removed, I'd like to avoid manually deleting all this stuff, chance of breaking the whole integration is to big.

**Comment by SukramJ** [comment]
1. statistic entries are handled by HA and not by this integration.
2. Which files? Relevant files are only: core.device_registry, core.entity_registry, core.config_entries

**Comment by SukramJ** [comment]
And also the deleted sections in these files don't matter.

**Comment by schneevongestern** [comment]
Hello

I have a similar issue. Made today the setup of a new system. I was able to
setup the service but when finishing everything  no entities are taken
over. Made several times a new setup but always the same result. Attached
you the log maybe it is of use in that matter

Best regards

SukramJ ***@***.***> schrieb am Fr., 28. Juli 2023, 15:19:

**Comment by SukramJ** [comment]
@schneevongestern related? Please open a separate issue.

**Comment by Ra72xx** [comment]
When using homegear, which servers (rpcservers.conf) have to be enabled? I currently have all server types (JSON, RPC, REST, Websockets, Web UI) running on port 2001, but I think most of them are not really needed?

**Comment by SukramJ** [comment]
We only use 2001 for Homegear.

**Comment by Ra72xx** [comment]
But I can run different homegear servers on this port - see above. I'd like to disable unneeded homegear server "variants" in order to rule out interferences.
https://github.com/Homegear/Homegear/blob/master/misc/Config%20Directory/rpcservers.conf

**Comment by SukramJ** [comment]
I can't help you with homegear because I don't use it myself.
We use XmlRPC on 2001.

**Comment by stickybyte** [comment]
I guess homegear uses the same ports for XML like every CCU.
I face the same problem, that devices do not get updates after this messages appears using RaspberryMatic in an VM.

**Comment by Ra72xx** [comment]
For me it's working again right now (fingers crossed), but I don't really understand what has happened.

**Comment by SukramJ** [comment]
@stickybyte please fill out your own issue template. Otherwise i don't have an information about your environment.
