### ISSUE TITLE
Since update to 1.40.0 no connection to external RaspberryMatic CCU3 possible

### ISSUE THREAD

**Issue by luftdieb** [SukramJ/hahomematic#1137]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Since the update to 2023.8.1, I'm loosing complete connection to CCU and therefore no sensors are available. HomeAssistant is showing constantly these errormessages :
HOMEMATICIP_LOCAL-Interface not reachable (No connection to interface HAR-HM-CCU3-BidCos-RF / No connection to interface HAR-HM-CCU3-HmIP-RF)
Reboot of Home Assistant (Coldstart) and RaspberryMatic doesn't solve the issue.

Is there a chance to go back to the previous version?

### What version of HomematicIP (local) has the issue?

2023.8.1

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.69.7.20230626

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [X] Username and password
- [X] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.8.1",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.4",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "6.1.39",
    "supervisor": "2023.07.1",
    "host_os": "Home Assistant OS 10.4",
    "docker_version": "23.0.6",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "miele": {
      "version": "v2021.10.12",
      "requirements": [
        "requests_oauthlib>=1.3.0"
      ]
    },
    "solis": {
      "version": "3.4.1",
      "requirements": []
    },
    "solax_modbus": {
      "version": "2023.08.3",
      "requirements": [
        "pymodbus>=2.5.3",
        "pymodbus<=3.3.1"
      ]
    },
    "average": {
      "version": "2.3.0",
      "requirements": []
    },
    "wundergroundpws": {
      "version": "2.0.2",
      "requirements": []
    },
    "irrigation_unlimited": {
      "version": "2023.8.0",
      "requirements": [
        "crontab"
      ]
    },
    "hacs": {
      "version": "1.32.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "solarman": {
      "version": "1.0.0",
      "requirements": [
        "pyyaml"
      ]
    },
    "nodered": {
      "version": "2.1.0",
      "requirements": []
    },
    "homematicip_local": {
      "version": "1.40.0",
      "requirements": [
        "hahomematic==2023.8.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "homematicip_local",
    "name": "Homematic(IP) Local",
    "codeowners": [
      "@danielperna84",
      "@SukramJ"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/danielperna84/custom_homematic",
    "homekit": {},
    "integration_type": "hub",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/danielperna84/hahomematic/issues",
    "loggers": [
      "hahomematic"
    ],
    "requirements": [
      "hahomematic==2023.8.0"
    ],
    "ssdp": [
      {
        "manufacturer": "EQ3",
        "manufacturerURL": "http://www.homematic.com"
      }
    ],
    "version": "1.40.0",
    "zeroconf": [],
    "is_built_in": false
  },
  "data": {
    "config": {
      "entry_id": "b25d281df48197b7c59e6cff8e8118c4",
      "version": 2,
      "domain": "homematicip_local",
      "title": "HAR-HM-CCU3",
      "data": {
        "instance_name": "HAR-HM-CCU3",
        "host": "192.168.1.11",
        "username": "**REDACTED**",
        "password": "**REDACTED**",
        "tls": true,
        "verify_tls": false,
        "sysvar_scan_enabled": true,
        "sysvar_scan_interval": 30,
        "callback_host": null,
        "callback_port": null,
        "json_port": null,
        "interface": {
          "HmIP-RF": {
            "port": 42010
          },
          "BidCos-RF": {
            "port": 42001
          }
        },
        "enable_system_notifications": true
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "ssdp",
      "unique_id": "unknown",
      "disabled_by": null
    },
    "platform_stats": {},
    "devices": [],
    "system_information": {
      "available_interfaces": [],
      "auth_enabled": null,
      "https_redirect_enabled": null,
      "serial": null
    }
  }
}

### Anything in the logs that might be useful for us?

```txt
2023-08-05 19:50:28.307 DEBUG (MainThread) [hahomematic.xml_rpc_proxy] __ASYNC_REQUEST: ('system.listMethods', ())
2023-08-05 19:50:28.344 DEBUG (MainThread) [hahomematic.xml_rpc_proxy] __ASYNC_REQUEST: ('getVersion', ())
2023-08-05 19:50:28.506 DEBUG (MainThread) [hahomematic.json_rpc_client] POST method: Interface.listInterfaces
2023-08-05 19:50:28.506 DEBUG (MainThread) [hahomematic.json_rpc_client] GET_AVAILABLE_INTERFACES: Getting all available interfaces
2023-08-05 19:50:28.662 DEBUG (MainThread) [hahomematic.json_rpc_client] POST method: CCU.getAuthEnabled
2023-08-05 19:50:28.662 DEBUG (MainThread) [hahomematic.json_rpc_client] GET_AUTH_ENABLED: Getting the flag auth_enabled
2023-08-05 19:50:28.817 DEBUG (MainThread) [hahomematic.json_rpc_client] POST method: CCU.getHttpsRedirectEnabled
2023-08-05 19:50:28.817 DEBUG (MainThread) [hahomematic.json_rpc_client] GET_HTTPS_REDIRECT_ENABLED: Getting the flag https_redirect_enabled
2023-08-05 19:50:29.012 DEBUG (MainThread) [hahomematic.json_rpc_client] POST_SCRIPT: Method: ReGa.runScript [get_serial.fn]
2023-08-05 19:50:29.012 DEBUG (MainThread) [hahomematic.json_rpc_client] GET_SERIAL: Getting the backend serial
2023-08-05 19:50:29.073 DEBUG (MainThread) [hahomematic.xml_rpc_proxy] __ASYNC_REQUEST: ('ping', ('HAR-HM-CCU3-HmIP-RF',))
2023-08-05 19:50:29.103 DEBUG (MainThread) [hahomematic.client] CHECK_CONNECTION_AVAILABILITY failed: AuthFailure [(<ProtocolError for 192.168.1.11:42010/RPC2: 401 Unauthorized>,)]
2023-08-05 19:50:29.104 WARNING (MainThread) [hahomematic.central_unit] CREATE_CLIENTS failed: No connection to interface HAR-HM-CCU3-HmIP-RF [('No connection to HAR-HM-CCU3-HmIP-RF',)]
2023-08-05 19:50:29.108 DEBUG (MainThread) [hahomematic.central_unit] CREATE_CLIENTS failed for HAR-HM-CCU3
```

**Comment by SukramJ** [comment]
Die von die verwende Version der Integration ist die 1.40.0. Die 2023.8.1 ist eine nicht veröffentlichte Version der backend Bibliothek HaHomemtatic.

> failed: AuthFailure [(<ProtocolError for 192.168.1.11:42010/RPC2: 401 Unauthorized>,)]

Wie im Log zu sehen ist hat die Integration ein Problem mit der Authentifizierung. Also bitte prüfen, ob das Passwort den benötigten Regeln ([siehe Doku](https://github.com/danielperna84/custom_homematic#authentication)) entspricht, und ggf. nochmal in CCU und Integration setzen.

> Is there a chance to go back to the previous version?

Ja, über HACS.

**Comment by SukramJ** [comment]
Und bitte mal prüfen, ob Authentifizierung in der CCU aktiviert ist.

**Comment by luftdieb** [comment]
Der Downgrade über HACS hat problemlos geklappt und jetzt funktioniert auch die Kommunikation wieder.
Das Password besteht nur aus Buchstaben und wurde die letzten Wochen nicht geändert. Login mit dem Benutzer über die Homematic UI funktioniert. Ich befürchte eine Fehlwirkung in der Version 1.40.0. 
Die vorherige Version 1.39.2 funktioniert einwandfrei.

**Comment by SukramJ** [comment]
In der Fehlersuche hilft dein Downgrade leider nicht weiter.
Bei anderen Benutzern funktioniert die 1.40.0 problemlos.

**Comment by luftdieb** [comment]
OK. Wie kann ich bei der Fehlersuche behilflich sein? Alle Logfiles, die ich finden konnte habe ich im 1. Post beigefügt.
Die Authentifizierung im RasperryMatic ist aktiv.

**Comment by SukramJ** [comment]
Ich befürchte das das Problem von deiner Umgebung abhängig ist, also beim nächsten Update nicht behoben ist!

Welcher Benutzer wird für die Anmeldung verwendet?
Hat dieser Benutzer Administrationsrechte?
Ist Authentifizierung in der CCU aktiviert?  Ja
Tritt das Problem nur mit aktivierter Authentifizierung auf, oder auch ohne?
Ist der Port 443 in der CCU offen? 42010 und 42001 sollten ja offen sein.
Funktioniert die 1.40.0 wenn TLS in der Integration deaktiviert wird?

**Comment by luftdieb** [comment]
Ich habe mir noch mal die Anforderungen an den Homematic Benutzer durchgelesen... Dabei ist mir aufgefallen, dass der Benutzer Adminrechte benötigt. Bis einschließlich Version 1.39.2 war dies nicht erforderlich.
Ich habe dem Benutzer die Admin Rechte zugewiesen und bin wieder auf 1.40.0 gewechselt und siehe da, es geht. 
Aber warum werden jetzt Admin Rechte benötigt? Aus Sicherheitsgründen würde ich das gerne wieder rückgängig machen.
Aber trotzdem erst mal danke für die Hilfestellung!

**Comment by SukramJ** [comment]
Adminrechte wurden wurden für die JSONRPC API schon immer benötigt.
Warum es bei manchem Benutzer bzw. Bei manchem API Call auch ohne ging kann ich nicht sagen.

**Comment by SukramJ** [comment]
Ich schau mal, ob sich künftig was an den Rechten ändern kann.
