### ISSUE TITLE
HmIP-MOD-HO: Unknown Parameter value for value key: ERROR_CODE

### ISSUE THREAD

**Issue by ce3a** [SukramJ/hahomematic#1138]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

The following error is shown in the Home Assistant Core log:

```
DEBUG (MainThread) [hahomematic.client] GET_VALUE: channel_address <device_id>:1, parameter ERROR_CODE, paramset_key, VALUES, source:hm_init
DEBUG (MainThread) [hahomematic.client] GET_VALUE failed with ClientException [(<Fault -5: 'Unknown Parameter value for value key: ERROR_CODE'>,)]: <device_id>:1, ERROR_CODE, VALUES
```

The device is a **HmIP-MOD-HO** (Modul für Hörmann-Antriebe).

### What version of HomematicIP (local) has the issue?

1.40.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.69.7.20230626

### What hardware are you running for your system?

Pi4

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Einige Parameter können nicht gelesen, obwohl das möglich sein sollte. Das ist aber kein Problem, und daher wird das auch unter DEBUG geloggt.
