### ISSUE TITLE
HomeMatic Switch entity disappeared in homeassistant

### ISSUE THREAD

**Issue by obermstre** [SukramJ/hahomematic#1140]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Since updating homeassistant to version 2023.8.1  today the entity "switch" of my homematic powermeter hm_es_pmsw1_pl is not available.

The ui states:
"Entität nicht verfügbar: switch.hm_es_pmsw1_pl_keq0968444_state"

The protokoll states:

```
Logger: homeassistant.components.switch
Source: custom_components/homematicip_local/generic_entity.py:147
Integration: Schalter 
First occurred: 16:38:25 (3 occurrences)
Last logged: 16:47:50

Error adding entities for domain switch with platform homematicip_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 585, in _async_add_entity
    entity_name = entity.name
                  ^^^^^^^^^^^
  File "/config/custom_components/homematicip_local/generic_entity.py", line 147, in name
    return entity_name.replace(
           ^^^^^^^^^^^^^^^^^^^^
TypeError: replace() argument 2 must be str, not UndefinedType
```
All other entities are working as expected.

### What version of HomematicIP (local) has the issue?

1.35.0

### What was the last working version of HomematicIP (local)?

1.35.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic HA-Addon

### What hardware are you running for your system?

x64

### Which config details do you use

- [ ] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [x] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
>  I am running the latest version of the custom_component (and Home Assistant)

Also 1.35.0 ist nun wirklich nicht die aktuelle Version.
Hast Du eine Idee warum das oben abgefragt wird?

**Comment by obermstre** [comment]
> > I am running the latest version of the custom_component (and Home Assistant)
> 
> Also 1.35.0 ist nun wirklich nicht die aktuelle Version. Hast Du eine Idee warum das oben abgefragt wird?
ich habe keien Idee, warum das abgefragt wird.

Ich dachte es wäre die aktuellste, weil mir von HA kein Update vorgeschlagen wurde.
Nach einem manuellen update über HACS funktioniert es nun wieder :-)
