### ISSUE TITLE
HmIP-FROLL ch:3 / Status vermisst

### ISSUE THREAD

**Issue by klingbing** [SukramJ/hahomematic#1151]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Vielen Dank für eure Arbeit an dieser Integration!
Ich vermisse den Status Kanal / Channel 3 des og. Aktors. Die versteckten und deaktivierten Entitäten habe ich bereits durchsucht: nix. 
Kann dieser Kanal „aktiviert“ werden?

### What version of HomematicIP (local) has the issue?

1.40.1

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.69.7.20230626

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [ ] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Da der Kanalstatus (4,5,6) bei den Broll/Froll/... nicht sauber umgesetzt wird (kann springen), verwendet die Integration für den ersten Aktorkanal (4) den Status von Kanal 3. Die weiteren virtuellen Kanäle verwenden jeweils ihren eigenen Status.
