### ISSUE TITLE
Home Assistant only Displays a Battery and Update Entity for the HmIP-SWSD Smoke detector

### ISSUE THREAD

**Issue by Kekskruemel** [SukramJ/hahomematic#1173]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hi,

all is working fine, except the HmIP-SWSD Smoke detector.

Home Assistant only Displays a Battery and Update Entity for the HmIP-SWSD Smoke detector.

![grafik](https://github.com/danielperna84/hahomematic/assets/7548088/a581a9fc-bf9f-4ad7-991a-f392b7ac6d95)

Thx & Greetings

### What version of HomematicIP (local) has the issue?

1.40.1

### What type of installation are you running?

Home Assistant Supervised

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.71.12

### What hardware are you running for your system?

Pi4

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[config_entry-homematicip_local-6a2c354121519c025a50246d744507bd.json.txt](https://github.com/danielperna84/hahomematic/files/12468388/config_entry-homematicip_local-6a2c354121519c025a50246d744507bd.json.txt)

**Comment by SukramJ** [comment]
> I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)

Please **really** read the docs. You have to [activate](https://github.com/danielperna84/custom_homematic#deactivated-entities) the siren.
