### ISSUE TITLE
transition funktioniert mit der Version 1.40.2b7 nicht mehr

### ISSUE THREAD

**Issue by stuckis6er** [SukramJ/hahomematic#1175]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Seit dem Update auf die Version 1.40.2b7 funktioniert das ein noch das ausschalten mit angegebener transition.

### What version of HomematicIP (local) has the issue?

1.40.2b7

### What was the last working version of HomematicIP (local)?

1.40.2b6

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.69.7.20230626

### What hardware are you running for your system?

Generica x86

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Ohne das relevante Gerät ist die Info noch nicht hilfreich.

**Comment by SukramJ** [comment]
Und häng bitte den Service der Automation an, mit dem Du die Transition durchführst.

**Comment by SukramJ** [comment]
Hab den Fehler gefunden, bitte beim nächste mal mehr relevante Informationen mit geben:
- Welches Gerät ist betroffen-
- Was wurde gemacht
- Log Dateien

Das würde mir die Arbeit erleichtern.
Vielen Dank.

**Comment by stuckis6er** [comment]
Klar, werde ich nächstes Mal machen. Schön das Du trotzdem den Fehler gefunden hast.

**Comment by SukramJ** [comment]
Sollte mit der 1.40.2b8 wieder funktionieren.
