### ISSUE TITLE
not connecting to Raspberrymatic after addon update

### ISSUE THREAD

**Issue by KoMa1012** [SukramJ/hahomematic#1180]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

No connection to any homematic IP device after update of Homematic IP Local. Switches etc. are "unavailable", every entity shows "This entity is no longer being provided by the homematicip_local integration. If the entity is no longer in use, delete it in settings."

### What version of HomematicIP (local) has the issue?

1.40.1

### What was the last working version of HomematicIP (local)?

not sure, but might have been 1.40.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.71.12.20230826

### What hardware are you running for your system?

VM on unraid

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Anything in the logs that might be useful for us?

```txt
Logger: hahomematic.central_unit
Source: custom_components/homematicip_local/control_unit.py:140
Integration: Homematic(IP) Local ([documentation](https://github.com/danielperna84/custom_homematic), [issues](https://github.com/danielperna84/hahomematic/issues))
First occurred: 08:16:42 (6 occurrences)
Last logged: 08:18:14

CREATE_CLIENTS failed: No connection to interface meine-VirtualDevices [POST method 'CCU.getAuthEnabled' failed: access denied ("ADMIN" needed 2)]
CREATE_CLIENTS failed: No connection to interface meine-BidCos-RF [POST method 'CCU.getAuthEnabled' failed: access denied ("ADMIN" needed 2)]
CREATE_CLIENTS failed: No connection to interface meine-HmIP-RF [POST method 'CCU.getAuthEnabled' failed: access denied ("ADMIN" needed 2)]
```

### Additional information

Information in Settings:
```
Interface meine-VirtualDevices not reachable
No connection to interface meine-VirtualDevices.

This Integration tries an automatic reconnect.

Check the Home Assistant log files for more details.
Additional Info, my raspberrymatic User isn't called "admin", I'm using a different user (not admin) for the addon. But I also tried "admin" with the same behavior.

**Comment by SukramJ** [comment]
Give your user the admin **role** (Berechtigunsstufe).

**Comment by KoMa1012** [comment]
Thank you, that fixed it!

What's the reason behind it needing admin rights not and not before?
Additionally, I don't like the idea of a service having admin rights at a server, is there a solution so that the integration again only acts as a normal user with only "switching" rights, but not editing all the stuff of raspberrymatic?

**Comment by SukramJ** [comment]
[See](https://github.com/danielperna84/hahomematic/issues/1143#issuecomment-1676902463)

> is there a solution so that the integration again only acts as a normal user with only "switching" rights, but not editing all the stuff of raspberrymatic?

No.
