### ISSUE TITLE
HmIPW-WRC6 Channel 7 has gone missing

### ISSUE THREAD

**Issue by Xsez** [SukramJ/hahomematic#1183]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [x] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Thanks for updating the WRC6. Now the lights can be easily controlled from the UI. This will make things much easier to automate instead of using COMBINED_PARAMETER command.

Unfortunately, channel 7 (the first light, top left) entity is not available anymore. Channel 8-13 are available and work perfectly.

![image](https://github.com/danielperna84/hahomematic/assets/8041173/7c05357a-4f54-4951-b1d1-9a2e7a3b4aa3)

### What version of HomematicIP (local) has the issue?

1.41.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which config details do you use

- [ ] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
This is the result of `Extend HmIPW-WRC6 implementation`.
This entity is a left over and can be deleted.

**Comment by Xsez** [comment]
Im sorry, but I don't understand?

Channel 7 is a valid channel. It's the individual control for the top left LED. It should not be disabled and is not a leftover.

What might be confusing, is that there are seven channels for the LEDs. Channel 7-12 control the individual LEDs. Channel 13 can control all LEDS at once, but only if they have their individual channels turned off.
Screenshot from CCU:
![image](https://github.com/danielperna84/hahomematic/assets/8041173/de56df61-7d0f-45c0-8a97-d6e258fedddb)

**Comment by SukramJ** [comment]
Ok, good info.
This has never been an [issue](https://github.com/danielperna84/hahomematic/discussions/1163) in this discussion.
I' ll re add this.

**Comment by FlowFrank** [comment]
Ich kann das Problem leider nur bestätigen.
Bin dem ursprünglichen Beitrag mit der Entwicklung auch gefolgt und habe ebenfalls ein wenig getestet. Ich habe aber niemals die LED links oben benutzt, weil ich die aktuell über die CCU in jedem Raum anderweitig verwende. ![image](https://github.com/danielperna84/hahomematic/assets/56410024/d61196e0-06e8-4629-826b-c9f71009ac0b)
