### ISSUE TITLE
Configuration pending

### ISSUE THREAD

**Issue by Stephan-4711** [SukramJ/hahomematic#1187]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I'm not able to add the integration.
The message which is shown while trying to add the Integration is:
Bitte warten, Konfigurationsassistent für homematicip_local wird gestartet

I waited already over 20min.
I also can't see anything in the HomeAsssistant log files.

### What version of HomematicIP (local) has the issue?

newest

### What was the last working version of HomematicIP (local)?

no one

### What type of installation are you running?

Home Assistant Supervised

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### What hardware are you running for your system?

Homeassistant RPI3-Arm64 bit installation

### Which config details do you use

- [ ] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
> while trying to add the Integration

This is a problem with Home Assistant before the integration starts. Since I also can't reproduce the problem myself, I can't help.
Maybe a restart of HA is helpful.
