### ISSUE TITLE
No brightness level entity available for HM-LC-Dim1TPBU-FM, -Dim1T-CV and -Dim1PWM-CV

### ISSUE THREAD

**Issue by DirkHBo** [SukramJ/hahomematic#1192]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I am using HA just for serveral weeks and noticed a few days ago that there is a working integration for homematic. After unconfiguring the deprecated core homematic installation, I first did install 1.41.0 of Homematic(IP) local via HACS and everything came up. While trying around I noticed that there is no possibilty to get or change the brightness level of those three dimmers.
I tried removing the integration and reinstalling it, without a change. At last I installed 1.41.1b1 (just in case....), but this did not bring up the level entity as well.
For the HM-LC-DIM1T-CV (and the others are pretty similar) these status attributes are shown:
`supported_color_modes:
  - brightness
interface_id: Magellan-CCU-BidCos-RF
address: LEQ0282XXX:1
model: HM-LC-Dim1T-CV
entity_type: custom
value_state: valid
friendly_name: OG-BAD-DIM
supported_features: 32`
Here is an overview of the datapoints directly out of homematic:
[HM-devices.txt](https://github.com/danielperna84/hahomematic/files/12643607/HM-devices.txt)

Everything else works fine, as far as I can tell right now. 👍 

### What version of HomematicIP (local) has the issue?

1.41.1b1

### What was the last working version of HomematicIP (local)?

none

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.71.12.2023082

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[config_entry-homematicip_local-8d02347b40e23beabd6cea4a4ac402b2.json.txt](https://github.com/danielperna84/hahomematic/files/12643618/config_entry-homematicip_local-8d02347b40e23beabd6cea4a4ac402b2.json.txt)

### Additional information

Screenshot of one of those dimmers as device.
![image](https://github.com/danielperna84/hahomematic/assets/47914186/87101d67-5875-4479-aabc-f30c584b9047)

**Comment by SukramJ** [comment]
No sure if i understood your problem.
There is no need for a dedicated brightness entity.
The brighness is part of the light entity and can be controlled (light.turn_on/off service) by the light entity.
Have a look at the [HA docs](https://www.home-assistant.io/integrations/light/).
