### ISSUE TITLE
Update 1.40.1 to 1.41.1 fails. Home Assistant does not start propperly afterwards.

### ISSUE THREAD

**Issue by ItsaBastI** [SukramJ/hahomematic#1195]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [ ] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [ ] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hello,

I am running HomeAssistant on a dedicated PC on HAOS. Here are the details:

Home Assistant 2023.9.2 Supervisor 2023.09.2 Operating System 10.5 Frontend 20230911.0 - latest 

HACS informed me of an update for HomematicIP (local) to version 1.41.1.
I started the update. After a while HACS informed me that there is a pending restart open. I restarted the whole machine, not just Home Assistant.
The restart took considerably longer with several of the standard integrations (Shelly, NINA, Apple TV, Uptime and many more) being stuck in a "not initialized" state. HomematicIP (local) would not load either.
I used HACS to downgrade to 1.40.1 and immediately after restart everything came back up normal.

That was three days ago. Today I used the HACS "Download again" function to try another update with the same result as described above.

Would you please help me figure out what is preventing HA from loading properly after the update? Thank you.

### What version of HomematicIP (local) has the issue?

1.41.1

### What was the last working version of HomematicIP (local)?

1.40.1

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### What hardware are you running for your system?

Intel PC

### Which config details do you use

- [ ] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[config_entry-homematicip_local-cb389847381e5a9c63185e121af8e6a6.json.txt](https://github.com/danielperna84/hahomematic/files/12677470/config_entry-homematicip_local-cb389847381e5a9c63185e121af8e6a6.json.txt)

**Comment by SukramJ** [comment]
1.41.1 is a beta version. If you donˋ t know how to deal with it, it is better to leave the beta track of this integration.

Fault reasons are always findable in the logs.

**Comment by ItsaBastI** [comment]
> 1.41.1 is a beta version. If you donˋ t know how to deal with it, it is better to leave the beta track of this integration.
> 
> 
> 
> Fault reasons are always findable in the logs.

You really should not reply to posts if you're not in the mood to give a polite answer.

**Comment by SukramJ** [comment]
Sorry, you are right, and I didnˋt want to be unpolite.

Anything else to add?
