### ISSUE TITLE
HmIP-WRC6 Is not working

### ISSUE THREAD

**Issue by Boarder** [SukramJ/hahomematic#1224]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I have all the latest sw installed. HA 2023.9.3 and custom_homematic 1.43.1

But all automations with the HmIP-WRC6 are not working.

I don`t see anything in the logs that would help.

I was working with one of the older releases. I will try …

Any feedback is welcome 

### What version of HomematicIP (local) has the issue?

1.43.1

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.71.12.20230826

### What hardware are you running for your system?

Intel Nuc

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
> I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)

Please read the [documentation](https://github.com/danielperna84/custom_homematic#events-for-homematicip-devices).
