### ISSUE TITLE
HmIP-SPI devices show different sensors

### ISSUE THREAD

**Issue by eikowagenknecht** [SukramJ/hahomematic#1226]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I have 2 HmIP-SPI. They are shown differently in Home Assistant. It is unclear to me why.

The first one (installed a year ago or so) has an additional "Current illumination" sensor:

![image](https://github.com/danielperna84/hahomematic/assets/1475672/b4014ae1-7460-4ee8-b4c2-91bccf1ead31)

The new one (installed today) has not:

![image](https://github.com/danielperna84/hahomematic/assets/1475672/08202428-1427-481f-ac15-1d2717ab068e)

My guess is that "Current illumination" is now filtered out? Is there any cleanup script or something like that to automatically remove those leftovers?

Seems to not have any problems with the functionality though, so low prio.

### What version of HomematicIP (local) has the issue?

1.43.1

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic HA-Addon

### Which config details do you use

- [ ] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
I guess the `current illumation` can be deleted after activation and a HA restart.
With the introduction of translatable entity names some prefixes where removed from entity names.

**Comment by eikowagenknecht** [comment]
Tanks! 

The complete sequence was:
- Activate it
- Restart HA
- Remove it from HA (delete button)

I guess there's no way to check if there are more of these ghost devices automatically?

**Comment by SukramJ** [comment]
Automatically? No.
Use the entity overview and manually search for deactivated entities with english name part.

**Comment by eikowagenknecht** [comment]
Ok, thanks for the help :-)
