### ISSUE TITLE
 GET_ALL_SYSTEM_VARIABLES failed: ValueError

### ISSUE THREAD

**Issue by loki-sft** [SukramJ/hahomematic#1230]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

HA log is flooding with this message:
`WARNING (MainThread) [hahomematic.client.json_rpc] GET_ALL_SYSTEM_VARIABLES failed: ValueError [invalid literal for int() `with base 10: 'Hausarbeit'] Failed to parse SysVar TTS_Echo_Devices 

"TTS_Echo_Devices" is a system variable type value list with 2 values.

Script on CCU is working without errors.
```
var sv       = dom.GetObject(ID_SYSTEM_VARIABLES).Get("TTS_Echo_Devices");
string s_group_name = web.webGetValueFromList(sv.ValueList(), sv.Value());
WriteLine("s_group_name : " + s_group_name );
```
 

### What version of HomematicIP (local) has the issue?

1.43.1

### What type of installation are you running?

Home Assistant Container

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.71.12.20230826

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Anything in the logs that might be useful for us? The log (full log) is the best source to support trouble shooting!

```txt
WARNING (MainThread) [hahomematic.client.json_rpc] GET_ALL_SYSTEM_VARIABLES failed: ValueError [invalid literal for int() with base 10: 'Hausarbeit'] Failed to parse SysVar TTS_Echo_Devices
```

**Comment by SukramJ** [comment]
~~Von welchem CCU sysvar Typ ist `Hausarbeit`?
Was ist der Inhalt von `Hausarbeit`?~~

**Comment by SukramJ** [comment]
Welche Werte stehen in der Werteliste von `TTS_Echo_Devices`?
Wie ist der aktuelle Wert von `TTS_Echo_Devices`?

**Comment by loki-sft** [comment]
Moin!
In der Werteliste steht "Hausarbeit;Alle".
Aktuell ist "Alle" gesetzt.

Das CCU Script liefert korrekt:
Index: 1
Wert: Alle

Stelle ich in der CCU auf "Hausarbeit", liefert das CCU Script auch die korrekten Werte:
Index: 0
Wert: Hausarbeit

**Comment by SukramJ** [comment]
Kann ich leider nicht reproduzieren.

Funktioniert bei mir mit und ohne [hahm](https://github.com/danielperna84/custom_homematic#system-variables)

Erstell die SV ggf. noch mal neu.

**Comment by loki-sft** [comment]
Mache ich.  
Im Log waren eigenartiger Weise nur Meldungen wenn die SV auf 0/Hausarbeit stand. 
Ich beobachte einen Tag und Melde morgen wieder.

**Comment by SukramJ** [comment]
Ich denke das Issue kann geschlossen werden.
