### ISSUE TITLE
No connect after upgrade anymore

### ISSUE THREAD

**Issue by stefanbode** [SukramJ/hahomematic#1235]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: hahomematic.client.json_rpc
Source: custom_components/homematicip_local/control_unit.py:954
Integration: Homematic(IP) Local (documentation, issues)
First occurred: 11:20:11 (1 occurrences)
Last logged: 11:20:11

GET_SYSTEM_INFORMATION failed: ClientException [POST method 'CCU.getAuthEnabled' failed: internal error: couldn't read file "/lib/libsecuritylevel.tcl": no such file or directory while executing "source "/lib/libsecuritylevel.tcl"" (file "/www/api/methods/ccu/getauthenabled.tcl" line 10) invoked from within "source [file join $env(DOCUMENT_ROOT) "api/methods/$method(SCRIPT_FILE)"]"]

### What version of HomematicIP (local) has the issue?

1.43.1

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU2

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: hahomematic.client.json_rpc
Source: custom_components/homematicip_local/control_unit.py:954
Integration: Homematic(IP) Local (documentation, issues)
First occurred: 11:20:11 (1 occurrences)
Last logged: 11:20:11

GET_SYSTEM_INFORMATION failed: ClientException [POST method 'CCU.getAuthEnabled' failed: internal error: couldn't read file "/lib/libsecuritylevel.tcl": no such file or directory while executing "source "/lib/libsecuritylevel.tcl"" (file "/www/api/methods/ccu/getauthenabled.tcl" line 10) invoked from within "source [file join $env(DOCUMENT_ROOT) "api/methods/$method(SCRIPT_FILE)"]"]

**Comment by SukramJ** [comment]
See #1223
