### ISSUE TITLE
Second CCU3 deleted in HA --> can't delete remaining devices (not even by service: homematicip_local.delete_device)

### ISSUE THREAD

**Issue by kitty99hub** [SukramJ/hahomematic#1246]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hi,
I had 2 CCU3 configured in my HA and deleted one of them in the integration.
After that, I realized that there were still a couple of devices and entities remaining in HA from the deleted CCU3.
After activating all the entities, I could delete them.
But I cannot delete the obsolete devices.
When using the service "homematicip_local.delete_device", only the devices from my first CCU3 appear, but no devices from the deleted CCU3....!?
How can I proceed to delete the obsolete devices from the deleted CCU3?
Many thanks

### What version of HomematicIP (local) has the issue?

1.45.0 (But I suspect that it affects all versions)

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.71.12

### What hardware are you running for your system?

NUC

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

No debug possible because no errors occur

**Comment by SukramJ** [comment]
The process of removing a config entry (a CCU) of an integration is controlled by HA and not by the integration.
All devices and entities belonging to the integration are also removed.

I do this very often, and never experienced an issue with left of devices or entities.

The service [homematicip_local.delete_device](https://github.com/danielperna84/custom_homematic#homematicip_localdelete_device) is only relevant if the config entry of the integration is still alive.

We cannot control /delete device/entities that are not associated with a config entry.

Only chance is to remove the entries from `/config/.storage/core.device_registry`, and restart HA afterwards. I do not recommend or support this, because a simple failure will kill your HA setup, and HA will not start!

**Comment by kitty99hub** [comment]
Hi @SukramJ 
Thanks for the quick reply.
That's not good news...
I also have no idea why this happened.
I deleted the CCU3 from the integration, but some devices still remained in HA.
Then, now the only way is via the core.device_registry, although I would have liked to avoid that because of the warnings I read in a couple of posts.
I hope the backups work, just in case.
After removing the devices in this config file, the system is then completely cleaned up, and nothing else remains anywhere else...?
regards

**Comment by SukramJ** [comment]
Should be.

**Comment by kitty99hub** [comment]
Ok, will give reply ;)

**Comment by SukramJ** [comment]
Can be closed as issue is not related to the integration.

**Comment by kitty99hub** [comment]
For the sake of completeness, a short feedback.
I was able to delete all referenced devices by editing the core.device_registry file and the system is still alive :)

Regarding the warnings about editing this file, I can only say that it worked for me without any problems.
For those who have to do it sometimes:
- Make sure that there is a working full backup of the system.
- To be on the safe side, also save the core.device_registry file to be edited.
- Stop Home Assistant Core before exchanging the config file!
- When editing this file, pay particular attention to ensuring that the code remains consistent, in terms of text indentation etc...
You can check the code here:
https://jsonlint.com
