### ISSUE TITLE
After upgrading from version 1.43.1 to 1.44.1 or 1.45.0, system variables are no longer updated 

### ISSUE THREAD

**Issue by euDominic** [SukramJ/hahomematic#1248]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

After upgrading from version 1.43.1 to 1.44.1 or 1.45.0, system variables are no longer updated.
System variables (number), with and without the "hahm" entry in the description. 

Triggering via "Home Assistant Core Integration: Update entity" does not improve the situation either.

### What version of HomematicIP (local) has the issue?

1.44.1 - 1.45.0

### What was the last working version of HomematicIP (local)?

1.43.1

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.71.12.20230826

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[config_entry-homematicip_local-b66c2dc057fb126519817ee6feb09602.json.txt](https://github.com/danielperna84/hahomematic/files/12855022/config_entry-homematicip_local-b66c2dc057fb126519817ee6feb09602.json.txt)
[home-assistant_homematicip_local_2023-10-10T07-14-51.496Z.log](https://github.com/danielperna84/hahomematic/files/12855032/home-assistant_homematicip_local_2023-10-10T07-14-51.496Z.log)

### Anything in the logs that might be useful for us? The log (full log) is the best source to support trouble shooting!

```txt
Unfortunately, there is no error shown.
```

**Comment by SukramJ** [comment]
I cannot reproduce this on my systems.
Please add integration diagnostics for version 1.45.0.

Please don't add logs with wildcard debug enabled. That reason why i wrote `Don't switch to DEBUG level if not requested`in the issue template is: I am not interested in unrelated stuff.

This is much better next time:
```
logger:
  default: warn
  logs:
    hahomematic: info
    hahomematic.client: debug
    custom_components.homematicip_local.generic_entity debug
```
These lines indicate that sysvars are updated:
```
[custom_components.homematicip_local.generic_entity] Sysvar changed event fired for Sv_stromzaehler kwh
[custom_components.homematicip_local.generic_entity] Sysvar changed event fired for Sv_stromzaehler kw
[custom_components.homematicip_local.generic_entity] Sysvar changed event fired for Sv_ccu_Temperatur


```

**Comment by eikowagenknecht** [comment]
**Maybe related**

Ich kann seit dem Update keine Variablen mehr setzen per Servicecall und bekomme folgende Meldungen:

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: hahomematic.central
Source: custom_components/homematicip_local/services.py:475
Integration: Homematic(IP) Local (documentation, issues)
First occurred: 11:38:17 (1 occurrences)
Last logged: 11:38:17

Variable Lueftung-KuecheWohnzimmer-Soll not found on CCU3
```

Die Variablen wurden auf der CCU seit Jahren nicht angefasst.

```
2023-10-10 11:38:17.395 WARNING (MainThread) [hahomematic.central] Variable Lueftung-KuecheWohnzimmer-Soll not found on CCU3
```

**Comment by SukramJ** [comment]
@eikowagenknecht Bitte mach ein eigenes Ticket auf.

**Comment by eikowagenknecht** [comment]
Done #1249

**Comment by klingbing** [comment]
Same setup, different Homematic hardware, same issue. I‘ll look into getting logs later if it helps.

**Comment by euDominic** [comment]
> I cannot reproduce this on my systems. Please add integration diagnostics for version 1.45.0.
> 
> Please don't add logs with wildcard debug enabled. That reason why i wrote `Don't switch to DEBUG level if not requested`in the issue template is: I am not interested in unrelated stuff.
> 
> This is much better next time:
> 
> ```
> logger:
>   default: warn
>   logs:
>     hahomematic: info
>     hahomematic.client: debug
>     custom_components.homematicip_local.generic_entity debug
> ```
> 
> These lines indicate that sysvars are updated:
> 
> ```
> [custom_components.homematicip_local.generic_entity] Sysvar changed event fired for Sv_stromzaehler kwh
> [custom_components.homematicip_local.generic_entity] Sysvar changed event fired for Sv_stromzaehler kw
> [custom_components.homematicip_local.generic_entity] Sysvar changed event fired for Sv_ccu_Temperatur
> ```

Das ist von einem Programm von mir.

service: number.set_value
data_template:
  entity_id: number.ccu_sv_stromzaehler_kw

Jedoch kommt kein update von der ccu nach hoa, wie beschrieben, auch nicht per manuellen Trigger.
Von hoa zu ccu geht.

integration diagnostics for version 1.45.0, kann ich nicht mehr posten, da wieder auf Version 1.43.1 und sonst meine ganze Energie daten für den Tag wieder durcheinander kommen.

Mir ist aufgefallen das mit version 1.44.1 die  recorder platform removed wurde. Hat das eine Auswirkung?

**Comment by SukramJ** [comment]
Wenn ich von Dir keine Infos aus der 1.45.0/1.46.0 kriege können wir das Ticket hier schliessen.
Wie gesagt kann ich das Problem bei mir nicht nachvollziehen.

> Mir ist aufgefallen das mit version 1.44.1 die recorder platform removed wurde. Hat das eine Auswirkung?

Nicht relevant hier.

**Comment by euDominic** [comment]
OK ich werde auf 1.46.0 updaten. Melde mich dann mit dem Ergebnis.

**Comment by euDominic** [comment]
[config_entry-homematicip_local-b66c2dc057fb126519817ee6feb09602.json.txt](https://github.com/danielperna84/hahomematic/files/12859445/config_entry-homematicip_local-b66c2dc057fb126519817ee6feb09602.json.txt)

**Comment by SukramJ** [comment]
File contains an error.

**Comment by SukramJ** [comment]
Please use this log config:

```
logger:
  default: warn
  logs:
    hahomematic: info
    hahomematic.client: debug
    hahomematic.client.jdbc_rpc: info
    hahomematic.client.xml_rpc: info
    custom_components.homematicip_local.generic_entity: debug
```
A short description what you have manually triggered might be helpful.

**Comment by euDominic** [comment]
> File contains an error.

[config_entry-homematicip_local-b66c2dc057fb126519817ee6feb09602.json.txt](https://github.com/danielperna84/hahomematic/files/12859547/config_entry-homematicip_local-b66c2dc057fb126519817ee6feb09602.json.txt)

**Comment by euDominic** [comment]
seit dem Update keine Änderungen mehr an den variablen.

![Bildschirmfoto 2023-10-10 um 18 29 55](https://github.com/danielperna84/hahomematic/assets/88461637/79c71e41-5dda-482f-9720-3cf71d9f44d7)

**Comment by euDominic** [comment]
> Please use this log config:
> 
> ```
> logger:
>   default: warn
>   logs:
>     hahomematic: info
>     hahomematic.client: debug
>     hahomematic.client.jdbc_rpc: info
>     hahomematic.client.xml_rpc: info
>     custom_components.homematicip_local.generic_entity: debug
> ```
> 
> A short description what you have manually triggered might be helpful.

richte ich gleich ein.

**Comment by SukramJ** [comment]
Die Anzeige wird nur aktualisiert, wenn der Wert sich ändert.
Hast Du eine Sysvar die Du in der CCU manuell änern kannst?

**Comment by euDominic** [comment]
> Die Anzeige wird nur aktualisiert, wenn der Wert sich ändert. Hast Du eine Sysvar die Du in der CCU manuell änern kannst?

Das ist mir schon klar, :-) über diese SVs werden die Verbräuche der einzelnen Geräte gemessen.

Ich habe eine Test SV angelegt, die ich jederzeit bearbeiten kann.

**Comment by SukramJ** [comment]
Ok, dann aktiviere die Test SV in HA (das dauert 30s) und dann kannst Du mal Werte in der CCU ändern.

Und dann kannst Du mal Logs anhängen.

**Comment by SukramJ** [comment]
Nur der vollständigkeit halber.
Der logger `hahomematic.client.jdbc_rpc: info` enthält einen Schreibfehler, so das der nicht greift, aber das ist aktuell auch gut so.

**Comment by euDominic** [comment]
So, warum auch immer, aber jetzt läuft alles wie gewohnt.
Das Einzige, was geändert wurde, war das Logging anzupassen und das anlegen und aktivieren der Test Sv.
2x Neustart.

Auch die Template-Sensoren für das Energieboard bekommen wieder die aktuellen Daten.

Ich beobachte alles noch genau.
Bis dahin kann der issue geschlossen werden.
