### ISSUE TITLE
HmIPW-SCTHD not recognized as 'climate' entitiy

### ISSUE THREAD

**Issue by Hannsre** [SukramJ/hahomematic#1250]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hello,

I recently bought a HmIPW-SCTHD and just installed it. 
I'm struggling to get it to show as a 'climate' Entity in Home Assistant so I can add it as a thermostat card for that particular room. 

I can read and set the target temperature using HA, but only manually opening the device settings. The target temperute is shown as 'number.hmipw_scthd_003860c9a4ac08_set_point_temperature', whereas a HmIPW-WTH is correctly shown as a climate entity to set the target temperature right in a thermostat card. 

I guess that's due to the HmIPW-SCTHD being rather new, so if I can help the integration by providing any data I'm happy to help! 

### What version of HomematicIP (local) has the issue?

1.43.1

### What was the last working version of HomematicIP (local)?

1.43.1

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.71.12.20230826

### What hardware are you running for your system?

Proxmox VMs for HA and RPimatic

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[config_entry-homematicip_local-7cf67563fdc2925a18715bc3fc1634ec.json.txt](https://github.com/danielperna84/hahomematic/files/12855748/config_entry-homematicip_local-7cf67563fdc2925a18715bc3fc1634ec.json.txt)

**Comment by SukramJ** [comment]
The HmIPW-SCTHD must be implemented as custom entity.
Therefor we need the device descriptions. [See](https://github.com/danielperna84/custom_homematic#homematicip_localexport_device_definition).
Please add the zipped files here.

**Comment by Hannsre** [comment]
That was quick, thanks! 
Here are the files: 

[export_paramset_descriptions_HmIPW-SCTHD.json](https://github.com/danielperna84/hahomematic/files/12855904/export_paramset_descriptions_HmIPW-SCTHD.json)
[export_device_descriptions_HmIPW-SCTHD.json](https://github.com/danielperna84/hahomematic/files/12855907/export_device_descriptions_HmIPW-SCTHD.json)

I hope those are the ones you need?

**Comment by SukramJ** [comment]
Looks good will be part of next release.

**Comment by SukramJ** [comment]
Please test with 1.46.0.
The old entities can be deleted.

**Comment by Hannsre** [comment]
Looks good to me, thanks!
