### ISSUE TITLE
Automation Auslöser WRC6

### ISSUE THREAD

**Issue by GitHubKlpp** [SukramJ/hahomematic#1262]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [ ] I am running the latest version of the custom_component (and Home Assistant)

### The problem

In der Automation wir der Druck auf Taste 6 des HmIP-WRC5 nicht als Auslöser erkannt.

platform: device
domain: homematicip_local
device_id: ea8b3ab7c23fdxxxxxxxxxxxxxabdf26
event_type: homematic.keypress
address: 000Bxxxxx4E47A
device_type: HmIP-WRC6
interface_id: 192-168-178-22-HmIP-RF
type: press_short
subtype: 6

![Screenshot 2023-10-15 143937](https://github.com/danielperna84/hahomematic/assets/118378823/c76f0e54-b2e2-43a2-ba88-0eba63f1d48a)

### What version of HomematicIP (local) has the issue?

1.46.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.71.12.20230826

### What hardware are you running for your system?

Pi4

### Which config details do you use

- [ ] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Da haben wir komischerweise einen Abschnitt in der [Doku](https://github.com/danielperna84/custom_homematic#events-for-homematicip-devices).
