### ISSUE TITLE
Download und Update nicht möglich.

### ISSUE THREAD

**Issue by ItsaBastI** [SukramJ/hahomematic#1263]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [ ] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Es tut mir leid, aber ich brauche bitte Hilfe mit der Aktualisierung von HomematicIP.

In HACS wird mit angezeigt, dass ich 1.40.1 zu 1.46.0 aktualisieren kann. Nachdem ich damit vor ein paar Wochen schon Probleme hatte, habe ich nun ein paar Versionen abgewartet um es heute erneut zu versuchen. Nun, nach dem RaspberryMatic Update auf 3.71.12.20231014 (welches Problemlos lief) habe ich es mit dem HomematicIP (local) noch mal versucht.

Ich weiß nicht warum, aber laut den Fehlermeldungen kann nichts von Github heruntergeladen werden. Via Terminal & SSH kann ich Github.com aber anpingen. Auch ein wget auf eine der Dateien, die angeblich nicht heruntergeladen können, klappt:

wget https://raw.githubusercontent.com/danielperna84/custom_homematic/1.46.0/custom_components/homematicip_local/.idea/hahm.iml

klappt ohne Fehler und die Datei ist anschließend im Dateisystem.

IP Config in HA steht auf Automatisch.

### What version of HomematicIP (local) has the issue?

1.40.1

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic HA-Addon

### What hardware are you running for your system?

Intel i5

### Which config details do you use

- [ ] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Anything in the logs that might be useful for us? The log (full log) is the best source to support trouble shooting!

```txt
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.hacs
Source: custom_components/hacs/repositories/base.py:991
Integration: HACS (documentation, issues)
First occurred: 15:15:30 (4 occurrences)
Last logged: 15:15:30

<Integration danielperna84/custom_homematic> [cover.py] was not downloaded.
<Integration danielperna84/custom_homematic> [hahm.iml] was not downloaded.
<Integration danielperna84/custom_homematic> [.gitignore] was not downloaded.
<Integration danielperna84/custom_homematic> [binary_sensor.py] was not downloaded.

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.hacs
Source: custom_components/hacs/base.py:719
Integration: HACS (documentation, issues)
First occurred: 15:11:20 (22 occurrences)
Last logged: 15:15:28

A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/danielperna84/custom_homematic/1.46.0/custom_components/homematicip_local/.idea/hahm.iml, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 1
A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/danielperna84/custom_homematic/1.46.0/custom_components/homematicip_local/cover.py, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 0
A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/danielperna84/custom_homematic/1.46.0/custom_components/homematicip_local/.idea/hahm.iml, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 0
A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/danielperna84/custom_homematic/1.46.0/custom_components/homematicip_local/.idea/.gitignore, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 0
A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/danielperna84/custom_homematic/1.46.0/custom_components/homematicip_local/binary_sensor.py, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 0
```

**Comment by ItsaBastI** [comment]
Hier noch der Link zu meinem Issue von vor ein paar Wochen: https://github.com/danielperna84/hahomematic/issues/1195

**Comment by SukramJ** [comment]
Ich denke nicht, das dieses Issue mit dem vor ein paar Wochen zusammen hängt.
Hier ist HACS nicht in der Lage Dateien bei Github herunterzuladen.

Halt also nichts mit der Integration zu tun.

Vielleicht macht es Sinn das Problem bei HACS zu melden.
