### ISSUE TITLE
unignore Parameter ist "versteckt durch Integration" und kann nicht in Dashboard als Graph angezeigt werden.

### ISSUE THREAD

**Issue by Baxxy13** [SukramJ/hahomematic#1265]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Ich habe einige "Unignore-Parameter" aktiv, unter anderem LEVEL.
(hier für ein eTRV um den LEVEL als Diagramm in der UI anzuzeigen)

Seit dem kürzlichen Update von "unignore" wird der Parameter beim Gerät als "nicht verfügbar" angezeigt.
![HA_eTRV_Level_nicht verfügbar](https://github.com/danielperna84/hahomematic/assets/54898249/cc6dc557-5780-48a3-b4c9-0083d17e6d07)
Gehe ich drauf und dann auf das Zahnrad steht dort "Versteckt durch Integration."
![HA_eTRV_Level_versteckt](https://github.com/danielperna84/hahomematic/assets/54898249/6d0b3843-761a-4db8-a4b9-331a07c1d6ca)
Was letztlich dazu führt das im Dashboard kein Graph mehr angezeigt wird.
![HA_eTRV_Level_Dashboard](https://github.com/danielperna84/hahomematic/assets/54898249/007ace0a-5d0e-40c4-bd42-04d211c4dc1b)

### What version of HomematicIP (local) has the issue?

1.47.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.71.12.20231020

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[config_entry-homematicip_local.json.txt](https://github.com/danielperna84/hahomematic/files/13055051/config_entry-homematicip_local.json.txt)

### Anything in the logs that might be useful for us? The log (full log) is the best source to support trouble shooting!

```txt
-
```

### Additional information

Ich weiß nicht genau wann du unignore erweitert hattest, in meiner \config\homematicip_local\unignore steht einfach nur `LEVEL` drin

**Comment by SukramJ** [comment]
Ich hab in der letzten Zeit viel den Code aufgeräumt, un dabei auch die WrapperEntities entfernt, die einen ziemlichen Overhead im Code verursacht haben.
`LEVEL` wird beim eTRV als `sensor` angezeigt, indem die Platform der eigentlichen `number` Entity auf `sensor` geändert wird, eine zuvor vorhandene WrapperEntity gibt's ja nicht mehr.
Wenn nun per unignore `LEVEL` aufgenommen wird, dann wird der die Platform  nicht auf `sensor` geändert sondern bleibt `number`.
Warum hast Du `LEVEL` überhaupt im unignore? Gab es da nicht ein Problem?

Die `sensor` Entity kann Du hier einfach löschen, die wurde nicht versteckt.

**Comment by Baxxy13** [comment]
Oh, ok. Da ist wohl was an mir vorbeigegangen. 
Ich hatte `LEVEL` von Anfang an in der `unignore` weil der damals nicht anders verfügbar war.
Ich lösche den jetzt mal raus und melde mich.

**Comment by SukramJ** [comment]
Gibt auch ein paar Änderungen bei [unignore](https://github.com/danielperna84/hahomematic/blob/devel/docs/unignore.md#examples).

**Comment by Baxxy13** [comment]
Hab ich gesehen, und beim überfliegen für gut befunden. 😉 
Deine Hinweise haben mein (selbstgemachtes) Problem gelöst, vielen Dank.
Läuft wieder!
