### ISSUE TITLE
Covers: Use special value 101.0/"ignore" if only level or tilt is to be changed

### ISSUE THREAD

**Issue by 1358** [SukramJ/hahomematic#1266]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Currently, if either `level` or `tilt_level` is not set the value is re-calculated from the current position:
[cover.py 274 275](https://github.com/danielperna84/hahomematic/blob/c2527f84a494d4a7706a541f6cf78a28d108a5a9/hahomematic/platforms/custom/cover.py#L274C14-L274C14):
``` python
_level = level if level is not None else self.current_position / 100.0
_tilt_level = tilt_level if tilt_level is not None else self.current_tilt_position / 100.0
```
This always causes a "major" reposition (as for e.g. the internal value of `level` always changes on adjusting the `tilt_level`) that is unneccessary in nearly all cases.

There are special values `101.0` "ignore" (and `100.5` ("last value")) that are used by the CCU itself and that should be used instead here too:
``` python
_level = level if level is not None else 101.0
_tilt_level = tilt_level if tilt_level is not None 101.0
```

### What version of HomematicIP (local) has the issue?

devel

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which config details do you use

- [ ] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Thanks for the contribution.
Why don't you just create a pull request?
Where did you get the information about 101? Is this documented somewhere?
Which device is this in your case?
