### ISSUE TITLE
Cant connect to Homematic anymore

### ISSUE THREAD

**Issue by heli77** [SukramJ/hahomematic#1267]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

HA cant connect to Homematic anymore. I do not get any good Errormessage it only says "Uknown error occured" but when I look to protocol in Homeassistant i see the following error:
 

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: hahomematic.client.xml_rpc
Source: custom_components/homematicip_local/control_unit.py:713
Integration: Homematic(IP) Local (documentation, issues)
First occurred: 20:57:32 (3 occurrences)
Last logged: 21:12:37

SSLError on temporary_instance-BidCos-RF: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1006)')

### What version of HomematicIP (local) has the issue?

1.47

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.47.15

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [ ] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[config_entry-homematicip_local-f43f287e2f6ff8ba572746f6ee816cb4.json (2).txt](https://github.com/danielperna84/hahomematic/files/13170048/config_entry-homematicip_local-f43f287e2f6ff8ba572746f6ee816cb4.json.2.txt)

**Comment by SukramJ** [comment]
Remove the forwarding to https (in ccu) or enable tls (integration).

**Comment by heli77** [comment]
Mate you made my day - I did not have the option for https in ccu so I made an update-> and now I can configure as it should be!
Thank you !!!
