### ISSUE TITLE
Service Climate Away Mode not working correctly

### ISSUE THREAD

**Issue by stefangries** [SukramJ/hahomematic#1271]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

For me, the service to activate the vacation mode shows a strange behavior:

- The start time is ignored, the target temperature is set immediately
- The start time is first displayed as end time
- approx. 20 seconds later the mode also changes from auto to vacation and the end time is now displayed correctly
- but at the same time the set temperature changes to a random value of 7.5

https://github.com/danielperna84/hahomematic/assets/10342151/cfd84259-0214-4919-a0cc-2e2c29383390

### What version of HomematicIP (local) has the issue?

1.47.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.71.12.20231020

### What hardware are you running for your system?

Intel NUC

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Thanks for reporting
