### ISSUE TITLE
HMIP-RGBW only one Channel in Tunable White Mode

### ISSUE THREAD

**Issue by Hannsre** [SukramJ/hahomematic#1280]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hey,

I've read through the topics around this controller but couldn't really find a solution to my specific case. 

I run the HMIP-RGBW in Tunable White mode with two TW LED-Strips connected like this: 

<img width="674" alt="image" src="https://github.com/danielperna84/hahomematic/assets/81830618/3f771c3a-b01b-4436-9a5e-857d741ec599">

The first Channel shows up and works as expected in Home Assistant (I can set Brightness, temperature, Effects), but the second channel doesn't show up. There is a second Entity called `vch2`, but it's unavailable. Both channels work fine in RPIMatic. 

<img width="839" alt="image" src="https://github.com/danielperna84/hahomematic/assets/81830618/506e9643-76af-4d83-b45d-57a0f56d9dd4">

Heres the device definitions to be safe: 

[HmIP-RGBW_Device_descriptions.json](https://github.com/danielperna84/hahomematic/files/13230308/HmIP-RGBW_Device_descriptions.json)
[HmIP-RGBW_Paramset_descriptions.json](https://github.com/danielperna84/hahomematic/files/13230309/HmIP-RGBW_Paramset_descriptions.json)

Not sure what to test next. 

### What version of HomematicIP (local) has the issue?

 1.47.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which config details do you use

- [ ] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
> There is a second Entity called vch2, but it's unavailable. 

Maybe reading the docs about [deactivated entities](https://github.com/danielperna84/custom_homematic#deactivated-entities) helps.

**Comment by Hannsre** [comment]
My god, now I feel stupid. Thanks, that was it.
