### ISSUE TITLE
Namen der Entity im HA falsch (zusätzliches Leerzeichen)

### ISSUE THREAD

**Issue by darkman242** [SukramJ/hahomematic#1287]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Ich habe debmatic im Einsatz und dort ein einzelnes HM-Gerät (Homematic (Bidcos-RF) - HM-SCI-3-FM) für den Briefkasten im Einsatz. In der OCCU ist der Name 'Briefkasten' korrekt. In der Integration in HA wird nach dem Briefkasten ein Leerzeichen eingefügt. Somit sind die Bezeichungen der Sensoren falsch.

![image](https://github.com/danielperna84/hahomematic/assets/46793576/523de052-3374-41ea-ae45-21f66937ac1a)

![image](https://github.com/danielperna84/hahomematic/assets/46793576/2c63e33a-9c16-4654-9364-af6d5d247eb1)

### What version of HomematicIP (local) has the issue?

1.48

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

Debmatic

### Which version of your homematic backend are you running?

3.71.12.109

### What hardware are you running for your system?

Proxmox, HB-RF-Eth

### Which config details do you use

- [ ] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Zum einen sehe ich da keine Leerzeichen, und zum anderen könntest du die Unterstriche entfernen, dann beginnen die Namen der Entitäten auch nicht mit einem Unterstrich.

Was habe ich übersehen?

**Comment by darkman242** [comment]
Ja, ich denke du hast was übersehen. Und ich habe mich unklar ausgedrückt. Die Entity passt, aber der Name nicht - da wird ein Leerzeichen eingefügt (nur beim HM-Gerät bei mir, alle HmIP-Geräte sind korrekt benamt. Am Gerät wird irgendwie ein Leerzeichen eingefügt, welches dann den Entity-Name teilt und somit nur alles nach dem Leerzeichen angezeigt wird.

Ist sicherlich nur kosmetischer Natur - wollte aber nicht die Entity nicht manuell umbenennen.

![image](https://github.com/danielperna84/hahomematic/assets/46793576/5dbd37a8-7139-4038-81a6-a2e744f2f118)
![image](https://github.com/danielperna84/hahomematic/assets/46793576/59688897-ba3f-4428-9223-3512dd3be801)

**Comment by SukramJ** [comment]
Das ist alles korrekt umgesetzt.
Vor einigen Versionen gab es in HA Änderungen bei der Benennung von Entitäten, um eine bessere UI Unterstützung zu ermöglichen. [Siehe](https://developers.home-assistant.io/docs/core/entity#has_entity_name-true-mandatory-for-new-integrations).

Der angezeigte Name wird aus dem Gerätenamen (`Briefkasten`) und dem Namen der Entität (`Briefkasten_unbenutzt` - `Briefkasten` = `_unbenutzt` zusammengesetzt.
Je nach verwendeter UI-Card wird dann der Fullname (`Briefkasten _unbenutzt`) oder nur der Entitätsname (`_unbenutzt`) angezeigt. 

Die Integration ist nicht für die Anzeige verantwortlich.
