### ISSUE TITLE
HmIP-BRC2 button event fails

### ISSUE THREAD

**Issue by DeepCoreSystem** [SukramJ/hahomematic#1289]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [ ] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Proceeded according to [events for HmIP](https://github.com/SukramJ/custom_homematic#events-for-homematicip-devices) to activate the event from the device to the CCU and created an automation.

The automation isn't called and I found the following warning/error in the logs of HA:
`2023-11-12 21:49:33.964 WARNING (XmlRpcServer on port 50503) [hahomematic.central.decorators] EXEC_CALLBACK_SYSTEM_EVENT failed: *args not supported for callback_system_event`

### What version of HomematicIP (local) has the issue?

1.47.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.69.7.20230506

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[config_entry-homematicip_local-c94b1c22f2fff44a6ff322c0b41c8f8d.json.txt](https://github.com/danielperna84/hahomematic/files/13376820/config_entry-homematicip_local-c94b1c22f2fff44a6ff322c0b41c8f8d.json.txt)

**Comment by SukramJ** [comment]
Please update to the latest version HA and integration!
I don't support older versions.

**Comment by DeepCoreSystem** [comment]
Why close, and as completed? 

I have to backup HA first to install 2023.11.2 ... and the HomematicIP integration is at 1.47.0 and HACS doesn't offer a newer version!

**Comment by DeepCoreSystem** [comment]
![grafik](https://github.com/danielperna84/hahomematic/assets/3703938/07acbfad-7451-4efb-ba54-6a27af0729e3)

**Comment by SukramJ** [comment]
HACS will offer a new version if updated to 2023.11.x.
