### ISSUE TITLE
Cannot set HVAC modes for HmIP-BWTH from HA

### ISSUE THREAD

**Issue by ASchwarz1984** [SukramJ/hahomematic#1291]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hello everyone,

I'm using multiple HmIP-BWTH thermostats and they are configured in heat/cool mode.
I can change the mode in RaspberryMatic but I cannot use HA climate.set_hvac_mode service to switch between heating and cooling. If I set hvac mode to cool via HA then the thermostat changes to heat mode. 

### What version of HomematicIP (local) has the issue?

1.48.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic HA-Addon

### Which version of your homematic backend are you running?

3.71.12

### What hardware are you running for your system?

Pi4

### Which config details do you use

- [ ] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Please describe step by step what and where you are do something.

**Comment by ASchwarz1984** [comment]
See the attached images.

**Thermostat state before:** 
![image](https://github.com/danielperna84/hahomematic/assets/15203293/f2079828-a74b-428e-b080-92a7b577bcca)

**Run HA service climate.set_hvac_mode**
![image](https://github.com/danielperna84/hahomematic/assets/15203293/a4400c0d-9d79-47e3-804e-9bec032ac959)

**Thermostat state after:**
![image](https://github.com/danielperna84/hahomematic/assets/15203293/15986a06-bf84-4872-8a78-a75967e5ece3)

**Comment by SukramJ** [comment]
Please post the setup of you BWTH in CCU WebUI.

**Comment by ASchwarz1984** [comment]
Is this sufficient?

![image](https://github.com/danielperna84/hahomematic/assets/15203293/b0da236d-2975-4bbe-a483-5e50112da525)

**Comment by SukramJ** [comment]
I don't know. I typically don't use cool mode esp. in November.
How do you control heat/cool in CCU WebUI. Please post screenshot.

**Comment by ASchwarz1984** [comment]
I set it from the CCU via a program - I can trigger the program from HA as well so this works but it is the only program that is running outside of HA. I tried this already a while ago but it did not work back then so I postponed it. 

![image](https://github.com/danielperna84/hahomematic/assets/15203293/461723d4-9a14-4336-9bd1-bd670b448577)

**Comment by SukramJ** [comment]
Ok. What i can see so far

1. You cannot switch the hvac_mode in HA from heat to cool. This can be switched by a ccu program.
2. Now the HA climate entity shows cool instead of heat mode

This works as expected.

**Comment by ASchwarz1984** [comment]
Thats correct - Question is, would it be possible to directly change between heat/cool mode from within HA to get rid of any external programs on the CCU?

**Comment by SukramJ** [comment]
I don't think it makes sense, because the semantics of HA is a little bit different.

Here the relevant Modes are `off`, `heat`, `cool` and `auto` in HA.
`Heat` and `cool` are what `manual` is in the CCU, and the `heating_cooling` must be set in another action.

So when switching `heat` to `cool` the semantics is clear but it gets confusing when switching from `auto` in `heat` mode to `auto` in `cool` mode, because there is only on `auto` in HA.

Of course, you also have to ask yourself why `heating_cooling` cannot be controlled directly in the CCU UI.

Instead of an external program you could call the HA service `homematicip_local.set_device_value` and switch the parameter `HEATING_COOLING` on channel 1 from HEATING to COOLING.
Another option is to add `HEATING_COOLING` to [unignore](https://github.com/danielperna84/custom_homematic#unignore-device-parameters), which makes this parameter controllable as entity in HA.

**Comment by ASchwarz1984** [comment]
Ok, thanks - i‘ll give it a try and keep you posted

**Comment by ASchwarz1984** [comment]
> Instead of an external program you could call the HA service `homematicip_local.set_device_value` and switch the parameter `HEATING_COOLING` on channel 1 from HEATING to COOLING.

This works like a charm! Thanks for pointing me into the right direction!
