### ISSUE TITLE
Automation editor does not show any triggers for Homematic (IP) devices

### ISSUE THREAD

**Issue by bacmaSTR** [SukramJ/hahomematic#1302]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

In the Homematic automation editor (app, as well as browser) it is no longer possible for me to use Homematic devices as triggers because these devices (Homematic and Homematic IP) do not have triggers (no triggers are displayed in the drop-down field, the field is grayed out ). For example, ZHA devices work problem-free here.

This error can be reproduced under several browsers as well as under Linux and iOS. Uninstalling and reinstalling Raspberrymatic and Homematic(IP) Local showed no change, nor did the HomeAssistant updates in the last few months. Do I have to completely reinstall HomeAssistant or is there a better solution? An error log is attached. Thanks!

### What version of HomematicIP (local) has the issue?

1.49.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic HA-Addon

### Which version of your homematic backend are you running?

20231030.2

### What hardware are you running for your system?

Pi4

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Anything in the logs that might be useful for us? The log (full log) is the best source to support trouble shooting!

```txt
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/homematicip_local/device_trigger.py:45
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 20:32:02 (10 occurrences)
Last logged: 21:02:53

[547064052672] Error handling message: Unknown error (unknown_error) Mxxx Bxxx from 192.168.0.22 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2023.7 (io.robbie.HomeAssistant; build:2023.471; iPadOS 17.1.1) Mobile/HomeAssistant, like Safari)
[547222347200] Error handling message: Unknown error (unknown_error) Mxxx Bxxx from 192.168.0.22 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1.1 Safari/605.1.15)
[546824978880] Error handling message: Unknown error (unknown_error) Mxxx Bxxx from 192.168.0.34 (Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36)
[546791335232] Error handling message: Unknown error (unknown_error) Mxxx Bxxx from 192.168.0.34 (Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 372, in with_error_handling
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 437, in websocket_device_automation_list_triggers
    await async_get_device_automations(
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 269, in async_get_device_automations
    for domain_results in await asyncio.gather(
                          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 228, in _async_get_device_automations_from_domain
    return await asyncio.gather(  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homematicip_local/device_trigger.py", line 45, in async_get_triggers
    device_address, interface_id = data
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
```

**Comment by SukramJ** [comment]
Based on your description, I can't understand what you're doing. Please describe what you are doing step by step and attach screenshots if necessary. 
Which device do you use and what should be triggered?
I can easily create the additional triggers (press keys) provided by the integration.

**Comment by bacmaSTR** [comment]
**Homematic(IP) Local**
e.g. in automation editor i want to carry out an action when the living room (HmIP-FSM Firmware 1.24.6) light comes on. 
![Bildschirmfoto vom 2023-11-26 23-06-52](https://github.com/danielperna84/hahomematic/assets/126669507/77c58d86-692e-41a3-99ef-6669013e3c2a)
No trigger such as 'turned_on' can be selected here. The drop down field is greyed out.
The same applies to all Homematic and HomematicIp devices.

I still have code created with the automation editor 'before the error / bug' in my automation.yaml. This is carried out without any problems, but these automations can no longer be edited correctly with the editor because the triggers are now missing here too (see screenshot).
![Bildschirmfoto vom 2023-11-26 23-05-08](https://github.com/danielperna84/hahomematic/assets/126669507/83ab9734-9491-4674-ba57-3fb5f2aa732b)
![Bildschirmfoto vom 2023-11-26 23-05-16](https://github.com/danielperna84/hahomematic/assets/126669507/96980811-4e4f-40ae-88a5-e13db72d8947)


**ZHA**
For example, with devices from the ZHA integration, this works with the automation editor and a trigger turned_on is generated in the YAML code.
![Bildschirmfoto vom 2023-11-26 22-24-55](https://github.com/danielperna84/hahomematic/assets/126669507/579f258d-0e86-42cd-b69c-9fd6c40045e9)
![Bildschirmfoto vom 2023-11-26 22-25-05](https://github.com/danielperna84/hahomematic/assets/126669507/cbae37e5-f491-41d9-9b12-6db2fcad884c)

**Comment by SukramJ** [comment]
Please add the integration diagnostics.

I cannot reproduce this on my system**s**.

Probably something is brocken in your device registry.

Apart from setting up the integration again, I would first delete individual devices using the service `homematicip_local.delete_device`.
This service only removes the device inkluding entities from HA and re-createdes them  after a HA restart, but this of course changes the `device_id` (if you use this in automation).

**Comment by SukramJ** [comment]
Can this be closed?

**Comment by bacmaSTR** [comment]
> Can this be closed?

Yes, but I can't solve the problem with your advice. I will / must try a complete reinstall. I will give feedback. Thx Maik

**Comment by SukramJ** [comment]
Please have a look at the device registry.
open the file `/config/.storage/core.device_registry`.
Search for `homematicip_local` and post some entries here, or attach the whole file.

**Comment by bacmaSTR** [comment]
entries from > /config/.storage/core.device_registry

[auszug_core.device_registry.txt](https://github.com/danielperna84/hahomematic/files/13525925/auszug_core.device_registry.txt)

**Comment by SukramJ** [comment]
Your integrations instance name is `raspberrymatic@homeassistant`?

**Comment by bacmaSTR** [comment]
Since I thought that @ was the problem, I changed it a few weeks ago (now: ccu3stuttgart). However, this doesn't seem to have been adopted into the Device Registry?

**Comment by SukramJ** [comment]
Yes, a reinstall is required. The device registry will not change afterwards.

**Comment by bacmaSTR** [comment]
> Yes, a reinstall is required. The device registry will not change afterwards.

Does this mean for the future that renaming a homematicip_local hub via the function in the integration manager is obsolete or should never be used?
I'm now trying to uninstall, then I delete the 'deleted devices' in the core.device_registry (I think that otherwise it will continue to work internally with the old names after reinstallation of Homematicip_local)....

**Comment by SukramJ** [comment]
Don't touch the device registry manually.

**Comment by bacmaSTR** [comment]
I did it! 

Done! Uninstalling homematic(IP) local, restarting and reinstalling several times was not enough.

Had worked:
1) hubs deleted in homematic(IP) local
2) uninstalled homematic(IP) local
3) restarted homeassistant twice
4) 'deleted devices' deleted in core.device_registry
5) 'deleted entities' deleted in core.entity_registry
6) restarted homeassistant twice
7) reinstalled homemativ(IP) local
8) the hubs newly set up

What a pain....

Thank you for your advice!
Can be closed.....

<img width="1649" alt="screenshot_53" src="https://github.com/danielperna84/hahomematic/assets/126669507/3280df7a-6662-4c58-ba4b-2d9d812c57b8">
