### ISSUE TITLE
Away-Mode (Party-Mode/Vacation-Mode) for Homematic (non-IP) thermostats

### ISSUE THREAD

**Issue by j-st1** [SukramJ/hahomematic#1304]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Since it's a known "bug", I'm not sure if this is a bug report or a feature request. I was wondering why the away-mode is not supported on non-IP Homematic thermostats (i.e. HM-CC-RT-DN). So after a quick search, it turns out, the interface for setting the mode is different for those devices. As, for example this thread states, there is a seprate parameter for the whole procedure: "PARTY_MODE_SUBMIT"
[homematic-forum.de](https://homematic-forum.de/forum/viewtopic.php?t=34673#p330200 )

So I modified the code from the HMIP-device  to match the described format and added it to CeRfThermostat in platform.custom.climate in order to test it, and it seems to work fine:

```
async def enable_away_mode_by_calendar(
        self, start: datetime, end: datetime, away_temperature: float
    ) -> None:
        """Enable the away mode by calendar on thermostat."""
        party_mode_str = "%.1f," % away_temperature
        party_mode_str += "%d," % (start.hour * 60)
        party_mode_str += start.strftime("%d,%m,%y,")
        party_mode_str += "%d," % (end.hour * 60)
        party_mode_str += end.strftime("%d,%m,%y")
        await self._client.put_paramset(
            address=self._channel_address,
            paramset_key=ParamsetKey.VALUES,
            value={
                "PARTY_MODE_SUBMIT": party_mode_str
            },
        )

    async def enable_away_mode_by_duration(self, hours: int, away_temperature: float) -> None:
        """Enable the away mode by duration on thermostat."""
        start = datetime.now() - timedelta(minutes=10)
        end = datetime.now() + timedelta(hours=hours)
        await self.enable_away_mode_by_calendar(
            start=start, end=end, away_temperature=away_temperature
        )

    async def disable_away_mode(self) -> None:
        """Disable the away mode on thermostat."""
        start = datetime.now() - timedelta(hours=11)
        end = datetime.now() - timedelta(hours=10)
        party_mode_str = "%.1f," % 12.0
        party_mode_str += "%d," % (start.hour * 60)
        party_mode_str += start.strftime("%d,%m,%y,")
        party_mode_str += "%d," % (end.hour * 60)
        party_mode_str += end.strftime("%d,%m,%y")
        await self._client.put_paramset(
            address=self._channel_address,
            paramset_key=ParamsetKey.VALUES,
            value={
                "PARTY_MODE_SUBMIT": party_mode_str
            },
        )
```
The minutes (rounded to 30 mins) is not yet considered.
It would be great to have this in the official release.

Thanks & regards

### What version of HomematicIP (local) has the issue?

1.49.0

### What type of installation are you running?

Home Assistant Container

### What type of installation are you running for your homematic backend?

Debmatic

### Which config details do you use

- [ ] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Thanks for adding this feature request and sample code.
I took parts of your code, but changed the [party mode code generation](https://github.com/danielperna84/hahomematic/pull/1305/files#diff-7dcb6c681de83f92dbf24d5838dc45028f68d44dd8892b03041d8c6226617892R400-R407) and still ignore the 30 minuts interval.
Testcases could be found [here](https://github.com/danielperna84/hahomematic/pull/1305/files#diff-f8cb89506d3abf8507dc9b982f0f010792f1df1c778ffca4100dbc0d40804f45R197-R225).

Could you please check, if this code also works with the service [set_device_value](https://github.com/danielperna84/custom_homematic#homematicip_localset_device_value) instead of [put_paramset](https://github.com/danielperna84/custom_homematic#homematicip_localget_paramset).

The value of the parameter `PARTY_MODE_SUBMIT` should be clear to you, but please ignore the 30 minutes interval in your tests too.

**Comment by j-st1** [comment]
Wow, that was fast!
I tested your code and everything worked as expected.

The set_device_value also worked. I set the party mode using:
```
service: homematicip_local.set_device_value
data:
  device_id: 6083956e7e234ce6...
  value_type: string
  value: 17.0,470,03,03,23,720,07,03,24
  parameter: PARTY_MODE_SUBMIT
  channel: 4
```
And also disabled it by replacing the year 24 by 23.

Thanks a lot for this!
