### ISSUE TITLE
Integration can not install

### ISSUE THREAD

**Issue by rohrbachger** [SukramJ/hahomematic#1307]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Integration danielperna84/hahomematic> Repository structure for 2023.12.0 is not compliant 

Seems to be related to actual version
User defined repository: https://github.com/danielperna84/hahomematic.git

### What version of HomematicIP (local) has the issue?

2023.12.0

### What type of installation are you running?

Home Assistant Supervised

### What type of installation are you running for your homematic backend?

CCU2

### Which version of your homematic backend are you running?

2.616

### What hardware are you running for your system?

Synology

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
> Integration danielperna84/hahomematic> Repository structure for 2023.12.0 is not compliant

Read your installation instruction **carefully**:
This is NOT the custom integration: `https://github.com/danielperna84/hahomematic`
This is the custom integration: `https://github.com/danielperna84/custom_homematic`
