### ISSUE TITLE
Configuration - Unknown error occurred

### ISSUE THREAD

**Issue by AlexF090** [SukramJ/hahomematic#1308]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hallo,

ich habe ein Problem bei der Einrichtung der custom_homematic Integration in Home Assistant. Während des Setup-Prozesses erhalte ich die Fehlermeldung "Unknown error occurred". Hier ist der fehlerhafte Request:

```ruby
POST http://192.168.1.35:8123/api/config/config_entries/flow/773e79850cdf03be63a4de38ab542243
```
Und die Response:

```arduino
500 Internal Server Error
Server got itself in trouble
```

Die Netzwerkkonfiguration meiner Homematic-Zentrale ist wie folgt:

Zugriffseinstellungen der Ports: Ports blockiert
Homematic XML-RPC API: Vollzugriff
Remote Homematic-Script API: Eingeschränkt
Mediola-Zugriff: Vollzugriff
Authentifizierung (XML-RPC API): aktiv
Ich habe die IP-Adresse von Home Assistant zu den "IP-Adressen für den eingeschränkten Zugriff" hinzugefügt und die erforderlichen Ports geöffnet. Auch TLS ist konfiguriert.

Ich bin mir unsicher, ob es sich um ein Netzwerkproblem, eine Fehlkonfiguration oder einen Bug handelt. Können Sie mir bitte helfen, dieses Problem zu lösen? 

Vielen Dank im Voraus!

### What version of HomematicIP (local) has the issue?

3.71.12

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [X] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Additional information

<img width="397" alt="Bildschirmfoto 2023-12-01 um 20 56 36" src="https://github.com/danielperna84/hahomematic/assets/100590496/c38f4af4-15ed-43db-b686-2c8acf2b1fbc">

## System Information

version | core-2023.11.3
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.34-v8+
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4971
Installed Version | 1.33.0
Stage | running
Available Repositories | 1343
Downloaded Repositories | 2

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 30. November 2023 um 20:14
-- | --
current_recorder_run | 1. Dezember 2023 um 20:04
estimated_db_size | 0.67 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

**Comment by SukramJ** [comment]
Welche Version der Integration wird verwendet? 3.71.12 ist eine CCU Version.
Was steht in den HA Logs ( Full Logs)?

**Comment by Baxxy13** [comment]
Ich würde erstmal jeglichen Schnickschnack auf der Zentrale deaktivieren (Authentifizierung / HTTPS-Umleitung) und auch die Firewall (zum testen) komplett öffnen.
Dann drauf achten das wirklich nur die Interfaces angehakt sind die auch auf der Zentrale verfügbar sind.

Das nächste wäre das Netzwerk. 
Hier wird ja ein HA-Container benutzt. 
Docker-Netzwerke sind eine Sache für sich, vielleicht braucht man die Callback-Adresse oder sowas.

**Comment by Horscht0815** [comment]
Gleiche Problem hier.
Version Raspberrimatic: 3.73.9.20231130
Version Homematic(IP) Integration for Home Assistant: 1.49.0

Falls weitere Infos helfen würden, bitte Bescheid geben.

**Comment by SukramJ** [comment]
@Horscht0815 Ja, mach bitte ein eigenes Issue auf. Fülle alle Felder aus und schau auch in die Logs!

**Comment by AlexF090** [comment]
Es ist die aktuelle Version, die ich in benutzung habe.
Ich habe das Problem mithilfe der Logs lösen können. Es war tatsächlich die HTTPS-Weiterleitung schuld. 🙈
Ich habe ein selbst signiertes Zertifikat in Benutzung.
Meine Lösung war, natürlich alle Ports für TLS inkl. "[x] verwende TLS" und "JSON-RPC-Port: 433" anzugeben. Auf der Seite der Konfiguration habe ich nicht viel geändert.
Schwups, alles lief.
Ich hoffe, dass ich vielleicht mit meiner Antwort dem ein oder anderen nicht so Netzwerk affinen helfen kann, sein Problem schneller zu lösen.

Vielleicht wäre es auch möglich, dem Fehler einen Namen zu geben, damit der "User" weiß, was los ist anstelle von "Unknown error occurred". 🙂
Wenn solche Issues öfters auftreten sollten, könnte man vielleicht in der Installation noch einen Punkt mit HTTPS-Weiterleitung erstellen? 🙂

Vielen Dank für eure sehr schnellen Antworten, ohne diese hätte ich es nicht hinbekommen! 👍
