### ISSUE TITLE
Konfiguration schläg fehl

### ISSUE THREAD

**Issue by Horscht0815** [SukramJ/hahomematic#1309]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

"Unknown error occurred" bei der (Erst-)Einrichtung der Integration in Home Assistant

### What version of HomematicIP (local) has the issue?

1.49.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.73.9.20231130

### What hardware are you running for your system?

Pi3

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[home-assistant_2023-12-02T15-46-46.118Z.log](https://github.com/danielperna84/hahomematic/files/13536710/home-assistant_2023-12-02T15-46-46.118Z.log)

### Anything in the logs that might be useful for us? The log (full log) is the best source to support trouble shooting!

```txt
Bin für die Installation nach folgendem (Youtube)Video vorgegangen
https://www.youtube.com/watch?v=J3FexH-p2tk

Meine Vermutung. Gestern gab es eine neue Version der Raspberrymatic. Vielleicht liegts daran?
```

**Comment by SukramJ** [comment]
In der Log Datei steht es drin:

> Possible reason: 'Automatic forwarding to HTTPS' is enabled in backend, but this integration is not configured to use TLS

Du hast HTTPS forwarding in der CCU aktiviert, aber TLS nicht in der Konfiguration der Integration.

**Comment by Horscht0815** [comment]
Verdammt, du hast recht. Habe ich trotz mehrmaligen Überprüfen übersehen. Bitte vielmals um Verzeihung bezüglich des falschen Alarms.
Habe es zweimal (http und https) mit jeweils korreken Einstellungen in der Raspberrymatic wie auch der Integration probiert und es funktioniert.
Vielen Dank für die schnelle Hilfe.
