### ISSUE TITLE
RaspberryMatic Sv_Alarmmeldungen -> Reports one Alarm, RaspberryMatic does not ?

### ISSUE THREAD

**Issue by ChristophCaina** [SukramJ/hahomematic#1312]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

The Sensor 
sensor.RaspberryMatic Sv_Alarmmeldungen is showing the value of "1" - but there is no activ alarm in RaspberryMatic ...

![image](https://github.com/danielperna84/hahomematic/assets/26391061/90a8b048-e612-4a97-8a0e-36c641337c5b)

That's probably something within RaspberryMatic, I guess?
But since the alarm is not visible within RaspberryMatic, I thought, I should report it here, too...?

### What version of HomematicIP (local) has the issue?

1.49.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.71.12.20231020

### What hardware are you running for your system?

Proxmox VM

### Which config details do you use

- [ ] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Have a look at this [issue](https://github.com/danielperna84/hahomematic/issues/625#issuecomment-1252402685).
