### ISSUE TITLE
HmIP DLD state of lock is inconsistent

### ISSUE THREAD

**Issue by ZTHawk** [SukramJ/hahomematic#1314]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I have an inconsistent state values with the HmIP DLD in some cases when opening the door.
My setup:
- Fingerprint sensor
- Wiegand interface (HmIP FWI)
- Door lock (HmIP DLD)
All of them running the latest available firmware.

Here is what I had this morning (see attached logs [I have drag&dropped it but I do not see it]):
- Unlocked
  - Use finger print to open
- Unlocking
- Unlocked
  - Use finger print to open
- Unlocking
- Locking
- Unlocked
  - Use finger print to open
- Unlocking
  - Use finger print to open
- Unlocked

Sometimes I have also this state behaviour (no logs attached):
- Unlocked
  - Use finger print to open
- Locking
- Unlocked

### What version of HomematicIP (local) has the issue?

1.49.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.73.9.20231130

### What hardware are you running for your system?

VirtualBox

### Which config details do you use

- [X] Username and password
- [X] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Since I don't have a HmIP-DLD myself, I can't reproduce what you tried to explain.

It is important that the integration is about the correct representation of the values provided by the CCU and not about the consistency expected from the user's perspective.

It would be interesting for me to know which events are delivered from the CCU to HA when you carry out actions with your devices or on the CCU.

I think you should enter the following in the configuration.yaml and then restart HA:
```
logger:
   default: warn
   logs:
     hahomematic: info
     hahomematic.central: debug
```

Afterward do your tests with the devices/CCU and write down when you executed an action.
Then have a look at the HA log (Settings/System/Logs  press on full logs) and search for the corresponding `EVENT` of `LOCK_STATE` in the logs.

A [lock in HA](https://developers.home-assistant.io/docs/core/entity/lock) only has the state if it is locked or not. There is no state for open!

**Comment by ZTHawk** [comment]
I got the issue:
- DLD was at state "Unlocked" (last event was "Was unlocked")
- Use fingerprint to "open" the door
- DLD changed to "Is locking" (time 20:15:50)
- DLD changed to "Was unlocked" (time 20:15:51)

Log was attached. Starting from before the event and until after the event.
[home-assistant_2023-12-06T19-16-39.078Z_stripped.log](https://github.com/danielperna84/hahomematic/files/13590754/home-assistant_2023-12-06T19-16-39.078Z_stripped.log)

**Comment by SukramJ** [comment]
> Then have a look at the HA log (Settings/System/Logs press on full logs) and search for the corresponding EVENT of LOCK_STATE in the logs.

And which LOCK_STATE events could you find?

```
LOCK_STATE:

UNKNOWN = 0
LOCKED = 1
UNLOCKED = 2
```

To make it short: The DLD is sending 4 events with LOCK_STATE 2 which means UNLOCKED.


```
ACTIVITY_STATE:

UNKNOWN = 0 NO_DISPLAY
UP = 1 IS UNLOCKING
DOWN = 2  IS LOCKING
STABLE = 3 NO_DISPLAY
```

Also the even ACTIVITY_STATE is send with the values 3,2,3,3

Looks like the events match your observations.

**Comment by ZTHawk** [comment]
If "IS LOCKING" was sent, then this is incorrect (from CCU). Because the activity that was done is defenitly to open the lock.

**Comment by SukramJ** [comment]
What is displayed in HA  if you press lock and unlock?

**Comment by ZTHawk** [comment]
Well, most of the time the values are correct (as also seen in the activity list in my first post).
But sometimes "IS LOCKING" is sent incorrectly.
I had also once this behaviour:
- DLD was in state "UNLOCKED"
- finger print to open
- DLD changed to "Is unlocking"
- DLD changed to "Is locking"
- DLD changed to "Was unlocked"

So I asume now that either the DLD or CCU (RaspberryMatic) is sending wrong states.

**Comment by SukramJ** [comment]
Correct. This can be closed.
