### ISSUE TITLE
Jalousieaktor fährt immer auf irgendeine Position

### ISSUE THREAD

**Issue by Terabyte2000** [SukramJ/hahomematic#1317]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Fahre ich die Jalousie über Homeassistant (HomematicIP (local)) zum Beispiel runter, dann wird diese nach erreichen der Endposition wieder ein Stück geöffnet. 
Dies war in Version 1.32.0 nicht der Fall

### What version of HomematicIP (local) has the issue?

1.50.0

### What was the last working version of HomematicIP (local)?

1.32.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### What hardware are you running for your system?

Mini PC

### Which config details do you use

- [ ] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Was soll ich damit anfangen? 

Du schreibst nicht mal um was für ein Gerät es sich handelst, was Du machst, ob das Problem auch bei Bedienung in der CCU existiert, .....

Eine CCU Version / HA Version ist interessant, bzw. hast Du da mal ein Update gemacht.

Das wieder öffnen ist sicher nichts, was von der Integration gestartet wird. Das eher ein "feature" der CCU.
Also mach noch mal ein Downgrade auf die ältere Version um deine Aussage noch mal zu validieren.

So kannst Du das Ticket gerne schließen.

**Comment by Terabyte2000** [comment]
Sorry für meine Leienhafte Beschreibung.

Es handelt sich um einen Jalousieaktor HM-LC-Ja1PBU-FM.
Das Problem besteht in der CCU nicht.  

HA Version ist 11.2
Core 2023.12.0
Supervisor 2023.11.6

Leider kann ich nicht mehr auf die Version 1.32 downgraden, wird mir nicht mehr Angeboten im HACS. 1.47 ist die niedrigste Version.

Das Problem ist definitiv erst aufgetreten seit einem Versionsupdate.

Ich habe gerade im Changelog gesehen, dass in Version 1.34 etwas verändert wurde. (Add service set cover combined position)
Kann das damit zu tun haben? Er macht nämlich nachdem die Endposition erreicht wurde, die Lamellen wieder auf.

Danke schonmal für deine Hilfe.

**Comment by SukramJ** [comment]
1.34.0 ist 16 Versionen her und über 7 Monate alt. Es würde mich doch sehr wundern, wenn das bisher noch keinem aufgefallen ist.

Wie fährst du die Jalousie den runter?

**Comment by Terabyte2000** [comment]
Ganz normal über den Pfeil nach unten Button.

Ist es irgendwie möglich nochmal die alte Version vor 1.34 zu probieren?

**Comment by SukramJ** [comment]
Bestimmt. Kann ich dir jetzt nicht sagen, da ich jetzt ins Wochenende gehe. Vielleicht mal googeln.

**Comment by SukramJ** [comment]
@ZungeWegIchFurze 
Ich glaube Du hast das gleiche Gerät. Kannst du das Problem bei dir auch nachvollziehen?

**Comment by ZungeWegIchFurze** [comment]
Hallo zusammen,

@Terabyte2000 der Aktor hat ja von Haus aus zwei Einstellungen. Eine für die Behanghöhe und eine für die Lamellenstellung. Wenn Deine Jalousie hochgefahren ist (Behang 100% und Lamelle offen 100%) und die fährst den Behang auf halboffen (50%), dann wird im Anschluss wieder die Lamelle auf offen 100% gestellt. 
Ich habe eine Änderung der Button Funktion nicht bemerkt, weil ich die Buttons gar nicht benutzt habe. Diese können ja nicht vernünftig die Lamellen steuern.
Ich habe mir deshalb folgendes gebaut, welche alle relevanten 4 Positionen meiner Jalousien ansteuern können:
![Jalousien](https://github.com/danielperna84/hahomematic/assets/88394115/91bbb00e-313d-42e3-895d-398c7f5aa89c)
1. Knopf Sichtschutz: Jalousie runter (0%), Lamelle halbzu 40%
2. Knopf Lichtschutz: Jalousie runter (0%), Lamelle auf 100%
3. Knopf Hoch: Jalousie hoch (100%), Lamelle auf 100%
4. Knopf Geschlossen: Jalousie runter (0%), Lamelle geschlossen 0%

Das löst zwar jetzt nicht direkt Dein Problem, aber ich sehe die Funktion wie sie jetzt ist sowie als Feature und nicht als Bug.
Damit Du die Jalousien richtig nutzen kannst, solltest Du Dir auch Deine eigenen Buttons bauen. Von Haus aus bietet Home Assistant leider keine vernünftige Lösung zur Steuerung der Jalousien.

Falls Du weitere Infos oder Code brauchst, wie ich die Buttons gebaut habe, sag gerne Bescheid.

Viele Grüße

**Comment by SukramJ** [comment]
Danke @ZungeWegIchFurze

**Comment by ZungeWegIchFurze** [comment]
> Danke @ZungeWegIchFurze

Danke an Euch für die Entwicklung. Weltklasse!
