### ISSUE TITLE
HmIP-BROLL-2 seems to have inverted cover_position values

### ISSUE THREAD

**Issue by RustyDust** [SukramJ/hahomematic#1323]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Since installing two new HmIP-BROLL **-2** I find they're showing the inverse state of the actual cover position. Using the development tools I can see that the state for `current_position` behaves exactly the opposite of my older HmIP-BROLLs (w/o the -2).
When the cover is open, current_position is shown as "0", when it is closed current_position has a value of 100.

### What version of HomematicIP (local) has the issue?

1.50.0

### What type of installation are you running?

Home Assistant Core

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.73.9.20231130

### What hardware are you running for your system?

Pi4

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Sounds like a problem with your devices in CCU. Check your settings in CCU.
There is no implementation difference between HmIP-BROLL and -2

**Comment by SukramJ** [comment]
Another option is a wrong cabling

**Comment by RustyDust** [comment]
Removing the devices from the CCU and adding them again seems to have done the trick. No idea why, though. Thanks for the fast reactions!
