### ISSUE TITLE
HmIP-eTRV-C valve - entity is not numeric

### ISSUE THREAD

**Issue by ChristophCaina** [SukramJ/hahomematic#1325]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

From time to time, my eTRV-C are reporting unknown values for the Valve to HomeAssistant.

It seems, that this change, when I replace batteries, or move the valve, and also set the Thermostat to boost - but I could not really find the root cause for this.

In RaspberryMatic, the valve will be reported with 0%
<img width="316" alt="image" src="https://github.com/danielperna84/hahomematic/assets/26391061/28ade251-88d8-455c-a7ea-e97943bfd961">

But HomeAssistant is reporting Unknown - while all other values are reported correctly.
<img width="299" alt="image" src="https://github.com/danielperna84/hahomematic/assets/26391061/32bef838-9eaf-4fa1-b24c-424caa18cdcf">

<img width="207" alt="image" src="https://github.com/danielperna84/hahomematic/assets/26391061/96b68258-56af-4978-9c5f-1520663dfe5c">

I know, that the valve is also correctly reporting a zero-value (at least some times)
<img width="297" alt="image" src="https://github.com/danielperna84/hahomematic/assets/26391061/0d637bc3-16c4-4181-8bf1-ad4fb5aa70df">

Right now, I don't see any pattern or reason, why this could happen...

What additional information can I provide for this case?

### What version of HomematicIP (local) has the issue?

1.50.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.73.9.20231130

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [ ] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Ich kenn das nur, wenn auf dem Gerät eine Meldung steht. Bei mir war damals die Adaptierfahrt ausstehend.

Kannst du mit dem Homematic Manager oder den RaspberryMatic DevTools mal draufschauen. Was die WebUI anzeigt ist für mich nicht so relevant.

**Comment by ChristophCaina** [comment]
OK, da muss ich mich jetzt erst mit befassen.
Habe mit diesen Tools noch nicht zu tun gehabt

**Comment by SukramJ** [comment]
In der RM Systemsteuerung /Erweiterte Einstellungen kannst Du den DevConfig Butten aktivieren, der danach in der Systemsteuerung erscheint.

**Comment by ChristophCaina** [comment]
Ich hoffe, die Daten passen:

Unter Service Messages habe ich lediglich für folgende Geräte eine Meldung:
<img width="653" alt="image" src="https://github.com/danielperna84/hahomematic/assets/26391061/59091139-d197-493d-a1fe-7c7e044f1692">

Keines davon ist das betroffene Gerät.

Sonst konnte ich jetzt nichts weiteres finden...

**Comment by ChristophCaina** [comment]
was mir gerade einfällt:

Das Gerät ist bei uns im Schlafzimmer... und ziemlich nah am Bett...
Es KÖNNTE sein, dass das Thermostat durch Bewegung keine richtige Verbindung zum Ventil bekommt... 

Ich spiele damit mal noch ein wenig herum und teste, woran es ggf. liegen könnte.

**Comment by SukramJ** [comment]
Ich gehe davon aus, das es sich nicht um einen Fehler in  der Integration handelt.
Mein eTRV-2 (gleicher Code) funktioniert.

**Comment by ChristophCaina** [comment]
Hi.
Ja, es scheint tatsächlich etwas mit der Adaption zu sein.
Sobald ich die Spannungsversorgung weg nehme - und wieder hinzufüge, wird eine Adaption durchgeführt und auch der Status wird dann korrekt ermittelt.

Einzig, dass der Status als "unknown" zurück gemeldet wird, wundert mich - da eben sonst in RM nichts auftaucht.
Kein Alarm, keine Warnung, keine Service-Meldung.

Und in der Web-Anzeige eben auch 0% gemeldet wurden.

Das macht dann die Fehlersuche natürlich etwas komplizierter, wenn man das letztendlich nur noch am Temperaturverlauf feststellt ^^

<img width="1434" alt="image" src="https://github.com/danielperna84/hahomematic/assets/26391061/b63a50aa-238d-474d-9b3b-e645f73caa38">

Und sich 'leider' eine gewisse Regelmäßigkeit einzustellen scheint.
Was mich ebenfalls etwas irritiert - aber das kann am Thermostat selbst liegen:

Ich habe auch jetzt, nachdem die Adaptionsfahrt durch Spannungswegfall erneut gemacht wurde, keinerlei Meldung in den ServiceMessages dazu.
<img width="655" alt="image" src="https://github.com/danielperna84/hahomematic/assets/26391061/415b00c9-e1b1-4a94-8ed7-ab3158990ada">

Immerhin gibt mir das andere Thermostat, welches gerade LowBat meldet nun einen ERROR_POSITION zurück.
Dennoch zeigt mir HomeAssistant hier einen Wert für die Ventilstellung an...

btw - das wäre allerdings ggf. ein FR:
Wäre es möglich, solche Meldungen via Notification System in HomeAssistant unter zu bringen?

**Comment by SukramJ** [comment]
> Wäre es möglich, solche Meldungen via Notification System in HomeAssistant unter zu bringen?

Ich wüsste nicht wie.

**Comment by SukramJ** [comment]
> Einzig, dass der Status als "unknown" zurück gemeldet wird, wundert mich - da eben sonst in RM nichts auftaucht.
> Kein Alarm, keine Warnung, keine Service-Meldung.
> 
> Und in der Web-Anzeige eben auch 0% gemeldet wurden.

Die Logik der WebUI ist mir nicht bekannt. Die Integration verwendet nur die Werte aus der XmlRPC.
