### ISSUE TITLE
Status Springt immer wieder zurück

### ISSUE THREAD

**Issue by Peter1980FFM** [SukramJ/hahomematic#1327]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Ich kann in der Integration das Licht einschalten, dann geht es auch an, der schalter geht aber wieder zurück auf aus und das Licht kann nicht mehr ausgeschaltet werden.
Die Geräte werden Teilweise mit anderen Schaltern erkannt wo es dann geht .....
Funktioniert:
![image](https://github.com/danielperna84/hahomematic/assets/45266139/888bb572-6918-4173-84c5-13ff471c372c)
Funtioniert nicht:
![image](https://github.com/danielperna84/hahomematic/assets/45266139/477b89e3-bd84-41ff-bcaa-8f83e82dd9c2)

### What version of HomematicIP (local) has the issue?

1.3

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.73.9.20231130

### What hardware are you running for your system?

Pi3

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[home-assistant_homematicip_local_2023-12-16T12-20-38.305Z.log](https://github.com/danielperna84/hahomematic/files/13692539/home-assistant_homematicip_local_2023-12-16T12-20-38.305Z.log)

**Comment by SukramJ** [comment]
Bitte auf die aktuelle Version aktualisieren, und hänge danach die Integration-Diagnostics mit an.
Dein Grundproblem liegt darin, das dein Ha von der CCU keine Updates  empfängt.

**Comment by Peter1980FFM** [comment]
Jetzt wollte ich die Integration in der neuesten Version laden, aber in HACS kommt jetzt die fehlermeldung
<Integration danielperna84/hahomematic> Repository structure for 2023.12.2 is not compliant

**Comment by SukramJ** [comment]
Was machst Du da?
Wenn Du die Integration mit HACS installiert hast, dann geht man in HACS und aktualisiert die Integration.
Dann muss man nicht erneut ein Repository hinzufügen, das zudem noch das falsche ist. Siehe Installationsanleitung.

**Comment by Peter1980FFM** [comment]
Habe jetzt den Home Assistant neu Aufgesetzt und jetzt geht die Integration mit allem sehr seltsame
