### ISSUE TITLE
Probleme mit HMIP Broll

### ISSUE THREAD

**Issue by JensHowi** [SukramJ/hahomematic#1330]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hallo zusammen,
ich bin neu in der Materia HomeAssistant, habe bisher nur die Raspberrymatic auf einem Pi3 betrieben. Damit das ein oder andere vielleicht ein wenig für die anderen Mitbewohner visualisiert werden kann, habe ich mir mal auf einer Windows-VM HA als "Testinanz" aufgebaut.

Mit als letztes folgte bei mir die Integration der Raspberrymatic über "HomematicIP_Local". Alle Aktoren werden dort soweit korrekt angezeigt. Probleme macht mir jedoch der HMIP Broll, welchen ich überall als Rollladenaktor verbaut habe.

Zum einen bekomme ich dort nur Ereignisse und Diagnose-Daten angezeigt und beim Starten von HA bekomme ich noch eine Fehlermeldung. Aktuell ist es mir nicht möglich, die Rollläden über HA zu steuern. Was mache ich noch falsch, bzw. was fehlt mir?
Vielleicht könnt ihr mir helfen. Danke

### What version of HomematicIP (local) has the issue?

1.50.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.73.9

### What hardware are you running for your system?

Hyper-V on Win11 Pro

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [x] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

![291067664-661de242-573d-435f-bdbb-4a436759dfdd](https://github.com/danielperna84/hahomematic/assets/153711552/0b1f26bd-8f14-4d73-8b45-2b3d088bc131)

### Anything in the logs that might be useful for us? The log (full log) is the best source to support trouble shooting!

```txt
2023-12-17 20:06:54.033 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform 'homematicip_local.cover': Platform not found (No module named 'custom_components.homematicip_local.cover').
```

**Comment by SukramJ** [comment]
Bitte noch die Diagnoseinformationen der Integration anhängen.
Vom Log hätte ich gerne das detaillierte Log(auf vollständiges Protokoll laden klicken)

**Comment by JensHowi** [comment]
2023-12-17 21:42:41.521 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration homematicip_local which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
-12-17 21:42:44.155 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform 'homematicip_local.cover': Platform not found (No module named 'custom_components.homematicip_local.cover').

**Comment by SukramJ** [comment]
**Bitte noch die Diagnoseinformationen der Integration anhängen.**

**Comment by JensHowi** [comment]
Ich hab dir alles geliefert, was die kiste her gibt. 
Deine Kommunikation ist bisher alles andere als höflich.

**Comment by SukramJ** [comment]
> Deine Kommunikation ist bisher alles andere als höflich.

Was erwartest Du? Soll ich Romane schreiben in denen ich um deine Gunst bettele?
Ich versuch hier kurz und knapp die benötigten Fakten abzufragen, aber leider klappt das nicht so ganz, deswegen muss ich nachfragen. 

Ohne die Diagnoseinformationen brauchen wir nicht weiter machen.
Im Issue hab ich extra eine Beschreibung eingebaut, wie man an die Diagnoseinformationen kommt:

```
Diagnostics information
This integrations provides the ability to [download diagnostic data](https://www.home-assistant.io/docs/configuration/troubleshooting/#debug-logs-and-diagnostics).
It would really help if you could download the diagnostics data for the device you are having issues with, and drag-and-drop that file into the textbox below.
```

Nach welcher Installationanleitung bist Du vorgegangen?

**Comment by JensHowi** [comment]
Wird geschlossen. Installation war nicht vollständig, da über WLAN verbunden war. Virtuelle Umgebungen unterstützen kein WLAN.
Hinweis kam aus einem anderen Forum, aufgrund der hier aufgeführten Fehlerbeschreibungen!

**Comment by SukramJ** [comment]
> Hinweis kam aus einem anderen Forum, aufgrund der hier aufgeführten Fehlerbeschreibungen!

Und welcher Punkt soll das sein?

**Comment by SukramJ** [comment]
Falls noch jemand auf diese Issue stösst und eine Lösung sucht:

> Wird geschlossen. Installation war nicht vollständig, da über WLAN verbunden war. Virtuelle Umgebungen unterstützen kein WLAN.

Richtig konfiguriert unterstützen virtuelle Umgebungen auch WLAN, aber das ist hier nicht das Problem.

> Alle Aktoren werden dort soweit korrekt angezeigt. 

Die Integration ist in der Lage eine Kommunikation zur CCU/RM aufzubauen und Geräte zu laden, ob auch eine Steuerung möglich war, ist aus dem Eingangspost nicht ersichtlich, aber aufgrund der ausbleibenden Fehlermeldungen (Ping/Pong Mismatch) wahrscheinlich.

Das Problem aus dem Log ist, das HA die `cover` Komponente der Integration nicht findet. 
Warum lässt sich aufgrund fehlender Informationen nicht sagen.

Ich kann aber mit Sicherheit sagen, das ein Kommunikationsproblem nicht ursächlich ist, ansonsten wäre das Log voller Fehlermeldungen.

**Comment by JensHowi** [comment]
-12-17 21:42:44.155 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform 'homematicip_local.cover': Platform not found (No module named 'custom_components.homematicip_local.cover').

Der hat gereicht. Da kam der Hiinweis, dass das Modul nicht gefunden werden konnte. Nächster Check Prüfung der Installation und siehe da, diese war nicht vollständig. Ab in die Doku von Hyper-V/VirtualBox. Dort ist beschrieben, dass die Netzwerkbrücke nicht über WLAN funktionstüchtig ist.

**Comment by SukramJ** [comment]
> Platform not found (No module named 'custom_components.homematicip_local.cover').

Das ist der Hinweis, das eine lokal liegende Datei nicht gefunden werden konnte, und das hat nichts mit Netzwerkkommunikation zu tun!

**Comment by JensHowi** [comment]
Wenn etwas nicht gefunden wird, woran könnte es liegen? Erste Prüfung, kann es denn überhaupt transferiert werden? Antwort,  nein konnte es nicht aufgrund vom Netzwerkschwierigkeiten.

**Comment by SukramJ** [comment]
Warum schreibst Du das dann:

> Alle Aktoren werden dort soweit korrekt angezeigt.

??

Es gibt keinen Unterschied zwischen cover und den restlichen Plattformen.
Hast Du eigentlich mal geprüft, ob die Datei da liegt?


Aber egal. Wenn es bei dir läufts,  ist doch Super. Schönen Tag noch.
