### ISSUE TITLE
No switch/light entities generated for actor channels (-BSL, -BSM,...)

### ISSUE THREAD

**Issue by epruesse** [SukramJ/hahomematic#1336]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Switches don't seem to have their primary actor channel(s) mapped to an entity in HA.

E.g, I have a `BSM` that shows all of it's attribute entities, but no switch (channel 4-6 normally). Or a `BSL` which created entities for the two LED backlit buttons, but no `light` entity for the actual switched light. Or `PCBS` that should have it's relay as actor/switch-entity, but nothing is showing at all. 

### What version of HomematicIP (local) has the issue?

1.5.20b0

### What was the last working version of HomematicIP (local)?

NA

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.63.8

### What hardware are you running for your system?

PI5

### Which config details do you use

- [ ] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[config_entry-homematicip_local-2effc1c935edb6c2134eca047d5e97a6.json.txt](https://github.com/danielperna84/hahomematic/files/13762928/config_entry-homematicip_local-2effc1c935edb6c2134eca047d5e97a6.json.txt)

**Comment by SukramJ** [comment]
Please add screenshots and a not empty integration diagnostics. Which versions HA  do you use?

**Comment by epruesse** [comment]
<img width="503" alt="image" src="https://github.com/danielperna84/hahomematic/assets/2774474/dcfbd170-5468-4147-bad5-29ed6eaba5be">

**Comment by epruesse** [comment]
[config_entry-homematicip_local-2effc1c935edb6c2134eca047d5e97a6.json.txt](https://github.com/danielperna84/hahomematic/files/13763140/config_entry-homematicip_local-2effc1c935edb6c2134eca047d5e97a6.json.txt)

Fixed empty file. Apologies.

Happy to help debug, just need to know where to start. I do know a bit of Python. Challenge for me with this Hassio setup is that I don't know how to get into the container that's running HA and has the right Python env installed. The issue looks to me like it isn't recognizing the Bidcos "actor" channel for the BSM/BSL switches as a light/switch entity somehow. The fancy multi-colored LED buttons work, but I can't turn light on/off.

Yes, this is a bleeding edge install. Didn't think to check whether Pi5 was fully supported yet when I clicked the button the moment I saw it available. I'll try updating the CCU next, it's a bit behind on firmwares.

**Comment by epruesse** [comment]
This looks like a more informative error:

```python
ERROR (MainThread) [homeassistant.util.logging] Exception in async_add_switch when dispatching 'homematicip_local-new-entity-2effc1c935edb6c2134eca047d5e97a6-switch': ({<hahomematic.platforms.custom.switch.CeSwitch object at 0x7f7f90b010>, <hahomematic.platforms.custom.switch.CeSwitch object at 0x7f7fcd6e10>, <hahomematic.platforms.custom.switch.CeSwitch object at 0x7f7f90b250>, <hahomematic.platforms.custom.switch.CeSwitch object at 0x7f7f9c8450>, <hahomematic.platforms.generic.switch.HmSwitch object at 0x7f7fab9a50>, <hahomematic.platforms.custom.switch.CeSwitch object at 0x7f7f8f9a90>, <hahomematic.platforms.custom.switch.CeSwitch object at 0x7f802a2890>, <hahomematic.platforms.custom.switch.CeSwitch object at 0x7f7f90ad10>, <hahomematic.platforms.custom.switch.CeSwitch object at 0x7f7f8f9d90>, <hahomematic.platforms.generic.switch.HmSwitch object at 0x7f7f8e15d0>, <hahomematic.platforms.custom.switch.CeSwitch object at 0x7f7f8f9fd0>},)
Traceback (most recent call last):
  File "/config/custom_components/homematicip_local/switch.py", line 47, in async_add_switch
    HaHomematicSwitch(
  File "/config/custom_components/homematicip_local/generic_entity.py", line 65, in __init__
    if entity_description := get_entity_description(hm_entity=hm_entity):
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homematicip_local/entity_helpers.py", line 718, in get_entity_description
    name, translation_key = get_name_and_translation_key(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homematicip_local/entity_helpers.py", line 748, in get_name_and_translation_key
    entity_desc.translation_key = hm_entity.parameter.lower()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __setattr__
dataclasses.FrozenInstanceError: cannot assign to field 'translation_key'
```

If I understand correctly, that's related to the recent change in the EntityDescription dataclass. Those are frozen, but entity helpers is trying to write?

**Comment by epruesse** [comment]
@SukramJ You were faster. I got exactly the same patch as you did.

Fixed by https://github.com/danielperna84/custom_homematic/pull/598

Thank you for very fast repair!
