### ISSUE TITLE
set_device_value throws warning and is not executed in automations or scripts. Works fine when just manually started.

### ISSUE THREAD

**Issue by captaindork** [SukramJ/hahomematic#1337]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hi there,

i am trying to change the display of an ePaper Wallswitch (WRCD) with the homematicip_local integration.
I found that this is possible via set_device_value, channel 3, COMBINED_PARAMETER, etc. which basically is exactly the same way/command i used in iobroker for the last 5 years :)
Happily this directly worked with the integration as well, when i am editing an automation or script and test to fire the service... My Display instantly updates properly. 
If i now want it to be triggered as part of an automation the display won't update... instead i get following log entry:

WARNING (MainThread) [hahomematic.client] SET_VALUE failed with TypeError 

What is the difference of just testing the exact same service and putting it in an automation/script.
(Its quite weird if you hit the run-button for the service (within a script) it works, and if you hit the run-button for the whole script containing ONLY this service it fails with this warning?!?)

Thanks for any support. Happy to provide more info as required!

### What version of HomematicIP (local) has the issue?

1.52.0

### What type of installation are you running?

Home Assistant Core

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.73.9

### What hardware are you running for your system?

NUC/i5

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Anything in the logs that might be useful for us? The log (full log) is the best source to support trouble shooting!

2023-12-25 12:55:29.686 WARNING (MainThread) [hahomematic.client] SET_VALUE failed with TypeError [cannot marshal <class 'homeassistant.util.yaml.objects.NodeStrClass'> objects]: 002A60C9950C18:3, COMBINED_PARAMETER, {DDBC=WHITE,DDTC=BLACK,DDI=0,DDA=CENTER,DDS=,DDID=2},{DDBC=WHITE,DDTC=BLACK,DDI=6,DDA=CENTER,DDS=,DDID=4,DDC=true},{R=0,IN=5,ANS=4}

**Comment by SukramJ** [comment]
Please attach the corresponding YAML code.

**Comment by SukramJ** [comment]
I think it's a better approach to go on in this [diskussion](https://github.com/danielperna84/hahomematic/discussions/176).
Basically sending commands to WRCD works for me, so i think there is no issue with the integration.

From an integrations perspective there is no difference between script, automation and manual execution. That is HA core stuff and not part of this integration.

**Comment by SukramJ** [comment]
Set the value type to string and it should work.

**Comment by captaindork** [comment]
Hi SukramJ,

don't close it too fast, before i can say thank you!!!
Value type to string made it work. So your hint made my day!
(in the linked discussion i can see the value type is not set, i had indeed used this one as a template and was happy its the same approach as i did with my other systems...)
