### ISSUE TITLE
Climate actions not working as expected

### ISSUE THREAD

**Issue by itn3rd77** [SukramJ/hahomematic#134]
**custom_component/hahomematic version (if applicable):**
0.13.1

**Home Assistant version (if applicable):**
2021.12.7

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, ...): Raspi3
- OS (Original, RaspberryMatic, debmatic/...): RaspberryMatic
- Version: 3.61.7.20211218

**Problem-relevant configuration:**

Do you use tls? yes
Do you use callback? no
Do you use username and password? yes
Which interfaces do you use? RF / HmIP

**Describe the bug**
The climate actions do not work as expected. This holds true for a single climate device and a group. 

I control my climate devices from HA and thus on the display of the coresponding devices (HM-CC-RT-DN, HmIP-eTRV) "Manu" for manual control is shown. The device in HA is always showing "Automatic". In the old integration it was showing "Heat".

![grafik](https://user-images.githubusercontent.com/2655169/148169832-3f974296-f924-44d8-958a-cb77d40f99f1.png)

But thats not the only problem. When clicking heat (which was previously like manual control) the temperature jumps to max. 30 Grad Celsius, but the icon is not active and remains on "Automatic".

![grafik](https://user-images.githubusercontent.com/2655169/148170497-c6fdf832-496e-4801-940a-44a7b94ba3ff.png)

The "Off" button is working  as expected.

**To Reproduce**
1. Go to a climate device in HA
2. Click on "Heat"

**Expected behavior**
Manual control of a climate device should show "Heat". A click on "Heat" should not be a boost to max. instead it should stay on the current temperature and put the device in manual control.

**Screenshots**
see description

**Additional context**

**Comment by SukramJ** [comment]
I can confim the 30 degree problem for HM-CC-RT-DN. Will fix it to keep the current temparature.
Please restart your CCU and HA, and retest.

I don't own a HM-CC-RT-DN, but my HmIP-eTRV-2 works as expected.

**Comment by SukramJ** [comment]
I found the manu mode issue for HM-CC-RT-DN.

**Comment by itn3rd77** [comment]
Did a restart of HA and restest with an HmIP-eTRV-2 group. The 30 degree jump is vanished but it behaves strange. Have recorded a video which is hopefully better than thousand words.

https://user-images.githubusercontent.com/2655169/148187075-2d814d62-99e8-49f1-a710-b57b3bfec8d6.mp4

**Comment by SukramJ** [comment]
Nice video. I guess there was no audio track.
But what i've seen is what i would expect.
Reason: There is no off-mode in hm -> Off-Mode means 4.5 degree.
If you press off, the temperature is set to 4.5 degree.
If you then press on heat the temperature is still 4.5 degree so status if off.
You need to move the slider to maybe 20 degree and then the mode is heat.

Switching  to auto switches to the temperature defined in a profile.
Switching  to heat will use the latest set temperature. so it's 20 degree again.
But switching to off always means switching the temparature to 4.5 degree, so going to manual uses latest set temperature which is 4.5, which means off.

Understandable?

**Comment by itn3rd77** [comment]
Yes no audio. Did'nt want to record my dogs or my breathing ;-)

Seems reasonable, except the switch from auto to heat (19th second in the video) which turn off 4.5 degree. Or did I miss something?

**Comment by SukramJ** [comment]
You switch from off to auto -> last manu temp is 4.5.

**Comment by SukramJ** [comment]
Latest relase contains fixes for man_mode and 30 degree issue.

**Comment by itn3rd77** [comment]
Updated, Re-tested. Works like a charm!

**Comment by danielperna84** [comment]
If I may add:  
When my HM-CC-RT-DN is in automatic mode and I then press the "Ein" button, the slider jumps to the maximum temp. (30,5 in my case). The same happens when I'm in manual mode and press "Ein". So even though it might be odd, it matches what has been initially reported here.

My assumption when playing with the UI back in the day was, that "On" is an _unprecise_ target level, which is why the temp. is set to the max level. This would also match the "Heat" label, which I would interpret as "make the room warm", or "dreh die Heizung voll auf".

I'm not saying how this is handled now is incorrect. But the behavior may not match the CCU-UI anymore, which might confuse users that only have used the CCU. Hence I at least want to mention the observation as a reference if this discussion comes up again in the future.

**Comment by SukramJ** [comment]
Good info. I don't own HM climate devices only HmIP, so these state changes are unknown to me.
Current behavior is more like the HmIP changes, except the transition from off to heat -> the CCU knows the last state.
Would you like to start a new discussion about that?

**Comment by danielperna84** [comment]
Nah, I think it's ok like that. I actually like this more than the CCU behavior. I'd only revisit this topic if anyone feels like this is an issue that should be addressed. Homematic devices sometimes are inconsistent, and I'm not a fan of _Extrawürste_. So as long as nobody complains I'm fine. 😁
