### ISSUE TITLE
https://github.com/danielperna84/custom_homematic is not a valid add-on repository

### ISSUE THREAD

**Issue by OlliGoDev** [SukramJ/hahomematic#1341]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I have installed HomeAssistant version Core 2023.12.4 and HACS version 1.33.0.
When adding the repository, I get the error "https://github.com/danielperna84/custom_homematic is not a valid add-on repository"

### What version of HomematicIP (local) has the issue?

1.33.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which config details do you use

- [ ] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
The simple answer is: This is not an Addon.
Please check your installation instructions.
This custom integration has to be added in HACS.
