### ISSUE TITLE
HM-LC-Sw1-PI-... lose contact

### ISSUE THREAD

**Issue by AlphaZuluNRW** [SukramJ/hahomematic#1342]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

All HM-LC-Sw1-PI...-devices lose contact after a while and become grayed out. Of course, automations etc. will no longer work.

In RaspberryMatic, the devices are also displayed as unreachable, but can be operated. In addition to "unreach", the reception quality is also output here, which is good. If you then operate the socket via RaspberryMatic, you can use them normally again in Home Assistant for some time.

Only adapter plugs that are used via HomeAssistant are affected. Devices that are still operated exclusively via Homematic work perfectly.

### What version of HomematicIP (local) has the issue?

1.520

### What was the last working version of HomematicIP (local)?

1.520

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.73.9.20231130

### What hardware are you running for your system?

Pi4

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[config_entry-homematicip_local-15d510bae692900232d14db38e5d0e95.json.txt](https://github.com/danielperna84/hahomematic/files/13800623/config_entry-homematicip_local-15d510bae692900232d14db38e5d0e95.json.txt)

**Comment by SukramJ** [comment]
The necessary [service](https://github.com/danielperna84/custom_homematic#homematicip_localforce_device_availability) handling is described in the [docs](https://github.com/danielperna84/custom_homematic#homematicip-local-documentation).

There are also some [blueprints](https://github.com/danielperna84/custom_homematic#available-blueprints) to reactivate devices that loose contact very often.
