### ISSUE TITLE
HmIP-RGBW: Light will not turn on when using transition-parameter

### ISSUE THREAD

**Issue by knonem** [SukramJ/hahomematic#1351]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hello everyone,

when using the transition-parameter while turning on the HmIP-RGBW, e.g. when activating a scene, the light will not turn on. (Without the transition parameter it will). 
I also tried to use the 'light.turn_on'-service in the developer tools with the same result. Here is the YAML when calling the service:

```
service: light.turn_on
target:
  entity_id: light.wohnzimmer_licht_schrankwand
data:
  transition: 5
```

### What version of HomematicIP (local) has the issue?

1.52.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.73.9.20231130

### What hardware are you running for your system?

Pi4

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Anything in the logs that might be useful for us? The log (full log) is the best source to support trouble shooting!

```txt
From Home Assistant Core Log:
2024-01-03 16:37:27.988 WARNING (MainThread) [hahomematic.client] PUT_PARAMSET failed: ClientException [XMLRPC Fault from backend: -1 Generic error (MISSING_NON_OPTIONAL_PARAMETER)] 0033E0C99248BE:1, VALUES, {'COLOR_TEMPERATURE': 4504, 'RAMP_TIME_UNIT': <TimeUnit.SECONDS: 0>, 'RAMP_TIME_VALUE': 5, 'LEVEL': 1.0}
```

**Comment by SukramJ** [comment]
A transition to ... which brightness value?

**Comment by knonem** [comment]
In the example I mentioned, I didn't specifically add a brightness value when calling the service. The service will then use the default brightness of 100%. The log-message I added shows that the brightness value was passed forward correctly { ..., 'LEVEL': 1.0}.
I now also tried to add a brightness value to the service-call with the same result: Works without the transition parameter, but not when using it.

**Comment by SukramJ** [comment]
> The service will then use the default brightness of 100%.

Thanks, good to know.

**Comment by SukramJ** [comment]
Please try this service call, and replace the device_address and  the channel (1-4) with the correct one. 

```
service: homematicip_local.put_paramset
data:
  device_address: "6789"
  channel: 1
  paramset_key: VALUES
  paramset:
    RAMP_TIME_UNIT: 0
    RAMP_TIME_VALUE: 5
    LEVEL: 1
```

**Comment by knonem** [comment]
That will give me a similar error:
PUT_PARAMSET failed: ClientException [XMLRPC Fault from backend: -1 Generic error (MISSING_NON_OPTIONAL_PARAMETER)] 0033E0C99248BE:1, VALUES, {'RAMP_TIME_UNIT': 0, 'RAMP_TIME_VALUE': 5, 'LEVEL': 1}

**Comment by SukramJ** [comment]
The question is now: What is the `MISSING_NON_OPTIONAL_PARAMETER` ?
I don't know!

Please create a program in the CCU and check what is needed for a transition.

**Comment by SukramJ** [comment]
Please try:

```
service: homematicip_local.put_paramset
data:
  device_address: "0033E0C99248BE"
  channel: 1
  paramset_key: VALUES
  paramset:
    RAMP_TIME_UNIT: 0
    RAMP_TIME_VALUE: 5
    LEVEL: 1
    HUE: 9
    SATURATION: 80
```

**Comment by SukramJ** [comment]
Also try:

```
service: homematicip_local.put_paramset
data:
  device_address: "0033E0C99248BE"
  channel: 1
  paramset_key: VALUES
  paramset:
    RAMP_TIME_UNIT: 0
    RAMP_TIME_VALUE: 5
    LEVEL: 1
    HUE: 9
    SATURATION: 0.8
```

**Comment by knonem** [comment]
They both didn't work. When creating a program in the CCU it seems to be using the COMBINED_PARAMETER parameter.
The following service call works:

service: homematicip_local.set_device_value
data:
  device_address: "0033E0C99248BE"
  channel: 1
  parameter: COMBINED_PARAMETER
  value: L=80,OT=111600,RT=1,TC=6000,RTTOV=0,RTTOU=0
  value_type: string

I'm only not yet sure, what all the single parameters mean: L = LEVEL, RT= RAMP_TIME, TC=COLOR_TEMPERATURE, RTTOU=RAMP_TIME_TO_OFF_UNIT, RTTOV=RAMP_TIME_TO_OFF_VALUE, ...?
OT= no idea.

**Comment by SukramJ** [comment]
Found on https://homematic-forum.de/forum/viewtopic.php?f=58&t=78673&start=20:


L Level = Helligkeitswert [0-100] Integer als % Wert; 0 = Aus; 100 = Ein; 101 = Ignorieren
OT On Time = Einschaltdauer [0 - 108000] Basiseinheit: Sekunden; mit 0 = Dauer an = 31 hrs
RT Ramp (up) Time = Rampenzeit [ 0 - ?? ] Basiseinheit: Sekunden
H Hue = Farbwert "H" [0° - 360°] in Grad
SAT Saturation = Sättigung = "S" [0-100] Integer als % Wert
RTTOV Ramp Time to OFF Value = Ausschalt-Rampenzeit Dauer [ 0 - ?? ] Ausschalt-Rampenzeit: Wert
RTTOU Ramp Time to OFF Unit = Ausschalt-Rampenzeit-Einheit {0, 1, 3} Ausschalt-Rampenzeit: Wert 0 = sec; 1 = min; 3 = ms

**Comment by knonem** [comment]
Ok, I played around a little and the only thing missing compared to the original parameters seems to be DURATION_UNIT and
DURATION_VALUE.

The following call will work and the light will transition to 100% in 5 seconds:

service: homematicip_local.put_paramset
data:
  device_address: "0033E0C99248BE"
  channel: 1
  paramset_key: VALUES
  paramset:
    RAMP_TIME_UNIT: 0
    RAMP_TIME_VALUE: 5
    DURATION_UNIT: 0
    DURATION_VALUE: 0
    LEVEL: 1

**Comment by SukramJ** [comment]
Good job!

**Comment by knonem** [comment]
For some reason, when adding a ramptime in a CCU-Program the OT-value (DURATION_VALUE?) will be 111600 instead of 0. 
I tried both, and they both worked (I'm not sure what would happen after the 111600 seconds though ;-)

**Comment by knonem** [comment]
> Good job!

thanks!

**Comment by SukramJ** [comment]
Please test with version 1.53.0b0.
Beta can be enabled in HACS.
- click on the integration
- open the menu on the upper right
- re-download
- enable show beta

**Comment by knonem** [comment]
Tested 1.53.0b0: The light will turn on as expected, but will turn off agian instantly. 

I tested again with service call homematicip_local.put_paramset as desribed above with DURATION_VALUE: 0 and there it is happening too. I'm very sorry but I would swear, that it worked with duration=0 when I initially posted the solution.
It seems that it needs to be 111600 instead of 0 after all like in the CCU-program, as I commented above after posting the initial solution.

Tripple tested with this command:

`service: homematicip_local.put_paramset
data:
  device_address: "0033E0C99248BE"
  channel: 1
  paramset_key: VALUES
  paramset:
    RAMP_TIME_UNIT: 0
    RAMP_TIME_VALUE: 5
    DURATION_UNIT: 0
    DURATION_VALUE: 111600
    LEVEL: 1`

Again, very sorry, that I didn't notice the first time...

**Comment by SukramJ** [comment]
No problem. Thanks for feedback.

**Comment by SukramJ** [comment]
Please retest with 1.53.0b1

**Comment by knonem** [comment]
1.53.0b1 shows the same behaviour as 1.53.0b0. The light is turning right off again.

**Comment by SukramJ** [comment]
Please add a debug log

**Comment by knonem** [comment]
There is no log message generated after sending the command. But the device behaves excactly as if 0 was transmitted instead of 111600.

**Comment by knonem** [comment]
ok, just found out about the option to debug an integration:
Here's the log message: 

2024-01-08 18:34:58.201 DEBUG (MainThread) [hahomematic.client] PUT_PARAMSET: 0033E0C99248BE:2, VALUES, {'COLOR_TEMPERATURE': 3105, 'DURATION_UNIT': <TimeUnit.SECONDS: 0>, 'DURATION_VALUE': 0, 'RAMP_TIME_UNIT': <TimeUnit.SECONDS: 0>, 'RAMP_TIME_VALUE': 5, 'LEVEL': 1.0}

**Comment by SukramJ** [comment]
Please add the integration diagnostics.
Click on the integration / download diagnostics.

**Comment by knonem** [comment]
[config_entry-homematicip_local-06cd027a37c2659929908f1af7e66f0a.json.txt](https://github.com/danielperna84/hahomematic/files/13864586/config_entry-homematicip_local-06cd027a37c2659929908f1af7e66f0a.json.txt)

**Comment by SukramJ** [comment]
Are you using this service call?

```
service: light.turn_on
target:
  entity_id: light.wohnzimmer_licht_schrankwand
data:
  transition: 5
```

**Comment by knonem** [comment]
yes

**Comment by SukramJ** [comment]
Please retest with the latest beta (b2).

**Comment by knonem** [comment]
I can confirm that it's working now with 1.53.0b2.
Thank you for your support and for fixing this issue!
