### ISSUE TITLE
Unexpected exception importing component custom_components.homematicip_local

### ISSUE THREAD

**Issue by Juice47** [SukramJ/hahomematic#1354]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

After Core Upgrade to 2024.1.0 homematic intergarion is not started any more. Reboot of the PI did not help.

### What version of HomematicIP (local) has the issue?

1.52.0

### What was the last working version of HomematicIP (local)?

1.52.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### What hardware are you running for your system?

PI4

### Which config details do you use

- [ ] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

Uncaught thread exception
16:52:32 – (ERROR) components/stream/worker.py
Host 192.168.1.49:443, could not verify a working RTSP url
16:52:04 – (ERROR) components/reolink/host.py - message first occurred at 16:52:02 and shows up 6 times
Setup failed for custom integration 'homematicip_local': Unable to import component: Exception importing custom_components.homematicip_local
16:51:51 – (ERROR) setup.py
Unexpected exception importing component custom_components.homematicip_local
16:51:51 – (ERROR) loader.py

### Anything in the logs that might be useful for us? The log (full log) is the best source to support trouble shooting!

```txt
n/a
```

### Additional information

N/A

**Comment by SukramJ** [comment]
This is not an error message from the integration.
HA is not able to find the integration.

Is the integration still under custom_components/custom_homematic?

Go to hacs, click on the Integration., go to the 3 dot menu on the upper right, reload integration and restart afterwards.

**Comment by Juice47** [comment]
Hi,

 

thanks, I missed the update to Custom Home Assistant Component for HomeMatic
1.52.0. Because I did not get a notification that it was available.

 

How can I make sure that I receive such notifications?

 

Cheers

Uli

**Comment by SukramJ** [comment]
> How can I make sure that I receive such notifications?

should work automatically.
Maybe you should open an issue at the hacs repository.
