### ISSUE TITLE
[HM-LC-RGBW-WM] Light effects not working

### ISSUE THREAD

**Issue by klassm** [SukramJ/hahomematic#1355]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

When enabling a light effect, the LED device shortly switches, then jumps back to the original color ignoring the selected effect. When enabling the effect via RaspberryMatic, it works works as expected.

The same thing also happens when trying to enable the effect via a service call:

```yaml
service: light.turn_on
target:
  entity_id: light.my_led
data:
  effect: Campfire
```

It quickly jumps to another color, then goes back to the original state.

![image](https://github.com/danielperna84/hahomematic/assets/498976/ac9d4266-5309-4938-b4cc-317e5a76c846)

### What version of HomematicIP (local) has the issue?

1.52.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic HA-Addon

### Which version of your homematic backend are you running?

3.73.9.20231130

### What hardware are you running for your system?

Pi4

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[home-assistant_homematicip_local_2024-01-04T18-30-00.837Z.log](https://github.com/danielperna84/hahomematic/files/13834232/home-assistant_homematicip_local_2024-01-04T18-30-00.837Z.log)

**Comment by SukramJ** [comment]
I don't have this device and therefore can't say anything about how the correct control for effects should be done. Sometimes the devices are quite unique.

What happens if you execute this service:

```
service: homematicip_local.set_device_value
data:
  device_address: REQ0192450
  channel: 3
  parameter: PROGRAM
  value: 4
```

**Comment by klassm** [comment]
Thanks :-). This properly starts the program, just like when I start it via RaspberryMatic.

**Comment by klassm** [comment]
Thank you so much! :-)

**Comment by SukramJ** [comment]
Please test with version 1.53.0b0.
Beta can be enabled in HACS.
- click on the integration
- open the menu on the upper right
- re-download
- enable show beta

**Comment by klassm** [comment]
It works just nice, perfectly fine. Absolutely awesome, thank you so much! Enjoy the rest of your Sunday evening :-)
