### ISSUE TITLE
HmIP-RGBW not (fully) working

### ISSUE THREAD

**Issue by hanshanderson** [SukramJ/hahomematic#1359]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I Have configured my HmIP-RGBW in Mode: Single Channel on raspberrymatic.

Each channel works as a single dimmer. On channel 1-3 a LED light is connected. Channel 4 currently not used. I had to activate channel 2+3 manually in ha.

Initially non of the channels were working as expected in ha. I could dim, power on but not power off the LED via home assistant device controls. Percentage value was Unknown, last update time was equal to the last reboot. Slider could be used but color stays grey, even if the LED was switched on.

During my own trouble shooting I have temporally switch to each of the other mode (RGBW, RGB, turntable white) of the HmIP-RGBW device in rasbperrymatic.

In RGBW mode channel 1 got active in ha and changed to normal operation.
In RGB mode still  only channel 1 was active.
With Turntable White mode channel2 got active in ha and changed to normal operation.

After changing back to Single Channel mode on raspberrymatic channel 1+2 are working as expected in ha now. I can dim, power on/off the LED via home assistant device controls. Percentage value, last update time and slider color are updated as expected.

But still channel 3 is not working as expected. Still the same issue as mentioned above.

![ha device control](https://github.com/danielperna84/hahomematic/assets/154376686/2b66e374-8451-4055-bc32-bcd4077f8bd5)

![ha device not working](https://github.com/danielperna84/hahomematic/assets/154376686/3d653045-13b4-4aa1-b86a-d95507a8c0d0)

### What version of HomematicIP (local) has the issue?

1.52.0

### What was the last working version of HomematicIP (local)?

never worked

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.73.9.20231130

### What hardware are you running for your system?

Pi4

### Which config details do you use

- [X] Username and password
- [X] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[config_entry-homematicip_local-ea8df8c5fd0315a7faf9cee4fc5cde87.json-2.txt](https://github.com/danielperna84/hahomematic/files/13847264/config_entry-homematicip_local-ea8df8c5fd0315a7faf9cee4fc5cde87.json-2.txt)

[home-assistant_homematicip_local_2024-01-05T22-18-46.535Z.log](https://github.com/danielperna84/hahomematic/files/13847265/home-assistant_homematicip_local_2024-01-05T22-18-46.535Z.log)

### Anything in the logs that might be useful for us? The log (full log) is the best source to support trouble shooting!

```txt
No error/warning visible in the home assitant log.
```

### Additional information

Config view in raspberrymatic:

![raspberrymatic](https://github.com/danielperna84/hahomematic/assets/154376686/bbc8342f-5af8-40ca-9aa2-e4543d81353d)

**Comment by SukramJ** [comment]
Have you restarted HA in between so that the changes (channel configuration in the ccu) on the devices are also adopted in HA?
Due to reconfigurations (dimmer to RGBW), it can also happen that entities remain that can then be deleted manually.

**Comment by hanshanderson** [comment]
I did not restart the raspberrymatic during the mode changes. But several times afterwards.

In the meantime I also deleted the device with `homaticip_local.delete_device` and cleared the cache with `homaticip_local.clear.cache`.

I checked and the device with entities was no longer visible, also the two cache files were deleted.

After rebooting the device was back and the entities for channel 2+3 need to be enabled again. But the problem was still there.

Then did the device/clear cache again and completely shut down ha. I deleted the device from rasberrymatic and rebooted. I then teached in again, switched to single channel mode and renamed the device and channels differently than before.

After booting ha, the device was back with the new device and entity names. But only channel 1 works, value state `valid`. Channel 2+3 did not work after activating the entities, value state `not valid`. Rebooting ha again did not change this.

![Screenshot 2024-01-06 at 06 26 36](https://github.com/danielperna84/hahomematic/assets/154376686/f80597ac-10dc-461f-9ef4-5e1269382752)

**Comment by SukramJ** [comment]
I don't understand what you're actually doing and what your goal is.

1. Configure the device in Raspberrymatic the way you want it. A Raspberrymatic restart is not necessary.
Test that the device behaves as desired in Raspberrymatic.
2. Describe how you configured the device in RM. The RM configuration will no longer be changed from now on.
3. So that HA is clean, delete the device from HA again with `homaticip_local.delete_device`, and to be on the safe side, clear the cache again (`homaticip_local.clear.cache`). Then restart HA.
4. Describe the entities created in HA and what you can do with them and please also attach screenshots.

**Comment by hanshanderson** [comment]
Sorry for the confusion. That was not my intention. Here is the current status and output. I'm not going to change anything anymore.

1.  Device is configured in Mode Single Channel. All 3 of the 4 channels I'm using working as expected.
![Screenshot 2024-01-06 at 13 40 32](https://github.com/danielperna84/hahomematic/assets/154376686/6fec082e-de26-42ec-a5e8-bd55b5c6ad2b)

2. Device is configured/named as following.
![Screenshot 2024-01-06 at 13 36 56](https://github.com/danielperna84/hahomematic/assets/154376686/6c32f206-3068-4cdc-ac8d-80749a79dca6)

3. Deleted device in HA, cleared the cache and rebooted.
- Before
![Screenshot 2024-01-06 at 13 48 43](https://github.com/danielperna84/hahomematic/assets/154376686/5953163d-c9aa-44a6-b53e-00c73ea96a74)
![Screenshot 2024-01-06 at 13 52 00](https://github.com/danielperna84/hahomematic/assets/154376686/9e831705-2a27-496a-a242-df05b9e9ee55)

- After
![Screenshot 2024-01-06 at 13 54 59](https://github.com/danielperna84/hahomematic/assets/154376686/87df031a-f946-4b7a-ac18-fcbd87f431b7)
![Screenshot 2024-01-06 at 13 58 10](https://github.com/danielperna84/hahomematic/assets/154376686/bfbe8ce3-d320-45e8-b3c9-04a88e4639fb)

- Reboot performed 
![Screenshot 2024-01-06 at 14 01 15](https://github.com/danielperna84/hahomematic/assets/154376686/7109d6e2-0371-4ad4-9671-b8ff71300176)

4. Status after reboot
- Device Status
![Screenshot 2024-01-06 at 14 04 18](https://github.com/danielperna84/hahomematic/assets/154376686/b1fd2740-e4b9-4d76-8145-d7328c912a2d)
![Screenshot 2024-01-06 at 14 08 49](https://github.com/danielperna84/hahomematic/assets/154376686/bb83424e-6302-42d2-9719-44550507d31f)

- Channel 1 - Entity R fully working, no issue.
![Screenshot 2024-01-06 at 14 11 44](https://github.com/danielperna84/hahomematic/assets/154376686/a6cfd3fc-ed8f-4c1f-82fb-83d000ef175a)

- Channel 2+3 - Entities VR + VL after I have enabled them, not working as expected.
Entities responding both in the same way.
I can switch them ON and OFF via the lightnig icon.
![Screenshot 2024-01-06 at 14 18 24](https://github.com/danielperna84/hahomematic/assets/154376686/52ec35f7-dbfa-49b4-bce1-c28a3f5f9bb2)

- Entitie VL + VR responding both in the same way.
I can switch them ON via power button but not OFF.
Dimmer slider is working but colour not changing to yellow.
% value remains Unknown.
Time not updating to last changes. Stays related to last reboot.
![Screenshot 2024-01-06 at 14 19 50](https://github.com/danielperna84/hahomematic/assets/154376686/ddb407d0-0811-442e-8663-21317229af81)

**Comment by SukramJ** [comment]
Much better now.

The `value state` of VL is `restored`. That means that the this channel has not received events from the CCU, and the state is restored from a HA cache. 

The `value state` should switch to `valid` after some time or when you change e.g. the level in CCU.
The log from the initial post contains events from 003920C994EB72:2, so this should basically work.

In rare cases this could be a problem with the browser cache, so refresh it or use another browser.

**Comment by hanshanderson** [comment]
Even after some hours the `value state` of VR and VL did not change, They were still at `restored`.

I have change the status (`ON, OFF, dimmer slide`) several times in RM/CCU . No update on `value state`
Clearing  browser cache of Safari didn't update is as well.

Attached a new log
[home-assistant_homematicip_local_2024-01-06T16-44-13.079Z.log](https://github.com/danielperna84/hahomematic/files/13850601/home-assistant_homematicip_local_2024-01-06T16-44-13.079Z.log)
- 17:38 trying from RM/CCU
- 17:43 trying form HA

Tested the same with Firefox and a new installation of Chrome. No `value state` update at all. Same behaviour as mention above.

![Screenshot 2024-01-06 at 18 54 50](https://github.com/danielperna84/hahomematic/assets/154376686/59265d37-c2e1-41b7-8f80-9401ca53edf7)
![Screenshot 2024-01-06 at 18 55 05](https://github.com/danielperna84/hahomematic/assets/154376686/07951c6e-65db-4176-8a4c-0af84a37063b)

**Comment by SukramJ** [comment]
At the moment I'm rather at a loss, I don't have the device, but I can simulate the events with pydevccu and I don't see any problems there.

> [custom_components.homematicip_local.generic_entity] Device changed event fired for WDW VL

In the logs you can see how a device_change event is triggered for the channel, so everything is as it should be.


How does the entity look like under developertools /states?

**Comment by SukramJ** [comment]
After looking at the code, I am pretty sure that the error is not in the integration, since WDW R works, and the same implementation is used for WDW VL and WDW VR.

What does the output look like when you run this [script](https://github.com/danielperna84/hahomematic/blob/devel/hahomematic/rega_scripts/fetch_all_device_data.fn) on the CCU?

Do you have the opportunity to install a test instance?

Alternatively at your own risk and only with a full backup:
I still wonder why the value state of the entities is still restored.
You could delete the restore file (/config/.storage/core.restore_state). This will be created again after the HA restart. This worked without any problems on my test system.

**Comment by hanshanderson** [comment]
Here the screenshot from developertools /states:
![Screenshot 2024-01-07 at 00 39 43](https://github.com/danielperna84/hahomematic/assets/154376686/d824c73a-37f2-48cd-acf4-123db85cab2e)

And the output of the script, limited to the HMIP-RGBW device:
[fetch_all_device_data_HMIP-RGBW.txt](https://github.com/danielperna84/hahomematic/files/13853459/fetch_all_device_data_HMIP-RGBW.txt)

Looks good to me as everything is identical.

I will set up a test system before messing around with the production HA.

**Comment by SukramJ** [comment]
The data looks good.
A HA Testsystem is the better choice.

**Comment by hanshanderson** [comment]
As the HMIP-RGBW is a new device for me I have added it to on older OpenHab setup I had here. Just to be more save that the HMIP device itself works as expected. 

```
Dimmer  I_Di_WDW_R  "WDW R [%.0f %%]"   <light> {channel="homematic:HmIP-RGBW:ccuip:0033E0C9923762:1#LEVEL"}
Dimmer  I_Di_WDW_VL "WDW VL [%.0f %%]"  <light> {channel="homematic:HmIP-RGBW:ccuip:0033E0C9923762:2#LEVEL"}
Dimmer  I_Di_WDW_VR "WDW VR [%.0f %%]"  <light>	{channel="homematic:HmIP-RGBW:ccuip:0033E0C9923762:3#LEVEL"}
```

Status changes on the OpenHab UI are transferred and visible in RM/CCU and vice versa.

From my point of view the HMIP device is working and sending/receiving status updates as expected.

**Comment by SukramJ** [comment]
> From my point of view the HMIP device is working and sending/receiving status updates as expected.

I don't question it. We all see the events correctly in HA. I think something is not working properly in the HA setup, beyond the integration.

**Comment by SukramJ** [comment]
I think i have found something in the script output.
More data is send for channel 1, so i have to check how to work with it in the code.

**Comment by hanshanderson** [comment]
Test system with Homeatic(IP) local 1.52.0 is setup.
![Screenshot 2024-01-07 at 16 42 09](https://github.com/danielperna84/hahomematic/assets/154376686/c55d1f24-0ab0-487f-8c35-cb3cc22fd406)

Only channel 1 came up by default. Channel 2 + 3 I had to manually activate as usual.
![Screenshot 2024-01-07 at 16 55 05](https://github.com/danielperna84/hahomematic/assets/154376686/b9006134-32d8-4688-8762-2f9cfec10703)

`Value states `after integrations has started:
- Channel 1: `valid`
- Channel 2: `not valid`
- Channel 3: `not valid`

States was still the same after 30 min without pushing any button.
Changing dimmer values on CCU  and HA later on did not change the value state.

![Screenshot 2024-01-07 at 16 52 29](https://github.com/danielperna84/hahomematic/assets/154376686/70842234-68ce-495b-a61c-22d9ea5dfa9e)

**Comment by SukramJ** [comment]
Keep you Testsystem for a while. I 'll create a beta soon.

**Comment by SukramJ** [comment]
Please test with version 1.53.0b0.
Beta can be enabled in HACS.
- click on the integration
- open the menu on the upper right
- re-download
- enable show beta

**Comment by hanshanderson** [comment]
I have already accidentally installed 1.53.0b1.

At first glance, there is no change. But I have not yet done a device delete or a cache clean. I'll have a closer look tomorrow when I get back from work.

**Comment by SukramJ** [comment]
B1 is ok.
device delete or a cache clean should not be necessary.

Please check the value_state.

**Comment by SukramJ** [comment]
I mismatched the modes. I‘ll create a new beta tomorrow.

**Comment by SukramJ** [comment]
Please retest with 1.53.0b2

**Comment by hanshanderson** [comment]
1.53.0b2 installed and is working!

View after reboot:
![Screenshot 2024-01-08 at 21 27 32](https://github.com/danielperna84/hahomematic/assets/154376686/3ae7ac4b-e8f7-409e-b84a-1ff338f1bc47)

 Channel states are all `valid` now:
![Screenshot 2024-01-08 at 21 43 53](https://github.com/danielperna84/hahomematic/assets/154376686/b54fe491-0a97-4fe6-8008-c0ad1f254003)

![Screenshot 2024-01-08 at 21 28 33](https://github.com/danielperna84/hahomematic/assets/154376686/0506e3f6-d7ff-4fab-a820-5de9034e49c1)

![Screenshot 2024-01-08 at 21 29 00](https://github.com/danielperna84/hahomematic/assets/154376686/d8b4c429-f399-43c8-b23f-2bcf95929da9)

- Power slider on control view working
- Power on/off button working
- Dimmer slider working
- % value updating
- Time updating
- All data update visible in RM/CCU and changes made there are updated in HA 

Activated channel4 to verify the settings as well. Here also everything is working as mentioned above.
![Screenshot 2024-01-08 at 21 35 19](https://github.com/danielperna84/hahomematic/assets/154376686/3709484c-86f0-4aed-9d19-30c320217831)
![Screenshot 2024-01-08 at 21 30 58](https://github.com/danielperna84/hahomematic/assets/154376686/ccbcc422-5fd3-4e65-baf5-086ba1da409b)

From my point of view all is fine now.

The only thing I'm not sure about is the **Effect** button. Im RM/CCU only the normal dimmer controls are visible but no effect settings:
![Screenshot 2024-01-08 at 22 03 43](https://github.com/danielperna84/hahomematic/assets/154376686/22ffb55b-64f1-4a3f-991f-04f6b24acb77)

If a Effect setting is doing something then the same setting (e.g. Effect 10) creates different light/flash pattern on each of the channels.

**Comment by hanshanderson** [comment]
To understand where the Effects are coming from I have played around with the settings in CCU.

Regardless of the Mode selected in Device Settings, you can configure the effects on channel 0 in the CCU:
![Screenshot 2024-01-08 at 22 25 33](https://github.com/danielperna84/hahomematic/assets/154376686/13ee375c-e2b4-4dfb-be79-78410aff8763)

But the effect settings are only visible under Device Control for RBGW, RGB and Turnable White mode.
![Screenshot 2024-01-08 at 22 47 38](https://github.com/danielperna84/hahomematic/assets/154376686/a518adbf-893b-4c4c-a99a-ff0f4ad1a3b6)
Screenshot from RGBW mode

I guess the effects are not meant to be available in Single Channel mode.

**Comment by SukramJ** [comment]
Thanks for reporting and extensive testing. I will remove the effects for PWM-mode the final version.

**Comment by hanshanderson** [comment]
Thank you for taking the time to review and update the code. It was a joy as I didn't expect it to be done in such a short time.

Is there something like a "Buy me a coffee" link?

**Comment by SukramJ** [comment]
Thanks for the idea, but it's not necessary. When people participate so well and stay on the ball like you do, I enjoy it too.
I don't have a "Buy me a coffee" link.
