### ISSUE TITLE
Sensors for system variables show hash sign in HA

### ISSUE THREAD

**Issue by itn3rd77** [SukramJ/hahomematic#136]
**custom_component/hahomematic version (if applicable):**
0.13.2

**Home Assistant version (if applicable):**
2021.12.7

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, ...): Raspi3
- OS (Original, RaspberryMatic, debmatic/...): RaspberryMatic
- Version: 3.61.7.20211218

**Problem-relevant configuration:**

Do you use tls? yes
Do you use callback? no 
Do you use username and password? yes
Which interfaces do you use? RF / HmIP

**Describe the bug**
I have activated "aktiviere Sensoren für Systemvariablen" (just for testing, no use case so far). The sensors are all shwon with an hash sign at the end???

![grafik](https://user-images.githubusercontent.com/2655169/148197368-c3c78954-392b-4828-812a-ab26315afd3e.png)

**To Reproduce**
-

**Expected behavior**

**Screenshots**
-

**Additional context**
-

**Comment by SukramJ** [comment]
Yes that is correct.
Systemvariables are just Strings that have no unit.
To make them displayable in charts the need a unit. That's why i selected a `#`.
You can customize it in HA, if you want an other unit.

**Comment by itn3rd77** [comment]
Ok fine.

**Comment by itn3rd77** [comment]
But maybe we should make the the Entity-ID's more unique e.g. sensor.alarmmeldungen is not very unique.

Better to prefix the sensor name with the name e.g. in my case  sensor.raspberrymatic_alarmmeldungen. Or what do you think?

![grafik](https://user-images.githubusercontent.com/2655169/148200204-0d19fbfa-b015-443c-8f39-ebb045badc28.png)

**Comment by SukramJ** [comment]
There is a unique_id in the backgroud, so you can change the entity_id (within sensor domain) to whatever you want.

**Comment by itn3rd77** [comment]
Just one more question regarding sensors for system variables. 

RaspberryMatic WebUI shows the following variables:

![grafik](https://user-images.githubusercontent.com/2655169/148338435-b0a5be93-963c-45ca-8f48-4412a9524dfb.png)

But in HA only those are visible:

![grafik](https://user-images.githubusercontent.com/2655169/148340261-2740e5d6-6c9d-4450-ab2c-9b4aa80c792e.png)

What about DutyCycle for example? This would be nice to have.

**Comment by SukramJ** [comment]
Which RF-Module do you use?

**Comment by itn3rd77** [comment]
Uhhh ... I don't know. I ordered a ready build device 2018 from Homematic-Guru.de.

Does i really mater? The system variable is shown inside RaspberryMatic WebUI and seems alive ...

![grafik](https://user-images.githubusercontent.com/2655169/148344217-546498e5-df48-45d3-91af-ce6b01a4ea8a.png)

**Comment by SukramJ** [comment]
Check your ccu device list, if there is a dedicated device for your rf-module.

**Comment by itn3rd77** [comment]
No here is no extra device shown.

**Comment by SukramJ** [comment]
Then i guess you have the old rf-module.
And yes, it matters, because the new module is a dedicated device with real sensor.
So instead of relying in SV device sensors are much better.
But i didn't know that the old one is not available as a dedicated device.

**Comment by itn3rd77** [comment]
Ok. I was so naive to think it a system variable and just shows up in HA :-(

**Comment by itn3rd77** [comment]
As my Python skills are a bit limited I fired up some curl magic to call the JSON-API service _SysVar.getAll_.

This is what is called in [client.py#L513](https://github.com/danielperna84/hahomematic/blob/f05777933d866692f357a16ce61a9f9ffd9c948d/hahomematic/client.py#L513), right?

This is the result I get, which although includes the DutyCycle. Is there some magic I missed why only "Alarmmeldungen" and "Anwesenheit" is shown in HA?

```
{
  "id": 0,
  "version": "1.1",
  "result": [
    {
      "id": "40",
      "name": "Alarmmeldungen",
      "type": "NUMBER",
      "unit": "",
      "value": "0",
      "channelId": "65535",
      "minValue": "0",
      "maxValue": "65000",
      "isLogged": false,
      "isVisible": true,
      "isInternal": true
    },
    {
      "id": "950",
      "name": "Anwesenheit",
      "type": "LOGIC",
      "unit": "",
      "value": "true",
      "channelId": "65535",
      "valueName0": "nicht anwesend",
      "valueName1": "anwesend",
      "isLogged": false,
      "isVisible": true,
      "isInternal": false
    },
    {
      "id": "5025",
      "name": "DutyCycle",
      "type": "NUMBER",
      "unit": "%",
      "value": "20.000000",
      "channelId": "65535",
      "minValue": "-1",
      "maxValue": "100",
      "isLogged": false,
      "isVisible": true,
      "isInternal": false
    },
    {
      "id": "5165",
      "name": "DutyCycle-Alarm",
      "type": "ALARM",
      "unit": "",
      "value": "",
      "channelId": "65535",
      "valueName0": "nicht ausgelöst",
      "valueName1": "ausgelöst",
      "isLogged": false,
      "isVisible": true,
      "isInternal": false
    },
    {
      "id": "41",
      "name": "Servicemeldungen",
      "type": "NUMBER",
      "unit": "",
      "value": "1",
      "channelId": "65535",
      "minValue": "0",
      "maxValue": "65000",
      "isLogged": false,
      "isVisible": true,
      "isInternal": true
    },
    {
      "id": "5335",
      "name": "WatchDog-Alarm",
      "type": "ALARM",
      "unit": "",
      "value": "",
      "channelId": "65535",
      "valueName0": "nicht ausgelöst",
      "valueName1": "ausgelöst",
      "isLogged": false,
      "isVisible": true,
      "isInternal": false
    },
    {
      "id": "7357",
      "name": "WatchDog: no-internet",
      "type": "ALARM",
      "unit": "",
      "value": "false",
      "channelId": "65535",
      "valueName0": "nicht ausgelöst",
      "valueName1": "ausgelöst",
      "isLogged": false,
      "isVisible": true,
      "isInternal": true
    }
  ],
  "error": null
}
```

**Comment by SukramJ** [comment]
I know that there is a SV. But it has been filtered out for the above reasons.
I remove the filter for Dutycycle.

**Comment by itn3rd77** [comment]
Thanks. Are the WatchDog* variables although filtered out?

**Comment by SukramJ** [comment]
Only from sensor. It's in the hub.

EXCLUDED_FROM_SENSOR = [
    "Connection",
    "pcCCUID",
    "RF-Gateway-Alarm",
    "WatchDog",
]

EXCLUDED = [
    "CarrierSense",
    "OldVal",
    "Servicemeldungen",
]

**Comment by itn3rd77** [comment]
I would suggest to leave it up to the user to disable the sensors like e.g. WatchDog. On the other side you didn't exclude those energy tracking variables (I deleted those alerady on the CCU).

**Comment by SukramJ** [comment]
It's not only energy tracking. There are also SVs from the weather station, that show the last day's value, which are not available by the devices itself.
If Watchdog is not filtered out.

**Comment by itn3rd77** [comment]
Hi,

I would like to suggest to use the the `unit` attribute from the system variable as the `unit_of_measurement` e.g.

```
    {
      "id": "5025",
      "name": "DutyCycle",
      "type": "NUMBER",
      "unit": "%",
      "value": "20.000000",
      "channelId": "65535",
      "minValue": "-1",
      "maxValue": "100",
      "isLogged": false,
      "isVisible": true,
      "isInternal": false
    },
```

If the `unit` is empty than do not set  `unit_of_measurement` for the sensor. This way the unit can be controlled by the user via CCU and is preserved and not overwriten by a `#` sign.

![grafik](https://user-images.githubusercontent.com/2655169/148903586-2d847009-2904-4761-aea4-c8937f7fc8d2.png)

What do you think?

Best regards
Ingo

**Comment by SukramJ** [comment]
As successor of pyhomematic this integration supports CCU and Homegear.
Homegear does not provide unit values, only key names and values.
So common to both is key and value.

The only sysvars on my system with a unit are dutycycle and carriersense_level, but these sysvars are only relevant if you have an old rf-module, because the new module is avalaible as a dedicated device.

Just customize the entity in HA, like i do with other sysvars.

**Comment by itn3rd77** [comment]
Forgotten about Homegear sorry.

**Comment by SukramJ** [comment]
No problem.

**Comment by emufan** [comment]
@SukramJ Closed, but related, 

> You can customize it in HA, if you want an other unit.

The unit on the left stays in #. Is this because recording stated with % and at the time only % are displayed, it will change to % or do you have another idea?

![image](https://user-images.githubusercontent.com/22775515/148959255-588fed2b-0d62-4bfc-96dc-e0c19ca74bb8.png)

```
sensor.hmip_status_dutycycle:
  state_class: measurement
  unit_of_measurement: '%'
```

**Comment by SukramJ** [comment]
Good Question. 
Go to Developer Tools -->statistics.
Are there any problems reported?

**Comment by SukramJ** [comment]
Do you use a CCU3? Then you should have a device of type RPI-RF-MOD.

**Comment by emufan** [comment]
> Are there any problems reported?

No. 

Yes CCU3. 

I'll search in HA community and/or wait for some days. Most probably a standard behavior. Thanks for your answer.

**Comment by SukramJ** [comment]
Do you have a device of type RPI-RF-MOD?

**Comment by emufan** [comment]
No.

**Comment by emufan** [comment]
> Good Question.

@SukramJ Nur weil ja alle sysvars keine Einheiten haben und es daher ja sein kann, dass nach eigener Änderung ab und an wieder die Frage kommt, bzgl. meiner Beobachtung von oben. Hier die Rückmeldung. Scheinbar nimmt die y-Achse den ersten/ätesten im Recorder vorhandenen Wert (im Displayfenster/angezeigtenDatumrange!). Daher war es vorher ewig # und nun nach purge der ältesten Werte die neue %.

![image](https://user-images.githubusercontent.com/22775515/149753268-043fedbf-4772-45aa-98f5-3818c77a728b.png)

Was ebenso auftritt und aber auch ein HA-Fehler/Feature sein wird. Auch im Hover der Werte wird diese älteste aller Einheiten (im Displayfenster/angezeigtenDatumrange!) auch für neue Werte genommen, selbst wenn diese eigentlich schon mit neuer Einheit im Recorder sind.

**Comment by ThomDietrich** [comment]
Hey friends,
I suggest to reopen this issue.

The incentive to use a "placeholder" unit as a workaround for presentation as a graph is understandable. However, it's not clean (would call it a hack) and technically speaking a hash is not commonly used for e.g. number of alarm messages.

The topic was discussed by home assistant developers here: https://github.com/home-assistant/architecture/discussions/503 -> use `state_class: measurement` (https://developers.home-assistant.io/docs/core/entity/sensor/#available-state-classes), alternatively use `unit_of_measurement=' '` (discouraged but [supported](https://github.com/home-assistant/frontend/pull/9879/files) to ease transition for integrations which resorted to this solution)

Bonus: Please cast Alarmmeldungen and Servicemeldungen to `int`. Home Assistant will show them without decimal places.

**Comment by SukramJ** [comment]
This ticket can stay closed. [See](https://github.com/danielperna84/custom_homematic/releases/tag/1.7.2)

**Comment by ThomDietrich** [comment]
Did you look into `state_class`?

Also, fancy to cast Alarmmeldungen and Servicemeldungen to int? Sounds minor but feels relevant.

**Comment by SukramJ** [comment]
i needed a solution for `sensor` and `number`, and `number` doesn't support `state_class`.

That's behind:

> Better differentiate between float and int for sysvars

I don't care about single sysvars.

**Comment by ThomDietrich** [comment]
I can see that now 👌  https://github.com/danielperna84/hahomematic/compare/1.7.1...1.7.2
Great! Thanks
