### ISSUE TITLE
One specific virtual device not reachable

### ISSUE THREAD

**Issue by EckeFL** [SukramJ/hahomematic#1360]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

A virtual device (INT0000005) is not available. All other virtual devices are available. 
The blueprint reactivate_single_device does not work.

### What version of HomematicIP (local) has the issue?

1.52.0

### What type of installation are you running?

Home Assistant Container

### What type of installation are you running for your homematic backend?

CCU2

### Which version of your homematic backend are you running?

2.61.7

### What hardware are you running for your system?

Pi4

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[home-assistant_homematicip_local_2024-01-07T15-08-11.824Z.log](https://github.com/danielperna84/hahomematic/files/13853920/home-assistant_homematicip_local_2024-01-07T15-08-11.824Z.log)

**Comment by SukramJ** [comment]
> Don't switch to DEBUG level if not requested.

Manchmal Frage ich mich, warum ich das ins Issue Template überhaupt reingeschrieben habe.

Bitte ein Log ohne DEBUG Level anhängen.

**Comment by EckeFL** [comment]
Sorry. Beim nächsten mal schick ich dann den richtigen Log. Nach einem erneuten Neustart von HA ist der Fehler leider verschwunden. Somit ist auch nichts mehr da zum loggen. Den Fehler habe ich ich spordaisch schon mehrfach beobachtet. Beim nächstem Mal kann ich dann ja einen Log Posten und das Thema hier wieder aufbringen.

**Comment by SukramJ** [comment]
Nur zum Verständnis:

Fehler und Warnungen  sind immer im Log. Erst wenn man mit diesen Informationen nicht weiter kommt, dann kann man selektiv für einige Module Debug aktivieren. Ansonsten enthält das Log tausende Zeilen, die nicht relevant sind, und man sieht so den Wald vor lauter Bäumen nicht.
