### ISSUE TITLE
Can't get integratrion running

### ISSUE THREAD

**Issue by romjana** [SukramJ/hahomematic#1362]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I can't get the integration running. Always get "connection failed see HA logs".
I have tried it with and without TLS.

### What version of HomematicIP (local) has the issue?

1.52.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.73.9.20231130

### What hardware are you running for your system?

Synology VM

### Which config details do you use

- [X] Username and password
- [X] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Anything in the logs that might be useful for us? The log (full log) is the best source to support trouble shooting!

```txt
Loginfo
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: hahomematic.central
Source: custom_components/homematicip_local/control_unit.py:770
Integration: homematicip_local (documentation, issues)
First occurred: 19:23:23 (5 occurrences)
Last logged: 19:29:17

POST method 'Session.login' failed: invalid credentials or too many sessions
ClientConnectorCertificateError[Cannot connect to host 10.1.1.118:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1006)')]]. Possible reason: 'Automatic forwarding to HTTPS' is enabled in backend, but this integration is not configured to use TLS
```

**Comment by SukramJ** [comment]
> [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate 

Disable TLS or TLS verify or use a valid certificate.

**Comment by Lemocin** [comment]
`ClientConnectorCertificateError[Cannot connect to host 10.1.1.118:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1006)')]]. Possible reason: 'Automatic forwarding to HTTPS' is enabled in backend, but this integration is not configured to use TLS
`

Did you try to reconfigure with TLS enabled/dont verify?

**Comment by romjana** [comment]
Yes i tried it now:
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: hahomematic.central
Source: custom_components/homematicip_local/control_unit.py:770
Integration: homematicip_local (documentation, issues)
First occurred: 19:23:23 (7 occurrences)
Last logged: 19:52:30

POST method 'Session.login' failed: invalid credentials or too many sessions
ClientConnectorCertificateError[Cannot connect to host 10.1.1.118:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1006)')]]. Possible reason: 'Automatic forwarding to HTTPS' is enabled in backend, but this integration is not configured to use TLS

**Comment by SukramJ** [comment]
> Possible reason: 'Automatic forwarding to HTTPS' is enabled in backend, but this integration is not configured to use TLS

Da steht doch alles.
Aber wenn Du TLS aktivierst must Du TLS verify deaktivieren, weil dein Zertifikat nicht validierbar ist.

**Comment by romjana** [comment]
Vielen Dank für die Mühe, aber ich hab nix aktiviert in Homematic
![HM1](https://github.com/danielperna84/hahomematic/assets/98216237/d8c7168f-1ee1-4ec7-a19a-d5ee3e4a4e58)

**Comment by SukramJ** [comment]
> POST method 'Session.login' failed: invalid credentials or too many sessions

Dann TLS deaktivieren. Benutzername auf Gross/Kleinschreibung kontrollieren bzw. einen neuen Benutzer (Admin-Rolle) in der CCU anlegen, und [PW regeln](https://github.com/danielperna84/custom_homematic?tab=readme-ov-file#authentication) beachten.

Der Rest der [Doku](https://github.com/danielperna84/custom_homematic?tab=readme-ov-file#homematicip-local-documentation) ist natürlich  auch hilfreich.

**Comment by romjana** [comment]
Vielen Vielen DANK, ich bin schon verzweifelt gewesen!
Es war tatsächlich der User, neuen User angelegt und schon funkts!
LG aus Österreich
