### ISSUE TITLE
Uncomplete itegration of HmIP-SWSD

### ISSUE THREAD

**Issue by schnu240** [SukramJ/hahomematic#1368]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

![image](https://github.com/danielperna84/hahomematic/assets/153402727/11bef110-cd58-4746-bb8c-07fa384fba86)
These functions for the fire detector are not available in HomeAssistant.
Is there a possibility to add them to the add-on?

### What version of HomematicIP (local) has the issue?

1.5.3

### What was the last working version of HomematicIP (local)?

1.5.3

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.73.9

### What hardware are you running for your system?

Pi4

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Anything in the logs that might be useful for us? The log (full log) is the best source to support trouble shooting!

```txt
not needed for a feature request.
```

### Additional information

not needed for a feature request.

**Comment by SukramJ** [comment]
1. This is is not an add-on this is a custom integration.
2. Please use the discussion form for feature request (as already written on the issue opener)
3. A feature request should describe the expected feature, which may differ from the existing implementation.
4. It might be helpful to read the [documentation](https://github.com/danielperna84/custom_homematic?tab=readme-ov-file#homematicip-local-documentation), to find out more about integration
5. A feature of HA is to create an entity deactivate, and to [activate](https://github.com/danielperna84/custom_homematic?tab=readme-ov-file#deactivated-entities) it when needed.

Number 5 leads to the goal. Good luck.
