### ISSUE TITLE
HM-CC-RT-DN Parameters

### ISSUE THREAD

**Issue by hesi02** [SukramJ/hahomematic#1388]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hello, I have some HM-CC-RT-DN valves in use. And I would like to query the status of the valve (how wide it is open 10% - x% ...) in an automation. But this sensor is not available. Is it possible to make it available? Many thanks in advance

### What version of HomematicIP (local) has the issue?

1.5

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### What hardware are you running for your system?

Pi4

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[config_entry-homematicip_local-376aa36016b31aedb8ac8cd3b2e5ca27.json (1).txt](https://github.com/danielperna84/hahomematic/files/13977768/config_entry-homematicip_local-376aa36016b31aedb8ac8cd3b2e5ca27.json.1.txt)

**Comment by SukramJ** [comment]
It's just a deactivated entity! Activate it.

**Comment by hesi02** [comment]
Hallo,

there is no entity to activate: I´m searching für „Thermostat-Wohnzimmer-Stellmotor -> Sensor -> Ventilposition…..“

**Comment by SukramJ** [comment]
Please don't reply by email.
Add as screenshot of the device in HA.

**Comment by hesi02** [comment]
found, had an incorrect “part” name for the device. Found it and activated it - thank you very much
