### ISSUE TITLE
No local connection to raspberrymatic

### ISSUE THREAD

**Issue by atze09** [SukramJ/hahomematic#1389]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Failure
Interface Homematic hmip RF not available.
After Internet connection is not available, the integration can not access to raspberrymatic addon.
In the log, I can see the Internet up address and not the local one. Can I manually add the local one instead?

### What version of HomematicIP (local) has the issue?

1.54.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic HA-Addon

### Which version of your homematic backend are you running?

3.73.9.20231130

### What hardware are you running for your system?

Intel NUC

### Which config details do you use

- [X] Username and password
- [X] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Anything in the logs that might be useful for us? The log (full log) is the best source to support trouble shooting!

```txt
GET_ALL_DEVICE_DATA for BidCos-RF failed: ClientConnectorError [(ConnectionKey(host='de838cd8-raspberrymatic', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x7f1bcf41deb0>, proxy=None, proxy_auth=None, proxy_headers_hash=1051970753186681232), ConnectionRefusedError(111, "Connect call failed ('172.30.33.6', 443)"))]
GET_ALL_DEVICE_DATA for HmIP-RF failed: ClientConnectorError [(ConnectionKey(host='de838cd8-raspberrymatic', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x7f1bcf41deb0>, proxy=None, proxy_auth=None, proxy_headers_hash=1051970753186681232), ConnectionRefusedError(111, "Connect call failed ('172.30.33.6', 443)"))]
```

**Comment by SukramJ** [comment]
This integration has 100% nothing to do with the Internet.
However, if your infrastructure has problems with name resolution without internet, then you should look into the problem.

**Comment by atze09** [comment]
@SukramJ : Thanks for quick feedback.
But really everything here is working fine also without internet but only this integration is trying to call internet adress here is the i will add the log above now.
I also tried a restart with same issue. And i tried to check all of the setting in the addon, but i couldn't find a way to add local connection. Must be on the site of the addon or the integration.

where dows the integration obtain the IP address?

**Comment by SukramJ** [comment]
The "internet address" is from your local RM addon which refuses the connection.

Take another look at the installation instructions to see whether your firewall setup on the CCU is correct.

**Comment by atze09** [comment]
> The "internet address" is from your local RM addon which refuses the connection.
> 
> Take another look at the installation instructions to see whether your firewall setup on the CCU is correct.

I added this IP address to the firewall settings of RM addon and now it works. 
Thank you very much for helping and guiding me to solve the issue although it was not caused be this integration.
I really appreciate your support!
