### ISSUE TITLE
HM-ES-TX-WM energy counter has state class total_increasing, but its state is not strictly increasing

### ISSUE THREAD

**Issue by kramer74** [SukramJ/hahomematic#1390]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Entity sensor.hm_es_tx_wm_seq3474688_iec_energy_counter_ch1 from integration homematicip_local has state class total_increasing, but its state is not strictly increasing. Triggered by state 2781.748898 (2781.7489) with last_updated set to 2024-01-22T12:17:02.929023+00:00. 

The energy counter determines the total consumption in kWh... I suspect Home Assitant is bothered by the number of decimal places

### What version of HomematicIP (local) has the issue?

1.54.0

### What was the last working version of HomematicIP (local)?

1.54.0

### What type of installation are you running?

Home Assistant Core

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.73.9

### What hardware are you running for your system?

Tinkerboard

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.1.5",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.6",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "6.1.63-haos-raspi",
    "supervisor": "2023.12.1",
    "host_os": "Home Assistant OS 11.4",
    "docker_version": "24.0.7",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "browser_mod": {
      "version": "2.3.0",
      "requirements": []
    },
    "dwd_weather": {
      "version": "v2.1.1",
      "requirements": [
        "simple_dwd_weatherforecast==2.0.29",
        "markdownify==0.6.5",
        "suntimes==1.1.2"
      ]
    },
    "solcast_solar": {
      "version": "4.0.14",
      "requirements": [
        "aiohttp>=3.8.5",
        "datetime>=4.3",
        "isodate>=0.6.1"
      ]
    },
    "watchman": {
      "version": "0.5.1",
      "requirements": [
        "prettytable==3.0.0"
      ]
    },
    "holidays": {
      "version": "1.9.10",
      "requirements": [
        "python-dateutil>=2.8.2",
        "holidays>=0.35"
      ]
    },
    "battery_notes": {
      "version": "1.4.1",
      "requirements": []
    },
    "sun2": {
      "version": "3.1.0",
      "requirements": []
    },
    "wundergroundpws": {
      "version": "2.0.5",
      "requirements": []
    },
    "homematicip_local": {
      "version": "1.54.0",
      "requirements": [
        "hahomematic==2024.1.7"
      ]
    },
    "dwd": {
      "version": "2024.1.0",
      "requirements": [
        "defusedxml==0.7.1"
      ]
    },
    "better_thermostat": {
      "version": "1.5.0-beta4",
      "requirements": []
    },
    "waste_collection_schedule": {
      "version": "1.45.0",
      "requirements": [
        "icalendar",
        "recurring_ical_events",
        "icalevents",
        "beautifulsoup4",
        "lxml",
        "shapely"
      ]
    },
    "powercalc": {
      "version": "v1.10.0",
      "requirements": [
        "numpy>=1.21.1"
      ]
    },
    "hacs": {
      "version": "1.34.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "average": {
      "version": "2.3.1",
      "requirements": [
        "colorlog==6.7.0"
      ]
    },
    "ui_lovelace_minimalist": {
      "version": "v1.3.9",
      "requirements": [
        "aiofiles==0.8.0",
        "aiogithubapi>=22.2.4"
      ]
    },
    "webuntis": {
      "version": "v1.0.5",
      "requirements": [
        "webuntis==0.1.22"
      ]
    }
  },
  "integration_manifest": {
    "domain": "homematicip_local",
    "name": "Homematic(IP) Local",
    "codeowners": [
      "@danielperna84",
      "@SukramJ"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/danielperna84/custom_homematic",
    "homekit": {},
    "integration_type": "hub",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/danielperna84/hahomematic/issues",
    "loggers": [
      "hahomematic"
    ],
    "requirements": [
      "hahomematic==2024.1.7"
    ],
    "ssdp": [
      {
        "manufacturer": "EQ3",
        "manufacturerURL": "http://www.homematic.com"
      }
    ],
    "version": "1.54.0",
    "zeroconf": [],
    "is_built_in": false
  },
  "data": {
    "config": {
      "entry_id": "a242de78edcb2cdfb14fb8d19e0c6f83",
      "version": 2,
      "minor_version": 1,
      "domain": "homematicip_local",
      "title": "RaspberryMatic",
      "data": {
        "instance_name": "RaspberryMatic",
        "host": "192.168.77.244",
        "username": "**REDACTED**",
        "password": "**REDACTED**",
        "tls": false,
        "verify_tls": false,
        "sysvar_scan_enabled": true,
        "sysvar_scan_interval": 30,
        "callback_host": null,
        "callback_port": null,
        "json_port": null,
        "enable_system_notifications": true,
        "interface": {
          "HmIP-RF": {
            "port": 2010
          },
          "BidCos-RF": {
            "port": 2001
          }
        }
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "ssdp",
      "unique_id": "5A4993EF1B",
      "disabled_by": null
    },
    "platform_stats": {
      "binary_sensor": 34,
      "climate": 13,
      "cover": 8,
      "hub_binary_sensor": 15,
      "hub_button": 1,
      "hub_sensor": 21,
      "select": 2,
      "sensor": 65,
      "switch": 10,
      "update": 48
    },
    "devices": [
      "HM-ES-TX-WM",
      "HM-RCV-50",
      "HMIP-PS",
      "HmIP-BROLL",
      "HmIP-BS2",
      "HmIP-FALMOT-C12",
      "HmIP-FSM",
      "HmIP-RCV-50",
      "HmIP-SLO",
      "HmIP-SMO",
      "HmIP-SMO-2",
      "HmIP-STHD",
      "HmIP-STHO",
      "HmIP-SWDO-I",
      "HmIP-WRC6",
      "RPI-RF-MOD"
    ],
    "system_information": {
      "available_interfaces": [
        "CUxD",
        "BidCos-RF",
        "VirtualDevices",
        "HmIP-RF"
      ],
      "auth_enabled": true,
      "https_redirect_enabled": false,
      "serial": "**REDACTED**"
    }
  }
}

### Anything in the logs that might be useful for us? The log (full log) is the best source to support trouble shooting!

```txt
Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:288
Integration: Sensor (documentation, issues)
First occurred: 13:20:10 (2 occurrences)
Last logged: 13:20:10

Entity sensor.hm_es_tx_wm_seq3474688_iec_energy_counter_ch1 from integration homematicip_local has state class total_increasing, but its state is not strictly increasing. Triggered by state 2781.748898 (2781.7489) with last_updated set to 2024-01-22T12:17:02.929023+00:00. Please create a bug report at https://github.com/danielperna84/hahomematic/issues
Entity sensor.hm_es_tx_wm_seq3473700_iec_energy_counter_ch1 from integration homematicip_local has state class total_increasing, but its state is not strictly increasing. Triggered by state 10644.460297 (10644.4603) with last_updated set to 2024-01-22T12:17:02.880589+00:00. Please create a bug report at https://github.com/danielperna84/hahomematic/issues
```

**Comment by SukramJ** [comment]
Thanks for reporting.

Did you manually reset the counter in the CCU?
Is it the first time the error occurred?

**Comment by kramer74** [comment]
I did not reset the counter manually in the CCU. The errors appear from time to time in the logs and they have no direct impact in the energy dashboard and so on.

**Comment by SukramJ** [comment]
Thanks for feedback.

Option 1: set the `state_class: total` via HA [customize](https://www.home-assistant.io/docs/configuration/customizing-devices/#customizing-entities).
Option 2: wait for the next release
