### ISSUE TITLE
Temperature and Level Missing for a HmIP-eTRV-E

### ISSUE THREAD

**Issue by mgherzan** [SukramJ/hahomematic#1391]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

After some re-configuration done in the HmIP web interface (debmatic-based), I can no longer read the Level and the Temperature entities of a HmIP-eTRV-E device. Previously, that device was part of a heating group, but now it's independent with no other HmIP devices in the room. 

### What version of HomematicIP (local) has the issue?

1.54.0

### What type of installation are you running?

Home Assistant Container

### What type of installation are you running for your homematic backend?

Debmatic

### What hardware are you running for your system?

PI4

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[home-assistant_homematicip_local_2024-01-22T15-53-36.881Z.log](https://github.com/danielperna84/hahomematic/files/14014029/home-assistant_homematicip_local_2024-01-22T15-53-36.881Z.log)

**Comment by SukramJ** [comment]
Activate the deactivated sensors !!!
