### ISSUE TITLE
Homeassistant - HACS - RasperryMatic - HM-LAN-Gateway

### ISSUE THREAD

**Issue by swoop124** [SukramJ/hahomematic#1393]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I am new to Homeassistant and HACS. Recently I installed `Homeassistant`, `HACS` and `RaspberryMatic` as Add-On an a VM under Proxmox. Then I've added my HM-LAN-Gateway to RaspberryMatic an added some Homematic Devices. so far so good.

Now i tried to install `Homematic(IP) Local`. The installation as such was successfully and i now see a new integration has popped up. But when i try to configure it, on the last step i get his error messages:
![grafik](https://github.com/danielperna84/hahomematic/assets/75502165/9e467b86-d704-4887-b204-3e57dc2ca5ee)
Password an User are correct

This is under RasperryMatic-AddOn - Protocoll:
![grafik](https://github.com/danielperna84/hahomematic/assets/75502165/a924bfe8-1209-4970-85df-af1dab8eabfa)

There is no USB-RF or something installed only HM-LAN-GW, i will connect 3 of them, in the end.

is there a way to use the HA-Integration in HA?

### What version of HomematicIP (local) has the issue?

1.54.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic HA-Addon

### Which version of your homematic backend are you running?

3.73.9.20231130

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Anything in the logs that might be useful for us? The log (full log) is the best source to support trouble shooting!

```txt
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: hahomematic.central
Source: custom_components/homematicip_local/control_unit.py:770
Integration: homematicip_local (documentation, issues)
First occurred: 22. Januar 2024 um 16:25:42 (18 occurrences)
Last logged: 07:47:10

()
SSLError on temporary_instance-BidCos-RF: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1006)')
OSError on temporary_instance-HmIP-RF: (111, 'Connection refused')
OSError on temporary_instance-BidCos-RF: (111, 'Connection refused')
```

**Comment by SukramJ** [comment]
>  The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.

Here we expect a working backend! 
-> RF-Harware is connected to your RM, and you are able to teach in devices, or already have teached in devices.

Otherwise the CCU will not start and a connection is not possible.

**Comment by Baxxy13** [comment]
Eigentlich sollte das gehen.
Wenn mindestens 1 HM-LGW korrekt verbunden ist gibt es auch das BidCos-Interface.
Man darf dann natürlich kein HmIP oder andere nicht vorhandene Interfaces anklicken. 
Bei den Gruppen bin ich nicht sicher, erstmal ohne probieren würde ich sagen.

**Comment by swoop124** [comment]
Hello,

thanks for the Answers
In the meantime i configured other things like icloud3 v3. Through this installation i restarted HA several times.

Nachdem ich jetzt die Installation nochmal, ohne HM-IP anzuklicken, versucht hab, hat die Integration komischerweise funktioniert.
Es ist nicht so, dass ich zuvor den HA nicht mehrere Male neu gestartet hätte, aber scheinbar wurde durch die Installation von icloud3 etwas geändert, das die Installation nun begünstigt hat.

Danke für eure Hilfe.

**Comment by Baxxy13** [comment]
Mit "komischerweise" hat das eher nichts zu tun, auch nicht mit irgendeinem "icloud3".

Es ist nun mal so das die Integration nur funktioniert wenn auch nur die Sachen angehakt sind die auf der Zentrale existieren. 

Bei einer Zentrale ohne Funkmodul (aber mit verbundenen LGW) gibt es eben nichts außer BidCos-RF, also auch kein HmIP.
