### ISSUE TITLE
HmIPW-SCTHD

### ISSUE THREAD

**Issue by AndynordSee** [SukramJ/hahomematic#1394]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

HmIPW-SCTHD

Unfortunately, with the HmIPW-SCTHD only the channels are:

5:Decision value temperature - (temperature)
3:Decision value moisture - (moisture)

I'm missing the channel:
2:Decision value CO2
​
HmIPW-SCTHD

beim HmIPW-SCTHD werden leider nur die Kanäle :

5:Entscheidungswert Temperatur - (Temperatur)
3:Entscheidungswert Feuchtigkeit - (Feuchtigkeit)

mir fehlt der Kanal :
2:Entscheidungswert CO2

### What version of HomematicIP (local) has the issue?

1.54.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.73.9

### What hardware are you running for your system?

Intel NUC

### Which config details do you use

- [ ] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Add the missing parameters to [unignore](https://github.com/danielperna84/custom_homematic#unignore-device-parameters).

**Comment by Baxxy13** [comment]
Hmm, die Entscheidungswert-Kanäle haben (laut Doku) keinerlei "State-Parameter" die man unignoren könnte.

Die Frage wäre also was man mit diesen Kanälen in HA anfangen will. 
Das einzige was mir da einfällt wäre der Dienst: `Homematic(IP) Local: Parametersatz schreiben` mit dem man die Entscheidungswertparameter ändern könnte.

**Comment by AndynordSee** [comment]
Moin, das richtig ich möchte nur den Co2 wert in HA einlesen und da stellen. Den das ist ja der neue Homematic IP Wired CO2 Sensor HmIPW-SCTHD, inkl. Temperatur- und LuftfeuchtigkeitsmessungHomematic IP Wired
.

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Baxxy13** [comment]
`CONCENTRATION` liegt laut Doku in Kanal:1

Den könnte man "unignoren" und dann sollte der als Sensor-Entität verfügbar sein.

**Comment by SukramJ** [comment]
Diese Entität ist vorhanden.
RTMF und die Entität aktivieren.

**Comment by SukramJ** [comment]
Ich denke das Issue kann geschlossen werden
