### ISSUE TITLE
HomematicIP Geräte funktionieren nur teilweise (CCU3)

### ISSUE THREAD

**Issue by H2FSpawn** [SukramJ/hahomematic#1400]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hallo,
ich habe HomeAssistant als VM auf einem Proxmox Server installiert. Leider gibt es Probleme mit der Integration der Homematic IP CCU3. Die Geräte werden zwar erkannt, reagieren aber zum teil gar nicht oder nur halb.  Es wird auch ein Fehler ausgegeben "Pending Pong mismatch" Woran es liegen könnte, erschließt sich mir leider nicht. Die Firewall auf der CCU3 habe ich zu Testzwecken maximal geöffnet.

### What version of HomematicIP (local) has the issue?

1.54.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

	3.73.9

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[home-assistant_homematicip_local_2024-01-26T19-13-31.799Z.log](https://github.com/danielperna84/hahomematic/files/14068574/home-assistant_homematicip_local_2024-01-26T19-13-31.799Z.log)

**Comment by SukramJ** [comment]
Bitte die Integration Diagnostics anhängen.

Ist die Firewall in Proxmox aktiv? Die CCU muss eine Verbindung zu HA aufbauen können.

**Comment by H2FSpawn** [comment]
Vielen Dank! Das war der entscheidende Hinweis. Mir war nicht bewusst, das ich in meinem Router nicht nur eine Freigabe von HA in das Vlan wo die CCU3 sitzt geben muss, sondern auch in die andere Richtung. Jetzt klappts.
