### ISSUE TITLE
Magnetkontakt nur noch Update Status

### ISSUE THREAD

**Issue by LegatusPlauzus** [SukramJ/hahomematic#1402]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Seit einem Update (kann leider nicht sagen welches) zeigen die Magnetkontakte keinen Offen/Geschlossen Status mehr. Die Geräte haben nur noch eine Update Entität. Diese zeigt aber nicht die Informationen ob Offen/Geschlossen. In den deaktivierten ist leider auch nichts dabei.
Eine Neueinrichtung brachte das selbe Ergebnis. 
Was kann ich tun?

![grafik](https://github.com/danielperna84/hahomematic/assets/8740935/ad480390-6a7f-42a2-aefd-4bf825504b07)

### What version of HomematicIP (local) has the issue?

1.37.1

### What was the last working version of HomematicIP (local)?

1.x.x

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.73.9

### What hardware are you running for your system?

Proxmox VM

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[config_entry-homematicip_local-ab608a1483c6252a0d55b2452dea7bc7.json.txt](https://github.com/danielperna84/hahomematic/files/14071441/config_entry-homematicip_local-ab608a1483c6252a0d55b2452dea7bc7.json.txt)

**Comment by SukramJ** [comment]
>   I am running the latest version of the custom_component (and Home Assistant)

Ich würde mal ein Update machen. Aktuell ist die Version 1.54.0
