### ISSUE TITLE
Redundant name part in entity_id in device sensors/diagnostic

### ISSUE THREAD

**Issue by noxhirsch** [SukramJ/hahomematic#141]
Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
0.15.0

**Home Assistant version (if applicable):**
2021.12.8

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, ...): Synology Virtual Machine
- OS (Original, RaspberryMatic, debmatic/...): RaspberryMatic
- Version: 3.61.7.20211218

**Problem-relevant configuration:**

Do you use tls? No
Do you use callback? No
Do you use username and password? Yes
Which interfaces do you use? HM, HmIP, Groups

**Describe the bug**
When adding a new device, part of the name in the entity_id is redundant (see screenshot below)

**To Reproduce**
1. Add new device to Homematic
2. Reload Homematic(IP) Local
3. Go to settings of the new device in HA
4. In Sensors & Diagnostic you can see the redundant name part in the entity_ids

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/30938717/148603622-6b3e1b05-4ff7-4b54-a2ba-7db54791f69f.png)

**Additional context**

**Comment by SukramJ** [comment]
Please make a screenshot of your ccu channels

**Comment by noxhirsch** [comment]
![image](https://user-images.githubusercontent.com/30938717/148607258-81dce18e-f241-4332-883c-1f1511849c7a.png)
I forgot to rename them before reloading Homematic(IP) Local

**Comment by SukramJ** [comment]
When did you first install?
Option1: There is a service called` hahm.delete_device` that removes a single device from HA (not CCU). Then reload the integration or restart HA.
Option2: Is it possible to delete the integration and add it again?

**Comment by noxhirsch** [comment]
On my main HA server I installed this integration about 2 weeks ago.
Option 1 helped - after deleting and reloading everything was named perfectly fine.
Tomorrow I can investigate further, if that redundant name appears again - and also test it with a freshly added integration on my second HA server.

**Comment by SukramJ** [comment]
One a second view: Looks like you initially had an issue with json, because your entity id contains the unique_id. The unique_id is only used when json call is not possible. So best would be you reinstall the integration to get a clean setup.

**Comment by danielperna84** [comment]
If I may add: when you add a new device, hahomematic should notice that because of the call of `newDevices`. This happens even before the user has a change to rename the channels on the CCU. That's one of the reasons why the pyhomematic based integration was always reloading the names on every start because they could have changed.

Maybe a service to refresh the name cache manually would make sense?

**Comment by SukramJ** [comment]
A `reload integration` will refresh the names cache.
A restart will not refresh the name cache.
There is a service called `hahm.delete_device` that removes a single device from HA (not CCU). This service erases all information for this device from all caches. A `reload integration` or a HA restart will add it again with fresh data.

**Comment by noxhirsch** [comment]
Is it maybe possible to block new devices until a reload of the integration (or auto-delete)? I thought anyway that I have to reload the integration to see new devices (that's why I wrote that in the issue template). I only saw later that the new device shows up immediately in HA - just with the original name of the device.
The only other solution would be, that you'd have to delete every newly added device before reloading (or rename everything manually).

**Comment by SukramJ** [comment]
`0.16.0` fixes the redundant name parts. 

> The only other solution would be, that you'd have to delete every newly added device before reloading (or rename everything manually).

This is current state. Without a `hahm.device_delete` a reload will fetch the names, but the the entity_id will not change.
Other possible options like blocking, auto-delete, .. sound simpler than they are, and have other disadvantages.

**Comment by noxhirsch** [comment]
> 0.16.0 fixes the redundant name parts.

Thank you! Tested and working 👍

> Other possible options like blocking, auto-delete, .. sound simpler than they are, and have other disadvantages.

I can imagine that - it was just an idea I had in mind. I can live with deleting new devices first and then reloading :)
