### ISSUE TITLE
Service Climate Away Mode (still) not working correctly

### ISSUE THREAD

**Issue by stefangries** [SukramJ/hahomematic#1420]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [x] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

This is a follow-up of #1271 which actually did not fix the problem. I apologize that I have waited until now to test the service again. Setting the vacation mode still sets the wrong times in the ccu. 

When setting start and end time, this leads to the vacation mode not starting and setting a wrong end date:
![mitStart](https://github.com/danielperna84/hahomematic/assets/10342151/52090ada-f408-4314-b063-1dcd18bdb67a)

When only setting end time, this leads to the vacation mode starting instantly, but with the wrong end date:
![ohneStart](https://github.com/danielperna84/hahomematic/assets/10342151/ec676f1f-d807-4ef3-adc2-cf00179ab17d)

### What version of HomematicIP (local) has the issue?

1.54.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic HA-Addon

### Which version of your homematic backend are you running?

3.73.9.20240130

### What hardware are you running for your system?

Intel NUC

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by stefangries** [comment]
I think the problem is here:
https://github.com/danielperna84/hahomematic/blob/f27058f831384c1a55da01f62f4f4dfca69d6f9e/hahomematic/platforms/custom/climate.py#L573-L574
as the variable is a constant value:
https://github.com/danielperna84/hahomematic/blob/f27058f831384c1a55da01f62f4f4dfca69d6f9e/hahomematic/platforms/custom/climate.py#L36

**Comment by SukramJ** [comment]
Warum soll das ein Problem sein? Bitte erklären.

Wiederhole deine Tests doch mal mit realistischen Werten. Die wenigsten werden gleich für 1 Minute in den Urlaub gehen.

Wenn ich bis zum 10.2. oder vom 9.2. bis 10.2. aktiviere sehe ich da kein Problem.

**Comment by stefangries** [comment]
Hallo, danke für deine Antwort.

Ich habe das ganze jetzt nochmal mit den von dir vorgeschlagenen Parametern versucht. Das führt bei mir dazu, dass der Urlaub mit der falschen Temperatur und sofort startet, dafür aber den korrekten Endzeitpunkt anzeigt.

![image](https://github.com/danielperna84/hahomematic/assets/10342151/28d84a28-a63c-4d18-8f95-70b05fbcbb93)

**Comment by SukramJ** [comment]
Und am 9. geht dann die Temperatur auf 18 Grad.

**Comment by SukramJ** [comment]
Wenn du den Urlaubsmodus über die CCU einstellst wirst du die gleich Darstellung haben.

**Comment by stefangries** [comment]
> Wenn du den Urlaubsmodus über die CCU einstellst wirst du die gleich Darstellung haben.

Da hast du recht. War mir nicht klar und finde die Anzeige verwirrend.

> ... Urlaub mit der falschen Temperatur und sofort startet, dafür aber den korrekten Endzeitpunkt anzeigt. ...

Wenn das was du schreibst, korrekt ist, dann verändert sich die Temperatur zum Beginn des Urlaubs noch auf den korrekten Wert. 

Was mir allerdings komisch vorkam, ist, dass gleichzeitig sich auch die aktuelle Temperatur geändert hatte. Mglw. ist bei mir der Service Call allerdings genau mit einer Temperaturänderung im Wochenplan zusammengefallen, sodass ich dachte, dass der Service Call die Temperatur bereits vor Urlaubsbeginn schon verändert hat...

Btw: Anscheinend rundet die CCU die Zeiten auf eine halbe Stunde. Kann also sein, dass sie zusammenfallen, wenn der Abstand zu klein ist...

**Comment by SukramJ** [comment]
Ich denke das Issue kann geschlossen werden.
