### ISSUE TITLE
wrong import of HBW-LC-RGBWW-IN6-DR

### ISSUE THREAD

**Issue by holzwurm83** [SukramJ/hahomematic#1424]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I need help with the HBW-LC-RGBWW-IN6-DR. I have two of this and on RaspberryMatic I don’t have any problems.

I don´t use the HBW-LC-RGBWW-IN6-DR for RGB strips. I´m useing it vor 3 white strips.

On this page is written, you can use it for 2 RGB-strips, 1 RGBWW or 3 CW+WW-strips like 6 canal mode.
https://haus-bus.secure-stores.de/?showProduct=9

I´m use it with 3 CW+WW-stripe like 6 canal mode.

My problem is now that I have only two channels (1-2) like the picture below.

![](https://community-assets.home-assistant.io/original/4X/6/3/b/63b48458bd36de0010f34a1a310802b84892c55b.png)

And four canal (4-6) looks like this picture.

![](https://community-assets.home-assistant.io/original/4X/9/0/3/9035d4f59f8030fa0edbf5a15991b3aaf36a6ce2.png)

If canal 1or 2 is on and I put canal 3 on, than 2 chance to off.
I need all canals like first picture.

So, is it possible to fix the define of HBW-LC-RGBWW-IN6-DR? If not, how I can do it?

### What version of HomematicIP (local) has the issue?

1.54.0

### What was the last working version of HomematicIP (local)?

not work

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.73.9.20231130

### What hardware are you running for your system?

PI3

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [X] BidCos-Wired (HM-Wired)

### Diagnostics information (no logs here)

[config_entry-homematicip_local-8d3ece07cc2647596aa32487aa59b9a1.json.txt](https://github.com/danielperna84/hahomematic/files/14225112/config_entry-homematicip_local-8d3ece07cc2647596aa32487aa59b9a1.json.txt)

**Comment by SukramJ** [comment]
I'm sorry, but I have to say that I have little motivation to read about these homebrew devices. The homebrew devices are very special, differ from the normal eQ3 approach, and are only used by a few users.
Unfortunately I can't do anything with the information from the link.

For me it is not clear from the existing device descriptions how one should be able to switch between the operating modes.
Either you can follow up with the information, or there is someone else who can do it.
I will therefore close the issue and convert it into a discussion/feature request.
