### ISSUE TITLE
hdm blind devices stop working after update to 1.56.0b0

### ISSUE THREAD

**Issue by sander76** [SukramJ/hahomematic#1431]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

The latest beta update seems to break controlling hdm (hdm1 and hdm2) blinds.

see below log output:
```
Logger: hahomematic.client
Source: custom_components/homematicip_local/cover.py:160
Integration: Homematic(IP) Local (documentation, issues)
First occurred: 19:31:24 (1 occurrences)
Last logged: 19:31:24

SET_VALUE failed with ClientException [XMLRPC Fault from backend: -5 Invalid parameter or value]: 00004481510117:2, COMBINED_PARAMETER, L2=0,L=10
```

### What version of HomematicIP (local) has the issue?

1.56.0b0

### What was the last working version of HomematicIP (local)?

1.55

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic HA-Addon

### Which version of your homematic backend are you running?

3.73.9.20240130

### What hardware are you running for your system?

Pi3

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
Logger: hahomematic.client
Source: custom_components/homematicip_local/cover.py:160
Integration: Homematic(IP) Local (documentation, issues)
First occurred: 19:31:24 (1 occurrences)
Last logged: 19:31:24

SET_VALUE failed with ClientException [XMLRPC Fault from backend: -5 Invalid parameter or value]: 00004481510117:2, COMBINED_PARAMETER, L2=0,L=10
```

**Comment by SukramJ** [comment]
Please retest with 1.56.0b1

**Comment by sander76** [comment]
It works! thanks a 1000!
