### ISSUE TITLE
CCU user name and password?

### ISSUE THREAD

**Issue by DTekNOdev** [SukramJ/hahomematic#1436]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hi, I have trouble configuring the Homematic IP local integration. During the integration flow I am asked for the CCU user name and password. How do I create a new user? I couldn't find that information anywhere. I can only find how to add a new mobile phone in the Homematic IP app, but that seems to be something else?

### What version of HomematicIP (local) has the issue?

1.55.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### What hardware are you running for your system?

RPi3

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Are you really using the CCU? Looks more like your using the Accesspoint with the App, and then this is the wrong integration!

**Comment by SukramJ** [comment]
But if you are a CCU user then you should go to the CCU WebUI and add a user there.

**Comment by DTekNOdev** [comment]
Ok thanks, I was quite confused for a while. Yes I do indeed have an access point so this integration is not the one I need. I was looking for a solution for local control of this as operation of blinds on homematic through HA seems to be very slow.
