### ISSUE TITLE
homamaticip_local does not load any more after update

### ISSUE THREAD

**Issue by Eckart0** [SukramJ/hahomematic#1439]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

After the update of HA to 2024.2.2 ant the update of Raspberrymatic ti version 3.73.9.20240130 the connection HM-HA is broken. HA does not load HomematicIP (local). 

### What version of HomematicIP (local) has the issue?

1.55

### What was the last working version of HomematicIP (local)?

1.52

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.73.9.20240130

### What hardware are you running for your system?

Odroid N2

### Which config details do you use

- [X] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [X] BidCos-Wired (HM-Wired)

### Diagnostics information (no logs here)

"Debug enable" nicht möglich
( Der Konfigurationsfluss konnte nicht geladen werden: {"message":"Invalid handler specified"} )

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
Logger: homeassistant.setup
Source: setup.py:251
First occurred: 16. Februar 2024 um 21:56:18 (1 occurrences)
Last logged: 16. Februar 2024 um 21:56:18

Setup failed for custom integration 'homematicip_local': Unable to import component: Exception importing custom_components.homematicip_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 827, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/homematicip_local/__init__.py", line 21, in <module>
    from .control_unit import ControlConfig, get_storage_folder
  File "/config/custom_components/homematicip_local/control_unit.py", line 87, in <module>
    from .support import (
  File "/config/custom_components/homematicip_local/support.py", line 128, in <module>
    class HmBinarySensorEntityDescription(HmEntityDescription, BinarySensorEntityDescription):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 835, in get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.homematicip_local


Logger: homeassistant.loader
Source: loader.py:827
First occurred: 16. Februar 2024 um 21:56:18 (1 occurrences)
Last logged: 16. Februar 2024 um 21:56:18

Unexpected exception importing component custom_components.homematicip_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 827, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/homematicip_local/__init__.py", line 21, in <module>
    from .control_unit import ControlConfig, get_storage_folder
  File "/config/custom_components/homematicip_local/control_unit.py", line 87, in <module>
    from .support import (
  File "/config/custom_components/homematicip_local/support.py", line 128, in <module>
    class HmBinarySensorEntityDescription(HmEntityDescription, BinarySensorEntityDescription):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

**Comment by SukramJ** [comment]
Please add the integration diagnostics as already requested.

**Comment by Eckart0** [comment]
The integration fails to load. The option “Enable debug” is not offered. Are there other possibilities to get the diag data?

Regards, Eckart

 

Von: SukramJ ***@***.***> 
Gesendet: Samstag, 17. Februar 2024 12:52
An: danielperna84/hahomematic ***@***.***>
Cc: Eckart0 ***@***.***>; Author ***@***.***>
Betreff: Re: [danielperna84/hahomematic] homamaticip_local does not load any more after update (Issue #1439)

 

Please add the integration diagnostics as already requested.

**Comment by SukramJ** [comment]
I don't want a debug log!
Click on the integration and download the integration diagnostics.

**Comment by Eckart0** [comment]
There is no option „Diagnoseinformationen herunterladen“ The integration refuses to load.



Shall I downgrade HM/Raspberrymatic and/or HA to help narrow down the problem?

 

Regards, Eckart

 

Von: SukramJ ***@***.***> 
Gesendet: Samstag, 17. Februar 2024 13:40
An: danielperna84/hahomematic ***@***.***>
Cc: Eckart0 ***@***.***>; Author ***@***.***>
Betreff: Re: [danielperna84/hahomematic] homamaticip_local does not load any more after update (Issue #1439)

 

I don't want a debug log!
Click on the integration and download the integration diagnostics.

**Comment by SukramJ** [comment]
Please upload the file `/config/custom_components/homematicip_local/manifest.json`

**Comment by Eckart0** [comment]
Here it is.

 

Von: SukramJ ***@***.***> 
Gesendet: Samstag, 17. Februar 2024 15:11
An: danielperna84/hahomematic ***@***.***>
Cc: Eckart0 ***@***.***>; Author ***@***.***>
Betreff: Re: [danielperna84/hahomematic] homamaticip_local does not load any more after update (Issue #1439)

 

Please upload the file /config/custom_components/homematicip_local/manifest.json

**Comment by Eckart0** [comment]
… and got me on the right track. Version 1.50 was still loaded, so the update went wrong. Now update to 1.56 and everything works. Thanks for the tips and sorry for the inconvenience. Eckart

 

Von: ***@***.*** ***@***.***> 
Gesendet: Samstag, 17. Februar 2024 15:56
An: 'danielperna84/hahomematic' ***@***.***>
Betreff: AW: [danielperna84/hahomematic] homamaticip_local does not load any more after update (Issue #1439)

 

Here it is.

 

Von: SukramJ ***@***.*** ***@***.***> > 
Gesendet: Samstag, 17. Februar 2024 15:11
An: danielperna84/hahomematic ***@***.*** ***@***.***> >
Cc: Eckart0 ***@***.*** ***@***.***> >; Author ***@***.*** ***@***.***> >
Betreff: Re: [danielperna84/hahomematic] homamaticip_local does not load any more after update (Issue #1439)

 

Please upload the file /config/custom_components/homematicip_local/manifest.json
