### ISSUE TITLE
HomematicIP (local) not available in HACS

### ISSUE THREAD

**Issue by gregwis** [SukramJ/hahomematic#1441]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

After clicking on "[ADD INTEGRATION](https://my.home-assistant.io/redirect/config_flow_start?domain=homematicip_local)"
and providing my HA address I am receiving this message (translated by Google Translator from PL):
"This integration does not support configuration via the UI. If you clicked this link from the Home Assistant website, make sure you are using the latest version of Home Assistant."

HomematicIP Cloud is available.
​
HA Core version: 2024.2.2.
UI version: 20240207.1

### What version of HomematicIP (local) has the issue?

N/A

### What was the last working version of HomematicIP (local)?

N/A

### What type of installation are you running?

Home Assistant Container

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.73.9

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by danielperna84** [comment]
Did you follow these instructions to install the integration? https://github.com/jens-maus/RaspberryMatic/wiki/HomeAssistant-Integration

**Comment by gregwis** [comment]
Thanks, it helped a lot.
Using custom repository was a key.
