### ISSUE TITLE
HA Log Error: The preset_mode is not a valid preset_mode

### ISSUE THREAD

**Issue by iHaveAstream** [SukramJ/hahomematic#1450]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hi,
Since a while I get some error in the HA log as follows and each time I either enable another preset mode for heating or switch to Auto mode:

`Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:282
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 20:51:22 (1 occurrences)
Last logged: 20:51:22

[139881380757696] The preset_mode is not a valid preset_mode: boost, none, week_program_1, week_program_2, week_program_3, week_program_4, week_program_5, week_program_6`

The presets modes that I can select in HA are named differently, at least some of them... the week programs are named "WP 1", "WP 2", etc. But "Boost" and "None" do exist under same naming.

I know that this is not an error originated by this Integration, however probably someone has an idea to get rid of it.
Apparently, everything seems to work well, means I can control everything, even though that errror comes in the log.

Thank you!

### What version of HomematicIP (local) has the issue?

1.57.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.73.9

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information (no logs here)

[config_entry-homematicip_local-4955d97c1c647201c85697b73cd283aa.json](https://github.com/danielperna84/hahomematic/files/14486733/config_entry-homematicip_local-4955d97c1c647201c85697b73cd283aa.json)

**Comment by SukramJ** [comment]
> I know that this is not an error originated by this Integration, however probably someone has an idea to get rid of it.

Yes, this is the issue tracker for the integration. For any other topic we have a discussion forum.
