### ISSUE TITLE
Configuration for gas_flow parameters of HmIP-ESI throws warning

### ISSUE THREAD

**Issue by dawnbreak** [SukramJ/hahomematic#1453]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

After updating the latest version I see a new warning in the logs about the new GAS_FLOW parameter for HmIP-ESI.

> using state class 'measurement' which is impossible considering device class ('gas')

### What version of HomematicIP (local) has the issue?

1.57.0

### What was the last working version of HomematicIP (local)?

1.56.0

### What type of installation are you running?

Home Assistant Container

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.73.9

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
2024-03-05 08:18:13.552 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.hmip_esi_gas_gas_flow (<class 'custom_components.homematicip_local.sensor.HaHomematicSensor'>) is using state class 'measurement' which is impossible considering device class ('gas') it is using; expected None or one of 'total', 'total_increasing'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/danielperna84/hahomematic/issues
```

### Additional information

In CCU3 I see that GAS_FLOW is measured in m³/h.

* [export_device_descriptions/HmIP-ESI.json](https://github.com/danielperna84/hahomematic/files/14492147/HmIP-ESI.json)
* [export_paramset_descriptions/HmIP-ESI.json](https://github.com/danielperna84/hahomematic/files/14492163/HmIP-ESI.json)

**Comment by SukramJ** [comment]
This is related to #1445

Please attach the device definition as described [here](https://github.com/danielperna84/custom_homematic#homematicip_localexport_device_definition).
