### ISSUE TITLE
Verbindung fehlgeschlagen

### ISSUE THREAD

**Issue by skyguy2002** [SukramJ/hahomematic#1458]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Ich habe gerade die RaspberryMatic per Proxmox VM installiert und wollte dies jetzt zu HA verknüpfen.
Jedoch bekomme ich die Fehlermeldung: 
![image](https://github.com/danielperna84/hahomematic/assets/128747654/cc2715f2-cbb4-46fc-a21c-27821679bb91)

Als Anmerkung, bei der CCU sind noch keine Geräte hinzugefügt, liegt das daran?
Will später ein HomaticIP AP als Gateway hinzufügen und darüber dann die Geräte.

In der Firewall der CCU sind die Ports:
80;
8082;
2098;
2099;
8082;
9092;
5435;
2000;
2001;
2002;
2010;
8181;
8701

erlaubt

### What version of HomematicIP (local) has the issue?

1.57.1

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.73.9.20240130

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Ist an RM ein Funkmodul angeschlossen?

**Comment by skyguy2002** [comment]
> Ist an RM ein Funkmodul angeschlossen?

Hey, ne, bis jetzt noch nicht. War geplant das ich statt einem USB Stick nur den HMIP-HAP anschließe. 
Laut diesem Github link zu RaspberryMatic auch problemlos möglich.
[Der Github Post](https://github.com/jens-maus/RaspberryMatic/discussions/1162)

**Comment by skyguy2002** [comment]
> > Ist an RM ein Funkmodul angeschlossen?
> 
> Hey, ne, bis jetzt noch nicht. War geplant das ich statt einem USB Stick nur den HMIP-HAP anschließe. Laut diesem Github link zu RaspberryMatic auch problemlos möglich. [Der Github Post](https://github.com/jens-maus/RaspberryMatic/discussions/1162)

Ich weiß natürlich das es in dem Post um Homematic und nicht um HomematicIP geht, aber hatte gedacht das es auch da so laufen müsste.

**Comment by SukramJ** [comment]
So funktioniert dein RM nicht.

> The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.

Hast Du dich beim Erstellen des Issue mal gefragt warum das abgefragt wird?
