### ISSUE TITLE
Status / Anregungen

### ISSUE THREAD

**Issue by guenter-ms** [SukramJ/hahomematic#146]
Hallo,

ich gebe gerne mal einen Statusbericht:

Sehr gut: Geräte und Entitäten werden sauber importiert! Auch Variablen!

######## 1 #########
Unklar: Können Variablen über die Lovelace-Oberfläche verändert werden (Buttons/Schalter/Slider für Variablen vom Typ boolean und Zahl)?

######## 2 #########
Beim Dimmer HmIP-DRDI3 sind nur die Kanäle 6, 10 und 14 als Steuerelemente angelegt. Korrekt wäre 5-7, 9-11 und 13-15, also 9 Steuerelemente.

![Bildschirmfoto 2022-01-08 um 13 27 52](https://user-images.githubusercontent.com/6253315/148644162-40778526-91df-499b-aaca-083b7cc9185c.jpg)

![Bildschirmfoto 2022-01-08 um 13 23 25](https://user-images.githubusercontent.com/6253315/148644068-cd7f86d8-29b8-4084-97f6-0fdc6ab74d44.jpg)

######## 3 ######### 
Es fehlen noch die CUxD Geräte, Beispiel siehe screenshot:

![Bildschirmfoto 2022-01-08 um 13 13 26](https://user-images.githubusercontent.com/6253315/148643741-46d0196d-2187-46a1-99e6-33acb3cc1022.jpg)

######## 4 #########
Generell wäre es sehr schön, wenn die CCU Räume den Bereichen der Geräte und Entitäten zugeordnet würden. 

######## 5 #########
Als entity-ID für Geräte und Entitäten die CCU Seriennummer zu bevorzugen. Die sind eindeutig im Gegensatz zu den Devicenames, die doppelt vergeben werden dürfen.

![Bildschirmfoto 2022-01-08 um 13 46 08](https://user-images.githubusercontent.com/6253315/148644735-7c2ff40c-a950-4f79-9447-b5e3a223a25a.jpg)

######## 6 #########
Bleibt noch die Überlegung, die CCU-Anbindung von XMLAPI auf CCU-Jack umzustellen oder separat zu veröffentlichen. Das hätte eine Menge Vorteile. Am besten da mal lesen: https://github.com/mdzio/ccu-jack

######## 7 #########
Insgesamt sollte man generischer arbeiten, um nicht auf alle Device Typen individuell eingehen zu müssen (Pflegeaufwand!!).
Ideal wäre dann 1 Gerät pro CCU-Device (so wie heute, gut!) und eine Entity pro CCU-Datenpunkt. 

Jeder Datenpunkt liefert dazu ja alle notwendigen Informationen, insbesondere den datapointType. Die grosse Menge der Datenpunkte lässt sich auf CCU Seite im CCU-Jack bereits filtern.

![Bildschirmfoto 2022-01-08 um 14 01 23](https://user-images.githubusercontent.com/6253315/148645179-10a6b7fa-a16b-4a6c-ae78-34a7d33c748a.jpg)

Das CCU addon "HQ WebUI" macht ja auch nichts anderes: Darstellung aller Geräte mit allen Datenpunkten:

![Bildschirmfoto 2022-01-08 um 14 03 13](https://user-images.githubusercontent.com/6253315/148645221-1fcd71b6-569a-4449-abaf-0e3e4f51e745.jpg)

![Bildschirmfoto 2022-01-08 um 13 55 14](https://user-images.githubusercontent.com/6253315/148644940-09682a56-e569-4c55-bf16-2f9e174e5a67.jpg)

Soweit meine 2 cents. 
Viele Grüße aus Münster
Günni

**Comment by SukramJ** [comment]
Danke für dein Feedback. 
Bitte nummeriere deine Punkte durch, dann kann man besser Bezug nehmen.

**Comment by guenter-ms** [comment]
ok, siehe oben.

**Comment by SukramJ** [comment]
zu 1
Die Variablen können im HA als Sensoren angezeigt werden. Wenn du Variablen ändern möchtest kannst Du das über den Service `hahm.set_variable_value` machen. 

zu 2. 
die Kanäle 6, 10, und 14  sind die physische Kanäle. Willst du auch die virtuellen Kanäle angezeigt bekommen, kann du das in der Konfiguration der Integration anklicken. Die Kanäle 5,9, und 13 sind nur Sensoren die in den Attributen der Kanäle angezeigt werden, sofern der Wert vom aktuellen Wert abweicht.

zu 3.
Cuxd wird nicht unterstützt, da cuxd binrpc als Protokoll verwendet. Für binrpc gibt es keine Python Implementierung.

zu 4.
Schön ja, aber aufwendig, Eine Unterstützung ist derzeit nicht geplant. 

zu 5.
Innerhalb eines Gerätes können Kanalnamen nicht doppelt vergeben werden. Innerhalb der CCU könne Gerätenamen auch nicht doppelt vergeben werden, zumindest bei meinem RaspberryMatic. 
Grundsätzlich wird für HA-Entitäten eine unique_id erstellt (inkl. SN,Kanal,Parameter). Der Name der Entität wird entsprechend den vergebenen Geräte, Kanal und Parameter Namen erstellt. Aus dem Namen generiert HA dan die entity_id, und sorgt ggf. durch anhängen eines Prefix dafür das die entity_id auch eindeutig ist. Ich sehe beim aktuellen Schema kein Problem, oder hast Du ein konkretes Beispiel. Du kannst die entity_id und Namen aufgrund der drunterliegenden unique_id natürlich nach eigenem Gusto anpassen.

zu 6.
Diese Integration verwendet nicht die XML-API (Addon) sondern die herstellereigene XML-RPC und JSON-RPC API. 
Die XML-API wird schon länger nicht mehr gepflegt, und wie das bei CCU-Jack aussieht kann wohl auch keiner sagen.
Eine Verwendung von CCU-Jack würde ich daher einfach mal ausschliessen.

zu 7.
Diese Integration verfolgt weitest gehend einen generischen Ansatz, wie du vielleicht schon auf der Startseite oder [hier](https://github.com/danielperna84/hahomematic/wiki/Homematic-Devices-supported-by-custom-entity) gelesen hast.

Um das ganze im HA sinnvoll darzustellen werden einzelne Parameter über [Filterlisten](https://github.com/danielperna84/hahomematic/wiki/Ignored-Parameters) nicht importiert.
Wenn Du dir alle Datenpunkte der CCU anzeigen lassen möchtest ist HA sicher nicht das geeignete Tool.

Ich hoffe ich hab mich einigermassen verständlich ausgedrückt.

**Comment by guenter-ms** [comment]
Vielen Dank. Hier gerne noch mein Feedback dazu:

zu 1: OK, ist aber etwas umständlich

zu 2: das ist nicht korrekt. Jeder reale Kanal hat 3 virtuelle Kanäle (5-7 dann 9-11 und 13-15), siehe screenshot. Der reale Dimmwert, der darüber errechnet wird, wird in den Kanälen 4, 8 und 12 ausgegeben und sollte als sensor anzeigbar sein.

![Bildschirmfoto 2022-01-08 um 15 54 29](https://user-images.githubusercontent.com/6253315/148648841-5b67ba0c-0263-4c82-b9d7-69be4ebecf17.jpg)

![Bildschirmfoto 2022-01-08 um 15 59 20](https://user-images.githubusercontent.com/6253315/148648999-a16acc1f-1ee7-4e68-8281-c9060cdfd68f.jpg)


zu 3: Für mich ist das leider ein K.O., da ich viele CUxD Geräte habe. Schade.

zu 4: OK, aber schade.

zu 5: Kann man so machen, in der Entity-Übersicht findet man leider die SN nicht.

zu 6: Verstehe ich. Aber es gibt immer Abhängigkeiten, ist ja bei deiner Implementierung genauso. Den Jack kann/darf man ja auch kopieren....

zu 7: Ist OK. Mit generischem Ansatz meinte ich allerdings, dass du nicht bei jedem neuen Gerätetyp tätig werden musst.  

Danke und bleib gesund.

**Comment by SukramJ** [comment]
Danke, wünsche ich dir auch.

Schade das Cuxd ein Problem für die darstellt, aber da kann ich leider nichts machen.

zu 2 Da hast du grundsätzlich recht. Wir versuchen die Darstellung in HA einfach aber sinnvoll zu gestalten.
zu 7 Jedes Gerät erscheint automatisch, wenn man es "hübscher" haben will kann man eine custom entity definieren.

Wenn ich sonst nichts für dich tuen kann, dann schliesse bitte diese Ticket.

**Comment by danielperna84** [comment]
Hier noch mein Senf als Projektinhaber zu manchen Punkten:

2. [Hier](https://github.com/danielperna84/hahomematic/discussions/17) gibt es zum Thema der Kanäle schon eine offene Diskussion.

3. Vielleicht nicht zu 100% ein K.O. Kriterium, da sich beim Home Assistant einige Geräte, die man bisher per CUxD betrieben, hat entweder nativ, oder auf anderen Umwegen nutzen kann. Gibt ja so einige Projekte, die Gerät XYZ einfach per MQTT bereitstellen.

4. Das würde dann offensichtlich voraussetzen, dass die Räume gleich benamte Pendants in Home Assistant haben. Was sollte dann passieren wenn da was fehlt? Wäre eigentlich ein separates Issue dass man mal als Feature anlegen könnte.

6. CCU-Jack ist zwar cool, aber ich zumindest habe keine Ahnung, ob das auch 100% mit Homegear funktioniert (aber ich nehme es mal an). Viel wichtiger ist jedoch, dass nicht alle User erst mal das installieren müssen bevor sie ihre CCU mit Home Assistant verheiraten können. Wenn das so wäre hätten schon direkt zu Anfang viele keinen Bock mehr drauf weil's zu viel Arbeit ist. Nicht jeder hat Spaß an solchen Spielereien. Und das allermeriste funktioniert ja schon hervorragend über XML-RPC. Da lohnt sich der Aufwand nicht.

7. Das generische ist ja genau der Ansatz den dieses Projekt verfolgt. Es sind ja nur "spezielle" Geräte bei denen man nacharbeiten muss. Und selbst bei denen kann man auch schon ohne die Nacharbeit die vermutlich wichtigsten Datenpunkte mit den automatisch generierten Entities verwenden.  
Anfangs hatte ich selbst den Anspruch wirklich alle Entities in Home Assistant zur Verfügung zu stellen. Aber das sind einfach zu viele, und eine Menge davon sind im Alltag nicht wirklich nützlich. Mag sein, dass einem Profi dann genau dieser eine Datenpunkt fehlt. Aber ich denke so wie das jetzt ist, dürfte das eigentlich für den Großteil der User eine gute Lösung sein.

**Comment by SukramJ** [comment]
Ich denke das Issue kann geschlossen werden. Sollte ich hier falsch liegen einfach wieder öffnen.
