### ISSUE TITLE
After upgrade HA the Homematic IP not wokring 

### ISSUE THREAD

**Issue by net09apphome** [SukramJ/hahomematic#1463]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Dear all,

after upgrade the HA and HACS and Homematic i get a error when HA startsup

Setup failed for custom integration 'homematicip_local': Requirements for homematicip_local not found: ['hahomematic==2024.3.1'].

Under Integration i can see that it shows - not loaded

any idea how to slove the issue ?

### What version of HomematicIP (local) has the issue?

1.58.0

### What was the last working version of HomematicIP (local)?

1.55

### What type of installation are you running?

Home Assistant Core

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### What hardware are you running for your system?

PI3

### Which config details do you use

- [x] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
This is not an issue with the integration, because your HA is not able to load a dependency.
Maybe a restart of your system helps.

**Comment by net09apphome** [comment]
done several time ! but with the same result

**Comment by SukramJ** [comment]
There is nothing i can do. The [dependency](https://pypi.org/project/hahomematic/) is available.

**Comment by net09apphome** [comment]
any idea how i can enable it -> in the settings it shows that it was loaded.
<img width="230" alt="image" src="https://github.com/danielperna84/hahomematic/assets/124444304/fa73f386-99ee-4ee1-b3f7-09b2f738ae3f">

**Comment by net09apphome** [comment]
<img width="575" alt="image" src="https://github.com/danielperna84/hahomematic/assets/124444304/ac35059b-8fc9-411f-80e2-3822d603a994">
error message

**Comment by SukramJ** [comment]
Same with other integration.

**Comment by net09apphome** [comment]
Not with all only the Homematic and Rademacher integration

Von: SukramJ
Gesendet: Donnerstag, 14. März 2024 12:41
An: danielperna84/hahomematic
Cc: net09apphome; Author
Betreff: Re: [danielperna84/hahomematic] After upgrade HA the Homematic IP notwokring (Issue #1463)

Same with other integration.

**Comment by SukramJ** [comment]
Closing this.

> There is nothing i can do. The [dependency](https://pypi.org/project/hahomematic/) is available.

If you are using core and not HAOS maybe a `pip install hahomematic==2024.3.1` in your venv helps.

There is no further hint i could give you and the loading of requirements/dependencies is part of HA and not of this integration.

**Comment by net09apphome** [comment]
Issue was solve after new update of HA - thanks for your support
