### ISSUE TITLE
update.hmip* shows wrong firmware version

### ISSUE THREAD

**Issue by RK62** [SukramJ/hahomematic#1464]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

State update.hmip_ccu3_xxxxxx_update reflects not the real firmware version.

### What version of HomematicIP (local) has the issue?

1.58.0

### What was the last working version of HomematicIP (local)?

never

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.73.9

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information (no logs here)

Info on CCU3 shows firmware 3.73.9 (with posibility on an update):

![image](https://github.com/danielperna84/hahomematic/assets/39200469/ffd9698b-4673-4154-ade8-cbedd8b7d503)

Home Assistant shows also this release:

![image](https://github.com/danielperna84/hahomematic/assets/39200469/c60be01a-459a-4312-8acf-edb2e42fea35)

State update.hmip_ccu3_xxx_update shows version 4.4.22 and no hint of newer version:

![image](https://github.com/danielperna84/hahomematic/assets/39200469/d9258b8c-45ab-401d-8104-1e83e24c84cb)

### Additional information

Big "thank you", great integration, works fine!

**Comment by Baxxy13** [comment]
4.4.22 is the Firmware-Version of your RF-Module.
This has nothing to do with the central-firmware.

**Comment by RK62** [comment]
Any other chance to make a check with the central-firmware?
Also I can't see it in any state or attribute to make a script for an own check.

**Comment by SukramJ** [comment]
There is no api method to update the central firmware.

**Comment by RK62** [comment]
Update is not necessary, but it would be very helpful to see the current version in a state.

**Comment by SukramJ** [comment]
Same answer

**Comment by RK62** [comment]
OK, if anyone else is looking for it, here is the solution:
- Create the system variable **CCU3-Firmware** on the CCU 
- Create a script on the CCU and repeated hourly with a schedule
```
string stdout;
string stderr;
string cmd;
cmd = 'cat /boot/VERSION';
system.Exec(cmd, &stdout, &stderr);
string version = stdout.StrValueByIndex("=",1);
dom.GetObject("CCU3-Firmware").State(version);
```
- Then make the variable visible in Home Assistant

**Comment by SukramJ** [comment]
Sorry, I misread you previous post.
The **current** version can be seen at the service entity.
There is no API method for the **available** version.
