### ISSUE TITLE
homematic(IP) Integration lässt sich nicht einbinden

### ISSUE THREAD

**Issue by Hacki92** [SukramJ/hahomematic#1467]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Ich kann die homematic Integration nicht konfigurieren. Anmeldedaten sind korrekt. Ein neu angelegter Benutzer mit Admin Rechten auf der CCU3 hat auch nicht geholfen.
![KonfigurationIntegration](https://github.com/danielperna84/hahomematic/assets/163772878/28460a55-1859-40d8-ba4e-c5c75380a24b)
![KonfigurationSchnittstellen](https://github.com/danielperna84/hahomematic/assets/163772878/af35707e-5d97-44b1-bff7-4fdb6a7dcb0d)
![CCU Firewall](https://github.com/danielperna84/hahomematic/assets/163772878/c438200f-a5cb-40ab-908d-5ee5ac8f5508)

### What version of HomematicIP (local) has the issue?

1,58

### What was the last working version of HomematicIP (local)?

1,58

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.61.6

### What hardware are you running for your system?

Pi5

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [X] BidCos-Wired (HM-Wired)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: hahomematic.central
Quelle: custom_components/homematicip_local/control_unit.py:769
Integration: homematicip_local (Dokumentation, Probleme)
Erstmals aufgetreten: 23. März 2024 um 23:50:52 (28 Vorkommnisse)
Zuletzt protokolliert: 11:57:04

()
```

**Comment by SukramJ** [comment]
Hast Du Homematic wired Komponenten?

**Comment by Hacki92** [comment]
Ja einige.

**Comment by SukramJ** [comment]
Was steht dem im Log (full log drücken)?

**Comment by Hacki92** [comment]
2024-03-23 22:49:50.605 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-03-23 22:49:50.606 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration homematicip_local which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-03-23 22:50:00.418 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
2024-03-23 23:50:52.572 WARNING (MainThread) [hahomematic.central] ()
2024-03-23 23:51:09.825 WARNING (MainThread) [hahomematic.central] ()
2024-03-23 23:56:18.892 WARNING (MainThread) [hahomematic.central] ()
2024-03-23 23:56:37.646 WARNING (MainThread) [hahomematic.central] ()

**Comment by SukramJ** [comment]
Entspricht das Passwort den [Regeln](https://github.com/danielperna84/custom_homematic#authentication)?
Ggf. mal einen neuen Benutzer (mit admin-role) anlegen.

**Comment by SukramJ** [comment]
Welche wired Geräte verwendest Du?
Welche Funk Geräte verwendest Du?

**Comment by Hacki92** [comment]
Hatte ich gestern schon mal probiert ohne Erfolg.
Habe es jetzt nochmal versucht mit neuem Passwort auch ohne Erfolg.

kabelgebundene Geräte: DRAP, Jalousieaktoren, Schaltaktoren, Eingangsaktoren, Präsenzmelder (über Bus)
Funkgeräte: Heizthermostate, Klingeltaster, Kombisignalgeber, Fenstersensoren, Türschlossantrieb, Zahlenfeld, Rauchmelder

**Comment by SukramJ** [comment]
Ich meinte die Gerätetypen.

HmIP-BWTH ...

**Comment by Hacki92** [comment]
Funkgeräte: HmIP-eTRV-2, HmIP-DLD, HmIP-WKP, HmIP-DBB, HmIP-SWDO, HmIP-SWSD, HmIP-BWTH, HmIP-VDMOT, HmIP-FALMOT-C12, HmIP-FAL230-C10, HmIP-MP3P

kabelgebundene Geräte: HmIPW-DRAP, HmIPW-DRBL4, HmIPW-DRS8, HmIPW-DRD3, HmIPW-DRI32, HmIPW-DRI16, HmIPW-SPI

**Comment by SukramJ** [comment]
> Hast Du Homematic wired Komponenten?

Du hast kein einziges Homematic wired Gerät.
Das sind alles HomematicIP wired Geräte.

In der Schnittstellenauswahl darf also Homematic-Wired (BidCos-Wired) nicht ausgewählt sein.

**Comment by Hacki92** [comment]
Aber die kabelgebundenen Geräte sind Hm-IPW Geräte. U.a. auch Geräte in meiner Verteilung. Sind das nicht Homematic-Wired Geräte?

**Comment by SukramJ** [comment]
Absolut nicht. Die Homematic-Wired Geräte heissen HMW-,...

**Comment by Hacki92** [comment]
Hab es ausprobiert und es funktioniert tatsächlich. Vielen Dank für die Hilfe.
