### ISSUE TITLE
Homematic Wired-classic components are not recognized

### ISSUE THREAD

**Issue by tgw-de** [SukramJ/hahomematic#1468]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hello,
I am quite new to Home-Assist and installed the Homematic-local two days ago. During the installation I also passed the point that Wired is activated. 
However, no devices are recognized on the wired (not IP). All ports are open.
Where can I search or look something up? 

Klaus

### What version of HomematicIP (local) has the issue?

1.5.8.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.75.6

### What hardware are you running for your system?

VMware-Image

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [X] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Also ich sehe da grundsätzlich kein Problem mit der Integration, da hier mehrere Leute bereits wired benutzen.
Daher wandle ich das mal in eine Diskussion.
