### ISSUE TITLE
Thermostats card behaves strange in HA

### ISSUE THREAD

**Issue by ChristophCaina** [SukramJ/hahomematic#1485]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

within the recent updates from Homeassistant, the Thermostat Card got some attention and got replaced with a new card matching the design of the tile cards.

By default, the Thermostats are in Automatic Mode - and I can select a Preset which has been saved in Homematic - everything is working fine and as expected

<img width="398" alt="image" src="https://github.com/danielperna84/hahomematic/assets/26391061/a95f6195-1439-41cf-af84-3ca38eeae80d">

BUT:
When I click the "Off" Icon - for example
<img width="398" alt="image" src="https://github.com/danielperna84/hahomematic/assets/26391061/8484f2e4-6d0d-4af5-9707-c5913e00cc15">
then, the card is switching immediately to "heating" - and all profiles are gone from the selection

<img width="388" alt="image" src="https://github.com/danielperna84/hahomematic/assets/26391061/db0ee5a2-f0f1-467b-9775-bba90f4b34c7">

Also, switching back to the Automatic mode, I am getting the following information about invalid programs
<img width="528" alt="image" src="https://github.com/danielperna84/hahomematic/assets/26391061/85714e29-1413-4fcb-a203-00b80803a542">

### What version of HomematicIP (local) has the issue?

1.58.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.75.6.20240316

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Im wesentlichen ist das eine Dublette zu #1452, mit einem entsprechenden Kommentar zur [Fehlermeldung](https://github.com/danielperna84/hahomematic/discussions/1452#discussioncomment-8680313)
