### ISSUE TITLE
Stopped working with message "Config entry has already been setup!"

### ISSUE THREAD

**Issue by schulti** [SukramJ/hahomematic#1490]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

The integration was working well until today. After a reboot I recognized that it was delaying boot. After it finally booted, the Homematic/Raspberrymatic components were not available.

Error message in the logs shows:
"Config entry has already been setup!"

If I reconfigure and only configure Bidcos-RF it works, but obviously only shows some of the entities.
If I check Homematic IP **OR** Heat Groups, it fails. Bidcos-RF alone works.

### What version of HomematicIP (local) has the issue?

1.58.0 + 1.59.0b1

### What was the last working version of HomematicIP (local)?

1.58.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.75.6.20240316

### What hardware are you running for your system?

Proxmox VM

### Which config details do you use

- [X] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information (no logs here)

[home-assistant_homematicip_local_2024-04-09T15-22-32.845Z.log](https://github.com/danielperna84/hahomematic/files/14921041/home-assistant_homematicip_local_2024-04-09T15-22-32.845Z.log)

**Comment by SukramJ** [comment]
Das ist kein mir bekanntes Fehlerbild.
ConfigEntries werden von HA erstellt, verwaltet und auch gestartet.
Ich denke da ist was in HA kaputt gegangen.

Wenn VM neustarten nicht hilft würde ansonsten ein Backup machen, den ConfigEntry der Integration aus HA löschen und wieder neu einrichten.

**Comment by schulti** [comment]
Danke für die rasche Antwort.
Das Update zu 1.59.0 hat das Problem gelöst! Ich konnte es aus dem Changelog nicht rauslesen, aber wollte es noch probieren - und es geht wirklich wieder alles!
Danke!

**Comment by SukramJ** [comment]
Die Version 1.59.0 enthält keine zu deiner Problembeschreibung passende Änderung.
Aber gut das es trotzdem klappt.
