### ISSUE TITLE
HMIP SWO PL sunshineduration overflow and negative duration

### ISSUE THREAD

**Issue by l-mb** [SukramJ/hahomematic#1494]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hi, I have a HMIP SWO PL weather station, and that also exposes sensor.hmip_swo_pl_XXXXXX_sunshineduration_2 which counts the daily minutes of sunshine.

That wraps around at apparently 16xxx (my guess would 16384, a 14 bit field), and then drops to zero.

When using this together with a "rate of change" statistic in HA, there's a day with months of darkness :-)

```
state_class: total
interface_id: ccu3-webui-HmIP-RF
address: 00xxxxxxxxxx:1
model: HmIP-SWO-PL
entity_type: generic
parameter: SUNSHINEDURATION
function: null
value_state: valid
unit_of_measurement: min
friendly_name: Sunshine Duration
```

![Graph of sunshine duration](https://github.com/danielperna84/hahomematic/assets/1162196/e88d331c-1e36-45f1-902e-10a11f6dd98a)

![Change history graph](https://github.com/danielperna84/hahomematic/assets/1162196/e0bbe40d-8a60-440f-8953-9518aaff68a9)

I am uncertain whether the right fix is to have a `total_increasing` instead, or whether the integration should hide this wrap internally to keep going?

### What version of HomematicIP (local) has the issue?

1.58.0

### What was the last working version of HomematicIP (local)?

n/a

### What type of installation are you running?

Home Assistant Container

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### What hardware are you running for your system?

AMD 64bit

### Which config details do you use

- [X] TLS
- [X] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information (no logs here)

[config_entry-homematicip_local-3be70f23a73bd5697928db10f144d573.json](https://github.com/danielperna84/hahomematic/files/14931276/config_entry-homematicip_local-3be70f23a73bd5697928db10f144d573.json)

**Comment by Baxxy13** [comment]
I had a similar issue with all ENERGY_COUNTER's (PSM/FSM/BSM) since Version 1.55.0 (2024-02-02).
(related change: "Use state_class total instead of total_increasing for sensors")

Discussed here: https://github.com/danielperna84/hahomematic/discussions/1470

As a result i customized all my "COUNTER's" back to "total_increasing" and it's working now without problems like before 1.55.0.

**Comment by SukramJ** [comment]
Please use HA [customize](https://www.home-assistant.io/docs/configuration/customizing-devices/#customizing-entities) to change the state_class to total_increasing, and report back if it works.
