### ISSUE TITLE
Bug while creating cache-directory during setup

### ISSUE THREAD

**Issue by danielperna84** [SukramJ/hahomematic#151]
**custom_component/hahomematic version (if applicable):**
0.17.1

**Home Assistant version (if applicable):**
2021.12.8 (Core installation in venv)

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, ...): Debmatic
- OS (Original, RaspberryMatic, debmatic/...): Debian Bullseye on Proxmox 7
- Version: 11

**Problem-relevant configuration:**

Do you use tls? No
Do you use callback? No
Do you use username and password? Yes
Which interfaces do you use? HM, HmIP, Groups

**Describe the bug**
During the config flow the UI reported an unexpected error. Within the logs of Home Assistant I got the following traceback:

```
Jan 09 21:36:16 hasstest hass[10101]: Traceback (most recent call last):
Jan 09 21:36:16 hasstest hass[10101]:   File "/home/homeassistant/.homeassistant/custom_components/hahm/config_flow.py", line 218, in async_step_interface
Jan 09 21:36:16 hasstest hass[10101]:     await _async_validate_input(self.hass, self.data)
Jan 09 21:36:16 hasstest hass[10101]:   File "/home/homeassistant/.homeassistant/custom_components/hahm/config_flow.py", line 149, in _async_validate_input
Jan 09 21:36:16 hasstest hass[10101]:     control_unit = await ControlConfig(
Jan 09 21:36:16 hasstest hass[10101]:   File "/home/homeassistant/.homeassistant/custom_components/hahm/control_unit.py", line 495, in async_get_control_unit
Jan 09 21:36:16 hasstest hass[10101]:     await control_unit.async_init_central()
Jan 09 21:36:16 hasstest hass[10101]:   File "/home/homeassistant/.homeassistant/custom_components/hahm/control_unit.py", line 87, in async_init_central
Jan 09 21:36:16 hasstest hass[10101]:     self._central = await self.async_create_central()
Jan 09 21:36:16 hasstest hass[10101]:   File "/home/homeassistant/.homeassistant/custom_components/hahm/control_unit.py", line 422, in async_create_central
Jan 09 21:36:16 hasstest hass[10101]:     central = await CentralConfig(
Jan 09 21:36:16 hasstest hass[10101]:   File "/srv/homeassistant/lib/python3.9/site-packages/hahomematic/central_unit.py", line 635, in get_central
Jan 09 21:36:16 hasstest hass[10101]:     await central.load_caches()
Jan 09 21:36:16 hasstest hass[10101]:   File "/srv/homeassistant/lib/python3.9/site-packages/hahomematic/central_unit.py", line 192, in load_caches
Jan 09 21:36:16 hasstest hass[10101]:     await self.raw_devices.load()
Jan 09 21:36:16 hasstest hass[10101]:   File "/srv/homeassistant/lib/python3.9/site-packages/hahomematic/central_unit.py", line 852, in load
Jan 09 21:36:16 hasstest hass[10101]:     result = await super().load()
Jan 09 21:36:16 hasstest hass[10101]:   File "/srv/homeassistant/lib/python3.9/site-packages/hahomematic/central_unit.py", line 690, in load
Jan 09 21:36:16 hasstest hass[10101]:     return await self._central.async_add_executor_job(_load)
Jan 09 21:36:16 hasstest hass[10101]:   File "/srv/homeassistant/lib/python3.9/site-packages/hahomematic/central_unit.py", line 339, in async_add_executor_job
Jan 09 21:36:16 hasstest hass[10101]:     return await self.loop.run_in_executor(None, executor_func, *args)
Jan 09 21:36:16 hasstest hass[10101]:   File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
Jan 09 21:36:16 hasstest hass[10101]:     result = self.fn(*self.args, **self.kwargs)
Jan 09 21:36:16 hasstest hass[10101]:   File "/srv/homeassistant/lib/python3.9/site-packages/hahomematic/central_unit.py", line 677, in _load
Jan 09 21:36:16 hasstest hass[10101]:     if not check_or_create_directory(self._cache_dir):
Jan 09 21:36:16 hasstest hass[10101]:   File "/srv/homeassistant/lib/python3.9/site-packages/hahomematic/helpers.py", line 96, in check_or_create_directory
Jan 09 21:36:16 hasstest hass[10101]:     os.makedirs(directory)
Jan 09 21:36:16 hasstest hass[10101]:   File "/usr/lib/python3.9/os.py", line 215, in makedirs
Jan 09 21:36:16 hasstest hass[10101]:     makedirs(head, exist_ok=exist_ok)
Jan 09 21:36:16 hasstest hass[10101]:   File "/usr/lib/python3.9/os.py", line 225, in makedirs
Jan 09 21:36:16 hasstest hass[10101]:     mkdir(name, mode)
Jan 09 21:36:16 hasstest hass[10101]: PermissionError: [Errno 13] Permission denied: 'hahm'
```

The _problematic_ code is [here](https://github.com/danielperna84/hahomematic/blob/d861815a12995fbf574eb84504fbd186363456cb/hahomematic/helpers.py#L96), and the folder that fails to be created is `hahm/cache`. Note the relative path that's being used. Having a look at the PID of my `hass` process I noticed, that the CWD was `/`. Hence the process was correctly prohibited from creating `/hahm/cache`.

I then created the folders manually and set the permissions. Afterwards everything was working as expected.

**To Reproduce**
1. Perform a Core-installation according to the officials Docs (on Debian Bullseye in this case)
2. Install HACS + this integration
3. Try to configure this integration

**Expected behavior**
The configuration should work with the cache directory being created at the correct path.

**Additional context**
As mentioned above, this is in a Debian container with a Core installation. Maybe I have overlooked something, as `/` is a bad CWD for the HA process to begin with. So probably my Systemd Unit is faulty and this is not necessarily a bug. But perhaps Home Assistant provides a helper to obtain the path to the actual configuration, which could then be used within the config flow. That way we wouldn't have to rely on the CWD to be at a certain path, making the configuration flow more robust.

**Comment by Lemocin** [comment]
> Perform a Core-installation according to the officials Docs (on Debian Bullseye in this case)

Just tested it with an Ubuntu 20.04 LTS based system. My CWD with a Core-installation seems to be `/srv/homeassistant`. 
Is your venv maybe created under `/` or something like that?

I can try it again with Debian Bullseye but i first have to download and install it. Could take one or two hours, will report back.

**Comment by danielperna84** [comment]
No, the venv is in `/srv/homeassistant` as well. I think it's just a problem with the unit. But that's not really the point of the issue. I feel like the CWD the process is using should not cause a problem during setup. I'm pretty sure HA knows all about the used path. So it should be possible to forward this information to hahomematic so it can create the cache at the proper location, regardless of which CWD the process has.

**Comment by Lemocin** [comment]
Yes, youre right. I just wondered why it wants to access `/` in the default installation. 


> I'm pretty sure HA knows all about the used path. So it should be possible to forward this information to hahomematic so it can create the cache at the proper location, regardless of which CWD the process has.

That's indeed a better approach. From a quick look at it, it may be possible with [`homeassistant.core.Config.path`](https://dev-docs.home-assistant.io/en/master/api/core.html#homeassistant.core.Config.path). 
`hass.config.path()` returns the path, where my `configuration.yaml` resides.

**Comment by SukramJ** [comment]
Next release will use the `hass.config.path` + `hahm` as storage path.

**Comment by SukramJ** [comment]
Please retest with >=0.18.0

**Comment by danielperna84** [comment]
Tested with 0.19.0 and it's working. 👍
