### ISSUE TITLE
HmIP-MOD-TM: cover open not possible if position not completely closed

### ISSUE THREAD

**Issue by N3rdix** [SukramJ/hahomematic#1523]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I just switched from the legacy integration to the custom component and face a regression with the cover for my garage door.

The device (HmIP-MOD-TM) used to toggle correctly from any position between open/closed, which was reflected by an unknown state in the legacy integration. With this custom component the cover now remains in position open when I open it partially (which is correct).

The problem: I can't open the cover from the UI or via the toggle action anymore, the buttons are disabled as long as the state is not closed:
![image](https://github.com/danielperna84/hahomematic/assets/70015952/57849519-e2b2-487e-b3f1-faff4507093b)

When I explicitly call the service `cover.open_cover` it works as expected.

Could this be a bug for this specific homematic device?

### What version of HomematicIP (local) has the issue?

1.59

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.75.6.20240316

### What hardware are you running for your system?

Pi4

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
The definition of open is HA is that it is not closed! So this sounds correct.
I can't tell you how the UI elements work, and why buttons are greyed out.

**Comment by N3rdix** [comment]
> The definition of open is HA is that it is not closed! So this sounds correct. I can't tell you how the UI elements work, and why buttons are greyed out.

Agree that it sounds correct, I'm just wondering if this can be somehow fixed in the integration as it was working in the legacy component. But I assume it was working due to the `unknown` state, if I manually change the state to that the open buttons are also there.
If you think this isn't related to the device/integration I'll figure out how to adjust my automations 😄

**Comment by SukramJ** [comment]
I think there is no need to fix it in the integration, because it is implemented according to the HA specs.
The legacy component is basically unmaintained, so a comparison makes no sense for me.

If you want to change the behavour of your cover component you could implement a [cover template](https://www.home-assistant.io/integrations/cover.template/), that better fits your needs.
