### ISSUE TITLE
Reconnect not working with Homegear

### ISSUE THREAD

**Issue by swnf** [SukramJ/hahomematic#1538]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Every time I restart Homegear, the integration fails to reconnect automatically. As far as I can tell, this package performs the following steps to reconnect:

1. Check if the connection is available again using `is_connected` (which uses `check_connection_availability`)
2. If yes, sleep 120s
3. Call `proxy.init()` to make sure everything is working again

If the client is connected to a CCU, it will use `proxy.ping()` to check the connection in `check_connection_availability`. This works because `ping` is in `_VALID_XMLRPC_COMMANDS_ON_NO_CONNECTION`.

If the client is connected to Homegear, it will use `proxy.clientServerInitialized(interface_id)` to check the connection. This will always raise a `NoConnection` exception because this method is not in `_VALID_XMLRPC_COMMANDS_ON_NO_CONNECTION`.

Adding `clientServerInitialized` to `_VALID_XMLRPC_COMMANDS_ON_NO_CONNECTION` solved the problem for me, but I'm not sure if this is the correct solution. According to the [Homegear docs](https://ref.homegear.eu/rpc.html#clientServerInitialized), this method is used to check if `init()` was already called. I'm not sure if Homegear can always remember the previous `init()` after a restart. Is there any reason why the `ping()` check is not used for Homegear clients?

### What version of HomematicIP (local) has the issue?

1.60.1

### What type of installation are you running?

Home Assistant Container

### What type of installation are you running for your homematic backend?

Homegear

### Which version of your homematic backend are you running?

0.7.51-3497

### What hardware are you running for your system?

Homegear on a Pi2, Home Assistant on an x86_64 server

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Sounds good. Thanks for reporting.
