### ISSUE TITLE
HmIP-BSL support no longer works completely after updating the switch

### ISSUE THREAD

**Issue by hendrikwolf** [SukramJ/hahomematic#1541]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

HmIP-BSL (new Version 2.0.2) - The signal LED control no longer works with the new firmware via the integration. The mode for the signal LED must now be sent. 

### What version of HomematicIP (local) has the issue?

1.60.1

### What was the last working version of HomematicIP (local)?

1.60.1

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.75.7.20240420

### What hardware are you running for your system?

CCU3

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information (no logs here)

[config_entry-homematicip_local-2406833a45e4345078ce8f35eba8ddbc.json](https://github.com/danielperna84/hahomematic/files/15208394/config_entry-homematicip_local-2406833a45e4345078ce8f35eba8ddbc.json)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
Logger: homeassistant.components.trend.binary_sensor
Quelle: components/trend/binary_sensor.py:230
Integration: Trend (Dokumentation, Probleme)
Erstmals aufgetreten: 3. Mai 2024 um 20:21:27 (85 Vorkommnisse)
Zuletzt protokolliert: 09:35:15

could not convert string to float: <HmEntityState.VALID: 'valid'>
float() argument must be a string or a real number, not 'NoneType'
```

**Comment by SukramJ** [comment]
> Logger: homeassistant.components.trend.binary_sensor

Also für logs der trend integration interessiere ich mich nicht! Bitte mal die vollständige Log-Datei anhängen.

Desweiteren für die neue Version mal die Gerätebeschreibung [exportieren](https://github.com/danielperna84/custom_homematic#homematicip_localexport_device_definition), und hier anhängen.

**Comment by hendrikwolf** [comment]
[HmIP-BSL.json](https://github.com/danielperna84/hahomematic/files/15210190/HmIP-BSL.json)
[error_log-13.txt](https://github.com/danielperna84/hahomematic/files/15210198/error_log-13.txt)

**Comment by SukramJ** [comment]
Die Gerätebeschreibung besteht aus zwei Dateien.

**Comment by hendrikwolf** [comment]
Meinst du die Datei?
[config_entry-homematicip_local-2406833a45e4345078ce8f35eba8ddbc.json](https://github.com/danielperna84/hahomematic/files/15210216/config_entry-homematicip_local-2406833a45e4345078ce8f35eba8ddbc.json)

**Comment by SukramJ** [comment]
Nein.

Beim Export werden zwei Dateien erzeugt, die in zwei Verzeichnissen liegen.

**Comment by hendrikwolf** [comment]
Hab die richtige gefunden. Sorry
[HmIP-BSL (1).json](https://github.com/danielperna84/hahomematic/files/15210220/HmIP-BSL.1.json)

**Comment by SukramJ** [comment]
> The mode for the signal LED must now be sent.

Wie kommst Du da drauf?
Übersehe ich was im Log?
Welcher Mode?

**Comment by hendrikwolf** [comment]
Im WebUI muss ich den Modus "Dauerhaft ein" einstellen. Ab der Version 2.0.2 kann die LED auch Blinken und Pulsieren.

![Screenshot 2024-05-04 181044](https://github.com/danielperna84/hahomematic/assets/38292534/11afcde0-76ad-465f-bfce-f83f1eb9ace4)

**Comment by hendrikwolf** [comment]
In der Parameterset-Beschreibung in der Zeile 4503 sind dort die Modis aufgeführt.

**Comment by hendrikwolf** [comment]
Ich habe mal "alte" Gerätebeschreibung mit neu verglichen und schonmal einen neuen Bereich unter "VCUxxxxxxx:8 / MASTER" gefunden.

"POWERUP_OPTICAL_SIGNAL_BEHAVIOUR"

"VALUES" / "COLOR_BEHAVIOUR_STATUS"

"VALUES" / "COLOR_BEHAVIOUR"

**Comment by hendrikwolf** [comment]
Ich möchte nochmal kurz das eigentliche Problem erklären. Die Tasterleuchten können zwar über die HA Integration getriggert werden, aber die Leuchten bleiben aus. Im WebUI der CCU ist ab der Firmwareversion 2.0.2 jetzt der Modus dazu gekommen. Standardmäßig ist der Modus "Beleuchtung aus". Erst wenn ein anderer Modus angegeben wird, leuchtet auch die LED mit entsprechender Farbe und Level.

**Comment by SukramJ** [comment]
Danke für die Erklärung. Funktioniert mit dem nächsten Release wieder

**Comment by hendrikwolf** [comment]
Hab das Pre-Release getested und funktioniert perfekt. Danke für die sehr schnelle Umsetzung.
