### ISSUE TITLE
 2024.5.1 update

### ISSUE THREAD

**Issue by Wolfi311** [SukramJ/hahomematic#1543]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I have installed 2024.5.1 and there are clearly problems with Homematic or (RaspberryMatic)
There are mainly problems when reporting back from RaspberryMatic to HA.

### What version of HomematicIP (local) has the issue?

1.52.0

### What type of installation are you running?

Home Assistant Core

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.75.7.20240420

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Only for people that don't update the CC for month.

**Comment by Wolfi311** [comment]
I don't know what you mean

**Comment by Wolfi311** [comment]
CC ??

**Comment by SukramJ** [comment]
Your Custom Component version has been released in December 2023. update to the latest version.

**Comment by Wolfi311** [comment]
The integration does not show me an update

**Comment by SukramJ** [comment]
Then you should investigate further why hacs does not display, but this is not part of this integration. Latest version is 1.60.1.
