### ISSUE TITLE
GET_ALL_DEVICE_DESCRIPTIONS failed

### ISSUE THREAD

**Issue by asroc-B** [SukramJ/hahomematic#1544]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Nach dem Starten der Integration kommt der folgende Fehler:
Logger: hahomematic.client
Quelle: custom_components/homematicip_local/control_unit.py:679
Integration: Homematic(IP) Local ([Dokumentation](https://github.com/danielperna84/custom_homematic), [Probleme](https://github.com/danielperna84/hahomematic/issues))
Erstmals aufgetreten: 15:44:41 (1 Vorkommnisse)
Zuletzt protokolliert: 15:44:41
GET_ALL_DEVICE_DESCRIPTIONS failed: ExpatError [not well-formed (invalid token): line 3, column 1710]

### What version of HomematicIP (local) has the issue?

1.60.1

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic HA-Addon

### Which version of your homematic backend are you running?

3.75.7.20240420 (RaspberryMatic)

### What hardware are you running for your system?

Generic x86-64

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information (no logs here)

[config_entry-homematicip_local-801237ad2d12383bc9a8f913fb3f7a02.json](https://github.com/danielperna84/hahomematic/files/15209896/config_entry-homematicip_local-801237ad2d12383bc9a8f913fb3f7a02.json)
[home-assistant_homematicip_local_2024-05-04T13-44-56.060Z.log](https://github.com/danielperna84/hahomematic/files/15209897/home-assistant_homematicip_local_2024-05-04T13-44-56.060Z.log)

Untenstehnd die Geräte im RaspberryMatic Addon (Zugriff von dort funktioniert).
![grafik](https://github.com/danielperna84/hahomematic/assets/154887920/d6fc5dc4-62ee-4438-9891-800d8b216ca2)

### Additional information

Ich habe bereits die Homematic_local Integration deinstalliert und auch das RaspberryMatic AddOn. Anschließend beides wieder komplett neu installiert und die Geräte angelernt.
Leider funktioniert der "Import" der Devices nicht nach HA

**Comment by SukramJ** [comment]
Ich gehe hier nicht von einem Fehler in der Integration aus, da der Fehler darauf hinweist, das die Antwort von der CCU einen Fehler enthält. Bisher habe ich diesen speziellen Fehler noch nicht gesehen, und kann dir somit keine Lösung anbieten.
In der Vergangenheit waren solche Fehler auf ein angelerntes Gerät zurückzuführen.
