### ISSUE TITLE
Change the direction of a awning

### ISSUE THREAD

**Issue by dimigiann** [SukramJ/hahomematic#1545]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hi,
I control an awning with a HomematicIP FBroll. The integration in Home Assistant runs via your integration. A total of 20 devices are running and everything is working perfectly. 
The direction of movement is wrong for the actuator in question. Everything is fine in Homematic (CCU3). In Homekit, which I also integrate via Home Assistant, everything is also correct. Only in Homeassistant is the direction of movement displayed incorrectly. Is there a way to change the direction of movement?
Thank you for your help and the really good integration!
Dimi

### What version of HomematicIP (local) has the issue?

1.60.1

### What was the last working version of HomematicIP (local)?

none

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.75.6

### What hardware are you running for your system?

Pi4

### Which config details do you use

- [X] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Woran machst Du fest, das die Umsetzung in HA falsch herum ist? An den angezeigten Prozentwerten, oder am angezeigten Text während der Bewegung?

**Comment by dimigiann** [comment]
Beides,
Wenn die Markise öffnet (sprich wenn sie ausfährt) dann schließt sie in der Anzeige
Wenn die Markise schließt (sprich, wenn sie einfährt) dann öffnet sie in der Anzeige
Eine kleine Korrektur: Die Integration zu HomeKit läuft direkt über die CCU3 und HAP Homematic

Gibt es denn eine Möglichkeit, die Anzeige und den Zustand einzustellen?
VG
Dimi

**Comment by SukramJ** [comment]
Du kannst dir mit einem Cover Template (HA Doku) selber ein Cover definieren.

Die Semantik ist gegenüber Homematic gedreht. https://developers.home-assistant.io/docs/core/entity/cover#properties

**Comment by dimigiann** [comment]
Da klemm ich mich die Tage dahinter. Bin eher Anfänger und muss mich da durchbeißen. Danke für die schnelle Hilfe!Von meinem iPhone gesendetAm 04.05.2024 um 18:26 schrieb SukramJ ***@***.***>:﻿
Du kannst dir mit einem Cover Template (HA Doku) selber ein Cover definieren.
Die Semantik ist gegenüber Homematic gedreht. https://developers.home-assistant.io/docs/core/entity/cover#properties

**Comment by SukramJ** [comment]
Dann schließe ich das Ticket hier.
