### ISSUE TITLE
Motion Sensor update

### ISSUE THREAD

**Issue by 8L12** [SukramJ/hahomematic#1551]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I have a HmIP motion sensor
![61O9kIxdnOL](https://github.com/danielperna84/hahomematic/assets/159006591/b2aad48b-8ef8-4453-88e1-10a88c454599)
It won`t update its state. The only time it updates is when I restart the Addon.
It worked before, I don't know what the issue is.

### What version of HomematicIP (local) has the issue?

1.54.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic HA-Addon

### What hardware are you running for your system?

Pi4

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by 8L12** [comment]
Appenrently I don`t receive any data only on request. I can only set things.

**Comment by SukramJ** [comment]
>  I am aware that an integration that was installed via HACS also needs to be updated via HACS
 
 I am running the latest version of the custom_component (and Home Assistant)

Hast du dich eigentlich gefragt warum die Punkte abgefragt werden.

--> Damit ich nicht ständig das gleiche schreiben muss.


Deine Version ist viel zu alt.
