### ISSUE TITLE
Cover not fully opening (DRBL)

### ISSUE THREAD

**Issue by JonasWirz** [SukramJ/hahomematic#1552]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

After updating to 1.6.1.0, my covers are only opening up to 99% when opening them via HomeAssistant Dashboard. 
They first fully open to 100%. After a few seconds, they are moving again and stop at 99%. 

Before updating, everything worked fine. 

### What version of HomematicIP (local) has the issue?

1.6.1.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
We only send one command for covers, so why do you think it’s an issue of this integration.
Or are you using blinds?

**Comment by JonasWirz** [comment]
Sorry. I am using blinds ;). 
I think it has something to do with the "slap position" as well. After opening the blind via HA, the blind has a slat position of 50% configured in HomeMatic. 
When I open the blind directly in HomeMatic, the slat position is 100%.

**Comment by SukramJ** [comment]
That is menitioned in the release notes of 1.60.0:

> Set open tilt level to 50%

**Comment by JonasWirz** [comment]
I saw the release notes of 1.60.0. 
But this causes problems in my case. If I press "open" in Homeassistant, the blind opens (I think it receives the command 100% open). Afterwards, it receives the command for 50% slat position and goes to position 99% and 50% slat position, because I think that 100% open at 50% slat position is an invalid state (if the blind is fully open, it can not have a slat position). 
Why was an open tilt level of 50% chosen?

**Comment by SukramJ** [comment]
It was requested by blind users in the past.

**Comment by SukramJ** [comment]
I think this is not an issue with this integration.
If you want to change the tilt default to a new value you should start a discussion in this repository.
I personally don‘t use blinds or covers.

**Comment by JonasWirz** [comment]
Thank you! 

I think the problem lies within the order of the commands as they are sent to the Homematic upon combined tilt/position command. 
In cover.py starting from line 109, there is the service definition. First, the position command is sent. Afterwards, the tilt command is sent. This way, the position of 100% is overwritten by the HomeMatic system due to the wrong tilt value. However, if you press "open" in HomeAssistant, a position of 100% is sent, which is never reached because of the tilt value.

**Comment by SukramJ** [comment]
No, if you use the service cover combined position, then only on combined parameter is send.
Same with the  cover open/close command.
