### ISSUE TITLE
Skipping interface ... missing paramsets

### ISSUE THREAD

**Issue by eikowagenknecht** [SukramJ/hahomematic#156]
**custom_component/hahomematic version (if applicable):**
latest

**Home Assistant version (if applicable):**
latest

**CCU version:**
CCU3 with Raspberrymatic

**Problem-relevant configuration:**
Do you use tls? No
Do you use callback? No
Do you use username and password? yes
Which interfaces do you use? Hm, HmIP

**Describe the bug**

I get the following logging entry on every restart:

```
Logger: hahomematic.device
Source: /usr/local/lib/python3.9/site-packages/hahomematic/device.py:667
First occurred: 20:40:41 (12 occurrences)
Last logged: 23:31:38

create_devices: Skipping interface CCU3-HmIP-RF, missing paramsets.
create_devices: Skipping interface CCU3-BidCos-RF, missing paramsets.
```

**Expected behavior**
No errors

**Screenshots**
Config
![image](https://user-images.githubusercontent.com/1475672/148851394-3e42337e-9a2e-4f27-a422-f21782f533d5.png)

![image](https://user-images.githubusercontent.com/1475672/148851408-ada16a96-27a6-4482-be10-86ce4c41a3bf.png)

Also happens without Callback (0.0.0.0)

**Additional context**
Integration seems to work though.

**Comment by SukramJ** [comment]
Das sind nur Warnung, die ignoriert werden können.
Ich werde das LogLevel anpassen.

**Comment by SukramJ** [comment]
LogLevel ist reduced with 0.18.1

**Comment by eikowagenknecht** [comment]
Nice, closing this.
