### ISSUE TITLE
HMIP-BBL öffnet nicht mehr komplett

### ISSUE THREAD

**Issue by martin-st-81** [SukramJ/hahomematic#1560]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hallo, wünschen einen schönen Tag :-)
Wir haben 10 HMIP-BBL in Verwendung und diese schließen leider auch mit der Version 1.62.0b0 nicht mehr komplett. Sie schließen zu 100% und fahren dann auf Lamellenposition 50%. Was bedeutet, dass sich diese praktisch wieder öffnen und aus dem Jalousiekasten mehrere Zentimeter herausfahren und ungeschützt sind. Dieses Verhalten tritt bei direkter Ansteuerung aus HomeMatic nicht auf.
Es werden die unveränderten Entitäten von Homematic(IP) Local - cover.hmip_bbl_XYZ in HomeAssistant 2024.5.4 verwendet.
Wie kann die Lamellenposition wieder allgemein beim schließen auf 0% gesetzt werden ?
Ich habe bei den HMIP-BBL bereits die Auto Calibration in der HomeMatic ausgeführt und das Homematic(IP) Local im HomeAssistant neu installiert.
Bitte um Unterstützung, Danke

### What version of HomematicIP (local) has the issue?

1.62.0b0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.75.7.20240420

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by sleiner** [comment]
Wie löst du das Schließen der Jalousie denn in Home Assistant aus? Insbesondere, falls du das weißt: Welcher Service wird zum Schließen aufgerufen und mit welchen Parametern?

**Comment by martin-st-81** [comment]
Ich öffne meine Jalousien direkt über die unveränderten Entitäten von Homematic(IP) Local (Pfeil nach oben) - siehe Bilder.
Der Dienst - siehe Screenshot lautet Abdeckung öffnen.
Mit öffnen meine ich das die Jalosie oben ist und die Fenster nicht abgedunkelt werden ... (schließen war bei der Einmeldung eher missverständlich)
Sie öffnen zu 100% und fahren dann auf Lamellenposition 50%. Was bedeutet, dass sich diese praktisch wieder schließen und aus dem Jalousiekasten mehrere Zentimeter herausfahren und ungeschützt sind. Dieses Verhalten tritt bei direkter Ansteuerung aus HomeMatic nicht auf.
Ich vermute dass Verhalten seit [1.60.0] - Breaking change: "tilt level is set to 50% to be open instead of 100% for blinds"

Wenn das ein Feature ist - wie kann ich das umgehen ? Danke

![2024-05-18 12_38_59-Einstellungen – Home Assistant](https://github.com/danielperna84/hahomematic/assets/104215732/1e37e7e3-1d90-44b6-87ba-233c10c93276)
![2024-05-18 12_40_30-Einstellungen – Home Assistant](https://github.com/danielperna84/hahomematic/assets/104215732/c1fa4f84-a3ba-4ba7-bc6a-0ed04478cfa6)

**Comment by sleiner** [comment]
Diese Änderung habe ich auch neulich gesehen; ich bin auch der Meinung, dass das Öffnen der Jalousie zu Behanghöhe 100% und Lamellenposition 100% führen sollte, sodass der Motor bis zum Anschlag hoch fährt 👍🏻 @SukramJ hat ja auch schon in #1552 formuliert, dass man darüber diskutieren kann.

Dein ursprünglicher Bug Report bezog sich allerdings aufs Schließen, nicht aufs Öffnen. Daher lass uns in diesem Ticket mal beim Schließen bleiben:

> Sie schließen zu 100% und fahren dann auf Lamellenposition 50%.

Wie löst du das aus? Bisher hast du nur erläutert, wie du die Jalousie öffnest.

**Comment by martin-st-81** [comment]
Beim Schließen habe ich keine Probleme, nur beim "öffnen". Sorry für die anfängliche Formulierung.
Habe soeben den Titel korrigiert

**Comment by SukramJ** [comment]
Wenn isch schon auf Issue #1552 verweise und dort schreibe, das doch ein entsprechender Diskussionsbetrag zu erstellen sei, dann macht ein neues Issue keinen Sinn.
Ansonsten ist das nur eine Dublette zu #1552
