### ISSUE TITLE
Device goes offline until switching its state in homematic

### ISSUE THREAD

**Issue by lomtaslipptas** [SukramJ/hahomematic#1564]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

After investigation of the problem it seems like this:
In situation where there is a motion sensor deactivating a light for example and you are turning into the motion sensor right in this situation it should immediately turn on again. But if you catch the exact time where the switch was going to turn off by the motion sensor and than has to turn on again it is reported as unavailable im home assistant. This is until you switch to the homematic UI (or an app using homematic directly) and switching the state of the actor. Afterwards everything works fine again. 

### What version of HomematicIP (local) has the issue?

1.61.0

### What was the last working version of HomematicIP (local)?

-

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.75.6

### What hardware are you running for your system?

Synology NAS 918+

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information (no logs here)

[config_entry-homematicip_local-eba7a1fdb64d21144fc331dc59c93fc4 (1).json](https://github.com/danielperna84/hahomematic/files/15370085/config_entry-homematicip_local-eba7a1fdb64d21144fc331dc59c93fc4.1.json)

**Comment by SukramJ** [comment]
This is basically a communication problem in your homematic system.
To reactivate the device in HA you can use the service [force_device_availability](https://github.com/danielperna84/custom_homematic#homematicip_localforce_device_availability).
There are also some supportive [blueprints](https://github.com/danielperna84/custom_homematic#available-blueprints).
See also discussion #566.
