### ISSUE TITLE
Motion_Detection_Active lets itself turn off but not on again

### ISSUE THREAD

**Issue by Steffie1995** [SukramJ/hahomematic#1568]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I have an automation that controles my motionsensor and switches it of after specific conditions were met. I'm using the Motion_Detection_Active button for this but for some reason it turns it off but never on again.

I also noticed it throws me a warning in the logs when it doesn't turn it on again (included in the form).

I'm more than happy to admit I'm to stupid for the sensor, I just have no clue what to do further I've already reset the sensor once and it did the exact same thing...
I'm also running the sensor on batteries.

Thanks for the help in advance.

### What version of HomematicIP (local) has the issue?

1.61.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic HA-Addon

### Which version of your homematic backend are you running?

3.75.7.20240420

### What hardware are you running for your system?

Pi4

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
2024-05-24 20:06:42.481 WARNING (MainThread) [hahomematic.client] SET_VALUE failed with ClientException [XMLRPC Fault from backend: -1 Generic error]: XXXXXXXXXXXXXXXX:3, MOTION_DETECTION_ACTIVE, True
```

**Comment by SukramJ** [comment]
I cannot reproduce this with my HmIP-SMI (FW 3.2.48)/HmIP-SMO (FW 3.6.72), so i guess the problem is device specific/related to your environment.

**Comment by Steffie1995** [comment]
Thank you I will try some other thinks or maybe even resetting it again :)
