### ISSUE TITLE
Where to use the HMIP-SWSD template?

### ISSUE THREAD

**Issue by adieball** [SukramJ/hahomematic#1569]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Sorry, i'm quite new to HA and came across this template: https://github.com/danielperna84/hahomematic/wiki/Community-Templates-for-Home-Assistant for the HMIP-SWSD integration that I believe I need for a proper integration in Alarmo (only report via push which sensor is the primary).

My Question is: where to i use these code lines? I searched in helpers, etc. but nowhere I can paste yaml.

thanks

### What version of HomematicIP (local) has the issue?

1.61.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Please don‘t use the issue tracker for general support questions. Therefore we have the discussions [part](https://github.com/danielperna84/hahomematic/discussions) or the [HA community forum ](https://community.home-assistant.io/).

These code snippets must be added to the configuration.yaml

You should also have a deeper look at the [HA docs](https://www.home-assistant.io/docs/configuration/).
