### ISSUE TITLE
Warning for unreachable devices in wrong place

### ISSUE THREAD

**Issue by eikowagenknecht** [SukramJ/hahomematic#157]
**custom_component/hahomematic version (if applicable):**
latest

**Home Assistant version (if applicable):**
latest

**CCU version:**
CCU3 with RaspberryMatic

**Describe the bug**
Unreachable devices generate a persistent notification:
![image](https://user-images.githubusercontent.com/1475672/148908787-1ef437fe-ea57-48c7-b410-bd66b5edec72.png)

**To Reproduce**
1. Unplug Hm device with regular status messages
2. Wait until the CCU notices that the device is unreachable
3. See error

**Expected behavior**
The usual way would be to instead mark the entities as "not reachable" as it is done in the old homematic integration:

![image](https://user-images.githubusercontent.com/1475672/148909039-4b0706ab-08f0-48a9-807a-86a9243f8c6e.png)

**Screenshots**
see above

**Comment by emufan** [comment]
I would like to see this persistent notification disabled/removed as well. The user, who needs it, can create them via automation. 

My setup: I have a outdoor sensor and know, that this has sometime problems. But that doesn't matter, some seconds afterwards it is back again, so I don't care. But the persistent notification is generated.

**Comment by SukramJ** [comment]
@eikowagenknecht : Thanks for reporting a bug. Unreach should be displayed on an entity_level. (device is not posible)
@emufan: I don't think an issue is the correct place to discuss a feature

**Comment by eikowagenknecht** [comment]
If you prefer to discuss it over at discussions, I just created a thread there: https://github.com/danielperna84/hahomematic/discussions/161

**Comment by danielperna84** [comment]
I like these notifications. They are the equivalent of the "Servicemeldungen" on the CCU. That's a feature other users actually requested for the old integration. And in my case they also disappeared in HA automatically once the device was reachable again. So essentially you get the relevant message from the HA UI without having to look at the CCU to know what the problem is.

**Comment by SukramJ** [comment]
Unreach is fixed now. Will be displayed at entity_level again.
with 0.18.1

**Comment by eikowagenknecht** [comment]
Nice, closing this. The discussion can be continued in the discussion thread.
