### ISSUE TITLE
Platform homematicip_local does not generate unique IDs

### ISSUE THREAD

**Issue by BOFH90** [SukramJ/hahomematic#1573]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I just installed Home Assistant and added all 3 of my CCU´s. 
It´s all working just fine, but the following Errors shows up in my log:

`2024-05-29 10:35:47.766 ERROR (MainThread) [homeassistant.components.event] Platform homematicip_local does not generate unique IDs. ID homematicip_local_bidcos_wir_1 already exists - ignoring event.hmw_rcv_50_bidcos_wir_ch1
2024-05-29 10:35:47.766 ERROR (MainThread) [homeassistant.components.event] Platform homematicip_local does not generate unique IDs. ID homematicip_local_bidcos_wir_2 already exists - ignoring event.hmw_rcv_50_bidcos_wir_ch2
2024-05-29 10:35:47.766 ERROR (MainThread) [homeassistant.components.event] Platform homematicip_local does not generate unique IDs. ID homematicip_local_bidcos_wir_3 already exists - ignoring event.hmw_rcv_50_bidcos_wir_ch3
2024-05-29 10:35:47.766 ERROR (MainThread) [homeassistant.components.event] Platform homematicip_local does not generate unique IDs. ID homematicip_local_bidcos_wir_4 already exists - ignoring event.hmw_rcv_50_bidcos_wir_ch4
2024-05-29 10:35:47.766 ERROR (MainThread) [homeassistant.components.event] Platform homematicip_local does not generate unique IDs. ID homematicip_local_bidcos_wir_5 already exists - ignoring event.hmw_rcv_50_bidcos_wir_ch5`

[home-assistant_2024-05-29T09-02-54.340Z.log](https://github.com/danielperna84/hahomematic/files/15481820/home-assistant_2024-05-29T09-02-54.340Z.log)

### What version of HomematicIP (local) has the issue?

1.61.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.75.7.20240420

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [X] BidCos-Wired (HM-Wired)

### Diagnostics information (no logs here)

[config_entry-homematicip_local-c3051cb361acb5517d2d3512dca5d1f4.json](https://github.com/danielperna84/hahomematic/files/15481862/config_entry-homematicip_local-c3051cb361acb5517d2d3512dca5d1f4.json)

**Comment by SukramJ** [comment]
Thanks for reporting. Please add the diagnostics information for the other CCUs too.

**Comment by BOFH90** [comment]
sure :) they are all attached.:
[config_entry-homematicip_local-1c57f46b1d4efcb60cefc0bf73d34477.json](https://github.com/danielperna84/hahomematic/files/15488181/config_entry-homematicip_local-1c57f46b1d4efcb60cefc0bf73d34477.json)
[config_entry-homematicip_local-72d54e9b0fec5fd25a99c6088e26d10d.json](https://github.com/danielperna84/hahomematic/files/15488182/config_entry-homematicip_local-72d54e9b0fec5fd25a99c6088e26d10d.json)
[config_entry-homematicip_local-c3051cb361acb5517d2d3512dca5d1f4.json](https://github.com/danielperna84/hahomematic/files/15488183/config_entry-homematicip_local-c3051cb361acb5517d2d3512dca5d1f4.json)

**Comment by SukramJ** [comment]
Danke.
Bitte poste mal einen Screenschot aus der CCU->Einstellungen->Geräte
Mich interessiert das aufgeklappe virtuelle Gerät für Homematic Wired.

**Comment by BOFH90** [comment]
Na klar :) reicht das so? 
![image](https://github.com/danielperna84/hahomematic/assets/6523520/d968e36a-f16b-4cdb-b925-83a536c4ecb8)

**Comment by SukramJ** [comment]
Danke das ist hilfreich.

**Comment by SukramJ** [comment]
Update bitte mal auf die Beta 1.62.1b0.
Die Meldungen sollten nicht mehr auftreten, und es sollte keine doppelten Event Entitäten im HMW virtual device geben.

**Comment by BOFH90** [comment]
Ist erledigt und die Meldung ist jetzt weg :) Die "alten" event.hmw_rcv_50_bidcos_wir_chXX sind jetzt nicht mehr verfügbar gewesenund habe ich entfernt. Dafür sind jetzt von allen 3 CCUs die Entitäten vorhanden. Das hat super geklappt.

Vielen Dank 🙂👍
