### ISSUE TITLE
Raumthermostate nicht mit climate device bedienbar

### ISSUE THREAD

**Issue by joe16joe16** [SukramJ/hahomematic#1586]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Wenn im HA UI bei einem Raumthermostat bedient wird kommt diese Meldung links unten:

> Failed` to call service climate/set_hvac_mode. expected HVACMode or one of 'off', 'heat', 'cool', 'heat_cool', 'auto', 'dry', 'fan_only' for dictionary value @ data['hvac_mode']

### What version of HomematicIP (local) has the issue?

1.62.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic HA-Addon

### Which version of your homematic backend are you running?

3.75.7.20240601

### What hardware are you running for your system?

NUC

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information (no logs here)

[config_entry-homematicip_local-2db849d37309733cf7959033fdb50fb2 (1).json](https://github.com/user-attachments/files/15525441/config_entry-homematicip_local-2db849d37309733cf7959033fdb50fb2.1.json)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
This error originated from a custom integration.

Logger: hahomematic.client
Source: custom_components/homematicip_local/climate.py:279
integration: Homematic(IP) Local (documentation, issues)
First occurred: 2:51:46 PM (5 occurrences)
Last logged: 3:08:30 PM

SET_VALUE failed with ClientException [XMLRPC Fault from backend: -1 Generic error (TIMEOUT)]: 000A98A9A73E92:1, SET_POINT_TEMPERATURE, 9.5
SET_VALUE failed with ClientException [XMLRPC Fault from backend: -1 Generic error (TIMEOUT)]: 000A98A9919F47:1, SET_POINT_TEMPERATURE, 19.5
SET_VALUE failed with ClientException [XMLRPC Fault from backend: -1 Generic error (TIMEOUT)]: 000A98A9919F47:1, SET_POINT_TEMPERATURE, 14.5
SET_VALUE failed with ClientException [XMLRPC Fault from backend: -1 Generic error (TIMEOUT)]: 000A98A9A73E9D:1, SET_POINT_TEMPERATURE, 12.5
SET_VALUE failed with ClientException [XMLRPC Fault from backend: -1 Generic error (TIMEOUT)]: 000A98A9919F47:1, SET_POINT_TEMPERATURE, 18.5
```

**Comment by SukramJ** [comment]
`Generic error (TIMEOUT)]`

Du hast Kommunikationsprobleme!

Gerät neustarten
CCU neustarten
HA neustarten

**Comment by joe16joe16** [comment]
Hab ich alles schon gemacht, kein Erfolg.

Der Fehler kommt auch nicht immer vor aber bei acht von 10 Versuchen ist es so das das Gerät dann von HA nach dem Auswählen der Temperatur in der climate als "Nicht verfügbar" Angezeigt wird.

Die Ports in den Raspberry Matic Einstellungen sind nicht verändert.
![image](https://github.com/danielperna84/hahomematic/assets/169074579/1df649a5-219d-48bc-ad71-af2be97f030c)

**Comment by SukramJ** [comment]
Ich kann da nichts machen, wenn die CCU mit Timeout antwortet, weil dein Gerät nicht erreichbar ist.
Welches Gerät auch immer. Hast Du ja nicht geschrieben.

**Comment by joe16joe16** [comment]
RaspberryMatic AddOn (hab ich beim ersten Post ausgewählt und auch die Versionsnummern angegeben) also nutzte auch den hostnamen des docker containers (de838cd8-raspberrymatic) 

`➜  / ping de838cd8-raspberrymatic
PING de838cd8-raspberrymatic (172.30.33.2) 56(84) bytes of data.
64 bytes from addon_de838cd8_raspberrymatic.hassio (172.30.33.2): icmp_seq=1 ttl=64 time=0.119 ms
64 bytes from addon_de838cd8_raspberrymatic.hassio (172.30.33.2): icmp_seq=2 ttl=64 time=0.069 ms
64 bytes from addon_de838cd8_raspberrymatic.hassio (172.30.33.2): icmp_seq=3 ttl=64 time=0.153 ms`

Die Firewall in RaspberryMatic ist im Assistenten auf "Relaxed" gestellt und hat diese Einstellungen:

![image](https://github.com/danielperna84/hahomematic/assets/169074579/2bd384b3-8f87-4165-8eba-28283ad9e380)

Also Netzwerkprobleme sollten es mal nicht sein können.

Hier noch die genauen Einstellungen der Integration:

![image](https://github.com/danielperna84/hahomematic/assets/169074579/6c0c6542-4cd1-411a-8e1a-f8d6037f9725)

![image](https://github.com/danielperna84/hahomematic/assets/169074579/1f8260f7-b158-4756-a283-8bad10aeac5b)

**Comment by SukramJ** [comment]
Es geht nicht um die Kommunikation HA --> CCU, sondern um CCU --> Gerät.
Daher kann ich nichts machen, und daher sind die Firewallregeln egal.
