### ISSUE TITLE
Kommunikation zwischen HA und HmIP

### ISSUE THREAD

**Issue by dietklein** [SukramJ/hahomematic#1592]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Nach HA 2024.5.0 keine Kommunikation zwischen HA und HmIP.
Zurückgehen auf 2024.4.04

### What version of HomematicIP (local) has the issue?

1.58.0

### What was the last working version of HomematicIP (local)?

1.58.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information (no logs here)

[config_entry-homematicip_local-784391452e8c73312109c59173f43677(1).json](https://github.com/user-attachments/files/15784421/config_entry-homematicip_local-784391452e8c73312109c59173f43677.1.json)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
#1
Logger: hahomematic.central
Quelle: /usr/local/lib/python3.12/site-packages/hahomematic/central/__init__.py:1071
Erstmals aufgetreten: 15:06:44 (54 Vorkommnisse)
Zuletzt protokolliert: 15:13:22

FIRE_HA_EVENT_CALLBACK: Unable to call handler: Detected that custom integration 'homematicip_local' calls issue_registry.async_delete from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#issue_registryasync_delete at custom_components/homematicip_local/control_unit.py, line 355: async_delete_issue(. Please report it to the author of the 'homematicip_local' custom integration.
#2
Logger: homeassistant.helpers.frame
Quelle: helpers/frame.py:184
Erstmals aufgetreten: 15:06:41 (84 Vorkommnisse)
Zuletzt protokolliert: 15:13:22

Detected that custom integration 'homematicip_local' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/homematicip_local/generic_entity.py, line 218: self.async_write_ha_state(), please report it to the author of the 'homematicip_local' custom integration
Detected that custom integration 'homematicip_local' calls issue_registry.async_delete from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#issue_registryasync_delete at custom_components/homematicip_local/control_unit.py, line 355: async_delete_issue(, please report it to the author of the 'homematicip_local' custom integration
#3
Logger: hahomematic.platforms.entity
Quelle: /usr/local/lib/python3.12/site-packages/hahomematic/platforms/entity.py:236
Erstmals aufgetreten: 15:06:41 (30 Vorkommnisse)
Zuletzt protokolliert: 15:13:05

FIRE_UPDATE_ENTITY_EVENT failed: Detected that custom integration 'homematicip_local' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/homematicip_local/generic_entity.py, line 218: self.async_write_ha_state(). Please report it to the author of the 'homematicip_local' custom integration.
```

### Additional information

 Ed1954 hat ein ähnliches Problem am 03.Mai gemeldet, welches geschlossen wurde. 
Ich komme leider mit dem Englisch nicht so gut zurecht! Ich bitte daher um Hilfe !
Lieben Dank im vorraus!!!

**Comment by SukramJ** [comment]
> I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)

Einfach mal updaten!
Bei fehlenden Sprachkenntnissen hilft u.a. Google translate.

**Comment by dietklein** [comment]
Hallo, danke für deine Antwort!

ich komme aber trotzdem nicht weiter (Einfach mal updaten)??? was und wie?

Google translate hilf schon mal, aber nicht immer! Habe HomematicIP (local) händisch über die configuration.yaml eingefügt!

Würde mich freuen wenn sie mich ein wenig mehr unterstützen!

vielen Dank.

Dieter

**Comment by SukramJ** [comment]
Diese Integration wird nicht über die configuration.yaml konfiguriert.
Ich gehe mal davon aus, das die Installation über HACS erfolgt ist, und wie schon im Kopf des Issues vermerkt, wenn etwas über HACS installiert wird, dann muss es auch über HACS aktualisiert werden.
Die Punkte werden nicht ohne Grund im Kopf des Issues ergänzt, weil ich mir somit Arbeit  und die immer gleichen Antworten ersparen möchte. Leider wird eher der Haken angeklickt, anstatt den dazugehörigen Text zu lesen.

**Comment by dietklein** [comment]
Guten Morgen,
ich habe vollstes Verstäniss für ihre Anmerkung!! Ich habe Gestern so viel gelesen, jetzt raucht mein Kopf! Ich habe HACS gelöscht und neu installiert, keine Besserung. Home Assistant ist ein super tolles Projet und ich wäre sehr traurig wenn mir jetzt nicht weiter geholfen wird. Homematic IP local in HACS kann ich nicht updaten, der Button ist inaktiv, warum auch immer.
[config_entry-hacs-be487ca191e81daf61ffb24ec2614c9a(4).json](https://github.com/user-attachments/files/15799998/config_entry-hacs-be487ca191e81daf61ffb24ec2614c9a.4.json)

Ich bitte nochmals um Hilfe !
Gruß Dieter

**Comment by SukramJ** [comment]
> … und ich wäre sehr traurig wenn mir jetzt nicht weiter geholfen wird.

Das finde ich absolut unangebracht!
Deine Probleme haben nichts mit der Integration zu tun.

Schau dir am Besten mal die Installationsanleitung an. Hast Du das Repository der Integration auch wieder zu HACS hinzugefügt?
