### ISSUE TITLE
Homeatic funktioniert nicht mehr nach update 

### ISSUE THREAD

**Issue by fastbag** [SukramJ/hahomematic#1594]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Ich kann nicht mehr auf Geräte von HomeaticIp zugreifen über HA

### What version of HomematicIP (local) has the issue?

1.63

### What was the last working version of HomematicIP (local)?

1.62.1

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic HA-Addon

### Which version of your homematic backend are you running?

1.63

### What hardware are you running for your system?

HomeAssistant 

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information (no logs here)

[home-assistant_2024-06-17T19-41-58.473Z.log](https://github.com/user-attachments/files/15876387/home-assistant_2024-06-17T19-41-58.473Z.log)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
2024-06-17 14:21:43.037 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration homematicip_local which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-17 14:21:46.027 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'homematicip_local': Unable to import component: No module named 'custom_components.homematicip_local.const'
File "/config/custom_components/homematicip_local/__init__.py", line 16, in <module>
ModuleNotFoundError: No module named 'custom_components.homematicip_local.const'
2024-06-17 14:49:38.744 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration homematicip_local: No module named 'custom_components.homematicip_local.const'
File "/config/custom_components/homematicip_local/__init__.py", line 16, in <module>
ModuleNotFoundError: No module named 'custom_components.homematicip_local.const'
```

### Additional information

Muss nach dem letzten update gekommen sein, bei mir ist eigentlich 1.63 installiert und anzeigen, mit nicht gestartet im Integrationen Reiter ist 1.62.1 nicht gestartet und ich kann mich trotzdem im docker ganz normal auf der Oberfläche anmelden. Backup Rückspielen usw. habe ich probiert.
Gruß Sven
![image](https://github.com/danielperna84/hahomematic/assets/46375317/bb7c64e3-20be-43f2-80ae-b9901813bedf)
![image](https://github.com/danielperna84/hahomematic/assets/46375317/6a9642af-205e-4afc-858a-2d78c787db62)

**Comment by fastbag** [comment]
So habe jetzt mal das core update 2024.6.1 zurück gespielt das war es jetzt hat er sie wieder drin

**Comment by SukramJ** [comment]
> So habe jetzt mal das core update 2024.6.1 zurück gespielt das war es jetzt hat er sie wieder drin

Funktioniert es jetzt? Der Satz ist nicht zu verstehen.

**Comment by SukramJ** [comment]
Ich gehe mal davon aus, das es jetzt funktioniert.

**Comment by fastbag** [comment]
Sobald ich wieder das update mache auf 1.63 geht wieder nix mehr. Beim Backup wieder einspielen, 1.61 geht alles wieder. Kann es auch daran liegen das ich jetzt 1 Version überspringe  ? Also von 1.61 auf 1.63 ?
So konnte jetzt alle updates von HomeAssistant nacheinander fahren, geht immer noch nur das update von Raspberrymatic local habe ich noch nicht gemacht sonst geht wieder nix mehr. Hättest du eine Idee ?
Gruß

**Comment by SukramJ** [comment]
> Also von 1.61 auf 1.63?

Nein.

Ich denke da funktioniert etwas beim HACS Download nicht, so das die Dateien nicht vollständig heruntergeladen werden.

Vielleicht noch mal über HACS -> Homematic(IP) Local --> (Dreipunkte Menü) --> Erneut herunterladen --> herunterladen klicken.

**Comment by fastbag** [comment]
Habe jetzt erst über die 3 Punkte die 62  erneut runtergeladen und dann nach dem Neustart die 1.63, jetzt geht es endlich wieder, besten dank, ich konnte mir nicht erklären, ohne das ich was an der config geändert hatte, das sie beschädigt ist. Danke noch mal
