### ISSUE TITLE
Issues with HmIP-MOD-HO

### ISSUE THREAD

**Issue by stefangries** [SukramJ/hahomematic#1608]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Unfortunately, there are problems with my HmIP-MOD-HO garage door control unit. The open/close buttons in the HA UI unfortunately become disabled at inappropriate times. This is the current situation:

![image](https://github.com/danielperna84/hahomematic/assets/10342151/793d47af-994f-4035-80be-2d57a7d6e408)
The Up/Stop/Down Buttons control the door. The switch controls its light.

**When closed**, the state is "closed" and the the open and stop button are active. This is nearly correct, as the stop button could be disabled.
**During opening**, the state is "unknown" and the the close and stop button are active.  This is wrong, as all buttons should be active.
**When opened**, the state is "open" and the the close and stop button are active. This is nearly correct, as the stop button could be disabled.
**During closing**, the state ist "unknown" and the the open and stop button are active. This is wrong, as all buttons should be active.
**When stopped during closing**, the state is "unknown" and the the close and stop button are active.  This is wrong, as close and open buttons should be active.
**When stopped during opening**, the state is "unknown" and the the close and stop button are active.  This is wrong, as close and open buttons should be active.

By the way, in the CCU UI, all the buttons (open/close/stop) are clickable all the time. Additonally, the "Lüften"-Button (Opens the door just a bit to allow ventilation) is only available in the CCU UI and not via HA. 

![image](https://github.com/danielperna84/hahomematic/assets/10342151/3c05057d-8db9-4051-b320-94cdf2029f74)

### What version of HomematicIP (local) has the issue?

1.63.1

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic HA-Addon

### Which version of your homematic backend are you running?

3.75.7.20240601

### What hardware are you running for your system?

Intel NUC

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
This integration is **not** controlling the button activation/deactivation. This is part of the [HA frontend](https://github.com/home-assistant/frontend). Open an issue in their repository if you don't like it.

> By the way, in the CCU UI, all the buttons (open/close/stop) are clickable all the time. Additonally, the "Lüften"-Button (Opens the door just a bit to allow ventilation) is only available in the CCU UI and not via HA.

Lüften is not supported by the [HA cover entity model](https://developers.home-assistant.io/docs/core/entity/cover).
If you want "Lüften" to be added, then you should start a discussion in the [HA architecture repo](https://github.com/home-assistant/architecture/discussions).

**Comment by stefangries** [comment]
Thank you for your answer!

> This integration is **not** controlling the button activation/deactivation.

I had assumed that the HA UI decides which buttons are active based on a status transmitted by the integration. For example, if the integration reports that the door is open, only the close button is active.

With roller shutters, for example, if you stop them halfway, both the open and close buttons are displayed as active in HA. In general, it is therefore possible to display both as active. I assume this happens when current_position is somewhere between 0% and 100%. In the case of the garage door, the current_position attribute simply disappears during the movement and reappears with a value of 0 or 100 at the end of the movement.

I could imagine that there is a problem here, as the Homematic integration does not know the position of the garage door, it reports it as unknown. This may lead to the strange display of the buttons in the Home Assistant.

**Comment by SukramJ** [comment]
The garage doors only have the states `OPEN`, `VENT`  and `CLOSED`.
Everthing in between is `UNKNOWN` for HA.

If you use the slider to control the garage door then 0-10 means closed, 11-50 is vent and 51-100 is open.

I think this issue can be closed.
