### ISSUE TITLE
HM-Sec-SC-2 - missing sabotage contact 

### ISSUE THREAD

**Issue by Eckart0** [SukramJ/hahomematic#1614]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hello,
I have some old HM door/window contacts HM-Sec-SC-2. The status of the reed relay is displayed in HA, but the sabotage contact, which is also present, is not.
Is there anything I can do about this or is it due to the integration here?
Best regards,
Eckart

### What version of HomematicIP (local) has the issue?

1.63.1

### What was the last working version of HomematicIP (local)?

1.63.1

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.73.9.20240130 

### What hardware are you running for your system?

Odriod

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [X] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Der HM-Sec-SC-2 hat keinen für die Integration nutzbaren Datenpunkt für SABOTAGE.
Ggf ERROR über [unignore](https://github.com/danielperna84/custom_homematic#unignore-device-parameters) einbinden.
Bitte vermeide Doppelposts in verschiedenen Foren. Das ist Zeitverschwendung für die Beteiligten.
