### ISSUE TITLE
Device e.g. HmIP-BSM has no available triggers in automation

### ISSUE THREAD

**Issue by itn3rd77** [SukramJ/hahomematic#1616]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I changed the HmIP-BSM switch to be treated like a light (shown in the screenshot of the device). When createing a new automation I noticed that my HmIP-BSM device has no available triggers. This also affects my existing automations (where I changed the switch to be a light). Tiggers are gone and I am no longer able to distinguish between any actions. I could sear this was not the case before. Other devices like HmIP-SMI are not effected and triggers are shown as normal.  

![grafik](https://github.com/user-attachments/assets/30e6e3cd-92ab-4e23-b465-dcd718434a02)

![grafik](https://github.com/user-attachments/assets/e2760bcf-fe23-44db-901a-5dd702535fdb)

### What version of HomematicIP (local) has the issue?

1.63.1

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic HA-Addon

### Which version of your homematic backend are you running?

3.75.7.20240601

### What hardware are you running for your system?

Synology DS723+

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
No problem with my devices.
Looks like you are using Switch as X on this device. 
When changing an entity to light, then the triggers are gone.

I don't think that this is an issue with this integration.

**Comment by itn3rd77** [comment]
Yes you are right. I am using Switch as X on this device and this seem to cause the trouble. Mhhhh to bad as most of the switches are really just used as "lights". If there is nothing that can be done on integration side than I have to revert this.

**Comment by SukramJ** [comment]
I think this problem is caused by switch as X. Maybe you could open an issue in the HA repo.

**Comment by itn3rd77** [comment]
Seems not to be a HA issue. For opening an HA issue I wanted to used an official integration like Shelly and used switch as X on a Shelly device.

![grafik](https://github.com/user-attachments/assets/c3666df8-8ce3-4d88-a5ea-bdf047a53ed5)

When selecting the device all triggers are available:

![grafik](https://github.com/user-attachments/assets/cdc2f238-4ead-4cc4-8fd5-47a35f605c9d)

**Comment by itn3rd77** [comment]
Hope you can find the issue. I really need this switch as X  thing.

**Comment by SukramJ** [comment]
@itn3rd77 good catch
