### ISSUE TITLE
BROLL Displays Always 10% as position

### ISSUE THREAD

**Issue by Pitjupp111** [SukramJ/hahomematic#1618]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I just got a BROLL for my awning. The installation and configuration at my CCU3 works fine. The new device is already available in the Homematic local integration. The only problem I have is, that the position is always shown with 10%. The awning Drives well at every position, but the Display value stays at 10.
Do you have any idea?
Thanks
Peter

### What version of HomematicIP (local) has the issue?

1.61.1

### What was the last working version of HomematicIP (local)?

1.63.1

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.77.6

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information (no logs here)

[error_log-1.txt](https://github.com/user-attachments/files/16382447/error_log-1.txt)

**Comment by SukramJ** [comment]
I refuse to look at logs from several days that are full of errors that have nothing to do with this integration.

Please delete the existing logs and restart HA with only this integration enabled for debug. Other integration that still throw errors should be disabled to avoid a log pollution.

Before you start you should reboot your CCU.

1.61.1 is the latest version for you that works?
I basically don‘t think this is an issue with this integration.

**Comment by Pitjupp111** [comment]
I'm sorry for that logfile. Because I'm a really newby at HA, I didn't look for that.
When I'm able to cleanup the File, I'll send it again.

Thanks for your assistant.
Peter

**Comment by SukramJ** [comment]
> When I'm able to cleanup the File, I'll send it again.

Please don't cleanup the existing file. Just delete the log and restart HA and CCU as described above.

If the problem exists afterwards, attach a new log and reopen this issue
