### ISSUE TITLE
Memory leak when device firmware update is ready

### ISSUE THREAD

**Issue by dfigus** [SukramJ/hahomematic#1622]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

As soon as a Hm(IP) device firmware are ready for update (=update entity for the device has state `on`), the memory consumption of HA is constantly increasing until HA hangs and the watchdog restarts it. It seems to get worse with an increasing number of devices ready for update, but it's already noticeable with a single one. As I only have HmIP devices, I don't know whether it specific for HmIP devices.

Without HmIP devices ready for update, the memory consumption is really stable.

I don't think it's a new issue as I experiences similar issues in the past but could never relate it to this component.
Memory is increasing now with one update entity:
![image](https://github.com/user-attachments/assets/d385a365-06aa-4c9f-9a10-836afac511d1)

In March I had a ~8-10 device updates ready:
![image](https://github.com/user-attachments/assets/07a3674a-0616-49ed-8418-d20d7327162d)

### What version of HomematicIP (local) has the issue?

1.63.1

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.75.7

### What hardware are you running for your system?

Pi4 for HA, Pi3 for piVCCU3

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information (no logs here)

[config_entry-homematicip_local-7d64311ecfe351677dc3647105a9fec7.json](https://github.com/user-attachments/files/16441802/config_entry-homematicip_local-7d64311ecfe351677dc3647105a9fec7.json)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
No entries from this component in the logs
```

### Additional information

How to reproduce: 

1. Upload a new device firmware to the CCU3 and wait until the device is ready for update and the update entities on HA are in state `on`. 
2. Keep an eye on the memory consumption, it's slowly increasing. The more update entities are in state `on`, the faster the memory consumption increases (until the update entities are `off` again).

**Comment by SukramJ** [comment]
According to your diagnostic file you are using version 1.62.1.
Please update to the latest version.
Afterwards enable debug logging for this integration during the ongoing update.

**Comment by dfigus** [comment]
Now running the latest version and the memory is increasing slowly again. Debug log of about 4 hours:
[home-assistant_2024-07-31T18-45-03.386Z.log](https://github.com/user-attachments/files/16446006/home-assistant_2024-07-31T18-45-03.386Z.log)

Just to be precise, the memory leak does not occur when the update is triggered. The memory leak is happening when the device is ready for update (FW transferred from CCU to device, update entity has state `on`). Once the device is updated, the memory leak does no longer occur.

**Comment by SukramJ** [comment]
This is hard to analyse.
Try beta version [1.64.0b2](https://github.com/danielperna84/custom_homematic/releases/tag/1.64.0b2). That reduces the amount of data loaded while "device is ready for update".

**Comment by dfigus** [comment]
Thanks, I updated to the beta version and keep an eye on the memory consumption. I also enabled the memory profiler with 10 min intervals this morning and here are 5 hours of the log with 1.63.1:
[memory_profiler.log](https://github.com/user-attachments/files/16456166/memory_profiler.log)
I can't see much info in there, but maybe you are.

If you like I can also get a memory profile or dump an object as described [here](https://www.home-assistant.io/integrations/profiler).

**Comment by SukramJ** [comment]
> I can't see much info in there

Me too!

You should update to [1.64.0b3](https://github.com/danielperna84/custom_homematic/releases/tag/1.64.0b3).
1.64.0b2 has an issue with entity descriptions.

> If you like I can also get a memory profile or dump an object as described [here](https://www.home-assistant.io/integrations/profiler).

Let's try it.

**Comment by danielperna84** [comment]
Are you sure this is really caused by the available updates? The screenshot below shows how haos eats memory on my Promox across one week. And in my new house I don't use HomeMatic anymore.

![image](https://github.com/user-attachments/assets/9ae94e66-75cb-4364-aa4e-cca701c91089)

**Comment by dfigus** [comment]
@danielperna84 I'm pretty sure on this as on my end the memory consumption is really stable. It started when the devices were ready for the update and in the past I had a similar experience. It seems to get worse with more devices ready for update (in March I had around 15 devices ready and within a few days it consumed all memory).

**Comment by SukramJ** [comment]
@dfigus What is the metric `Raspberry PI Speicherauslastung`. I can't find it on my PI.
I only have` sensor.home_assistant_core_arbeitsspeicher_in_prozent` from Supervisor Core

Any news about version [1.64.0b3](https://github.com/danielperna84/custom_homematic/releases/tag/1.64.0b3)?

**Comment by dfigus** [comment]
> @dfigus What is the metric `Raspberry PI Speicherauslastung`. I can't find it on my PI.
> 
> I only have` sensor.home_assistant_core_arbeitsspeicher_in_prozent` from Supervisor Core
> 

I use the [System monitor](https://www.home-assistant.io/integrations/systemmonitor/) integration. This shows the details of the host system. Your sensor probably only shows the usage of the HA Core docker container. But the memory growth is coming from the HA container. 

> 
> Any news about version [1.64.0b3](https://github.com/danielperna84/custom_homematic/releases/tag/1.64.0b3)?
> 
> 

The memory consumption is increasing slower than before. I'll take a memory dump once I'm at my PC and report back here.

**Comment by SukramJ** [comment]
The system monitor integration is too global for me. It makes no sense for me to look at the whole system, as that includes the linux caches and add-ons. I'm only interested in the memory behavior of the core. So please add the values ​​for `sensor.home_assistant_core_ram_in_percent`. My system has been running stable for months with a memory usage of 95%, with 90% being used by the Linux cache at times

**Comment by SukramJ** [comment]
Which database do you use for HA? The integrated SQL-Lite, an addon like mariadb or an external one?

**Comment by dfigus** [comment]
> The system monitor integration is too global for me. It makes no sense for me to look at the whole system, as that includes the linux caches and add-ons. I'm only interested in the memory behavior of the core. So please add the values ​​for `sensor.home_assistant_core_ram_in_percent`. My system has been running stable for months with a memory usage of 95%, with 90% being used by the Linux cache at times

I enabled the HA core sensor and there is just slight increase in a few days:
![image](https://github.com/user-attachments/assets/3490e5dd-79b4-4aba-80d1-315523b9234c)
The new beta is definitely an improvement.

> Which database do you use for HA? The integrated SQL-Lite, an addon like mariadb or an external one?

I use the integrated SQL-Lite DB. 

I also tried to dump the growing objects in memory via the HA profiler, but it's now a 600MB text file... Hard to analyze as the main growing objects are plain `dict` and `list`. With the current slow memory increase I think the memory leak is no longer practically have any negative effect. If you don't have any other idea to track it further, we can close the issue. 

I would keep an eye on the memory consumption and maybe next time when HA firmware updates are ready, you can also check on your system.

**Comment by SukramJ** [comment]
Thanks for your feedback.
I close the issue and see what happens next time.
