### ISSUE TITLE
Add Homatic I (Local) integration fails with :"Invalid handler specified"

### ISSUE THREAD

**Issue by TobseF** [SukramJ/hahomematic#1630]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I try to add the Homatic I (Local) integration on the Integrations Dashboard (config/integrations/dashboard).
The _Homematic(IP) Local_ HAC is installed in the latest `1.64.0` on my fresh Home Assistant `2024.8.0`.
I try to finish step "Configuring custom_homematic" in the tutorial.
After pressing "ADD INTEGRATION" i can search and find the "Homeatic(IP) Local" integration.
When I click on the integration, an error message appears with:
```
Config flow could not be loaded: {"message":"Invalid handler specified"}
````

In addition, the logs show the error `No module named 'hahomematic'`:
```
2024-08-10 11:05:28.165 ERROR (MainThread) [homeassistant.config_entries]
Error occurred loading flow for integration homematicip_local: No module named 'hahomematic'
```

![2024-08-10_12h21_58](https://github.com/user-attachments/assets/930eb94e-ef94-4d8e-89e6-90e44e3ca497)
![2024-08-10_12h22_09](https://github.com/user-attachments/assets/7439ed31-814b-4cdc-a28e-17b7fa49f58c)

### What version of HomematicIP (local) has the issue?

1.64.0

### What type of installation are you running?

Home Assistant Container

### What type of installation are you running for your homematic backend?

CCU3

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```
2024-08-10 11:05:28.165 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration homematicip_local: No module named 'hahomematic'
```

**Comment by SukramJ** [comment]
> Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

Please add logs.

**Comment by TobseF** [comment]
Goo point... added the log output which shows another error message as well.

**Comment by SukramJ** [comment]
Please add the whole log.

**Comment by TobseF** [comment]
### 📃 Full log
 [home-assistant_2024-08-10T12-25-32.937Z.log](https://github.com/user-attachments/files/16569565/home-assistant_2024-08-10T12-25-32.937Z.log)

**Comment by SukramJ** [comment]
> Error occurred loading flow for integration homematicip_local: No module named 'hahomematic'

This indicates that your HA is not able to download the required backend dependency 'hahomematic'.
This is more of a problem in HA on your system than an integration issue.

Restart HA try again, If that doesn't help you should enable debug logging for HA (not only for this integration) restart HA and try again.

**Comment by TobseF** [comment]
@SukramJ Thanks for your support.
I downloaded the HARC again, and now it works.
