### ISSUE TITLE
Loads very slow or stops with error

### ISSUE THREAD

**Issue by Mappenhei** [SukramJ/hahomematic#1633]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

The integration is loading very slow after home assistant was restarted. And even worse, the integration does not start and stops with error from time to time.

### What version of HomematicIP (local) has the issue?

1.64.0

### What was the last working version of HomematicIP (local)?

1.64.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.77.7

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information (no logs here)

[config_entry-homematicip_local-2d56b9299185d8984acb5dbb8f5b4e9f.json](https://github.com/user-attachments/files/16629725/config_entry-homematicip_local-2d56b9299185d8984acb5dbb8f5b4e9f.json)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
If slow:
Logger: homeassistant.bootstrap
Quelle: bootstrap.py:739
Erstmals aufgetreten: 21:27:39 (2 Vorkommnisse)
Zuletzt protokolliert: 21:28:39

Waiting on integrations to complete setup: {('homematicip_local', '2d56b9299185d8984acb5dbb8f5b4e9f'): 80370.210077693}

If it fails:
Logger: homeassistant.config_entries
Quelle: config_entries.py:604
Erstmals aufgetreten: 21:34:23 (1 Vorkommnisse)
Zuletzt protokolliert: 21:34:23

Error setting up entry PiVCCU3 for homematicip_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homematicip_local/__init__.py", line 68, in async_setup_entry
    await control.start_central()
  File "/config/custom_components/homematicip_local/control_unit.py", line 223, in start_central
    await super().start_central()
  File "/config/custom_components/homematicip_local/control_unit.py", line 123, in start_central
    await self._central.start()
  File "/usr/local/lib/python3.12/site-packages/hahomematic/central/__init__.py", line 312, in start
    await self._start_clients()
  File "/usr/local/lib/python3.12/site-packages/hahomematic/central/__init__.py", line 406, in _start_clients
    await self._init_clients()
  File "/usr/local/lib/python3.12/site-packages/hahomematic/central/__init__.py", line 477, in _init_clients
    if await client.proxy_init() == ProxyInitState.INIT_SUCCESS:
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hahomematic/client/__init__.py", line 139, in proxy_init
    await self._proxy.init(self._config.init_url, self.interface_id)
  File "/usr/local/lib/python3.12/site-packages/hahomematic/client/xml_rpc.py", line 126, in __async_request
    result = await self._looper.async_add_executor_job(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError
```

## System Information

version | core-2024.8.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.44-haos
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4994
Installed Version | 1.34.0
Stage | running
Available Repositories | 1393
Downloaded Repositories | 21
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.0
-- | --
update_channel | stable
supervisor_version | supervisor-2024.08.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 38.7 GB
disk_used | 12.4 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | InfluxDB (5.0.0), Terminal & SSH (9.14.0), Log Viewer (0.17.0), Uptime Kuma (0.12.1), File editor (5.8.0), MQTT Explorer (browser-1.0.3), Studio Code Server (5.15.0), Whisper (2.1.2), Piper (1.5.2), Matter Server (6.4.1), Grott stable branch (2.8) (0.1.11), Mosquitto broker (6.4.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 4
views | 8
mode | storage

</details>

<details><summary>Miele</summary>

component_version | 2024.8.1
-- | --
reach_miele_cloud | ok

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 5. August 2024 um 18:58
-- | --
current_recorder_run | 15. August 2024 um 21:26
estimated_db_size | 771.41 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

**Comment by SukramJ** [comment]
I guess slow is a local problem.
Try restart your CCU and afterwards HA.
I that a new installation?

**Comment by Mappenhei** [comment]
Yes I restarted both, my Proxmox (Home assistant environment) and my CCU. I also checked CPU and memory load on both machines. Everything runs smoothly. The error occurs since home assistant was updated with OS 13 and 2024.8.
Edit: the installation is not new

**Comment by SukramJ** [comment]
You are running PiVCCU3 on a CCU3?

Please enable debug logging for the integration an restart HA?
Attach the full log file here after the integration is ready.

**Comment by Mappenhei** [comment]
It‘s a PiVCCU3 running on a RbPi4 (nothing else is running on the Pi)
Debug was enabled. Unfortunately I can‘t indicate a root cause out of 
[home-assistant_2024-08-15T21-07-24.596Z.log](https://github.com/user-attachments/files/16630360/home-assistant_2024-08-15T21-07-24.596Z.log)
the log.

**Comment by Mappenhei** [comment]
Log after homematic stopped with error, but still no indicator :-(
[home-assistant_2024-08-15T21-26-47.177Z.log](https://github.com/user-attachments/files/16630491/home-assistant_2024-08-15T21-26-47.177Z.log)

**Comment by SukramJ** [comment]
Those are no logs with debug enabled!

Besides that your log contains far to many ERRORS from multiple integrations.
> does not generate unique IDs

These errors are not normal for this integration, so I suspect that there is something wrong with the HA registries. There are also error messages related to an (older?) instance named raspberry.

I can only recommend you to reinstall this integration.
Ensure, while this integration is uninstalled, that there are no leftovers on the system.

I don’t think that there is an issue with the integration‘s code.
