### ISSUE TITLE
2024.8 Climate Min/Max Value - 4,5 Degree ist now an invalid Temperature

### ISSUE THREAD

**Issue by mcfly2283** [SukramJ/hahomematic#1642]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

As of HA 2024.8 it is not possible to Set the TRV Temperature to 4,5 Degree to switch off the TRV.

The TRV does support 5-30,5 Degrees at the moment.
![image](https://github.com/user-attachments/assets/febfe7b7-1b77-4e24-b0c5-3f4eaf57b255)
I Think the right setable Range schould be 4,5 - 30,5 Degrees, so we can also switch off the TRV via Set Temeprature.

There is also an open Issue related to to this Problem
https://github.com/home-assistant/core/issues/123612

https://github.com/home-assistant/developers.home-assistant/pull/2259/files
"As of Home Assistant Core 2024.8, we have implemented validation for the temperature action call provided by the `ClimateEntity`.

Integrations no longer need to check this within their own set temperature methods (`async_set_temperature`/`set_temperature`).

However, it's important that integrations specify the `min_temp` and `max_temp` properties correctly, or the user might not be able to set their correct temperature if validation fails.
Likewise, integrations that handle devices which can operate on both `Celsius` and `Fahrenheit` need to convert their respective `min_temp` and `max_temp` values accordingly."

### What version of HomematicIP (local) has the issue?

1.64.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic HA-Addon

### What hardware are you running for your system?

3.75.7.20240601

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Just turn_off (climate.turn_off) your device instead of setting the temperature to 4.5 degree and it works.

**Comment by SukramJ** [comment]
Have a look at this [discussion](https://github.com/danielperna84/hahomematic/discussions/661)

**Comment by mcfly2283** [comment]
Thank you for the Informations, Sukram.
But then, what about the 4,5 Degree within the Climate-Card when switching off the Device? 
Under this light, this is seemms absolutely wrong for me... 

![image](https://github.com/user-attachments/assets/7103f830-fe90-4050-93aa-0ceb22165708)

**Comment by SukramJ** [comment]
I don't care about (custom) cards!
And what is the problem? Homematic semantic is that 4,5degree means off. 

If you want to discuss this topic use the linked discussion or create a new one.

**Comment by SukramJ** [comment]
Closing this, as this is not an issue with the integration.
