### ISSUE TITLE
Memory leak when device firmware update is ready

### ISSUE THREAD

**Issue by dfigus** [SukramJ/hahomematic#1648]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Follow up to #1622 which is locked and I can't reopen.

As a `dict` was growing constantly, I did a [profiler.dump_log_objects](https://www.home-assistant.io/integrations/profiler/#action-profilerdump_log_objects). As this gave me a 600mb txt file, it took me some time to analyze, but I found something that looks like a leak:

The dict object contains 22.889 entries and each entry contains a list with 1030 duplicate entries or a multiple of it e.g. for HmIP-RCV-1 it have 51.500 list entries (with values 1-50 repeated 1030 times):
![image](https://github.com/user-attachments/assets/6d0862b0-0835-4483-9f9b-e8b9f6828dd9)

HmIP-RCV-1:
![image](https://github.com/user-attachments/assets/4c044119-6087-44ef-a49a-f67fd7633aaa)

Maybe this helps to locate the memory leak.

Note: The dump was taken with version 1.64.0b3.

### What version of HomematicIP (local) has the issue?

1.64.0b3

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.75.7

### What hardware are you running for your system?

Pi4 for HA, Pi3 for piVCCU3

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information (no logs here)

see #1622

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
No errors, log file is 600+ MB due to dump
```

**Comment by SukramJ** [comment]
Nice!

**Comment by SukramJ** [comment]
Please retest with 1.65.0b3

**Comment by dfigus** [comment]
Thanks, updated to 1.65.0b3! I'll keep an eye on the memory consumption for around 1-3 days and report back.

**Comment by SukramJ** [comment]
1.65.0b4 should have some minor optimisations.

**Comment by dfigus** [comment]
Thanks, updated to latest beta! I'll report back in the next days.

**Comment by dfigus** [comment]
The memory consumption of HA core (and the whole HA OS) is stable again. It seems that the memory leaks are solved now. Thanks!
