### ISSUE TITLE
Thermostat valve value invalid

### ISSUE THREAD

**Issue by eikowagenknecht** [SukramJ/hahomematic#165]
**custom_component/hahomematic version (if applicable):**
latest

**Home Assistant version (if applicable):**
latest

**CCU version:**
CCU3 Raspberrymatic

**Describe the bug**
The valve is shown underlined in red because it has too many digits after the comma:
![image](https://user-images.githubusercontent.com/1475672/149036028-07a76b88-c03f-4e00-86df-b3372d429f99.png)

Using the buttons increments in in ,1 steps (0,1 > 0,2 > 0,3 ...).

**Expected behavior**
As this is a percentage value, it should be shown as 45 % instead. Or at least support two digits after the comma.

**Additional context**
Side note: What does setting this actually achieve? I can see in homematic that the value is set to whatever I put in and I hear the motor going to the position. But after a very short while it seems to return to the previous position. Quite interesting. I always though this was a read-only value (as it is in the official webUI).

**Comment by Lemocin** [comment]
> As this is a percentage value, it should be shown as 45 % instead.

I think this is not possible due to a limitation of HA, as [Number entities](https://developers.home-assistant.io/docs/core/entity/number/) don't have a Unit.

**Comment by danielperna84** [comment]
This is an automatically generated entity that is not usually used. It has already been mentioned [here](https://github.com/danielperna84/hahomematic/discussions/25#discussioncomment-1949980). For some thermostats it's writable, for some not.

**Comment by sotatech** [comment]
> This is an automatically generated entity that is not usually used. 

@danielperna84 I have always used this value to trigger my heating. If a valve was open > 5% then turn on the heating for that group. Is this not the correct way to do it?

**Comment by danielperna84** [comment]
@sotatech 

Uhm, I'm no expert. But for me that would equate to "if the valve is open >5% then open it even more". Wouldn't the correct automation be "if the ambient temperature is below X turn on the heating"?

**Comment by sotatech** [comment]
The valve postion on the TRV is controlled only by the TRV (or it's Heating Group). It's position is proportional to the set temperature on the TRV compared to the actual temperature. So, if the set temperature is 21 degrees and the measured temperature is 19 degrees, the valve will open. The greater the difference, the more the valve will open to allow a larger flow of hot water to the radiator. As the room heats up, the valve will slowly close.
I control my heating using Groups and change the set temperature using a schedule. There is a separate automation on the CCU that monitors the valve position, and turns on and off the heating pump according to the valve position.
