### ISSUE TITLE
Normally Open contacts shown inverted as on/off - HMW-Sen-SC-12-DR

### ISSUE THREAD

**Issue by dk1305hb** [SukramJ/hahomematic#1653]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

A HMW-Sen-SC-12-DR displays its contacts as on/off not open/close- i dont know if this is normal. The greater problem is the condition. If the contact is open in the ccu it is displayed as „on“ in HA. But it should be „off“. 
Is it possible to change this behavior? 

### What version of HomematicIP (local) has the issue?

1.64.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [X] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
This is an automatically created device with no further customization within this integration. The values are displayed as delivered by the CCU.
If you want to have an inverted binary_sensor then you have to create a [template binary_sensor](https://www.home-assistant.io/integrations/template/) that inverts the behaviour and gives you options for further customization.

Another option is to use the integration spook from HACS that support inverted binary_sensor out of the box.
