### ISSUE TITLE
1.65.x breaks HmIP-WUA level

### ISSUE THREAD

**Issue by Gordon2Freeman** [SukramJ/hahomematic#1656]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Updated today to 1.65.x. After that i couldnt control the levels of HmIP-WUA in HA. The "sensor.hmip_wua_level" (only shows the level) is working. The "number.hmip_wua_level" (controls/sets the level) isnt working anymore. Deleted the entitiy, didnt show up again after several restarts. Worked immediately again after rollback to 1.64.0.

### What version of HomematicIP (local) has the issue?

1.65.0

### What was the last working version of HomematicIP (local)?

1.64.x

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.77.6.20240720

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
There is now a light entity to control the Dimmer.

**Comment by Gordon2Freeman** [comment]
The light entity was only an on/off switch, not a number in percent which I
can set.

SukramJ ***@***.***> schrieb am Do., 22. Aug. 2024, 16:01:

**Comment by SukramJ** [comment]
Please post a screenshot of the light entitiy.
Also press on the light entity and show a screenshot of the details.

**Comment by SukramJ** [comment]
Please run the service [export_device_definition](https://github.com/danielperna84/custom_homematic#homematicip_localexport_device_definition) and upload the device descriptions here .
