### ISSUE TITLE
HmIP-DRG-DALI, Zustand wird nicht korrekt angezeigt.

### ISSUE THREAD

**Issue by EAFSL** [SukramJ/hahomematic#1664]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Zustand von Dali Gruppen (HmIP-DRG-DALI) wird nicht richtig wiedergegeben. 
Die Gruppe wird in HA am Gerät HmIP-DRG-DALI eingeschalten. (Gruppe wird auch tatsächlich geschalten). 
Die Zustandanzeige ändert sich jedoch nach 1 - 2 sec wieder auf AUS obwohl die Lampe noch an ist. 
Ein ausschalten der Lampengruppe ist via HA nicht mehr möglich.

Bei einzelnen Dali Lampen (nicht Gruppen) ist das verhalten korrekt.

### What version of HomematicIP (local) has the issue?

1.65.0

### What was the last working version of HomematicIP (local)?

Never

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.77.6

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
> Zustand von Dali Gruppen (HmIP-DRG-DALI) wird nicht richtig wiedergegeben.

Ich hab keine Ahnung was das sein soll.
Wie unterscheidet man Lampen und Gruppen. Welche Kanäle gehören wozu?

Ein paar Screenshots wären hilfreich.

> Die Lampe wird in HA am Gerät HmIP-DRG-DALI eingeschalten. (Lampe wird auch tatsächlich geschalten).
Der Zustand ändert sich jedoch nach 1 - 2 sec wieder in AUS obwohl die Lampe noch an ist.
Ein ausschalten der Lampengruppe ist via HA nicht mehr möglich.

Lampe oder Gruppe?

Bitte häng auch noch das Log (full log) und die Diagnoseinformation (Integration / drei Punkte Menü) hier an.

**Comment by EAFSL** [comment]
> > Zustand von Dali Gruppen (HmIP-DRG-DALI) wird nicht richtig wiedergegeben.
> 
> Ich hab keine Ahnung was das sein soll. Wie unterscheidet man Lampen und Gruppen. Welche Kanäle gehören wozu?

Kanäle 1 -32 sind Lampen, Kanäle 33 - 48 sind Gruppen. Jede Lampe kann einen oder mehreren Gruppen über die Homematic Config zugewiesen werden. 
> 
> Ein paar Screenshots wären hilfreich.
![image](https://github.com/user-attachments/assets/d1b79683-97c7-45d4-b123-b86c76fb891b)

Ein Bespiel: DALI_OG_Bad_OG:B86C:39 ist eine Gruppe mehrerer Dali Lampen. Betätige ich den gezeigten Schalter, geht das Licht an, Schalter geht wieder aus, Licht bleibt an und es kann auch nicht mehr über HA ausgeschalten werden.

> 
> > Die Lampe wird in HA am Gerät HmIP-DRG-DALI eingeschalten. (Lampe wird auch tatsächlich geschalten).
> > Der Zustand ändert sich jedoch nach 1 - 2 sec wieder in AUS obwohl die Lampe noch an ist.
> > Ein ausschalten der Lampengruppe ist via HA nicht mehr möglich.
> 
> Lampe oder Gruppe?

Sorry, meinte natürlich Gruppe.

> 
> Bitte häng auch noch das Log (full log) und die Diagnoseinformation (Integration / drei Punkte Menü) hier an.

Im Log von Home Assistent Core sind keine Einträge vorhanden.
Download der Diagnoseinformation aktuell nicht möglich, muss ich mir noch ansehen.

**Comment by SukramJ** [comment]
Das Problem ist leider, das aus [Sicht der Integration](https://raw.githubusercontent.com/danielperna84/pydevccu/master/pydevccu/paramset_descriptions/HmIP-DRG-DALI.json) die Kanäle 1-48  gleich sind.

> Der Zustand ändert sich jedoch nach 1 - 2 sec wieder in AUS

Es sieht so aus, als ob die CCU für die Gruppenkanäle keine Events sendet.
Das kann man herausfinden, indem du für die Integration das debug Logging aktivierst, und die entsprechenden Kanäle in HA aber auch mal in der CCU bedienst. Das vollständige Log dann bitte hier anhängen.

**Comment by EAFSL** [comment]
> Das Problem ist leider, das aus [Sicht der Integration](https://raw.githubusercontent.com/danielperna84/pydevccu/master/pydevccu/paramset_descriptions/HmIP-DRG-DALI.json) die Kanäle 1-48  gleich sind.
> 
> 
> 
> > Der Zustand ändert sich jedoch nach 1 - 2 sec wieder in AUS
> 
> 
> 
> Es sieht so aus, als ob die CCU für die Gruppenkanäle keine Events sendet.
> 
> Das kann man herausfinden, indem du für die Integration das debug Logging aktivierst, und die entsprechenden Kanäle in HA aber auch mal in der CCU bedienst. Das vollständige Log dann bitte hier anhängen.
> 
> 


Hab die Gruppe zuerst in der CCU ein und aus geschalten. 
Anschließend habe ich die Gruppe via HA ein und (versucht) auszuschalten:

Gruppe CH40 besteht aus Lampe CH22 und CH17

2024-08-26 16:46:51.880 DEBUG (MainThread) [custom_components.homematicip_local.generic_entity] Device updated event fired for DALI_OG:B85C DALI_OG_Kueche_Fenster ch40
2024-08-26 16:46:52.177 DEBUG (MainThread) [custom_components.homematicip_local.generic_entity] Device updated event fired for DALI_OG:B85C :17
2024-08-26 16:46:52.474 DEBUG (MainThread) [custom_components.homematicip_local.generic_entity] Device updated event fired for DALI_OG:B85C :22
2024-08-26 16:46:56.805 DEBUG (MainThread) [custom_components.homematicip_local.generic_entity] Device updated event fired for DALI_OG:B85C DALI_OG_Kueche_Fenster ch40
2024-08-26 16:46:57.101 DEBUG (MainThread) [custom_components.homematicip_local.generic_entity] Device updated event fired for DALI_OG:B85C :17
2024-08-26 16:46:57.397 DEBUG (MainThread) [custom_components.homematicip_local.generic_entity] Device updated event fired for DALI_OG:B85C :22
2024-08-26 16:47:14.990 DEBUG (MainThread) [custom_components.homematicip_local.generic_entity] Device updated event fired for DALI_OG:B85C DALI_OG_Kueche_Fenster ch40
2024-08-26 16:47:15.118 DEBUG (MainThread) [custom_components.homematicip_local.generic_entity] Device updated event fired for DALI_OG:B85C :22
2024-08-26 16:47:15.286 DEBUG (MainThread) [custom_components.homematicip_local.generic_entity] Device updated event fired for DALI_OG:B85C :17
2024-08-26 16:47:19.818 DEBUG (MainThread) [custom_components.homematicip_local.generic_entity] Device refreshed event fired for DALI_OG:B85C :17
2024-08-26 16:47:20.115 DEBUG (MainThread) [custom_components.homematicip_local.generic_entity] Device refreshed event fired for DALI_OG:B85C :22
2024-08-26 16:47:27.827 DEBUG (MainThread) [custom_components.homematicip_local.generic_entity] Device updated event fired for DALI_OG:B85C DALI_OG_Kueche_Fenster ch40
2024-08-26 16:47:28.124 DEBUG (MainThread) [custom_components.homematicip_local.generic_entity] Device updated event fired for DALI_OG:B85C :17
2024-08-26 16:47:28.420 DEBUG (MainThread) [custom_components.homematicip_local.generic_entity] Device updated event fired for DALI_OG:B85C :22

**Comment by SukramJ** [comment]
Nächstes mal bitte als Dateien anhängen.
~~Wenn das alle Logeinträge sind, dann wird auf den Kanälen ab 33 nichts von der CCU gesendet. Warum das so ist solltest Du mit dem Hersteller klären. Ich kann da leider nichts machen, außer die Kanäle nicht mehr anzuzeigen.~~
Edit: Auf einem größeren Gerät sieht man mehr.

**Comment by SukramJ** [comment]
Trag bitte folgendes in der configuration.yaml ein:

```
logger:
  default: warn
  logs:
    hahomematic.client.xml_rpc: debug
```
Danach HA neustarten, und noch mal durchtesten ( Mit mindestens 10s zwischen den Aktionen)
Bitte schreib dir die Zeiten auf, wann Du was gemacht hast, dann kann ich das einfache nachvollziehen.
Danach bitte das vollständige Log als Datei anhängen

**Comment by EAFSL** [comment]
Folgender Testablauf:
Ablauf:

CCU3
Gruppe CH40 ein - 19:18:40
Gruppe CH40 aus - 19:18:50

HA
Gruppe CH40 ein - 19:19:40
Gruppe CH40 ein (weil ja auto auf aus) - 19:19:50

[home-assistant_homematicip_local_2024-08-26T17-20-26.668Z.log](https://github.com/user-attachments/files/16751726/home-assistant_homematicip_local_2024-08-26T17-20-26.668Z.log)

**Comment by SukramJ** [comment]
Die Ereignisse konnte ich soweit nachvollziehen, sehen richtig aus und lösen auch die erwarteten Events aus. Ich sehe keinen Grund, warum es nicht funktionieren sollte.

```
2024-08-26 19:18:42.262 DEBUG (MainThread) [hahomematic.central] EVENT: interface_id = RaspberryMatic-HmIP-RF, channel_address = 0033A0C98FB85C:40, parameter = LEVEL, value = 1.0
2024-08-26 19:18:42.560 DEBUG (MainThread) [hahomematic.central] EVENT: interface_id = RaspberryMatic-HmIP-RF, channel_address = 0033A0C98FB85C:17, parameter = LEVEL, value = 1.0
2024-08-26 19:18:42.855 DEBUG (MainThread) [hahomematic.central] EVENT: interface_id = RaspberryMatic-HmIP-RF, channel_address = 0033A0C98FB85C:22, parameter = LEVEL, value = 1.0


2024-08-26 19:18:52.117 DEBUG (MainThread) [hahomematic.central] EVENT: interface_id = RaspberryMatic-HmIP-RF, channel_address = 0033A0C98FB85C:17, parameter = LEVEL, value = 0.0
2024-08-26 19:18:52.820 DEBUG (MainThread) [hahomematic.central] EVENT: interface_id = RaspberryMatic-HmIP-RF, channel_address = 0033A0C98FB85C:40, parameter = LEVEL, value = 0.0
2024-08-26 19:18:52.950 DEBUG (MainThread) [hahomematic.central] EVENT: interface_id = RaspberryMatic-HmIP-RF, channel_address = 0033A0C98FB85C:22, parameter = LEVEL, value = 0.0


2024-08-26 19:19:40.516 DEBUG (MainThread) [hahomematic.client] SET_VALUE: 0033A0C98FB85C:40, LEVEL, 1.0
2024-08-26 19:19:40.516 DEBUG (MainThread) [hahomematic.client.xml_rpc] __ASYNC_REQUEST: ('setValue', ('0033A0C98FB85C:40', 'LEVEL', 1.0))
2024-08-26 19:19:42.500 DEBUG (MainThread) [hahomematic.central] EVENT: interface_id = RaspberryMatic-HmIP-RF, channel_address = 0033A0C98FB85C:40, parameter = LEVEL, value = 1.0
2024-08-26 19:19:42.797 DEBUG (MainThread) [hahomematic.central] EVENT: interface_id = RaspberryMatic-HmIP-RF, channel_address = 0033A0C98FB85C:17, parameter = LEVEL, value = 1.0
2024-08-26 19:19:43.095 DEBUG (MainThread) [hahomematic.central] EVENT: interface_id = RaspberryMatic-HmIP-RF, channel_address = 0033A0C98FB85C:22, parameter = LEVEL, value = 1.0

2024-08-26 19:19:50.773 DEBUG (MainThread) [hahomematic.client] SET_VALUE: 0033A0C98FB85C:40, LEVEL, 1.0
2024-08-26 19:19:50.773 DEBUG (MainThread) [hahomematic.client.xml_rpc] __ASYNC_REQUEST: ('setValue', ('0033A0C98FB85C:40', 'LEVEL', 1.0))
```

Werden die Entitäten 17,22 und 40  in HA bei CCU-Betätigung geschaltet?

**Comment by EAFSL** [comment]
> Die Ereignisse konnte ich soweit nachvollziehen, sehen richtig aus und lösen auch die erwarteten Events aus. Ich sehe keinen Grund, warum es nicht funktionieren sollte.
> 
> ```
> 2024-08-26 19:18:42.262 DEBUG (MainThread) [hahomematic.central] EVENT: interface_id = RaspberryMatic-HmIP-RF, channel_address = 0033A0C98FB85C:40, parameter = LEVEL, value = 1.0
> 2024-08-26 19:18:42.560 DEBUG (MainThread) [hahomematic.central] EVENT: interface_id = RaspberryMatic-HmIP-RF, channel_address = 0033A0C98FB85C:17, parameter = LEVEL, value = 1.0
> 2024-08-26 19:18:42.855 DEBUG (MainThread) [hahomematic.central] EVENT: interface_id = RaspberryMatic-HmIP-RF, channel_address = 0033A0C98FB85C:22, parameter = LEVEL, value = 1.0
> 
> 
> 2024-08-26 19:18:52.117 DEBUG (MainThread) [hahomematic.central] EVENT: interface_id = RaspberryMatic-HmIP-RF, channel_address = 0033A0C98FB85C:17, parameter = LEVEL, value = 0.0
> 2024-08-26 19:18:52.820 DEBUG (MainThread) [hahomematic.central] EVENT: interface_id = RaspberryMatic-HmIP-RF, channel_address = 0033A0C98FB85C:40, parameter = LEVEL, value = 0.0
> 2024-08-26 19:18:52.950 DEBUG (MainThread) [hahomematic.central] EVENT: interface_id = RaspberryMatic-HmIP-RF, channel_address = 0033A0C98FB85C:22, parameter = LEVEL, value = 0.0
> 
> 
> 2024-08-26 19:19:40.516 DEBUG (MainThread) [hahomematic.client] SET_VALUE: 0033A0C98FB85C:40, LEVEL, 1.0
> 2024-08-26 19:19:40.516 DEBUG (MainThread) [hahomematic.client.xml_rpc] __ASYNC_REQUEST: ('setValue', ('0033A0C98FB85C:40', 'LEVEL', 1.0))
> 2024-08-26 19:19:42.500 DEBUG (MainThread) [hahomematic.central] EVENT: interface_id = RaspberryMatic-HmIP-RF, channel_address = 0033A0C98FB85C:40, parameter = LEVEL, value = 1.0
> 2024-08-26 19:19:42.797 DEBUG (MainThread) [hahomematic.central] EVENT: interface_id = RaspberryMatic-HmIP-RF, channel_address = 0033A0C98FB85C:17, parameter = LEVEL, value = 1.0
> 2024-08-26 19:19:43.095 DEBUG (MainThread) [hahomematic.central] EVENT: interface_id = RaspberryMatic-HmIP-RF, channel_address = 0033A0C98FB85C:22, parameter = LEVEL, value = 1.0
> 
> 2024-08-26 19:19:50.773 DEBUG (MainThread) [hahomematic.client] SET_VALUE: 0033A0C98FB85C:40, LEVEL, 1.0
> 2024-08-26 19:19:50.773 DEBUG (MainThread) [hahomematic.client.xml_rpc] __ASYNC_REQUEST: ('setValue', ('0033A0C98FB85C:40', 'LEVEL', 1.0))
> ```
> 
> Werden die Entitäten 17,22 und 40 in HA bei CCU-Betätigung geschaltet?

Nein in HA wird bei CCU-Betätigung nichts geschalten (alles immer auf AUS). 
Ich habe jedoch an zwei Kanälen Dali Lampen wo auch die Farbtemperatur eingestellt werden kann. Diese funktionieren auch in HA so wie sie sollen. Aber nur diese zwei Lampen. 
Diese beiden Lampen sind auch in einer gemeinsamen Gruppe. Da ist dann die Grundfunktion gegeben. Mit folgendem Fehlverhalten: Gruppe in HA auf ON, Lampe geht an, nach 2 sec geht der Schalter in HA auf OFF und dann direkt wieder auf ON und ist somit korrekt. Auch bei AUS, geht der Schalter auf AUS und die Lampen sind aus, dann nochmals kurz auf AN und dann direkt wieder auf AUS was auch korrekt ist. 

Hoffe das war nun nicht zu viel Verwirrung.

**Comment by SukramJ** [comment]
Bitte lösch mal deinen Browsercache und häng bitte noch die Diagnoseinformation an.

**Comment by EAFSL** [comment]
> Bitte lösch mal deinen Browsercache und häng bitte noch die Diagnoseinformation an.

Welche Aktionen sollen danach ausgeführt werden?

**Comment by SukramJ** [comment]
> Welche Aktionen sollen danach ausgeführt werden?

Ganz normale Bedienung. Ich will nur ausschliessen, das dein Frontend veralteten HA Code geladen hat, ansonsten gehen mir die Ideen aus.

**Comment by EAFSL** [comment]
Cache geleert und Browser gewechselt:
Ablauf:
HA
Gruppe CH40 ein - 20:49:10
Gruppe CH40 ein (weil ja auto auf aus) - 20:49:20

CCU
Gruppe CH40 aus - 20:50:00

Gruppe mit Funktion CH39 über HA:

Gruppe CH39 ein - 20:50:30
Gruppe CH39 aus - 20:51:00
CH39 = CH18 + CH19
[home-assistant_homematicip_local_2024-08-26T18-51-26.582Z.log](https://github.com/user-attachments/files/16752555/home-assistant_homematicip_local_2024-08-26T18-51-26.582Z.log)

Keine Änderung im Verhalten. 
CH39 funktioniert wie oben beschrieben über HA. CH40 kann nur EIN geschalten werden und hat anschließend falschen Status AUS.

**Comment by SukramJ** [comment]
Die Lampen an Kanal 39 sind zumindest teilweise farblich einstellbar?
Die Lampen an Kanal 40 sind alle nicht farbig?

Wenn du die Geräte von Kanal 39 und 40 tauschst, dann funktioniert Kanal 40 aber Kanal 39 nicht mehr?

**Comment by EAFSL** [comment]
> Die Lampen an Kanal 39 sind zumindest teilweise farblich einstellbar?
> 
> Die Lampen an Kanal 40 sind alle nicht farbig?
> 
> 
> 
> Wenn du die Geräte von Kanal 39 und 40 tauschst, dann funktioniert Kanal 40 aber Kanal 39 nicht mehr?

Ja korrekt, Ch39 sind sogenannte DT8 Dali Geräte. Das zugehörige Steuergerät hat zwei Kanäle wodurch die Farbtemperatur eingestellt werden kann.
Ch40 sind DT6 Dali Geräte. Sind LEDs mit nur einem Kanalausgang am Steuergerät und es kann nur die Helligkeit eingestellt werden.
Die Lampen sind ja nur über Adressen zugewiesen. Der Fehler wandert bei Kanalwechsel Ch39 <-> Ch40 mit.

**Comment by SukramJ** [comment]
Langsam dämmerts.
Bitte häng mir aus Entwicklerwerkzeuge -> Zustände für die folgenden Kanäle die jeweils vollständigen Attribute hier an:
- 17
- 18
- 19
- 21
- 39
- 40

**Comment by EAFSL** [comment]
> Langsam dämmerts.
> 
> Bitte häng mir aus Entwicklerwerkzeuge -> Zustände für die folgenden Kanäle die jeweils vollständigen Attribute hier an:
> 
> - 17

effect_list:
  - NO_EFFECT
  - EFFECT_01_END_CURRENT_PROFILE
  - EFFECT_01_INTERRUPT_CURRENT_PROFILE
  - EFFECT_02_END_CURRENT_PROFILE
  - EFFECT_02_INTERRUPT_CURRENT_PROFILE
  - EFFECT_03_END_CURRENT_PROFILE
  - EFFECT_03_INTERRUPT_CURRENT_PROFILE
  - EFFECT_04_END_CURRENT_PROFILE
  - EFFECT_04_INTERRUPT_CURRENT_PROFILE
  - EFFECT_05_END_CURRENT_PROFILE
  - EFFECT_05_INTERRUPT_CURRENT_PROFILE
  - EFFECT_06_END_CURRENT_PROFILE
  - EFFECT_06_INTERRUPT_CURRENT_PROFILE
  - EFFECT_07_END_CURRENT_PROFILE
  - EFFECT_07_INTERRUPT_CURRENT_PROFILE
  - EFFECT_08_END_CURRENT_PROFILE
  - EFFECT_08_INTERRUPT_CURRENT_PROFILE
  - EFFECT_09_END_CURRENT_PROFILE
  - EFFECT_09_INTERRUPT_CURRENT_PROFILE
  - EFFECT_10_END_CURRENT_PROFILE
  - EFFECT_10_INTERRUPT_CURRENT_PROFILE
supported_color_modes:
  - brightness
effect: null
color_mode: null
brightness: null
interface_id: RaspberryMatic-HmIP-RF
address: 0033A0C98FB85C:17
model: HmIP-DRG-DALI
entity_type: custom
value_state: restored
friendly_name: DALI_OG:B85C :17
supported_features: 36

> - 18

min_color_temp_kelvin: 2000
max_color_temp_kelvin: 6535
min_mireds: 153
max_mireds: 500
effect_list:
  - NO_EFFECT
  - EFFECT_01_END_CURRENT_PROFILE
  - EFFECT_01_INTERRUPT_CURRENT_PROFILE
  - EFFECT_02_END_CURRENT_PROFILE
  - EFFECT_02_INTERRUPT_CURRENT_PROFILE
  - EFFECT_03_END_CURRENT_PROFILE
  - EFFECT_03_INTERRUPT_CURRENT_PROFILE
  - EFFECT_04_END_CURRENT_PROFILE
  - EFFECT_04_INTERRUPT_CURRENT_PROFILE
  - EFFECT_05_END_CURRENT_PROFILE
  - EFFECT_05_INTERRUPT_CURRENT_PROFILE
  - EFFECT_06_END_CURRENT_PROFILE
  - EFFECT_06_INTERRUPT_CURRENT_PROFILE
  - EFFECT_07_END_CURRENT_PROFILE
  - EFFECT_07_INTERRUPT_CURRENT_PROFILE
  - EFFECT_08_END_CURRENT_PROFILE
  - EFFECT_08_INTERRUPT_CURRENT_PROFILE
  - EFFECT_09_END_CURRENT_PROFILE
  - EFFECT_09_INTERRUPT_CURRENT_PROFILE
  - EFFECT_10_END_CURRENT_PROFILE
  - EFFECT_10_INTERRUPT_CURRENT_PROFILE
supported_color_modes:
  - color_temp
effect: null
color_mode: null
brightness: null
color_temp_kelvin: null
color_temp: null
hs_color: null
rgb_color: null
xy_color: null
interface_id: RaspberryMatic-HmIP-RF
address: 0033A0C98FB85C:18
model: HmIP-DRG-DALI
entity_type: custom
value_state: valid
friendly_name: DALI_OG:B85C :18
supported_features: 36

> - 19

min_color_temp_kelvin: 2000
max_color_temp_kelvin: 6535
min_mireds: 153
max_mireds: 500
effect_list:
  - NO_EFFECT
  - EFFECT_01_END_CURRENT_PROFILE
  - EFFECT_01_INTERRUPT_CURRENT_PROFILE
  - EFFECT_02_END_CURRENT_PROFILE
  - EFFECT_02_INTERRUPT_CURRENT_PROFILE
  - EFFECT_03_END_CURRENT_PROFILE
  - EFFECT_03_INTERRUPT_CURRENT_PROFILE
  - EFFECT_04_END_CURRENT_PROFILE
  - EFFECT_04_INTERRUPT_CURRENT_PROFILE
  - EFFECT_05_END_CURRENT_PROFILE
  - EFFECT_05_INTERRUPT_CURRENT_PROFILE
  - EFFECT_06_END_CURRENT_PROFILE
  - EFFECT_06_INTERRUPT_CURRENT_PROFILE
  - EFFECT_07_END_CURRENT_PROFILE
  - EFFECT_07_INTERRUPT_CURRENT_PROFILE
  - EFFECT_08_END_CURRENT_PROFILE
  - EFFECT_08_INTERRUPT_CURRENT_PROFILE
  - EFFECT_09_END_CURRENT_PROFILE
  - EFFECT_09_INTERRUPT_CURRENT_PROFILE
  - EFFECT_10_END_CURRENT_PROFILE
  - EFFECT_10_INTERRUPT_CURRENT_PROFILE
supported_color_modes:
  - color_temp
effect: null
color_mode: null
brightness: null
color_temp_kelvin: null
color_temp: null
hs_color: null
rgb_color: null
xy_color: null
interface_id: RaspberryMatic-HmIP-RF
address: 0033A0C98FB85C:19
model: HmIP-DRG-DALI
entity_type: custom
value_state: valid
friendly_name: DALI_OG:B85C :19
supported_features: 36

> - 21

effect_list:
  - NO_EFFECT
  - EFFECT_01_END_CURRENT_PROFILE
  - EFFECT_01_INTERRUPT_CURRENT_PROFILE
  - EFFECT_02_END_CURRENT_PROFILE
  - EFFECT_02_INTERRUPT_CURRENT_PROFILE
  - EFFECT_03_END_CURRENT_PROFILE
  - EFFECT_03_INTERRUPT_CURRENT_PROFILE
  - EFFECT_04_END_CURRENT_PROFILE
  - EFFECT_04_INTERRUPT_CURRENT_PROFILE
  - EFFECT_05_END_CURRENT_PROFILE
  - EFFECT_05_INTERRUPT_CURRENT_PROFILE
  - EFFECT_06_END_CURRENT_PROFILE
  - EFFECT_06_INTERRUPT_CURRENT_PROFILE
  - EFFECT_07_END_CURRENT_PROFILE
  - EFFECT_07_INTERRUPT_CURRENT_PROFILE
  - EFFECT_08_END_CURRENT_PROFILE
  - EFFECT_08_INTERRUPT_CURRENT_PROFILE
  - EFFECT_09_END_CURRENT_PROFILE
  - EFFECT_09_INTERRUPT_CURRENT_PROFILE
  - EFFECT_10_END_CURRENT_PROFILE
  - EFFECT_10_INTERRUPT_CURRENT_PROFILE
supported_color_modes:
  - brightness
effect: null
color_mode: null
brightness: null
interface_id: RaspberryMatic-HmIP-RF
address: 0033A0C98FB85C:21
model: HmIP-DRG-DALI
entity_type: custom
value_state: restored
friendly_name: DALI_OG:B85C :21
supported_features: 36

> - 39

min_color_temp_kelvin: 2000
max_color_temp_kelvin: 6535
min_mireds: 153
max_mireds: 500
effect_list:
  - NO_EFFECT
  - EFFECT_01_END_CURRENT_PROFILE
  - EFFECT_01_INTERRUPT_CURRENT_PROFILE
  - EFFECT_02_END_CURRENT_PROFILE
  - EFFECT_02_INTERRUPT_CURRENT_PROFILE
  - EFFECT_03_END_CURRENT_PROFILE
  - EFFECT_03_INTERRUPT_CURRENT_PROFILE
  - EFFECT_04_END_CURRENT_PROFILE
  - EFFECT_04_INTERRUPT_CURRENT_PROFILE
  - EFFECT_05_END_CURRENT_PROFILE
  - EFFECT_05_INTERRUPT_CURRENT_PROFILE
  - EFFECT_06_END_CURRENT_PROFILE
  - EFFECT_06_INTERRUPT_CURRENT_PROFILE
  - EFFECT_07_END_CURRENT_PROFILE
  - EFFECT_07_INTERRUPT_CURRENT_PROFILE
  - EFFECT_08_END_CURRENT_PROFILE
  - EFFECT_08_INTERRUPT_CURRENT_PROFILE
  - EFFECT_09_END_CURRENT_PROFILE
  - EFFECT_09_INTERRUPT_CURRENT_PROFILE
  - EFFECT_10_END_CURRENT_PROFILE
  - EFFECT_10_INTERRUPT_CURRENT_PROFILE
supported_color_modes:
  - color_temp
effect: null
color_mode: null
brightness: null
color_temp_kelvin: null
color_temp: null
hs_color: null
rgb_color: null
xy_color: null
interface_id: RaspberryMatic-HmIP-RF
address: 0033A0C98FB85C:39
model: HmIP-DRG-DALI
entity_type: custom
value_state: valid
friendly_name: DALI_OG:B85C DALI_OG_Bad_OG:B85C:39
supported_features: 36

> - 40

effect_list:
  - NO_EFFECT
  - EFFECT_01_END_CURRENT_PROFILE
  - EFFECT_01_INTERRUPT_CURRENT_PROFILE
  - EFFECT_02_END_CURRENT_PROFILE
  - EFFECT_02_INTERRUPT_CURRENT_PROFILE
  - EFFECT_03_END_CURRENT_PROFILE
  - EFFECT_03_INTERRUPT_CURRENT_PROFILE
  - EFFECT_04_END_CURRENT_PROFILE
  - EFFECT_04_INTERRUPT_CURRENT_PROFILE
  - EFFECT_05_END_CURRENT_PROFILE
  - EFFECT_05_INTERRUPT_CURRENT_PROFILE
  - EFFECT_06_END_CURRENT_PROFILE
  - EFFECT_06_INTERRUPT_CURRENT_PROFILE
  - EFFECT_07_END_CURRENT_PROFILE
  - EFFECT_07_INTERRUPT_CURRENT_PROFILE
  - EFFECT_08_END_CURRENT_PROFILE
  - EFFECT_08_INTERRUPT_CURRENT_PROFILE
  - EFFECT_09_END_CURRENT_PROFILE
  - EFFECT_09_INTERRUPT_CURRENT_PROFILE
  - EFFECT_10_END_CURRENT_PROFILE
  - EFFECT_10_INTERRUPT_CURRENT_PROFILE
supported_color_modes:
  - brightness
effect: null
color_mode: null
brightness: null
interface_id: RaspberryMatic-HmIP-RF
address: 0033A0C98FB85C:40
model: HmIP-DRG-DALI
entity_type: custom
value_state: restored
friendly_name: DALI_OG:B85C DALI_OG_Kueche_Fenster ch40
supported_features: 36

**Comment by SukramJ** [comment]
Dann installiere doch mal die Beta [1.65.1b0](https://github.com/danielperna84/custom_homematic/releases/tag/1.65.1b0).
Gegebenenfalls musst Du in HACS noch die Unterstützung für Vorabversionen aktivieren.

**Comment by EAFSL** [comment]
Super, funktioniert jetzt. Herzlichen Dank für die kompetente Unterstützung und Problemlösung ;).  
Was hat das Problem verursacht?
Jetzt kommt es nur manchmal vor das beim Ausschalten der Schalter auf OFF geht nach 2 sec kurz wieder auf ON und dann auf OFF.

**Comment by SukramJ** [comment]
> Herzlichen Dank für die kompetente Unterstützung und Problemlösung ;).

Auch dir ein Dankeschön für die gute Mitarbeit.

>Was hat das Problem verursacht?

Das DALI Gateway verhält sich komplett anders als andere Geräte.
Normalerweise (z.Bsp. HmIP-RGBW) werden die Datenpunkte im Event vollständig mitgeschickt.
Hier werden aber einzelne Datenpunkte (HUE/SATURATION) nur mitgeschickt, wenn die verbundenen Lampen das auch unterstützen. 

> Jetzt kommt es nur manchmal vor das beim Ausschalten der Schalter auf OFF geht nach 2 sec kurz wieder auf ON und dann auf OFF.

Hört sich an, als ob das Antwort-Event manchmal verzögert eintrifft.
