### ISSUE TITLE
Thermostat BWTH shows wrong status

### ISSUE THREAD

**Issue by familiesimon** [SukramJ/hahomematic#1675]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hi,

I have a issue with my Thermostat BWTH from HomematicIP running through a CCU3 and the HACS Integration.

It shows the wrong status. Everything else works as it should.

E.g. in the room I’ve 19 degrees, I set the thermostat to 22 degrees through Home Assistant. The Valve opens and shows in the CCU3 as open. But the Home Assistant Card shows inactive. When I turn the thermostat to 16 degree, the valve closes, shows as closed in the CCU3 but HA says it’s heating

### What version of HomematicIP (local) has the issue?

1.65.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which config details do you use

- [X] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Um zu verstehen wovon du redest wären Screenshots hilfreich.

**Comment by familiesimon** [comment]
Sorry, 

also hier wird angezeigt, das Thermostat würde heizen.

![Screenshot 2024-08-28 140122](https://github.com/user-attachments/assets/2a239d2b-aad3-4d6b-9ce9-62a8e51a38ad)

allerdings hat es 21,7° und soll nur 19° haben. Korrekterweise zeigt die CCU3 auch an das das Heizventil geschlossen ist und nicht geheizt wird.

Hier wiederum genau das Gegenteil.

![Screenshot 2024-08-28 140227](https://github.com/user-attachments/assets/a9e7b2ea-af79-4759-8ec8-c289efeef0f3)

Es hat 21,7° und soll 25° haben. Die CCU3 zeigt korrekterweise ein offenes Ventil an und es wird geheizt. Home Assist jedoch nicht.

**Comment by SukramJ** [comment]
Relevant ist hier nur was der Schaltausgang auf Kanal 9 anzeigt.
In der HA wird dieser Wert als Schaltausgang(muss ggf. aktiviert werden) angezeigt.

**Comment by Baxxy13** [comment]
"Helfen" kann ich dieses mal nicht (kein BWTH) aber interessant finde ich's trotzdem.

> Relevant ist hier nur was der Schaltausgang auf Kanal 9 anzeigt.

Bedeutet das, das die Darstellung in HA nur korrekt ist wenn auch der Schaltausgang des BWTH genutzt wird?
Was ist wenn jemand die interne DV (Thermostat <--> Schalktaktor) löscht weil er z.B. nur eTRV's oder nen FALxxx steuert und das "klicken" nicht ertragen kann?

**Comment by SukramJ** [comment]
> Bedeutet das, das die Darstellung in HA nur korrekt ist 

Korrekt ist gut gesagt. Es geht nur um die Zusatzinfo ob geheizt wird. Ist also im Zweifel verzichtbar.

> Was ist wenn jemand die interne DV (Thermostat <--> Schalktaktor) löscht weil er z.B. nur eTRV's oder nen FALxxx steuert und das "klicken" nicht ertragen kann?

Die klicken? :open_mouth:
Was denkst Du wie viele Leute sich mit sowas beschäftigen?  Ich noch nicht. :wink:

**Comment by Baxxy13** [comment]
Sag bloß du hast noch nie ein Ohr an ein BWTH gehalten? 😉 
"Früher" gab's da zig Threads im Forum als die Teile noch auf PWM fixiert waren, inzwischen können die ja auch 2-Punkt und es ist ruhiger geworden. (im wahrsten Sinne des Wortes).

Ok, also die Zusatzinfo (in diesem Fall) ist abhängig vom Schaltzustand den es so nur bei BWTH's gibt. 
Darum kann ich das mit anderen IP-Termostaten nicht nachstellen. 
Alles klar. 😃

**Comment by SukramJ** [comment]
> Darum kann ich das mit anderen IP-Termostaten nicht nachstellen.

Ich kann es an meinen BWTH auch nicht nachstellen.

**Comment by Andyhateinhandy** [comment]
![grafik](https://github.com/user-attachments/assets/1887d2f8-0dd2-47a7-9b92-1f7715367bb6)
Seit dem letzten Update werden die Entitäten der Falmot-Ventile nicht mehr bereitgestellt

**Comment by SukramJ** [comment]
@Andyhateinhandy  bitte nicht irgendwo reinspammen!

https://github.com/danielperna84/hahomematic/discussions/1611

**Comment by SukramJ** [comment]
Ich denke das Issue kann geschlossen werden. Ansonsten bitte ich um konkrete Rückmeldung.
