### ISSUE TITLE
Valve values and handling on FALMOT-C12

### ISSUE THREAD

**Issue by x4N70pHyLL** [SukramJ/hahomematic#1676]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Valve values (and handling) from FALMOT-C12 make no sense to me since last update.

They are not sensors anymore, but numbers, so I can change them. Does not make too much sense to me as this should be automatically done by FALMOT.
My problem is that once this is done manually I don't see a consistent way back to "auto operation", I did

- restart Raspberrymatic
- change the valve value back and forth
- deactivate / activate the thermostat (Auto -> Off -> Auto)
- Change FALMOT from cooling to heating and back

Most valves seem to be back at normal operation, but at least one still remains at the exact same percentage sind the update, both HA and CCU show me the same value, when I change it, it is change in CCU as well

### What version of HomematicIP (local) has the issue?

1.65.0

### What was the last working version of HomematicIP (local)?

1.64.0

### What type of installation are you running?

Home Assistant Core

### What type of installation are you running for your homematic backend?

RaspberryMatic HA-Addon

### Which version of your homematic backend are you running?

3.77.7.20240826

### What hardware are you running for your system?

Synology NAS (HA+HmIP-Plugin) & Pi4 (Raspberrymatic)

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
> Valve values (and handling) from FALMOT-C12 make no sense to me since last update.

Yes, this is related to your Falmot firmware update and not to this integration.
eq-3 made the valve state writable and that is what you see in the Integration (sensor --> number)
From an integration perspective, I don't really care whether it makes sense or not.

>  both HA and CCU show me the same value

Then everything is fine from an integration perspective and this ticket can be closed.

**Comment by SukramJ** [comment]
[See](https://github.com/danielperna84/hahomematic/discussions/1611) also
