### ISSUE TITLE
DV Umschreiben per PutParamset seit Update auf 1.65.0 nicht mehr möglich ("Parameter xxx could not be found")

### ISSUE THREAD

**Issue by Nappyy** [SukramJ/hahomematic#1681]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Ich möchte per PutParamset Aufruf die interne Direktverknüpfung eines HM-LC-Dim1T-FM ändern. 
Konkret soll der Parameter "SHORT_ON_LEVEL" im Kanal 1 angepasst werden.
Bis einschließlich Version 1.64.0 funktionierte das über den folgenden Aufruf ohne Probleme:

> data:
>   paramset_key: KEQ0002290:1
>   device_id: 12a1e4f784adff5473a6a86b4627e31f
>   channel: 1
>   paramset:
>     SHORT_ON_LEVEL: 1
> action: homematicip_local.put_paramset

Seit dem Update auf 1.65 wird der Parameter nicht wie bisher geschrieben, sondern es erscheint im Log eine Warnung:
`2024-08-30 14:00:50.957 WARNING (MainThread) [hahomematic.client] PUT_PARAMSET failed: HaHomematicException [Parameter SHORT_ON_LEVEL could not be found: RaspberryMatic-BidCos-RF/KEQ0002290:1/KEQ0002290:1] KEQ0002290:1, KEQ0002290:1, {'SHORT_ON_LEVEL': 1}`

Im UI wird kein Fehler ausgegeben.

Oder Testweise nach Update auf 1.65.1, allerdings mit dem selben Verhalten und Fehler im Log
> action: homematicip_local.put_paramset
> data:
>   paramset_key: MASTER
>   channel: 1
>   paramset:
>     SHORT_ON_LEVEL: 0.9
>   device_id: 12a1e4f784adff5473a6a86b4627e31f

### What version of HomematicIP (local) has the issue?

1.65.x

### What was the last working version of HomematicIP (local)?

1.64

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic HA-Addon

### Which version of your homematic backend are you running?

3.77.7.20240826

### What hardware are you running for your system?

NUC

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information (no logs here)

[config_entry-homematicip_local-c59476182b90e0815002df7c88aafcb8.json](https://github.com/user-attachments/files/16816499/config_entry-homematicip_local-c59476182b90e0815002df7c88aafcb8.json)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
2024-08-30 14:00:50.957 WARNING (MainThread) [hahomematic.client] PUT_PARAMSET failed: HaHomematicException [Parameter SHORT_ON_LEVEL could not be found: RaspberryMatic-BidCos-RF/KEQ0002290:1/KEQ0002290:1] KEQ0002290:1, KEQ0002290:1, {'SHORT_ON_LEVEL': 1}
```

### Additional information

Ich habe im Homematic-Forum dazu ein Post verfasst und wurde dabei hier hin verwiesen.
https://homematic-forum.de/forum/viewtopic.php?p=811952#p811952

**Comment by SukramJ** [comment]
Danke für die Meldung.
Mit der Version 1.65.0 wurde eine Validierung eingeführt, die überprüft, ob es diesen Parameter überhaupt gibt und ob dieser beschreibbar ist.

Wenn ich das richtig [sehe](pydevccu/paramset_descriptions/HM-LC-Dim1T-FM.json) dann hat ein `HM-LC-Dim1T-FM` auf `Kanal 1` im Paramset `MASTER` keinen Parameter `SHORT_ON_LEVEL`. Die Validierung hat also richtig funktioniert.

Den Parameter finde ich aber im Paramset `LINK`. Für die Validierung werden aber derzeit aber derzeit nur die Paramsets `MASTER` und `VALUES` herangezogen, so das es in der 1.65.0 auch unter verwendeung des `LINK` Paramsets nicht funktionieren wird.

Häng bitte die Geräte Beschreibungen für dein Gerät hier als Dateien an, um meine Daten zu überprüfen.
Dazu musst Du den Service [export_device_definition](https://github.com/danielperna84/custom_homematic?tab=readme-ov-file#homematicip_localexport_device_definition) aufrufen.

@Baxxy13 Hast du eine Idee, warum das alte Kommando funktioniert hat, obwohl das falsche Paramset verwendet wurde?

**Comment by Nappyy** [comment]
Super, danke für die schnelle Reaktion!

hier die gewünschten Files:
device_description: [HM-LC-Dim1T-FM.json](https://github.com/user-attachments/files/16817543/HM-LC-Dim1T-FM.json)
paramset_description: [HM-LC-Dim1T-FM (1).json](https://github.com/user-attachments/files/16817544/HM-LC-Dim1T-FM.1.json)

**Comment by Baxxy13** [comment]
Ich kann nur spekulieren. 
Vermutlich "weiß" die Schnittstelle das das LINK-Paramset genutzt werden muss wenn als Parameter Sender und Empfangeradresse enthalten sind. 
Müsste man mal gucken ob die Doku was hergibt, bin aber am WE außer Haus.

Am Gerät von @Nappyy liegt's aber eher nicht. Hatte das vorhin noch schnell an meiner PSM getestet, erfolglos.

**Comment by SukramJ** [comment]
> paramset_key: KEQ0002290:1
> Vermutlich "weiß" die Schnittstelle das das LINK-Paramset genutzt werden muss wenn als Parameter Sender und Empfangeradresse enthalten sind.

Gut das Du das noch mal betonst. Die Adresse als paramset_key hab ich ganz übersehen.

**Comment by SukramJ** [comment]
> paramset_key: KEQ0002290:1

Ist das die Adresse des HM-LC-Dim1T-FM?

**Comment by Nappyy** [comment]
Korrekt

**Comment by Baxxy13** [comment]
paramset_key: ist die Senderadresse, das kann auch ein externer Taster oder eine virt. Taste sein. 
Das "Ziel" ist der Aktorkanal. Das geben wir ja als Gerät samt Kanal an.

**Comment by SukramJ** [comment]
Moin,
mal bitte schauen, ob ich das richtig verstanden habe, und mit der version [1.66.0b0](https://github.com/danielperna84/custom_homematic/releases/tag/1.66.0b0) testen.

**Comment by Nappyy** [comment]
Moin, zuerst mal vielen Dank für den schnellen Support. Top!
Ich würde sagen, es funktioniert mit 1.66.0b0 "so halb".
Per alter Config aus meiner Automation kann jetzt ohne Fehler erfolgreich der Parameter wieder geschrieben werden:
> data:
>   paramset_key: KEQ0002290:1
>   device_id: 12a1e4f784adff5473a6a86b4627e31f
>   channel: 1
>   paramset:
>     SHORT_ON_LEVEL: "{{ states('sensor.nachtlicht_helligkeit')|int / 100 }}"
> alias: Nachtlicht in Toilette festlegen
> action: homematicip_local.put_paramset

Wenn ich aber den eigentlichen Pflichtparameter "Parametersatzschlüssel" mit "MASTER" oder "VALUES" befalle, schlägt es wieder fehl.
`2024-08-31 14:50:02.062 WARNING (MainThread) [hahomematic.client] PUT_PARAMSET failed: HaHomematicException [Parameter SHORT_ON_LEVEL could not be found: RaspberryMatic-BidCos-RF/KEQ0002290:1/MASTER] KEQ0002290:1, MASTER, {'SHORT_ON_LEVEL': 1.0}`
`2024-08-31 14:50:06.063 WARNING (MainThread) [hahomematic.client] PUT_PARAMSET failed: HaHomematicException [Parameter SHORT_ON_LEVEL could not be found: RaspberryMatic-BidCos-RF/KEQ0002290:1/VALUES] KEQ0002290:1, VALUES, {'SHORT_ON_LEVEL': 1.0}`

Wenn es noch ein Radio Button "Keiner/leer/link/o.Ä." gäbe, wäre es zumindest funktional i.O. Ob das dann bereits sauber wäre kann ich nicht beurteilen :)

Noch ein kleiner typo: beim Label "Parametersatz ist ein Anführungszeichen zu viel im visuellen editor.
<img width="838" alt="image" src="https://github.com/user-attachments/assets/f085d67d-bc11-4673-b38d-64bc78458311">

**Comment by SukramJ** [comment]
Funktioniert nur im yaml mode.
In der Ui hab ich bewusst drauf verzichtet.

**Comment by Nappyy** [comment]
Senden kann man auch im Ui Modus, nur "abwählen" der Radio Buttons eben nicht ohne weiteres ;)

**Comment by SukramJ** [comment]
Es geht NUR im yaml Modus, da statt paramset Master oder Values immer die Adresse rein muss.

**Comment by Nappyy** [comment]
Ah ich verstehe.. Bei mir funktioniert es nur, weil es in der Automation sich noch als paramset_key die Adresse gemerkt hatte.
Tatsächlich kann ich die Ui wie oben im Screenshot sichtbar ausführen, im YAML ist aber wie gesagt historisch noch die Adresse hinterlegt, daher klappt es noch. 

OK verstanden.
Bleibt das ein solcher Sonderfall, dass es "nur" per YAML konfigurierbar bleibt oder planst du eine Ui Umsetzung in einer kommenden Version?
Für mich passt das so - nur aus Interesse...

**Comment by Baxxy13** [comment]
Ließe sich vielleicht in die UI, neben/unter den beiden wählbaren MASTER / VALUES noch ein drittes wählbares Feld erzeugen was dann ein Eingabefeld aktiviert. Also so wie zuvor als man das Paramset noch selbst eintragen musste?

**Comment by SukramJ** [comment]
Für so einen absoluten Edge-Case würde ich, selbst wenn es UI technisch möglich wäre, keine Anpassung an der UI vornehmen.
Im YAML-Modus kann man die Werte entsprechend konfigurieren.
Wer möchte darf natürlich gerne die Doku entsprechend ergänzen!

**Comment by Baxxy13** [comment]
Hmm, jetzt geht das mit HmIP-DV's augenscheinlich nicht mehr.

Wir nehmen eine HmIP-PS/PSM und stellen in der Standard DV (Taster:1 <-> Aktor:3) eine Einschaltdauer von 30s ein (für den kurzen Tastendruck). 
Das nehmen wir als Ausgangslage und wollen nun die 30s auf 40s ändern.
Also: Parameter: `SHORT_ON_TIME_FACTOR` von `3` auf `4` 

```yaml
data:
  paramset_key: 0001D3C99CA0D2:1
  paramset:
    SHORT_ON_TIME_FACTOR: 4
  device_address: 0001D3C99CA0D2
  channel: 3
action: homematicip_local.put_paramset
```
Mit 1.64.0 kein Problem.

Mit 1.65.0 ging das ja generell nicht, mit den Betas 1.66.0b0 / 1.66.0b1 klappt das aber auch nicht.

Fehler: `Die Aktion homematicip_local.put_paramset konnte nicht ausgeführt werden. Unknown error`

Und in vollständig:

```
Logger: homeassistant.helpers.script.websocket_api_script
Quelle: helpers/script.py:525
Erstmals aufgetreten: 23:13:40 (1 Vorkommnisse)
Zuletzt protokolliert: 23:13:40

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: '0001D3C99CA0D2:1' is not a valid ParamsetKey
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 525, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2763, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2806, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1175, in check_permissions
    return await service_handler(call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homematicip_local/services.py", line 213, in async_call_hmip_local_service
    await _async_service_put_paramset(hass=hass, service=service)
  File "/config/custom_components/homematicip_local/services.py", line 513, in _async_service_put_paramset
    await hm_device.client.put_paramset(
  File "/usr/local/lib/python3.12/site-packages/hahomematic/performance.py", line 26, in async_wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hahomematic/client/__init__.py", line 589, in put_paramset
    else ParamsetKey(paramset_key)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1171, in __new__
    raise ve_exc
ValueError: '0001D3C99CA0D2:1' is not a valid ParamsetKey
```

**Comment by SukramJ** [comment]
Danke. Ich hab die HmIP Adressvalidierung vergessen

**Comment by SukramJ** [comment]
Mit der 1.66.0b2 sollte es jetzt auch mit HmIP Geräten funktionieren.

**Comment by Baxxy13** [comment]
Sehr schön, funktioniert wieder.
Danke!

**Comment by SukramJ** [comment]
Danke fürs Testen.
Mit UI könnte man es lösen, wenn man einen zweiten Service `put_link_paramset` erstellt. Das würde auch die Validierung übersichtlicher machen. Was denkst Du?

**Comment by Baxxy13** [comment]
Die Idee finde ich gut. 
Idealerweise dazu dann auch den Counterpart (`get_link_paramset`), denn früher oder später kommt bestimmt einer auf die Idee die Linkparameter auch lesen zu wollen. (geht aktuell nicht)

Hab jetzt nochmal die Doku gewälzt...


> Vermutlich "weiß" die Schnittstelle das das LINK-Paramset genutzt werden muss wenn als Parameter Sender und Empfangeradresse enthalten sind.

**putParamset:**
> Mit dieser Methode wird ein komplettes Parameter-Set für ein logisches Gerät geschrieben. Der Parameter address ist die Addresses eines logischen Gerätes. Der Parameter paramset_key ist „MASTER“, „VALUES“ oder die Adresse eines Kommunikationspartners für das entsprechende Link-Parameter-Set (siehe getLinkPeers).**

**Comment by Baxxy13** [comment]
Ich sehe du warst fleißig... hab mir die 1.66.0b3 angesehen.

Anmerkungen:
`homematicip_local.put_link_paramset`
- ich würde den Service "Homematic(IP) Local: Parametersatz einer Direktverknüpfung schreiben" nennen.
Direktverknüpfung ist gebräuchlicher als Verknüpfung (bezogen auf Homematic).
- du hast aktuell die Eingabefelder für Sender und Empfänger vertauscht
  (im Screenshot ist :1 der Sender und :3 der Empänger)
![HA_putlinkparamset](https://github.com/user-attachments/assets/4ca34946-d9de-40f9-8c28-5c0c815f4360)

Vorschlag:
zu 1: Sender Kanaladresse / Kanaladresse des verknüpften Senders (also das was bisher an Pos 2 steht)
zu 2: Empfänger Kanaladresse / Kanaladresse des verknüpften Empfängers

Im YAML wär's konsequenter wenn `channel_address` zu `receiver_channel_address` geändert würde.

```
action: homematicip_local.put_link_paramset
data:
  sender_channel_address: 0001D3C99CA0D2:3
  channel_address: 0001D3C99CA0D2:1
  paramset:
    SHORT_ON_TIME_FACTOR: 3
``` 

So funktioniert es, weil ich Sender und Empfänger getauscht habe.

**Comment by SukramJ** [comment]
Hört sich gut an. Schau dir mal bitte die 1.66.0b4 an.

**Comment by Baxxy13** [comment]
Sehr schön. 
Sieht jetzt nach einem Kurztest alles passend aus. 
Und du hast alle meine Anmerkungen/Vorschläge umgesetzt, danke dafür.
(nur das rot markierte, schwer zu sehende, Anführungszeichen bei `"Parametersatz` ist noch drin.) 😉 

Ich habe noch ein paar Ideen/Gedanken zwecks Beschriftungen/Texte damit diese verschiedenen "Aktionen" etwas intuitiver zu verstehen sind. 
Da werde ich die Tage mal im Diskussionsbereich was zu schreiben und dann denke ich das ich dir da nen PR zu machen kann.

So, nun sollte das Thema aber erstmal wirklich abgehakt sein. 😄

**Comment by Baxxy13** [comment]
Hmm, jetzt habe ich doch noch was...

Die Validierung der Adressen scheitert bei den virt. CCU-Tasten. 
DV's mit virt. CCU-Tasten kann man aktuell also weder lesen noch schreiben.

Die Adressen (Seriennummern) lauten z.B.
HM: `BidCoS-RF:13`
HmIP: `HmIP-RCV-1:13`
 
Test:
```
action: homematicip_local.get_link_peers
data:
  channel: 13
  device_address: BidCoS-RF
```
Fehler:
Die Aktion homematicip_local.get_link_peers konnte nicht ausgeführt werden. device_address is invalid for dictionary value @ data['device_address']. Got None

Wenn ich das statt über die Geräteadresse + Kanal über das "HA-Gerät" + Kanal mache gehts:
```
action: homematicip_local.get_link_peers
data:
  channel: 13
  device_id: 05fe1c62957e3798ea76e4e5b70a002a
```
Antwort:
```
BidCoS-RF:13:
  - QEQ0011501:1
```

**Comment by Baxxy13** [comment]
Kurzes Feedback zur 1.66.0b5:
Sieht gut aus, DV's zu virt. HM/IP-Tasten können nun auch gelesen, geschrieben und die Link-Partner abgefragt werden.

**Comment by SukramJ** [comment]
> Da werde ich die Tage mal im Diskussionsbereich was zu schreiben und dann denke ich das ich dir da nen PR zu machen kann.

Kannst Du ungefähr absehen wann du dazu kommst? Dann warte ich mit dem Release.

**Comment by Baxxy13** [comment]
Ich werde mich die Woche mal dransetzen. 
Du kannst ruhig einen Release rausbringen, brauchst nicht auf mich warten.

**Comment by SukramJ** [comment]
Ok, danke für die Info.
