### ISSUE TITLE
Since Upgrade to 1.65.0 Problems with HmIP-FALMOT-C12

### ISSUE THREAD

**Issue by holsteiner-kiel** [SukramJ/hahomematic#1682]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Entities for "Ventil Öffnungsgrad" are Not available any more

### What version of HomematicIP (local) has the issue?

1.65.0

### What type of installation are you running?

Home Assistant Container

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.77.7.20240826

### Which config details do you use

- [ ] TLS
- [X] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Bitte die Suchfunktion verwenden

Statt der Sensoren werden jetzt Number Entities generiert.

 [Siehe](https://github.com/danielperna84/hahomematic/discussions/1611)
