### ISSUE TITLE
almost all bidcos devices show update available

### ISSUE THREAD

**Issue by sebastianlorenzen** [SukramJ/hahomematic#1694]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

all battery powered classic homematic devices show update available under settings in ha 
1.66.0b3
might be related to the not updatable device change? Mostly these are optical door / window contacts

### What version of HomematicIP (local) has the issue?

1.66.0b3

### What was the last working version of HomematicIP (local)?

1.66.0b2

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.77.7.20240826

### What hardware are you running for your system?

RPI3

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information (no logs here)

[config_entry-homematicip_local-9f3e2e1bd8da4078035573cee483ccfa.json](https://github.com/user-attachments/files/16841338/config_entry-homematicip_local-9f3e2e1bd8da4078035573cee483ccfa.json)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
the only log entry I found:

This error originated from a custom integration.

Logger: hahomematic.caches.visibility
Source: custom_components/homematicip_local/control_unit.py:126
integration: Homematic(IP) Local (documentation, issues)
First occurred: 11:24:48 PM (2 occurrences)
Last logged: 11:24:48 PM

GET_UN_IGNORE_LINE_DETAILS failed: Could not add line 'VALVE_MAXIMUM_POSITION@HM-CC-RT-DN:MASTER' to un ignore cache. No ':' before '@'
ADD_LINE_TO_CACHE failed: No supported format detected for un ignore line 'VALVE_MAXIMUM_POSITION@HM-CC-RT-DN:MASTER'.
```

**Comment by SukramJ** [comment]
Thanks for testing a Beta version, and reporting an issue.

Your log entry is related to a wrong entry in the unignore file. Use the UI config  for unignore instead.

**Comment by sebastianlorenzen** [comment]
Oops, yes. Tests from the early days. Deleted the config file and log entries are gone.
Still having the update messages. Should I just skip them?

**Comment by SukramJ** [comment]
No wait, next version will fix it.

**Comment by SukramJ** [comment]
1.66.0b4 should fix it

**Comment by sebastianlorenzen** [comment]
Yes, Update and restart solved it. Thanks for the quick fix.
