### ISSUE TITLE
HmIP-BBL not rotating Shutter down

### ISSUE THREAD

**Issue by morpheus12** [SukramJ/hahomematic#1701]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hi All,
i got an issue with all of my HmIP-BBL Shutters through Home Assistant.
I identified the problem in Version 1.6.0 after Upgrading to 1.6.5 same behavior.
Opening and Closing the shutter works fine and well. But rotating the shutters from left to right (in HA a % value 0% = left, 100% = right).

One Shutter is not able to operate higher than 50% the rotation, another one (testing the behavior) is doing nothing means no rotation at all.

Thru CCU WebUI by operating with Channel 5 of the shutters all is working fine. Channel 4 and 6 is working sometimes, sometimes not. 

What is strange for me (but i don't know technical details of API so perhaps this is a normal behavior): I can't see in the CCU WebUI the change update (Time and Date of last action). 

Rebooting the HmIP-BBL by disconnecting power supply didn't changed anything.
Upgrading to the newest Version of Integration (1.6.5) didn't changed the behavior.
Currently running on 2024.9.0 of HA. I can't swear that this behavior was there bevor in 2024.8.0 but i'm quite sure because the one shutter where i've identified didn't changed the shutter rotation through HA sun programms since several weeks.

### What version of HomematicIP (local) has the issue?

1.6.5

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.71.12

### What hardware are you running for your system?

Intel Nuc i5 5th gen

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information (no logs here)

[config_entry-homematicip_local-90829f77ce979344a4d954a6e1eb3b37(1).json](https://github.com/user-attachments/files/16919856/config_entry-homematicip_local-90829f77ce979344a4d954a6e1eb3b37.1.json)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
No entries for HA Homematic Topics related to the shutter in Basic log. I've one independent issue to fetch data of a energy meter but this is not a real issue for me.

I've activated the debug mode and can provide a 2,4MB Log File of 20mins active.
```

**Comment by SukramJ** [comment]
> Thru CCU WebUI by operating with Channel 5 of the shutters all is working fine. Channel 4 and 6 is working sometimes, sometimes not.

Please ensure it is completely working in the CCU WebUI. Otherwise it makes no sense to open an issue here.
This issue can be closed.

**Comment by morpheus12** [comment]
Hi all,

i've done several things today morning.
- eliminated dependencies to homebridge
- updated CCU to newest Firmware 3.77.1

and got a deeper look into the function. 
Channel 4 is the standard used virtual channel for the control of the shutter
Channel 5/6 shall be used for Programms internal of CCU (as i figured out).


Currently 1 one 4 shutters makes trouble. This single on does exact the same behavior in CCU WebUI as in HA:
Controlling high is working fine, the rotation is not working higher than 50%. The real strange thing: Channel 3 (Status) is showing me the correct values! Which means i tried 70% but the shutter takes 50% and answering back 50%!
Therefore i startet a new calibration through CCU to learn again the adoption. No change!

But than i figured out something weird: Syncing manually the shutter positions on all Channels (4,5,6) got the solution. Lets see how long...

Therefore no issue regarding the plugin. Thx for watching.
