### ISSUE TITLE
lost possibility to se value in ELV-SH-WUA 00329D40001478 Level ch2

### ISSUE THREAD

**Issue by 1iFlow** [SukramJ/hahomematic#1720]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hi,
I am using the possibility to give  "ELV-SH-WUA 00329D40001478 Level ch2" to give a decimal value from 0 --- 100 %
With the latest update all my autmations and dashboards are not working any longer.
How can I proceed?
How can I downgrade to old version which was supporting thisß

### What version of HomematicIP (local) has the issue?

1.64

### What was the last working version of HomematicIP (local)?

1.63

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.77.6.20240720

### What hardware are you running for your system?

Pi4

### Which config details do you use

- [X] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information (no logs here)

.no information

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
.no information
```

### Additional information

.no information

**Comment by SukramJ** [comment]
> How can I downgrade to old version which was supporting thisß

Use HACS!

Next release will remove the customization from WUA.

**Comment by 1iFlow** [comment]
can you please be a bit more precise?
I am not an expert.
When will be next release?

**Comment by SukramJ** [comment]
> can you please be a bit more precise?

Go to HACS -> select the integration -> redownload (older version)

> When will be next release?

Don't know.

**Comment by 1iFlow** [comment]
older version can be selected, but after leaving the drop down menu 1.65.0 is set again

**Comment by SukramJ** [comment]
This is not a HACS support forum.

- Check that you use the latest version of hacs.
- select an older version
- press download
- restart HA

**Comment by 1iFlow** [comment]
sorry for bothering you.
But I am happy to get any help.
Thank you very much.
Hope update which is working againg for me is coming soon, :)
