### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by cremmering** [SukramJ/hahomematic#1725]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

When trying to install via adding a new repository I do get the following error message:

https://github.com/danielperna84/custom_homematic is not a valid add-on repository

This is what I do find in the log:
Logger: homeassistant.components.hassio
Quelle: components/hassio/websocket_api.py:135
Integration: Home Assistant Supervisor (Dokumentation, Probleme)
Erstmals aufgetreten: 10:06:18 (5 Vorkommnisse)
Zuletzt protokolliert: 10:10:19

Failed to to call /store/repositories - https://github.com/danielperna84/custom_homematic is not a valid add-on repository

### What version of HomematicIP (local) has the issue?

n/a

### What was the last working version of HomematicIP (local)?

n/a

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.77.7

### What hardware are you running for your system?

VirtualBox on Windows 11

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information (no logs here)

Logger: homeassistant.components.hassio
Quelle: components/hassio/websocket_api.py:135
Integration: Home Assistant Supervisor (Dokumentation, Probleme)
Erstmals aufgetreten: 10:06:18 (5 Vorkommnisse)
Zuletzt protokolliert: 10:10:19

Failed to to call /store/repositories - https://github.com/danielperna84/custom_homematic is not a valid add-on repository

**Comment by SukramJ** [comment]
Read the Installation Instruktion carefully. Its not an addon. Use HACS.
