### ISSUE TITLE
Unable to create device: Homegear-BidCos-RF

### ISSUE THREAD

**Issue by myrdrks** [SukramJ/hahomematic#1727]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

After a reboot of HA no device is responding. Homegear is working properly.

### What version of HomematicIP (local) has the issue?

1.66.0

### What was the last working version of HomematicIP (local)?

1.66.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

Homegear

### Which version of your homematic backend are you running?

0.7.51-3497

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [X] BidCos-Wired (HM-Wired)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: hahomematic.central
Quelle: custom_components/homematicip_local/control_unit.py:720
Integration: Homematic(IP) Local (Dokumentation, Probleme)
Erstmals aufgetreten: 21:21:52 (52 Vorkommnisse)
Zuletzt protokolliert: 21:21:52

CREATE_DEVICES failed: KeyError [UPDATABLE] Unable to create device: Homegear-BidCos-RF, PEQ1640614
CREATE_DEVICES failed: KeyError [UPDATABLE] Unable to create device: Homegear-BidCos-RF, MEQ0400253
CREATE_DEVICES failed: KeyError [UPDATABLE] Unable to create device: Homegear-BidCos-RF, PEQ0390644
CREATE_DEVICES failed: KeyError [UPDATABLE] Unable to create device: Homegear-BidCos-RF, OEQ0763173
CREATE_DEVICES failed: KeyError [UPDATABLE] Unable to create device: Homegear-BidCos-RF, NEQ1008822
```

**Comment by SukramJ** [comment]
Welche Geräte sind betroffen? Alle?

**Comment by myrdrks** [comment]
Ja, alle. Bidcos-RF und Bidcos-Wired.

**Comment by SukramJ** [comment]
Leider wird so was immer wieder passieren, weil Homegear vieles wie eine CCU, aber so einiges auch anders macht.
Der Wert UPDATABLE ist auch so ein Fall der in der CCU gesetzt, aber in Homegear nicht vorhanden ist.

Da ich mit Homegear nicht teste, und auch kein Homegear-Benutzer eine der Beta installiert, bleibt das also eine Wundertüte.

**Comment by Zwer2k** [comment]
Bei mir ist MAX! betroffen

**Comment by SukramJ** [comment]
Ich wusste nicht mal das MAX! geht.

**Comment by Zwer2k** [comment]
> Ich wusste nicht mal das MAX! geht.
 :-) Geht, nutze ich schon länger. Zuvor mit ioBroker jetzt mit HA

**Comment by SukramJ** [comment]
Über welche Zentrale läuft die Verbindung?

**Comment by Zwer2k** [comment]
Mit Homegear mit der MAX! Familie/Plugin oder was meinst du mit Zentrale?

**Comment by SukramJ** [comment]
Ja, aber das ist dann auch _nur_ Homegear und nicht der alte MaxCube.
Hatte mich schon gewundert.

**Comment by Zwer2k** [comment]
Ja genau, die Geräte kommunizieren per Busware-CUL-Stick mit Homegear

**Comment by SukramJ** [comment]
Bitte mal mit der Version 1.67.0b0 testen. Gegebenenfalls muss "Vorabversion/Pre-release" für die Integration in HACS aktiviert werden.

**Comment by Zwer2k** [comment]
Eben getestet. Funktioniert leider nicht.

**Comment by SukramJ** [comment]
@Zwer2k Damit kann ich ja richtig viel anfangen!

Was steht im Log.

**Comment by Zwer2k** [comment]
Das selbe wie zuvor. Fast 😅
```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: hahomematic.central
Quelle: custom_components/homematicip_local/control_unit.py:721
Integration: Homematic(IP) Local (Dokumentation, Probleme)
Erstmals aufgetreten: 10:47:59 (25 Vorkommnisse)
Zuletzt protokolliert: 10:47:59

CREATE_DEVICES failed: HaHomematicException [CREATE_ENTITY_AND_APPEND_TO_CHANNEL: Unable to create entity:DEFAULT] Unable to create entities: Homegear-BidCos-RF, JEQ0613373
CREATE_DEVICES failed: HaHomematicException [CREATE_ENTITY_AND_APPEND_TO_CHANNEL: Unable to create entity:DEFAULT] Unable to create entities: Homegear-BidCos-RF, KEQ0841415
CREATE_DEVICES failed: HaHomematicException [CREATE_ENTITY_AND_APPEND_TO_CHANNEL: Unable to create entity:DEFAULT] Unable to create entities: Homegear-BidCos-RF, KEQ0003777
CREATE_DEVICES failed: HaHomematicException [CREATE_ENTITY_AND_APPEND_TO_CHANNEL: Unable to create entity:DEFAULT] Unable to create entities: Homegear-BidCos-RF, KEQ0185867
CREATE_DEVICES failed: HaHomematicException [CREATE_ENTITY_AND_APPEND_TO_CHANNEL: Unable to create entity:DEFAULT] Unable to create entities: Homegear-BidCos-RF, KEQ0003318
```

**Comment by SukramJ** [comment]
Bitte mit der Version 1.67.0b1 testen.

**Comment by Zwer2k** [comment]
Bei mir funktioniert es wieder. 
Vielen Dank 😊
