### ISSUE TITLE
Missing Data Parameter "SECTION" for "HmIP-MOD-HO"

### ISSUE THREAD

**Issue by 1onar** [SukramJ/hahomematic#1728]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I am missing the "SECTION" parameter for the device "HmIP-MOD-HO". This parameter is essential to track whether the garage door is in the process of closing or opening. The "DOOR_STATE" parameter only delivers the following states:

- CLOSED
- OPEN
- VENTILATION_POSITION
- POSITION_UNKNOWN

However, when the garage door is opening or closing, the state only shows as "unknown." This missing information is critical, especially when integrating the garage door with HomeKit.

The `66.3.2.1.5. PARAMETER SECTION` would provide the following states:

- `0` = Door closed
- `2` = Door opening
- `3` = Door opened
- `5` = Door closing

This additional state information is important to properly reflect the status of the garage door in Home Assistant and HomeKit integrations.

### What version of HomematicIP (local) has the issue?

1.66.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU2

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Section wird bereits für den Cover State (opening und closing) verwendet.
Ändert sich der Wert von  Section in der CCU beim öffen und schließen? Mich interessiert nicht was in der UI angezeigt wird, sondern was im Datenpunkt steht. Das kann man mit dem Homematic Manager kontrollieren, oder du fügst Section über unignore(siehe Doku) als separate Entität hinzu.

**Comment by 1onar** [comment]
> Section wird bereits für den Cover State (opening und closing) verwendet.

Seitens `custom_homematic` oder HmIP-MOD-HO Firmware? Weder noch scheint `SECTION` zu berücksichtigen.


> Ändert sich der Wert von Section in der CCU beim öffen und schließen?

Ich kann diese Beobachtungen auf die Schnelle über ioBroker tätigen. Bei Fahrten opening/closing ändert sich `SECTION`:

- `0` = Door closed
- `2` = Door opening
- `3` = Door opened
- `5` = Door closing


> oder du fügst Section über unignore(siehe Doku) als separate Entität hinzu.

Das sollte mir reichen. Dann kann ich mir mein eigenes Garagentor anlegen.


Entschuldige bitte meine Unwissenheit. Ich bin gerade im Umstieg von ioBroker auf Home Assistant und musste dort auch mit `SECTION` arbeiten.

**Comment by SukramJ** [comment]
> Dann kann ich mir mein eigenes Garagentor anlegen.

Ziel sollte schon sein die bestehende Cover Entität zu fixen.

Wird als State der Entität immer unknown angezeigt, oder nur beim öffnen und schliessen?

**Comment by SukramJ** [comment]
Was zeigt eigentlich door_state an, wenn das Tor in Bewegung ist?

**Comment by 1onar** [comment]
Peinlich, aber ich habe mir das falsche Cover angesehen. Die Standard Homematic Integration via `configuration.yaml` hat es falsch angezeigt bzw. mit "unknown". `custom_homematic` zeigt alles richtig an. Entschuldigung!
