### ISSUE TITLE
homematicip_local.set_device_value does not work in 1.66

### ISSUE THREAD

**Issue by meks007** [SukramJ/hahomematic#1729]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

the following action works in 1.65 but does not in 1.66:

action: homematicip_local.set_device_value
data:
  device_address: 00165D89BBB239
  channel: 2
  parameter: COMBINED_PARAMETER
  value: L=100,L2=100
  rx_mode: BURST

there is no error, the acction executes green in both cases, but only works in 1.65.

### What version of HomematicIP (local) has the issue?

1.66

### What was the last working version of HomematicIP (local)?

1.65

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.77.7.20240826

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Schade. 
`set_device_value` läuft bei mit ohne Probleme.
Und was kannst Du mit der Information anfangen. Ich denke genau so wenig wie ich mit deinem Ticket.

Um was für ein Gerät handelt es sich?
Was steht im HA log (full log)?

**Comment by SukramJ** [comment]
Der Commit war falsch referenziert.

**Comment by meks007** [comment]
Hi,
es steht nichts in den Logs, das hatte ich zu Beginn schon geprüft. Sowohl mit 1.65 als auch mit 1.66 geht die Aktion auf Grün. Es betrifft alle Aktoren, konkret habe ich es mit mehreren HmIPW-DRBL4 versucht. Habe gerade den Gegentest gemacht und 1.66 wieder installiert - geht nicht. Installiere ich 1.65, geht es sofort.

Wenn mein Ticket nicht aussagekräftig ist, dann wäre ich dir dankbar, wenn du konkrete Anleitungen gibst, wie ich mehr Informationen bereitstellen kann. Der übliche Weg über die Logs liefert keine Hinweise.

**Comment by meks007** [comment]
OK, Debugging aktiviert und mit 1.66 kommt folgende Warnung, die mit 1.65 nicht kommt.
Mit 1.66 funktioniert nur der rx_mode WAKEUP, den es mit 1.65 nicht gibt (da gibt es nur BURST). Und BURST funktioniert mit 1.66 nicht mehr.


Logger: hahomematic.client
Quelle: custom_components/homematicip_local/services.py:510
Integration: Homematic(IP) Local ([Dokumentation](https://github.com/danielperna84/custom_homematic), [Probleme](https://github.com/danielperna84/hahomematic/issues))
Erstmals aufgetreten: 14:10:14 (1 Vorkommnisse)
Zuletzt protokolliert: 14:10:14
SET_VALUE failed: unsupported rx_mode: BURST

**Comment by SukramJ** [comment]
Wenn ich wir das im Code anschaue wird `SET_VALUE failed: unsupported rx_mode:` als warning geloggt, und ist somit auch ohne debug-logging sichtbar.

Also richtigen `rx_mode` wählen oder ganz weglassen. Die 1.66.0 prüft hier, denn das Gerät unterstützt `BURST`nicht, und hat es auch vorher nicht.

**Comment by SukramJ** [comment]
... sofern das Basis-Logging nicht auf ein höheres Level als `warning` gesetzt wurde.

**Comment by meks007** [comment]
danke für die info, klappt ohne rx mode auch. default logging ist error.

**Comment by SukramJ** [comment]
> default logging ist error.

Das ist mMn nicht sinnvoll.

**Comment by Acgua** [comment]
Hi. 
Ich hatte auch festgestellt, dass beim Update auf 1.66 bei mir `homematicip_local.set_device_value` nicht mehr funktionierte. 
Action in Node-RED:
 - Action: `homematicip_local.set_device_value` 
 - Data: `{"device_address":"xxxxxxxxxxxxxx:1", "channel": 1, "parameter":"WINDOW_STATE","value":1}`

(dabei entspricht xxxxxxx der Seriennummer, die unter "Device info" in HomeAssistant, Device des entsprechenden Thermostats angezeigt wird.)

Fehlermeldung in Node-RED: 
`"HomeAssistantError: device_address is invalid for dictionary value @ data['device_address']"`

Unter device_address steht hinter der Seriennummer ein ":1", ich weiß nicht mehr, warum ich das vor einigen Monaten hinzufügte, aber damit funktionierte es bis Version 1.66 immer.

**Meine Lösung für 1.66: ":1" entfernen:**
 - Data: `{"device_address":"xxxxxxxxxxxxxx", "channel": 1, "parameter":"WINDOW_STATE","value":1}`

Vielleicht hilft das jemandem...

**Comment by SukramJ** [comment]
@Acgua #1731
