### ISSUE TITLE
After updating to 1.66: [hahomematic.central] CREATE_DEVICES failed: KeyError [UPDATABLE]

### ISSUE THREAD

**Issue by ghost** [SukramJ/hahomematic#1739]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

After updating to 1.66, I get this error for all my homegear cul devices:

ERROR (MainThread) [hahomematic.central] CREATE_DEVICES failed: KeyError [UPDATABLE] Unable to create device: HomeGear-BidCos-RF, LEQxxxxxxxxxx

which makes all my devices "unavailable" right now. 

### What version of HomematicIP (local) has the issue?

1.66

### What was the last working version of HomematicIP (local)?

1.65

### What type of installation are you running?

Home Assistant Container

### What type of installation are you running for your homematic backend?

Homegear

### Which version of your homematic backend are you running?

0.7.51-3497

### What hardware are you running for your system?

Pi4

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information (no logs here)

[config_entry-homematicip_local-6458eefa767ed16caa027efad9e51444 (1).json](https://github.com/user-attachments/files/17221630/config_entry-homematicip_local-6458eefa767ed16caa027efad9e51444.1.json)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
2024-10-02 09:45:05.102 ERROR (MainThread) [hahomematic.central] CREATE_DEVICES failed: KeyError [UPDATABLE] Unable to create device: HomeGear-BidCos-RF, REQxxxxxxxxx
```

**Comment by SukramJ** [comment]
Dublicate #1727

**Comment by SukramJ** [comment]
Rollback to 1.65.0
