### ISSUE TITLE
Long press not showing all events

### ISSUE THREAD

**Issue by eikowagenknecht** [SukramJ/hahomematic#174]
For some devices like the HM-PB-2-WM55-2, pressing it longer sends the following events in *pyhomematic*:

- PRESS_LONG
- PRESS_CONT (n times as long as it is held)
- PRESS_LONG_RELEASE

See my blog here https://phenx.de/events-von-homematic-und-homematic-ip-tastern/ for a more detailled list.

In *hahomematic* only the following event is thrown (checked in developer tools):
- press_long

The other two are missing. They are also missing in the device dropdown:

![image](https://user-images.githubusercontent.com/1475672/149336520-97a0d4ac-0096-4c71-82e5-2e02d5806947.png)

*Comparison to HmIp device*:
This seems not to be intentional since HmIp devices correctly show them:

![image](https://user-images.githubusercontent.com/1475672/149336646-7718b37c-0b4d-47d1-9275-0ec548d438ae.png)

**custom_component/hahomematic version (if applicable):**
latest

**Home Assistant version (if applicable):**
latest

**CCU version:**
CCU3 with Raspberrymatic

**Expected behavior**
All three events have their uses (e.g. dimming for the press_cont), so please add them back.

**Comment by SukramJ** [comment]
These events are different. Should be fixed with next release.

**Comment by SukramJ** [comment]
Fixed wit 0.21.1. Please retest.

**Comment by eikowagenknecht** [comment]
LGTM
