### ISSUE TITLE
Installation/update to version 1.66 not possible

### ISSUE THREAD

**Issue by j-hallier** [SukramJ/hahomematic#1740]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

To be sure to have no leftover Homematic devices, entities and configs I've cleared my former revision of HomematicIP (local) from my local HACS component, removed nearly every homematic-related things from .storage, rebooted and then tried to install v1.66 via HACS (again with required restart). But the component is not configurable via Settings->Devices & services -> add new integration. Popup shows "Error:  Config flow could not be loaded: {"message":"Invalid handler specified"} ".

### What version of HomematicIP (local) has the issue?

1.66

### What was the last working version of HomematicIP (local)?

1.63.1

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic HA-Addon

### Which version of your homematic backend are you running?

3.77.7.20240826

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
2024-10-02 11:44:47.449 INFO (SyncWorker_12) [homeassistant.util.package] Attempting install of hahomematic==2024.9.12
2024-10-02 11:44:51.012 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration homematicip_local: No module named 'hahomematic.validator'
```

**Comment by SukramJ** [comment]
Please add the full log

**Comment by j-hallier** [comment]
Here it is ...

[error.log](https://github.com/user-attachments/files/17228514/error.log)

**Comment by SukramJ** [comment]
Your System is not able to download the required deendency hahomematic from pypi. This task is related to HA or maybe HACS, but not to this Integration.
Sorry, there is nothing i can do for you. Maybe it is worth asking in the HA Community forum.

**Comment by j-hallier** [comment]
Thank you !

**Comment by j-hallier** [comment]
I've digged into the docker container of homeassistant and I can see that during the try of enabling HomematicIP with "add integration" the dependency of hahomematic (2024.9.12) is pulled and stored under /usr/local/lib/python3.12/site_packages together with a directory hahomematic_support. So the dependencies are available. But what might be the reason that it couldn' be found ? Other components don't have this problem.

**Comment by SukramJ** [comment]
Thousands of Users don't have this problem wirh the integration too.

**Comment by j-hallier** [comment]
Ok, I see I'm on my own. Thanks for your support though !

**Comment by j-hallier** [comment]
Solution for anybody else like me who migrated from Homeassistant on docker to HAOS: My (rather) old config directory contained a subdirectory named "deps": it was obviously used to store dependencies from custom_compontents (HACS, ...) and was the location where homeassistant (on docker) stored site-packages and **is still the first place to search for**. After deletion of this directory containing older versions of hahomematic (from pypi) all my problems went away and HomematicIP could be installed (and works great !!!) in any recent version.

**Comment by SukramJ** [comment]
Great.
Good to know!
