### ISSUE TITLE
Homematic (Bidcos-RF): HM-ES-TX-WM. Die Entität hat keine Zustandsklasse mehr..

### ISSUE THREAD

**Issue by ThomasLoeffel** [SukramJ/hahomematic#1745]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Seit dem neuesten Update (1.66.0) zeigt HM mir diese Fehlermeldung für GAS und Wasser an. Bei Strom funktioniert es wie gehabt. Der Dienst zeigt in den Statistiken aber alles wie gewünscht an. Er bietet zwei Reparaturen an. Indem er anbietet: Möchtest du die Langzeitstatistiken von sensor.hausanschluss_gas_gas_leistung dauerhaft aus deiner Datenbank löschen? Ich bin verwirrt!

Welche Infos braucht Ihr noch von mir?

### What version of HomematicIP (local) has the issue?

1.66.0

### What was the last working version of HomematicIP (local)?

1.65.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.77.7.20240826

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [ ] TLS
- [X] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [X] BidCos-Wired (HM-Wired)

### Diagnostics information (no logs here)

[config_entry-homematicip_local-2557ef9295230914947af7c750f9e0c1.json](https://github.com/user-attachments/files/17261461/config_entry-homematicip_local-2557ef9295230914947af7c750f9e0c1.json)

### Additional information

Danke für Eure Unterstützung!
Gruß Thomas

**Comment by SukramJ** [comment]
Dann zeig doch mal wie die Entitäten unter Einstellungen/Entwicklerwerkzeuge aussehen.
An der Integration hat sich diesbezüglich nichts geändert, und aus deiner Beschreibung werde ich nicht schlau.

**Comment by SukramJ** [comment]
Seit Mai gibt es die [state_class](https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics) (MEASUREMENT) nicht mehr bei GAS_POWER (sensor.hausanschluss_gas_gas_leistung), da eine Kombination, laut HA Definition, nur mit TOTAL oder TOTAL_INCREASING erlaubt ist. Neu mit HA 2024.10 ist, das die Fehler als "Repair" angezeigt werden.
Ist der Wert von` sensor.hausanschluss_gas_gas_leistung` stetig steigend (TOTAL*), oder wird die momentane Leistung (MEASUREMENT) angezeigt?

**Comment by PummelQualle** [comment]
Hallo, ich habe den selben Hinweis.

stetig steigend würde ich sagen:

![Bildschirmfoto_5-10-2024_9741_192 168 178 111](https://github.com/user-attachments/assets/549e777b-dc7a-49bb-9b87-f4eb57a67b75)

**Comment by SukramJ** [comment]
Das ist eine andere Entität!  Du zeigst GAS_ENERGY_COUNTER(Energiezähler), aber es geht um GAS_POWER(Leistung).

**Comment by PummelQualle** [comment]
Ok dann der Reihe nach.

mit dem neuesten HA Update habe ich folgende Meldung erhalten:
![Bildschirmfoto_5-10-2024_91729_192 168 178 111](https://github.com/user-attachments/assets/a16acc4f-3869-4219-8638-44503b7daad6)
 ich habe nur 2 Entitäten dafür:
![Bildschirmfoto_5-10-2024_91910_192 168 178 111](https://github.com/user-attachments/assets/92c620a6-bfec-4dbe-ad43-900b8412f63e)
und der gepostete ist bei mir im Energiezähler hinterlegt:

![Bildschirmfoto_5-10-2024_91943_192 168 178 111](https://github.com/user-attachments/assets/742e8d18-7fda-489d-aaf1-88bd790815f8)

**Comment by SukramJ** [comment]
In deiner Fehlermeldung steht klar ...gas_leistung. Gas-Energiezähler und die Einbindung ins Energie-Dashboard sind irrelevant.

**Comment by PummelQualle** [comment]
Sorry Screenshot Gas Leistung habe ich vergessen.

der sieht bei mir aber merkwürdig aus:

![Bildschirmfoto_5-10-2024_94527_192 168 178 111](https://github.com/user-attachments/assets/b0e85740-decf-4334-bf94-859e2fa6c059)
![Bildschirmfoto_5-10-2024_94527_192 168 178 111](https://github.com/user-attachments/assets/725ae25f-471c-4d09-b1a4-af522aabaa95)

**Comment by PummelQualle** [comment]
![Bildschirmfoto_5-10-2024_9454_192 168 178 111](https://github.com/user-attachments/assets/9717c018-075c-4cb6-82db-8743726f1ea8)

**Comment by SukramJ** [comment]
Der Grund warum im Mai die `state_class` entfernt wurde:
Der Hersteller liefert als Einheit Kubikmeter, und schreibt das so auch in seiner Doku.
Mit Kubikmeter ist in HA aber nur die TOTAL oder TOTAL_INCREASING state_class erlaubt.
Also wurde die `state_class` aufgrund einer HA Fehlermeldung entfernt.
Mit HA 2024.10 hat HA die Statistik-Fehlermeldungen umgestellt.
Der Fehler sollte seit Mai/Juni auch unter Einstellungen

Ich werde in der Integration nichts ändern, da ich ungern etwas vom Hersteller geliefertes verbiege.

Ihr könnt euch die Entität aber in HA konfigurieren (customize.yaml):

```
sensor.hausanschluss_gas_gas_leistung:
  unit_of_measurement: 'm³/h'
  state_class: measurement
```
Ich hab das mangels Sensor nicht getestet.

Es dauert einige Stunden bis die Statistiken neu berechnet werden, also warten!
