### ISSUE TITLE
Issues with dependencies in 1.66

### ISSUE THREAD

**Issue by katter** [SukramJ/hahomematic#1756]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

This is a follow-up on https://github.com/danielperna84/hahomematic/issues/1740.
I can confirm this to be an issue in a containerized environment with HA on K8s with HACS. The needed dependencied get to config/deps/ but are expected in config/deps/lib/python-3.12/site-packages/
`hahomematic-2024.6.0.dist-info` was present there instead of `...2024.9.12...` Hope that helps
Something must have changed somewhere (Hacs?)

No time yet to figure out how dependencies are managed in HACS tbh

### What version of HomematicIP (local) has the issue?

1.66

### What was the last working version of HomematicIP (local)?

1.65

### What type of installation are you running?

Home Assistant Container

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### What hardware are you running for your system?

K3s Cluster

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
This is not an issue with this integration.

> Something must have changed somewhere (Hacs?)

So why do you report it here?
Dependency management is not part of this integration, as might have already read in the linked issue.

> No time yet to figure out how dependencies are managed in HACS tbh

Tbh I don't care about it too.

Delete the the old dependency from /config/deps and restart HA.

**Comment by katter** [comment]
It is not that simple. Manual intervention in the container is required.  So it looks like you are kindly asking for some help getting to the bottom of the issue?
Am Dienstag, 8. Oktober 2024 um 17:55, SukramJ ***@***.***&gt; schrieb:   This is not an issue with this integration.   Something must have changed somewhere (Hacs?)  So why do you report it here?
 Dependency management is not part of this integration, as might have already read in the linked issue.   No time yet to figure out how dependencies are managed in HACS tbh  Tbh I don't care about it too. Delete the the old dependency from /config/deps and restart HA. —

**Comment by SukramJ** [comment]
> It is not that simple. Manual intervention in the container is required.  So it looks like you are kindly asking for some help getting to the bottom of the issue?

Nein, ich brauche da keine Hilfe, und ich hab auch nicht vor dem Thema auf den Grund zu gehen.
Ich kümmere mich um die Integration, und um alles Andere sollen sich auch Andere kümmern.
