### ISSUE TITLE
HmIP-SLO wird nicht erkannt

### ISSUE THREAD

**Issue by ps915** [SukramJ/hahomematic#1759]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Ich nutze diese Integration schon länger, jedoch nur mit meinen "normalen" HM Geräten. Die Integration läuft super bisher. 

Nun habe ich mir einen HmIP-SLO gekauft, zummengelötet und mit einer CCU3 (Raspberrymatic) angelernt. Das hat auch wunderbar funktioniert. 
![image](https://github.com/user-attachments/assets/420781d0-36b2-4a97-8c2f-fb7ce194ed3e)

Allerdings wird das neue Gerät nicht in der Integration angelegt. Auch nach einem Neustart der Integration, wird das Gerät nicht in Home Assistant angelegt. 

![image](https://github.com/user-attachments/assets/2bde1417-7eef-4aac-b109-fc5289edef41)

Übersehe ich hier etwas? Gibt es bei HmIP Geräte noch einen weiteren Schritt, den es bei den HM Geräten nicht gibt?

### What version of HomematicIP (local) has the issue?

1.66.0

### What was the last working version of HomematicIP (local)?

1.66.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.77.7.20240826

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information (no logs here)

home-assistant_homematicip_local_2024-10-10T14-28-22.118Z.log

**Comment by SukramJ** [comment]
Das Gerät läuft bei mir ohne Probleme.
[Cache löschen](https://github.com/danielperna84/custom_homematic#homematicip_localclear_cache) und neustarten.

Bitte häng die Diagnoseinformation der Integration an.

**Comment by ps915** [comment]
Okay, nachdem ich die Konfiguration des Moduls erneut gestartet habe (alle Werte sind gleich geblieben) hat es nun funktioniert. 
Er hat nun eine zweite CCU3 in Homeassistant angelegt, die nur für Homematic Ip zuständig ist. 

![image](https://github.com/user-attachments/assets/1fab2dc7-1f87-4b8b-9215-c5896feb8cb6)

Diese war zuvor nicht erstellt worden (wahrscheinlich weil ich keinerlei HmIP Geräte bisher angelernt habe.

Klappt nun!
