### ISSUE TITLE
Zunehmende Abstürze von HomematicIP (local) und HA

### ISSUE THREAD

**Issue by desek90** [SukramJ/hahomematic#1771]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hallo zusammen, 

ich habe ein Issue zu melden. Alle paar Tage/Wochen/Stunden, also mit verschiedensten Zeitabständen, scheint Homematic IP Integration abzustützen, was die ganze Instanz von HomeAssistant unbesiegbar macht. Kommen die Meldungen, die auf den Screenshots zu sehen sind, kann im HomeAssistant nichts mehr gemacht werden. Nicht mal ein Log kann heruntergeladen werden. Herunterfahren über die GUI funktioniert auch nicht. Stecker ziehen bleibt einem übrig. Das Problem tritt auf, seitdem ich Homeassistant überhaupt habe (seit einem halben Jahr), aber kommt gefühlt immer häufiger vor. Bspw. gestern zweimal und davor erst vor 2-3 Wochen das letzte Mal.

Ich bin vom der CCU3 zu HA mit Raspberrymaric und HMIP-RFUSB umgestiegen, wo es mit den Geräten selbst keine Probleme gab. Ich glaube, dass man die Thermostate usw. als Fehlerquelle deswegen ausschließen kann.

Ich würde mich über jegliche Hilfe/Tipps sehr freuen. 
Beste Grüße,
Bart

<img width="654" alt="Bildschirmfoto 2024-10-13 um 17 39 23" src="https://github.com/user-attachments/assets/03607682-e746-4a45-aa1a-f6ca9f755b73">
<img width="637" alt="Bildschirmfoto 2024-10-13 um 17 39 12" src="https://github.com/user-attachments/assets/5372a925-05f9-4f50-8ee3-cea908abba40">
<img width="652" alt="Bildschirmfoto 2024-10-13 um 17 38 47" src="https://github.com/user-attachments/assets/25341a7e-2c4b-476a-bc2e-b29aac27ac56">

### What version of HomematicIP (local) has the issue?

1.66.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic HA-Addon

### Which version of your homematic backend are you running?

3.77.7.20240826

### What hardware are you running for your system?

PI5

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Additional information

Identifying host system: Raspberry Pi 5 Model B Rev 1.0 (oci), OK
Initializing RTC Clock: onboard, OK
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Running seedrng: OK
Initializing System: OK
Setup ca-certificates: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.2, OK
Identifying Homematic RF-Hardware: ....HmRF: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-xhci-hcd.0-2, HmIP: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-xhci-hcd.0-2, OK
Updating Homematic RF-Hardware: HMIP-RFUSB: 4.4.18, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: .......OK
Starting rfd: .OK
Starting HMIPServer: .........OK
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.77.7.20240826 (raspmatic_oci_arm64)
Identifying host system: Raspberry Pi 5 Model B Rev 1.0 (oci), OK
Initializing RTC Clock: onboard, OK
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Running seedrng: OK
Initializing System: OK
Setup ca-certificates: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.2, OK
Identifying Homematic RF-Hardware: ....HmRF: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-xhci-hcd.0-2, HmIP: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-xhci-hcd.0-2, OK
Updating Homematic RF-Hardware: HMIP-RFUSB: 4.4.18, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: .......OK
Starting rfd: .OK
Starting HMIPServer: .........OK
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.77.7.20240826 (raspmatic_oci_arm64)

**Comment by SukramJ** [comment]
Wie kommst Du darauf, das die Integration die Abstürze verursacht?
Die Fehlermeldungen besagen nur, das dein Raspberrymatic-Addon nicht mehr erreichbar ist.

Das Raspberrymatic Log interessiert mich nicht, und ich kann damit auch nichts anfangen.

Einzig die **Integrationsdiagnose** (!!!!!) und die HA Log Datei, wie beim Erstellen des Issues gefordert, interessieren mich, also bitte anhängen.

**Comment by desek90** [comment]
Wie ich drauf komme? Das ist nur blindes Raten von meiner Seite, also irgendwo musste ich anfangen... 
[home-assistant_homematicip_local_2024-10-13T16-09-42.961Z.log](https://github.com/user-attachments/files/17356239/home-assistant_homematicip_local_2024-10-13T16-09-42.961Z.log)

[home-assistant_2024-10-13T16-10-52.649Z.log](https://github.com/user-attachments/files/17356274/home-assistant_2024-10-13T16-10-52.649Z.log)

Danke für die schnelle Reaktion
Beste Grüße

**Comment by SukramJ** [comment]
Du hast das Log zweimal angehängt. Ich hätte noch gerne die Integrationsdiagnose.

> Detected blocking call to open with args ('/usr/local/lib/python3.12/site-packages/miio/integrations/light/yeelight/specs.yaml',) inside the event loop by custom integration 'miio_yeelink' at custom_components/miio_yeelink/__init__.py, line 428: self._device = Yeelight(ip=host, token=token) (offender: /usr/local/lib/python3.12/site-packages/miio/integrations/light/yeelight/spec_helper.py, line 56: with open(os.path.dirname(__file__) + "/specs.yaml") as filedata:), please create a bug report at https://github.com/al-one/hass-miio-yeelink/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open

`miio_yeelink` erzeugt viele Fehler, vielleicht mal aktualisieren.

Diese Integration würde ich ausschliessen, die Fehlermeldungen beziehen sich nur auf die fehlende Verbindung zu RaspberryMatic.

**Comment by Baxxy13** [comment]
Wenn jetzt im Log des RM-AddOns kein C&P Fehler steckt dann würde ich sagen das RM-AddOn wird entweder hart "abgewürgt" (vielleicht wegen OOM vom HA) oder es crasht einfach, und wird dann in beiden Fällen vom Watchdog neu gestartet.

Ich kann nicht ausschließen das das Problem vom RM-AddOn ausgeht, bezweifle das aber da mir aktuell keine solchen Meldungen bekannt sind. 
Diese Integration würde ich auch ausschließen, sie meckert halt berechtigterweise weil das RM-AddOn gar nicht bzw. sehr unrund läuft.

**Comment by SukramJ** [comment]
Mit dem jetzigen Zustand deines Systems (miio_yeelink error/warnings) macht es keinen Sinn sich das Thema aus Integrations Sicht anzuschauen.
