### ISSUE TITLE
Loading integration fails with hahomematic 1.67.0

### ISSUE THREAD

**Issue by towo** [SukramJ/hahomematic#1776]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Integration cannot be loaded in current stable HA Container with extant configuration.

### What version of HomematicIP (local) has the issue?

1.67.0

### What was the last working version of HomematicIP (local)?

1.66.0

### What type of installation are you running?

Home Assistant Container

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
Logger: homeassistant.setup
Source: setup.py:334
First occurred: 09:46:37 (1 occurrences)
Last logged: 09:46:37

Setup failed for custom integration 'homematicip_local': Unable to import component: cannot import name 'CustomEntity' from 'hahomematic.platforms.custom' (/config/deps/lib/python3.12/site-packages/hahomematic/platforms/custom/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/homematicip_local/__init__.py", line 35, in <module>
    from .control_unit import ControlConfig, ControlUnit, get_storage_folder
  File "/config/custom_components/homematicip_local/control_unit.py", line 94, in <module>
    from .support import (
  File "/config/custom_components/homematicip_local/support.py", line 10, in <module>
    from hahomematic.platforms.custom import CustomEntity
ImportError: cannot import name 'CustomEntity' from 'hahomematic.platforms.custom' (/config/deps/lib/python3.12/site-packages/hahomematic/platforms/custom/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/homematicip_local/__init__.py", line 35, in <module>
    from .control_unit import ControlConfig, ControlUnit, get_storage_folder
  File "/config/custom_components/homematicip_local/control_unit.py", line 94, in <module>
    from .support import (
  File "/config/custom_components/homematicip_local/support.py", line 10, in <module>
    from hahomematic.platforms.custom import CustomEntity
ImportError: cannot import name 'CustomEntity' from 'hahomematic.platforms.custom' (/config/deps/lib/python3.12/site-packages/hahomematic/platforms/custom/__init__.py)
```

### Additional information

I tried to reproduce this in a venv and could not:

```
$ python -m venv tmp
$ cd tmp; . bin/activate
$ pip install hahomematic
$ python
>>> from hahomematic.platforms.custom import CustomEntity
>>> import sys
>>> 'hahomematic' in sys.modules
True
>>> 'hahomematic.platforms.custom' in sys.modules
True
>>> 'hahomematic.platforms.custom.entity' in sys.modules
True
>>> CustomEntity
<class 'hahomematic.platforms.custom.entity.CustomEntity'>
```

**Comment by SukramJ** [comment]
Kein Fehler der Integration.
Ich denke hier liegt mal wieder ein Problem im Dependency Management von HA vor.
Dependency Management  ist eine Aufgabe von HA und nicht dieser Integration

Im /config/deps liegt bestimmt eine alte Version von hahomematic. Version löschen und HA neustarten.

**Comment by towo** [comment]
Okay, interessant. Es gibt:

```
./deps/hahomematic-2024.10.8.dist-info
./deps/hahomematic
./deps/hahomematic_support
./deps/lib/python3.10/site-packages/hahomematic
./deps/lib/python3.10/site-packages/hahomematic-2023.5.2.dist-info
./deps/lib/python3.11/site-packages/hahomematic
./deps/lib/python3.11/site-packages/hahomematic_support
./deps/lib/python3.11/site-packages/hahomematic-2024.1.7.dist-info
./deps/lib/python3.12/site-packages/hahomematic
./deps/lib/python3.12/site-packages/hahomematic_support
./deps/lib/python3.12/site-packages/hahomematic-2024.9.12.dist-info
./deps/lib/python3.9/site-packages/hahomematic
./deps/lib/python3.9/site-packages/hahomematic-1.9.1.dist-info
```

Die alte Variante in `deps/lib/python3.12/site-packages` gelöscht… Integration startet nimmer. die Versionen in `deps/ha*` gelöscht: Integration startet nimmer.

Haut freundlich ein

```
Oct 16 17:43:44 bifrost.waystone.wolter.house home-assistant[1171497]: 2024-10-16 17:43:44.858 INFO (SyncWorker_43) [homeassistant.util.package] Attempting install of hahomematic==2024.10.8
Oct 16 17:43:46 bifrost.waystone.wolter.house home-assistant[1171497]: 2024-10-16 17:43:46.847 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'homematicip_local': Unable to import component: No module named 'hahomematic'
```

raus nach einem disable/enable. Neustarts haben erstaunlich wenig Erfolg, die Dependencies neu zu installieren. Ist zwar jetzt wieder in `deps`, wird aber nicht zu den Python 3.12-Paketen gepackt.

**Comment by towo** [comment]
Wird scheinbar nur nach `/config/deps` installiert; Pakete werden aber in `/config/deps/lib/python3.12/site-packages` erwartet. Manuell hinkopiert geht's.
Ist das eher ein HACS oder ein HA-Thema für's followup?

**Comment by SukramJ** [comment]
Ich muss hier auch raten, weil das nicht mein Thema ist, und das Problem nur bei Containerinstallationen existiert.
Alles was nicht python 3.12 kann grundsätzlich komplett gelöscht werden.
Dependencies sollte HA alleine nachladen.
Was ist das:`bifrost.waystone.wolter.house`?

Bei meiner HAOS installation ist `/config/deps` leer.
Ich hab vor ein paar Wochen mal eine Container Installation  gemacht, und da ist der Order auch leer.

Da  ich ja davon ausgehe, das du ein Backup hast und dich an die Conatiner Vorgaben für die Installation gehalten hast, würde ich den `/config/deps` Order komplett leeren, und danach den Container neu starten. Wie durch ein Wunder funktioniert danach alles.
Ansonsten endet da mein Wissen.

**Comment by towo** [comment]
bifrost ist nur der Hostname, habe die Sachen direkt aus einem der Logs kopiert. Bin gerade mal bisschen durch den Code gegangen, `homeassistant.util.package` installiert fleissig, aber irgendwie stolpern die über die `site-packages`. Vielleicht mal wirklich mit Backup und tabula rasa probieren, aber dann sollte das ja eigentlich mal in irgendwelchen Release Notes stehen, dass man da die alten Sachen wegwerfen darf.

**Comment by SukramJ** [comment]
>  HA-Thema für's followup?

Das ist ein HA Thema. 
Tickets in Github werden aber mit Verweis auf eine custom_component gerne zurückverwiesen, obwohl der komplette Code in HA liegt

**Comment by SukramJ** [comment]
Irgendwie häufen sich die Probleme aktuell bei den Container Installation, und die User landen dann hier.
Wenn Du was rausfindest wäre es schön, wenn Du noch mal Feedback geben kannst.
Issue werden irgendwann gelockt. Gerne dann auch als neue Diskussion.

**Comment by chris42** [comment]
FYI: Hatte gerade den gleichen Fehler in Containern. Tip von towo funktioniert.
Ggf. vorhandene alte Versionen im site-packages vorher löschen.

> Wird scheinbar nur nach `/config/deps` installiert; Pakete werden aber in `/config/deps/lib/python3.12/site-packages` erwartet. Manuell hinkopiert geht's. Ist das eher ein HACS oder ein HA-Thema für's followup?

**Comment by u-lehner** [comment]
> Wird scheinbar nur nach `/config/deps` installiert; Pakete werden aber in `/config/deps/lib/python3.12/site-packages` erwartet. Manuell hinkopiert geht's. Ist das eher ein HACS oder ein HA-Thema für's followup?

Danke, hat geholfen.

Wenn's beruhigt: ist nicht die einzige Integration, die deswegen ausgestiegen ist. Die [DWD-Integration hatte das selbe Problem](https://github.com/FL550/dwd_weather/issues/155).

**Comment by eloo** [comment]
for the record:
here is the upstream issue about the dependency issues:

https://github.com/home-assistant/core/issues/127966

**Comment by lackhove** [comment]
@SukramJ  Ich habe ein ähnliches Problem mit Version 1.68.1, ebenfalls im Container. `deps/lib/python3.12/site-packages/hahomematic` hat allerdings existiert. Darauf habe ich das komplette `deps` Verzeichnis umbenannt und den Container neu gestartet. Jetzt gibt es gar kein `deps/lib` mehr, nur noch die Pakete direkt unter deps (z.B. `deps/hahomematic` existiert). Im Log sehe ich folgendes:

```2024-10-26 20:45:27.244 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'homematicip_local': Unable to import component: No module named 'hahomematic'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/homematicip_local/__init__.py", line 11, in <module>
    from hahomematic import __version__ as HAHM_VERSION
ModuleNotFoundError: No module named 'hahomematic'
```

Ist das das gleiche Problem oder ein anderes?

**Comment by SukramJ** [comment]
> Ist das das gleiche Problem oder ein anderes?

Das Gleiche

**Comment by viennaa** [comment]
Kurze Info für alle, die hier auch noch drüber stolpern, bis es gefixt ist. Credit to the [upstream issue](https://github.com/home-assistant/core/issues/127966#issuecomment-2439414558).

Im podman run Command einfach das mitgeben, um die Environment var zu setzen, dann braucht man nicht die Files kopieren.

```-e 'PYTHONPATH=/config/deps' ```
