### ISSUE TITLE
No reconnection after loosing Connection to Homegear

### ISSUE THREAD

**Issue by wbuh123** [SukramJ/hahomematic#1785]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I'm running homegear 0.10.24101812-3672 with HomematicIP local 1.59.0 in Homeassistant.
Homegear is on a separated server with different IP Adress.
I'm running into problems with HomematicIP local in case the HomematicIP Server looses it's IP connection to the Homegear server for a short period (a few seconds).
After the IP connection is back, the HomematicIP local app must be restarted in Homeassistant manually. There is no reconnect by homematicIP local itself.
Log-File of homeassistant says
![grafik](https://github.com/user-attachments/assets/7381cc01-9876-4e64-8129-58aff8a42de7)

### What version of HomematicIP (local) has the issue?

1.59.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

Homegear

### Which version of your homematic backend are you running?

0.10.24101812

### What hardware are you running for your system?

proxmox

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Dir ist beim lesen der Release Notes nicht aufgefallen, dass deine Version veraltet ist?
Warum schreib ich das wohl da oben rein?
Die alten Versionen supporte ich nicht mehr.

**Comment by wbuh123** [comment]
Danke für die schnelle Antwort.
Mit "alte Version" meinst Du die 1.59 von HomaticIP local?
Hierzu muss ich sagen, dass eine neuere Version von HomematicIP local bei mir dazu geführt hat, dass die Abfrage beim Start nach wenigen Sekunden abbrach und damit überhaupt keine Homatic Komponenten mehr in Homeassistant angezeigt wurden. Daher musste ich zurück zur 1.59

Da ich recht neu in der Homeassistant Welt unterwegs bin, würde ich mich über einen freundlichen Hinweis freuen: welchen Versionsstand bei homegear und HomematicIP local empfiehlst Du aktuell als "funktioniert"?

**Comment by SukramJ** [comment]
> welchen Versionsstand bei homegear und HomematicIP local empfiehlst Du aktuell als "funktioniert"?

Das kann ich nicht, da ich Homegear nicht verwende.

Also installiere die neuste Version, und mach ein Ticket auf, wenn es nicht funktioniert.
Wie soll man ansonsten die Fehler finden?
