### ISSUE TITLE
Invalid value 4.5 warning when turning off a thermostat

### ISSUE THREAD

**Issue by zapccu** [SukramJ/hahomematic#1787]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

When turning off a thermostat a value of 4.5 must be send by the integration to the CCU (30.5 is turning a thermostat permanentlly on).
This results in the following log entry:

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: hahomematic.platforms.generic.entity
Quelle: custom_components/homematicip_local/climate.py:405
Integration: Homematic(IP) Local (Dokumentation, Probleme)
Erstmals aufgetreten: 21. Oktober 2024 um 20:49:33 (1 Vorkommnisse)
Zuletzt protokolliert: 21. Oktober 2024 um 20:49:33

NUMBER failed: Invalid value: 4.5 (min: 5.0, max: 30.0, special:None)
```

Obviously the bounds checking of the integration has a problem. I guess this behaviour came in with the last update.

### What version of HomematicIP (local) has the issue?

1.67.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.77.7

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
2024-10-21 20:49:33.497 WARNING (MainThread) [hahomematic.platforms.generic.entity] NUMBER failed: Invalid value: 4.5 (min: 5.0, max: 30.0, special:None)
```

**Comment by SukramJ** [comment]
No problem with my thermostats so i guess it's not related to the integration.

Which thermostat model?
How do you turn off?
What is the min temperature setting for the thermostat in CCU?

**Comment by trilu2000** [comment]
I have exactly the same issue with a "Heizungsgruppe", as my radiator and wall mount thermostat is combined and visible in HA as "Heizungsgruppe". If i change the single devce, RT or WT all works as expected.
The integration was working last winter, so i guess there was a change in the last time and only on "Heizungsgruppe"
Please let me know if you need more information.

**Comment by SukramJ** [comment]
Andere Fragen hab ich nicht.

**Comment by SukramJ** [comment]
Wenn ich keine Antworten auf meine Fragen erhalte werde ich das Ticket schliessen.

**Comment by trilu2000** [comment]
Bitte nicht schließen, ich hatte doch die Details geliefert. 
Zumindest aus meiner Sicht - WT und RD habe ich getestet, die gehen, aber Heizungsgruppen gehen nicht.
Da tritt exakt der beschriebene Fehler auf.

**Comment by SukramJ** [comment]
Und wie Du an meiner Reaktion siehst sind für mich die Information nicht ausreichend / relevant!
Was soll WT und RD sein? 

> Which thermostat model?
How do you turn off?
What is the min temperature setting for the thermostat in CCU?

**Comment by trilu2000** [comment]
WT = Wallmount Thermostat, HM-TC-IT-WM-W-EU
RT = Radiator Thermostat, HM-CC-RT-DN

Ausschalten einer Heizungsgruppe funktioniert mit keiner der beiden Möglichkeiten
- Lovelace Card, auf Aus drücken
- Drei Punkte auf der Lovelace Card drücken und im geöffneten Fenster das Modus drop down auf Aus setzen

Bei einem RT und WT funktioniert es ohne Probleme und ändert auch den Status der Heizungsgruppe.

In der CCU kann ich bei RT, WT und Heizungsgruppe 4.5 bis 30.5 Grad einstellen, bei 4.5 Grad ändert sich der Zustand auf Aus. 

In Homeassistant kann ich bei RT, WT und Heizungsgruppe 5 bis 30.5 Grad einstellen.
Wenn ich in Homeassistant bei RT und WT auf Aus drücke, dann schaltet das jeweilige Gerät aus und die Temperaturanzeige zeigt 4.5 Grad.
Wenn ich in Homeassistant bei Heizungsgruppe auf Aus drücke, springt die Anzeige auf Heizbetrieb und  
`2024-10-24 13:46:15.571 WARNING (MainThread) [hahomematic.platforms.generic.entity] NUMBER failed: Invalid value: 4.5 (min: 5.0, max: 30.0, special:None)`
wird ins Log geschrieben.

**Comment by SukramJ** [comment]
Geht doch.

Bitte exportiere die Gerätedefinitionen der Heizgruppe mit dem [Export-Service](https://github.com/danielperna84/custom_homematic#homematicip_localexport_device_definition), und hänge bitte beide Dateien hier an.

> (min: 5.0, max: 30.0, special:None)

Deutet darauf hin, das bei HM-Heizgruppen neuerdings 5.0 als minimaler Temperatur Wert steht.

**Comment by trilu2000** [comment]
[HM-CC-VG-1-device.json](https://github.com/user-attachments/files/17507030/HM-CC-VG-1-device.json)
[HM-CC-VG-1-paramset.json](https://github.com/user-attachments/files/17507031/HM-CC-VG-1-paramset.json)

**Comment by SukramJ** [comment]
Die Integration verwendet den erlaubten Wertebereich, den das Gerät liefert.

Der ist bei der Gruppe `HM-CC-VG-1` **5.0**-30.0 und bei `HM-TC-IT-WM-W-EU` / `HM-CC-RT-DN` **4.5**-30.0.
Da die Homematic Definition 4.5 als `Aus` definiert funktioniert es bei der Gruppe nicht, da der Wertebereich nicht passt.

```
      "SET_TEMPERATURE": {
        "UNIT": "°C",
        "MIN": "5.0",
        "MAX": "30.0",
        "OPERATIONS": 7,
        "FLAGS": 1,
        "ID": "SET_TEMPERATURE",
        "TAB_ORDER": 4,
        "TYPE": "FLOAT",
        "DEFAULT": "20.0",
        "CONTROL": "HEATING_CONTROL.SETPOINT"
      },
```
Beim  `HM-TC-IT-WM-W-EU` und beim `HM-CC-RT-DN` ist der Wertebereich 4,5-30.0
```
      "SET_TEMPERATURE": {
        "TYPE": "FLOAT",
        "OPERATIONS": 7,
        "FLAGS": 1,
        "DEFAULT": 20.0,
        "MAX": 30.5,
        "MIN": 4.5,
        "UNIT": "\u00b0C",
        "TAB_ORDER": 0,
        "CONTROL": "HEATING_CONTROL.SETPOINT"
      },

**Comment by SukramJ** [comment]
... und diese Validierung ist seid 11/2021 eingebaut.

**Comment by SukramJ** [comment]
Hat es mit der 1.66.0 noch funktioniert?
Wenn möglich bitte mal testen.

**Comment by trilu2000** [comment]
Eben getestet,
Ja, funktioniert in der 1.66

**Comment by SukramJ** [comment]
@trilu2000 Vielen Dank. Wird in der nächsten Version gefixt sein.
@zapccu Überleg dir das nächste mal, ob es Sinn macht ein Issue zu eröffnen, wenn Du keine Zeit/Lust hast mitzuarbeiten.

**Comment by trilu2000** [comment]
Danke!

**Comment by Baxxy13** [comment]
Eigentlich müsste eQ-3 die MIN/MAX - Definitionen für die HM-Heizgruppen an "den Standard" anpassen.
Alle mir bekannten HM/HmIP - Geräte gehen von 4.5 - 30.5. Auch die HmIP-Heizgruppen.
Nur die HM-Heizgruppen tanzen mit 5.0 - 30.0 aus der Reihe.

**Comment by SukramJ** [comment]
Eigentlich ... :wink:

**Comment by zapccu** [comment]
Sorry, dass ich nicht gleicht geantwortet habe. Auf der anderen Seite: dieser Bug in der Paramset-Description der CCU für Heizungsgruppen ist seit langem bekannt. Ich habe in meinem FHEM-Modul für die Homematic Integration eine entsprechende Korrektur irgendwann 2022 eingebaut.

Und einen Bug schließen, nur weil Infos fehlen, löst das Problem nicht.

P.S. das Problem mit der falschen Paramset Description gibt's auch bei anderen Geräten (z.B. bei einigen Rollladenaktoren mit Spezialwerten >1 für das LEVEL.

**Comment by SukramJ** [comment]
> Und einen Bug schließen, nur weil Infos fehlen, löst das Problem nicht.

Ich schliesse Tickets wenn keine Reaktion kommt. Dann gehe ich davon aus, das kein Interesse mehr da ist.
