### ISSUE TITLE
HmIP-DRBLI4 channel 23 + 24 entity does not appear

### ISSUE THREAD

**Issue by Laharny** [SukramJ/hahomematic#1794]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I am not able to use channel 23 + 24 on my HmIP-DRBLI4 0025DD89B1F9B0 because they don't show up in the list of entities. Channel 11 + 12, 15 + 16 and 19 + 20 (same functionality) are visible and working.

### What version of HomematicIP (local) has the issue?

1.66.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.79.6

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information (no logs here)

[home-assistant_homematicip_local_2024-10-26T07-56-57.519Z.log](https://github.com/user-attachments/files/17529546/home-assistant_homematicip_local_2024-10-26T07-56-57.519Z.log)

**Comment by SukramJ** [comment]
>I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
 I am aware that an integration that was installed via HACS also needs to be updated via HACS 
I am running the latest version of the custom_component (and Home Assistant)
Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!
For example, error message, or stack traces. **Don't switch to DEBUG level if not requested.**

Thank you for carefully filling out the issue template.
Please don' report issues for outdated versions. Current version is 1.68.1.
