### ISSUE TITLE
Incorrect Lock Status Notification for Homematic DLD Door Lock in Home Assistant

### ISSUE THREAD

**Issue by freigeistmaschine** [SukramJ/hahomematic#1796]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I would like to report an issue with the Homematic integration in Home Assistant.

When I unlock my Homematic DLD door lock via Home Assistant, the lock briefly shows as "locked" just a second before it shows as "unlocked," but this isn’t correct. The door wasn’t locked initially, and it doesn’t actually lock at that moment; only the latch is released.

I also receive notifications from HomeKit stating:

“Door locked”
“Door unlocked”

<img width="998" alt="Bildschirmfoto 2024-10-26 um 16 17 45" src="https://github.com/user-attachments/assets/ace167a7-7ac5-4cf0-9bba-b730e551a34b">

### What version of HomematicIP (local) has the issue?

1.67.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.77.7.20240826

### What hardware are you running for your system?

Proxmox, Lenovo m720q i5-8400t

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Additional information

When I open the door in the RaspberryMatic web interface, only “Door was unlocked” is pushed in HomeKit, and in the Home Assistant lock status, it only shows “unlocked.” So, everything is working correctly in this case.

**Comment by SukramJ** [comment]
Bitte auf 1.68.1 updaten und debugging aktivieren.
Bitte folgende Aktionen mit jeweils einer Minute Abstand durchführen und die Uhrzeit aufschreiben:
DLD über HA sperren, entsperren, öffnen.
Aktionen mit CCU wiederholen.

Danach kann debugging wieder deaktiviert werden.
Die vollständige Logdatei(Einstellungen, System, Protokoll), die aufgeschriebenen Zeiten der Aktionen und einen neuen Screenshot mit dem Verlauf hier anhängen


Bitte keine Verweise zu HomeKit, da die nur stören, und mich nicht interessieren.

**Comment by freigeistmaschine** [comment]
nach dem update auf 1.68.1 steht in Lochbuch nicht mehr zugesperrt

in Homekit leider immer noch, aber da bin ich hier falsch :)

Werde ich dann bei der Homekit Integration nachfragen
