### ISSUE TITLE
Homematic HmIP-DLD crash when locking

### ISSUE THREAD

**Issue by franky121** [SukramJ/hahomematic#1807]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hi, I have an issue with the HmIP-DLD door lock. It is working correct from the CCU3 interface. When I trigger "lock" it is loosing communication and showing as "not available" in the Home Assistant user interface. 
When I then click buttons on the CCU3 a couple of times is is available again until I trigger again a function in Home Assistant. 
I updated HomematicIP (local) to the latest version as well as Home Assistant. CCU 3 (Raspberymatic) is on latest version as well. 
I am lost...

### What version of HomematicIP (local) has the issue?

1.68.1

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.77.7.20240826

### What hardware are you running for your system?

PI3B

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [X] BidCos-Wired (HM-Wired)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
Error in Homeassistant: 

Logger: hahomematic.platforms.custom.lock
Quelle: custom_components/homematicip_local/lock.py:104
Integration: Homematic(IP) Local ([Dokumentation](https://github.com/danielperna84/custom_homematic), [Probleme](https://github.com/danielperna84/hahomematic/issues))
Erstmals aufgetreten: 10:43:07 (1 Vorkommnisse)
Zuletzt protokolliert: 10:43:07

SET_VALUE failed for 002A1D89B50451:1/LOCK_TARGET_LEVEL/0: XMLRPC Fault from backend: -1 Generic error (TIMEOUT)
```

**Comment by SukramJ** [comment]
Es ist kein Fehler der Integration, wenn deine CCU aufgrund eines `TIMEOUT` das Gerät nicht erreicht.
Wenn Du ein Problem mit der Geräteverfügbar keit hast (deswegen werden Geräte in HA als nicht verfügbar angezeigt), dann soltest Du dir mal den Service [force_device_availability](https://github.com/danielperna84/custom_homematic#homematicip_localforce_device_availability) anschauen, der auch in den [Reactivate Blueprints](https://github.com/danielperna84/custom_homematic#available-blueprints) verwendet wird.
Die Integration wertet nur das aus was von der API geliefert wird.

**Comment by franky121** [comment]
Das habe ich gecheckt. Das Problem ist das nur dieses Device als nicht verfügbar angezeigt wird und das das Gerät in der Homematic keinen Fehler wirft und dort erreichbar ist.

**Comment by SukramJ** [comment]
Nein, das Problem ist, das Du meine Antwort nicht durchgelesen hast.
In der CCU werden die Fehler nicht angezeigt.
