### ISSUE TITLE
Error while trying to add Integration to Home Assistant 

### ISSUE THREAD

**Issue by michaelkrause-SAP** [SukramJ/hahomematic#1814]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

When trying to add the Integration I get the following message: Der Konfigurationsfluss konnte nicht geladen werden: 500 Internal Server Error Server got itself in trouble

### What version of HomematicIP (local) has the issue?

1.69.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

core-2024.10.4

### What hardware are you running for your system?

Raspberry 3b

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Additional information

I'm not able to install it, so device logging not possible

**Comment by SukramJ** [comment]
This is not an issue with  the integration. It's related to HA.

Please add the log (full log)

**Comment by michaelkrause-SAP** [comment]
[HA Log.txt](https://github.com/user-attachments/files/17611378/HA.Log.txt)
does that help ?? thanks a lot for your help

**Comment by SukramJ** [comment]
Not really, but looks like your system has a problem with uv that is used by HA for dependency management.
Try restart HA, then try again.

Closing this, as it is an issue with HA, and not with this integration.
