### ISSUE TITLE
Rename of device in CCU not reflected in Home Assistant

### ISSUE THREAD

**Issue by eikowagenknecht** [SukramJ/hahomematic#182]
Not sure if this is intended to work, so I filed it as a bug, but it might as well just be a feature request.

I recently renamed a device in the CCU3 because I moved it to another place/function. This was not reflected in Home Assistant, even after a reboot. It would be nice if devices that I have not named manually get renamed together with the one on the CCU3. Is this possible or another HA limitation? ;-)

**custom_component/hahomematic version (if applicable):**
latest

**Home Assistant version (if applicable):**
latest

**CCU version:**
CCU3 with Raspberrymatic

**To Reproduce**
1. Rename device in CCU3
2. Restart HA
3. See the device name in HA

**Comment by SukramJ** [comment]
Option 1: Reload the Integration, that will delete the caches, but the entity_id will not change.
Option 2: use the service `hahm.delete_device`. This deletes the device from all caches, and from entity/device_registry. A reload on the integration/or a restart will recreate the device an entities. The new name will be reflected also in the entity_id.
Option 3: Just rename entity_id and name in HA

**Comment by SukramJ** [comment]
Just started a [HowTo](https://github.com/danielperna84/hahomematic/wiki/Howto's) page. To be extended.

**Comment by eikowagenknecht** [comment]
Very nice, thank you :-)

**Comment by eikowagenknecht** [comment]
It's hahm instead of haha btw.
