### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by bonnz-de** [SukramJ/hahomematic#1821]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

While adding the integration I get the error message "Verbindung fehlgeschlagen. Weitere Details finden Sie im HA-Protokoll". Unfortunately there's no log entry reporting this issue or any other issue while trying to connect

### What version of HomematicIP (local) has the issue?

1.70.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.77.7

### What hardware are you running for your system?

Pi3

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [X] BidCos-Wired (HM-Wired)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
No log entries for the connection problems
```

**Comment by SukramJ** [comment]
Dann solltest Du das HA log Level anpassen. Dann sieht man auch den Fehler.
Info sollte reichen, ansonsten auf debug stellen.

**Comment by bonnz-de** [comment]
Also diese Meldungen wiederholen sich im Log (debug!) immer wieder. Schlau werde ich darauf aber nicht:

`2024-11-07 19:51:17.288 DEBUG (MainThread) [zeroconf] Received from '::ffff:192.168.2.252':5353 [socket 31 (('::', 5353, 0, 0))]: <DNSIncoming:{id=0, flags=33792, truncated=False, n_q=0, n_ans=6, n_auth=0, n_add=0, questions=[], answers=[record[ptr,in,_hap._tcp.local.]=4500.0/4499,CCU3-58FC._hap._tcp.local., record[srv,in-unique,CCU3-58FC._hap._tcp.local.]=120.0/119,CC_22_3D_CB_45_EB.local.:51826, record[txt,in-unique,CCU3-58FC._hap._tcp.local.]=4500.0/4499,b'\x07md=CCU'..., record[a,in-unique,CC_22_3D_CB_45_EB.local.]=120.0/119,192.168.2.252, record[a,in-unique,CC_22_3D_CB_45_EB.local.]=120.0/119,10.220.130.159, record[quada,in-unique,CC_22_3D_CB_45_EB.local.]=120.0/119,fe80::3751:89fe:4fca:652d]}> (373 bytes) as [b'\x00\x00\x84\x00\x00\x00\x00\x06\x00\x00\x00\x00\x04_hap\x04_tcp\x05local\x00\x00\x0c\x00\x01\x00\x00\x11\x94\x00\x1b\tCCU3-58FC\x04_hap\x04_tcp\x05local\x00\tCCU3-58FC\x04_hap\x04_tcp\x05local\x00\x00!\x80\x01\x00\x00\x00x\x00\x1f\x00\x00\x00\x00\xcar\x11CC_22_3D_CB_45_EB\x05local\x00\tCCU3-58FC\x04_hap\x04_tcp\x05local\x00\x00\x10\x80\x01\x00\x00\x11\x94\x00I\x07md=CCU3\x06pv=1.0\x14id=CC:22:3D:CB:45:EB\x04c#=3\x04s#=1\x04ff=0\x04ci=1\x04sf=1\x0bsh=oYYRbA==\x11CC_22_3D_CB_45_EB\x05local\x00\x00\x01\x80\x01\x00\x00\x00x\x00\x04\xc0\xa8\x02\xfc\x11CC_22_3D_CB_45_EB\x05local\x00\x00\x01\x80\x01\x00\x00\x00x\x00\x04\n\xdc\x82\x9f\x11CC_22_3D_CB_45_EB\x05local\x00\x00\x1c\x80\x01\x00\x00\x00x\x00\x10\xfe\x80\x00\x00\x00\x00\x00\x007Q\x89\xfeO\xcae-']
2024-11-07 19:51:17.290 DEBUG (MainThread) [zeroconf] IPv6 scope_id 0 associated to the receiving interface
2024-11-07 19:51:17.291 DEBUG (MainThread) [zeroconf] Received from '::ffff:192.168.2.252':5353 [socket 31 (('::', 5353, 0, 0))]: <DNSIncoming:{id=0, flags=33792, truncated=False, n_q=0, n_ans=6, n_auth=0, n_add=0, questions=[], answers=[record[ptr,in,_hap._tcp.local.]=4500.0/4499,G5 Vorderseite-9699._hap._tcp.local., record[srv,in-unique,G5 Vorderseite-9699._hap._tcp.local.]=120.0/119,CC_22_3D_67_59_1E.local.:51912, record[txt,in-unique,G5 Vorderseite-9699._hap._tcp.local.]=4500.0/4499,b'\x11md=G5 '..., record[a,in-unique,CC_22_3D_67_59_1E.local.]=120.0/119,192.168.2.252, record[a,in-unique,CC_22_3D_67_59_1E.local.]=120.0/119,10.220.130.159, record[quada,in-unique,CC_22_3D_67_59_1E.local.]=120.0/119,fe80::3751:89fe:4fca:652d]}> (414 bytes) as [b'\x00\x00\x84\x00\x00\x00\x00\x06\x00\x00\x00\x00\x04_hap\x04_tcp\x05local\x00\x00\x0c\x00\x01\x00\x00\x11\x94\x00%\x13G5 `


192.168.2.252 ist die IP der CCU3

**Comment by SukramJ** [comment]
Da ist aber kein Verbindungsversuch zu sehen.
Was machst du um zu verbinden?
Häng bitte Screenshots an.

**Comment by bonnz-de** [comment]
Gerne

![Bildschirmfoto 2024-11-07 um 20 05 11](https://github.com/user-attachments/assets/0ca538ee-f91b-48b3-8a09-78d189ab6dc3)
![Bildschirmfoto 2024-11-07 um 20 04 56](https://github.com/user-attachments/assets/e2971fe7-a21e-4d89-8edc-a12846195ab6)

**Comment by bonnz-de** [comment]
Das habe ich gerade noch im Log gefunden:

`2024-11-07 19:52:23.921 DEBUG (MainThread) [custom_components.homematicip_local.config_flow] Homematic(IP) Local SSDP discovery SsdpServiceInfo(ssdp_usn='uuid:upnp-BasicDevice-1_0-3014F711A0001F9A498C9E19::upnp:rootdevice',
                ssdp_st='upnp:rootdevice',
                upnp={'UDN': 'uuid:upnp-BasicDevice-1_0-3014F711A0001F9A498C9E19',
                      'UPC': '123456789002',
                      'deviceType': 'urn:schemas-upnp-org:device:Basic:1',
                      'friendlyName': 'HomeMatic Central RaspberryMatic',
                      'manufacturer': 'EQ3',
                      'manufacturerURL': 'http://www.homematic.com',
                      'modelDescription': 'HomeMatic Central '
                                          '3014F711A0001F9A498C9E19',
                      'modelName': 'HomeMatic Central',
                      'presentationURL': None,
                      'serviceList': {'service': {'SCPDURL': None,
                                                  'controlURL': None,
                                                  'eventSubURL': None,
                                                  'serviceId': 'urn:upnp-org:serviceId:dummy1',
                                                  'serviceType': 'urn:schemas-upnp-org:service:dummy:1'}}},
                ssdp_location='http://192.168.2.252/upnp/basic_dev.cgi',
                ssdp_nt=None,
                ssdp_udn='uuid:upnp-BasicDevice-1_0-3014F711A0001F9A498C9E19',
                ssdp_ext='',
                ssdp_server='HomeMatic',
                ssdp_headers={'CACHE-CONTROL': 'max-age=5000', 'EXT': '', 'LOCATION': 'http://192.168.2.252/upnp/basic_dev.cgi', 'SERVER': 'HomeMatic', 'ST': 'upnp:rootdevice', 'USN': 'uuid:upnp-BasicDevice-1_0-3014F711A0001F9A498C9E19::upnp:rootdevice', '_host': '192.168.2.252', '_udn': 'uuid:upnp-BasicDevice-1_0-3014F711A0001F9A498C9E19', '_location_original': 'http://192.168.2.252/upnp/basic_dev.cgi', 'location': 'http://192.168.2.252/upnp/basic_dev.cgi', '_timestamp': datetime.datetime(2024, 11, 7, 19, 51, 9, 312560), '_remote_addr': ('192.168.2.252', 1900), '_port': 1900, '_local_addr': ('0.0.0.0', 0), '_source': <SsdpSource.SEARCH: 'search'>},
                ssdp_all_locations={'http://192.168.2.252/upnp/basic_dev.cgi'},
                x_homeassistant_matching_domains={'homematicip_local'})
`

Einen Fehler lese ich aber trotzdem nicht raus

**Comment by SukramJ** [comment]
Häng doch mal das vollständige Log an. Häppchenweise finde ich nervig.

**Comment by SukramJ** [comment]
Wie hast Du debug aktiviert?

**Comment by bonnz-de** [comment]
So ist das Log Level aktiviert

<img width="458" alt="Bildschirmfoto 2024-11-07 um 20 18 22" src="https://github.com/user-attachments/assets/9e97c48f-c04e-4177-82d6-f4bde021baac">

und hier noch das komplette Log
[home-assistant_2024-11-07T18-54-00.353Z.log](https://github.com/user-attachments/files/17668239/home-assistant_2024-11-07T18-54-00.353Z.log)

**Comment by SukramJ** [comment]
Hast du altes homematic wired oder homematic**ip** wired?

Wenn Du kein homematic wired hast, dann den Haken nicht setzten.

Bitte den Logger ändern, neustart und dann noch mal einen neuen Verbindungsversuch starten.

```
logger:
  default: warn
  logs:
    hahomematic: debug
    custom_components.homematicip_local: debug
```

**Comment by bonnz-de** [comment]
Ich habe tatsächlich "nur" HmIP wired und kein "altes" wired.

Jetzt hat es auch funktioniert, danke Dir für Deine Hilfe! Lag es wirklich nur daran?

**Comment by SukramJ** [comment]
Ja.
