### ISSUE TITLE
Error occurred loading flow for integration homematicip_local: No module named 'hahomematic'

### ISSUE THREAD

**Issue by brightdroid** [SukramJ/hahomematic#1822]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

After installing homematicip_local via HACS and restarting HA (Docker) I get the following error while starting:

> Error occurred loading flow for integration homematicip_local: No module named 'hahomematic'

### What version of HomematicIP (local) has the issue?

1.70.0

### What type of installation are you running?

Home Assistant Container

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.79.6.20241031

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
2024-11-07 17:44:16.657 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration homematicip_local: No module named 'hahomematic'                                                                                       
  File "/config/custom_components/homematicip_local/__init__.py", line 11, in <module>                                                                                                                                                                       
    from hahomematic import __version__ as HAHM_VERSION                                                                                                                                                                                                      
ModuleNotFoundError: No module named 'hahomematic'
```

### Additional information

I found the module in HA `config/deps/` folder, so it got installed by hacs.

**Comment by SukramJ** [comment]
Dublette #1776
