### ISSUE TITLE
mehrere homematicip_local-Konfigurationseinträge mit derselben eindeutigen ID seit HA 2024.11.0

### ISSUE THREAD

**Issue by centertivevier** [SukramJ/hahomematic#1825]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Seit dem Update auf Homeassistant 2024.11.0 bekomme ich folgenden Fehler angezeigt:

Es gibt mehrere homematicip_local-Konfigurationseinträge mit derselben eindeutigen ID.
Die Konfigurationseinträge heißen 'Rapsberrymatic1', 'Rapsberrymatic2'

Ich habe aber selber nur Rapsberrymatic1 in der Liste stehen und konfiguriert. Gibt es hier irgendwo einen toten Eintrag und wenn ja, wo? Ich habe selber nix gefunden um den falschen Eintrag zu entfernen.

### What version of HomematicIP (local) has the issue?

1.7.0

### What was the last working version of HomematicIP (local)?

1.7.0

### What type of installation are you running?

Home Assistant Core

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.79.6.20241031

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [X] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Siehe #1823
