### ISSUE TITLE
FIRE_HA_EVENT_CALLBACK: Unable to call handler: Detected that custom integration 'homematicip_local' calls issue_registry.async_delete

### ISSUE THREAD

**Issue by lordduckstein** [SukramJ/hahomematic#1830]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hello,
I have this in my protocol in Home Assisant. I have request google for the issue, also here an other places to find the solution for this problem.
I didn't know why Home assisant say this is an error, because I see no problems during use

### What version of HomematicIP (local) has the issue?

1.54.0

### What type of installation are you running?

Home Assistant Container

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.79.6.20241031

### What hardware are you running for your system?

Pi3

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
Logger: hahomematic.central
Quelle: /usr/local/lib/python3.12/site-packages/hahomematic/central/__init__.py:1070
Erstmals aufgetreten: 16:59:41 (2682 Vorkommnisse)
Zuletzt protokolliert: 20:43:39

FIRE_HA_EVENT_CALLBACK: Unable to call handler: Detected that custom integration 'homematicip_local' calls issue_registry.async_delete from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#issue_registryasync_delete at custom_components/homematicip_local/control_unit.py, line 356: async_delete_issue(. Please report it to the author of the 'homematicip_local' custom integration.
```

**Comment by SukramJ** [comment]
> What version of HomematicIP (local) has the issue?
1.54.0
I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
I am aware that an integration that was installed via HACS also needs to be updated via HACS
I am running the latest version of the custom_component (and Home Assistant)

Thank you for taking care that you installed the latest [version](https://github.com/danielperna84/custom_homematic/releases)!!

**Comment by lordduckstein** [comment]
Sorry,

I am a Honk!

Your are right I have not the higher Version...

Im so sorry

Thanks 
lordi
