### ISSUE TITLE
HM-CC-RT-DN valve information missing

### ISSUE THREAD

**Issue by kabakakao** [SukramJ/hahomematic#184]
Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
0.22.

**Home Assistant version (if applicable):**
2021.12.7

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, ...): Docker Container
- OS (Original, RaspberryMatic, debmatic/...): piVCCU3
- Version: 3.61.6

**Problem-relevant configuration:**

Do you use tls? No
Do you use callback? No
Do you use username and password? Yes
Which interfaces do you use? ??

**Describe the bug**
I do not geht valve information of the Therrmostat. With the "old" integration it worked

**Expected behavior**
Get an attribute with the valve information in %

**Comment by danielperna84** [comment]
You're right, it's missing fore mine as well. [This](https://github.com/danielperna84/pydevccu/blob/712fcbcb9be2e53d09a3b25ceef779146fb0da83/pydevccu/paramset_descriptions/HM-CC-RT-DN.json#L2493) is the parameter in the paramset.

**Comment by SukramJ** [comment]
VALVE_STATE on channel 4?

**Comment by danielperna84** [comment]
Yes. In pyhomematic it's added as an attribute [here](https://github.com/danielperna84/pyhomematic/blob/899a28c6036ea799cfb5513a65e37135556c60a7/pyhomematic/devicetypes/thermostats.py#L140). But depending on the device the channel might be different. MAX devices seem to have it on channel 1.

**Comment by kabakakao** [comment]
That was fast.
Thank you for your good work.

**Comment by SukramJ** [comment]
Thanks. Will be released in the next days.

**Comment by SukramJ** [comment]
Fixed with release 0.22.1
