### ISSUE TITLE
Es werden diverse Homematic Devices in der HA Übersicht nicht angezeigt

### ISSUE THREAD

**Issue by kmbach** [SukramJ/hahomematic#1844]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hallo,
ich habe gerade mit HomeAssistant begonnen. Die Integration der Homematic funktioniert soweit. Alle Geräte sind in HA vorhanden. Leider werden einige Geräte jedoch nicht in der Übersicht/Dashboard angezeigt

2x HM-RC-4-3,  - 4 Tasten Fernbedienung
1x HM-RC-19 - 19 Tasten Fernbedienung
1x HM-PB-2-WM55 - 2fach Wandtaster
1x HM-RC-P1 - Funk Paniktaster (Homebrey)
3x HB-LC-Bl1-RM3 - Rollladensteuerung (Homebrey - eigener Typ)
2x HB-LC-Bl1-RM2 - Rollladensteuerung (Homebrey - eigener Typ)
1x HM-OU-LED16 - 16LED - Statusanzeige

Was ist erforderlich um die Geräte in der Übersicht anzuzeigen?

### What version of HomematicIP (local) has the issue?

aktueller Download

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3 77.7

### What hardware are you running for your system?

VM auf Synology NAS für HA

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Additional information

Leider kenne ich noch nicht alle Zusammenhänge genau um alle Fragen exakt beantworten zu können. Die RaspberryMatik läuft als Container auf einem Rasperry Pi 4.

**Comment by SukramJ** [comment]
> aktueller Download

Welche Version verwendest Du?

Werden die Geräte in der Geräteübersicht der Integration angezeigt?  Das Dashboard interessiert mich nicht.

Bitte noch die Diagnose-Informationen und das HA Log anhängen.

**Comment by kmbach** [comment]
Sorry, die Version ist 1.70.0

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.11.1",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.4",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Amsterdam",
    "os_name": "Linux",
    "os_version": "6.6.54-haos",
    "supervisor": "2024.11.2",
    "host_os": "Home Assistant OS 13.2",
    "docker_version": "27.2.0",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "homematicip_local": {
      "documentation": "https://github.com/danielperna84/custom_homematic",
      "version": "1.70.0",
      "requirements": [
        "hahomematic==2024.11.0"
      ]
    },
    "hacs": {
      "documentation": "https://hacs.xyz/docs/configuration/start",
      "version": "2.0.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "huawei_solar": {
      "documentation": "https://github.com/wlcrs/huawei_solar/wiki",
      "version": "1.4.1",
      "requirements": [
        "huawei-solar==2.3.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "homematicip_local",
    "name": "Homematic(IP) Local",
    "codeowners": [
      "danielperna84",
      "SukramJ"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/danielperna84/custom_homematic",
    "homekit": {},
    "integration_type": "hub",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/danielperna84/hahomematic/issues",
    "loggers": [
      "hahomematic"
    ],
    "requirements": [
      "hahomematic==2024.11.0"
    ],
    "ssdp": [
      {
        "manufacturer": "EQ3",
        "manufacturerURL": "http://www.homematic.com"
      }
    ],
    "version": "1.70.0",
    "zeroconf": [],
    "is_built_in": false,
    "overwrites_built_in": false
  },
  "setup_times": {
    "null": {
      "setup": 5.241300095804036e-05
    },
    "01JAX1Z2QB7NBDMXWA3W6GGY10": {
      "wait_import_platforms": -0.09725834299752023,
      "wait_base_component": -0.0008023450063774362,
      "config_entry_setup": 4.403700071998173
    }
  },
  "data": {
    "config": {
      "created_at": "2024-10-23T16:04:42.347987+00:00",
      "data": {
        "advanced_config": {},
        "host": "192.168.13.20",
        "instance_name": "ccu",
        "interface": {
          "BidCos-RF": {
            "port": 2001
          },
          "HmIP-RF": {
            "port": 2010
          }
        },
        "password": "**REDACTED**",
        "tls": false,
        "username": "**REDACTED**",
        "verify_tls": false
      },
      "discovery_keys": {
        "ssdp": [
          {
            "__type": "<class 'homeassistant.helpers.discovery_flow.DiscoveryKey'>",
            "repr": "DiscoveryKey(domain='ssdp', key='uuid:upnp-BasicDevice-1_0-3014F711A061A7D3C9962755', version=1)"
          }
        ]
      },
      "disabled_by": null,
      "domain": "homematicip_local",
      "entry_id": "01JAX1Z2QB7NBDMXWA3W6GGY10",
      "minor_version": 1,
      "modified_at": "2024-10-23T16:04:42.347993+00:00",
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "ssdp",
      "title": "ccu",
      "unique_id": "D3C9962755",
      "version": 7
    },
    "platform_stats": {
      "binary_sensor": 42,
      "cover": 5,
      "hub_binary_sensor": 38,
      "hub_button": 168,
      "hub_sensor": 65,
      "number": 6,
      "select": 16,
      "sensor": 19,
      "switch": 27,
      "update": 12
    },
    "devices": [
      "HB-LC-Bl1-RM2",
      "HB-LC-Bl1-RM3",
      "HB-UNI-Sen-DUMMY-BEACON-V2",
      "HM-ES-PMSw1-DR",
      "HM-ES-PMSw1-Pl",
      "HM-ES-TX-WM",
      "HM-LC-Bl1-FM",
      "HM-LC-Bl1PBU-FM",
      "HM-LC-Sw1-FM",
      "HM-LC-Sw1-Pl",
      "HM-LC-Sw4-WM",
      "HM-OU-LED16",
      "HM-PB-2-WM55",
      "HM-RC-19-B",
      "HM-RC-4-2",
      "HM-RC-4-3",
      "HM-RC-P1",
      "HM-RCV-50",
      "HM-SCI-3-FM",
      "HM-Sec-SC",
      "HM-Sec-SC-2",
      "HM-Sec-SCo",
      "HmIP-RCV-50",
      "ZEL STG RM FFK"
    ],
    "system_information": {
      "available_interfaces": [
        "CUxD",
        "BidCos-RF",
        "VirtualDevices",
        "HmIP-RF"
      ],
      "auth_enabled": false,
      "https_redirect_enabled": false,
      "serial": "**REDACTED**"
    }
  }
}

Die Geräte werden in der Integration angezeigt, deren Aktivitäten werden auch ordnungsgemäss protokolliert.

Was macht dann bitte die Verbindung zur Übersicht, dem standard Dashboard? Wer könnte mir da helfen?

**Comment by SukramJ** [comment]
> Die Geräte werden in der Integration angezeigt, deren Aktivitäten werden auch ordnungsgemäss protokolliert.

Dann arbeitet die Integration erwartungsgemäss.

> Wer könnte mir da helfen?

Ich würde es mal im [community forum](https://community.home-assistant.io/) oder bei [simon42](https://community.simon42.com/)versuchen.

Sinnvoller, als auf das automatisch generierte Dashboard zu setzen, wäre ein [Dashboard](https://next.home-assistant.io/dashboards) selber zu konfigurieren.

**Comment by kmbach** [comment]
sorry, dass ich mich doch noch einmal zu dem Problem melde.
Ich habe nun versucht eins der Problemgeräte in ein eigenes Dashboard zu
bringen. Dabei scheitere ich daran, dass für die HomeBrey
Rollladensteuerungen keine Entität "cover.", so wie bei den anderen RL, im
Integrator existiert.


Am 16. November 2024 14:21:13 schrieb SukramJ ***@***.***>:

**Comment by SukramJ** [comment]
> keine Entität "cover."

Das stimmt.
Bei den ganzen Homebrew-Geräten, die vielleicht von 1,2 Leuten verwendet werden, hab ich eigentlich keine Lust mehr, da Aufwand reinzustecken. 
Du kannst mal die Gerätedefinitionen wie [hier](https://github.com/danielperna84/custom_homematic#homematicip_localexport_device_definition) beschrieben erzeugen und hier hochladen. Ich schau mir das mal an, und sofern der Homematic Standard eingehalten wird, werde ich die hier aufnehmen. Wenn da aber wieder mal eine Sonderlocke gebaut wurde, dann werde ich da nichts machen.
Alternativ kannst du dir selber ein [Cover-Template](https://www.home-assistant.io/integrations/cover.template/) erstellen. Die dafür benötigten Entitäten sollten dir alle angezeigt werden.
