### ISSUE TITLE
Missing trigger for HmIP-SRH (Homematic IP Fenstergriffsensor)

### ISSUE THREAD

**Issue by therosss** [SukramJ/hahomematic#1857]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [x] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Not sure if this is HA or Plugin related:

I am missing trigger entries (state) for my HmIP-SRH.
Usecase: I want to read the state of the window sensor in order to complete one of my automations.

Issue: When selecting the entity in the automation editor, I can not find the state of the sensor. Only battery level and so:
![image](https://github.com/user-attachments/assets/64e76b1f-86c4-4751-b405-8ccd648919cd)

Additional info: When opening the device list information, I can see the desired states when the last were changed in the logbook:
![image](https://github.com/user-attachments/assets/6ea051ad-b2d8-4646-a03b-a433086d836f)

### What version of HomematicIP (local) has the issue?

1.70.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.79.6

### What hardware are you running for your system?

Proxmox on Intel n100 with 32gb DDR5 Ram

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
This integration does not provide any triggers except for KEY_PRESS events!
All other triggers are provided by HA core.

Use an entity as trigger instead.
