### ISSUE TITLE
Devices not reachable after 1.71 update

### ISSUE THREAD

**Issue by opu1000** [SukramJ/hahomematic#1867]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hello, I have installed the version 1.71 of HomematicIP (Local) in HA. Now I can not reach the devices over HA.
What can I do ?
Regards OPU

### What version of HomematicIP (local) has the issue?

1.71

### What was the last working version of HomematicIP (local)?

1.70.0

### What type of installation are you running?

Home Assistant OS
 Core 2024.11.2
Supervisor 2024.11.3
Operating System 13.2
Frontend 20241106.2

### What type of installation are you running for your homematic backend?

RaspberryMatic Addon

### Which version of your homematic backend are you running?

  3.79.6.20241031

### What hardware are you running for your system?

Raspberry Pi 4

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [x ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
> What can I do ?

Keine Logs? 
Keine Diagnostics information?
Du kannst dir gerne ein wenig Mühe geben beim Ausfüllen des Issue!

**Comment by opu1000** [comment]
Sag mir welche Logs du brauchst und wo ich die herbekomme. Ich bin gerade nervös, weil nix mehr geht!

**Comment by SukramJ** [comment]
>Sag mir welche Logs du brauchst und wo ich dir herbekomme. Ich bin gerade nervös, weil nix mehr geht

Wenn man ein Issue erstellt steht das dort alles beschrieben! Soll ich dir jetzt alles noch mal schreiben?
Ich will natürlich das HA Protokoll. Einstellungen -> System -> Protokolle

**Comment by opu1000** [comment]
START_CENTRAL
Logger: custom_components.homematicip_local.control_unit
Quelle: custom_components/homematicip_local/control_unit.py:131
Integration: Homematic(IP) Local ([Dokumentation](https://github.com/danielperna84/custom_homematic), [Probleme](https://github.com/danielperna84/hahomematic/issues))
Erstmals aufgetreten: 19:33:33 (1 Vorkommnisse)
Zuletzt protokolliert: 19:33:33
START_CENTRAL: Failed to start central unit for RapsberryMatic



HIER für Homematic local:

Logger: hahomematic.client
Quelle: custom_components/homematicip_local/control_unit.py:128
Integration: Homematic(IP) Local ([Dokumentation](https://github.com/danielperna84/custom_homematic), [Probleme](https://github.com/danielperna84/hahomematic/issues))
Erstmals aufgetreten: 19:33:33 (1 Vorkommnisse)
Zuletzt protokolliert: 19:33:33
unexpected control character in string: line 1 column 31976 (char 31975)


We bekomme ich die alte version wieder zurück, ohne das komplette systembackup einspielen zu müssen

**Comment by SukramJ** [comment]
Bitte häng das vollständige Log / unveränderte Log an!

**Comment by opu1000** [comment]
[home-assistant_2024-11-20T19-18-28.907Z.log](https://github.com/user-attachments/files/17835683/home-assistant_2024-11-20T19-18-28.907Z.log)

**Comment by SukramJ** [comment]
Bitte mal `Debug Protokoll aktivieren` auf der Integration klicken und HA neustarten.
Danach bitte das neue Log hier anhängen.

**Comment by opu1000** [comment]
wo macht man das genau, welche Integration ?

**Comment by SukramJ** [comment]
Die Integration heisst Homematic(IP) Local und du findest die unter Einstellungen -> Geräte & Dienste

**Comment by opu1000** [comment]
ich hatte es gefunden:
[home-assistant_2024-11-20T19-34-54.671Z.log](https://github.com/user-attachments/files/17835887/home-assistant_2024-11-20T19-34-54.671Z.log)

**Comment by SukramJ** [comment]
Es sieht so aus, als ob deine CCU für das BidCos Interface keine valides JSON zurückliefert, und dadurch der Start abbricht.
Bei ähnlichen Problemen war bisher etwas mit der Gerätebeschreibung in der CCU defekt.
Hier sieht es so aus als ob `Device.listAllDetail` der fehlerhaften Wert zurückliefert.

Du kannst versuchen in HACS auf eine ältere Version zurück zu wechseln.
Wenn die ältere Version läuft dann bitte dort noch mal mit aktivierten Debug Protokoll die Integration neu starten, und das Log wieder hier anhängen

**Comment by opu1000** [comment]
wie komm ich an den alte version ran ?

**Comment by SukramJ** [comment]
Über HACS -> Homematic(IP) Local -> drei Punkte oben rechts -> erneut herunterladen -> Version auswählen -> neu starten

**Comment by SukramJ** [comment]
Bitte ergänze noch die Informationen, die Du oben im Issue beim Erstellen weggelassen hast.

**Comment by opu1000** [comment]
Ich spiele jetzt erstmal da sletzte HA Backup ein, damit erstmal wieder alles läuft. Schaust du im Hintergrund nach, woran es liegen kann. Ich denke mal, dass die Geräteliste vom CCU addon kommt, oder.

Ich schau oben mal was, moch fehlt.

**Comment by opu1000** [comment]
Hallo, ich hab das Backup eingespielt, hier das logfile:

[Uploading home-assistant_homematicip_local_2024-11-20T20-16-21.703Z.log…]()

Ich würde gerne die letzte Version irgendwann zum filegen bringen, meinst du, dass bekommen wir hin? 
Aber die Kuh ista erstmal vom Eis, geht wieder, mit 1.70.

**Comment by opu1000** [comment]
Hab eben 1.72 Pre - release eingespielt, es scheint zu laufen, danke !!!!!!!!!!!!
