### ISSUE TITLE
Entity name is not transferred correctly

### ISSUE THREAD

**Issue by mano87** [SukramJ/hahomematic#1868]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

When adding the devices in Home Assistant, I noticed that the name of the two buttons was not correctly adopted for all HmIP-BROLL-2. The entities of the two buttons of the BROLL-2 all start with event.none...
For all other BROLLs, the device name is adopted correctly for the entity. For example event.bad_eg_rolladen_taste_oben

What is the reason for this?

![grafik](https://github.com/user-attachments/assets/900bb4fd-7730-4b73-a84a-0aa5efd6f350)

![grafik](https://github.com/user-attachments/assets/43906f6c-8fb3-4353-858b-5fab53ccb3fb)

### What version of HomematicIP (local) has the issue?

1.69.0

### What was the last working version of HomematicIP (local)?

1.69.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.79.6

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
>  I am running the latest version of the custom_component (and Home Assistant)

Please update to the latest version.

**Comment by SukramJ** [comment]
Since which version do you use the integration?
I would delete the device from HA and then reload the integration or restart HA.

**Comment by mano87** [comment]
It looks much better with version 1.72.0. Unfortunately, it is not known when the problem started.

**Comment by SukramJ** [comment]
Nothing has changed for a long time

**Comment by SukramJ** [comment]
Entity ID generation is a task of Homeassistant and not of this integration.
This integration provides the name and HA created the entity_id from it.

**Comment by mano87** [comment]
Okay, but I haven't changed anything in HA's version.
