### ISSUE TITLE
Gaszaehler does not work 

### ISSUE THREAD

**Issue by vlink78** [SukramJ/hahomematic#1873]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Unfortunately the new Gaszaehler is not working correctly. I did not get the data what I see in the CCU3. Type is HMIP-ESI
Thank you !

### What version of HomematicIP (local) has the issue?

1.70.0

### What was the last working version of HomematicIP (local)?

1.70.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Bitte verschwende meine Zeit nicht  mit so einem lustlosem erstelltem Ticket!
Du hast ein Problem, und benötigst Hilfe, also gib dir auch Mühe deinen Fehler zu beschreiben, z. Bsp. mit Screenshots, worin das Problem besteht, oder was erwartet wäre.

Ich schliesse das Tickets, da ich veraltete Versionen nicht supporte, aber das wird dir beim abhaken der obigen Checkboxen sicher aufgefallen sein
