### ISSUE TITLE
Problem mit HM IP Gaszähler

### ISSUE THREAD

**Issue by vlink78** [SukramJ/hahomematic#1875]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Entschuldigung für das letzte Ticket. War in Eile. Aber Du hast Recht, das wir nicht hilfreich.

Folgendes Problem.
Ich habe eine recht große HM IP / Wired Installation und nutze diese Integration. Klappt auch super.
Einzigst für den recht neuen Gaszähler Typ HmIP-ESI kommen keine bzw. keine richtigen Werte an.

Screenshot von der CCU3 mit den aktuellen Werten vom Zähler:
![2024-11-22 21_11_33-HomeMatic WebUI](https://github.com/user-attachments/assets/b7e03865-66d6-42c1-bac5-0032d38e0689)

Aktueller Zählerstand 1726.829 m³

In HA :
![2024-11-22 21_12_58-Entwicklerwerkzeuge – Home Assistant](https://github.com/user-attachments/assets/1683c292-e843-4aad-b890-e42c36c33dd1)

hier kommt nur ein Wert an 'Gas-Volumen' mit einem Wert von aktuell 11326.12
Diesen gibt es sogar nicht in der CCU3
Mir ist der aktuelle Zählerstand und der Verbrauch von heute wichtig.

Ich kann gerne bei der Fehlersuche unterstützen wenn Du weitere Daten benötigst.

Vielen Dank!!
Gruß
Volker

### What version of HomematicIP (local) has the issue?

1.72.0

### What was the last working version of HomematicIP (local)?

1.72.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.79.6

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Geht doch.

Die HA Bilder sind sehr unscharf. Welche Einheit steht bei Gas Volumen?

**Comment by vlink78** [comment]
Sorry nochmal !
Ft3 steht da
Weiß auch nicht warum sich mein HA öfters mal umstellt. Habe temp auch immer mal in Fahrenheit. Stelle dann wieder auf F zurück und wieder auf Celcius dann passt es wieder. Muss dazu sagen bin neu bei HA - steige vom ioBroker um :) 
Zum Gaszähler - leider fehlt der Zählerstand ganz 
![IMG_1874](https://github.com/user-attachments/assets/7b5438ea-52bc-4856-8a31-cf00b27d9bb0)

**Comment by SukramJ** [comment]
Irgendwas stimmt mit deiner HA Konfiguration nicht.

Die Integration liefert für GAS_VOLUME m³ ale Einheit.
Entweder hast Du am Sensor die Einheit geändert, oder Du hast als Land nicht Deutschland eingestellt.

**Comment by vlink78** [comment]
Habe mal ein paar Screenshots gemacht 
Passt eigentlich alles oder ?

![IMG_1875](https://github.com/user-attachments/assets/23a04747-332c-4600-9708-cbfe216b1117)
![IMG_1876](https://github.com/user-attachments/assets/328707a5-6159-40e2-a16a-f04c401b141f)
![IMG_1877](https://github.com/user-attachments/assets/5d608c36-f563-4129-92db-61fa74ea86fb)

**Comment by vlink78** [comment]
Habe gerade mal auf Fahrenheit umgestellt - danach wieder auf celcius. Jetzt passt zwar die Einheit - aber der eine angezeigte Wert passt nicht was in der ccu3 steht 
![Uploading IMG_1878.png…]()

**Comment by SukramJ** [comment]
Wie sieht es denn aus, wenn du den Sensor unter Geräte/Einstellungen öffnest?
Lösch am besten das Gerät noch mal aus HA und starte HA neu.

**Comment by SukramJ** [comment]
Ändert sich der Wert in HA?

**Comment by vlink78** [comment]
Du meinst nur den gaszähler löschen aus der Integration ? Oder komplett HM Integration löschen ? Sorry bin neu - weiß gar nicht wie ich nur das Gerät gaszähler löschen soll

**Comment by SukramJ** [comment]
Erst mal wichtig: Ändert sich der Wert in HA?

> Du meinst nur den gaszähler löschen aus der Integration ?

In Geräte/Einstellungen das Gerät öffnen.
Auf der Karte Geräteinformationen gibt es unter rechts 3 Punkte.
Darauf klicken und dann löschen.

**Comment by vlink78** [comment]
Cool Danke.
Habe das Gerät gelöscht , danach HA neu gestartet -  gerät wieder da - aber gleiches Problem wieder 

![IMG_1879](https://github.com/user-attachments/assets/50468cd6-5cc0-4997-84af-df26cd1c4a30)

**Comment by SukramJ** [comment]
3. Versuch: Ändert sich der Wert in HA?

**Comment by vlink78** [comment]
Sorry.  Nein hat sich bisher nicht geändert. Muss ich aber beobachten da aktuell mein Gas verbraucht wird

**Comment by vlink78** [comment]
Also Gas fließt gerade - durchfluss wert ändert sich auch - siehe Fotos einmal von CCU3 Andere von HA
Werte Gas Volumen passen nur nicht zusammen 

![IMG_1880](https://github.com/user-attachments/assets/cd6b9bde-719e-4728-a940-a8a02b92ba25)
![IMG_1881](https://github.com/user-attachments/assets/5ad37265-5860-44d4-9767-c0bd65081847)

**Comment by SukramJ** [comment]
Wenn der Wert sich ändert, dann empfängt die Integration Daten von der CCU.
Die Integration funktioniert also richtig.
Warum der empfangene Wert nicht in der CCU UI zu sehen ist, kann ich nicht beantworten.
Aus Sicht der Integration kann das Ticket geschlossen werden.

**Comment by vlink78** [comment]
Das ist in Ordnung 
Integration scheint dann richtig zu laufen 
Muss ich noch herausfinden warum der Wert anders ist und warum sich mein HA immer mal auf Fahrenheit umstellt.
Vielen Dank !!

**Comment by Baxxy13** [comment]
Der "Zählerstand" (CCU) ist eine systeminterne Systemvariable (svGasCounter_xxx).
Wenn der SysVar-Scan aktiv ist sollte die als (deaktivierte) Sensor-Entität (HA) verfügbar sein.

"Gas-Volumen" (HA) zeigt den Zählerstand des Gerätes. Der ist aber relativ nutzlos und deshalb wird der in der CCU erst gar nicht angezeigt.
Den könntest du aber für's HA Energy Dashboard nehmen um den Verbrauch im Blick zu haben. 
Mit der SysVar geht das auch, die muss man aber erst "customizen". 

An "heute", "gestern" usw. (CCU) kommt man nicht so ohne weiteres ran, das sind Metadaten die beim Kanal gespeichert sind.
Braucht man aber auch nicht wenn man den Gaszähler oder die SysVar in's HA Energy Dashboard aufnimmt.

**Comment by SukramJ** [comment]
@Baxxy13 
Vielen Dank für die Info. Wieder was gelernt.
