### ISSUE TITLE
Window sensor state wrong after becoming available again

### ISSUE THREAD

**Issue by ZTHawk** [SukramJ/hahomematic#1884]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I have a HmIP-SWDO-I and yesterday I encountered a weird issue. The device became "unavailable" in HA. After 3-5 min it was available again but with the state "open". The window was still closed and the state in RaspberryMatic was also "closed".
The state in HA did not get updated to the correct value, even after some minutes.

After opening the window (to correctly change state to "open") and then closing the window (to correctly change to "closed"), the state in HA updated correctly.

I encountered this issue yesterday for the first time with two sensors.

### What version of HomematicIP (local) has the issue?

1.72.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.79.6.20241122

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [X] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
> What version of HomematicIP (local) has the issue?
1.1.10

Wow deine Version ist 3 Jahre alt.
Bitte die Version aktualisieren!

**Comment by ZTHawk** [comment]
Sry falschen Wert kopiert. Ist korrigiert. Meine version ist 1.72.0

Ist gerade auch mit einem Lichtschalter "HmIP-BSL" der Fall. In RM ist er aus, aber in HA ist er an.

**Comment by SukramJ** [comment]
Solange die CCU keinen geänderten Wert sendet, ist ggf. nur ein alter Wert vorhanden.

**Comment by ZTHawk** [comment]
Es ist gerade wieder passiert. In RA + HA waren die Fensterkontakte auf "closed". Fensterkontakt wurde "unavailable" und nachdem er wieder vorhanden ist hat er in HA den Status "open". In RA weiterhin "closed".

**Comment by ZTHawk** [comment]
Kannst du das ticket wieder öffnen oder soll ich ein neues erstellen?
Ich habe debug logs die vielleicht helfen (wie kann ich dir diese direkt zukommen lassen?).
Ich konnte dieses verhalten erzwingen indem ich RM neugestartet habe.

**Comment by ZTHawk** [comment]
[home-assistant_homematicip_local_2024-11-30T11-11-13.732Z_reduced.log.zip](https://github.com/user-attachments/files/17965294/home-assistant_homematicip_local_2024-11-30T11-11-13.732Z_reduced.log.zip)

Fensterkontakt "Fensterkontakt BadPrivat rechts State"

HA log:
```
was closed - 12:03:23 - 1 hour ago
was opened - 12:01:55 - 1 hour ago
became unavailable - 11:57:15 - 1 hour ago
was closed - 11:31:18 - 1 hour ago
was opened - 11:11:28 - 2 hours ago
became unavailable - 10:50:48 - 2 hours ago
```

In den oben gelisteten Zeiten (von HA) wurde das Fenster nicht geöffnet (war die ganze Zeit zu). In RM war der Status die ganze Zeit zu.
Um ~11:57 wurde RM neugestartet.

**Comment by SukramJ** [comment]
Wichtig ist welchen Wert das Attribut [`value_state`](https://github.com/danielperna84/custom_homematic#noteworthy-about-entity-states) der Entität hat.

**Comment by ZTHawk** [comment]
wenn ich es schaffe wieder nachzustellen, dann guck ich welchen wert die entity hat. Aktuell ist alles ok mit wert "valid".

**Comment by SukramJ** [comment]
Dann werde ich das Ticket erst mal schliessen.
Ich denke der `offen` Wert kommt von HA, und dann sollte da restored als `value_state` stehen.

**Comment by ZTHawk** [comment]
> Dann werde ich das Ticket erst mal schliessen. Ich denke der `offen` Wert kommt von HA, und dann sollte da restored als `value_state` stehen.

Heißt es, dass "restored" bedeutet:
1. HA macht restart
2. ein Wert für eine Entity wird gespeichert
3. Zwischenzeitlich kann sich nucht der Wert (state) ändern
4. Wenn ein "restore" passiert, dann wird der wert von 2. genommen?

Wie kann ein Wert von:
unavailable -> opened -> closed -> unavailable -> opened -> closed
springen ohne dass es ein event von RM gab?

**Comment by SukramJ** [comment]
> Wie kann ein Wert von:
unavailable -> opened -> closed -> unavailable -> opened -> closed
springen ohne dass es ein event von RM gab?

Default Werte ?


Wenn die CCU neu gestartet wurde hat die CCU nach dem Neustart **keine** Daten, d.h. der CCU Cache ist leer.
Durch den CCU Start verliert die Integration die Verbindung, versucht einen Neustart, und nach dem Nestart werden die Daten von der CCU gelesen, aber die sind leer, bzw. haben default Werte.

**Comment by ZTHawk** [comment]
Sorry dass ich etwas verbissen bin, aber ich möchte das Verhalten verstehen. Diese "Default Werte" machen für mich keinen Sinn.

Nach einem neustart von RM waren die Werte in "Status und Bedienung" > "Geräte" auf geschlossen. Trotzdem sprang in HA der Wert erst auf "offen".
Wenn RM keinen Wert zurückgibt, dann sollte in HA der letzte bekannte Wert genommen werden. Dies war "geschlossen".

**Comment by SukramJ** [comment]
> Sorry dass ich etwas verbissen bin, aber ich möchte das Verhalten verstehen. Diese "Default Werte" machen für mich keinen Sinn.

Solange du mir nicht den value_state deiner Entitäten lieferst, ist das rum-theoretisiere für mich reine Zeitverschwendung!

> Nach einem neustart von RM waren die Werte in "Status und Bedienung" > "Geräte" auf geschlossen. Trotzdem sprang in HA der Wert erst auf "offen".

Die UI interessiert mich nicht! Die Werte werden über die APIs abgerufen. Wenn dort kein Wert geliefert werden kann, dann nimmt die Integration den default Wert, und der ist beim SWDO State `closed`. 
Wenn aber ein Wert abrufbar ist, dann wird primär dieser genommen, ansonsten der von HA gespeicherte (restored) und dann erst dann der default Wert der Entität.

> Wenn RM keinen Wert zurückgibt, dann sollte in HA der letzte bekannte Wert genommen werden. Dies war "geschlossen".

Hört sich richtig an. Aber ohne `value_state` kann man nicht sagen, ob dein HA richtig gespeichert hat.
