### ISSUE TITLE
Error "No primary interface (HmIP-RF, BidCos-RF) defined" starting from version 1.71.0

### ISSUE THREAD

**Issue by chillymattster** [SukramJ/hahomematic#1894]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hi,
first of all, many thanks for the great and continous work you are doing!

I used HomematicIP (local) for several years now and it has been working great so far. Unfortunately I encounter a critical error starting with the versions 1.71.0 and 1.72.0. Last working version for me is 1.70.0.

The integration doesn't start any more, all entities are unavailable and it is not even possible to configure the integration any more. The integration shows a message like `Setup error. Check protocolls` (translated by myself).
By clicking on "Configure" there is just an error message telling
```
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble. 
```

Switching back to 1.70.0 solves the problem, everything is working again as expected.

The primary error message from logs seems to be
```
No primary interface (HmIP-RF, BidCos-RF) defined
```
My setup with Raspberrymatic doesn't involve any RF devices. I'm just using plain Homematic Wired devices with HMW-LGW which are usable directly from Raspberrymatic without any problems.

Any help is greatly appreciated and if I should contribute more information, please let me know.

### What version of HomematicIP (local) has the issue?

1.71.0, 1.72.0

### What was the last working version of HomematicIP (local)?

1.70.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic HA-Addon

### Which version of your homematic backend are you running?

3.79.6.20241122

### What hardware are you running for your system?

Intel NUC5, KVM/qemu VM

### Which config details do you use

- [X] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [X] BidCos-Wired (HM-Wired)

### Diagnostics information (no logs here)

[home-assistant_homematicip_local_2024-12-05T09-47-25.929Z.log](https://github.com/user-attachments/files/18021107/home-assistant_homematicip_local_2024-12-05T09-47-25.929Z.log)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
Same as in the uploaded file
```

**Comment by SukramJ** [comment]
Please enable Bidcos as additional interface

**Comment by chillymattster** [comment]
Hi @SukramJ,
many thanks for taking care so fast :smiley: 
Is there any documentation or do you have a hint for me on how to include to fix in my installation?
I'm not that experienced and unfortunately wasn't able to find a way to test the fix.

**Comment by SukramJ** [comment]
Just wait for the next Release.
