### ISSUE TITLE
The valve position of the HmIP-FALMOT-C12 is not displayed 

### ISSUE THREAD

**Issue by TobiasKarge** [SukramJ/hahomematic#1897]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Since the last CCU3 firmware update, the valve position of the HmIP-FALMOT-C12 is not displayed in Home Assistant. The status is not available.

### What version of HomematicIP (local) has the issue?

1.73.0

### What was the last working version of HomematicIP (local)?

1.67.x

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.79.6

### What hardware are you running for your system?

VM

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

## System Information

version | core-2024.12.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.0
os_name | Linux
os_version | 6.6.63-haos
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 14.0
-- | --
update_channel | stable
supervisor_version | supervisor-2024.11.4
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 30.8 GB
disk_used | 13.0 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.3.2), File editor (5.8.0), Terminal & SSH (9.15.0), Studio Code Server (5.17.3), Mosquitto broker (6.4.1), ESPHome Device Compiler (2024.11.3), eWeLink Smart Home (1.4.3), TasmoAdmin (0.31.0)

</details>

### Additional information

HmIP-FALMOT-C12 Firmware: 1.6.2

**Comment by SukramJ** [comment]
There is no version 2.0.1. Current version is 1.73.0

Please post a screenshot of the Falmot device in HA. 
Maybe you simple need to enable the number entity.

**Comment by TobiasKarge** [comment]
Sorry 2.0.1 is the Version of HACS. The Version from HomematicIP (local) is 1.73.0

**Comment by SukramJ** [comment]
> Please post a screenshot of the Falmot device in HA.

Still needed

**Comment by TobiasKarge** [comment]
The issue comes with the last Firmware Update from the HmIP-FALMOT-C12

**Comment by TobiasKarge** [comment]
I updated the Information. I used the Version 1.67.x and after the issue comes up i make the update to 1.73.0 but the issue is still there

**Comment by SukramJ** [comment]
As already discussed here:
#1611
#1682

The firmware adds new features to the falmot. The datapoint is not editable and switches from sensor to number. Delete the old sensor.

This is not an issue with this integration.

**Comment by TobiasKarge** [comment]
Danke für deine Hilfe
