### ISSUE TITLE
HM-LC-Sw4-DR nicht verfügbar

### ISSUE THREAD

**Issue by stereotone** [SukramJ/hahomematic#1900]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hi,
erstmal vielen Dank für die super Integration. Soweit läuft alles sehr gut und alle Geräte wurden in HA  übernommen, jedoch macht ein Gerät Probleme: HM-LC-Sw4-DR

Wenn ich das Gerät schalten möchte passiert nichts, und im Dashboard steht immer : "nicht verfügbar" in der Kachel. 
Muss bei diesem Gerät irgendwas zusätzlich eingerichtet werden ?
Alle anderen Geräte funktionieren einwandfrei, und auch der HM-LC-Sw4-DR lässt sich über die CCU oder die TinyMatic schalten.

LG

### What version of HomematicIP (local) has the issue?

1.73.0

### What type of installation are you running?

Home Assistant Core

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.79.6.20241031

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information (no logs here)

[config_entry-homematicip_local-01JEKKASCJBGB98W4XY0RXA193.json](https://github.com/user-attachments/files/18053621/config_entry-homematicip_local-01JEKKASCJBGB98W4XY0RXA193.json)

**Comment by SukramJ** [comment]
Die Nichterreichbarkeit wird von der CCU gemeldet.

In der [Doku](https://github.com/danielperna84/custom_homematic#homematicip-local-documentation) gibt es auch entsprechende Infos:
Bei regelmäßigen Problemen kann man die [Geräteverfügbarkeit erzwingen](https://github.com/danielperna84/custom_homematic#homematicip_localforce_device_availability)

Umgesetzt wird das ganze auch in den Reactivate* [Blueprints](https://github.com/danielperna84/custom_homematic#available-blueprints).

**Comment by stereotone** [comment]
Super, danke für die schnelle Antwort, dann gucke ich mir das mal an.
