### ISSUE TITLE
Fehlender Wert für HmIP-eTRV-2 I9F Thermostat

### ISSUE THREAD

**Issue by Lovntola** [SukramJ/hahomematic#1909]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Das Thermostat HmIP-eTRV-2 I9F hat einen Wert der den Fensterstatus anzeigt:
![image](https://github.com/user-attachments/assets/b6d0068a-9e80-4771-97d4-9db3a03aabc4)
Dieser ist in Home Assistant nicht als Attribute verfügbar.

### What version of HomematicIP (local) has the issue?

Lates Version

### What was the last working version of HomematicIP (local)?

Never

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

core-2024.12.2

### What hardware are you running for your system?

Green

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information (no logs here)

[config_entry-homematicip_local-01J9KDTY3MFSJWDB90TP1RDMKN.json](https://github.com/user-attachments/files/18122211/config_entry-homematicip_local-01J9KDTY3MFSJWDB90TP1RDMKN.json)

### Additional information

Der Fenster Status ist mit keinen Fensterkontakt gekoppelt. 
Das Thermostat ermittelt den Wert anhand von plötzlichen Temperaturabfällen und schaltet für 5 Min die Heizkörper auf 12°C herab. Während dieser Zeit wird der Status Fensteroffen gesetzt.

**Comment by SukramJ** [comment]
Wie bereits beim Erstellen des Issues beschrieben ist das ein Bug-Tracker und kein Support Forum!
Beim aufmerksamen Lesen der Dokumentation ist dir sicherlich der Punkt unignore aufgefallen, über den man fehlende Datenpunkte hinzufügen kann. In deinem Fall könnte `window_state` hilfreich sein.

**Comment by Lovntola** [comment]
Ich habe dies wohl überlesen. 
Entschuldigung vielmals.
Und vielen Dank für deine / eure wirklich ausgezeichnete Arbeit.
