### ISSUE TITLE
Reconnecting sometimes fails for HmIp

### ISSUE THREAD

**Issue by eikowagenknecht** [SukramJ/hahomematic#191]
Sometimes reconnecting fails when the CCU3 is rebooted, then it looks like this:

![image](https://user-images.githubusercontent.com/1475672/149640614-431f34e9-d04e-40f1-80d2-bd9fede729d4.png)

All HmIp devices failed, all Hm devices are there.

**custom_component/hahomematic version (if applicable):**
latest

**Home Assistant version (if applicable):**
latest

**CCU version:**
CCU3 with Raspberrymatic

**To Reproduce**
1. Have HA running
2. Reboot CCU

**Expected behavior**
Reconnection should not result in missing entities.

Restarting the integration fixes this as a workaround, but this should be handled automatically.

In the old integration there was a service homematic.reconnect which could be used to mitigate the problems. This service does not exist in the hahm.* namespace. A better solution would of course be if this wasn't even needed anymore.

**Additional context**
I've had a very similar bug in openHAB, see https://github.com/openhab/openhab-addons/issues/8808#issuecomment-957412370 for the explanation of the addon developer there.

**Comment by SukramJ** [comment]
What happens if you click on reload integration. That should be the equivalent to a service reload.

Please add logs

**Comment by SukramJ** [comment]
Please give me a summary of the attached openhab issue. Why is this relevant?
hahomematic waits until a successful API PING (not icmp ping) do reinit the client.

**Comment by eikowagenknecht** [comment]
> Please give me a summary of the attached openhab issue. Why is this relevant?

It showed the same behaviour after reboot (HmIp not available while Hm is available), so I thought it might be the same issue. The most relevant finding is this:

> This XML-RPC message appears because the CCU returns HTML code containing a message that it is not ready. Would be much better if it would return a correct error state ...

In combination with this:

> hahomematic waits until a successful API PING (not icmp ping) do reinit the client.

it maybe would explain why your API PING succeeds even though the API is not really booted up correctly.

**Comment by eikowagenknecht** [comment]
> What happens if you click on reload integration. That should be the equivalent to a service reload.

Yes, reload integration fixed it.

> Please add logs

Unfortunately after enabling the debug logging the error hasn't occurred for 5 CCU restarts in a row now which speaks for an error that could probably be dependent on the exact timing of the reconnection attempt . I'll keep restarting and hope that it fails again to privide better data :-)

**Comment by SukramJ** [comment]
Yes, i guess the CCU is too slow for the current reconnect.

**Comment by SukramJ** [comment]
Current config is a check interval of 30s, and reconnect immediately if check is successful again.
I will switch to less aggressive solution:
Check every 60s and wait 120s after successful connection check to reconnect.

**Comment by eikowagenknecht** [comment]
I think the "wait 120s after successful connection check" will mostly fix it when there is no other way to reliably check if the service is running correctly yet. The correct time to wait would depend on the hardware the CCU is running on and maybe some other things like number of devices and/or programs, addons installed etc. :-/

Don't know why you would set the check interval from 30s to 60s though, this just increases the variation of the timespan (ccu_is_available to do_the_reconnect), doesn't it?

**Comment by SukramJ** [comment]
I already planned to raise it to 60s before. Should be enough for a connection check.

**Comment by SukramJ** [comment]
addressed in 0.23.0

**Comment by eikowagenknecht** [comment]
Thanks. I have restarted about 20 times now and currently can't reproduce. I'll close this and reopen if I catch it another time.
