### ISSUE TITLE
Some rain states are not translated

### ISSUE THREAD

**Issue by eikowagenknecht** [SukramJ/hahomematic#192]
"Trocken" is from HmIP-SWO-PR, "DRY" from HM-Sen-RD-O. I prefer "Trocken" ;-)

![image](https://user-images.githubusercontent.com/1475672/149640791-a14365a7-0c8c-4446-bee8-542be4c716d2.png)

**custom_component/hahomematic version (if applicable):**
latest

**Home Assistant version (if applicable):**
latest

**Comment by SukramJ** [comment]
What is name of the parameter.
You can find it when you click on the entity under attributes.

**Comment by eikowagenknecht** [comment]
Parameter
STATE

Entity type
generic

**Comment by SukramJ** [comment]
Fixed with 0.23.0

**Comment by eikowagenknecht** [comment]
Had to readd the sensor because of the changed type (binary), works fine now. Thank you!
