### ISSUE TITLE
High duty cycle caused by integration

### ISSUE THREAD

**Issue by dagobert** [SukramJ/hahomematic#1920]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Regularly every couple days I get a high duty cycle. Only restarting HA solves the problem. CCU restart does not.

### What version of HomematicIP (local) has the issue?

1.75.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.79.6.20241122

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Additional information

I am not sure If this behavior started after an update of either Raspberrymatic or this integration. Since I have to restart HA to make this problem go away I guess it is a problem of the integration.
The time of the occurrences are not always at the same time, hence I guess it is not connected to an automation.

I do not have a log yet, since I just thought about posting this issue after it happened again yesterday. Can you point out what we/you need to check where the source of the problem might be.

**Comment by SukramJ** [comment]
It is most likely that a permanent high duty cycle is not related to this integration.
See my answer in the related discussions:

See https://github.com/danielperna84/hahomematic/discussions/1871#discussioncomment-11340974
https://github.com/danielperna84/hahomematic/discussions/1871#discussioncomment-11340974

**Comment by dagobert** [comment]
It is not permanently high. It is way below 10 most of the time but on some point spikes up and than does not come down anymore unless I am restarting HA.

**Comment by SukramJ** [comment]
Thank you for reading the referenced posts.
Don't tell stories ->post facts like a screenshot.

**Comment by dagobert** [comment]
Here is a graph of the duty cycle. Note that the duty cycle drops only because I restart HA. I let it run a whole day when it happened the first time because I thought it would stop by itself.

![grafik](https://github.com/user-attachments/assets/6e554c38-43bd-4738-9b82-da887557a87f)


As I said, I would love to supply more useful information. Please tell me what I need to do before this happens to prepare being able to get the data for you and what I need to do to get the data for you when it happens.

**Comment by SukramJ** [comment]
I hope you read the referenced posts, where i describe how the integration works, so there is no permanent and active data fetching from devices that would cause a a higher duty cycle.

I could take a look at your debug logs.
Therefore click on the integration, acivate debug and restart the integartion.
After a while stop debug and download the log file.
Post it here as a zipped file.

 **It feels a complete waste of time to hunt for 10% of duty cycle!**

**Comment by dagobert** [comment]
> I hope you read the referenced posts, where i describe how the integration works, so there is no permanent and active data fetching from devices that would cause a a higher duty cycle.

I understand. I don't think it is a fetching problem but a sending problem. The only thing I can imagine is that a "command" is send over and over by HA though the CCU to a device.
But I do not have obvious automations that are sending commands at the times the high duty cycle starts.

> I could take a look at your debug logs. Therefore click on the integration, acivate debug and restart the integartion. After a while stop debug and download the log file. Post it here as a zipped file.

I will start the debug log and hope that this problem will ocurr soon again.
 
> **It feels a complete waste of time to hunt for 10% of duty cycle!**

Maybe I am not clear enough on the problem. I am not hunting down a generally high duty cycle. I understand the general problem of the duty cycle and why it might be high or stays high.
The duty cycle suddenly ramps up to 20% and stays there until HA is restartet. A CCU restart is **not** solving the problem. At 20% device control does not work any more or only sluggish.
I observed this problem now for month(s) am not fast on creating issues since I know that time of people is precious.
