### ISSUE TITLE
Thermostat ist nicht Verfügbar wenn die Gruppe nicht fehlerfrei ist

### ISSUE THREAD

**Issue by blueb6** [SukramJ/hahomematic#1942]
### I agree to the following

- [X] I have read the [documentation](https://github.com/sukramj/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/sukramj/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/sukramj/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Wenn man in der Homematic eine Gruppe mit z.B. drei Fensterkontakten und drei Thermostaten erstellt kann man die Gruppe als Thermostat in HA integrieren, sollte aber z.B. ein Fensterkonatkt nicht erreichbar sein aus welchen Grund auch immer, dann ist der Thermostat in HA nicht mehr ansprechbar/verfügbar, aber in der Homematic funktioniert die Gruppe trotzdem tadellos.

### What version of HomematicIP (local) has the issue?

1.75.1

### What was the last working version of HomematicIP (local)?

nicht bekannt, früher nicht benötigt

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.79.6.20241122

### What hardware are you running for your system?

CCU3

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/sukramj/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Bitte folgendes lesen: https://github.com/SukramJ/hahomematic/discussions/1882#discussioncomment-11373416
