### ISSUE TITLE
Water sensor not reported as water sensor

### ISSUE THREAD

**Issue by alexhass** [SukramJ/hahomematic#1945]
### I agree to the following

- [X] I have read the [documentation](https://github.com/sukramj/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/sukramj/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/sukramj/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I have a wmbus stick integrated with cuxd. This sensors are synced to HA, but they are not properly defined. I cannot select the values as „Water consumption“. Based on hadocs i should report this to the integration what i‘m herby doing.

The sensor looks like this:

```
interface_id: ccu3-webui-CUxD
address: CUX2500001:1
model: HM-ES-TX-WM
parameter: METER
function: Energiemanagement
value_state: valid
unit_of_measurement: m&#179;
friendly_name: Hausanschluss - Wasser Meter
```

as you can see, unit_of_measurement is broken html, it is not device_class water,  state_class total_increasing is missing. The  sensor value seems fine.

first issue report… so not sure what you may need from me.

### What version of HomematicIP (local) has the issue?

1.75.1

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which config details do you use

- [X] TLS
- [ ] callback data ([see](https://github.com/sukramj/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
You can customize it yourself https://github.com/SukramJ/hahomematic/discussions/873#discussioncomment-4736306

**Comment by alexhass** [comment]
Und warum macht man das nicht gleich so, dass es richtig ist?

**Comment by SukramJ** [comment]
Richtig für die mit dem Gas oder für die mit dem Wasserzähler?
Die mit dem Gaszähler haben Glück.

**Comment by alexhass** [comment]
Stimmt der Esi gas schein ok zu sein. Mein wmbus der per cuxd angebunden wird, ist vieleicht nicht das gängigste produkt, aber auch der einzige weg das wasser auszulesen… wäre doch sicher nicht unmöglich das out of the box funktional zu bekommen

**Comment by SukramJ** [comment]
Wenn Du herausgefunden hast, wie über das Datenmodell erkannt werden kann, welcher Sensor angeschlossen ist, dann könnte man weiter sprechen.

Allerdings ...

> Mein wmbus der per cuxd angebunden wird, ist vieleicht nicht das gängigste produkt,

lohnt sich der Aufwand, für die drei Leute, die das benutzen nicht.

**Comment by alexhass** [comment]
Ich schätze der cux entwickler hätte das nicht eingebaut, wenn es nur 3 user sind… :-)

**Comment by SukramJ** [comment]
Ist mehr ehrlich gesagt trotzdem egal. Es geht nicht automatisch.

**Comment by alexhass** [comment]
Hab noch etwas darüber nachgedacht und jetzt weiss ich wie es geht.

Die address: CUX2500001:1 ist absolut eindeutig. CUX25xxxxx ist immer ein wmbus gerät. Meines wissens hat der cuxd maintainer nichts anderes als wasser getestet. Die sache ist also immer klar.

METER sagt dir das es wasser ist und die 6 anderen sensoren die dabei mitkommen sind absolut unique auf wasser bezogen. Da ist immer klar das es m3 ist…

Die anderen CUX Geräte sind da ähnlich… hat alles einen eindeutigen Prefix…

**Comment by SukramJ** [comment]
Das Gerät läuft als HM-ES-TX-WM, und hat eine Gerätebeschreibung, die für mich relevant ist.
Was CUXD daraus mach interessiert mich nicht, und ich werde auch auch nicht plötzlich anfangen Geräteadressen auszuwerten, um daraus abzuleiten ob es ein Wassersensor ist.

Warum machst Du so einen Aufriss um einen Wassersensor einzubinden? 
Es gibt in HA die Möglichkeit die Entitäten anzupassen, so wie im initial verlinkten Beitrag beschrieben, also benutzt es auch.

**Comment by alexhass** [comment]
Naja, es ist doch offensichtlich, dass die cuxd integration nicht ganz richtig oder zumindest unvollständig implementiert ist. 

In cuxd kann man sich das gerät einfach beliebig aussuchen. HM-ES-TX-WM in cuxd ist kein HM-ES-TX-WM, sondern nur ein fake device damit es einem namen hat den hmip erkennt und optisch das ist was du als icon haben möchtest, denn hmip kannst du halt keine unbekannten geräte unterjubeln.

Klar kann man alles zurechtfummeln in ha, aber es kann ja vieleicht auch einfach out of the box funktionieren ohne gefrickelt. Das ist wahrlich nicht auf meine wasserzähler begrenzt.

**Comment by SukramJ** [comment]
Kappierst du das nicht?

Ein HM-ES-TX-WM kann abhängig vom Lesekopf Gas oder Wassersensoren anschliessen. 
Primär ist für die Integration GAS konfiguiriert, da über die Gerätebeschreibung nicht zwischen Gas und Wasser unterschieden werden kann. Hab ich alles schon erklärt!

CUxD benutzt die Beschreibung eines HM-ES-TX-WM als Aliasgerät, aber man kann immer noch nicht zwischen Gas und Wasser unterscheiden. Hab ich alles schon erklärt!

> Naja, es ist doch offensichtlich, dass die cuxd integration nicht ganz richtig oder zumindest unvollständig implementiert ist.

Dann kannst Du als Experte ja gerne einen PR erstellen und die Integration korrigieren.
Ich werde für CUxD keine Sonderlocken einbauen, die für die regulären HM/HmIP Geräte nicht notwendig sind.

Warum soll ich Stunden investieren, damit ein Wassersensor der über CuXD angebunden wird, und sicherlich nur von einer handvoll Leute verwendet wird, in HA als Wassersensor angezeigt wird?

Bitte verschwende meine Zeit nicht, wenn du innerhalb von einer Minute die nötige Anpassung selber machen kannst.

Mehr habe ich zu dem Thema nicht zu sagen.
