### ISSUE TITLE
Support Cooling Mode for HmIP-BWTH

### ISSUE THREAD

**Issue by DaelDe** [SukramJ/hahomematic#1952]
### I agree to the following

- [X] I have read the [documentation](https://github.com/sukramj/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/sukramj/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/sukramj/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

HmIP-BWTH channel 1 supports switching from heating to cooling mode.
Currently the mode of the device can only be set to Auto, Heating or off.
Please also support Cooling mode.

According to the device documentation:
Channel 1 - HEATING_CLIMATECONTROL_TRANSCEIVER
Parameter HEATING_COOLING

<img width="300" alt="image" src="https://github.com/user-attachments/assets/148f71d8-2e71-40cd-925e-1fa08c68ae01" />

### What version of HomematicIP (local) has the issue?

1.76.1

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.77.6

### What hardware are you running for your system?

Pi4

### Which config details do you use

- [X] TLS
- [ ] callback data ([see](https://github.com/sukramj/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Enable the `operation mode` entity of the BWTH.
When switched to cooling the modes are selectable.

**Comment by DaelDe** [comment]
OK, thanks.
