### ISSUE TITLE
Entdeckte, dann ignorierte Zentralen tauchen in den Homematic(IP) Local: Aktionen als wählbare Zentrale auf

### ISSUE THREAD

**Issue by Baxxy13** [SukramJ/hahomematic#1954]
### I agree to the following

- [X] I have read the [documentation](https://github.com/sukramj/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/sukramj/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/sukramj/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Da ich viele RaspberryMatic-Testsysteme laufen habe, habe ich diese (nachdem sie von meinem produktiven HA entdeckt wurden) ignoriert.
Diese ignorierten Zentralen tauchen dann als wählbare Zentrale in den Homematic(IP) Local: Aktionen auf.

Entferne ich den "ignorieren Status" so das sie wieder unter "Entdeckt" stehen verschwinden sie auch wieder als wählbare Zentrale in den Homematic(IP) Local: Aktionen.

### What version of HomematicIP (local) has the issue?

1.76.1

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.79.6

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/sukramj/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Additional information

- Mir ist das schon vor Ewigkeiten aufgefallen daher kann ich auch nicht sagen ob es mal anders war.
- Bin heute eher zufällig auf die Zusammenhänge gestoßen wodurch sich das leicht reproduzieren lässt.
(nach dem "Ignorieren" / "UnIgnorieren" der entdeckten Zentrale 1x Browser-Refresh um den Effekt instant in den Homematic(IP) Local: Aktionen zu sehen)

Bin mir auch nicht sicher ob es ein HA oder Integrations-Problem ist.

Eine der Zentralen ist "ignoriert":
![HA_RM26_ignoriert](https://github.com/user-attachments/assets/5db375fd-64c6-4caf-afdc-136b5daa8677)
Und taucht als wählbare Zentrale in den Homematic(IP) Local: Aktionen auf.
![HA_RM26_ignoriert_Aktion](https://github.com/user-attachments/assets/c4e2752d-9310-47f7-b4ab-4b80e9b99622)

Die Zentrale ist "entdeckt" und nicht mehr "ignoriert":
![HA_RM26_nicht_ignoriert](https://github.com/user-attachments/assets/3ea1d08f-8246-49d2-a4e5-bd73ba9eaf1e)
Und ist aus den wählbaren Zentralen in den Homematic(IP) Local: Aktionen verschwunden.
![HA_RM26_nicht_ignoriert_Aktion](https://github.com/user-attachments/assets/189dc13a-8b5f-44ea-8f3c-ddd6eecaaae7)

**Comment by SukramJ** [comment]
1. Kenn ich
2. nervt mich
3. Halte ich für einen HA-Frontend Bug

**Comment by SukramJ** [comment]
Ich hab noch mal in der Doku nachgeschaut.

Die Integration verwendet den [config entry selector](https://next.home-assistant.io/docs/blueprint/selectors/#config-entry-selector), und der kann nur auf eine Integration, aber nicht weiter auf nur Aktive, eingeschränkt werden:

```
        config_entry:
          integration: homematicip_local
```

**Comment by Baxxy13** [comment]
Verstehe.
Etwas unglücklich umgesetzt seitens HA. 
Dann belassen wir's dabei.
Ist auch nicht so dramatisch jetzt wo ich weiß wie das zustande kommt.

Dir später nen guten Rutsch! 😃

**Comment by SukramJ** [comment]
Danke, wünsche ich dir auch.
