### ISSUE TITLE
Alarmmessages is not refreshed properly

### ISSUE THREAD

**Issue by marc965** [SukramJ/hahomematic#197]
**custom_component/hahomematic version (if applicable):**
0.22.2

**Home Assistant version (if applicable):**
2021.12.9

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, ...): CCU2/3
- OS (Original, RaspberryMatic, debmatic/...): RaspberryMatic
- Version: 3.61.7.20220115

**Problem-relevant configuration:**
Do you use tls? no
Do you use callback? no
Do you use username and password? yes
Which interfaces do you use? BidCos-RF, HmIP-RF

**Describe the bug**
Alarmmessages are not refreshed properly.
I had a Alarm Message due to "Device not available" this early morning.
Home Assistant is displaying immediately this Alarm Message, but
is not falling back to 0 after this Device turn back to "available" after 45 Minutes.

Dont know if this helps, but Servicemessages are refreshed in time,
and my test with "WatchDog: hb-rf-eth-connection" was succesfull too.

**Expected behavior**
Alarmmessages are displayed as in RaspberryMatic with a delay of a few seconds.

**Screenshots**
![image](https://user-images.githubusercontent.com/85791333/149662905-2019348e-b5b8-4e53-a793-b3bbcae54a11.png)
![image](https://user-images.githubusercontent.com/85791333/149662925-2284aa80-bc27-4eb3-b3cc-41028d47be19.png)

**Comment by SukramJ** [comment]
I don't know how this sysvar ist filled on the CCU, and how this sysvar relates to the UI element.
Maybe someone else can give a hint on this.
We load all sysvars together and update the sensors, so there is now reason why Alarmmeldungen should behave different.
The refresh interval on sensors is 30 seconds.

**Comment by marc965** [comment]
After more than 24h the variable Alarmmessages still counting 1,0!
Restart supervisor, core und RaspberryMatic Addon has no effect...

**Comment by SukramJ** [comment]
Please check with the following script on your CCU:
`WriteLine(dom.GetObject('Alarmmeldungen').Value());`
Goto CCU / Programme / Script testen

Looks like the content of your sysvar is 1.

**Comment by marc965** [comment]
> Please check with the following script on your CCU: `WriteLine(dom.GetObject('Alarmmeldungen').Value());` Goto CCU / Programme / Script testen
> 
> Looks like the content of your sysvar is 1.
Yes, you are right!
But why the Display "Alarmmeldungen" is "0"?
How can i fix this?

**Comment by marc965** [comment]
> > Please check with the following script on your CCU: `WriteLine(dom.GetObject('Alarmmeldungen').Value());` Goto CCU / Programme / Script testen
> > Looks like the content of your sysvar is 1.

Yes, you are right!
But why the Display "Alarmmeldungen" is "0"?

![image](https://user-images.githubusercontent.com/85791333/149987466-d8d58f9e-00dc-4fc9-ac90-b8fa06a5eb2c.png)

How can i fix this?

****

**Comment by SukramJ** [comment]
I dont't know. Maybe you should ask in the[ homematic-forum](https://homematic-forum.de/).

**Comment by SukramJ** [comment]
I think this can be closed here

**Comment by marc965** [comment]
> I think this can be closed here

You don't want to wait until i have response from forum?
I do not care...

Close it, i re-open it or open a new issue if necessary, ok?

**Comment by SukramJ** [comment]
OK

**Comment by marc965** [comment]
> OK

Found Issue: 
https://github.com/jens-maus/RaspberryMatic/issues/1016

It will be mentioned on one of next releases...
Thanks for your effort.
