### ISSUE TITLE
Doc missing on how to use/try with Homeassistant

### ISSUE THREAD

**Issue by ProfDrYoMan** [SukramJ/hahomematic#200]
If this is already in the state to tryout in Homeassistant I would love to do, but I do not find any doc on how to do so.

**Comment by Lemocin** [comment]
Hello, yes, ist's testable. [Here](https://github.com/danielperna84/custom_homematic/wiki/Installation) are some instructions in how to Install the Integration.

This repository is from the library which the integration uses. The custom_homematic repo contains the actual integration, so the docs on how to install are there.

**Comment by ProfDrYoMan** [comment]
Thx for this info. Risk? E.g. how big is the chance to make the HA instance unusable?

I just want to play around/learn/help, but don't want to risk my house automation.

It would be good to link to the integration in the readme of this repo.

**Comment by Lemocin** [comment]
> Thx for this info. Risk? E.g. how big is the chance to make the HA instance unusable?

I'm using it now for around two or three months and using it as my main homematic ha integration.
Sometimes there are small breaking within the integration(when the entities get redesigned) but HA should not break by using this integration. But, as always, you should have a backup.

**Comment by ProfDrYoMan** [comment]
I would keep all my old automations / sensor definitions / ... in use and only have the new integration in parallel.

Is parallel usage working ok?

**Comment by SukramJ** [comment]
I don't think this is a good idea, because this is untested.
I'd recommend to use a dedicated test system

**Comment by ProfDrYoMan** [comment]
Hmm, ok. Good that I asked.

I only have one raspimatic running in VM. Is it at least ok to have a second HA instance but the same raspimatic?

**Comment by Lemocin** [comment]
I'm using it in parallel. Just have to make sure while setting up, that the instance name differs from the one in the yaml file.

**Comment by Lemocin** [comment]
> I only have one raspimatic running in VM. Is it at least ok to have a second HA instance but the same raspimatic?

That should work. [Here](https://github.com/danielperna84/hahomematic/discussions/130)  are some informations about this

**Comment by ProfDrYoMan** [comment]
> I'm using it in parallel. Just have to make sure while setting up, that the instance name differs from the one in the yaml file.

You are even using the old and the new integration in parallel?

Or, you are using "only" the same raspimatic/ccu but two HA instances?

Just to be very clear before messing up.

**Comment by Lemocin** [comment]
> > I'm using it in parallel. Just have to make sure while setting up, that the instance name differs from the one in the yaml file.
> 
> You are even using the old and the new integration in parallel?
> 
> Or, you are using "only" the same raspimatic/ccu but two HA instances?
> 
> Just to be very clear before messing up.

I'm using both integrations in my main HA (but this is not recommended, nevertheless, i find it easier to test if i'm actively using it) and another one in another HA. So parallel HA instances accessing the same CCU are possible.  Only the instancenames must differ.
