### ISSUE TITLE
TRV Level issues with recent releases

### ISSUE THREAD

**Issue by sotatech** [SukramJ/hahomematic#202]
I think there is some confusion about the control of the valve opening on HM-IP TRVs. This entity has a value range from 0 (closed) to 1 (fully open). I normally multiply it by 100 to give a percentage.
It is controlled by the logic within the TRV based on the difference between the set temperature and the actual room temperature. As far as I know, it is not meant to be changed directly. Since 0.22.1 this has changed so it can be adjusted, However the TRV will quickly reset itself to it's original value so it serves no purpose.
Also, when the valve is at 0 the state changes to unavailable. Finally, the value is reported as "#" which I think is correct. See attached image. Thanks!

![image](https://user-images.githubusercontent.com/9580066/149738572-48b55d40-417f-4da8-a8aa-833d0200ed5a.png)

**Comment by SukramJ** [comment]
@sotatech Please use the hahomatic repo for issues as requested on the front page
Thanks

**Comment by sotatech** [comment]
Apologies, I had missed the request. I was a few releases behind, so I've updated to 0.23.0 this morning, thanks. I use the level to know when a room is calling for heat, which then triggers the heating for that zone. So my automations were not working properly when it became unavailable.
The reason I mentioned that it should not be adjustable, is that it is read-only in RaspberryMatic and there is no reason to manually change it which may confuse some people.
