### ISSUE TITLE
names of imported hmipw-drs8 objects have unexpected additional characters in it

### ISSUE THREAD

**Issue by AlexaMiller** [SukramJ/hahomematic#210]
Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

**Home Assistant version (if applicable):**
2021.12.10

**CCU version:**
- debmatic 3.61.7.88 with RPI-RF-MOD

**Describe the bug**
device HmIPW-DRS8 does not 

nameconversion from debmatic -> homeassistant:
AU_Garage_Licht:Status -> binary_sensor.au_garage_licht_state_chstatus
AU_Garage_Licht:Schalter_A -> switch.au_garage_licht_chschalter_a
AU_Garage_Licht:Schalter_B -> switch.au_garage_licht_vchschalter_b
AU_Garage_Licht:Schalter_C-> switch.au_garage_licht_vchschalter_c

**Screenshots**
![bug1](https://user-images.githubusercontent.com/30142423/149944890-bbb97587-ca51-45aa-afac-567a8bfcaf88.jpg)
![bug2](https://user-images.githubusercontent.com/30142423/149944906-d4b2f7ba-7c91-4047-bea3-646aef100b3a.jpg)

**Comment by SukramJ** [comment]
Your naming breaks the default schema.
Homematic uses the ":" as separator between name and channel no.
If you use something else than ":" the device names will be fine.

**Comment by AlexaMiller** [comment]
my naming actually follows the scheme: as you see the part before the ":" is always the same per device, only the channel names are modified and named according to their function

**Comment by SukramJ** [comment]
Naming is complicated!
What i could do is accept your channel name as custom (take it as it is), if the part after the colon in not an int.

So the Entity will be named `AU_Garage_Licht:Schalter_B ` and the entity name might be `switch.au_garage_licht_schalter_b`
HA generates the entity_id based on the name, so i'am not sure what HA does with the ":".

**Comment by SukramJ** [comment]
Tested with HA
ccu: AU_Garage_Licht:Schalter_B
name: AU_Garage_Licht:Schalter_B
entity_id: switch.au_garage_licht_schalter_b

Should be ok.

**Comment by AlexaMiller** [comment]
That sounds like a perfect solution, if the part after the colon is an integer then the channel usually just has not been named (yet). this would also follow the eq3 naming convention.

the entity name as you propose would be the logical path, i fully agree with you there.

the "friendly name" - honestly, i do not really care about that as i set it in the frontend individually just as needed.
(a device might sport different names in different views - depending on how the view is weighted, but that's a completely different topic now.)

**Comment by AlexaMiller** [comment]
phew, you are faster coding that stuff than me composing an anwer. and YES, that sound just perfect, thank you!

**Comment by SukramJ** [comment]
Next release will contain the fix. You should then recreate the integration.

**Comment by AlexaMiller** [comment]
excellent, will do and keep you updated.

**Comment by SukramJ** [comment]
Fixed with latest release (0.24.3)

**Comment by AlexaMiller** [comment]
- removed the integration
- checked for remaining entities (no cleanup needed, there were none)
- added the integration
- entities were added with expected name behaviour

Thank you!
