### ISSUE TITLE
Entity_ID - Name

### ISSUE THREAD

**Issue by AlexaMiller** [SukramJ/hahomematic#218]
Guten Morgen,

in der aktuellen Version hat sich ein zusätzliches Attribut eingeschlichen,
erwartetes Verhalten: 
Name des Devices + "_" + Name des Kanals (bzw Datenpunkts)
jetzt ist: Name des Devices + "_" + Attribut(?) + Name des Kanals (bzw Datenpunkts)

vorher: binary_sensor.eg_esszimmer_wassersensor_geschirrspueler_alarmstate
jetzt: binary_sensor.eg_esszimmer_wassersensor_geschirrspueler_ **sensor_** alarmstate

vorher: binary_sensor.eg_eingang_tuer_state
jetzt: binary_sensor.eg_eingang_tuer_ **verschluss_** state

Die Namen sind somit nicht mehr intuitiv schreibbar, der vorherige Status war mE besser.

Liebe Grüße, Alexa

**Comment by SukramJ** [comment]
eg_eingang_tuer is dein Gerätename
sensor und verschluss sind deine Kanalnamen
state ist der Parametername

Der Name besteht (verkürzt)  aus devicename + kanalname+ parameter.

Ich weiss nicht vorauf dich dein vorher bezieht, aber da jetzt mehr Entitäten generiert werden ist der Kanalname notwendig geworden. Ansonsten müsste man sich mit der Eindeutigkeit von Namen beschäftigen.

Ich denke Du wirst dich schon dran gewöhnen.

**Comment by AlexaMiller** [comment]
"vorher" bezieht sich auf das Release vor dem am gestrigen Abend.
ok, hab's nochmal genau durchgesehen. 
ist ein ziemlicher breaking change, aber - ich mag ihn, macht Sinn und ist logisch ableitbar.
Danke für die Klärung!
