### ISSUE TITLE
Authentication fails if the password contains #

### ISSUE THREAD

**Issue by HomeClassic22** [SukramJ/hahomematic#235]
Hi all,

i had big problems setting up the connection because the password in the ccu contained #.

**custom_component/hahomematic version (if applicable):**
0.27.1

**Home Assistant version (if applicable):**
2021.12.10
Home Assistant OS 7.2 stable

**CCU version:**
- Model CCU3
- OS  RaspberryMatic
- Version: 3.61.7.20220115

**Problem-relevant configuration:**
Do you use tls?
use TLS                         YES
check TLS connection NO
Do you use callback?  NO
Do you use username and password? YES
username: user1
password: 5dpiv!#gAW3Sg2xfl4nG
Which interfaces do you use?
HmIP-RF; Bidcos-RF; groups

**Describe the bug**
If the password contains a #, no connection to the CCU is established.

**To Reproduce**
1. I did to try establish an connection between hahomatic an ccu with password contains # 
2. no errors in log files from home assistant; no errors in the ccu and no connection (i did not had set flags for debug)
3. change password to less complex and without #, connection can established 

Can this be reproduced?

**Comment by SukramJ** [comment]
Yes, this is [documented](https://github.com/danielperna84/custom_homematic#authentication).

**Comment by SukramJ** [comment]
I think this can be closed
