### ISSUE TITLE
Retry connection if CCU not available during HA start

### ISSUE THREAD

**Issue by danielperna84** [SukramJ/hahomematic#236]
**Is your feature request related to a problem? Please describe.**
A user has reported, that there are problems when the CCU is not available while Home Assistant is started.

**Describe the solution you'd like**
 _Premium_ Integrations perform some sort of retry-loop during startup if the target device can't be reached. I believe I have seen some guidelines for this somewhere, but can't find them right now as I'm a bit in a hurry. The interval of the retries increases over time.

**Describe alternatives you've considered**
None. This should be implemented some day.

**Additional context**
None.

**Comment by SukramJ** [comment]
Are there any integrations that retry if counterpart is not available during startup?

https://developers.home-assistant.io/docs/integration_quality_scale_index?_highlight=platin#platinum-

**Comment by danielperna84** [comment]
I don't know for sure. I assume the recorder-Integrations would be good candidates to look at. So MariaDB, Postgres etc..

**Comment by SukramJ** [comment]
Recorders are "stupid". They just send data and have no devices.
I think the only requirement from the link above is to fire an PlatformNotReady if unable to connect during platform setup.

**Comment by SukramJ** [comment]
So far i haven't found any comparable integration that supports restart on intit-fail, but the connection-checker is also "stupid" and running despite missing counterpart. Lets see.

**Comment by danielperna84** [comment]
Well, the old integration didn't handle this case as well. So we're not worse than before regarding this topic. That being said, we create the entities from cache, so theoretically it should start up in any case, and the values should start coming in as soon as the connection checker eventually triggers the init. Only the variables would be missing in this case I guess. 🤔

**Comment by SukramJ** [comment]
Should work with 0.28.0.

**Comment by SukramJ** [comment]
Solved with 0.29.0
