### ISSUE TITLE
AlarmOn for HM-SEC-SD(2)

### ISSUE THREAD

**Issue by kabakakao** [SukramJ/hahomematic#251]
Would it be possible to set the SmokeDetector to AlarmOn and AlarmOff through Homeassistant.
I came from FHEM, where it was possible: https://wiki.fhem.de/wiki/HM-SEC-SD_Rauchmelder
But I didn't find a solution to get it for piVCCU or Homeassistant.

**Comment by danielperna84** [comment]
I don't think this will be possible. The [paramset](https://github.com/danielperna84/pydevccu/blob/master/pydevccu/paramset_descriptions/HM-Sec-SD-2-Generic.json) does not contain any parameters that to me look like they could be used to control the device. Apart from that the FHEM Wiki you have linked is talking about _teams_. Maybe those habe other parameters, but I don't have any paramset-data for these. Furthermore even the FHEM Wiki mentions those to be _fragile_, and what they are doing there seems more like a _hack_.

Maybe someone else who has these devices can chime in. But as far as I can tell it won't be possible.

**Comment by kabakakao** [comment]
I read a bit more about how FHEM is working. And it seems, that they are „talking“ BidCos directly with the device. I have several smoke detectors. What can I do, create a param-set of the device and/or Team?

**Comment by danielperna84** [comment]
I had a look at the Homematic Forum, and there doesn't seem to be an _official_ way to do this. If FHEM found a way to do this, that's nice. But the way we are communicating the the CCU does not allow _advanced_ control like FHEM. So we won't be able to support this. Especially as this might be security-relevant for you. And I don't think you want something hacky that's possibly unstable for security-related tasks. My advice would be to upgrade to HmIP smoke detectors. They support triggering of the siren out of the box.

**Comment by kabakakao** [comment]
Okay. I understand. I will close it here
