### ISSUE TITLE
set_value failed with ProxyException

### ISSUE THREAD

**Issue by IAmKonni** [SukramJ/hahomematic#252]
When shutting down two covers at once (grouped by cover group via two HmIP-BROLL) I got the following exception/logs. One cover shut down immediately, the other with a delay of ~10 to 20 seconds.

Both HmIP-BROLL are installed in the near range of the CCU3 (~1 to 1,5 meters).

Custom Homeatic version: 0.28.7

```
Logger: hahomematic.client
Source: /usr/local/lib/python3.9/site-packages/hahomematic/client.py:269
First occurred: 21:37:38 (2 occurrences)
Last logged: 21:37:58

set_value failed with ProxyException ((<Fault -1: 'Generic error'>,)): 00111D8998D677:4, LEVEL, 0.0
set_value failed with ProxyException ((<Fault -1: 'Generic error'>,)): 00111D8998D035:4, LEVEL, 0.0
```

**Comment by SukramJ** [comment]
The single HmIP-BROLLs work without a Problem? 
Have you used the old integration successfully with groups?

**Comment by IAmKonni** [comment]
I am completely new to HomeMatic as well as to Home Assistant. The HmIP-BROLLS are installed since 2 weeks and are mostly used by the hardware switch itself.
But i remember that I had some delay issues (5 to 30 seconds), when I used the BROLLs via TinyMatic app. Probably this is more an CCU / hardware issue.

**Comment by SukramJ** [comment]
Good to know. 
You should start solving this in the CCU. If this works you should go on in HA.
Maybe the [homematic-forum](https://homematic-forum.de/) can help you with the CCU related issues.
Please close this issue, if you agree.

**Comment by IAmKonni** [comment]
I will. Does the log fit to the explained behaviour?

**Comment by SukramJ** [comment]
Not really.
