### ISSUE TITLE
Cover does not tilt after changing tilt position

### ISSUE THREAD

**Issue by Knechtie** [SukramJ/hahomematic#258]
**custom_component/hahomematic version:**
0.29.0

**Home Assistant version:**
2021.12.10

**CCU version:**
- Model: Raspi3
- OS: RaspberryMatic
- Version: 3.61.7.20220115

**Problem-relevant configuration:**
Homematic Device: HmIPW-DRBL4

**Describe the bug**
Covers/blinds are not tilting immediately after changing the tilt position with the slider or the tilt buttons in Home Assistant. They tilt into the right position either when the position slider is changed or the stop tilt button is pressed.

**To Reproduce**
1. Go to a cover entity that supports tilting
2. Slide the tilt position slider to any position OR press a tilt up/down button
3. Nothing happens
4. Change the cover position with the corresponding slider OR press the stop tilt button
5. Cover tilts into the right position

**Expected behavior**
Covers/Blinds should tilt immediately after changing the tilt position. The stop tilt button should stop the movement instead of starting it.

**Screenshots**
<img width="399" alt="Bildschirmfoto 2022-02-01 um 21 28 57" src="https://user-images.githubusercontent.com/32765231/152046074-a7ee004d-ffea-41c5-a8c1-d7c9bcfe17ba.png">

**Comment by SukramJ** [comment]
Hi,
i think you are the first one with a blind.
I have some questions:
Which mode is set on the channel (cover or blind or whatever it is named) ?
Everything works as expected when using the CCU Web-UI?
Default cover operations work as expected?

**Comment by Knechtie** [comment]
Hi,

1.  The mode in the CCU is set to "Jalousie", so blind is the correct translation I guess.
2. CCU Web-UI works as expected
3. The default position operations in the HA UI are working (except the tilt behavior described in my latest issue). But I have not tested all service calls yet

**Comment by SukramJ** [comment]
When you change the tilt position in ccu is this change displayed in HA?

**Comment by Knechtie** [comment]
Yes, it changes even faster in the HA UI. It is refreshing multiple times in a single tilt move. 
While its moving and after/when reaching the set tilt position. Same visual behavior as in the CCU UI, but more responsive.

**Comment by SukramJ** [comment]
That ok. CCU sends  multiple events.

**Comment by SukramJ** [comment]
Have you ever used the old integration? Did it works as expected?

**Comment by SukramJ** [comment]
> Covers/blinds are not tilting immediately after changing the tilt position with the slider or the tilt buttons in Home Assistant. They tilt into the right position either when the position slider is changed or the stop tilt button is pressed.

In my words:
1. You use the lower controls below "Kippstellung", but nothing happens.
2. The you use the position slider or the stop button and the tilting starts.

@danielperna84
Do you know API wise what is required to tilt. Does it work for HmIPW-DRBL4 in pyhomematic ?
Currently i only set the tilt position, but i think it is required to set the tilt position AND the cover position (to the current 
 cover position) at once.

**Comment by danielperna84** [comment]
No. I don't have any, and with pyhomematic we don't support IP-blinds because of the different channels they use. One of the reasons why I started this new integration. So for this someone else has to step in to answer the question. 😕

**Comment by SukramJ** [comment]
> we don't support IP-blinds

so HmIP-FBL and HmIP-BBL are not supported as blinds?
But a blind like HM-LC-Ja1PBU-FM is supported incl. tilt?

**Comment by SukramJ** [comment]
@Knechtie: As you can see it is not that simple, if the devs do not own such a device.

I created a beta 0.29.1.HmIPW-DRBL4 that is especially created for for testing your device.
Beta is selectable in HACS if you click on "Erneut herunterladen".

Please if anything changes. Both tickets are addressed.

**Comment by Knechtie** [comment]
> Have you ever used the old integration? Did it works as expected?

Yes I used the old integration but used mainly service calls in automations to set tilt and position (I also needed multiple service calls to physically tilt the blind: cover.set_cover_tilt_position and cover.set_cover_position).

At the time I tried to add tilt support for HmIPW-DRBL4 (pyhomematic [PR #398](https://github.com/danielperna84/pyhomematic/pull/398)) I thought the tilt behavior in the HA UI is the same as it is for other HM/HMIP devices and should be the "right behavior"

I can remember that the HA tilting UI _sometimes_ behaved strangely with pyhomematic and controlled the wrong blind but I never did further investigations as I was waiting for hahomematic.

> In my words:
> 
> 1. You use the lower controls below "Kippstellung", but nothing happens.
> 2. The you use the position slider or the stop button and the tilting starts.

1.  Yes
2. To be more precise: 
* If I click, hold and drag the slider away, turn back to the actual cover position and release the mouse: Tilting starts
* If I press the stop button below "Kippstellung": Tilting starts

> > we don't support IP-blinds
> 
> so HmIP-FBL and HmIP-BBL are not supported as blinds? But a blind like HM-LC-Ja1PBU-FM is supported incl. tilt?

I do have one blind with HmIP-FBL but as it currently behaves not as it should in the CCU UI, I consider to do a factory reset and reconfigure it before further testing. The tilt controls for HmIP-FBL are available in HA.

**Comment by Knechtie** [comment]
> I created a beta 0.29.1.HmIPW-DRBL4 that is especially created for for testing your device. Beta is selectable in HACS if you click on "Erneut herunterladen".
> 
> Please if anything changes. Both tickets are addressed.

Ok thank you, I will test the beta and give feedback 👍🏻

**Comment by danielperna84** [comment]
> so HmIP-FBL and HmIP-BBL are not supported as blinds?
> But a blind like HM-LC-Ja1PBU-FM is supported incl. tilt?

They are available as cover-entities, but users always complain about them being buggy.

I don't know if tilt works for the classic devices, but I don't recall anybody complaining about that. So it might work as it should.

Maybe those devices don't behave _intuitively_ when controlled via XML-RPC in general. Reading this issue to me it appears as if only changes to `LEVEL` (and `STOP`) cause the motor to be activated, whereas calls to `LEVEL_2` only tell the actor how much to tilt once movement has started. Somewhat similar to when you first set a duration with `ON_TIME` for switches (which at first does nothing), and then turn in on via `STATE`. But that's just a guess. It's hard to tell if you don't have the hardware. 🤷‍♂️

**Comment by SukramJ** [comment]
I know from my Cloud days, that this API requires cover and tilt level in one call.
So my try is now to set the tilt and afterward the current cover level.

**Comment by SukramJ** [comment]
I also send multiple calls for dimmer transitions.

**Comment by SukramJ** [comment]
@Knechtie You can also test the latest release.

**Comment by Knechtie** [comment]
0.29.1.HmIPW-DRBL4 fixed this issue and #259 🎉. 
#259 persists in the latest release 0.30.0.

**Comment by SukramJ** [comment]
Thanks for your Feedback.
