### ISSUE TITLE
Tilt behavior when opening/closing a cover/blind

### ISSUE THREAD

**Issue by Knechtie** [SukramJ/hahomematic#259]
**custom_component/hahomematic version:**
0.29.0

**Home Assistant version:**
2021.12.10

**CCU version:**
- Model: Raspi3
- OS: RaspberryMatic
- Version: 3.61.7.20220115

**Problem-relevant configuration:**
Homematic Device: HmIPW-DRBL4

**Describe the bug**
When I fully open or close my blind, e.g. with the service call cover.close_cover or cover.open_cover, the cover will tilt into the last set tilt position after closing/opening.

This also happens when the cover position up/down-button is being pressed.

**To Reproduce**
1. Go to a cover entity that supports tilting
2. Slide the tilt position slider to 50%
3. Nothing happens (#258)
4. Call cover.close_cover for that blind
5. Cover closes and tilts to 50% afterwards

**Expected behavior**
cover.close_cover: The tilt position should be 0% after closing.
cover.open_cover: The tilt position should be 100% after opening.
Position down/up button: either 0% or 100% tilt like it would be with a "classic" wall button installation (CCUs "Direkte Verknüpfungen" with buttons have also this behavior).

**Comment by SukramJ** [comment]
Hi,
I have some questions:
Which mode is set on the channel (cover or blind or whatever it is named) ?
Everything works as expected when using the CCU Web-UI?

**Comment by SukramJ** [comment]
So basically you say that the close tilt is missing after the cover is closed (or vise versa).
Is that what happens when you press the close cover button in ccu or on a physical button?

**Comment by Knechtie** [comment]
Yes this is exactly what happens when I use the CCU buttons or the physical buttons.

**Comment by Knechtie** [comment]
@SukramJ As [mentioned ](https://github.com/danielperna84/hahomematic/issues/258#issuecomment-1029466292) this issue was _only_ solved in 0.29.1.HmIPW-DRBL4 but not in releases >=0.30.0

**Comment by SukramJ** [comment]
Oh I missed that.
So  behaviour of >=0.30.0 is **exactly** like 0.29.0 (your initial post)?

**Comment by SukramJ** [comment]
Please use the service to clear the cache and then restart HA.
`hahm.clear_cache`

**Comment by SukramJ** [comment]
Please retest with 0.35.1.

**Comment by Knechtie** [comment]
Thanks!
It works with 0.35.1.
