### ISSUE TITLE
HMIP-DLD isn´t working right

### ISSUE THREAD

**Issue by kussione** [SukramJ/hahomematic#264]
Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

Version 0.29.2

**Home Assistant version (if applicable):**
2022.01.1

- Model: CCU3, Raspi4 at the same device as HA
- OS :RaspberryMatic
- Version: 3.61.7.20220115

**Problem-relevant configuration:**

Do you use tls? Yes
Do you use callback? So far as I know: Not
Do you use username and password? Yes

**Describe the bug**
I am able to lock a door with my device and using HA-Homematic but I am not able to relock or to open it. 
All funktions are working fine by using the Raspberrymatic Web-Ui

**Comment by SukramJ** [comment]
Hi,
do you have any  related log messages?

@eikowagenknecht Hi Eiko, do you have the same problem with your HmIP-DLD? Thanks.

**Comment by eikowagenknecht** [comment]
@SukramJ For me it's working just fine, using it multiple times a day. Opening and closing. I'm still on 0.28.7 though.

/edit: Just updated, now on 2022.2 core, latest OS, latest integration. Still working fine.

**Comment by kussione** [comment]
Thank you very much for your message. I will have an eye on it. 
Maybe I have to descripe my issue a bit better. 
Here you will see a screen shot in my Lovelace: 
![image](https://user-images.githubusercontent.com/79758430/152361535-917d2fe7-95a1-4d87-8959-65f2eebdd5bb.png)
I am able to press "VERRIEGELN" and when I am doing so, the DLD is locking right.
If the door is locked, there is still the word "VERRIEGELN" in my lovelace card. If I am right, the the word should be change to "ENTRIEGELN". But this is not happening.
The funktion "OPEN" is missing. 
Maybe I am doing something wrong. 
Best regards from Mittelfranken 
Stefan

**Comment by SukramJ** [comment]
> Maybe I have to descripe my issue a bit better.

YES

What happens if you click on the name?

**Comment by kussione** [comment]
I am getting this:
![image](https://user-images.githubusercontent.com/79758430/152364239-4c1bccc3-36ff-45bb-964d-b9eacf3df498.png)

**Comment by SukramJ** [comment]
And what happens if you click on "ENTRIEGELN"?

**Comment by SukramJ** [comment]
@eikowagenknecht Thanks for your fast reply. How do you operate your DLD? Do you use a special Card?

**Comment by kussione** [comment]
It is working fine.

**Comment by kussione** [comment]
Just the status of the devise is wrong. 
I am using the card which HA is creating

**Comment by SukramJ** [comment]
Do you have anything related in the logs?

**Comment by kussione** [comment]
The funktion "OPEN" whould be fine :-)

**Comment by SukramJ** [comment]
Logs would be fine too.

**Comment by kussione** [comment]
I am looking for. Where can I find it? 
In the "Logbuch" I can´t find any information.

**Comment by kussione** [comment]
is_callback_alive: Callback for HA_Homematic-BidCos-RF has not received events for 11983 seconds')
15:54:00 – (WARNUNG) /usr/local/lib/python3.9/site-packages/hahomematic/client.py - Die Nachricht ist zum ersten Mal um 12:38:47 aufgetreten und erscheint 1172 mal

**Comment by eikowagenknecht** [comment]
> @eikowagenknecht Thanks for your fast reply. How do you operate your DLD? Do you use a special Card?

Just the standard entities card.

**Comment by SukramJ** [comment]
Something is broken with your setup.
Your HA is not receiving state updates from your CCU.
Maybe restart the CCU and reinstall the Integration

**Comment by SukramJ** [comment]
@eikowagenknecht State update is working fine for you?

**Comment by kussione** [comment]
I will do it and keep you updated. Latest tomorrow. 
Stefan

**Comment by SukramJ** [comment]
So basically is think your problem is no related to you DLD.
Other states should not be updated too.

**Comment by eikowagenknecht** [comment]
> @eikowagenknecht State update is working fine for you?

Never checked it before. Seems like it's always reported as "unlocked" (checked in devtools) no matter the actual state. It's also not listed in the "Logbuch". No sys log entries for me though.

**Comment by SukramJ** [comment]
@eikowagenknecht Aaah. That's the only thing i found.

**Comment by kussione** [comment]
Hello together, I reinstalled the integration again and did a complete new configuration.
Now it is working as it should.
I have no idea what exactly solved the issue. 
1.) The new version 0.30.0
2.) The new configuration without TLS or
3.) The reinstallation 
Nevertheless: Thank you very much for the support. I am really happy about with your homematic solution. 

Best regards

Stefan

**Comment by SukramJ** [comment]
Thanks for feedback.
