### ISSUE TITLE
Wrong year in the changelog

### ISSUE THREAD

**Issue by breti** [SukramJ/hahomematic#279]
The year of the 2022 changelog file dates is wrong - it rolls over from 2021-12-31 to 2021-01-01...

**Comment by breti** [comment]
Oh I see it's fixed in the new repo. I'm sorry.

**Comment by breti** [comment]
My mistake. In the changelog in the custom_homematic repo the error still exists - for all entries of this year 2022 the year 2021 is given.

**Comment by SukramJ** [comment]
Just  fix it with a PR next time. Thanks
