### ISSUE TITLE
HmIP-Mod-HO doesn’t work

### ISSUE THREAD

**Issue by kwithus** [SukramJ/hahomematic#286]
Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
0.31.4

**Home Assistant version (if applicable):**
2022.2.5

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, ...):CCU 3
- OS (Original, RaspberryMatic, debmatic/...):Original
- Version: 3.61.5

**Problem-relevant configuration:**

Do you use tls?
Do you use callback?
Do you use username and password?yes
Which interfaces do you use?

**Describe the bug**
Wenn trying to open/close the Garagentor-opener it doesn’t work, it also shows wrong state
**To Reproduce**

**Relevant HA log entries**
```

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.core
Source: custom_components/hahm/cover.py:210 
Integration: Homematic(IP) Local (documentation, issues) 
First occurred: 09:53:45 (1 occurrences) 
Last logged: 09:53:45

Error executing service: <ServiceCall cover.close_cover (c:d5a2733b1e9dc8968428a0dbfa2e8be1): entity_id=['cover.garagentor_2']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1648, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1667, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 668, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 927, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 705, in _handle_entity_call
    await result
  File "/config/custom_components/hahm/cover.py", line 210, in async_close_cover
    await self._hm_entity.close_cover()
  File "/usr/local/lib/python3.9/site-packages/hahomematic/devices/cover.py", line 324, in close_cover
    await self._e_door_command.send_value(GARAGE_DOOR_COMMAND_CLOSE)
TypeError: object NoneType can't be used in 'await' expression


```

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by SukramJ** [comment]
Hi,
thanks for opening an issue.
Your device is currently missing in [pydevccu](https://github.com/danielperna84/pydevccu), so the currently implementation for HmIP-MOD-HO is only based on documentation.
Please export a device definition as  described [here](https://github.com/danielperna84/hahomematic/discussions/127#discussioncomment-1904703) and [here](https://github.com/danielperna84/hahomematic/discussions/127#discussioncomment-1905570)
Afterward please add the DD (2 files per device) to the issue or even better create a new issue at  [pydevccu](https://github.com/danielperna84/pydevccu).
Thanks.

**Comment by SukramJ** [comment]
Please test with 0.32.0.beta3.

**Comment by kwithus** [comment]
Ok, willing to do, however, no idea how to install this beta. I am currently on 0.31.4.
Where can I find a description how to install a beta?

**Comment by SukramJ** [comment]
In HACS on the Integration you can select „reload“. Then you can select Beta.

**Comment by kwithus** [comment]
Ok, I managed to install.
The basic functionality of the device is ok. Hitting up will open, hitting down will close, hitting stop will stop.
What I miss:
Beside the fact that the up-arrow is grey, when garage is open und the down arrow respectively, there is no I Formation about current state.
When opening/closing the garage the embedded light turns on, and will turn off after a while, the old integration did show this separately as light entity.
The garage door has beside open/close a third state, which can be triggered by the HMIP-Mod HO „Lüftungsstellung“. Would be great when this could be showed and controlled by HA as well.

thanks for your efforts

**Comment by SukramJ** [comment]
> Beside the fact that the up-arrow is grey, when garage is open und the down arrow respectively, there is no I Formation about current state.

Compared to a HmIP-BROLL your device does not provide information like opening/closing.

> When opening/closing the garage the embedded light turns on, and will turn off after a while, the old integration did show this separately as light entity.

I can't see how that might be realized in the old integration. @danielperna84 ???

>The garage door has beside open/close a third state, which can be triggered by the HMIP-Mod HO „Lüftungsstellung“. Would be great when this could be showed and controlled by HA as well.

Venting is not supported by HA.

**Comment by kwithus** [comment]
Just checked in CCU-WebUI, during ‚opening‘, ‚closing‘ the state shown is ‚unknown‘, so yes, will not be possible to show anything specific. Anyhow, I also use HomeKit, there I can see ‚opening‘/‚closing‘, I can only assume that this is shown based on the prior state (prior state=closed, changing to u known = ‚opening‘)
In regards to the light, this is basically channel 2 of the device
In regards to ventilation status, the state of channel 1 separates between open/ventilation/close.
As other devices (e.g. HmIP-SRH) differentiate between 3 states (open/tilted/closed) as well, which is also mirrored in HA and in HAhomeatic (offen/gekippt/geschlossen), wouldn’t that be applicable for this device as well?

**Comment by SukramJ** [comment]
HmIP-SRH is a sensor and a sensor can show anything.

**Comment by kwithus** [comment]
Ok, that’s beyond my knowledge/expertise ;-).
But is a ‚state‘ not a ‚state‘?

**Comment by SukramJ** [comment]
No, sensor is difrent from cover.
See dev docs for [cover](https://developers.home-assistant.io/docs/core/entity/cover).

**Comment by kwithus** [comment]
As a cover does have positions between open and close, would it be a solution to interpret the ventilation as a 90% position? (no idea how this could be implemented, I have no clue about coding, I am just quite good in copy/paste)

Von meinem iPad gesendet

**Comment by SukramJ** [comment]
I can add state of channel 2. That will be displayed as switch.

**Comment by kwithus** [comment]
Yes, that’s what I assumed, that channel 2 is a (light) switch, would be perfect!
Thanks

Von meinem iPad gesendet

**Comment by SukramJ** [comment]
Venting should currently be displayed as 10 % on the slider

Moving the slider > 50 should open the door.
Slider between 10 and 50 should go to vent position.
Slider between <10 should close the door

**Comment by SukramJ** [comment]
This is all about the slider, the displayed state is only open or closed

**Comment by kwithus** [comment]
Ok, seems to be the same ‚issue‘ as with the cover entities in general. I would love to see there the position as state, which is obviously at least currently not possible.
However, seeing this on the slider, could probably the starting point for a solution via templates or similar.


Von meinem iPad gesendet

**Comment by SukramJ** [comment]
> which is obviously at least currently not possible.

That true

Please have a look at [0.32.0.beta4](https://github.com/danielperna84/custom_homematic/releases/tag/0.32.0.beta4)
That should add support for state on ch2.

**Comment by Baxxy13** [comment]
I don't have that device, can not test.
But 2 thoughts about...

- The param "DOOR_STATE" on CH:1 should reflect the actual position [ CLOSED; OPEN; VENTILATION_POSITION; POSITION_UNKNOWN ] . Maybe this can be used someways. 
- Feedback of the "moving" garage-door could give the param "PROCESS", can be tested via the unignore file.
(i don't know if this works for this device)

**Comment by kwithus** [comment]
@ SukramJ: Just installed the new beta, the light (Chan 2) shows up and works as supposed to.
Thanks 
@ Baxxy13: yes, that’s what is shown in the CCU WebUI, unknown is shown when door is moving.
Thanks for your input

**Comment by kwithus** [comment]
> Venting should currently be displayed as 10 % on the slider
> 
> Moving the slider > 50 should open the door. Slider between 10 and 50 should go to vent position. Slider between <10 should close the door

I just tested this and can confirm, that’s how it works. I tested by sending set_position service calls.
For venting position the ‚current_position‘ shows 10.

**Comment by kwithus** [comment]
I just looked at the entities given by the ‚old‘ integration, there I do have an addition sensor.garagentor_door_state which does show the actual position as closed/open/ventilation
Maybe that’s possible with the new integration as well

**Comment by kwithus** [comment]
In Homematic channel 1 for this device has several data points.
The datapoint ‚section‘ shows 3 when the door is stopped, 5 when it’s currently opening, 2 when it’s currently closing 
No idea why this is not shown in the state, which shows unknown when moving

**Comment by SukramJ** [comment]
>  5 when it’s currently opening, 2 when it’s currently closing

How do you read the values? 

> No idea why this is not shown in the state, which shows unknown when moving

You mean door_state?
What is the value of door_state while door is moving?

**Comment by SukramJ** [comment]
Please test with 0.32.1.beta1
Contains sensor for door_state (Check translations!)
Should support opening/closing

**Comment by kwithus** [comment]
Tested 0.32.1.beta1, the sensor shows up and it does show the correct position, very nice
In regards to the datapoint ‚section‘, I do use the NodeRed Addon with node-contrib-ccu installed. That way I can see (mostly) all datapoints.

**Comment by kwithus** [comment]
Forgot to mention: the sensor shows up with a Generic name (hahm_00241a499de23c_1_door_state) not with the name garage_door

**Comment by SukramJ** [comment]
[Option2](https://github.com/danielperna84/hahomematic/wiki/Howto's) should fix your naming issue.
Thanks for delivering advanced information about the device.

**Comment by kwithus** [comment]
I have to say thanks for your work on this new integration.
Without you and others, I couldn’t use HA

Von meinem iPhone gesendet

**Comment by SukramJ** [comment]
Thanks a lot. Can this be closed?

**Comment by kwithus** [comment]
Yes, I think you brought it to work as good as possible 

Von meinem iPhone gesendet
