### ISSUE TITLE
HM-LC-Sw1-SM shows battery although it is operated at 230v

### ISSUE THREAD

**Issue by zngguvnf** [SukramJ/hahomematic#291]
Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
0.32.0

**Home Assistant version (if applicable):**
2022.2.6

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, ...): ProxmoxVE
- OS (Original, RaspberryMatic, debmatic/...): RaspberryMatic
- Version: 3.61.7.20220115

**Problem-relevant configuration:**

Do you use tls? No
Do you use callback? NN
Do you use username and password? Yes
Which interfaces do you use? NN

**Describe the bug**
According to the state (correct) the integrationn shows a battery state for HM-LC-Sw1-SM although this module can only be operated at 230V.

**To Reproduce**

**Relevant HA log entries**

**Expected behavior**
Just the state, no battery element.

**Screenshots**

**Additional context**

**Comment by SukramJ** [comment]
This is an auto-generated device, for which we interpret the given parameters.
The [paramset](https://github.com/danielperna84/pydevccu/blob/master/pydevccu/paramset_descriptions/HM-LC-Sw1-SM.json) contains a LOWBAT, so an entity LOWBAT gets generated.
So just disable the entity and ignore it.
