### ISSUE TITLE
HM-Sec-RHS window state not available in automation

### ISSUE THREAD

**Issue by smartmatic** [SukramJ/hahomematic#299]
Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
0.3.2

**Home Assistant version (if applicable):**
2022.2.6

**CCU version:**
- RaspberryMatic
- Version: 3.61.7.20220115

**Problem-relevant configuration:**

Do you use tls?
No
Do you use callback?
No
Do you use username and password?
Yes
Which interfaces do you use?
RF

**Describe the bug**
Window state could not selected within automation as trigger

**To Reproduce**
Go to HA
Create a new automation
Select HM-Sec-RHS as device

**Relevant HA log entries**
```


```

**Expected behavior**
open / close as state should be available as trigger

**Screenshots**
![Bildschirmfoto 2022-02-14 um 22 44 01](https://user-images.githubusercontent.com/74932663/153952753-d6fbda94-197d-4056-a491-91061fa82a88.png)

**Additional context**

**Comment by SukramJ** [comment]
> open / close as state should be available as trigger

But it is open / close / tilted. That's why it is a sensor and not a binary_sensor.
You can automate it, if you use `Zustand` aus `Auslösertyp` .

**Comment by smartmatic** [comment]
> > open / close as state should be available as trigger
> 
> But it is open / close / tilted. That's why it is a sensor and not a binary_sensor. You can automate it, if you use `Zustand` aus `Auslösertyp` .

Ah ok, in this case what do i need to select in order to use the state in the form?

![Bildschirmfoto 2022-02-15 um 19 56 01](https://user-images.githubusercontent.com/74932663/154129794-27dd1ce8-a6c7-4188-9ff2-5d6408a6446d.png)

![Bildschirmfoto 2022-02-15 um 19 56 56](https://user-images.githubusercontent.com/74932663/154129913-c696045a-6847-4ab9-bc16-8d403ca22372.png)

**Comment by Lemocin** [comment]
> what do i need to select

Nothing in the attributes, if it's the state of the entity. Just select the entity

If you want a trigger when it's opened, you have to input something(i think open or tilted) in the "Zu" field. 

If you want it to trigger on every state change, you could just leave everything empty except entity

**Comment by smartmatic** [comment]
Alright, thank you for the guideline.

**Comment by SukramJ** [comment]
Can this be closed?

**Comment by smartmatic** [comment]
Yes
