### ISSUE TITLE
Device lost friendly name after update to latest release

### ISSUE THREAD

**Issue by smartmatic** [SukramJ/hahomematic#303]
Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
0.34.2

**Home Assistant version (if applicable):**
2022.2.6

**CCU version:**

RaspberryMatic
Version: 3.61.7.20220115

**Problem-relevant configuration:**

Do you use tls?
No
Do you use callback?
No
Do you use username and password?
Yes
Which interfaces do you use?
RF

**Describe the bug**
Device are no longer displayed with friendly name. Instead a combination of Device_Serial is shown in the device section!

**To Reproduce**
I dont know if this behaviour can be reproduced on other sytems

**Relevant HA log entries**

**Expected behavior**
Device is displayed with friendly name given in Raspberrymatic which worked before the update.

**Screenshots**
![Bildschirmfoto 2022-02-16 um 21 16 32](https://user-images.githubusercontent.com/74932663/154350404-9e55357e-0fe1-4170-90f5-77ac0aff6821.png)

**Additional context**
No

**Comment by smartmatic** [comment]
solved by myself

**Comment by SukramJ** [comment]
I cannot reproduce you issue.
There are no relevant log entries?
Is port 80 open on you CCU?
