### ISSUE TITLE
The following integrations and platforms could not be set up:  hahm.climate

### ISSUE THREAD

**Issue by marc965** [SukramJ/hahomematic#312]
After installing last release 0.36.0 on core-2022.2.9, supervisor-2022.01.1 and Home Assistant OS 7.4 receiving this log entry:

`2022-02-24 17:57:37 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform hahm.climate: Platform not found (cannot import name 'HM_PRESET_MODE_PREFIX' from 'hahomematic.devices.climate' (/usr/local/lib/python3.9/site-packages/hahomematic/devices/climate.py)).`

All climate entities are dead:
![image](https://user-images.githubusercontent.com/85791333/155572421-ebf360f6-246e-4fee-90f7-075e9734e989.png)

**Comment by SukramJ** [comment]
I know, thats why i removed the **BETA** release shortly after release.
Just rollback to a non beta.

**Comment by marc965** [comment]
dont know how to do this :-(

**Comment by SukramJ** [comment]
In HACS:

1. click on "erneut herunterladen". 
2. Disable BETA.
3. select a version listed

**Comment by marc965** [comment]
thx, found it.
All is working again.
Always learning something new :-)
