### ISSUE TITLE
Buttons for presets "Maximal" and "Keine" for thermostats without function

### ISSUE THREAD

**Issue by eikowagenknecht** [SukramJ/hahomematic#315]
**custom_component/hahomematic version (if applicable):**
latest

**Home Assistant version (if applicable):**
latest beta

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, ...): ccu3
- OS (Original, RaspberryMatic, debmatic/...): latest raspberrymatic

**Describe the bug**

![image](https://user-images.githubusercontent.com/1475672/155843491-19fe701e-910e-4865-adfa-8e374fbb7b25.png)

The two crossed out buttons have no effect for thermostats in "Automatisch" mode.

**To Reproduce**
1. Click the buttons
2. Nothing happens

**Relevant HA log entries**
no warnings or errors

**Expected behavior**
Buttons should not exist for mode "Automatisch"

**Comment by Lemocin** [comment]
Edit: With the update to 0.36.0, Boost is broken for me too. With 0.35 i had the following behaviour, which should be the right:


Maximal (Boost) turns the heating valve for 300 seconds to 100%, like the button on the thermostat. Keine (None) is switching the thermostat back to the previous profile. 
![grafik](https://user-images.githubusercontent.com/4162496/155846092-fb5c3594-62d7-4556-bcb2-58f8a4606ebc.png)

**Comment by eikowagenknecht** [comment]
Weird, for some thermostats it seems to work (Boost / Maximum( and for some it doesn't. They are all the exact same model though.

**Comment by SukramJ** [comment]
Please retest with 0.36.1.beta

**Comment by Lemocin** [comment]
> Please retest with 0.36.1.beta

Works for me, thanks!

**Comment by eikowagenknecht** [comment]
Boost seems to work for me now as well. But why do we need "Keine" when all it does is go back to the previous Profile? Just to disable Boost?

**Comment by SukramJ** [comment]
You disable `Boost` with `Keine`

**Comment by eikowagenknecht** [comment]
Okey, then I'm closing this now :-)
