### ISSUE TITLE
Populate Groups with all attributes

### ISSUE THREAD

**Issue by sotatech** [SukramJ/hahomematic#316]
**Is your feature request related to a problem? Please describe.**
The homematic Heating Groups only show the temperature settings, despite numerous other entities being available, such as valve state, window state and battery state. In RaspberryMatic and in the old HA integration all these entities were available. I have 10 heating groups and each has multiple devices such as TRVs, thermostats and window sensors. The Group thus provides an overview of all these devices in one location which greatly simplifies automations. For example, some of my rooms have more than one TRV, but using the group I only have to check the Group status rather than the individual devices.

**Describe the solution you'd like**
I would like for the Heating Groups to show **all** the entities that are available.

**Describe alternatives you've considered**
This issue has been discussed here and dismissed: [(https://github.com/danielperna84/hahomematic/issues/97))](url)  The suggested solution was to use an Entities card but this does not address the issue that a better and simpler solution is available, and it does not help for automations.

**Additional context**
I know that this integration is under active development and I am greatly impressed with it. However, this is a feature **request** so I would like it included for future development. But I do not think it is for an integration to decide what attributes are visible to the user, it should be for the user to decide. It is easy for the user to enable or disable the entities as needed.

**Comment by SukramJ** [comment]
My mind did not change since the referenced issue.

> It is easy for the user to enable or disable the entities as needed.

I think there are users that may have a different opinion.

> But I do not think it is for an integration to decide what attributes are visible to the user, it should be for the user to decide

If you want more entities then [this](https://github.com/danielperna84/hahomematic/blob/devel/docs/unignore.md) feature is for you.

**Comment by sotatech** [comment]
I will try the unignore feature, but I do not see any of the attributes I am looking for in the list. I would just like Heating Groups to act the same as any other heating device such as a thermostat or TRV and report window position, valve and battery state. When setting up Homematic, ELV recommends that you use Heating Groups rather than handling each device separately.

With some of the other devices that your integration sets up in HA, it has disabled some attributes such as Dutycycle and RSSI that would only be of interest to advanced users.

All I am asking is for the same be applied to Heating Groups. Users who do not use these attributes will not be affected.

**Comment by SukramJ** [comment]
You should use [this](https://www.eq-3.de/downloads/download/homematic/hm_web_ui_doku/HmIP_Device_Documentation-1.38.4.pdf) document.

> ELV recommends that you use Heating Groups rather than handling each device separately.

The handling can be done with the existing climate entities for groups. This is what you need to **control** your groups.

What you want is a duplication (not reuse) of additional sensors, that are already available for individual devices.
The heating_group only contains aggregated values.

It is not that simple to disable these sensors by default, because here we need a lot of extra configuration.
It is simple to disable a sensor for a parameter named "RSSI_XX", but a lot of configuration to do the same for a sensor named state (window open) for a heating group.

**Comment by sotatech** [comment]
OK, I think we are not understanding each other. I an just looking for a feature that was available in the old integration and you reply by sending me a link to a document with 14,130 pages and telling me to use it.
I **requested** a feature and have been refused which is your right, so I will close this

**Comment by SukramJ** [comment]
Your right heating groups are not in this document.
Add these parameters to the unignore file

WINDOW_STATE
HUMIDITY
LEVEL
VALVE_STATE
ACTUAL_TEMPERATURE
LOW_BAT

**Comment by sotatech** [comment]
Thank you, that does exactly what I needed. Two small issues with this, the Valve State (which I do not need) has a % after it and the Valve Level is showing 0.13% instead of 13%. Should I open a separate issue for this?
![image](https://user-images.githubusercontent.com/9580066/155887381-143a9470-ed95-447e-86fa-a5873973ea4b.png)

**Comment by SukramJ** [comment]
Do you really need valve state. It's not used for HmIP devices in this Integration. For HM devices its a number and the percentage is OK.

**Comment by sotatech** [comment]
I do not need the valve state and I will not be using it. I do use the Level and in the Heating Group it shows 0.13% when the actual reading under TRV device shows 13%. As it's a percentage, it's range should be 0 to 100.
I think this was fixed for the TRVs in release 0.31.3.

**Comment by SukramJ** [comment]
LEVEL is not a problem. 
Just remove the VALVE_STATE and delete the entities after restart.

**Comment by sotatech** [comment]
OK, thanks I look forward to the fix. 
I removed VALVE_STATE and I decided to remove and reinstall the integration as I had a lot of stale entities on my test system. I did not bother to assign rooms to the devices in the HA prompt page where it lists the devices it has discovered as it takes too long, but the integration did it automatically for me from the rooms I had set in RasberryMatic - nice!

**Comment by SukramJ** [comment]
LEVEL should be fixed with 0.36.2

**Comment by sotatech** [comment]
Yes that worked, thanks again.
