### ISSUE TITLE
HmIP-BSL offers only on/off/toggle and in/decrease brightness, but no color as Action

### ISSUE THREAD

**Issue by Bastian007** [SukramJ/hahomematic#321]
For the Homematic IP device **HmIP-BSL** I can only find following actions offered in HA:
- turn on
- turn off
- toggle 
- increase brightness
- decrease brightness

but I can't see any action for automations to set the color.
![2022-03-04 01_25_24-Configuration – Automation](https://user-images.githubusercontent.com/12425311/156675770-7c912d1a-1fab-4c1b-88fc-3324670e7c2a.jpg)

The HA device controll offers the color picker where I can also change the color accordingly:
![2022-03-04 01_12_53-Configuration – Home Assistant](https://user-images.githubusercontent.com/12425311/156675771-f58efe1c-ca63-4a0b-a1bc-4f0bd19d3e40.jpg)

I am not sure if this an issue related to custom_homematic.

**custom_component/hahomematic version (if applicable):**
0.36.2

**Home Assistant version (if applicable):**
2022.3.0

**CCU version:**
- Model (Raspi4):
- OS (RaspberryMatic):
- Version: 3.61.7.20220226

**Comment by Lemocin** [comment]
I tried it and it's the same for other integrations, so i think thats a limitation of HA. (And a dropdown with every color would be too much)
Instead of the Actiontype "Device" you can use "call service" with the service light.turn_on. With this you can set everything you should need.

**Comment by Bastian007** [comment]
> Instead of the Actiontype "Device" you can use "call service" with the service light.turn_on. With this you can set everything you should need.

Thanks for the workaround, this is working as expected.
