### ISSUE TITLE
need config help

### ISSUE THREAD

**Issue by martinmolt** [SukramJ/hahomematic#324]
Hi, sorry for propably being stupid, I can't get the custom_homematic integration to work properly.
I only get 1 device with 11 entities (only the raspberrymatic itself). No devices.

HA running in docker on Pi4, raspberrymatic running on Pi2 (firewall is set to full access without authentication, no tls)
I only use hmip-devices and heating groups.
I guess there are no devices because I have to set callback ip and port? I don't know exactly how tho. 

Would be glad to get some help as the official homematic-integration is not that reliable imo.

cheers!

**Comment by Lemocin** [comment]
Are there any log entries?

**Comment by martinmolt** [comment]
> Are there any log entries?

in HA? None, when creating the integration it just works and not a single enty in full HA log.

**Comment by Lemocin** [comment]
Can you post screenshots of your config? Does the normal homematic integration work? If yes, is custom_homematic configured with the same values?

You say, you have to set the callback. May i ask you why?

**Comment by martinmolt** [comment]
![image](https://user-images.githubusercontent.com/7353549/156939534-0387d9be-7035-4073-81ee-e8136ac38dd4.png)
![image](https://user-images.githubusercontent.com/7353549/156939553-8551938d-b583-48fe-a344-50f7842522fd.png)

Kind of. With the default homematic integration it does not update the values, only once when restarting the integration/HA. Also values from HA to homematic won't work. That's why I wanted to try out this one.

And yes, same values as with default integration. Same ports, group path etc.

**Comment by martinmolt** [comment]
> You say, you have to set the callback. May i ask you why?

HA is running inside docker. As from the documentation I thought that might be the issue.

**Comment by SukramJ** [comment]
The problem is related to your HA installation with Docker. I guess you don‘t use the host network for your HA. 
Best option is to switch to Docker host network or use a supervised Installation of HA.
Or you create an additional port mapping in your HA Docker e.g. 45678:45678 and use 45678 a callback port an you HA ip as callback ip in integration config.

 Please fill out the issue template next time.

**Comment by Lemocin** [comment]
I am also running ha with docker (Homeassistant Supervised). I didn't need it. You can look in Home assistant Configuration - Settings - General - Network. Normally if there is a IP beginning with 192.168, you are using the host network like described in the HA docs. Then you should not need callback. But if it starts with 172. you will need to set it to the IP from the ha Pi.

**Comment by SukramJ** [comment]
The supervised or HAOS installation runs the HA container in the host network.This also solves multiple other issues with device discovery.

**Comment by Lemocin** [comment]
> The supervised or HAOS installation runs the HA container in a host network.This also solves multiple other issues with device discovery.

The [official container installation guide](https://www.home-assistant.io/installation/raspberrypi#install-home-assistant-container) also runs it with the host network. 
But i agree, HAOS and supervised are the better solutions in my opinion.

**Comment by martinmolt** [comment]
switched to host network, works fine now. 
Thanks guys! :)
