### ISSUE TITLE
Missing attributes

### ISSUE THREAD

**Issue by THorst92** [SukramJ/hahomematic#325]
Hello,

thank you for this great integration!
I have a wish concerning attributes/entities which might be interesting to add:
- for all devices: RSSI of the device (with the old integration available in the attributes)
- for eTRV: valve position
Would it maybe also be possible to add a sensor for the eTRV window open detection?

Best regards,

Thorsten

**Comment by SukramJ** [comment]
Just check the deactivated entities of each device.

**Comment by THorst92** [comment]
Thank you! My fault... sorry!
