### ISSUE TITLE
incomplete restart of integration after host restart

### ISSUE THREAD

**Issue by JoMass** [SukramJ/hahomematic#326]
**custom_component/hahomematic version :**
0.36.3

**Home Assistant version (if applicable):**
Version	core-2022.3.3
Installationstyp	Home Assistant OS
Python-Version	3.9.9
Betriebssystemfamilie	Linux
Betriebssystem-Version	5.10.92-v8
Host-Betriebssystem	Home Assistant OS 7.4
Supervisor-Version	supervisor-2022.01.1
Installierte Add-ons	Terminal & SSH (9.3.0), File editor (5.3.3), Node-RED (11.0.4), ESPHome (2022.2.6), Samba Backup (5.0.0), Grafana (7.4.1), RaspberryMatic CCU (3.61.7.20220226), Glances (0.14.2)

Do you use tls? no
Do you use callback?  no
Do you use username and password? yes
Which interfaces do you use?  browser edge Win 11

**Describe the bug**
After a full OS restart of the Homeassistant OS  the CCU devices are loaded correctly, however  even after waiting >10 minutes, the system variables are marked as "unavailable" in "History". After a additional  core restart, they are then also available again.

**To Reproduce**
- Restart HAS OS 
- Wait till Raspberrymatic is fully loaded
- Check System Variables in History
- Restart HAS CORE
- Recheck system variables in History

**Screenshots**
![image](https://user-images.githubusercontent.com/30499961/157288013-f76d766f-2dfa-40ac-b6cd-a75c60e3f399.png)

**Comment by SukramJ** [comment]
Please add logs.

**Comment by JoMass** [comment]
The config LOG states  "Es gibt keine neuen Probleme!"

the core LOg has a warning and nothing more; , but this might be normal:  
2022-03-08 16:31:19 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hahm which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

[de838cd8-raspberrymatic-2022-03-08.log](https://github.com/danielperna84/hahomematic/files/8208778/de838cd8-raspberrymatic-2022-03-08.log)

**Comment by SukramJ** [comment]
I need the HA logs **before** restart. 
Click on full logs (not only the abstract).

**Comment by JoMass** [comment]
[CoreLog.txt](https://github.com/danielperna84/hahomematic/files/8208883/CoreLog.txt)

die o.k ? oder weitere ?

**Comment by SukramJ** [comment]
Ich schau mal.

**Comment by JoMass** [comment]
![image](https://user-images.githubusercontent.com/30499961/157306949-06d59000-b522-4f09-8bde-9ddc484c88f4.png)

**Comment by SukramJ** [comment]
Should be fixed with [0.36.4](https://github.com/danielperna84/custom_homematic/releases/tag/0.36.4)

**Comment by JoMass** [comment]
Just performed a restart of the host. I’d like to confirm, the issue has been resolved.  Thank you
