### ISSUE TITLE
Enabled HM-RF blocks HMIP-RF

### ISSUE THREAD

**Issue by NemesisRE** [SukramJ/hahomematic#329]
**custom_component/hahomematic version (if applicable):**
0.36.4

**Home Assistant version (if applicable):**
2022.3.4

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, ...): Docker x86
- OS (Original, RaspberryMatic, debmatic/...): RaspberryMatic
- Version: 3.61.7.20220226

**Problem-relevant configuration:**

Do you use tls? No
Do you use callback? yes
Do you use username and password? yes
Which interfaces do you use? 

**Describe the bug**
If you enable HM-RF in addition to HMIP-RF but only have homematic ip devices the integration will not find any devices but instead will forever try to connect to HM-RF 

**To Reproduce**
Enable HM-RF in addition to HMIP-RF without HM-RF devices on CCU

**Relevant HA log entries**
```
2022-03-14 12:06:34 | 2022-03-14 12:06:34 WARNING (MainThread) [hahomematic.central_unit] check_connection: No clients exist. Trying to create clients for server CCU
2022-03-14 12:06:34 | 2022-03-14 12:06:34 WARNING (MainThread) [hahomematic.central_unit] create_clients: Failed to create clients for central [('Failed to get backend version. Not creating client: http://172.20.109.2:2001',)].
```

**Expected behavior**
I would expect that the HMIP-RF devices would be found anyway and it is not stuck on trying to get the HM-RF connection to work

**Comment by danielperna84** [comment]
In my opinion blocking in this case is actually a good thing. If you configure the integration to expect devices of a specific type and don't get a result, then there is a somewhat critical error. If the integration would start anyways, the problem might not be noticed, or later than it should be noticed.

That being said, it might also be reasonable to still continue in such a case and only retry a backend that does not respond.

In any case, the current behavior is not incorrect / a bug, it's by design in a way. It's left to discuss if this design makes sense.

What's your opinion on this @SukramJ ?

**Comment by Baxxy13** [comment]
Das Problem wird hier sein das die Zentrale kein Interface "BidCos-RF" besitzt.
Das kommt normalerweise nur vor wenn ein HmIP-RFUSB-TK (Telekom-Variante) oder ein älteres System mit HmIP-RFUSB (und BidCos inkompatibler Firmware) eingesetzt wird. 
An fehlenden HM-Geräten liegt es eher nicht, denn wenn das BidCos-Interface vorhanden ist hat man normalerweise auch mindestens ein Gerät (die virtuelle Fernbedienung HM-RCV-50 BidCoS-RF).

Das die Integration hängen bleibt wenn sie sich an ein nicht vorhandenes Interface binden soll ist natürlich nicht schön, aber nachvollziehbar. 

Sollte man vielleicht dokumentieren falls ich die Problematik auf den Punkt getroffen habe.

**Comment by NemesisRE** [comment]
@danielperna84 makes sense but is confusing, when I saw the integration defaults I thought it would be alright but instead nothing showed up. And you are right if it is by design that does not try the other backends then it is not a bug instead I would say it would be a feature request for convince and ease of use.

@Baxxy13 I will keep it english who knows who has the same problem and is not familiar with the german language ^^
I use the HmIP-RFUSB (Homematic IP ELV ARR-Bausatz RF-USB-Stick für Alternative Steuerungsplattformen HmIP-RFUSB 01.2021) with FW 4.4.16
If the stick supports BidCos maybe you can give me a hint what could be wrong.

**Comment by Baxxy13** [comment]
Ich habe das jetzt mal durchgetestet und konnte die Problematik nicht nachstellen.
(hahomematic 0.37.4)

- frische RaspberryMatic VM (Nightly 16.03.) mit HmIP-RFUSB aufgesetzt
- den HmIP-RFUSB aus dem Posteingang geholt
- ein HmIP Gerät (HmIP-SCI) angelernt
- die per Auto-Discovery gefundene RM-VM integriert und dabei Homematic IP und Homematic (Bidcos-RF) ausgewählt

Es wurden alle 4 "Geräte" korrekt gefunden.
HM-RCV-50 BidCoS-RF; HmIP-RCV-50 HmIP-RCV-1; HmIP-RFUSB; HmIP-SCI

Was bei Dir da klemmt kann ich leider nicht sagen. 
Ob das BidCos-RF Interface bei Dir vorhanden ist kannst du am Vorhandensein der HM-RCV-50 BidCoS-RF prüfen.
Auch im "Geräte anlernen" Fenster sieht man das, dort müssen die beiden Felder für HM Geräte anlernen sichtbar sein.

**Comment by NemesisRE** [comment]
Ok there are no HM-RCV-50 BidCoS-RF but the there are no buttons to learn HM devices so no BidCoS-RF Interface. Something seems to be borked regarding BidCoS-RF somehow... Would be nice to have a feature that should be working but luckily I currently don't own any HM device so I will ignore that for the moment. Thank you anyway for your help.

Regarding the initial request of the ticket I would still consider it good to treat each backend on its own and not let one backend stop the other from working, I even think that would make it more fail prove when it replaces the HA core integration some day and more inexperienced users use it.

**Comment by SukramJ** [comment]
I think allow creation of the other interfaces and sending a persistent notification about the unavailable interface might be the best option.

**Comment by SukramJ** [comment]
Should be better with 0.37.3. Please test and close this issue if OK.

**Comment by NemesisRE** [comment]
Looks like it works and the notification is a neat feature :)

Thank you all for your great work!
