### ISSUE TITLE
Strange behavior: rfd Error on startup and new piMatic device detected

### ISSUE THREAD

**Issue by marc965** [SukramJ/hahomematic#333]
**custom_component/hahomematic version (if applicable):**
0.36.3

**Home Assistant version (if applicable):**
core-2022.3.5

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, ...): CCU3
- OS (Original, RaspberryMatic, debmatic/...): RaspberryMatic CCU
- Version: Current version: 3.61.7.20220226

**Problem-relevant configuration:**

Do you use tls? no
Do you use callback? no
Do you use username and password? yes
Which interfaces do you use? rf + ip

Since lastest Version i get a new devices detected:
![image](https://user-images.githubusercontent.com/85791333/158793557-1998a102-69ff-42a2-a528-1c9eddb21bc4.png)

And some trouble when Homematic OS is restarting and RaspberryMatic is coming up:
```
Mounting /data as /usr/local (Home Assistant Add-On): OK
Identifying host system: oci, OK
Initializing RTC Clock: onboard, OK
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Initializing System: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.3, OK
Identifying Homematic RF-Hardware: ......HmRF: RPI-RF-MOD/HB-RF-ETH@192.168.133.110, HmIP: RPI-RF-MOD/HB-RF-ETH@192.168.133.110, OK
Updating Homematic RF-Hardware: RPI-RF-MOD: 4.4.12, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting sshd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: ...OK
Starting rfd: ....................ERROR
Starting HMIPServer: ........OK
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting NeoServer: disabled
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.61.7.20220226 (raspmatic_oci_amd64)
```

The CCU is warning because of restart of rfd!

Never seen this before...

Should i update to 0.37.0?
What should i do with the second piMatic detected? ignoring?

**Comment by marc965** [comment]
Seit einer Stunde ungefähr geht gar nichts mehr

```
Mounting /data as /usr/local (Home Assistant Add-On): OK
Identifying host system: oci, OK
Initializing RTC Clock: onboard, OK
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Initializing System: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.3, OK
Identifying Homematic RF-Hardware: ......HmRF: RPI-RF-MOD/HB-RF-ETH@192.168.133.110, HmIP: RPI-RF-MOD/HB-RF-ETH@192.168.133.110, OK
Updating Homematic RF-Hardware: RPI-RF-MOD: 4.4.12, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting sshd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: ...........ERROR
Starting rfd: ....................ERROR
Starting HMIPServer: .....................................................................................................ERROR
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting NeoServer: disabled
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.61.7.20220226 (raspmatic_oci_amd64)
```

![image](https://user-images.githubusercontent.com/85791333/158797180-6ba03f00-b5e1-4f23-9dae-83d61fcc33e1.png)

**Comment by SukramJ** [comment]
Du denke Du hast HAOS bzw. den Supervior aktualisiert, und dadurch kann die Integration jetzt per Autodiscovery dein Homematic Addon auffinden. Hier kann Du einfach auf ignorieren klicken.

Bei den Log-Meldungen im Addon kann ich dir leider nicht weiterhelfen. Am besten im [Homematic Forum](https://homematic-forum.de/forum/viewforum.php?f=65) nachfragen, bzw. im [Gitub-Repo](https://github.com/jens-maus/RaspberryMatic) ein Issue anlegen.

**Comment by SukramJ** [comment]
In Bezug auf die Integration sehe ich hier keinen Handlungsbedarf mehr. 
Kann das Ticket geschlossen werden.

**Comment by marc965** [comment]
Ja, kann geschlossen werden. Ich habe das neu erkannte device einfach ignoriert.
Was die Störung angeht, die den Totalausfall ausgelöst hat, das lag an der RPI-RF-MOD/HB-RF-ETH Kombination, die war wohl abgestürzt. Nach einem Neustart der Platine ging alles wieder.
