### ISSUE TITLE
Warning in the RM-Logs every time i use "Integration neu laden" or "Homeassistant neu starten"

### ISSUE THREAD

**Issue by SukramJ** [SukramJ/hahomematic#340]
Since changes for this issue i got a warning in the RM-Logs every time i use "Integration neu laden" or "Homeassistant neu starten"
It's just a warning, but was not seen before and should not be there.
Don't know if it's maybe problematic.

```
Mar 18 15:17:37 RM-Test-Pi3Bplus-27 local0.warn ReGaHss: WARNING: cannot clear session with id '1bWXOdzQux' [ExecSystem():iseESPexec.cpp:3764]
Mar 18 15:17:49 RM-Test-Pi3Bplus-27 user.err rfd: XmlRpc fault calling system.listMethods({"RM-Test-Pi3Bplus-27-BidCos-RF"}) on http://192.168.113.29:43959/RPC2:[faultCode:1,faultString:"<class 'TypeError'>:system_listMethods() takes 1 positional argument but 2 were given"]
Mar 18 17:51:19 RM-Test-Pi3Bplus-27 local0.warn ReGaHss: WARNING: cannot clear session with id '1FObNXZ2rw' [ExecSystem():iseESPexec.cpp:3764]
Mar 18 17:51:38 RM-Test-Pi3Bplus-27 user.err rfd: XmlRpc fault calling system.listMethods({"RM-Test-Pi3Bplus-27-BidCos-RF"}) on http://192.168.113.29:36839/RPC2:[faultCode:1,faultString:"<class 'TypeError'>:system_listMethods() takes 1 positional argument but 2 were given"]
Mar 18 17:56:05 RM-Test-Pi3Bplus-27 local0.warn ReGaHss: WARNING: cannot clear session with id 'nD1aRrKtFb' [ExecSystem():iseESPexec.cpp:3764]
Mar 18 17:56:17 RM-Test-Pi3Bplus-27 user.err rfd: XmlRpc fault calling system.listMethods({"RM-Test-Pi3Bplus-27-BidCos-RF"}) on http://192.168.113.29:32829/RPC2:[faultCode:1,faultString:"<class 'TypeError'>:system_listMethods() takes 1 positional argument but 2 were given"] 
```

_Originally posted by @Baxxy13 in https://github.com/danielperna84/hahomematic/issues/328#issuecomment-1072607285_

**Comment by SukramJ** [comment]
1. `XmlRpc fault calling system.listMethods` is very old, and has already been a warning with the old integration. 
I think this is related to the Python XmlRPC-Server implementation. Here i have currently no idea.

2. `ReGaHss: WARNING: cannot clear session with id '1bWXOdzQux'` seems to be new and I guess `1bWXOdzQux` is the JSON Session ID. Here i can add a Session.logout before shutdown.

**Comment by SukramJ** [comment]
0.37.4 should fix `ReGaHss: WARNING: cannot clear session`

**Comment by SukramJ** [comment]
@Baxxy13 please retest

**Comment by SukramJ** [comment]
0.37.5 should fix `XmlRpc fault calling system.listMethods`

**Comment by Baxxy13** [comment]
zu 1. 
`XmlRpc fault calling system.listMethods` taucht nun gar nicht mehr auf. Sehr gut.

zu 2.
`ReGaHss: WARNING: cannot clear session with id '1bWXOdzQux'` sehe ich noch ab und zu, aber nicht mehr bei jedem Neustart von HA oder Neu Laden der Integration.
Habe aber noch kein Muster erkannt, gucke ich mir morgen nochmal in Ruhe an.

**Comment by Baxxy13** [comment]
zu 2.
Die Warnung scheint immer dann noch zu kommen wenn ich beide Optionen (HA Neu Starten / Integration Neu laden) in einer bestimmten Reihenfolge nutze.

Also: 
"Integration Neu laden" --> Warnung erscheint nicht
dann...
"HA Neu Starten" --> Warnung erscheint

Jeder weiter Neustart / Reload bringt keine Warnung, erst wenn die obige Reihenfolge eingehalten wird gibt es wieder eine.
Merkwürdig.

Da man das i.d.R. nicht so exzessiv nutzt wie ich hier beim testen und man normalerweise nur den HA nach Update der Integration neu startet kann man das ignorieren... würde ich sagen.

**Comment by SukramJ** [comment]
Passt
