### ISSUE TITLE
Can not connect

### ISSUE THREAD

**Issue by Smart86** [SukramJ/hahomematic#343]
I get this errors:

Logger: hahomematic.json_rpc_client
Source: /usr/local/lib/python3.9/site-packages/hahomematic/json_rpc_client.py:127
First occurred: 08:06:15 (6 occurrences)
Last logged: 08:07:16

login: Unable to open session: {'name': 'JSONRPCError', 'code': 501, 'message': 'invalid credentials or too many sessions'}

Logger: hahomematic.json_rpc_client
Source: /usr/local/lib/python3.9/site-packages/hahomematic/json_rpc_client.py:153
First occurred: 08:06:15 (6 occurrences)
Last logged: 08:07:16

post: Error while logging in via JSON-RPC.

![Settings_HASS](https://user-images.githubusercontent.com/59134553/159111504-f2d0a793-0d9a-40fc-979e-871e3b4d940f.JPG)
![Settings_HASS1](https://user-images.githubusercontent.com/59134553/159111509-799b9d36-1abc-4ed2-8cff-94b0ead27ad4.JPG)
![Setings_homematic](https://user-images.githubusercontent.com/59134553/159111515-9dc4f60e-92e5-4b83-baf2-fb1cdf221679.JPG)

I tried it with and without authentification in Homematic and also with SSL and without.

**Comment by SukramJ** [comment]
Please use the issue template!

**Comment by SukramJ** [comment]
First line in `Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.`

> login: Unable to open session: {'name': 'JSONRPCError', 'code': 501, 'message': 'invalid credentials or too many sessions'}

--> [Authentication](https://github.com/danielperna84/custom_homematic#authentication)

--> [Configuration Variables](https://github.com/danielperna84/custom_homematic#configuration-variables)
Why do you set a callback?

**Comment by Smart86** [comment]
Thank you SukramJ.

Authentication is OK.  It is not activated and the password has no special characters.

I don`t want a callback. When i delete the entry and save the dialog the entry apperas again.  Now i tried to reinstall the integration and set no callback. But its the same error.

Logger: hahomematic.json_rpc_client
Source: /usr/local/lib/python3.9/site-packages/hahomematic/json_rpc_client.py:127
First occurred: 08:30:31 (10 occurrences)
Last logged: 08:30:32

login: Unable to open session: {'name': 'JSONRPCError', 'code': 501, 'message': 'invalid credentials or too many sessions'}

Logger: hahomematic.json_rpc_client
Source: /usr/local/lib/python3.9/site-packages/hahomematic/json_rpc_client.py:153
First occurred: 08:30:31 (10 occurrences)
Last logged: 08:30:32

post: Error while logging in via JSON-RPC.

**Comment by SukramJ** [comment]
> It is not activated

It must be activated!

**Comment by Smart86** [comment]
Sorry! I understood that if authentication is not active, the fields are ignored. It works now! Thanks!!!
