### ISSUE TITLE
No values availabel when HS485D interface activ

### ISSUE THREAD

**Issue by addy38** [SukramJ/hahomematic#346]
DONT'T DELETE THIS.
Please answer all questions as good as possible.

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
0.37.5

**Home Assistant version (if applicable):**
2022.3.5

**CCU version:**
- CCU3...):
- OS (RaspberryMatic,):
- Version: 3.59.6.20211009

**Problem-relevant configuration:**

Do you use tls? no
Do you use callback? no
Do you use username and password? yes
Which interfaces do you use? HM-Funk, HM-wired, HM-IP, groups

**Describe the bug**
I' am not able to get values from my HM-wired (classic) interface. I setup in the integration the configuration "aktiviere HS485D (HM-Wired)" and restart Home Assistant. 
After Home Assistant reboot I loose the communication with **all** my HM interfaces. 

When I re-disable the HM-wired interface and reboot Home Assistant, I get again all the other value

**Relevant HA log entries**
```
create_clients: Failed to create client for central [('Failed to get backend version. Not creating client: http://192.168.178.27:2000',)].
Logger: hahomematic.central_unit
Source: /usr/local/lib/python3.9/site-packages/hahomematic/central_unit.py:298
First occurred: 17:43:17 (1 occurrences)
Last logged: 17:43:17

```

**Expected behavior**

**Screenshots**

**Additional context**
In the CCU3 Firewall it doesnt mattter if all Ports are open or closed. Port 2000 is also in "Port Freigabe"

**Comment by SukramJ** [comment]
> After Home Assistant reboot I loose the communication with all my HM interfaces.

Please retest 0.38.0. Shoud fix this.

Afterwards add new HA logs and click on **full logs**.

**Comment by addy38** [comment]
I update to 0.38.0 , reboot Home Assistant.
When I activate the interface in the configuration and press "Absenden" I get Error "Unerwarteter Fehler"
In the Log I get an ERROR (MainThread) [custom_components.hahm.config_flow] Unexpected exception  

Full Log enclosure
[Log_1.txt](https://github.com/danielperna84/hahomematic/files/8311049/Log_1.txt)

**Comment by SukramJ** [comment]
The log is strange.

1. Please delete the integration.
2. Update update the component in hacs to 0.38.1
3. restart
4. Add the integration  (start without HS485D)

**Comment by addy38** [comment]
nothing changed
1. delete in Settings the Integration
2. Update in HACS to 0.32.2
3. Restart Home Assistant
4. I dont need to add the Integration,it was already detected
5.  Log is ok, normal values (HM-IP, .....) present
6. try to activate the HS485D interface, still get "Unerwarteter Fehler" 
7. Reboot Home Assistant
8. Log ok
9. try to activate the HS485D interface, still get "Unerwarteter Fehler" 
10. in the CCU Syslog I get "local0.warn ReGaHss: WARNING: cannot clear session with id 'BapLb5CIpf' [ExecSystem():iseESPexec.cpp:3761]"

**Comment by SukramJ** [comment]
Please add new logs HA logs (full log).
Basically what i saw from your previous logs is that that CCU port 2000 cannot be reached.
This released addresses, that an unavailable port 2000 does not block other parts of the integration.
Please post screenshots of you CCU Firewall settings.
Do you run RM in Docker?
Please ensure, with another external application like Homematic Manager , that port 2000 and the corresponding service in CCU/RM is running.

**Comment by addy38** [comment]
Log and Firewall setting 
![Bildschirmfoto vom 2022-03-20 19-53-49](https://user-images.githubusercontent.com/86205137/159177958-feecb971-5042-41b8-98aa-8604da41ff42.png)
enclosure

No, RM run at an CC3, Home Assistant run in VM at Synology

I also Run Historian in Docker at the Syn, there I get all values from the wired interface, so I'am sure that Port 2000 at the CCU3 is fine 


[LOG_2.txt](https://github.com/danielperna84/hahomematic/files/8311949/LOG_2.txt)

**Comment by SukramJ** [comment]
I checked the API based on errors in your logs:
BidCos-Wired (Port 2000) does not support the API method getVersion that we use to identify the backend system (CCU/Homegear).
So for now BidCos-Wired is not supported with this integration, but i think it's a rather small thing to fix it. Hopefully a new release this week adds support for BidCos-Wired.

I think you are the first one, I know of, who uses BidCos-Wired with this integration, so i need to come back to you, if this is ok, to do some testing.

**Comment by addy38** [comment]
no problem, of course I will do some testing

**Comment by SukramJ** [comment]
Please try 0.38.3

**Comment by addy38** [comment]
- update to 0.38.3
- activate HS485D, no Error message
[LOG_3.txt](https://github.com/danielperna84/hahomematic/files/8317441/LOG_3.txt)

- I get no values Home Assistant
- restart Home Assist
- get an Error in the CCU3 Syslog, see enclosure Log_3 
- still no values in Home Assistant
- when I check the configuration, Option HS485D is again disabled

**Comment by SukramJ** [comment]
> * when I check the configuration, Option HS485D is again disabled

It's not disabled. The 2nd page only displays the defaults.


Please add **HA** full log.
Please add diagnostic information( Goto device overview, open any device, "Diagnose informationen herunterladen"). Here you can see your actual configuration.

Just to be sure: You get updates for your wireless devices?

Please execute this [script](https://github.com/danielperna84/hahomematic/blob/devel/hahomematic/rega_scripts/fetch_all_device_data.fn) in CCU WebUI. Please post some lines from any wired device.

**Comment by addy38** [comment]
[LOG_6.txt](https://github.com/danielperna84/hahomematic/files/8318106/LOG_6.txt)
Logs enclosure
- I hope I unterstood everything you require, otherwise please explaine more detailed
- I get updates from the normal HM and HM-IP devices, Systemvaraibles
[LOG_4.txt](https://github.com/danielperna84/hahomematic/files/8318049/LOG_4.txt)
[LOG_5.txt](https://github.com/danielperna84/hahomematic/files/8318050/LOG_5.txt)

**Comment by SukramJ** [comment]
The interface name is wrong, so the initial load doesn't work, but the entities should be updated by callback events.
What happens if you change something via CCU WebUI?

**Comment by addy38** [comment]
I cant find in Home Assistant any deivice or entitie from BidCos wired. 
Also when I change the state of any wired device, still not present in Home Assistant

**Comment by SukramJ** [comment]
LOG3 is interesting, but it looks cut off. I don't see an error reason. Please add more from CCU log.

**Comment by addy38** [comment]
LOG_3 was done from the Syslog in CUXD, I believe it is incomplete. Enclosure the Log direct from CCU3. 
192....35 is Home Assitant in the Syn VM
[LOG_7.txt](https://github.com/danielperna84/hahomematic/files/8318359/LOG_7.txt)

**Comment by SukramJ** [comment]
I guess LOG_7 is hm_server.log, but it doesn't contain the messages from LOG_3.
Please also add /var/log/messages.

**Comment by addy38** [comment]
Log_8 is the full log which I can get at Syslog in CUXD
[LOG_8.txt](https://github.com/danielperna84/hahomematic/files/8318437/LOG_8.txt)
[messages.txt](https://github.com/danielperna84/hahomematic/files/8318467/messages.txt)

**Comment by addy38** [comment]
after one more HASS reboot, I get also some Errors in the HASS Log
[LOG_9.txt](https://github.com/danielperna84/hahomematic/files/8318599/LOG_9.txt)

**Comment by SukramJ** [comment]
I think the key problem is in LOG_3` ccu3 user.err hs485d: XmlRpcClient error calling newDevices`
This is required for device creation but the ccu has only cut off logs.

Please add this to `configuration.yml`  to get verbose logs in HA.

```
logger:
  default: info
  logs:
    hahomematic: info
    #hahomematic.json_rpc_client: debug
    hahomematic.xml_rpc_proxy: debug
    #hahomematic.xml_rpc_server: debug
    hahomematic.central_unit: debug
```

**Comment by addy38** [comment]
log after I add this and reboot HASS
[LOG_10.txt](https://github.com/danielperna84/hahomematic/files/8318749/LOG_10.txt)

**Comment by SukramJ** [comment]
From  Log_10 it looks like you have wired devices in HA, but with no initial data load

**Comment by addy38** [comment]
but I cant see anything about it in HASS, also when I do an action at this device

**Comment by SukramJ** [comment]
Are they listed under "Geräte"?

```
2022-03-21 20:28:12 DEBUG (MainThread) [hahomematic.central_unit] create_devices: Skipping device BidCoS-Wir on ccu3-HS485D, already exists.
2022-03-21 20:28:12 DEBUG (MainThread) [hahomematic.central_unit] create_devices: Skipping device JEQ0271573 on ccu3-HS485D, already exists.
2022-03-21 20:28:12 DEBUG (MainThread) [hahomematic.central_unit] create_devices: Skipping device JEQ0271589 on ccu3-HS485D, already exists.
2022-03-21 20:28:12 DEBUG (MainThread) [hahomematic.central_unit] create_devices: Skipping device JEQ0271614 on ccu3-HS485D, already exists.
2022-03-21 20:28:12 DEBUG (MainThread) [hahomematic.central_unit] create_devices: Skipping device JEQ0271769 on ccu3-HS485D, already exists.
2022-03-21 20:28:12 DEBUG (MainThread) [hahomematic.central_unit] create_devices: Skipping device JEQ0271786 on ccu3-HS485D, already exists.
2022-03-21 20:28:12 DEBUG (MainThread) [hahomematic.central_unit] create_devices: Skipping device JEQ0271797 on ccu3-HS485D, already exists.
2022-03-21 20:28:12 DEBUG (MainThread) [hahomematic.central_unit] create_devices: Skipping device JEQ0272106 on ccu3-HS485D, already exists.
2022-03-21 20:28:12 DEBUG (MainThread) [hahomematic.central_unit] create_devices: Skipping device JEQ0272107 on ccu3-HS485D, already exists.
2022-03-21 20:28:12 DEBUG (MainThread) [hahomematic.central_unit] create_devices: Skipping device JEQ0272112 on ccu3-HS485D, already exists.
2022-03-21 20:28:12 DEBUG (MainThread) [hahomematic.central_unit] create_devices: Skipping device JEQ0272200 on ccu3-HS485D, already exists.
2022-03-21 20:28:12 DEBUG (MainThread) [hahomematic.central_unit] create_devices: Skipping device JEQ0272576 on ccu3-HS485D, already exists.
2022-03-21 20:28:12 DEBUG (MainThread) [hahomematic.central_unit] create_devices: Skipping device JEQ0272639 on ccu3-HS485D, already exists.
2022-03-21 20:28:12 DEBUG (MainThread) [hahomematic.central_unit] create_devices: Skipping device JEQ0272688 on ccu3-HS485D, already exists.
2022-03-21 20:28:12 DEBUG (MainThread) [hahomematic.central_unit] create_devices: Skipping device JEQ0272722 on ccu3-HS485D, already exists.
2022-03-21 20:28:12 DEBUG (MainThread) [hahomematic.central_unit] create_devices: Skipping device LEQ0978498 on ccu3-HS485D, already exists.
2022-03-21 20:28:12 DEBUG (MainThread) [hahomematic.central_unit] create_devices: Skipping device LEQ0979858 on ccu3-HS485D, already exists.
2022-03-21 20:28:12 DEBUG (MainThread) [hahomematic.central_unit] create_devices: Skipping device LEQ1323138 on ccu3-HS485D, already exists.
2022-03-21 20:28:12 DEBUG (MainThread) [hahomematic.central_unit] create_devices: Skipping device MEQ0726104 on ccu3-HS485D, already exists.
2022-03-21 20:28:12 DEBUG (MainThread) [hahomematic.central_unit] create_devices: Skipping device OEQ2606590 on ccu3-HS485D, already exists.
```

**Comment by addy38** [comment]
no, no wired device listed under "Geräte"

**Comment by SukramJ** [comment]
That's confusing.

- Please update to 0.38.4
- restart HA
- go into the Integration Configuration and configure your Interfaces
- restart HA

I don't think this fixes the issue, but it uses the correct interface names.

**Comment by addy38** [comment]
I get wired devices :+1: 
In the configuration the label for the wired option is missing.

**Comment by SukramJ** [comment]
OK.
The label should be there if you refresh your browser
The devices are there and get updates?

**Comment by addy38** [comment]
- ok, new label is present
- Devices are there
- I get update Values 
![Bildschirmfoto vom 2022-03-21 21-17-21](https://user-images.githubusercontent.com/86205137/159357377-d798a702-0f24-4223-8a6f-84943a041e9e.png)
from analog values
- I get update from State output and can OFF/ON from HASS Dashboard

**Comment by addy38** [comment]
still 
Mar 21 21:05:50 ccu3 user.err hs485d: XmlRpc transport error
in the CCU log

**Comment by SukramJ** [comment]
I have no idea about this error.

**Comment by addy38** [comment]
the interface in general is ok, should we close this Issue?
Will you invest also in further and more detailed integration? or should I start a new Issue about this?

**Comment by SukramJ** [comment]
I think we can close this issue.
The problem with `XmlRpc transport error` is, that i don't have these errors in the logs, but a new issue is better then using this one.

**Comment by SukramJ** [comment]
@addy38 Thanks a lot for testing.
