### ISSUE TITLE
HM-Sec-Key "Entriegeln" / "Verriegeln" reversed

### ISSUE THREAD

**Issue by trilu2000** [SukramJ/hahomematic#349]
**custom_component/hahomematic version (if applicable):**
0.37.7

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, ...):
- OS (Original, RaspberryMatic, debmatic/...):
- Version: 3.61.7.20220226

HM-SEC-Key shows the correct status in Home Assistant but the actions "Lock" / "Unlock" are reversed.

Example: Device is unlocked, Lovelace status icon shows an open lock, the shortcut states "Verriegeln", everything correct.
If you click on "Verriegeln", the device confirms with two short beeps, so obvious it is receiving the command "Entriegeln".

If you send the "Entriegeln" command to the unit, the motor starts and locks the device.

Please let me know if you need a system log or more info.

**Comment by SukramJ** [comment]
Thanks for reporting.

@danielperna84 you have this device too. Please confirm.

**Comment by danielperna84** [comment]
I can confirm. Visually it's looking correct, but the actions are inverted.

**Comment by SukramJ** [comment]
Please retest with 0.38.1

**Comment by trilu2000** [comment]
Work now as expected, many thanks!

**Comment by SukramJ** [comment]
Thanks for feedback
