### ISSUE TITLE
es werden keine Geräte gefunden

### ISSUE THREAD

**Issue by elchi007** [SukramJ/hahomematic#350]
DONT'T DELETE THIS.
Please answer all questions as good as possible.

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
0.38

**Home Assistant version (if applicable):**
2022.3.5

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, ...): Raspi3/
- OS (Original, RaspberryMatic, debmatic/...): PIVCCU3
- Version: lates

**Problem-relevant configuration:**

Do you use tls? no
Do you use callback? no
Do you use username and password? tried wih out without
Which interfaces do you use? Classic wireless , IP wireles

**Describe the bug**
no devices will be discoverd by HA only 2 for Classic wireless and HM IP wireless ans 16 sensless deactivate enties.
I tried without any restriction and no password , with FHEM erverything is working.

**To Reproduce**

**Relevant HA log entries**
```
non

```

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by SukramJ** [comment]
Authentication must be enabled in CCU -> Password is required for CCU.
Please update to 0.38.1.
What happens after a restart?
Click in HA on "vollständiges Log ..." to get log entries.

**Comment by elchi007** [comment]
I did the update and a fresh install of raspimatic with only one hm-ip plug in the config. I did a new integration of the new system and got this:

`
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.config_entries
Source: custom_components/hahm/control_unit.py:104
Integration: Homematic(IP) Local (documentation, issues)
First occurred: 16:41:12 (1 occurrences)
Last logged: 16:41:12

Error setting up entry RaspberryMatic for hahm
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hahm/__init__.py", line 27, in async_setup_entry
    await control.async_start()
  File "/config/custom_components/hahm/control_unit.py", line 104, in async_start
    await self._central.start()
  File "/usr/local/lib/python3.9/site-packages/hahomematic/central_unit.py", line 213, in start
    await self._start_clients()
  File "/usr/local/lib/python3.9/site-packages/hahomematic/central_unit.py", line 221, in _start_clients
    await self._init_hub()
  File "/usr/local/lib/python3.9/site-packages/hahomematic/central_unit.py", line 384, in _init_hub
    await self._hub.fetch_data()
  File "/usr/local/lib/python3.9/site-packages/hahomematic/hub.py", line 226, in fetch_data
    await self._update_entities()
  File "/usr/local/lib/python3.9/site-packages/hahomematic/hub.py", line 241, in _update_entities
    variables = await self._central.get_all_system_variables()
  File "/usr/local/lib/python3.9/site-packages/hahomematic/central_unit.py", line 674, in get_all_system_variables
    return await client.get_all_system_variables()
  File "/usr/local/lib/python3.9/site-packages/hahomematic/client.py", line 918, in get_all_system_variables
    key, value = parse_ccu_sys_var(var)
  File "/usr/local/lib/python3.9/site-packages/hahomematic/helpers.py", line 116, in parse_ccu_sys_var
    return data[ATTR_NAME], float(data[ATTR_VALUE])
ValueError: could not convert string to float: ''
`

**Comment by SukramJ** [comment]
This is related to system variables, but should not affect devices
Which devices do you have connected?

**Comment by SukramJ** [comment]
Please post screenshots of the device overview and add a diagnostics file (click on the integration, download diagnostics)

**Comment by elchi007** [comment]
right now it is only a "HMIP-PSM" ip meter plug, nothing else.

i did not find where to download the diagnostics (sorry)

![grafik](https://user-images.githubusercontent.com/101953724/159171326-69b5efe4-163f-4753-b500-3e7690d22bf5.png)

**Comment by SukramJ** [comment]
https://www.home-assistant.io/blog/2022/02/02/release-20222/#diagnostics-for-integrations-and-devices

**Comment by elchi007** [comment]
there is no diagnostics download button / linke available, sorry

**Comment by SukramJ** [comment]
Go on the integrations page 
Click on the service

**Comment by elchi007** [comment]
![grafik](https://user-images.githubusercontent.com/101953724/159173826-0a6d63f1-eed2-474b-9c2d-567620ec20cb.png)

it is not there because it never had started completely

**Comment by SukramJ** [comment]
Please try 0.38.2. That should log the defect SysVar

**Comment by elchi007** [comment]
I updated the upadate and loaded an old HM config with many devices and now it is working. thankyou very much for your help
