### ISSUE TITLE
HM-LC-DW-WM

### ISSUE THREAD

**Issue by trilu2000** [SukramJ/hahomematic#357]
Not sure if it is a bug or a feature request :-)
Dualwhite dimmer (HM-LC-DW-WM) is shown with 6 single dimmer channels in Lovelace but 
the device is organized differently:
Channel 1, 3 and 5 are brightness channels
Channel 2, 4 and 6 are color temp settings

Would be great if you could make the device working like a philips hue white bulb with channel 1 showing in Lovelace and channel 2 within the popup to set the color temperature.

Please give me a note if you need further information or a log file

**Comment by SukramJ** [comment]
Try 0.38.5 and delete the obsolete entities.

**Comment by trilu2000** [comment]
many thanks, it is working. One small issue, but not sure if worth to change code.
Default setting of colortemp of HM-LC-DW-WM is "niedrig ist warmweiss"
In Home Assistant integration a low value is coldwhite.
Fix could be to change in homematic or here - so on your choice :-)
Never the less, many thanks for your support and quick fixes overall!
The integration is working like a charm.

**Comment by SukramJ** [comment]
The unit in HA is [mired](https://de.wikipedia.org/wiki/Mired), so low values are cold and high values are warm.

**Comment by trilu2000** [comment]
Ok, i change the setting in homamatic :-)
Many thanks!
