### ISSUE TITLE
Devices are not detected

### ISSUE THREAD

**Issue by LinusHoppe** [SukramJ/hahomematic#360]
DONT'T DELETE THIS.
Please answer all questions as good as possible.

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
0.38.5

**Home Assistant version (if applicable):**
2022.3.7

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, ...): Raspi 4
- OS (Original, RaspberryMatic, debmatic/...): RaspberryMatic
- Version: 3.61.7.20220226

**Problem-relevant configuration:**

Do you use tls? no
Do you use callback? no
Do you use username and password? yes
Which interfaces do you use? HMIP-RF

**Describe the bug**
After configuring the custom_homematic integration, a connection is establised, but only the default device HmIP-RCV-50 HmIP-RCV-1 is added to home assistant. All other devices are not shown.

**To Reproduce**
1. Configure hahomematic integration
2. Integration is displayed correctly, but only with one device and 7 disabled entities

**Relevant HA log entries**
no log entries corresponding to hahomematic found.

**integration diagnostics**
```
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.3.7",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.9.9",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "5.10.92-v8",
    "supervisor": "2022.03.5",
    "host_os": "Home Assistant OS 7.5",
    "docker_version": "20.10.9",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "hahm": {
      "version": "0.38.5",
      "requirements": [
        "hahomematic==0.38.5"
      ]
    },
    "hacs": {
      "version": "1.19.3",
      "requirements": [
        "aiogithubapi>=21.11.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "hahm",
    "name": "Homematic(IP) Local",
    "config_flow": true,
    "documentation": "https://github.com/danielperna84/custom_homematic",
    "issue_tracker": "https://github.com/danielperna84/hahomematic/issues",
    "requirements": [
      "hahomematic==0.38.5"
    ],
    "ssdp": [
      {
        "manufacturer": "EQ3",
        "manufacturerURL": "http://www.homematic.com"
      }
    ],
    "zeroconf": [],
    "homekit": {},
    "dependencies": [],
    "codeowners": [
      "@danielperna84",
      "@SukramJ"
    ],
    "iot_class": "local_push",
    "loggers": [
      "hahomematic"
    ],
    "version": "0.38.5",
    "is_built_in": false
  },
  "data": {
    "config": {
      "entry_id": "548eb76093bf7ecbf0997ac0d61af7a8",
      "version": 1,
      "domain": "hahm",
      "title": "Homematic",
      "data": {
        "instance_name": "Homematic",
        "host": "de838cd8-raspberrymatic",
        "username": "**REDACTED**",
        "password": "**REDACTED**",
        "callback_host": "0.0.0.0",
        "callback_port": 0,
        "json_port": null,
        "tls": false,
        "verify_tls": false,
        "interface": {
          "HmIP-RF": {
            "port": 2010
          }
        }
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": "172.30.33.0",
      "disabled_by": null
    },
    "platform_stats": {},
    "devices": []
  }
}
```

**Expected behavior**
All devices (HMIP-BROLL and HMIP-BWTH) are found and added as devices + entities.

**I tried:**
everything without success:
- Restarting home assistant
- reload integration
- remove and re-add integration
- restart raspberrymatic
- just wait for two hours (thought it would just take some time)

**additional context:**
- with the "old" homematic integration, everything worked fine (except the bad integration ;-)). In between, I did not change any configuration within RaspberryMatic (user, firewall, security, ...).

**Comment by SukramJ** [comment]
Please add:
- HA logs (press full log)
- screenshot of RM Firewall
- RM Addon logs
- screenshot of integrations device view

**Comment by LinusHoppe** [comment]
> Please add:
> 
>     * HA logs (press full log)
```
2022-03-24 12:14:34 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hahm which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-03-24 12:14:34 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-03-24 12:14:40 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547941051840] Received invalid command: energy/get_prefs
2022-03-24 12:14:47 WARNING (MainThread) [homeassistant.config_entries] Config entry '192.168.2.105' for synology_dsm integration not ready yet: ConnectionError = <urllib3.connection.HTTPSConnection object at 0x7f91ce2be0>: Failed to establish a new connection: [Errno 113] Host is unreachable; Retrying in background
2022-03-24 12:14:47 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Canon MB2700 series' for ipp integration not ready yet: Invalid response from API: Error occurred while communicating with IPP server.; Retrying in background
2022-03-24 12:14:54 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Xiaomi' for xiaomi_miio integration not ready yet; Retrying in background
2022-03-24 12:15:17 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Default for unifi
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/unifi/__init__.py", line 40, in async_setup_entry
    if not await controller.async_setup():
  File "/usr/src/homeassistant/homeassistant/components/unifi/controller.py", line 311, in async_setup
    await self.api.initialize()
  File "/usr/local/lib/python3.9/site-packages/aiounifi/controller.py", line 152, in initialize
    await self.clients.update()
  File "/usr/local/lib/python3.9/site-packages/aiounifi/api.py", line 114, in update
    raw = await self._request("get", self._path)
  File "/usr/local/lib/python3.9/site-packages/aiounifi/controller.py", line 272, in request
    return await self._request(method, path, json, url)
  File "/usr/local/lib/python3.9/site-packages/aiounifi/controller.py", line 321, in _request
    raise ResponseError(f"Call {url} received 404 Not Found")
aiounifi.errors.ResponseError: Call https://192.168.0.1:443/proxy/network/api/s/default/stat/sta received 404 Not Found
```
>     * screenshot of RM Firewall
![RM firewall](https://user-images.githubusercontent.com/32911160/159907220-b78df7e9-1621-4d01-9751-45131b8c89b6.png)

>     * RM Addon logs
```
Mounting /data as /usr/local (Home Assistant Add-On): OK
Starting watchdog...
Identifying host system: oci, OK
Initializing RTC Clock: no hardware found
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Initializing System: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.0, OK
Identifying Homematic RF-Hardware: ....HmRF: HM-MOD-RPI-PCB/GPIO, HmIP: HM-MOD-RPI-PCB/GPIO, OK
Updating Homematic RF-Hardware: HM-MOD-RPI-PCB: 2.8.6, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: ...OK
Starting rfd: .OK
Starting HMIPServer: ............OK
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting NeoServer: disabled
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.61.7.20220226 (raspmatic_oci_arm64)

```
>     * screenshot of integrations device view

![integration devices](https://user-images.githubusercontent.com/32911160/159907946-4309dad4-975a-4f38-8434-7442f1068a17.png)

**Comment by SukramJ** [comment]
Looks good.

Please add this to `configuration.yml`  to get verbose logs in HA, and restart HA.

```
logger:
  default: info
  logs:
    hahomematic: info
    hahomematic.json_rpc_client: debug
    hahomematic.xml_rpc_proxy: debug
    hahomematic.xml_rpc_server: debug
    hahomematic.central_unit: debug
```
Afterwards add RM logs (Einstellungen -> Systemsteuerung -> Zentralenwartung -> Logdatei herunterladen)

**Comment by SukramJ** [comment]
```
logger:
  default: info
  logs:
    hahomematic: info
    hahomematic.json_rpc_client: debug
    hahomematic.xml_rpc_proxy: debug
    hahomematic.xml_rpc_server: debug
    hahomematic.central_unit: debug
```

**Comment by LinusHoppe** [comment]
[home-assistant.log](https://github.com/danielperna84/hahomematic/files/8342026/home-assistant.log)
Please see line 638 ff. - do I have a problem with existing devices which are skipped? As mentioned before, I have used the legacy integration before. I deleted all entities in the UI.

**Comment by SukramJ** [comment]
Skipped means, that they already exist from a previous start. Old and new integration can exist in parallel.
Looks good, i wonder why there are no devices/entities. Press F5 in device view?
You're  already receiving events (line 668ff).

Please use service hahm.delete_cache. Restart with debugging enabled afterwards.

> Afterwards add RM logs (Einstellungen -> Systemsteuerung -> Zentralenwartung -> Logdatei herunterladen)

Please add the RM logs.

**Comment by LinusHoppe** [comment]
> Please use service hahm.delete_cache. Restart with debugging enabled afterwards.

I think you mean hahm.clear_cache. I've done that - now I have 12 devices and 80 entities, looks much better. Will do a deep-dive and try all sensors / actions. I still don't understand why that was necessary, but is maybe related to my installation and not a bug in hahomematic at all.

**Comment by SukramJ** [comment]
Don't know if that really was a problem. I forgot to ask you to save the old cache files, but good to know that it works now.
You could retest this by calling the service again and then delete the integration, otherwise the cached files under `{HA config dir}/hahm/cache/` will not be deleted. 
Then you could try a clean install.
