### ISSUE TITLE
RaspberryMatic System Variables not available anymore (?)

### ISSUE THREAD

**Issue by marc965** [SukramJ/hahomematic#361]
DONT'T DELETE THIS.
Please answer all questions as good as possible.

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
0.38.4

**Home Assistant version (if applicable):**
core-2022.3.6, supervisor-2022.03.5, Home Assistant OS 7.5

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, ...):
- OS (Original, RaspberryMatic, debmatic/...):
- Version: RaspberryMatic CCU Current version: 3.61.7.20220226

**Problem-relevant configuration:**

Do you use tls? no
Do you use callback? no
Do you use username and password? yes
Which interfaces do you use? RF & HmIP

**Describe the bug**

Is there any reason why the RaspberryMatic System Variables are not available anymore?
I dont't change anything...
![image](https://user-images.githubusercontent.com/85791333/159990660-e3f201c4-02cb-413a-a065-f46debf02484.png)

**To Reproduce**

**Relevant HA log entries**
```


```

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by SukramJ** [comment]
No

**Comment by marc965** [comment]
Is there any reason for this?
Why the System Variables:

binary_sensor.pimatic_sv_alarmzone_1
binary_sensor.pimatic_sv_watchdog_hb_rf_eth_connection
binary_sensor.pimatic_sv_watchdog_no_internet
binary_sensor.pimatic_sv_watchdog_regahss_restart

are still available?

**Comment by SukramJ** [comment]
So that I don't have to rely on a crystal ball, you should provide more information:
- What's in the logs (full logs)? (part of the template)
- did you restart HA?
- what happens if you create a new SV in RM and restart HA?
- Which SVs are NOT working?

**Comment by SukramJ** [comment]
Anything to add here?

**Comment by marc965** [comment]
Sorry, dass ich mich so spät melde. Hatte die letzten Tage sehr wenig Zeit hier etwas zu tun.
Leider besteht der Fehler immer noch. Regelmässig sind die SV* Variablen weg.
Melde mich bei Gelegenheit wieder, es steht ja die Installation der 1.0.0 an. Das tut mir ziemlich weh alles neu installieren zu müssen, zumal ich bereits Wetterstatistiken aufgebaut hatte.

**Comment by Lemocin** [comment]
> Melde mich bei Gelegenheit wieder, es steht ja die Installation der 1.0.0 an. Das tut mir ziemlich weh alles neu installieren zu müssen, zumal ich bereits Wetterstatistiken aufgebaut hatte.

Hi Marc,
kurze Info dazu: Du kannst [Methode 2](https://github.com/danielperna84/custom_homematic/wiki/Migration--from-domain-hahm-to-homematicip_local#option-2-advanced-will-migrate-the-component-without-reinstalling) nutzen. Dann musst du nichts neu aufsetzen. Nur die Systemvariablen müssen alle aktiviert sein und diese werden neu erstellt. Möglicherweise hilft das dann auch bei deinem Problem. Ein paar [mehr Infos ](https://github.com/danielperna84/hahomematic/issues/361#issuecomment-1078712580)zum debuggen würden sonst schon benötigt werden... 

Die alten sind dann als nicht verfügbar drin und können entfernt werden. Bei den neuen, deaktivierten SVs dann einfach das _2 bei der Entity ID entfernen und dann ist alles, als wäre nie etwas gewesen.

**Comment by SukramJ** [comment]
> Leider besteht der Fehler immer noch. Regelmässig sind die SV* Variablen weg.

Damit kann ich leider nichts anfangen. Entweder Du lieferst die angeforderten Information oder ich kann dir leider nicht weiterhelfen helfen. 
Ich habe keine Probleme mit ausbleibenden Werten und bisher sind auch keine weiteren Meldungen aufgelaufen.
Mach erst mal das Update auf 1.0.0. 
Wenn das Problem mit 1.0.0 wieder auftaucht öffne das Ticket wieder, aber liefere dann auch alle Informationen, die dir zur Verfügung stehen, u.a. alle mögliche Logs und was Du bisher zur Fehlersuche gemacht hast (Neustart der einzelnen Komponenten, ...). Viel Erfolg beim Update.

**Comment by marc965** [comment]
Danke!
Ich hab mir Methode 2 mal angeschaut.
mir macht das editieren der device registry und der anderen files echt Angst, zumal dann nicht nur die homematic futsch ist, wenn das schief geht.

das mit dem Fehler bei den SV Variablen habe ich nicht weiter analysiert, weil mir einfach die Zeit und die Möglichkeiten fehlen.
ich habe teilweise noch nicht ganz verstanden wie hass in der tiefe genau funktioniert. ich werde auch oft dumm angemacht wenn manche fragen von mir „blöd“ formuliert sind.
Aber die SV Variablen sind mal da und mal sind sie nicht da. Manchmal sind die nur teilweise weg. und wenn sie mal weg sind bleiben sie auch weg, bis zum nächsten Neustart. Es sind auch immer wieder andere die fehlen, manchmal sind auch alle wieder da. das passiert immer beim Start.
Jetzt gerade eben die neue core installiert und nach dem Neustart sind wieder alle weg.

**Comment by Lemocin** [comment]
> Danke! Ich hab mir Methode 2 mal angeschaut. mir macht das editieren der device registry und der anderen files echt Angst, zumal dann nicht nur die homematic futsch ist, wenn das schief geht.

Vorher ein Backup machen und herunterladen ist ja selbstverständlich. Wenn du allerdings stur nach Anleitung vorgehst, sollte das hinhauen. Falls du das Terminal Addon verwendest, ab dem vierten Bullet point einfach `cd /config` und dann die befehle eingeben. Wenns nicht klappt, dann wird eben das Backup wieder eingespielt. 

> Jetzt gerade eben die neue core installiert und nach dem Neustart sind wieder alle weg.

Dann poste doch bitte mal die Full Home Assistant logs jetzt wo die SVs wieder weg sind. 

Nochmal zu den angefragten Infos, hast du ja zum Teil auch schon beantwortet:

> What's in the logs (full logs)? (part of the template)

Wäre damit ja dann beantwortet wenn du die postest.

> did you restart HA?

Das ja dementsprechend auch. Und du meinst, dass die SVs verschwunden bleiben, wenn sie einmal verschwunden sind? Erscheinen Sie dann, wenn du HA danach nochmal neustartest, 

>what happens if you create a new SV in RM and restart HA?

Müsstest du dann noch testen

> Which SVs are NOT working?

Da meintest du es sind immer wieder unterschiedliche die nicht laufen. Richtig?

> ich werde auch oft dumm angemacht wenn manche fragen von mir „blöd“ formuliert sind.

Dich will hier niemand dumm anmachen, allerdings ist das "Problem" nunmal, dass das Problem bei uns nicht zu existieren scheint. Deshalb kann ja nichts untersucht werden, wenn man nicht weiß, was bei dir vor sich geht. Deshalb hat @SukramJ auch die Infos angefragt. 

Versuche allerdings erstmal auf die neue Version zu updaten, vielleicht ist es ja dann schon gut.

**Comment by marc965** [comment]
Hallo! Ist zwar closed der Beitrag, aber vielleicht schaut ja jemand rein!
Habe jetzt die neue Homematic 1.0.1 drauf. Habe nach der Methode 1 (als Neuinstallation) gearbeitet.
Hatte, soweit ich im Moment sehe, keine Schwierigkeiten.
Der Installationsprozess ist einfach, es sollte nur erwähnt sein, dass nach einer Neuinstallation die RaspberryMatic automatisch erkannt wird, sofern Sie als Integration unter Home Assistant läuft, Das ist sehr vorbildlich.

Da ich die Entitäten nie umbenannt habe und nur die "friendly_names" für mich, wegen der besseren Wartbarkeit geändert hatte, sind alle Automationen unter Node-Red augenblicklich wieder gelaufen. Hatte nur die deaktivierten Entitäten wieder zu aktivieren. Arbeitszeit insgesamt 30 Minuten.

 Die SV* Variablen stehen zur Verfügung. Jetzt bleibt abzuwarten wie stabil das nach einem Neustart aussieht.

**Comment by Lemocin** [comment]
> es sollte nur erwähnt sein, dass nach einer Neuinstallation die RaspberryMatic automatisch erkannt wird, sofern Sie als Integration unter Home Assistant läuft,

Das ist schon relativ lange so. Das funktioniert außerdem mit jeder CCU, nicht nur mit der RM Integration! Ist eine gute Sache.

> alle Automationen unter Node-Red augenblicklich wieder gelaufen

Ja, mit Node-Red sollte es da keine Probleme geben. NR läuft glaube ich noch mit den Entity-IDs, wobei die HA Automationen eher auf Device-IDs setzen. Da kann es dann mit Methode 1 Probleme geben

> Ist zwar closed der Beitrag, aber vielleicht schaut ja jemand rein!
Die SV* Variablen stehen zur Verfügung. Jetzt bleibt abzuwarten wie stabil das nach einem Neustart aussieht.

Sehr schon, hoffen wir dass das jetzt funktioniert. Falls der Fehler noch einmal auftritt, kann der Issue hier auch einfach wieder geöffnet werden. Die Logs etc. bräuchte man dann aber :)

**Comment by marc965** [comment]
Hi!
Leider tritt der Fehler immer noch sehr regelmässig auf.
Ein Neustart behebt das Problem meistens. Vielleicht gibt es Interesse, den Fehler zu finden.
Leider steht nichts im Log.

Kann mir jemand sagen wie ich speziell für die Homematic das Log auf debug stellen kann?
Ich müsste dan warten, bis es wieder passiert und würde dann die Logs reinstellen, wenn Interesse besteht.

Wenn es recht ist, würde ich den case gerne wieder öffnen. Wie geht das? kann ich das selbst?
