### ISSUE TITLE
Missing interfaces

### ISSUE THREAD

**Issue by Darkman1900** [SukramJ/hahomematic#362]
Hi,
thank you for your great work.
I changed my total implementation from Redmatic to HomeAssisant.
Now I still miss some of my used features:

Application: I stop heating 2x longer than the window is open 
Devices: HmIP-WTH-2,HmIP-BWTH
Channel 1 - HEATING_CLIMATECONTROL_TRANSCEIVER
Parameter WINDOW_STATE
A entity to directly control that state would be nice and solve my issue.

Application: Instusion alarm, alarm testing, ... with HmIP-SWSD
Device: HmIP-SWSD
Channel 1 - SMOKE_DETECTOR
Parameter SMOKE_DETECTOR_COMMAND
Parameter SMOKE_DETECTOR_EVENT
Parameter SMOKE_DETECTOR_TEST_RESULT
Entities for read/write access would be nice

I tried to activate the entiy Operating voltage but that was not working - access would be nice for more automated control for the devices

Thank you
Best regards

**Comment by SukramJ** [comment]
> Application: I stop heating 2x longer than the window is open Devices: HmIP-WTH-2,HmIP-BWTH Channel 1 - HEATING_CLIMATECONTROL_TRANSCEIVER Parameter WINDOW_STATE A entity to directly control that state would be nice and solve my issue.

As this is not a commone scenario, use [unignore](https://github.com/danielperna84/hahomematic/blob/devel/docs/unignore.md) for WINDOWS_STATE.
 
> Application: Instusion alarm, alarm testing, ... with HmIP-SWSD Device: HmIP-SWSD Channel 1 - SMOKE_DETECTOR Parameter SMOKE_DETECTOR_COMMAND Parameter SMOKE_DETECTOR_EVENT Parameter SMOKE_DETECTOR_TEST_RESULT Entities for read/write access would be nice

SMOKE_DETECTOR_COMMAND, SMOKE_DETECTOR_EVENT are write only parameters. Use service hahm.set_value to write to it. 

Use [unignore](https://github.com/danielperna84/hahomematic/blob/devel/docs/unignore.md) for SMOKE_DETECTOR_TEST_RESULT.


> I tried to activate the entiy Operating voltage but that was not working - access would be nice for more automated control for the devices

OPERATING_VOLTAGE is in the paramset_description, but there are no values send/available from devices. You could use Homematic Maanger to verify this

**Comment by SukramJ** [comment]
Can this be closed?

**Comment by SukramJ** [comment]
No update so far. I close this issue for now. Reopen it, if there is something new.
