### ISSUE TITLE
Show valve state of a Homematic heating thermostat in Home Assistant

### ISSUE THREAD

**Issue by DGrebe** [SukramJ/hahomematic#363]
Currently, the valve state of a Homematic heating thermostat is not available in Home Assistant. 
This value is available in Homematic UI as well as Raspberrymatic and also in the OpenHab Homematic integration

It would be also nice to show this value in the thermostat panel in order to have all main information available.

What has to be done to make the valve state available?

I think this feature belongs to this repository not into the custom homematic repo.

Regards

Dirk

**Comment by SukramJ** [comment]
What is  **`a Homematic heating thermostat`** ?
A concrete device type is required.

**Comment by DGrebe** [comment]
Hi,

the concrete device is a HmIP-eTRV-2 from eQ-3 [https://de.elv.com/homematic-ip-heizkoerperthermostat-hmip-etrv-2-fuer-smart-home-hausautomation-140280?fs=1284589651&c=692](url)

After checking the device in home assistant, I found that the entitiy level has been disabled. Therefore everything is fine, I just enabled the field.

Kind regards

Dirk
