### ISSUE TITLE
HMW-LC-Bl1-DR position Level missing

### ISSUE THREAD

**Issue by addy38** [SukramJ/hahomematic#365]
I missing the actual Level from my connected Rollo 

**Describe the solution you'd like**
I require a % value and/or an active Symbol which show the actual "Rollo" Level. Maybe Like in the HM GUI 
Enclosure the active Symbol in the HM GUI which show actual an 60% (60% from max. 100% open) Position  
![Bildschirmfoto vom 2022-03-27 18-13-53](https://user-images.githubusercontent.com/86205137/160290619-2556a0ce-258d-47d1-ab8f-6ec3ea2697bc.png)

**Comment by SukramJ** [comment]
The HMW-LC-Bl1-DR has `current_position` and `current_tilt_position` attributes that could be read out by a [template](https://www.home-assistant.io/integrations/homematic/#reading-attributes-of-entities) sensor.

**Comment by addy38** [comment]
ok, I can see attributes but I have no experience to follow your advice to add. this to my dashboard :(
Why these attributes are not in general integrated?

**Comment by SukramJ** [comment]
Because they are already part of the cover entity.

**Comment by SukramJ** [comment]
[Templates](https://www.home-assistant.io/docs/automation/templating/) are not that complicated and very useful. Just read the HA docs.
The already referenced link is a good example, where you only need to replace the values and add to `configuration.yaml`.

**Comment by addy38** [comment]
I add in /config/configuration.yaml the below code, I get the Label "Rollo Wert ." in my Dashboard but no value. Also not after HASS reboot.
template:
  - sensor:
    - name: "Rollo Wert 1"
      state: "{{ state_attr('custom.JEQ0272688:3', 'current_position') }}"
  - sensor:
    - name: "Rollo Wert 2"
      state: "{{ state_attr('custom.JEQ0272688:3', 'current_tilt_position') }}"

**Comment by SukramJ** [comment]
You read the docs? 

`custom.JEQ0272688:3` should be **entity_id** of your cover : `cover.XYZ`

**Comment by addy38** [comment]
I wrote few days the docs.
Now I could find https://www.home-assistant.io/docs/configuration/state_object about this.

With the code
template:
  - sensor:
    - name: "Rollo Wert 1"
      state: "{{ state_attr('cover.kueche_rollo', 'current_position') }}"

I get now also the position value direct in my Dashboard, thanks
