### ISSUE TITLE
hmip-dld Action 'lock: open' missing in Lock Lovelace Card

### ISSUE THREAD

**Issue by Ja-sha256** [SukramJ/hahomematic#366]
I'm missing in the Lovelace Card for the lock the action to open the lock.

In 'developer tools-Services' I can call the service 'lock: open lock.open' for the entity hmip-dld, but it is missing in it's Entity Card. 

![grafik](https://user-images.githubusercontent.com/5091324/160292590-806c23b1-0146-409b-ab24-88563c6bdf83.png)

I'm no developer but looking through the documentation i saw this flag: 'SUPPORT_OPEN' maybe it is missing?
https://developers.home-assistant.io/docs/core/entity/lock/#supported-features

It would be really awesome if it would be also possible to use the action.

![grafik](https://user-images.githubusercontent.com/5091324/160292701-205ce3ff-210f-49ff-b3e8-7348ed0628a7.png)

The hmip-dld is integrated through Debmatic running on DietPi Bullseye on the Raspberry Pi 2b. HASS OS is running in a VM on a seperate Windows 10 machine.

**Comment by SukramJ** [comment]
SUPPORT_OPEN is set

https://github.com/danielperna84/custom_homematic/blob/10a4b1f7d6c2ceb8b2d930e753a84b265d8af6e9/custom_components/hahm/lock.py#L55-L58

I don't know why it is not displayed.

**Comment by SukramJ** [comment]
An integration does not deal with Lovelace cards. We just create entities with attributes.
Please post a screenshot of the `Developer Tools/States` of your lock.

**Comment by Ja-sha256** [comment]
Thank you for your help! Here is the Picture: of the Developer Tools/States of this entity
![grafik](https://user-images.githubusercontent.com/5091324/160295198-b6511f71-a7ba-4f70-bbc2-24be6fda368e.png)

I will try making a custom lovelace card in that case.

**Comment by Ja-sha256** [comment]
Ok thanks for your time and help. I think I found what I was looking for. Sorry I'm just a noob with Home Assistant. Here is the Code for the Button I was looking for:
![grafik](https://user-images.githubusercontent.com/5091324/160295684-26033864-ce1a-4d58-8f6e-a54fff85f799.png)

show_name: true
show_icon: true
type: button
entity: lock.haustur
show_state: true
tap_action:
  action: call-service
  service: lock.open
  service_data: {}
  target:
    entity_id: lock.haustur
hold_action:
  action: toggle
