### ISSUE TITLE
Reboot create Syslog Error "cannot clear session with id ...."

### ISSUE THREAD

**Issue by addy38** [SukramJ/hahomematic#367]
**custom_component/hahomematic version (if applicable):**
0.38.5

**Home Assistant version (if applicable):**
2022.3.7

**CCU version:**
CCU3
- OS (Original, RaspberryMatic, debmatic/...):
- Version: RM3.59.6.20211009

**Problem-relevant configuration:**

Do you use tls? no
Do you use callback? no
Do you use username and password? yes
Which interfaces do you use? all

**Describe the bug**
Each Reboot from HASS generate an Error in the CCU Syslog, like:
ccu3 local0.warn ReGaHss: WARNING: cannot clear session with id 'uBLN8s59pn' [ExecSystem():iseESPexec.cpp:3761]

**Comment by SukramJ** [comment]
This is already discussed [here](https://github.com/danielperna84/hahomematic/issues/340).
This integration does a logout from the session on shutdown.

**Comment by addy38** [comment]
ok,sorry, Issue can be closed

**Comment by SukramJ** [comment]
Better twice than none. Thanks for reporting
