### ISSUE TITLE
Autodiscover: Just Raspberrymatic and Virtual Buttons, everything else just the entity of the Devices

### ISSUE THREAD

**Issue by meistermolli** [SukramJ/hahomematic#373]
DONT'T DELETE THIS.
Please answer all questions as good as possible.

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
0.38.5

**Home Assistant version (if applicable):**
Core 2022.3.7
Superviser 2022.3.5

**CCU version:**
- Model Raspberry Pi 3B+
- OS raspberrymatic
- Version: 3.61.7.20220226

**Problem-relevant configuration:**

Do you use tls? no
Do you use callback? no
Do you use username and password? yes
Which interfaces do you use? HAP Homematic

**Describe the bug**

**To Reproduce**
Autodiscover show just 3 Devices (Raspberrymatic, Virtual Homematic, Virtual Homematic IP)
but all my real devices are not shown.
Visible are the entities of my raspberrymatic system variables.

Not included are all my HmIP devices, but the  entities of my devices are shown service as disabled inside HomeAssistant.

**Expected behavior**
show all my devices in Autodiscover

**Additional context**
Do i have to manual write something into the configuration.yaml?

Thanks a lot

**Comment by SukramJ** [comment]
Please 
- post logs (full log) of HA.
- add system diagnostics
- add screenshots of integratios an device view, RM Firewall

**Comment by SukramJ** [comment]
Additionally:
There is a folder `hahm/cache` in your HA config folder that should contain 2 files (technical description of your devices/ no content). Please zip these files and add them to the issue.

**Comment by meistermolli** [comment]
[config_entry-hahm-7b57b398c6db081d50a94bd95549144e.json.txt]


Hope its all you need. If not I can do you the things you need.
Thank you

**Comment by SukramJ** [comment]
Please execute service hahm.clear_cache (Developer tools/Services), and restart afterwards

**Comment by meistermolli** [comment]
It worked.
it was not clear to me that this service could be found under the developer tools and that it could help me with the problem.
thank you for your quick help

![Bildschirmfoto 2022-03-29 um 15 54 57](https://user-images.githubusercontent.com/55836556/160629484-4d9f7e4a-b58a-4a6c-8424-164e5d206fa4.png)
![Bildschirmfoto 2022-03-29 um 16 00 11](https://user-images.githubusercontent.com/55836556/160629600-7f755726-5e50-4c37-b497-90d730e2b8c4.png)

**Comment by SukramJ** [comment]
Did you restart the RM Addon before you installed the integration initially?

**Comment by meistermolli** [comment]
I dont use the addon, because an other issue with homeassistant. Its installed but stopped. This is the ip of my other raspberrymatic. This was backuped and rebootet.

There is a bug with cgroup that i dont Unterstand
Home Assistant: Current Version: 2022.3.7
raspberrymatic: Version: 3.61.7.20220226 (oci)
HMIP-RFUSB (4.4.16)

**Comment by SukramJ** [comment]
Thanks for feedback.

**Comment by meistermolli** [comment]
With new version of 
Home Assistant core-2022.3.8
raspberrymatic add-on 3.63.8.20220330
the auto discovery worked for the Add on!

until now im using the add-on and it works.

Thanks
