### ISSUE TITLE
HmIP-SWSD SMOKE_DETECTOR_ALARM_STATUS

### ISSUE THREAD

**Issue by Darkman1900** [SukramJ/hahomematic#386]
**custom_component/hahomematic version (if applicable):**
1.0.3

**Home Assistant version (if applicable):**
2022.03.5

**CCU version:**
- Model (Raspi4):
- OS (RaspberryMatic running as add-on directly on HA):
- Version: 3.63.8.20220330

**Problem-relevant configuration:**

Do you use tls? no
Do you use callback?  do not know
Do you use username and password? yes
Which interfaces do you use? independent

**Describe the bug**

**To Reproduce**
1. Activate intrusion alarm independent from source e.g HA automation, Node Red Service, directly in Raspberrymatic 
2. sensor.hmip_swsd_xxx_smoke_detector_alarm_status shows every time IDLE_OFF state, not possible to trigger INTRUSION_ALARM, test with PRIMARY_ALARM not done

**Expected behavior**
Instrusion alarm enabled should generate Instrusion alarm state at sensor.hmip
Same for primary alarm - do not know if that is working

**Comment by SukramJ** [comment]
This integration does not generate state changes of devices. It displays what is in the parameter.
Please use an external tool (not CCU WebUI) like homematic manager to verify the content of SMOKE_DETECTOR_ALARM_STATUS.

**Comment by Darkman1900** [comment]
Thanks for your feedback. I do not expect to generate a state change. 
From my understanding the entiy "sensor.hmip_swsd_xxx_smoke_detector_alarm_status" should show the status of the smoke sensor, but this is not the case. It shows every time only the state IDLE_OFF and not like expected the state INTRUSION_ALARM.

**Comment by SukramJ** [comment]
Please match your expectation with reality:
> Please use an external tool (not CCU WebUI) like homematic manager to verify the content of SMOKE_DETECTOR_ALARM_STATUS.

Please add a screenshot of the result

**Comment by SukramJ** [comment]
Link to [homematic manager](https://github.com/hobbyquaker/homematic-manager/releases)

**Comment by Darkman1900** [comment]
Hi, in my current configuration it is not possible to use homematic manager because as I mentioned I use Raspberrymatic as a addon in home assistent and for that I mapped e.g. port 2001 to 2201. Homematic manager expects access to port 2001. So when I start homematic manager I only see crash messages.
I used the same function with Redmatic an it worked like expected.

**Comment by SukramJ** [comment]
Why do you map ports if you use HA and RM on the same machine?

**Comment by Darkman1900** [comment]
That was the only way to get it working for me. Is there a better way to do it?
Homematic(IP) Local config
![image](https://user-images.githubusercontent.com/76952569/161618401-33b53cfd-7e2a-4f51-944e-177fb5100503.png)
Raspberrymatic config
![image](https://user-images.githubusercontent.com/76952569/161618580-12783d28-cdef-434f-ad91-6935c62e6c9b.png)

**Comment by SukramJ** [comment]
A good description is [here](https://github.com/jens-maus/RaspberryMatic/wiki/HomeAssistant-Integration).

In your case
hostname: de??????-raspberrymatic (goto Addon page: use the hostname) This is the name in the internal docker network so no port mapping is required.

No Callback IP (Any special reason to configure a callback ip?)
No Callback Port (Any special reason to configure a callback port?)

No you receive update for other entities?
Are there any relevant log messages?

**Comment by Darkman1900** [comment]
Thanks for the link, last time I checked the documentation I found no description for that use case.

**Comment by Darkman1900** [comment]
I changed the integration according to guideline. It's working again like before. Callback was deleteted from me but after saving value is set again. 
I tried the entiy "sensor.hmip_swsd_xxx_smoke_detector_alarm_status" again but it is still not working. All other enties are working like expected.
How can I access with homematic manager? 
Port forwarding in Raspberrymatic addon is deactivated now - when I try to forward port 2010 then I get the message port is already used

**Comment by SukramJ** [comment]
I found a bug with resetting the callback XXX.
Option 1 Reinstall the integration
Option 2 Change the callback port to e.g. 52010 

then port  2010 should by forwardable.

**Comment by SukramJ** [comment]
Try reconfigure with version 1.0.4.
Existing values will no longer be defaults in reconfigurations (callback_xxx)

**Comment by Darkman1900** [comment]
Thank you for the quick fix. I will test it

**Comment by Darkman1900** [comment]
After several setting, resetting the config and reboots of the system I can forward the port 2010 for external access
Homematic manager is getting the first data

**Comment by Darkman1900** [comment]
Hi, I checked the function I requested with homeatic manager and WebUI. 
WebUI reaction is fast, homematic manager needs more time to show the result
![image](https://user-images.githubusercontent.com/76952569/161968694-82288b32-bfc1-42c8-9b10-31462c079158.png)

Some seconds later I can now see the result also in home assistant
![image](https://user-images.githubusercontent.com/76952569/161968823-6d953fdd-059a-43dd-a8d3-06f1b7b3c1e5.png)

You can close the bug 
Thank you very much for the fixes you did and your patience.
Regards
