### ISSUE TITLE
Error setting up Homegear for hahm

### ISSUE THREAD

**Issue by andyboeh** [SukramJ/hahomematic#387]
DONT'T DELETE THIS.
Please answer all questions as good as possible.

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
1.0.3

**Home Assistant version (if applicable):**
2022.3.8

**CCU version:**
- Model: Raspberry Pi 4
- OS: Raspbian Bulls Eye
- Homegear via Docker
- Version: 

**Problem-relevant configuration:**

Do you use tls? no
Do you use callback? yes
Do you use username and password? no
Which interfaces do you use? only Homematic RF

**Describe the bug**

Home Assistant does not succeed in setting up the integration.

**To Reproduce**
1. Install and configure the integration

**Screenshots (if applicable)**

**Relevant HA log entries (full log)**
```
Error setting up entry Homegear for hahm

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hahm/__init__.py", line 27, in async_setup_entry
    await control.async_start()
  File "/config/custom_components/hahm/control_unit.py", line 104, in async_start
    await self._central.start()
  File "/usr/local/lib/python3.9/site-packages/hahomematic/central_unit.py", line 213, in start
    await self._start_clients()
  File "/usr/local/lib/python3.9/site-packages/hahomematic/central_unit.py", line 221, in _start_clients
    await self._init_hub()
  File "/usr/local/lib/python3.9/site-packages/hahomematic/central_unit.py", line 384, in _init_hub
    await self._hub.fetch_data()
  File "/usr/local/lib/python3.9/site-packages/hahomematic/hub.py", line 227, in fetch_data
    await self._update_hub_state()
  File "/usr/local/lib/python3.9/site-packages/hahomematic/hub.py", line 232, in _update_hub_state
    value = 0 if service_messages is None else int(service_messages)
ValueError: invalid literal for int() with base 10: ''
```

**Diagnostic Information (available on every device)**
```


```

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by SukramJ** [comment]
Welcome. You are the first one with Homegear after 6 Month testing!
What is the content of Sysvar Servicemeldungen? Does it exist?

**Comment by SukramJ** [comment]
I wonder about this log line: `Error setting up entry Homegear for hahm`
The integration has been renamed with 1.0.0 to homematicip_local.
Did follow the [migration plan](https://github.com/danielperna84/custom_homematic/wiki/Migration--from-domain-hahm-to-homematicip_local)?

**Comment by andyboeh** [comment]
Yeah, I know, Homegear isn't very common. I discovered it because I had a mixed setup of MAX! and Homematic devices - and MAX! can be used perfectly fine with Homegear. Now that I've replaced all MAX! devices, I would still like to use Homegear.

No, sorry, I didn't notice this change. It doesn't make a difference, though.

I have no idea where I can find Sysvars in Homegear. I know that service messages are available and that Homegear plays well with homematic-manager and all service messages are reported correctly there. This is a completely fresh Homegear installation, I don't know if that makes a difference.

**Comment by andyboeh** [comment]
OK, I found out how to get all system variables in Homegear: 
```
$ docker exec -it homegear homegear -e rc 'print_r($hg->getAllSystemVariables());'
Array
(
    [homegearStartTime] => 1649097950
    [socketPath] => /var/run/homegear/
)
```
So no, Servicemeldungen is not defined.

**Comment by danielperna84** [comment]
You can get the service messages with the following Python code:

```python
from xmlrpc.client import ServerProxy
p = ServerProxy("http://1.2.3.4:2001") # Use the IP of Homegear here
p.getServiceMessages()
```

That being said, I have noticed something odd here with Debmatic. When using port `2010` for HmIP I get `[['0001D3C...:3', 'UNREACH', True]]`, but on port `2001` I get the empty string `''` instead of an empty list. That matches the error message you are seeing. I also don't see the Message for the HmIP device in the Debmatic UI, which is even more confusing. I even don't see that device ID in my devconfig list. So I wonder where that is coming from. 🤔

**Comment by andyboeh** [comment]
Now it's getting interesting: On Port 2001 I receive an empty list. Since port 2010 is not open, I just get "Connection Refused" (I only enabled port 2001 in the device configuration and I can confirm that this setting is stored correctly):

```
>>> from xmlrpc.client import ServerProxy
>>> p = ServerProxy('http://192.168.177.70:2001')
>>> p.getServiceMessages()
[]
```

However: Since it's returning an empty list, it shouldn't crash, right!?

**Comment by SukramJ** [comment]
This one is more relevant:
```
from xmlrpc.client import ServerProxy
p = ServerProxy('http://192.168.177.70:2001')
p.getSystemVariable("Servicemeldungen")
```
I guess it returns `""`

**Comment by SukramJ** [comment]
Please retest with 1.0.4

**Comment by andyboeh** [comment]
Looks good, the integration starts now - thanks for the quick support!
