### ISSUE TITLE
Duplicate devices after update to 1.x

### ISSUE THREAD

**Issue by eikowagenknecht** [SukramJ/hahomematic#390]
**custom_component/hahomematic version (if applicable):**
1.0.4

**Home Assistant version (if applicable):**
2022.4.0b5

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, ...): Raspberry Pi 4
- OS (Original, RaspberryMatic, debmatic/...): RaspberryMatic
- Version: latest

**Problem-relevant configuration:**

Do you use tls? No
Do you use callback? No
Do you use username and password? Yes
Which interfaces do you use? HM, HmIP

**Describe the bug**
I followed the migration manual (upgrade) and now I have duplicate devices:

![image](https://user-images.githubusercontent.com/1475672/161745477-4d8124e4-f8b3-44f5-afe9-eceaa4fc4128.png)

The devices are named "... (Gerät)" on the CCU3 and were renamed by me to "..." before the upgrade.

These renamed variants seem to have another "Verbunden über" entry as well:

"Old" device:
[wettersensor.txt](https://github.com/danielperna84/hahomematic/files/8417769/wettersensor.txt)

![image](https://user-images.githubusercontent.com/1475672/161745656-146624e8-fe9d-40c4-9a83-890b5b94a608.png)

This is the "KG.Flur Homematic CCU3" entry:

[kg_flur_ccu3.txt](https://github.com/danielperna84/hahomematic/files/8417768/kg_flur_ccu3.txt)

![image](https://user-images.githubusercontent.com/1475672/161745808-9f2ed0f9-8439-4276-a658-a49398158858.png)

"New" device:
[wettersensor_geraet.txt](https://github.com/danielperna84/hahomematic/files/8417770/wettersensor_geraet.txt)

![image](https://user-images.githubusercontent.com/1475672/161745697-b463daff-f2f0-4d0c-a2e6-9151639e4dcb.png)

This is the CCU3 entry:

[ccu3.txt](https://github.com/danielperna84/hahomematic/files/8417767/ccu3.txt)
![image](https://user-images.githubusercontent.com/1475672/161745740-b3cbd00c-6995-4e00-97c6-14b27adeec28.png)

The automations seem to still link to the renamed (=old) devices.

What do I do to consolidate those duplicates in a way that my automations still work?

Restoring my backup for now.

**To Reproduce**
1. Rename device before migration
2. Migrate
3. Look at the duplicates in device view ;-)

**Screenshots (if applicable)**
See above

**Relevant HA log entries (full log)**
```
```

**Diagnostic Information (available on every device)**
```
```

**Expected behavior**
Devices are migrated as well or there is a warning on the migration page that the devices need to have their original names before migration.

**Screenshots**
See above. By the way, this is a duplicate entry in your issues form ;-)

**Additional context**
n/a

**Comment by SukramJ** [comment]
Please post some device entry from `.storage/core.device_registry`

**Comment by SukramJ** [comment]
Option 1:
Something could be wrong with your `.storage/core.device_registry`

Each device should have an identifier section like this:
```
                "identifiers": [
                    [
                        "homematicip_local",
                        "000B5BE999XXXX@CCU3-HmIP-RF"
                    ]
                ],
```
or 

```
                "identifiers": [
                    [
                        "homematicip_local",
                        "000B5BE999XXX@CCU3-BidCos-RF"
                    ]
                ],
```

Before v1 it should be `hahm` instead of `homematicip_local`

**Comment by SukramJ** [comment]
Option 2:
You missed to execute step `sed -i "s/hahm/homematicip_local/g" .storage/core.device_registry` **BEFORE** restarting HA with the new version.

There is no need to rename devices, but when the above step missed out new devices (with the new name) will be created after restart.

**Comment by eikowagenknecht** [comment]
This is what I did *before* the restart:

![image](https://user-images.githubusercontent.com/1475672/161761534-44d7e630-5052-46be-ae47-aac02bf25f8a.png)

Looks right to me?

**Comment by SukramJ** [comment]
Yes, so now you have to check `.storage/core.device_registry` as mentioned above.

**Comment by eikowagenknecht** [comment]
This is the device from before the update:

```
            {
                "config_entries": [
                    "2565974ba7d32a6a80e7f2f4a43e1f7e"
                ],
                "connections": [],
                "identifiers": [
                    [
                        "hahm",
                        "00185A498C4401@CCU3-HmIP-RF"
                    ]
                ],
                "manufacturer": "eQ-3",
                "model": "HmIP-SWO-PR",
                "name": "AU.Garten Wettersensor (Ger\u00e4t)",
                "sw_version": "1.0.18",
                "hw_version": null,
                "entry_type": null,
                "id": "fbfbc02fb8178c9b9c89948ece4ea0e3",
                "via_device_id": "655d25f0685d9d2534bc5b52e6d762ee",
                "area_id": "au_garten",
                "name_by_user": "AU.Garten Wettersensor",
                "disabled_by": null,
                "configuration_url": null
            },
```

The identifier looks like the one in your example.

**Comment by SukramJ** [comment]
Looks good.

Please add device 655d25f0685d9d2534bc5b52e6d762ee.
Do you have a backup of the migrated entries (and after the restart)?

**Comment by eikowagenknecht** [comment]
This is 655d25f0685d9d2534bc5b52e6d762ee (also *before* the update)

```
            {
                "config_entries": [
                    "2565974ba7d32a6a80e7f2f4a43e1f7e"
                ],
                "connections": [],
                "identifiers": [
                    [
                        "hahm",
                        "CCU3"
                    ]
                ],
                "manufacturer": "eQ-3",
                "model": "CCU",
                "name": "CCU3",
                "sw_version": "3.63.8.20220330",
                "hw_version": null,
                "entry_type": "service",
                "id": "655d25f0685d9d2534bc5b52e6d762ee",
                "via_device_id": null,
                "area_id": "kg_flur",
                "name_by_user": "KG.Flur Homematic CCU3",
                "disabled_by": null,
                "configuration_url": "http://192.168.40.31"
            },
```

I have no backup of the migrated entries but I can do the migration again and post the results.

**Comment by Lemocin** [comment]
Klingt nach einem ähnlichen Problem, das ich hier auch erwähnt hatte: [Dev-Talk](https://github.com/danielperna84/hahomematic/discussions/12#discussioncomment-2461452)

`sed -i "s/hahm/homematicip_local/g" .storage/core.config_entries` musste ich auch zwei Mal ausführen. 

Eventuell überschreibt HA da etwas, wenn man nicht schnell genug ist...

**Comment by SukramJ** [comment]
@Lemocin Could be. But what is so active on the registries. Do you use mqtt?

@eikowagenknecht please make a copy of .the files before and after restart.
Please check the files before restart.

**Comment by Lemocin** [comment]
> @Lemocin Could be. But what is so active on the registries. Do you use mqtt?

Yes, I'm using [EMS-ESP32](https://github.com/emsesp/EMS-ESP32)

**Comment by eikowagenknecht** [comment]
So I think @Lemocin has a very good point there. I'm currently in the migration process and I have the files open in notepad++. After the sed command no "hahm" is there any more.. but a few seconds later it comes back. Not only in one but multiple files. Seems like they are in active use and rewritten every now and then from some (cached?) source.

**Comment by SukramJ** [comment]
The files on all my machines (Raspi/PVE, beta/latest) where updated after the last restart and then not touched for hours.

**Comment by eikowagenknecht** [comment]
So I managed to execute the command so often and then quickly restarting that the files stayed on "homematicip_local". But that seems like it warrants a warning or safer method in the migration doc, even though only some users (like me and @Lemocin are affected so far).

It works fine now, though. No more duplicates :-)

**Comment by SukramJ** [comment]
Next time, whenever that is, we can migrate programatically, so this is a one time action.

What would you add to the migration plan?

**Comment by Lemocin** [comment]
Maybe [noxhirsch](https://github.com/danielperna84/hahomematic/discussions/12#discussioncomment-2467168)
has a point here and a solution could be, to chain the commands with `&& `and  to add an additional `ha core restart`. I think it would be the fastest way to change the files and restart HA.

To explain the individual commands, the individual bullet points could remain. But as a recommendation the chained command might be given.

**Comment by eikowagenknecht** [comment]
> What would you add to the migration plan?

Command chaining seems to be a solution that could quite likely work as it minimizes the time betweed the change and the restart.

Alternatively (or better additionally) I'd add a warning like:

"Please be aware that changing the registry files directly (even with the sed command) is not officially supported by HA. In busy HA installations the files may be rewritten quite often from cache, so the changes might be lost again. Please make sure to instantly restart HA after the sed commands (e.g. with `ha core restart`) and check that the files do not contain "hahm" any more after the migration. lf they do, you were probably not fast enough. To avoid strange side effects you need to restore your backup and try again."

**Comment by SukramJ** [comment]
Thanks a lot, i added the warning.
