### ISSUE TITLE
BATTERY_STATE von HM Geräten als Diagnose-Entität

### ISSUE THREAD

**Issue by Baxxy13** [SukramJ/hahomematic#392]
DONT'T DELETE THIS.

**Is your feature request related to a problem? Please describe.**
Bei IP-Geräten gibt es ja die (per default deaktivierte) Diagnose-Entität "OPERATING_VOLTAGE".  Ganz nützlich bei Batterieaktoren / Sensoren. Einige HM-Geräte haben den Datenpunkt "BATTERY_STATE" der auch die Batteriespannung ausgibt. Z.B. HM-TC-IT-WM-W-EU und HM-CC-RT-DN.

**Describe the solution you'd like**
Ich würde es gut finden wenn "BATTERY_STATE" auch per default als deaktivierte Diagnose-Entität verfügbar wäre.

**Describe alternatives you've considered**
Man kann BATTERY_STATE schon jetzt mittels unignore aktivieren. Da fehlt dann aber erstmal ein nettes Symbol und die Entität ist unter den Sensoren gelistet.

**Additional context**
![HA_BATTERY_STATE](https://user-images.githubusercontent.com/54898249/162327635-ea40e621-f335-4542-a8d5-e3e308e9cd11.JPG)

**Comment by SukramJ** [comment]
Kann ich machen. Diesen Parameter gibt es scheinbar **nur**  bei HM-TC-IT-WM-W-EU und HM-CC-RT-DN.

**Comment by SukramJ** [comment]
Veröffentlicht mit 1.1.0.beta1
