### ISSUE TITLE
Script to return the serials of the current rf-module

### ISSUE THREAD

**Issue by SukramJ** [SukramJ/hahomematic#397]
DONT'T DELETE THIS.

**Is your feature request related to a problem? Please describe.**
I need a script to extract the serial**s** hm/hmip of the current rf-module.
The JsonRPC method `CCU.getSerial` only returns one serial, and in combination with `HM-MOD-RPI-PCB` only the rf-serial.
For a match with the UPNP-Response i need the hmip-serial. The rf-serial is required for better diagnostics and as fallback.

**Describe the solution you'd like**
The script should return a json like this:
```
{
"rf_serial": "5A4993D111",
"hmip_serial": "5A4993D111"
}
```

**Describe alternatives you've considered**

**Additional context**

**Comment by SukramJ** [comment]
Hi @baxxy13,

i already noticed that the data i need is included in your [Analysescript ...](https://homematic-forum.de/forum/viewtopic.php?f=31&t=62096&p=614148#p614148), but my scripting knowledge is very limited.
Could you create a stripped down script that meats the above mentioned requirements?

**Comment by Baxxy13** [comment]
Hi, ich mache das mal auf Deutsch. Liegt mir besser.

Wenn ich mich recht entsinne wird für das HM-MOD-RPI-PCB gar keine "hmip-serial" generiert, sondern nur die alte im "BidCos-Style" (PEQxxxxx). Ist aber schon eine Weile her seit ich damit zu tun hatte.

Da müsste mal jemand mit dem Modul schauen was in...
`/var/hmip_board_serial` drinsteht. (CCUx / RM)

Mini-Script zum auslesen:
```
var boardserial;
system.Exec("cat /var/hmip_board_serial", &boardserial);
    boardserial = boardserial.Trim();
    WriteLine("Funkmodul SN: "# boardserial);
```

**Comment by SukramJ** [comment]
@Lemocin Kannst du hier mal schauen?

**Comment by Lemocin** [comment]
> ```
> var boardserial;
> system.Exec("cat /var/hmip_board_serial", &boardserial);
>     boardserial = boardserial.Trim();
>     WriteLine("Funkmodul SN: "# boardserial);
> ```

Funkmodul SN: PEQ2216061

Wobei `pivccu-info` meldet:
```
HMRF Hardware:  HM-MOD-RPI-PCB
 Connected via: GPIO (/dev/raw-uart)
 Board serial:  PEQ2216061
 Radio MAC:     0x6BDD88
HMIP Hardware:  HM-MOD-RPI-PCB
 Connected via: GPIO (/dev/raw-uart)
 SGTIN:         3014F711A061A7D8A9AB387D
 Radio MAC:     0xBC58AC
```
und die SGTIN mit UPNP übereinstimmt...

**Comment by Baxxy13** [comment]
Ok. Dann nehmen wir doch die SGTIN...
```
var boardserial;
system.Exec("cat /var/board_sgtin", &boardserial);
    boardserial = boardserial.Trim();
    WriteLine("Funkmodul SN: "# boardserial);
```

**Comment by Lemocin** [comment]
> Ok. Dann nehmen wir doch die SGTIN...
> 
> ```
> var boardserial;
> system.Exec("cat /var/board_sgtin", &boardserial);
>     boardserial = boardserial.Trim();
>     WriteLine("Funkmodul SN: "# boardserial);
> ```

Funktioniert. 

Hatte einen Gedankenfehler und dachte dass Serial=SGTIN aber dem ist wohl nicht so?

**Comment by Lemocin** [comment]
> ```
> var boardserial;
> system.Exec("cat /var/board_sgtin", &boardserial);
>     boardserial = boardserial.Trim();
>     WriteLine("Funkmodul SN: "# boardserial);
> ```

Ausgabe: `Funkmodul SN: 3014F711A061A7D8A9AB387D
`

Ausgabe UPNP: [hier](https://github.com/danielperna84/hahomematic/discussions/12#discussioncomment-2461801)

**Comment by Baxxy13** [comment]
> Serial=SGTIN

Das ist etwas "kompliziert". 
Beim RPI-RF-MOD und HmIP-RFUSB ist die `hmip_serial` in der SGTIN mit drin.

Beim HM-MOD-RPI-PCB wird die `hmip_serial` noch im BidCos Style generiert (PEQxxxx). Wie daraus dann die SGTIN erzeugt wird weiß ich nicht. 
Ich würde mal vermuten das eine CCU2 auch keine "korrekte" `hmip_serial` hat. 

Diese eindeutige Identifikation mittels Funkmodul-SN hat m.E. einen Haken.
Zieht man bspw. von CCU2 zu CCU3 / RM etc. um oder wechselt das Funkmodul bekommt man eine neue SN. Und hätte damit aus Sicht von HA auch wieder eine neue Zentrale.

Die IP-Adresse als Identifikator fand ich daher gar nicht so verkehrt. Die ist zwar auch nicht in Stein gemeißelt, aber der User kann relativ leicht dafür sorgen das die neue Zentrale wieder die IP der alten Zentrale bekommt.

**Comment by SukramJ** [comment]
Moin,

folgende Punkte sprechen gegen di IP:
- eine IP wird wird bei HA nicht als unique_id akzeptiert.
- das RM-HA-Addon meldet sich ggf. unter 2 IPs (intern/extern)

Einen Modulwechsel hab ich auch bedacht, aber zum einen vermute ich, das sowas sehr selten vorkommt, und zum anderen geht dadurch ja nicht die Integration kaput.

Ich möchte in erster Linie einen Fall wie bei @Lemocin vermeiden, wo eine alte PEQ-SN geliefert wird, obwohl auch eine SGTIN vorhanden ist.

Da ich ja mittlerweile ein wenig in den OCCU suche hab ich noch folgendes [gefunden](https://github.com/eq-3/occu/blob/master/WebUI/www/upnp/basic_dev.cgi):

```
proc get_serial_number {} {
    if {[file exist /var/board_sgtin]} {
      set serial [exec cat /var/board_sgtin]
    } elseif {[file exist /var/board_serial]} {
      set serial [exec cat /var/board_serial]
    } elseif {[file exist /sys/module/plat_eq3ccu2/parameters/board_serial]} {
      set serial [exec cat /sys/module/plat_eq3ccu2/parameters/board_serial]
    } else {
      set serial ""
    }
    return $serial
```

So wird die SN in der UPN-Nachricht erzeugt. 
Das statt als TCL(??) in rega script, und auf beiden Seiten sollte das gleich Ergebnis rauskommen.

[Edit] In dem Fall sollte natürlich auch nur eine SN im Ergebnis reichen.

**Comment by Baxxy13** [comment]
Also `/sys/module/plat_eq3ccu2/parameters/board_serial` habe ich noch nie gesehen.
Hier mal ein Testscript was die 3 möglichen "Fundstellen" in obiger Reihenfolge durchläuft und die erste gefundene SN ausgibt.
```
string hmip_serial; string error; boolean find = false;
string cmd_a = "/bin/sh -c 'cat /var/board_sgtin'";
string cmd_b = "/bin/sh -c 'cat /var/board_serial'";
string cmd_c = "/bin/sh -c 'cat /sys/module/plat_eq3ccu2/parameters/board_serial'";
system.Exec(cmd_a, &hmip_serial, &error);
if (hmip_serial) { hmip_serial = hmip_serial.Trim(); find = true; }
 if (!find) { system.Exec(cmd_b, &hmip_serial, &error);
  if (hmip_serial) { hmip_serial = hmip_serial.Trim(); find = true; }}
   if (!find) { system.Exec(cmd_c, &hmip_serial, &error);
    if (hmip_serial) { hmip_serial = hmip_serial.Trim(); }}
     if (hmip_serial) {
         hmip_serial = '{"hmip_serial": "'# hmip_serial #'"}';
          WriteLine(hmip_serial); }
      else { WriteLine("No SN found!"); }
```

Wenn die `/var/board_sgtin` auf allen Systemen existiert (müsste geprüft werden für CCU2 / piVCCU / DebMatic) dann bräuchte man die anderen Fundstellen gar nicht erst abfragen.

Testausgabe sieht so aus...
`{"hmip_serial": "3014F711A0001F5A4993E823"}`

Geht das als json durch?

**Comment by SukramJ** [comment]
Super. 
Das geht als json durch und funktioniert auch im Code.

@Lemocin Bitte testen. Kommt bei dir auch die SGTIN raus?

**Comment by Baxxy13** [comment]
Ich habe mal kurz eine RM mit dem HM-MOD-RPI-PCB getestet. (kurz vom LGW zur RM gemacht)
upnp (Auszug):
```
<device>
<deviceType>urn:schemas-upnp-org:device:Basic:1</deviceType>
<presentationURL/>
<friendlyName>HomeMatic Central - Pi2Bplus-103-RM-LGW</friendlyName>
<manufacturer>EQ3</manufacturer>
<manufacturerURL>http://www.homematic.com</manufacturerURL>
<modelDescription>HomeMatic Central 3014F711A061A7D8A99189C2</modelDescription>
<modelName>HomeMatic Central</modelName>
<UDN>uuid:upnp-BasicDevice-1_0-3014F711A061A7D8A99189C2</UDN>
<UPC>123456789002</UPC>
```
Scriptausgabe:
`{"hmip_serial": "3014F711A061A7D8A99189C2"}`

Passt überein.

**Comment by SukramJ** [comment]
Mit Version 1.1.0.beta1 veröffentlicht

**Comment by dfigus** [comment]
Ich habe ja eine piVCCU3 am Start und dort gibt es `/var/board_sgtin`. Script funktioniert bei mir.
