### ISSUE TITLE
Installation of integration Homematic(IP) Local in HA fails

### ISSUE THREAD

**Issue by gucki** [SukramJ/hahomematic#399]
Using latest Home Assistant 2022.4.1 the installation of the integration Homematic(IP) Local (1.0.5) doesn't work. In the logs the following errors are shown many times:

ERROR (MainThread) [backoff] Giving up async_download_file(...) after 5 tries (TypeError: timeout() got an unexpected keyword argument 'loop')
ERROR (MainThread) [custom_components.hacs] Download was not completed [timeout() got an unexpected keyword argument 'loop']

**Comment by SukramJ** [comment]
Please fill out the issue template. 
This looks like a hacs error.

**Comment by gucki** [comment]
Yes, I'm really sorry. It was caused by an outdated HACS version.
