### ISSUE TITLE
BidCos-Wired Integration funktioniert leider nicht

### ISSUE THREAD

**Issue by Keili78** [SukramJ/hahomematic#402]
DONT'T DELETE THIS.
Please answer all questions as good as possible.

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
1.1.0

**Home Assistant version (if applicable):**
2022.4.1

**CCU version:**
- Model Raspi3
- OS RaspberryMatic
- Version: 3.63.8.20220330

**Problem-relevant configuration:**

Do you use tls? nein
Do you use callback? nein
Do you use username and password? ja
Which interfaces do you use? Bidcos-RF, Bidcos-Wired

**Describe the bug**
Wenn ich versuche die Integration von der BidCos-wired Komponenten zu aktivieren bekomme ich einen Fehler. 
Die RF-Komponenten funktionieren. Die Konfiguration wird dann mit "Verbindung fehlgeschlagen" beendet, im HA Log taucht dann folgende Meldung auf: 
################################################
Logger: custom_components.homematicip_local.config_flow
Source: custom_components/homematicip_local/config_flow.py:157
Integration: Homematic(IP) Local ([documentation](https://github.com/danielperna84/custom_homematic), [issues](https://github.com/danielperna84/hahomematic/issues))
First occurred: 10. April 2022, 12:26:30 (5 occurrences)
Last logged: 11:58:39

Unable to connect (<Fault -1: 'getVersion: unknown method name'>,).
################################################

Wenn ich mir das Objektmodell von EQ3 anschaue, ist die Methode "getVersion" nicht in der BidCos-Wired schnittstelle implementiert.
https://www.eq-3.de/Downloads/eq3/download%20bereich/hm_web_ui_doku/HM_XmlRpc_API.pdf
Seite 10/11

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/37800344/162714757-20f66e92-e14c-477b-9267-f3b822f8813c.png)
![image](https://user-images.githubusercontent.com/37800344/162714863-cfbc1a51-8e7a-4646-91e8-0410a5c61b6e.png)

**Comment by SukramJ** [comment]
Thanks for reporting.
The bidscos wired and getVersion problem is well known and not fixed in all places. 
Should be fixed with version 1.1.1

**Comment by SukramJ** [comment]
Please report, if it is fixed.

**Comment by Keili78** [comment]
Thanks a lot. I'll report as soon as possible.
btw. really great work!

**Comment by Keili78** [comment]
I've upgradet. It works now.
Thank you very much.
Kind regards
