### ISSUE TITLE
 HM-LC-RGBW-WM support

### ISSUE THREAD

**Issue by Hypnos3** [SukramJ/hahomematic#408]
Please support Homematic "HM-LC-RGBW-WM" Device.

In the current device the channels only supported as numeric parameter:
![image](https://user-images.githubusercontent.com/12692680/163271030-bee2e2ab-8ad0-4266-baeb-ff46fbc399cc.png)

In the old Homematic Integration this device has full support as light with color selection.

**Comment by SukramJ** [comment]
Hi,
Your device is currently broken in [pydevccu](https://github.com/danielperna84/pydevccu).
Please export a device definition as  described [here](https://github.com/danielperna84/custom_homematic#homematicip_localexport_device_definition) 
Afterward please add the DD (2 files per device) to a new issue/PR at  [pydevccu](https://github.com/danielperna84/pydevccu).
Thanks.

**Comment by Hypnos3** [comment]
Thank you,
I have created [pydevccu/ issue 25](https://github.com/danielperna84/pydevccu/issues/25)

**Comment by SukramJ** [comment]
Please retest with 1.1.3.
