### ISSUE TITLE
Reconfiguration required after each Home Assistant Update

### ISSUE THREAD

**Issue by smartmatic** [SukramJ/hahomematic#409]
DONT'T DELETE THIS.
Please answer all questions as good as possible.

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
1.1.2

**Home Assistant version (if applicable):**
2022.4.3

**CCU version:**
- OS: RaspberryMatic on RPI
- Version: 3.63.8.20220330

**Problem-relevant configuration:**

Do you use tls?
No
Do you use callback?
No
Do you use username and password?
yes
Which interfaces do you use?
HA and RaspberyMatic

**Describe the bug**
Since HA 2022.4.x a reconfiguration of the integration is required after each HA update. The same Homematic Environment is discovered again.
I thought maybe the settings are lost and i tried to configure the discovered RaspberyMatic instance again. But now i have two integrations **for the same instance!**

![Bildschirmfoto 2022-04-14 um 07 52 16](https://user-images.githubusercontent.com/74932663/163323484-d24e964f-2b38-4bc4-83c2-06efd13d6202.png)

**To Reproduce**
1. Update to HA 2022.4.x
2. Restart HA
3. Check Devices & Services for new auto discovery of Custom Homematic

**Screenshots (if applicable)**
Existing First working integration:
![RaspberyMatic Prod First Integration](https://user-images.githubusercontent.com/74932663/163323859-3bb116bf-7b72-4b5f-a646-bb0bdd1227ef.png)

New discovered second integration
![New discovered equal second instance](https://user-images.githubusercontent.com/74932663/163323898-a5f5a221-6096-4b99-8fef-f4b5fb4cad4d.png)

**Relevant HA log entries (full log)**

**Diagnostic Information (available on every device)**
[config_entry-homematicip_local-0dd814ad370186796d64263873d3de98.json.txt](https://github.com/danielperna84/hahomematic/files/8486630/config_entry-homematicip_local-0dd814ad370186796d64263873d3de98.json.txt)

[config_entry-homematicip_local-7172fbf0b86ec6e8f25dda9c2d110fc9.json.txt](https://github.com/danielperna84/hahomematic/files/8486633/config_entry-homematicip_local-7172fbf0b86ec6e8f25dda9c2d110fc9.json.txt)

**Expected behavior**
One integration without need to reconfigure after HA update

**Additional context**

**Comment by SukramJ** [comment]
What i can see in [config_entry-homematicip_local-7172fbf0b86ec6e8f25dda9c2d110fc9.json.txt](https://github.com/danielperna84/hahomematic/files/8486633/config_entry-homematicip_local-7172fbf0b86ec6e8f25dda9c2d110fc9.json.txt) is that you maybe did not read the release notes.

> See chapter [auto-discovery](https://github.com/danielperna84/custom_homematic#auto-discovery), to get rid of an auto discovered instance.

This instance has a unique_id with IP-Address, whereby new instances use the last 10 digits of the rf-models SN.
So delete one instance and click on "configure" one the other instance as mentioned in the release notes.

**Comment by smartmatic** [comment]
> What i can see in [config_entry-homematicip_local-7172fbf0b86ec6e8f25dda9c2d110fc9.json.txt](https://github.com/danielperna84/hahomematic/files/8486633/config_entry-homematicip_local-7172fbf0b86ec6e8f25dda9c2d110fc9.json.txt) is that you maybe did not read the release notes.
> 
> > See chapter [auto-discovery](https://github.com/danielperna84/custom_homematic#auto-discovery), to get rid of an auto discovered instance.
> 
> This instance has a unique_id with IP-Address, whereby new instances use the last 10 digits of the rf-models SN. So delete one instance and click on "configure" one the other instance as mentioned in the release notes.

I read the documentation and i just create this issue as this behaviour appears since HA 2022.4.x. Before went everything fine and my instance was not discovered twice! If you are not interested in this information ok. 

And to be honest the documentation does from my point of view not clearly describe what to do in this situation:

Delete the existing configured integration or ignore the new discovered? 

I choose ignore as i configured everything but it is a confusing behaviour. A similar case appears in the past for the Withings integration and this was a bug. Therefore i raised this issue as it looks similar.

**Comment by SukramJ** [comment]
> If you are not interested in this information ok.

That's not the point, but one of instances is in an old state, and that should be fixed by clicking on configure on the existing instance. After a restart the discovered one should be gone.

There is no need to setup a discovered instance.

**Comment by smartmatic** [comment]
> > If you are not interested in this information ok.
> 
> That's not the point, but one of instances is in an old state, and that should be fixed by clicking on configure on the existing instance. After a restart the discovered one should be gone.
> 
> There is no need to setup a discovered instance.


And how can that happen? After the announcement of the breaking change i completely deleted and cleaned up the previous configuration and started new.

**Comment by SukramJ** [comment]
This could occure since 1.1.0. 
I updated the release notes

**Comment by SukramJ** [comment]
Closing this for now. Reopen if the problem reoccurs.
