### ISSUE TITLE
Please add the attribute voltage for (battery operated) devices

### ISSUE THREAD

**Issue by vakilando** [SukramJ/hahomematic#411]
DONT'T DELETE THIS.

Some Information first:
I use Home Assistant Core as a docker on Unraid. The version is 2022.4.1
I have a Raspberry 3b with pivccu as OS. The version is 3.63.8-70

**Is your feature request related to a problem? Please describe.**

pyhomematic fetched the actual voltage for the climate HmIP-eTRV-2 (for example) as an attribute of the entity.
This attribute is missing in hahomematic. The only way to get some information about the battery status is the binary_sensor "low_bat" which only says "_on_" or "_off_"
This is annoying because I used the attribute "_voltage_" to show the _exact_ battery status in lovelace.

**Describe the solution you'd like**

Please readd the attribute voltage - if possible - for all (battery operated) devices.

**Describe alternatives you've considered**

I could switch to only use the "low_bat" status "on" / "off" but I would love to have more precise informations...

**Additional context**

This is the code I use in my configuration.yaml for showing battery status in lovelace:

```
      # voltage_therm_arbeitszimmer:
      therm_azi_voltage:
        value_template: '{{ states.climate["000a1709a65432"].attributes.voltage }}'
        unit_of_measurement: 'Volt'
        friendly_name: 'Heizung Arbeitszimmer'
        icon_template: >-
          {% if state_attr('climate.000a1709a65432', 'voltage')|float > 2.8 %} 
            mdi:battery
          {% elif state_attr('climate.000a1709a65432', 'voltage')|float > 2.6 %} 
            mdi:battery-80
          {% elif state_attr('climate.000a1709a65432', 'voltage')|float > 2.4 %} 
            mdi:battery-60
          {% elif state_attr('climate.000a1709a65432', 'voltage')|float > 2.2 %} 
            mdi:battery-40
          {% elif state_attr('climate.000a1709a65432', 'voltage')|float > 2.0 %} 
            mdi:battery-20
          {% else %} 
            mdi:battery-alert-variant-outline 
          {% endif %}

```

See the screenshots of the entity (pyhomematic vs hahomematic):
![pic1](https://user-images.githubusercontent.com/36138919/163492591-7e0fe0d4-1490-4c71-8640-fa80eab724b0.png)

**Comment by Lemocin** [comment]
It's there as operating voltage, just disabled by default. 
![Screenshot_2022-04-15-06-00-46-35_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/4162496/163516206-4b8db983-f28d-4b22-828c-f7eed50c575c.jpg)


Go to the device(Einstellungen - Geräte & Dienste - Homematic local - Geräte) and enable the entities you need.

**Comment by vakilando** [comment]
Oh my good, sorry, it was just too late yesterday... Thank you!
