### ISSUE TITLE
RaspberryMatic System Variables not available anymore

### ISSUE THREAD

**Issue by marc965** [SukramJ/hahomematic#414]
DONT'T DELETE THIS.
Please answer all questions as good as possible.

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
1.1.2

**Home Assistant version (if applicable):**
2022.4.5

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, ...):
- OS (Original, RaspberryMatic, debmatic/...):
- Version: RaspberryMatic Current version: 3.63.8.20220330

**Problem-relevant configuration:**

Do you use tls? no
Do you use callback? no
Do you use username and password? yes
Which interfaces do you use? rf, HmIP, Group

**Describe the bug**
After HomeAssistant Updates and Restart the homematic integration does not have any system variables anymore.
After a second Restart of HomeAssistant all system variables are back.
See issue #361... 

**To Reproduce**
Install Home Assistant Core Updates and after restart look at your homematic system variables.

**Screenshots (if applicable)**
- CCU firewall
- integrations view
- device view
- enity view

**Relevant HA log entries (full log)**

No entries in the log, but i have default logger configuration.

`logger:
default: warning`  

Tell me what to add for detailed log of homematic integration

**Diagnostic Information (available on every device)**
```


```

**Expected behavior**

**Additional context**

**Comment by JoMass** [comment]
This issue had been fixed with version 0.36.4; However with version around ~1.0.5  it came back again. Can confirm that with a complete system restart  I phase this behavior (1.1.2 with core-2022.4.5).  Anything else works fine and a 2nd  restart of the core fills the entities with proper values.

**Comment by SukramJ** [comment]
@marc965 
To answer your question:

```
logger:
  default: info
  logs:
    hahomematic: debug
    custom_components.homematicip_local: debug
```

To be honest I can't do much with the error description.
- Which updates are imported?
- What is restarted?
- What CCU is used?
- Does this have anything to do with #361?

**Comment by JoMass** [comment]
Just installed core 2022.4.6 together with custom_homematic 1.1.4, on my test system first  and then on my much more complex productive system. Both work fine again! after the full reboot, all custom_homematic entities shows up correctly.  Thanks a lot!

Version	core-2022.4.6
Installationstyp	Home Assistant OS
Python-Version	3.9.9
Betriebssystemfamilie	Linux
Betriebssystem-Version	5.10.108
CPU-Architektur	aarch64
Home Assistant Community Store
Home Assistant Supervisor
Host-Betriebssystem	Home Assistant OS 7.6
Update-Channel	stable
Supervisor-Version	supervisor-2022.04.0
Docker-Version	20.10.9
Speicherplatz gesamt	56.6 GB
Speicherplatz genutzt	12.3 GB
Board	odroid-n2

**Comment by SukramJ** [comment]
@marc965 Any updates here?

**Comment by marc965** [comment]
Hallo.

Beim letzten Core Update auf die 2022.4.6 ist es nicht passiert. Ich bin diese Woche nicht zu Hause. 
Das nächste Core Update mache ich am Wochenende. Davor aktiviere ich die Debug-Logs.
Melde mich dann...
Bis dahin funktioniert sonst aber alles. Dieser Fehler trat sonst immer nur nach einem Core-Update auf. Nach einem erneuten Neustart war das Problem wieder behoben. Im Log stand nichts, das steht aber noch auf "default".

Und ich sehe gerade du hattest noch ein paar Fragen:
Ja es hat direkt mit issue #361 zu tun, habe #361 nur nicht wieder aufgekriegt, weiss nicht wie das geht.

Es geht um den Neustart des Core, die RaspberryMatic oder das OS wurde dabei nicht neu gestartet. Alles andere steht oben im Header.

Ich melde mich ja nochmal am Wochenende und wir sehen dann was passiert. Hoffentlich steht dann etwas im Log.

VG

**Comment by marc965** [comment]
Hi.

Update on Home Assistant 2022.4.7 today with debug log.
After restart of core all system variables are present.

I am closing this issue.
