### ISSUE TITLE
Entity missing for FAULT_REPORTING on HM-CC-RT-DN

### ISSUE THREAD

**Issue by martymcbro** [SukramJ/hahomematic#415]
Hi,

I'm having a problem / inconvenience with homematic custom component version 1.1.2 for home assistant and the homematic thermostat HM-CC-RT-DN (Firmware 1.5). My CCU is a piVCCU3 version 3.59.6 running on a Raspberry Pi. I also faced the issue using the original home assistant core homematic integration. Diagnostic information for the device can be found here: 
[config_entry-homematicip_local-a4d1fb91cba962a79914133d3b1ad580.json.txt](https://github.com/danielperna84/hahomematic/files/8508419/config_entry-homematicip_local-a4d1fb91cba962a79914133d3b1ad580.json.txt)

The problem is, that since my switch from openhab to home assistant I am missing the data point "4#FAULT\_REPORTING" from my HM-CC-RT-DN thermostat. There is no entity for that. This is important for me, since e.g. battery low warnings for this device are not transmitted using the data point "0#LOWBAT" which probably translates into the "Lowbat" entity in home assistant. Instead the data point "4#FAULT\_REPORTING" is used. Sometimes the calibration run of this thermostat fails, which is also transmitted using this data point. Possible values for this data point I know of are:

NO_FAULT, VALVE_TIGHT, ADJUSTING_RANGE_TOO_LARGE, ADJUSTING_RANGE_TOO_SMALL, COMMUNICATION_ERROR, LOWBAT, VALVE_ERROR_POSITION

I don't know whether the term "4#FAULT\_REPORTING" is an openhab specific term or directly references a piece of device information on the homematic XML-RPC-interface. So if you need more information to create an entity for "4#FAULT\_REPORTING" please let me know.

In general in openhab more information is available for this device, see the attached file. 

[HM-CC-RT-DN.txt](https://github.com/danielperna84/hahomematic/files/8508415/HM-CC-RT-DN.txt)

Could you possibly add entities for all the missing data points or explain how I could maybe do this myself?

Regards

**Comment by SukramJ** [comment]
[This](https://github.com/danielperna84/hahomematic/blob/devel/docs/unignore.md) could be interesting for you.

**Comment by martymcbro** [comment]
Thanks a lot. That seems to have worked. I have the missing entity now :)
