### ISSUE TITLE
How to install in older HA version?

### ISSUE THREAD

**Issue by ManniTom** [SukramJ/hahomematic#416]
have to stay with HA Version2021.8.8 due to video reasons.
so how can i manually install custom_homematic to this system?
i have HACS installed, but also an older Version 1.15.1.
Is a manual install of custom_homematic possible?
if yes, how can it be done?

**Comment by danielperna84** [comment]
This new integration depends on features introduced in later Home Assistant versions. Hence it is __NOT__ advised to use it with older HA versions. It may partially work, but you'll probably run into problems.

You should definitely look into resolving your issue that currently forces you to stay with the old HA version. Usually there should be some way to work around such problems.

**Comment by ManniTom** [comment]
ok, then i have to upgrade.
why are there custom_homematic and hahomematic?
will it bioth be installed if i install custom_homematic with HACS?

**Comment by danielperna84** [comment]
> why are there custom_homematic and hahomematic?

One is the code for the integration into Home Assistant, the other is the HomeMatic-specific code that _talks_ to the CCU. They have to be in separate code bases to better organize stuff. Installing `custom_homematic` automatically installs `hahomematic`. In any case, if you follow the instructions everything should work. We don't include undocumented pitfalls to annoy the users. 😉
