### ISSUE TITLE
Automatically convert äöüß in entity ids

### ISSUE THREAD

**Issue by ProfDrYoMan** [SukramJ/hahomematic#421]
DONT'T DELETE THIS.

**Is your feature request related to a problem? Please describe.**
No, only partially. Extra work.

**Describe the solution you'd like**
Entity IDs should are automatically generated. But something like "Türkontakt" gets converted to "turkontakt".
It would be nice to see äöüß (and maybe other special chars) to be converted automatically wenn devices are added.

**Describe alternatives you've considered**

**Additional context**

**Comment by SukramJ** [comment]
We don't generate entity_ids we only generate names. 
So when HA core generated entity_ids it slugifies the name to get an entity_id.

**Comment by ProfDrYoMan** [comment]
Hmm, ok. So name gets taken over with äöü but HA squashes to aou. So nothing to do on your side. If this is the case. Feel free to close.
