### ISSUE TITLE
Slow updating of homematic variables and slow recognition of homematic crash

### ISSUE THREAD

**Issue by ManniTom** [SukramJ/hahomematic#423]
Hi,
i switched from the standard homematic integration mainly because the states of the homematic entities are updated much faster in custom_homematic than in old homematic integration. 

1) i noticed though, that the update of the homematic variables is still slow. i measured the time until the new variable state is available in home assistant is around 30 seconds with my system.
Since is still use quite a few variables from homematic for use in home assistant, i would prefer a quicker update.

2) i noticed that the new custom_homematic integration recognizes if the homematic system is not responsive anymore or crashed. that's a huge progress compared to the old integration. 
i also measured the time until a crashed homematic was recognized. results did vary between 2 minutes and 4 minutes.
could you make that faster, too?
Very nice to have would also be a means to control the reconnect to a crashed homematic system, eg. by calling a service. For this the old homematic integration provided a service called "homematic.reconnect".
i did not find such a service in your documentation, but maybe someting alike is already there?
Quite a few people have alreay programmed a detection for homematic crashes into home assistant by the use of automations or similar manner. this code could be continued to be used if you could provide a reconnet service.
Also the user would gain control over the timing!

Thanks for your good work!

Mani

My System: Newest Home Assistant software.
RaspberryMatic (x86), newest software version,  running as a VM.

**Comment by SukramJ** [comment]
Hi,

thanks for feedback.

Here we have to consider a wide variety of system from slow Raspi to fast x86 Systems.

The update speed of states is identical to the old integration as both systems rely on CCU callbacks and update  state immediately.

1. The sysvar polling interval is the same (30s) as in the old integration, and we should not poll more often.
2. I think a restore of a HOME automation system within 5 minutes is an acceptable interval. There are several checks running to ensure that a CCU is not only up but also usable over the APIs. I did not implement the reconnect server to avoid complexity for the end user.

How often does your CCU crash?

BR

[Edit] 
2. We check CCU availability every 30s and try a reconnect every 120s.

**Comment by ManniTom** [comment]
i can imagine why you don't want to speed up a crash recognition, and it's not very important to me, as my system normally does not crash.

but 30s update rate for the homematic variables is very slow.
maybe this is a good rate for slow systems, but on faster systems this is really slow.
so why not make it configurable?
would be a good benefit...

**Comment by SukramJ** [comment]
We avoid every additional configuration, because every option needs to be tested.

**Comment by SukramJ** [comment]
@danielperna84 What do you think?

**Comment by danielperna84** [comment]
I'm not a fan of making this configurable. If something depends on quicker updates of the variables, there probably is a more efficient implementation possible by doing the job in HA straight away.

And if not, it's still not worse than before the way it is right now. And I recall the bug in RaspberryMatic caused disk writing for each login, which had the potential to corrupt the SD cards of the systems. Though this has been fixed, it still makes me cautious on hammering the API.

**Comment by ManniTom** [comment]
Not worse than before is correct. What a pity.

One last question:

SukramJ said:
"The update speed of states is identical to the old integration as both systems rely on CCU callbacks and update state immediately."

But with my system core 2021.8.8 and the old homematic integration the update rate of the STATES was also 30s.
How Come?
(The new system with 2022.4.5 updates states at once.)

**Comment by danielperna84** [comment]
> But with my system core 2021.8.8 and the old homematic integration the update rate of the STATES was also 30s.
> How Come?

The new integration uses exactly the same mechanism as the old integration. If you experience delays with the old integration, then something about your setup is broken.

**Comment by ManniTom** [comment]
Thank you.
