### ISSUE TITLE
Buttons of the HmIP-BSM are not useable as a trigger

### ISSUE THREAD

**Issue by MaDtz** [SukramJ/hahomematic#426]
DONT'T DELETE THIS.
Please answer all questions as good as possible.

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
1.1.4

**Home Assistant version (if applicable):**
2022.4.7

**CCU version:**
- CCU3
- RaspberryMatic
- Version: 3.63.8.20220330 (rpi3)

**Describe the bug**
You can´t use a HmIP-BSM device as a trigger in automations.

**To Reproduce**
1. Go to Settings > Automations & Scenes > Automations
2. Create new, empty automation
3. Select "device" as Trigger
4. When you select a HmIP-BSM device, you can´t select a trigger.

**Screenshots (if applicable)**
Selected a HmIP-BSM device:
![grafik](https://user-images.githubusercontent.com/75381734/165273584-08cdb907-21f3-4a2d-88e6-558c73ae8f12.png)
![grafik](https://user-images.githubusercontent.com/75381734/165274792-62e6d285-e1e7-4fa0-bf83-c1b887e2873b.png)

Selected a HmIP-BDT, HMIP-WRC2 or HmIP-BRC2 device:
![grafik](https://user-images.githubusercontent.com/75381734/165273845-95983a96-40da-43b0-b98e-b2659fb0dae5.png)
![grafik](https://user-images.githubusercontent.com/75381734/165274863-cea46c89-174b-44d3-9c06-f6c4a36f7ee7.png)

**Expected behavior**
I would expect the same behavior like the other divces with buttons, that I can use/select for example "Taster "1" wurde nach langem Tastendruck los gelassen" as a trigger.

**Log-Entry**

`2022-04-26 12:17:37 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140480635912880] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 292, in with_error_handling
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 351, in websocket_device_automation_list_triggers
    await async_get_device_automations(
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 224, in async_get_device_automations
    for domain_results in await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 182, in _async_get_device_automations_from_domain
    return await asyncio.gather(
  File "/config/custom_components/homematicip_local/device_trigger.py", line 64, in async_get_triggers
    control_unit: ControlUnit = hass.data[DOMAIN][entry_id]
KeyError: '361ac085b0b9187a8a29ff090a17389c'`

**Diagnostic Information**
[config_entry-homematicip_local-fda5bb615969b461658aaf796fc25e43.json.txt](https://github.com/danielperna84/hahomematic/files/8562260/config_entry-homematicip_local-fda5bb615969b461658aaf796fc25e43.json.txt)

**Comment by SukramJ** [comment]
Are you sure that there are no logs in HA (click on Full log)?

**Comment by MaDtz** [comment]
Sorry Sukram, I forgot the log. I edited my issue and added the log-entry.

**Comment by SukramJ** [comment]
Better.
Next, add diagnostic Information: "Diagnoseinformationen herunterladen" on the device.

**Comment by SukramJ** [comment]
Do you use `Switch as X` for HmIP-BSM?

**Comment by MaDtz** [comment]
Diagnostic file is added an yes I use Switch as X.

**Comment by SukramJ** [comment]
The issue is related to new `Switch as X` feature.
This will be fixed in 1.2.0.

Thanks for reporting an issue.

**Comment by SukramJ** [comment]
1.2.0 is released

**Comment by MaDtz** [comment]
1.2.0 solved the problem. Everything is fine now. So you can close this issue. Thanks for your help and the good work!!!
