### ISSUE TITLE
Motion Detector SMI current Illumination not correct

### ISSUE THREAD

**Issue by MagicMilamber** [SukramJ/hahomematic#433]
Hello,

Seems there is a lock in polling the acutal Values.
Value didn't change for hour and over night. After reload integration the acutal Value got.
Motion detection for Same senor worked fine in the same timeframe.

**Comment by SukramJ** [comment]
We don't poll data. We receive data from CCU.

Please fill out the issue template!
There is a reason why you should NOT delete the data: Without these information the issue is useless.
