### ISSUE TITLE
Configuration: Not able to disable BidCos-RF permantely (low priority)

### ISSUE THREAD

**Issue by hklages** [SukramJ/hahomematic#440]
DONT'T DELETE THIS.
Please answer all questions as good as possible.

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
1.3.1

**Home Assistant version (if applicable):**
2022.5.4

**CCU version:**
- Model Raspberrymatic on Home Assistant OS RaspberryPi 4
- OS RaspberryMatic
- Version: 3.63.9.20220430

**Problem-relevant configuration:**

Do you use tls? no
Do you use callback? no
Do you use username and password? yes
Which interfaces do you use? Homematic IP

**Describe the bug**
Unchecking the BidCos RF is not permanent. 

**To Reproduce**
Steps to reproduce the behaviour
1. Go to Integration and configure
2. Push submit to get to the 2nd screen
3. Uncheck the BidCos RF option
4. Submit
5. When starting the config dialog again, the box is cheched again

**Screenshots (if applicable)**
- CCU firewall
- integrations view
- device view
- enity view

**Relevant HA log entries (full log)**
none

**Diagnostic Information (available on every device)**
none

**Expected behavior**
Obvious - should be permanent

**Additional context**
In my installation there are only HomematicIP device, so I dont need the BidCosRF interface.

**Comment by SukramJ** [comment]
If you reconfigure the integration, the second page always displays default values (HmIP and BidCos)
If you want to know which interfaces are active you could use device diagnostics and have a look at the config  entry.

**Comment by hklages** [comment]
Understand. That's not a typical behavior in Home Assistant. Usually a configuration dialog picks up the active settings, not the defaults.  

Thanks for pointing me to the device diagnostics - there everything is fine.
