### ISSUE TITLE
HM-LC-Sw1PBU-FM with lowbat channel

### ISSUE THREAD

**Issue by ThomDietrich** [SukramJ/hahomematic#444]
**custom_component/hahomematic version (if applicable):**
1.3.3

**Home Assistant version (if applicable):**
2022.5.2

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, ...): Raspberry Pi 3
- OS (Original, RaspberryMatic, debmatic/...): RaspberryMatic
- Version: 3.63.9.20220430 (rpi3)

**Problem-relevant configuration:**

Do you use tls?
Do you use callback?
Do you use username and password?
Which interfaces do you use?

**Describe the bug**

Hey all,
The HM-LC-Sw1PBU-FM is a AC wired component and does not have a battery. Does this need to be fixed?

https://www.eq-3.de/produkte/homematic/detail/hm-lc-sw1pbu-fm.html

![image](https://user-images.githubusercontent.com/2870104/168490993-f63ec6e6-a3eb-4132-8d39-71396c14a008.png)

**Comment by ThomDietrich** [comment]
Same problem with HM-LC-Sw1-FM, maybe this is an error with my setup?

**Comment by SukramJ** [comment]
See #382

**Comment by ThomDietrich** [comment]
I see.
The ticket didn't really come to a conclusion. It certainly did not resolve the bug, which this clearly is. I understand where the error comes from (paramset_description), but then an exception needs to be defined, correct?

Edit: Just realized the bug is worse as the state of lowbat in the examples is "normal" and not "unknown"/"unavailable" as it should be.

**Comment by SukramJ** [comment]
The value is "normal" because the device returns a value.
If you call it a bug you should open a ticket at eq-3.

Maybe i implement a work around some time.

**Comment by SukramJ** [comment]
Could be solved by #445

**Comment by ThomDietrich** [comment]
Definitely is a bug, no matter who is responsible for it :) Thanks for opening #445
