### ISSUE TITLE
HASS - 'Invalid Add-on repository' error

### ISSUE THREAD

**Issue by sebastian-tischer** [SukramJ/hahomematic#489]
**Home Assistant version (if applicable):**
Home Assistant Core 2022.6.1
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1

**CCU version:**
- Raspberry Pi 4 (4GB) + Argon One M.2 Case + SSD 250GB + HmIP-RFUSB
- OS: RaspberryMatic
- Version: 3.63.9.20220521

**Describe the bug**
I use a HASS OS on my Raspberry PI together with the new RaspberryMatic installation. While trying to install the custom_homematic like stated here, I get the following error message:

Invalid Add-on repository!

**To Reproduce**
1. Go to Settings > Add-ons > Add-on Store
2. Click on **3 dots** > Repositories
3. Enter https://github.com/danielperna84/custom_homematic

**Comment by danielperna84** [comment]
Du hast die Doku vermutlich nicht richtig gelesen. Für das RaspberryMatic Add-on bitte dieser Doku folgen: https://github.com/jens-maus/RaspberryMatic/wiki/Installation-HomeAssistant

__Hinterher__ kannst du dann [dieser](https://github.com/jens-maus/RaspberryMatic/wiki/HomeAssistant-Integration) Anleitung folgen um die neue Integration zu installieren.

**Comment by sebastian-tischer** [comment]
Doch aber sicher hab ich alles gelesen, denn bei der zweiten Anleitung kommen wir ja genau an den gleichen Punkt:

https://github.com/jens-maus/RaspberryMatic/wiki/HomeAssistant-Integration#homematicip-local-integration-setup

Wenn ich jetzt versuche das Repository einzubinden (https://github.com/danielperna84/custom_homematic) kommt:

Invalid Add-on repository!

Ich werde jetzt aufgrund Funkproblemen eine CCU3 holen, aber es ändert nichts an der Integration dieser nach obiger Anleitung.

**Comment by sebastian-tischer** [comment]
Ach shit, dumm ohne Ende - dacht HACS ist integriert wurden im vorletzten Update und nun unter Custom Repositories in Addons. JA sorry, erledigt - Fehler direkt vorm Mac :(
