### ISSUE TITLE
1 service, but no devices found

### ISSUE THREAD

**Issue by A30BL** [SukramJ/hahomematic#497]
DONT'T DELETE THIS.
Please answer all questions as good as possible.

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
1.8.6

**Home Assistant version (if applicable):**
2022.6.5

**CCU version:**
- Model: Raspi3b
- OS: RaspberryMatic
- Version: 3.63.9.20220521
 
**Problem-relevant configuration:**

Do you use tls? no
Do you use callback? no
Do you use username and password? yes
Which interfaces do you use? Homematic IP Port 2010, Homematic (Bidcos-RF) 2001

**Describe the bug**
After Installing the integration, there is one service running, but devices are not found.

**Screenshots (if applicable)**
![01 service](https://user-images.githubusercontent.com/69244094/173041416-c17dda3f-3c10-4699-ba4e-c035959558f4.png)
![02 config](https://user-images.githubusercontent.com/69244094/173041436-35cb652e-be73-4bdd-85b1-31fad41826f0.png)
![03 config](https://user-images.githubusercontent.com/69244094/173041458-aaf3dd5a-1044-4330-a8c8-400c6f1fa3b9.png)
![04 config](https://user-images.githubusercontent.com/69244094/173041477-b768bd2c-e1c1-46f5-85d9-83f0225c329d.png)
![05 device](https://user-images.githubusercontent.com/69244094/173041675-4b7e8d41-2cd0-4546-a71b-abc7315b5952.png)
![06 RaspberryMatic](https://user-images.githubusercontent.com/69244094/173042033-5c0f005a-602c-4b83-bf27-fe4c18926dfd.png)

**Relevant HA log entries (full log)**
Logger: hahomematic.central_unit
Source: /usr/local/lib/python3.9/site-packages/hahomematic/central_unit.py:338
First occurred: 06:45:21 (2522 occurrences)
Last logged: 17:17:16

_create_clients: Interface: BidCos-RF is not available for backend.
_create_clients: Interface: HmIP-RF is not available for backend.

**Diagnostic Information (available on every device)**
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.6.5",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.9.12",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "5.15.41",
    "supervisor": "2022.05.3",
    "host_os": "Home Assistant OS 8.1",
    "docker_version": "20.10.14",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "auto_backup": {
      "version": "1.0.1",
      "requirements": []
    },
    "abfallapi_regioit": {
      "version": "0.1.0",
      "requirements": []
    },
    "fullykiosk": {
      "version": "1.0.2",
      "requirements": [
        "python-fullykiosk==0.0.11"
      ]
    },
    "entity_controller": {
      "version": "9.2.10",
      "requirements": [
        "transitions==0.8.8"
      ]
    },
    "alexa_media": {
      "version": "4.0.2",
      "requirements": [
        "alexapy==1.26.0",
        "packaging>=20.3",
        "wrapt>=1.12.1"
      ]
    },
    "waste_collection_schedule": {
      "version": "1.21.0",
      "requirements": [
        "icalendar",
        "recurring_ical_events",
        "icalevents",
        "bs4"
      ]
    },
    "dwd_weather": {
      "version": "1.2.21",
      "requirements": [
        "simple_dwd_weatherforecast==1.1.5",
        "markdownify==0.6.5"
      ]
    },
    "watchman": {
      "version": "0.5.1",
      "requirements": [
        "prettytable==3.0.0"
      ]
    },
    "nodered": {
      "version": "1.0.8",
      "requirements": []
    },
    "hacs": {
      "version": "1.25.5",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "homematicip_local": {
      "version": "1.8.6",
      "requirements": [
        "hahomematic==1.8.6"
      ]
    }
  },
  "integration_manifest": {
    "domain": "homematicip_local",
    "name": "Homematic(IP) Local",
    "config_flow": true,
    "documentation": "https://github.com/danielperna84/custom_homematic",
    "issue_tracker": "https://github.com/danielperna84/hahomematic/issues",
    "requirements": [
      "hahomematic==1.8.6"
    ],
    "ssdp": [
      {
        "manufacturer": "EQ3",
        "manufacturerURL": "http://www.homematic.com"
      }
    ],
    "zeroconf": [],
    "homekit": {},
    "dependencies": [],
    "codeowners": [
      "@danielperna84",
      "@SukramJ"
    ],
    "iot_class": "local_push",
    "loggers": [
      "hahomematic"
    ],
    "version": "1.8.6",
    "is_built_in": false
  },
  "data": {
    "config": {
      "entry_id": "39f50709f308989f92fabbe75a94cf95",
      "version": 1,
      "domain": "homematicip_local",
      "title": "RaspberryMatic",
      "data": {
        "instance_name": "RaspberryMatic",
        "host": "192.168.178.201",
        "username": "**REDACTED**",
        "password": "**REDACTED**",
        "tls": false,
        "verify_tls": false,
        "callback_host": null,
        "callback_port": null,
        "json_port": null,
        "interface": {
          "HmIP-RF": {
            "port": 2010
          },
          "BidCos-RF": {
            "port": 2001
          }
        }
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": "unknown",
      "disabled_by": null
    },
    "platform_stats": {},
    "devices": []
  }
}

**Expected behavior**
I expected new HM devices to be found.

**Additional context**
--

**Comment by SukramJ** [comment]
`_create_clients: Interface: BidCos-RF is not available for backend.`
This indicates that something blocks the connection to your CCU.
Switch your firewall to `Firewall policy: ports open`

**Comment by lrswss** [comment]
Same issue here. I'm using HA 2022.6.7 (running as docker container) and  recent homematicip_local (1.9.0).

When I add the integration only the CCU (running RaspberryMatic 3.63.9.20220625 with HmIP-only devices) is found, no devices. No errors or warnings concerning this integration in home-assistant.log. It's not a firewall policy issue either (ports are open). I call successfully call a 'listDevices' on port 2010 returning an XML with device tree.

Removed and added integration several times, restarted HA...no change. I'm I missing something?

```
{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2022.6.7",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.9.12",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "5.10.92-v8+",
    "run_as_root": true
  },
  "custom_components": {
    "ferienapidotde": {
      "version": "0.2.3",
      "requirements": [
        "ferien-api==0.3.6"
      ]
    },
    "lockuser": {
      "version": "0.1.0",
      "requirements": []
    },
    "ics": {
      "version": "20211212.01",
      "requirements": [
        "recurring-ical-events",
        "icalendar>=4.0.4",
        "tzlocal",
        "integrationhelper",
        "voluptuous",
        "python-dateutil>2.7.3"
      ]
    },
    "webrtc": {
      "version": "v2.3.0",
      "requirements": []
    },
    "alexa_media": {
      "version": "4.0.3",
      "requirements": [
        "alexapy==1.26.1",
        "packaging>=20.3",
        "wrapt>=1.12.1"
      ]
    },
    "dwd_weather": {
      "version": "1.2.22",
      "requirements": [
        "simple_dwd_weatherforecast==1.1.5",
        "markdownify==0.6.5"
      ]
    },
    "homematicip_local": {
      "version": "1.9.0",
      "requirements": [
        "hahomematic==1.9.1"
      ]
    },
    "hacs": {
      "version": "1.22.0",
      "requirements": [
        "aiogithubapi>=21.11.0"
      ]
    },
    "bodymiscale": {
      "version": "1.1.3",
      "requirements": []
    },
    "yi_hack": {
      "version": "0.3.6",
      "requirements": []
    },
    "icloud3": {
      "version": "2.4.6",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "homematicip_local",
    "name": "Homematic(IP) Local",
    "config_flow": true,
    "documentation": "https://github.com/danielperna84/custom_homematic",
    "issue_tracker": "https://github.com/danielperna84/hahomematic/issues",
    "requirements": [
      "hahomematic==1.9.1"
    ],
    "ssdp": [
      {
        "manufacturer": "EQ3",
        "manufacturerURL": "http://www.homematic.com"
      }
    ],
    "zeroconf": [],
    "homekit": {},
    "dependencies": [],
    "codeowners": [
      "@danielperna84",
      "@SukramJ"
    ],
    "iot_class": "local_push",
    "loggers": [
      "hahomematic"
    ],
    "version": "1.9.0",
    "is_built_in": false
  },
  "data": {
    "config": {
      "entry_id": "505fadfdc55287bed4765d0dde420bd9",
      "version": 1,
      "domain": "homematicip_local",
      "title": "RaspberryMatic",
      "data": {
        "instance_name": "RaspberryMatic",
        "host": "192.168.10.252",
        "username": "**REDACTED**",
        "password": "**REDACTED**",
        "tls": false,
        "verify_tls": false,
        "callback_host": null,
        "callback_port": null,
        "json_port": null,
        "interface": {
          "HmIP-RF": {
            "port": 2010
          }
        }
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": "DD89A4850C",
      "disabled_by": null
    },
    "platform_stats": {},
    "devices": []
  }
}
```

**Comment by SukramJ** [comment]
> Same issue here.

Is not not helpful, if you do not provide any requested information from the issue template.

What is the network mode of your docker container?

**Comment by SukramJ** [comment]
> _create_clients: Interface: BidCos-RF is not available for backend.
_create_clients: Interface: HmIP-RF is not available for backend.

@Irswss
As long as you don't have this errors in the log you have another problem, and your assumptions about the firewall might be misleading.

So best would be to open a separate issue.

**Comment by lrswss** [comment]
Problem solved: added `network_mode: host` to docker-compose.yaml of my HA container to make callbacks from CCU to HA on arbitrary ports work. Also considered options for `callback hostname` and `callback xml-rpc port`, but switching the container to host mode to expose the ip address of the host machine to HA  seems a lot easier.

**Comment by SukramJ** [comment]
Can this be closed?
