### ISSUE TITLE
Enabled entities from system variables disappear again

### ISSUE THREAD

**Issue by buzo-ffm** [SukramJ/hahomematic#499]
DONT'T DELETE THIS.
Please answer all questions as good as possible.

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
1.8.6

**Home Assistant version (if applicable):**
2022.6.6

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, ...): Raspi3
- OS (Original, RaspberryMatic, debmatic/...): RaspberryMatic
- Version: 3.63.9.20220521

**Problem-relevant configuration:**

Do you use tls? yes
Do you use callback? no
Do you use username and password? yes
Which interfaces do you use? Homematic-IP, Bidcos-RF, groups

**Describe the bug**
Enabled entities from system variables disappear again.

**To Reproduce**
I'm trying to add system variables to HA [as described here](https://github.com/danielperna84/custom_homematic#system-variables). I have added the `hahm` marker to the description in the CCU. Then I try to enable the respective entities (`select`, `switch`) in HA. This works for a while, but theses entities disappear again later (marked as _disabled by Integration_).

These enabled entities get disabled again as soon as I enable another one. Then I enable the first one again, which disables the second one. And so on.

**Relevant HA log entries (full log)**
none

**Expected behavior**
Enabled entities stay enabled unless explicitly disabled again.

**Comment by buzo-ffm** [comment]
Additional Info: I have removed `hahm` from some system variables, and try to use (in these cases) `sensor` instead of `select`. Same effect: Enabling one (or more) entities disables all other previously enabled ones after a while (about 30 seconds).

**Comment by nobwyn** [comment]
I can also confirm the same behavior - enabling system-variable entity disables the previously enabled ones, so that **only** one system variable is visible at the time... (using component version 1.8.6)

**Comment by buzo-ffm** [comment]
Thanks laimoncijus. My current workaround is to enable one variable which I _don't_ need, and then enable all variables which I need at once. It helps to sort the table with the list of entities by status, which brings them all next to each other.

**Comment by SukramJ** [comment]
Thanks for reporting. It took a while to analyse.
Fixed by CC version 1.10.0 / requires HA 2022.7
