### ISSUE TITLE
HmIPW-DRD3 (Dimm Actors) aren't properly recognized

### ISSUE THREAD

**Issue by JulianPSLearner** [SukramJ/hahomematic#500]
DONT'T DELETE THIS.
Please answer all questions as good as possible.

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
1.8.6

**Home Assistant version (if applicable):**
2022.6.7

**CCU version:**
- Model (CCU3):
- OS (RaspberryMatic):
- Version: 3.63.9.20220625

**Problem-relevant configuration:**

Do you use tls? No
Do you use callback? No
Do you use username and password? Yes
Which interfaces do you use? WebInterface of HomeAssistant / CCU3

**Describe the bug**
It seems that Wired Dimmers (HmIP-DRD3) aren't properly recognized in Homematic Local INtegration.
I can find the Actor within Home Assistant as Devices. But the actual Sensors aren't entities. With all other Actors this works perfectly fine. Except Dimmers. I cannot see the actual value of the dimmer and I also cannot switch on/off a dimmer light / set any level.
See also this post in HomeMatic forum for further details: https://homematic-forum.de/forum/viewtopic.php?p=722788#p722788

**To Reproduce**
1. Go to HomeAssistant / devices
2. Click on Devices / Dimmer-Actor
3. There you see the sensors but not entities.

**Expected behavior**
I see all entities of a Dimmer and I can switch on/off channels or set dim-levels.

Screenshots:
https://homematic-forum.de/forum/download/file.php?id=98036&mode=view

**Comment by SukramJ** [comment]
This device should be supported.
Try this use service `Homematic(IP) Local: Delete a device` to delete this device from HA, and restart HA.

If this doesn't work do the following:
[Export device definition](https://github.com/danielperna84/custom_homematic#homematicip_localexport_device_definition) of your DRD3 and attach it here.

**Comment by JulianPSLearner** [comment]
How can I use the "delete a device" service? :/

**Comment by SukramJ** [comment]
Developer Tools --> Services

**Comment by JulianPSLearner** [comment]
I deleted the DRD3 devices with your services. Thanks for the help!
I then  restarted. They were found again. Still no entities :(

**Comment by JulianPSLearner** [comment]
I just created the files but I cannot open a pull request :/ Its grayed out :/

**Comment by SukramJ** [comment]
I started a virtual ccu with your device definitions and the the device is created as expected.
Have you tried to delete the integration and install/configure it again?
Anything in the logs?
Btw: Sensors are also entities.
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/5650106/177003025-895f18ab-6f6f-4630-871b-f08bb393c3f9.png">

**Comment by JulianPSLearner** [comment]
![TReanSQ2gT](https://user-images.githubusercontent.com/79222321/177015070-be4d65e7-0264-46b7-8a33-95b71cc8f836.png)
It looks like this :( I see the sensors, but I dont have switches or "Steuerelemente" :(

**Comment by SukramJ** [comment]
>I started a virtual ccu with your device definitions and the the device is created as expected.
Have you tried to delete the integration and install/configure it again?
Anything in the logs?

?

**Comment by JulianPSLearner** [comment]
The only error message in the logs related to HomeMatic. 

`Logger: homeassistant.setup
Source: setup.py:298
First occurred: 22:09:21 (4 occurrences)
Last logged: 22:09:21

Unable to prepare setup for platform homematicip_local.climate: Platform not found (cannot import name 'ClimateEntityFeature' from 'homeassistant.components.climate' (/usr/src/homeassistant/homeassistant/components/climate/__init__.py)).
Unable to prepare setup for platform homematicip_local.lock: Platform not found (cannot import name 'LockEntityFeature' from 'homeassistant.components.lock' (/usr/src/homeassistant/homeassistant/components/lock/__init__.py)).
Unable to prepare setup for platform homematicip_local.siren: Platform not found (cannot import name 'SirenEntityFeature' from 'homeassistant.components.siren' (/usr/src/homeassistant/homeassistant/components/siren/__init__.py)).
Unable to prepare setup for platform homematicip_local.light: Platform not found (cannot import name 'ColorMode' from 'homeassistant.components.light' (/usr/src/homeassistant/homeassistant/components/light/__init__.py)).`

**Comment by SukramJ** [comment]
You mentioned you use HA 2022.6.7, but this looks like your HA version is older than 2022.5 .

**Comment by SukramJ** [comment]
To precise my previous statement:
These logs indicate that there are no entities for climate, lock, siren and light created for your instance.
Update to the latest HA version, then the logs are gone and all entities are created.

**Comment by SukramJ** [comment]
Can this be closed?

**Comment by JulianPSLearner** [comment]
Ok, when I copied all the details from my HA I copied the "most recent version" and not the "current version". Thats the gap why my Logs seemed old. And they were! My HA was old and now I wasted your time because I was not able to properly install the most recent update. Sorry Sukram, that was just foolish. Thank you for spending that effort. I feel dumb for copied the wrong version :/

**Comment by JulianPSLearner** [comment]
By the way: After installing the recent update, everything worked fine.
