### ISSUE TITLE
themostat manual mode not implemented?

### ISSUE THREAD

**Issue by f-zappa** [SukramJ/hahomematic#502]
DONT'T DELETE THIS.

**Is your feature request related to a problem? Please describe.**
I have no idea how to change thermostat operating mode (eg from "auto" to "manual"). I guess it's not implemented. 

**Describe the solution you'd like**
I would have expected a
service: climate.set_hvac_mode
data:
  hvac_mode: 'off'
to not only set the target temperatur to "off" but also using the operating mode "manual" so that the device remains off.

**Describe alternatives you've considered**
Define a preset which can be used with "service: climate.set_preset_mode" for switching the thermostat "manual/off"

**Additional context**
I want to switch off my valves during summer when heating is shut down.

**Comment by SukramJ** [comment]
Manual mode is implemented, as you can see from the UI-cards.

In HA the manual mode is named `heat` [See](https://www.home-assistant.io/integrations/climate/#automation-example)

Presets are only relevant for `hvac_mode` `auto`

**Comment by SukramJ** [comment]
I guess this can be closed
