### ISSUE TITLE
FIO6 incomplete list of sensors

### ISSUE THREAD

**Issue by meks007** [SukramJ/hahomematic#503]
DONT'T DELETE THIS.
Please answer all questions as good as possible.

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
1.8.6

**Home Assistant version (if applicable):**
2022.6.7

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, ...): RaspberryMatic 3.63.9.20220625 (ova)
- OS (Original, RaspberryMatic, debmatic/...): 
- Version: 3.63.9.20220625 (ova)
- 
**Problem-relevant configuration:**

Do you use tls? No
Do you use callback? No
Do you use username and password? Yes
Which interfaces do you use? HmIP only

**Describe the bug**

FIO6 device does not include "Sender" channels as HA sensors
Sensors start from Channel 7; Channels 1 to 6 are not visible in HA - see below screenshots:

<img width="166" alt="image" src="https://user-images.githubusercontent.com/23148641/176316200-bc44bcba-9d8d-4f9b-8a9b-2006cf0b9ce1.png">

<img width="627" alt="image" src="https://user-images.githubusercontent.com/23148641/176316323-2802fccc-30f4-4bcc-8ad8-bdc98255b782.png">

**To Reproduce**

**Screenshots (if applicable)**
- CCU firewall
- integrations view
- device view
- enity view

**Relevant HA log entries (full log)**
```


```

**Diagnostic Information (available on every device)**
```


```

**Expected behavior**

**Additional context**

**Comment by danielperna84** [comment]
That's the way it should be I think. If those sender-channels are comparable to buttons, you should be able to select the channels when creating automations based on the device. Have a look if [this](https://github.com/danielperna84/custom_homematic#devices-with-buttons) get things going for you.

**Comment by meks007** [comment]
To be honest I'm not entirely sure that's correct. As for the FIO6 the first 6 channels are multi-purpose. They can be defined as either button, switch or contact. From my understanding a channel defined as contact should be a sensor in HA, but they don't show up at all.

<img width="555" alt="image" src="https://user-images.githubusercontent.com/23148641/176508324-d16243cb-2a99-4771-a60f-51f8523f6124.png">

This is how the CCU displays the first 6 FIO6 channels:
(Only 1 + 2 are used in my setup, that's why 3-6 don't show anything.)

<img width="609" alt="image" src="https://user-images.githubusercontent.com/23148641/176508853-5c17c9ec-26a9-4933-95e3-db7475688e3b.png">

**Comment by Baxxy13** [comment]
These channels are type of " MULTI_MODE_INPUT_TRANSMITTER". 
That means that they can send different events depending on how they configured in CCU-WebUI.
Configured as "button" they send PRESS_XXX events.
Configured as "contact" they send STATE true/false.

To identify what is configured we could read the value from "CHANNEL_OPERATION_MODE" in the master-paramset of the channel. 
I don't have FIO6 but a HmIP-MOD-RC8 which hast teoretically the same functions.

```
"CHANNEL_OPERATION_MODE"
mode      |   value
inactive  |      0
key       |      1
switch    |      2
contact   |      3
```      
Real HmIP-"Buttons" can't be pressed from CCU or every other software mechanism. 
That just works only for virtual or old HM-Buttons.

**Comment by SukramJ** [comment]
To get a better insight to your device:
[Export device definition](https://github.com/danielperna84/custom_homematic#homematicip_localexport_device_definition) of your FIO6 and attach it here.

**Comment by SukramJ** [comment]
There is a custom device handling for FIO6, but maybe this should be removed due to the multipurpose nature of FIO6,
so dealing with CHANNEL_OPERATION_MODE should not be necessary.

**Comment by SukramJ** [comment]
1.9.0 removes the custom device handling.
After the update use the service `Homematic(IP) Local: Delete a device` to delete this device from HA. After the restart the device shows more entities.

**Comment by meks007** [comment]
it's working now! perfect, thank you! :)
