### ISSUE TITLE
custom_homematic not listed at Integration

### ISSUE THREAD

**Issue by LuckyTurtleDev** [SukramJ/hahomematic#505]
**custom_component/hahomematic version (if applicable):**
null

**Home Assistant version (if applicable):**
2022.6.7 (docker)

**CCU version:**
- Model Raspi Zero:
- OS RaspberryMatic:
- Version: 

**Problem-relevant configuration:**

* clear/new HomeAssistant instalation

* `docker-compose.yml`:
```yml
version: '3'
services:
  homeassistant:
    container_name: HomeAssistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./data:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: host
```

**Describe the bug**
I have follow this instructions https://github.com/danielperna84/custom_homematic#manual-configuration-steps.
But the custom_homematic Integration is not listen at "add Integration".
![image](https://user-images.githubusercontent.com/44570204/176537182-afb90e3f-571e-4e50-8a6b-8358524312a0.png)

**To Reproduce**
1. install docker and docker-compose
2. execute `mkdir data` (stay at the same directory)
3. copy the `docker-compose.yml` from above to the current working directory.
4. start docker (`sudo systemctl start docker`)
5. execute `sudo docker-compose up`
6. open the webinterface of homeassistant
7. follow the setup assistant
8. In the sidebar click on [Configuration](https://my.home-assistant.io/redirect/config)
9. From the configuration menu select: [Integrations](https://my.home-assistant.io/redirect/integrations)
10. In the bottom right, click on the [Add Integration](https://my.home-assistant.io/redirect/config_flow_start?domain=homematicip_local) button.

**Screenshots (if applicable)**
- CCU firewall
- integrations view
- device view
- enity view

**Relevant HA log entries (full log)**
not really relevant logs:
```
Starting homeassistant ... done
Attaching to homeassistant
homeassistant    | s6-rc: info: service s6rc-oneshot-runner: starting
homeassistant    | s6-rc: info: service s6rc-oneshot-runner successfully started
homeassistant    | s6-rc: info: service fix-attrs: starting
homeassistant    | s6-rc: info: service fix-attrs successfully started
homeassistant    | s6-rc: info: service legacy-cont-init: starting
homeassistant    | s6-rc: info: service legacy-cont-init successfully started
homeassistant    | s6-rc: info: service legacy-services: starting
homeassistant    | services-up: info: copying legacy longrun home-assistant (no readiness notification)
homeassistant    | s6-rc: info: service legacy-services successfully started
```

**Expected behavior**
I  would expect that the integration will be shown. 

**Additional context**
If I open this link [Add Integration](https://my.home-assistant.io/redirect/config_flow_start?domain=homematicip_local) , I get an error message witch says, that the integration does not support configuration at the gui.
![image](https://user-images.githubusercontent.com/44570204/176540669-55778820-28f1-4eab-888f-36a0edb4a436.png)

**Comment by SukramJ** [comment]
It's a custom_integration and not part of HA!
Follow [installation instructions](https://github.com/danielperna84/custom_homematic/wiki/Installation).

**Comment by LuckyTurtleDev** [comment]
Thank
Because it was was not mention at the readme i had expect it is part of HA.

Exist a reason, why it is not part of HA?

**Comment by SukramJ** [comment]
Installation is part of the first paragraph.

No.
