### ISSUE TITLE
CUxD devices (HM-Sec-SC) are not visible in HA

### ISSUE THREAD

**Issue by lrswss** [SukramJ/hahomematic#512]
DONT'T DELETE THIS.
Please answer all questions as good as possible.

**custom_component/hahomematic version:**
1.9.4

**Home Assistant version:**
2022.6.7 (running as docker container in host-mode)

**CCU version:**
- Model: Raspi2B with HM-MOD-RPI-PCB
- OS: RaspberryMatic
- Version: 3.63.9.20220625

**Problem-relevant configuration:**
Do you use tls? no
Do you use callback? no
Do you use username and password? yes
Which interfaces do you use? HmIP 2010

**Describe the bug**
Devices (window shutter contacts) which are connected to RaspberryMatic using the CUxD addon do not show up as devices in HA. The CUxD addon maps the original devices (FHT80-TF-2) to HM-Sec-SC. All other devices (HmIP-eTRV-2, HmIP-eTRV-B, HMIP-SWDO) are shown in HA. I tried adding Port 2001 for HM-RF, but it didn't make difference.

**Screenshots (if applicable)**

<img width="1126" alt="cux_fensterkontakt" src="https://user-images.githubusercontent.com/33193763/177180487-cb772bdc-7317-470c-953a-94d2f34f847b.png">

**Expected behavior**
HM-Sec-SC devices and their entities should also be available in HA.

**Additional context**
Add any other context about tI he problem here.

```
{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2022.6.7",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.9.12",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "5.10.92-v8+",
    "run_as_root": true
  },
  "custom_components": {
    "alexa_media": {
      "version": "4.0.3",
      "requirements": [
        "alexapy==1.26.1",
        "packaging>=20.3",
        "wrapt>=1.12.1"
      ]
    },
    "dwd_weather": {
      "version": "1.2.22",
      "requirements": [
        "simple_dwd_weatherforecast==1.1.5",
        "markdownify==0.6.5"
      ]
    },
    "homematicip_local": {
      "version": "1.9.4",
      "requirements": [
        "hahomematic==1.9.4"
      ]
    },
    "hacs": {
      "version": "1.25.5",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
  },
  "integration_manifest": {
    "domain": "homematicip_local",
    "name": "Homematic(IP) Local",
    "config_flow": true,
    "documentation": "https://github.com/danielperna84/custom_homematic",
    "issue_tracker": "https://github.com/danielperna84/hahomematic/issues",
    "requirements": [
      "hahomematic==1.9.4"
    ],
    "ssdp": [
      {
        "manufacturer": "EQ3",
        "manufacturerURL": "http://www.homematic.com"
      }
    ],
    "zeroconf": [],
    "homekit": {},
    "dependencies": [],
    "codeowners": [
      "@danielperna84",
      "@SukramJ"
    ],
    "iot_class": "local_push",
    "loggers": [
      "hahomematic"
    ],
    "version": "1.9.4",
    "is_built_in": false
  },
  "data": {
    "config": {
      "entry_id": "c8714d7e795aa13753d69e35bbe73ec6",
      "version": 1,
      "domain": "homematicip_local",
      "title": "RaspberryMatic",
      "data": {
        "instance_name": "RaspberryMatic",
        "host": "192.168.10.252",
        "username": "**REDACTED**",
        "password": "**REDACTED**",
        "tls": false,
        "verify_tls": false,
        "callback_host": null,
        "callback_port": null,
        "json_port": null,
        "interface": {
          "HmIP-RF": {
            "port": 2010
          },
          "VirtualDevices": {
            "port": 9292,
            "path": "/groups"
          }
        }
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "ssdp",
      "unique_id": "DD89A4850C",
      "disabled_by": null
    },
    "platform_stats": {
      "binary_sensor": 12,
      "climate": 6
    },
    "devices": [
      "HMIP-SWDO",
      "HmIP-eTRV-2",
      "HmIP-eTRV-B"
    ]
  }
}
```

**Comment by SukramJ** [comment]
CUxD (port 8701) is not supported by this integration like it was in the old integration.
CUxD uses BinRPC as the communication protocol, which is not supported by any known Python library.

**Comment by lrswss** [comment]
OK, then it was a misunderstanding on my part. I thought that all devices visible in RaspberryMatic can be mapped in HA with hahomematic. Digging a little deeper on this I ran across a [thread from 2018](https://community.home-assistant.io/t/homematic-component-does-not-show-cuxd-devices/85145/19) that explains in depth why CUxD devices are out of scope for this integration and will probably always be. Well, I guess I'll have to use Redmatic to send the status of the shutter contacts to HA via MQTT.
