### ISSUE TITLE
Blueprints do not intuitively support HM-PBI-4FM

### ISSUE THREAD

**Issue by andyboeh** [SukramJ/hahomematic#513]
DONT'T DELETE THIS.
Please answer all questions as good as possible.

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
1.9.4

**Home Assistant version (if applicable):**
2022.6.4

**CCU version:**
- Homegear

**Problem-relevant configuration:**

Do you use tls? no
Do you use callback? yes
Do you use username and password? no
Which interfaces do you use? RF

**Describe the bug**
The blueprints for the 4-button remote (wrongly labelled "3 button" on the website) are not very intuitive for the HM-PBI-4FM, since buttons 1/2 and 3/4 are swapped. This makes perfect sense for the non-flushmount devices, but it took me a while to debug why my automation for the one connected button does not trigger.

**To Reproduce**
N/A

**Screenshots (if applicable)**
N/A

**Relevant HA log entries (full log)**
N/A

**Diagnostic Information (available on every device)**
N/A

**Expected behavior**
Maybe a separate blueprint for the HM-PBI-4FM and similar devices would make sense that just have the buttons labelled in numeric order?

**Additional context**

**Comment by SukramJ** [comment]
I added these blueprints as i use them with my hmip devices.
I can update the docs, but i will not further investigate in these blueprints. Please feel free to tryout different options.
If you have an improved version we could add it to the repo.

**Comment by andyboeh** [comment]
Actually, I would add an additional blueprint with numbered buttons instead of labelled ones. I will try to come up with a PR on the weekend.

**Comment by SukramJ** [comment]
Sounds good.
I think this issue is no longer required.

**Comment by SukramJ** [comment]
Please use folder blueprints/community

**Comment by andyboeh** [comment]
For the sake of completeness: This has been added in https://github.com/danielperna84/custom_homematic/pull/265.
