### ISSUE TITLE
HM-ES-PMSw1-Pl state wrong after CCU reboot

### ISSUE THREAD

**Issue by ThomDietrich** [SukramJ/hahomematic#516]
DONT'T DELETE THIS.
Please answer all questions as good as possible.

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
1.10.0

**Home Assistant version (if applicable):**
2022.7.0

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, ...): Raspi 3
- OS (Original, RaspberryMatic, debmatic/...): RaspberryMatic
- Version: 3.63.9.20220625

**Problem-relevant configuration:**

Do you use tls?
Do you use callback?
Do you use username and password?
Which interfaces do you use?

**Describe the bug**

Hello there! 
When I restart my "CCU", more specifically my RaspberryMatic RPi3, all HM-ES-PMSw1-Pl in my Home are shown as Off, even though they are physically turned On. 

![image](https://user-images.githubusercontent.com/2870104/177729765-63764da0-efec-4b4d-a883-c17e764b1964.png)

I can confirm that the device is turned On on the CCU device status webpage:

![image](https://user-images.githubusercontent.com/2870104/177730112-02428302-a9d0-4e80-ac7c-6e9f350decbc.png)

Here is the strange part: Accessing this page (without any further action) also triggers the update of known state in Home Assistant:

![image](https://user-images.githubusercontent.com/2870104/177730333-b37d8ca6-2751-4c23-83d6-e8114eb2293a.png)

This might also be the cause for other issues. Would be great if you could look into this!! Thanks

**To Reproduce**
1. Turn On a HM-ES-PMSw1-Pl
2. Reboot the CCU
3. Check the device state as described above

**Screenshots (if applicable)**
- see above

**Relevant HA log entries (full log)**
```


```

**Diagnostic Information (available on every device)**
```


```

**Expected behavior**
Correct state at every given point.

**Additional context**
.

**Comment by SukramJ** [comment]
It takes a while (minutes/hours) after a CCU reboot until the devices reported the correct state to the CCU.
Afterward these updates are send to HA as events.

I think there is no issue with this integration

**Comment by ThomDietrich** [comment]
Thanks for the quick response!

I have one device left with the wrong state, let me see how long it takes to recover.

Disagree, if we must assume that the state shown after reboot is not correct (the device was never Off) I would expect the integration to (1) show state as `unknown` and (2) ideally actively query the CCU for the right state.

I have automations triggering on e.g. the HM-ES-PMSw1-Pl being turned off. Imagine the issues that could arise from this...

**Comment by SukramJ** [comment]
@baxxy13 any idea?

**Comment by SukramJ** [comment]
> Disagree, if we must assume that the state shown after reboot is not correct (the device was never Off) I would expect the integration to (1) show state as unknown and (2) ideally actively query the CCU for the right state.

How could we assume that the state (in HA/ in CCU) is not correct?

**Comment by SukramJ** [comment]
What we do so far.:

After start or reconnect:
1. Load all values from CCU (nur Start)
2. Register on there interfaces so that we get updates from the CCU

I don't see the point how to identify an "incorrect" state.

**Comment by Baxxy13** [comment]
Das Problem wird sein das nach einem Zentralenstart jeder "Sensorwert" ein Default-Wert ist. 
Schaltaktoren = Aus, TFK"s = geschlossen, Temperaturen = 0.0°C usw. 
Reconnected die Integration bevor ein Sensor zyklisch was gemeldet hat, wird dieser Default-Wert eben ausgelesen und genommen denn die aktive Abfrage der Geräte wurde ja wegen den damaligen DC Anstiegen umgestellt auf Abfrage lokaler Werte. 

Das Problem an sich gibt es schon immer auf der Zentrale, je nach Intervall der zykl. Meldungen kann es schon mal Stunden dauern bis der Status eines Gerätes korrekt ist.

Was könnte man tun... 
M.E. der einzige Anhaltspunkt ob es ein Default-Wert oder ein korrekter Wert ist liegt im Zeitstempel des Datenpunktes. Wenn ich das richtig in Erinnerung habe steht der bei Default-Werten auf 01.01.1970 oder so.

Ich gucke mir das später mal auf einem Testsystem an.

**Comment by SukramJ** [comment]
[fetch_all_device_data.fn](https://github.com/danielperna84/hahomematic/blob/devel/hahomematic/rega_scripts/fetch_all_device_data.fn) liefert ja nur Werte für DPs wo der Timestamp > 0 ist.
Aufgrund von #328 wird dann, für alles was aus dem Paramset VALUES ist, auf ein weiters Laden per getValue() verzichtet.

**Comment by Baxxy13** [comment]
Ja, hobbyquaker hatte da beim erstellen des Scriptes mitgedacht. Schade das er "verschwunden" ist.

Zurück zum Thema:
Hatte jetzt eine PMSw1-PL EINgeschaltet (korrekter Status in HA) und anschließend den Pi3B+ mit RM über dessen WebUI neu gestartet.
In HA wechselte alles auf "nicht verfügbar" (bzw. ausgegraut) und etwa 1min nachdem die Zentrale wieder "oben" war wechselte der Status korrekt auf (bzw. zurück zu) EIN.
Das habe ich jetzt 3x durchgeführt mit immer dem selben korrekten Ergebnis.

Von daher kann ich die Problematik aktuell nicht nachvollziehen.

**Comment by ThomDietrich** [comment]
Du has Recht. Konnte ich so bestätigen. Das habe ich oben falsch erfasst.

Zum reproduzieren:
1. Raspi aus
2. Home Assistant restart
3. Raspi ein
4. Status zeigt PMSw1-PL AUS

**Comment by SukramJ** [comment]
Wie ist der Stand in dem Issue.
Gibt es hier noch ein Todo?

**Comment by ThomDietrich** [comment]
Meiner Meinung nach ja. Das Problem wurde noch nicht gelöst.

> Das Problem wird sein das nach einem Zentralenstart jeder "Sensorwert" ein Default-Wert ist.

@Baxxy13 das erklärt das Fehlverhalten.
- Du hattest von einem Zeitstempel von epoch=0 gesprochen. Das klingt doch nach einem guten Anhaltspunkt um den Sensor in HA vorerst als `unknown` zu markieren.
- Darüber hinaus: Wenn ich in der CCU UI den Status des Geräts betrachte (siehe Screenshot oben) wird der korrekte Status abgefragt und in CCU und HA aktualisiert - wäre es sinnvoll ein solches force-update für alle Datenpunkte mit Zeitstempel 01.01.1970 auszulösen? (Ich verstehe dass das zu flooding Effekten führen kann)

**Comment by SukramJ** [comment]
Der Default-Wert wir nur bei Binärsensoren verwendet. Warum auch nicht?

Die initiale Datenabfrage lädt nur Werte die eine timestamp > 0 haben.
Was soll es also bringen danach per get_value eine Abfrage hinterherzuschicken, die mir den gleichen liefert, und nur den DutyCycle hochtreibt?

Was immer in der UI zu sehen ist interessiert mich nicht, weil dabei immer noch caching Effekte auftreten können.
Für mich ist nur relevant, ob der Wert per API abrufbar ist, also mit dem Homematic Manager.

**Comment by SukramJ** [comment]
> Der Default-Wert wir nur bei Binärsensoren verwendet. Warum auch nicht?

Das macht die UI auch.

**Comment by ThomDietrich** [comment]
Verstehe deine Antwort nicht ganz. Fakt ist dass ich hier einen reproduzierbaren und in der Praxis nicht unwahrscheinlichen Fehlerfall gemeldet habe. Sollten wir nicht versuchen dafür eine Lösung zu finden?

**Comment by Baxxy13** [comment]
Man muss auch wissen das man die "echten Werte" der Geräte nicht bei batteriebetriebenen Geräten aktiv abfragen kann. 
So ein "force-update" würde also für TFK's usw. gar nichts bringen. 

Außerdem bräuchte man in HA "Trinärsensoren". Die zusätzlich zu 1/0 oder true/false noch ein undefined haben. Dann könnte man diese bei Zeitstempel "0" erstmal auf undefined setzen bis ein echter Wert eintrifft. 

Summa summarum für mich kein Problem der Integration sondern ein altbekanntes der CCU. Nicht umsonst nutzen so viele den bekannten "CCU im Reboot-Workaround".

**Comment by SukramJ** [comment]
> Außerdem bräuchte man in HA "Trinärsensoren". Die zusätzlich zu 1/0 oder true/false noch ein undefined haben. Dann könnte man diese bei Zeitstempel "0" erstmal auf undefined setzen bis ein echter Wert eintrifft.

Das würde in HA schon gehen, da würde dann `unknown` angezeigt.
Gegenargument: Auch wenn ich das heranziehen der UI nicht mag: TFKs mit unbekannten Werten werden in der UI mit default-Wert angezeigt. Wenn ich das richtig beobachtet habe werden auch Schalter (Strombetrieben) als `aus` angezeigt, solange kein Wert vorliegt.

**Comment by ThomDietrich** [comment]
> Wenn ich das richtig beobachtet habe werden auch Schalter (Strombetrieben) als aus angezeigt, solange kein Wert vorliegt.

Tatsächlich werden diese in der CCU UI und in Folge auch in HA bei Aufruf aktiv aktualisiert (daher mein Gedanke eines "force-update").

> Man muss auch wissen das man die "echten Werte" der Geräte nicht bei batteriebetriebenen Geräten aktiv abfragen kann.

Meiner Meinung nach ist das auch gar nicht dringend erforderlich. Ich sähe das Problem als gelöst an, wenn bei Zeitstempel "0" die Home Assistant Entity auf `undefined` gesetzt würde, bis ein echter Wert eintrifft.

---

Am Rande:
@Baxxy13 HA hat durchaus sowas wie ein "Trinärsensor". Ein binärer Schalter hat tatsächlich vier etablierte Zustände: logisch 1, logisch 0, `unknown` und `unavailable`. Unavailable ist der Sensor wenn die Verbindung zur CCU nicht besteht. Unknown wird von anderen HA Integrationen typischerweise verwendet, wenn für eine Entität trotz verfügbarem Gerät der Zustand aktuell unbekannt ist.

**Comment by Baxxy13** [comment]
> TFKs mit unbekannten Werten werden in der UI mit default-Wert angezeigt. Wenn ich das richtig beobachtet habe werden auch Schalter (Strombetrieben) als `aus` angezeigt, solange kein Wert vorliegt.

Korrekt. Genau genommen hat wirklich alles nach dem Zentralenstart einen Default-Wert. Das fällt bei HM meist nicht so auf weil die Geräte teilweise ein kurzes zyklisches Senderaster haben. Dazu kommt das beim anwählen über Status und Bedienung --> Geräte von HM (Strom) Geräten diese aktiv abgefragt werden. Bei IP Geräten passiert das m.W. nicht. 
Daher wäre m.E. ein "force-update" auch nicht sinnvoll da dieses bei "force-update-all" eh nicht alle Geräte erreicht. Wenn dann müsste das selektiv erfolgen was aber wiederum ne Menge Pflegeaufwand bedeutet.

> Meiner Meinung nach ist das auch gar nicht dringend erforderlich. Ich sähe das Problem als gelöst an, wenn bei Zeitstempel "0" die Home Assistant Entity auf `undefined` gesetzt würde, bis ein echter Wert eintrifft.

Da gehe ich mit. 
Das wäre ein großer Fortschritt gegenüber der WebUI da diese nicht in der Lage ist undefinierte Zustände anzuzeigen. 

Ich umgehe das Problem z.B. für TFK's indem deren Stati über Wertelisten-SysVars abgebildet werden. Nach einem Reboot setzt ein simples Programm alle auf "undefiniert", nach der ersten zykl. Meldung bzw. echter Bewegung wird die SysVar dann mit dem korrekten Status synchronisiert.

> Am Rande:

Ich bin ja eher der WebUI-Insider. Bei HA kratze ich aktuell nur an der Oberfläche. Danke für die Erklärung zum Binärsensor.

**Comment by SukramJ** [comment]
Force update ist denke ich vom Tisch. Sehr gut.

Anzeige von `undefined`:
Kann man machen.
Aber:
Wer von Euch möchte normalen Benutzern jedes mal erklären warum der Wert der Web UI nicht mit HA übereinstimmt?
Doku? Kann man machen. Liest leider niemand.
Ist es akzeptabel, das Entitäten über Stunden und Tage (HmIP-SWD) den Status `undefined` haben?
Bei Zigbee ist das kein Problem, da gibt es innerhalb von Sekunden/Minuten ein Update.

Alternative:
Jede Entität enthält ein Attribut dem zu entnehmen ist, ob der dargestellt Wert valide ist oder nicht.

**Comment by ThomDietrich** [comment]
Wir dürfen nicht vergessen, dass Home Assistant einen Recorder/Cache hat. In vielen Fällen wird HA nach einem CCU reboot auch nach der hier diskutierten Verbesserung einen Wert anzeigen, siehe https://github.com/danielperna84/hahomematic/issues/516#issuecomment-1178040594
(Achtung: Ja! Dieser Wert könnte ebenso falsch sein, allerdings ist das ein weiterer Sonderfall der hier den Rahmen sprengen würde)

> über Stunden und Tage (HmIP-SWD) den Status `unknown` haben

Das klingt durchaus nach einem Ärgernis, Allerdings (!) solang der in WebUI dargestellte Wert ein default Wert ist, ist die daraus resultierende Gefahr einer Fehlinformation mMn eine Verfehlung von HM. Wir wollen doch sicher die "Qualität" der hahomematic custom component nicht mit der von HM deckeln :)

> Das wäre ein großer Fortschritt gegenüber der WebUI da diese nicht in der Lage ist undefinierte Zustände anzuzeigen.

💪

**Comment by Baxxy13** [comment]
Ich wäre tatsächlich auch eher dafür den "Undefiniert-Status" anzuzeigen solange kein korrekter Wert übermittelt wurde.
Auch wenn das mal länger dauert.
Zumindest finde ich das besser als einen Status anzuzeigen der möglicherweise nicht der Realität entspricht (wie in der WebUI).

> Jede Entität enthält ein Attribut dem zu entnehmen ist, ob der dargestellt Wert valide ist oder nicht.

Klingt jetzt auch erstmal gut, nur kann ich mir das aktuell nicht so recht vorstellen wie das dann in HA "aussieht".

Deine Gegenargumente sind natürlich nicht von der Hand zu weisen. 
Vielleicht mal im Diskussionsteil oder im Homematic-Forum eine Umfrage starten?

**Comment by SukramJ** [comment]
> Vielleicht mal im Diskussionsteil oder im Homematic-Forum eine Umfrage starten?

Hört sich für mich sehr sinnvoll an.
Also bitte sei so freundlich und starte eine Diskussion.

**Comment by Baxxy13** [comment]
Ich habe das als Umfrage im Homematic-Forum umgesetzt... schauen wir mal. 
[Homeassistant / Homematic(IP) Local - Umfrage zu möglicher Verbesserung](https://homematic-forum.de/forum/viewtopic.php?f=84&t=74780)

**Comment by SukramJ** [comment]
Ich hab mal eine neue Beta [(1.11.beta4)](https://github.com/danielperna84/custom_homematic/releases/tag/1.11.beta4 ) erstellt.
Die wesentlichen Änderungen hab ich in den Release Notes aufgeführt.
Bitte schaut Euch das mal an.

**Comment by Baxxy13** [comment]
So, nun konnte ich das mal etwas genauer unter die Lupe nehmen.
So richtig klappt das noch nicht. Es wird vieles für sehr lange Zeit als "unknown" angezeigt obwohl die Geräte inzwischen eine oder mehrere Statusmeldungen von sich gaben.

So habe ich z.B. einen Temperatursensor der alle 5min seine Daten sendet. 
Die Temperatur war aber so stabil das immer das Gleiche gesendet wurde. Erst als sich die Temperatur änderte, wechselte der Status von "unknown" zur korrekten Temperatur.

Gibt's da was in HA das sowas nur "bei Änderung" aktualisiert wird? 
Das wäre schlecht, denn dann würden diverse Geräte (z.B. Fensterkontakt real dauerhaft geschlossen, sendet aber alle 1,5h seinen Status) erst den "unknown"-Status verlieren wenn der Status sich geändert hat. 

Es scheint auch abhängig zu sein von "wann was gestartet wird", also Zentrale/HA. 
Da ich die letzten Tage auf Proxmox umgezogen bin wurde seitdem immer erst die Zentrale und 2min später HA gestartet.
Ich glaube hier tritt es am ehesten auf da zu diesem Zeitpunkt viele Daten noch als "Default-Werte" vorliegen.

**Comment by SukramJ** [comment]
> Gibt's da was in HA das sowas nur "bei Änderung" aktualisiert wird?

Ja, muss mir in dem Kontext noch mal anschauen.
Initial sind alle Werte None, also sollte jedes Event eine Änderung auslösen.

Was passiert nach einem kompletten Neustart (HA(CCU)?
Was passiert nach einem CCU Neustart?
Um was für Entitäten handelt es sich (custom/generic)? Sieht man in den Attributen der Entität.

**Comment by SukramJ** [comment]
Was für Geräte verwendest Du fürs Testen?

**Comment by Baxxy13** [comment]
Testkandidaten:
Nr. 1 ist ein HM-Sec-SCo, der ist aktuell dauerhaft geschlossen, sendet aber laut Timestamps ca. alle Stunde seinen Status. 
Nr. 2 ist eine HmIP-PCBS2, komplett aus, mit Statusmeldungen 0/0, meldet sich ca. alle 3min
Nr. 3 ein Selbstbausensor HB-UNI-SENxxx, sendet alle 5min "variable Werte"
```json
state_class: measurement
interface_id: RM-Live-OVA-26-BidCos-RF
address: UNISENS002:1
model: HB-UNI-Sensor1
function: Klima,Batterieversorgt
parameter: TEMPERATURE
entity_type: generic
state_uncertain: false
unit_of_measurement: °C
device_class: temperature
friendly_name: Klima Sensor Device FL: UNISENS002 Klima Sensor FL: UNISENS002:1 - Klimadaten Temperature
```
Die beobachte ich jetzt mal nach folgender Prozedur:

- HA komplett herunterfahren
- Zentrale neu starten
- HA 2min später starten

**Comment by Baxxy13** [comment]
So richtig kann ich kein klares Muster erkennen...
Mein UNI-Sensor z.B. sendet ja alle Werte im 5min Raster.
Tja und genau der Wert der aktuell unverändert bleibt wird als "unbekannt" angezeigt.
![HA_Unisensor_Test](https://user-images.githubusercontent.com/54898249/178825322-ba1a7b05-da15-489c-bab1-dac1ff3c19b2.jpg)
Ich werde mal die Luftfeuchte künstlich erhöhen...

**Comment by SukramJ** [comment]
Ich glaube das erste Event (Änderung None --> 4.0) wird verschluckt.
Die Events ohne Wertänderungen haben dann kein Update mehr ausgelöst.

**Comment by Baxxy13** [comment]
Hmm, klingt erstmal plausibel.
Der Sensor zeigt nun die Luftfeuchte an nachdem der Wert sich änderte.
Hier ist aber noch einiges "unbekannt", z.B. eine PMSw1-PL die die ganze Zeit real "AUS" ist. Selbst wenn ich sie in der WebUI anwähle (und damit den Status abfrage) bleibt die unbekannt.
HM-CC-RT-DN - BATTERY_STATE und VALVE_STATE werden alle 3min unverändert gesendet und sind damit "unbekannt". 

Ich lasse das jetzt mal so laufen und gucke dann morgen wie es aussieht.

**Comment by SukramJ** [comment]
Version 1.11.1 sollte das Problem beheben.

**Comment by SukramJ** [comment]
Meine HmIP-Geräte scheinen alle gut zu funktionieren, aber ich hab noch ein Problem mit einem HM-LC-Sw4-DR:
Nach einem Neustart von CCU und HA hat das `fetch_all_device_data` Script noch keine Werte, aber sehr kurz nach dem Start kommen schon Updates für den `STATE`.
Nach einiger Zeit kann man in der CCU/HomematicManager Werte für RSSI_PEER, RSSI_DEVICE sehen, aber es werden keine Events an HA gesendet, so das der Wert dort nicht aktualisiert wird.
Ich kann auch nicht im HomematicManager sehen das Events gesendet wurden.

Irgendeine Idee?

**Comment by ThomDietrich** [comment]
Bei diesen tiefen HM Themen kann ich wohl nicht viel beitragen.

Nur kurz als Meldung meinerseits:
Es scheint alles zu funktionieren. Entitätenstati werden aktualisiert (1), als unknown dargestellt (2) und vom Home Assistant Cache widerhergestellt (3).

![image](https://user-images.githubusercontent.com/2870104/178944325-05df992a-fb11-498b-8864-9c1c4ebbea31.png)


Ich bin skeptisch ob `state_uncertain` einen Mehrwert bietet. Prinzipiell wäre ich dafür die [Doppelnegierung](https://davej.io/2018/05/negative-naming.html) zu lösen. Darüber hinaus liefert die Kombination aus Entity Status `unknown` und `state_uncertain: true` kaum einen Mehrwert. Ich wäre also entweder dafür das Attribut wegzulassen, oder aber einen Schritt weiter zu gehen: `state_unkown_reason: waiting_for_event` oä...

**Comment by Baxxy13** [comment]
> Irgendeine Idee?

Ich kann das was du beobachtet hast hier soweit bestätigen. Für IP funktioniert das bestens, bei HM hakelt es bei manchen Geräten. Das gucke ich mir später mal genauer an. 
Eine erste Idee habe ich auch, die wird dir aber vermutlich nicht gefallen. `fetch_all_device_data` entweder zyklisch aufrufen oder zumindest ein zweites mal eine definierte Zeit nach HA Start.

**Comment by SukramJ** [comment]
[Script_fetch_all](https://github.com/danielperna84/hahomematic/blob/devel/hahomematic/rega_scripts/fetch_all_device_data.fn)
[Script_fetch_all_ext](https://gist.github.com/SukramJ/46d8f9d10a1a6a7b7f3bcba82b8c1142) ohne Timstamp Filter mit Timestamp Anzeige

Weiter Beobachtungen:

Variante 1:
- CCU Neustart
- HA Neustart
- Gerät zeigt kein RSSI an.
- sofort ausführen von `Script_fetch_all` zeigt kein RSSI an
- sofort ausführen von `Script_fetch_all_ext` zeigt RSSI mit default Wert und "jetzt" als Timestamp an.
- irgendwann: Gerät zeigt RSSI an!
- Scripte zeigen RSSI-Wert nicht an (nur default).

Variante 2:
- CCU Neustart
- HA Neustart
- warten
- Gerät zeigt RSSI an.
- `Script_fetch_all` zeigt kein RSSI an
- `Script_fetch_all_ext` zeigt RSSI mit Wert und "jetzt" als Timestamp an.
- nochmaliges ausführen von `Script_fetch_all` zeigt RSSI an.

Script_fetch_all_ext scheint ein Einlesen von Werten zu erzwingen (die Scriptausführung dauert initial länger).
Vermutung: Ein wiederholte Ausführung scheint auf ge-cachte Werte zuzugreifen.

**Comment by Baxxy13** [comment]
Gute Analyse!

Ich habe hier ein Testsystem mit einem HM-Sen-MDIR-WM55 aufgesetzt. 
Das Teil liegt im Schrank damit er "nichts zu melden hat". 
Die Integration ist erstmal nicht angebunden um "Seiteneffekte" zu vermeiden.
Beobachtet wird "LOWBAT" in Kanal:0 und "MOTION" in Kanal:3
Zusätzlich ist noch eine HM-LC-Sw4-Ba-PCB angelernt.

Was ich bisher sagen kann:
Die Zeitstempel aller Datenpunkte für den HM-Sen-MDIR-WM55 werden augenscheinlich auf die "Zentralen-Startzeit" gesetzt.
Ob es aktiv abgefragt wird (obwohl es ein Batteriegerät ist) kann ich aktuell nicht sagen.
Die Zeitstempel aller Datenpunkte für die HM-LC-Sw4-Ba-PCB sind nach Zentralenstart "default".

Frage ich beide Geräte über ein Script in der WebUI ab ergibt sich erstmal folgendes:
```
MDIR MOTION Timestamp: 2022-07-14 17:20:56 | LOWBAT Timestamp: 2022-07-14 17:20:56
Sw4-Ba-PCB STATE Timestamp: 1970-01-01 01:00:00 | LOWBAT Timestamp: 1970-01-01 01:00:00
```

Zusätzlich habe ich ein Programm ohne Bedingungen laufen was mit die "Zentralen-Startzeit" in eine SysVar schreibt:
`Systemstart: 2022-07-14 17:20:56`

Nutze ich dann das von die modifizierte `Script_fetch_all_ext` und danach nochmal mein Auslese-Test-Script...
```
MDIR MOTION Timestamp: 2022-07-14 17:20:56 | LOWBAT Timestamp: 2022-07-14 17:20:56
Sw4-Ba-PCB STATE Timestamp: 2022-07-14 17:27:37 | LOWBAT Timestamp: 2022-07-14 17:27:36
```
... bleibt der TS des MDIR auf dem Ursprungswert, aber der TS der Sw4 ändert sich auf den Ausführungszeitpunkt von `Script_fetch_all_ext`.

Das ist echt interessant und war mir auch bisher völlig unbekannt das...
A: batteriebetriebene HM-Geräte einen Zeitstempel vom Systemstart bekommen
B: nur durch auslesen "lokaler Werte" per Script die Zeitstempel irgendwie aktualisiert werden

Des Weiteren scheinen die :0 Kanäle (RSSI, LOWBAT usw.) keinerlei zyklische Daten zu senden. Vermutlich passiert da nur was wenn sich was "wichtiges" ändert. Das scheint bei den RSSI-Werten nicht der Fall zu sein, da stehen die Timestamps eines HM-Sec-SCo hier immer noch auf dem heute morgen erfolgten Zentralenstart. 2022-7-14 08:34:31. 


Wenn...
> (die Scriptausführung dauert initial länger)

... unproblematisch für die Integration ist würde ich das mal auf eventuelle Nebenwirkungen abklopfen. 
Da ich nicht weiß wo ich das selbst ändern müsste wäre ne Beta gut. ;-)

Kurz zum Script noch. Statt beide Bedingungen zu eliminieren würde ich nur die Abfrage auf Timestamp > 0 entfernen.
Zeile 29 sähe dann so aus:
`if (oDP) {`

**Comment by SukramJ** [comment]
Konntest Du nachvollziehen, das eine wiederholte Scriptausführung bei HM-Geräten auf Kanal 0 keine geänderten Werte zurückgibt, obwohl die UI diese anzeigt?

**Comment by Baxxy13** [comment]
Das müsstest du mal genauer ausführen worauf du dich beziehst?
Die RSSI Werte? 
Die sind bei mir trotz mehrfacher Ausführung des Scriptes n/a.
![HA_RSSI](https://user-images.githubusercontent.com/54898249/179035121-4ce5f3a7-b4dd-47bf-bc1a-6d82dafed429.JPG)

**Comment by SukramJ** [comment]
Ja, ich meine die RSSI-Werte. Ich verwende einen HM-LC-Sw4-DR zum Testen und der zeigt relativ schnell RSSI Werte an.
UNREACH und STICKY_UNREACH kann ich relativ schnell provozieren und die werden auch gesendet.
Ich sehe das Problem aktuell nur bei den RSSI Werten.

**Comment by SukramJ** [comment]
> Die sind bei mir trotz mehrfacher Ausführung des Scriptes n/a.

Auch mit dem .._ext Script?

**Comment by Baxxy13** [comment]
HM-Sen-MDIR-WM55... Zeitpunkt ist Zentralenstart:
```
"BidCos-RF.NEQ0962600:0.RSSI_DEVICE":1--> 2022-07-14 17:47:46,
"BidCos-RF.NEQ0962600:0.RSSI_PEER":1--> 2022-07-14 17:47:46,
```

HM-LC-Sw4-Ba-PCB... Zeitpunkt ist 1. Aufruf des _ext-Scriptes:
```
"BidCos-RF.OEQ1050013:0.RSSI_DEVICE":1--> 2022-07-14 18:42:04,
"BidCos-RF.OEQ1050013:0.RSSI_PEER":1--> 2022-07-14 18:42:04,
```

Hier sind aber keine DV's vorhanden, daher ändert sich da wohl auch nix.
M.E. beziehen sich die Werte nicht auf die Kommunikation mit der Zentrale.

**Comment by SukramJ** [comment]
Die Werte stehen auch auf 1, das ist der Default-Wert.

**Comment by Baxxy13** [comment]
Ok, aber wenn die jetzt nie geändert/aktualisiert werden dann ist das doch eigentlich unproblematisch wenn die in HA dauerhaft als "unbekannt" angezeigt werden. 
Der vorhin erwähnte HM-Sec-SCo zeigt auch bei beiden "1" obwohl der eine DV zu einem HM-CC-RT-DN hat. Nur "bewegt" wurde er noch nicht.

**Comment by SukramJ** [comment]
Ein weiteres Gerät (HM-LC-Sw1-FM) von mir hat seine RSSI Werte zwischenzeitlich geändert.
Die UI zeigt -59/-60 an, aber die Scripte zeigen immer noch 1/1 an.
Ich denke daher an ein Caching. Beobachtet hab ich das nur bei den RSSI Werten.
Daher denke ich auch, das eine wiederholte/periodische Scriptausführung nicht zielführend ist.

Normale Werte wie STATE auf Kanälen >= 1 werden allerdings korrekt aktualisiert (Script) und auch als Ereignis gesendet.

**Comment by SukramJ** [comment]
In #533 das gleiche Problem mit LOWBAT.

**Comment by SukramJ** [comment]
Ich denke das Ticket können wir erst mal schliessen.
Weitere Diskussionen sollten [hier](https://github.com/danielperna84/hahomematic/discussions/12#discussioncomment-3114694) fortgeführt werden.
