### ISSUE TITLE
Probleme mit Raspberrymatic Version 3.63.9.20220625 und Version 1.10.0  . 

### ISSUE THREAD

**Issue by Bimboboy007** [SukramJ/hahomematic#520]
DONT'T DELETE THIS.
Please answer all questions as good as possible.

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
1.x.x

**Home Assistant version (if applicable):**
2022.x.x

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, ...):
- OS (Original, RaspberryMatic, debmatic/...):
- Version: 

**Problem-relevant configuration:**

Do you use tls?
Do you use callback?
Do you use username and password? 
Which interfaces do you use?

**Describe the bug**

**To Reproduce**

**Screenshots (if applicable)**
- CCU firewall
- integrations view
- device view
- enity view

**Relevant HA log entries (full log)**
```


```

**Diagnostic Information (available on every device)**
```


```

**Expected behavior**

**Additional context**

**Comment by Bimboboy007** [comment]
Die neueste Integration 1.10.0 verursacht auf der CCU Raspberrymatic und auf HA Probleme. Es hat den Anschein dass zuviele Anfragen von der neuen Version heraus gehen und dadurch beide Systeme Beeinträchtigt werden die CCU ist über die Weboberfläche nicht mehr erreichbar. Die Anzeige der RSI Werte und die Voltangaben verschwinden ganz auf der webui der CCU. HA braucht auch eine gefühlte Ewigkeit zum Laden bei einem Neustart und andere Integrationen werden gar nicht mehr geladen.

**Comment by SukramJ** [comment]
Bitte fülle das Issue Template vollständig aus. ich hab keine Lust alles nachzufragen.

Bitte belege deine Vermutung, das zu viele Anfragen gestellt werden. Die Integration sendet nur sehr wenige Anfragen beim Start an die CCU, und wird danach von der CCU über Updates informiert.

**Comment by Bimboboy007** [comment]
Kein Problem mache was möglich ist um zu helfen. Nur ein kleiner Hinweiß scheint nicht nur mir so zu gehen es häufen sich die Meldungen im Internet(Facebook).

**Comment by SukramJ** [comment]
Ich hab mal in die Gruppe **Home Assistant Tips und Tricks** geschaut.
Die einzigen Fehler (Zu viele Serverzugriffe) die dort masshaft auflaufen sind Probleme mit dem **Access Point**.
Ich kann dort nichts im Zusammenhang mit der CCU finden.
Die einzigen Antworten mit Bezug zur CCU sind wohl, behaupte ich mal, von dir.
Die Integration für den Access Point "HomematicIP Cloud" und für die CCU "HomematicIP Local" haben absolut nichts mit einander zu tun.

Vielleicht hab ich auch in den falschen Foren gesucht, aber Facebook ist leider zu wage.

Um Probleme mit deiner CCU auszuschliessen solltest Du die Integration in HA deaktivieren, entfernen oder HA herunterfahren. Danach sollte, sofern deine Problembeschreibung stimmt, die CCU wieder normal arbeiten.
Sollte das Problem weiter bestehen solltest du in den entsprechenden [Foren](https://homematic-forum.de/forum/viewforum.php?f=65) oder bei [Raspberrymatic](https://github.com/jens-maus/RaspberryMatic) ein Ticket aufmachen.

Da in diesem Ticket nach wie vor keine verwendbaren Informationen zu finden sind werde ich diese Ticket erst mal schliessen.
Sofern ausgeschlossen werden kann, das deine CCU das Problem ist, kannst Du gerne wieder ein Ticket aufmachen.
Dann solltest Du aber das Issue-Template ausfühlen. Mit Wagen Hinweisen kann ich leider nichts anfangen, und meine Glaskugel hab ich leider verlegt.

**Comment by Bimboboy007** [comment]
HA Version 2022.7.2 custom_component über HACS Version 1.10.0
ccu Version 3 ; Raspberrymatic 3 Tinkerboard S Version 3.63.9.20220625
Benutze Admin Konto mit Benutzernamen und Passwort mit Lan Anbindung.
Backups brechen ab, RSSI werte in der webui werden nichtmehr dargestellt und auch keine Voltangaben mehr sichtbar.

Also mal langsam ich verstehe dich also versuche du es auch bei den anderen die nicht vom Fach sind bin bemüht alles zusammen zu tragen aber das dauert wenn man nicht so mit der Materie bewandert ist.
Im übrigen scheint es mich nicht alleine zu betreffen und so wie es mittlerweile aussieht liegt es eher an dem CCU update. 
 Wenn du noch etwas brauchst dann bitte so dass es auch normale Menschen verstehen und nicht im Nörd Überflieger modus.

<img width="805" alt="Bildschirmfoto 2022-07-09 um 13 43 14" src="https://user-images.githubusercontent.com/80967872/178104380-a030e6bf-e8b0-4688-9cca-80
<img width="1387" alt="Bildschirmfoto 2022-07-09 um 13 34 41" src="https://user-images.githubusercontent.com/80967872/178104391-3ab7c5c6-3414-42e9-bc5d-b19657886eb3.png">
976491e218.png">
<img width="502" alt="Bildschirmfoto 2022-07-09 um 13 31 08" src="https://user-images.githubusercontent.com/80967872/178104387-d72c390e-2221-4be9-9ebe-6800c8d5ddda.png">

**Comment by Bimboboy007** [comment]
Unter RaspberryMatic bei Facebook gibt es auch noch andere mit dem Problem.

**Comment by SukramJ** [comment]
Dann teile doch mal die Links zu den entsprechenden Threads auf Facebook.

>Um Probleme mit deiner CCU auszuschliessen solltest Du die Integration in HA deaktivieren, entfernen oder HA herunterfahren. Danach sollte, sofern deine Problembeschreibung stimmt, die CCU wieder normal arbeiten.
Sollte das Problem weiter bestehen solltest du in den entsprechenden [Foren](https://homematic-forum.de/forum/viewforum.php?f=65) oder bei [Raspberrymatic](https://github.com/jens-maus/RaspberryMatic) ein Ticket aufmachen.

Hast du das mal gemacht?

**Comment by SukramJ** [comment]
> Im übrigen scheint es mich nicht alleine zu betreffen und so wie es mittlerweile aussieht liegt es eher an dem CCU update.

Warum machst du dann das Ticket hier auf?

**Comment by Bimboboy007** [comment]
Hab da gerade einen Fehler entdeckt
<img width="1274" alt="Bildschirmfoto 2022-07-09 um 14 22 02" src="https://user-images.githubusercontent.com/80967872/178105585-00cb4acc-c10b-459e-bc2c-990753d22b09.png">
<img width="805" alt="Bildschirmfoto 2022-07-09 um 13 43 14" src="https://user-images.githubusercontent.com/80967872/178105588-ab2d090b-f3c6-48c1-a2a5-f7a1705b1803.png">
.

**Comment by Bimboboy007** [comment]
Scheint das die Ursache zu sein
<img width="1359" alt="Bildschirmfoto 2022-07-09 um 14 23 22" src="https://user-images.githubusercontent.com/80967872/178105645-d3d15db3-fd97-4a08-ae9d-f060683cc91e.png">
.

**Comment by Bimboboy007** [comment]
Seite wird nicht weiter geladen.

**Comment by SukramJ** [comment]
Beantwortest Du auch irgendwann mal meine Fragen?

**Comment by Bimboboy007** [comment]
Weil sobald ich die Integration deaktiviere wieder auf die webui zugriff bekomme
<img width="1359" alt="Bildschirmfoto 2022-07-09 um 14 46 46" src="https://user-images.githubusercontent.com/80967872/178106412-314f03f8-2b8d-48e9-a6b7-4ad66ee87c13.png">
.

**Comment by Bimboboy007** [comment]
<img width="776" alt="Bildschirmfoto 2022-07-07 um 12 29 34" src="https://user-images.githubusercontent.com/80967872/178106503-ba7d9a3a-3d2a-4af5-acd1-6ee15608337a.png">

**Comment by SukramJ** [comment]
Also wenn Du eine ältere RM Version einspielst hast Du das Problem auch nicht mehr?

**Comment by Bimboboy007** [comment]
Richtig so sieht es aus ich kann ihnen auch gerne mal die Logdatei von der CCU senden vielleicht hilft das etwas.
das was ich bis jetzt herausfinden konnte dass es aber nicht nur mit der Integration von ihnen sonder auch mit der letzten Version der CCU am besten funktioniert.

**Comment by Bimboboy007** [comment]
Richtig und die von ihnen.

**Comment by SukramJ** [comment]
Wenn die Integration mit einer älteren CCU Version läuft, kann ich hier nicht weiterhelfen.
Die Integration macht eine Verbindung zur CCU auf. Weniger geht nicht. 

Am Besten geholfen wird dir wenn Du ein Ticket direkt bei [RM](https://github.com/jens-maus/RaspberryMatic/issues) aufmachst. 
Scheinbar ist beim Einspielen der neusten CCU Version etwas schief gelaufen, aber da hab ich keine Expertise.

Auf meinen Systemen (Proxmox, RPi3) läuft 3.63.9.20220625 mit 1.10.0 fehlerfrei, und ich gehe mit bis zu 3 HA Instanzen auf eine CCU.

**Comment by Bimboboy007** [comment]
Haben sie eventuell einen link dazu ?
Ich versuche es gerade mit der alten RM Version und der 1.10.0 auf HA 2022.7.2 mal schauen was passiert.
Hab dazu im Homematic Forum schon mal etwas geschrieben aber jens maus hat dazu gemeint der Fehler ist nicht nachvollziehbar.  Hab es auch schon mit der alten CCU3 Probiert da sieht es besser aus und hab die neueste Version der CCU auch schon auf verschiedene arten installiert mit normalem update und download egal was ich mache.

**Comment by SukramJ** [comment]
Link zu was?  RM ist doch oben verlinkt(blau).

**Comment by Bimboboy007** [comment]
okay
danke schönes Wochenende

**Comment by Bimboboy007** [comment]
Nochmal einen kurzen Zwischenbericht am besten funktioniert HA 7.2 die Version 1.9.0 und Raspberrymatic 20220521 alles andere macht nur Ärger.

**Comment by danielperna84** [comment]
Keine Ahnung wie relevant das ist, aber die Meldung mit den zu vielen Verbindung hatte ich vor langer Zeit mal als ich mit dem JSON-RPC angefangen habe. Die CCU kommt nicht so gut mit _zu vielen_ (gefühlt einer Hand voll) Sessions klar. Wenn also mal ein Logout nicht klappt, Variablen gepollt werden, zusätzlich ggf. auch noch was anderes auf die CCU zugreift und man dann auch noch im Browser auf die CCU geht, dann liefert sie solche Meldungen.

**Comment by SukramJ** [comment]
Ich denke das hat keine Relevanz mehr. 
Seit Version 0.38 (März) werden alle CCU-Daten mit einem einzigen Request geladen.
Zu dem Zeitpunkt hab ich auch einen Bug im Session handling behoben. Seit dem verwenden wir für die JsonRPC nur noch eine Session, die wir dauerhaft aufhalten, und über die alle JsonRPC Anfragen gehen. Nach dem Start werden nur noch alle 30s die Systemvariablen abgefragt, und mehr nicht. Datenänderungen werden nur über XmlRPC gesendet.

Ich glaube das CCU Limit für WebSessions (JsonRPC) liegt bei 4. Hab ich irgendwann mal im Homematic Forum gefunden.
Mit 2 dauerhaft gestarteten HA Instanzen und einer Dev Instanz die ständig gestartet und gestoppt wird kommt meine CCU ohne Probleme klar. Das war noch vor 0.38 anders.

Ob hier beim Testen Version 1.8., 1.9 oder 1.10 verwendet werden macht keinen Unterschied.

**Comment by Bimboboy007** [comment]
Nochmal ein update zur Lage. Also hab ein Rollback gemacht original CCU3 mit Raspberrymatic und überall die neueste Software und alles läuft ohne Probleme.
