### ISSUE TITLE
No entities found after configuration

### ISSUE THREAD

**Issue by kaitomalik** [SukramJ/hahomematic#523]
DONT'T DELETE THIS.
Please answer all questions as good as possible.

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
1.10.0 / 2022.7.0

**Home Assistant version (if applicable):**
2022.6.7

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, ...): CCU3
- OS (Original, RaspberryMatic, debmatic/...): Original
- Version: 3.65.6

**Problem-relevant configuration:**

Do you use tls? no
Do you use callback? no
Do you use username and password? yes
Which interfaces do you use? Homematic IP Port 2010, Homematic (Bidcos-RF) 2001

**Describe the bug**
After installing the integration, 2 devices and a service are available - but no entities.

Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/65624148/178143242-1d286df4-8d44-4e4e-a74d-8354fcb1f409.png)
![image](https://user-images.githubusercontent.com/65624148/178143255-0a1fcc61-c0e4-41e9-b86b-747d352eb533.png)
![image](https://user-images.githubusercontent.com/65624148/178143259-0a1feac0-dd99-446a-b5d9-ff68c2a84547.png)

![image](https://user-images.githubusercontent.com/65624148/178143271-0e42033e-cbe6-4dcf-a89e-e1d3fa7b8e60.png)
![image](https://user-images.githubusercontent.com/65624148/178143181-c785bd2c-465b-4f4b-9b5f-c0d15a1908cc.png)
![image](https://user-images.githubusercontent.com/65624148/178143232-5c49ed8c-966b-499e-a9b3-c510ed4eb9fe.png)
![image](https://user-images.githubusercontent.com/65624148/178143312-adf9d7fa-3659-45a0-b59b-4ae0e7ed388f.png)
![image](https://user-images.githubusercontent.com/65624148/178143326-0b61e960-c4d5-40bd-b827-d5cb8d7e495e.png)

**Relevant HA log entries (full log)**
![image](https://user-images.githubusercontent.com/65624148/178143374-7b6e6343-a78a-4ad2-9ba9-9e05d39b7759.png)
![image](https://user-images.githubusercontent.com/65624148/178143387-469b371c-ba1c-4091-b568-84318d6eb015.png)

```

**Diagnostic Information (available on every device)**

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.6.7",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.9.12",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "5.15.32-v8",
    "supervisor": "2022.07.0",
    "host_os": "Home Assistant OS 8.2",
    "docker_version": "20.10.14",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "homematicip_local": {
      "version": "1.10.0",
      "requirements": [
        "hahomematic==2022.7.0"
      ]
    },
    "gardena_smart_system": {
      "version": "1.0.0",
      "requirements": [
        "py-smart-gardena==1.3.1"
      ]
    },
    "alexa_media": {
      "version": "4.0.3",
      "requirements": [
        "alexapy==1.26.1",
        "packaging>=20.3",
        "wrapt>=1.12.1"
      ]
    },
    "hacs": {
      "version": "1.26.0",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "dwd_weather": {
      "version": "1.2.22",
      "requirements": [
        "simple_dwd_weatherforecast==1.1.5",
        "markdownify==0.6.5"
      ]
    },
    "spotcast": {
      "version": "v3.6.29",
      "requirements": [
        "spotify_token==1.0.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "homematicip_local",
    "name": "Homematic(IP) Local",
    "config_flow": true,
    "documentation": "https://github.com/danielperna84/custom_homematic",
    "issue_tracker": "https://github.com/danielperna84/hahomematic/issues",
    "requirements": [
      "hahomematic==2022.7.0"
    ],
    "ssdp": [
      {
        "manufacturer": "EQ3",
        "manufacturerURL": "http://www.homematic.com"
      }
    ],
    "zeroconf": [],
    "homekit": {},
    "dependencies": [],
    "codeowners": [
      "@danielperna84",
      "@SukramJ"
    ],
    "iot_class": "local_push",
    "loggers": [
      "hahomematic"
    ],
    "version": "1.10.0",
    "is_built_in": false
  },
  "data": {
    "config": {
      "entry_id": "8a27e6afefb30428a02e466e73611425",
      "version": 1,
      "domain": "homematicip_local",
      "title": "ccu3-webui",
      "data": {
        "instance_name": "ccu3-webui",
        "host": "192.168.178.68",
        "username": "**REDACTED**",
        "password": "**REDACTED**",
        "tls": false,
        "verify_tls": false,
        "callback_host": null,
        "callback_port": null,
        "json_port": 80,
        "interface": {
          "HmIP-RF": {
            "port": 2010
          },
          "BidCos-RF": {
            "port": 2001
          },
          "VirtualDevices": {
            "port": 9292,
            "path": "/groups"
          }
        }
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "ssdp",
      "unique_id": "9D89AB2F6E",
      "disabled_by": null
    },
    "platform_stats": {},
    "devices": []
  }
}


```

**Comment by danielperna84** [comment]
[Hier](https://github.com/danielperna84/custom_homematic/releases/tag/1.10.0) steht der entscheidende Hinweis: _This release requires HA 2022.7_

**Comment by kaitomalik** [comment]
Das habe ich übersehen - sorry.
Ich wollte vom HMIP Cloud Integration mit AP auf die CCU3 wechseln und die Geräte sukzessive übernehmen.
Leider funktioniert mit HA 2022.7 die HMIP Cloud Integration nicht mehr sodas ich ein Rollback machen musste.
Dann warte ich bis die Cloud Integration wieder funktioniert und versuche es dann wieder.
Danke.

**Comment by irqnet** [comment]
Ich habe heute wegen eines SD Karten crashes meine uralt Homeassistant Installaton auf den Müll geworfen und habe RaspberryMatic CCU als Addon neu mit aufgesetzt.

Die Homematic Geräte habe ich alle neu angelernt, habe aber das Problem das mit der über HACS installierten Integration keine  Geräte angezeigt werden.

![image](https://user-images.githubusercontent.com/32534199/179807661-c8138db5-7e37-41b6-a8f5-7937ddfac886.png)

Mehr bekomme ich leider nicht zu sehen.

Aktuell habe ich die folgenden Ports manuell offen und auch in RapsberryMatic die Firewall deaktiviert.
![image](https://user-images.githubusercontent.com/32534199/179807772-3a398905-2856-4017-b21d-a3bd03cfd1f2.png)


Mit der nativen Homematic Integration in Homeassistant bekomme ich die Geräte importiert, aber ohne brauchbare Namen.

![image](https://user-images.githubusercontent.com/32534199/179807911-e45652b1-7f9e-4744-9191-db6a7c87c67a.png)
