### ISSUE TITLE
Configurable local xml-rpc callback port

### ISSUE THREAD

**Issue by nnexai** [SukramJ/hahomematic#537]
DONT'T DELETE THIS.

**Is your feature request related to a problem? Please describe.**
Currently there seems to be no way to have custom_homematic work as part of a home-assistant installation running as a container, without it using host-network. This is due to the xml-rpc-server in hahomematic seemingly using a random callback-port, making it impossible to setup a stable, working port mapping.

**Describe the solution you'd like**
Make the local port under which the xml-rpc-server is running configurable.

**Describe alternatives you've considered**
Other solutions could be: use the configurable "callback_port" not only for communication, but also as the port the server is started with - reduces the number of config options, but is less flexible.

Using the host-network route is no option, since ha is running as part of a larger collection of containers in a locally setup kubernetes cluster with multiple nodes. I need a way to setup a fixed port and ip (ingress, load balancer etc) and host-network would not allow for a fixed ip.

**Additional context**
Reading through other issues regarding ports and container based setups, the current solution seems to be to not do it. I know of the limitations regarding auto discovery but disregarding homematic I was able to work around all other limitations.

**Comment by SukramJ** [comment]
Version 1.12.0 will fix an [issue](https://github.com/danielperna84/custom_homematic/commit/625662d1744527d86f6aed01f0f7054a6c88d20e) with XmlRPCServer.
Then callback_host and callback_port can be used.
