### ISSUE TITLE
No entities listed in Homeassistant after configuring integration

### ISSUE THREAD

**Issue by irqnet** [SukramJ/hahomematic#544]
DONT'T DELETE THIS.

Please answer all questions as good as possible.

Language: english/german

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you have read the release notes at https://github.com/danielperna84/custom_homematic/releases. 

Make sure you are running the latest version of the custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
1.12.0

**Home Assistant version (if applicable):**
2022.7.5

**CCU version:**
- Model (RaspberryMatic CCU HA-Addon ...): HA-Addon
- OS (Original, RaspberryMatic, debmatic ...): RasperryMatic
- Version: 3.63.9.20220625

**Problem-relevant configuration:**

Do you use tls? No
Do you use callback? No
Do you use username and password? Yes
Which interfaces do you use (hmip/bidcos/wired)? bidcos

**Describe the bug**
Nach Konfiguration von HaHomematic werden keine Entities angezeigt

**To Reproduce**
1. Go to Homeassistant -> Integrations
2. Click on 'Add Integration
3. Scroll down to 'Homematic(IP) local'

**Screenshots (if applicable)**
 
![image](https://user-images.githubusercontent.com/32534199/179810658-6ed12536-3d12-4e0a-926e-a0bc4a939a14.png)

5. Config Part 2

![image](https://user-images.githubusercontent.com/32534199/179810716-6dee973c-d502-429b-bd9d-5284e31ccb15.png)

![image](https://user-images.githubusercontent.com/32534199/179810748-856d303f-3b1e-4d0a-9965-d461a6a15deb.png)

![image](https://user-images.githubusercontent.com/32534199/179810817-2c288a1c-d275-4d6f-ab8b-47a7378503b2.png)

![image](https://user-images.githubusercontent.com/32534199/179811135-1acdb178-d424-4735-bf50-d6db82608ba6.png)

- CCU firewall
- integrations view
- device view
- enity view

**Relevant HA log entries (full log)**

`2022-07-19 19:32:18 WARNING (MainThread) [hahomematic.json_rpc_client] _do_login: Unable to open session: {'name': 'JSONRPCError', 'code': 501, 'message': 'invalid credentials or too many sessions'}
2022-07-19 19:32:18 WARNING (MainThread) [hahomematic.json_rpc_client] _post_script: Error while logging in via JSON-RPC.
2022-07-19 19:32:18 WARNING (MainThread) [hahomematic.json_rpc_client] _do_login: Unable to open session: {'name': 'JSONRPCError', 'code': 501, 'message': 'invalid credentials or too many sessions'}
2022-07-19 19:32:18 WARNING (MainThread) [hahomematic.json_rpc_client] _post: Error while logging in via JSON-RPC.`

**Expected behavior**
Entities should be listed in Homeassistant

Der Fehler ist eher schon eindeutig, weil im Log ja steht das angeblich die credentials falsch sind, was ich aber ausschließen kann. Too many sessions kann ich nicht prüfen.

Bin gerade etwas auf dem Holzweg.

**Comment by SukramJ** [comment]
Sind irgendwelche Sonderzeichen in Password?
Siehe https://github.com/danielperna84/custom_homematic#authentication.
Ansonsten mal das RM-Addon starten damit damit die Sessions gelöscht werden.

**Comment by irqnet** [comment]
Keine Sonderzeichen, in dem Fall sogar nur Buchstaben.

RM-Addon neustarten meinst Du? Hab ich bereits, bringt aber nichts.

**Comment by SukramJ** [comment]
Ist die Authentifizierung in der CCU aktiviert?

**Comment by SukramJ** [comment]
> Which interfaces do you use (hmip/bidcos/wired)? **bidcos**

Du hast nur klassische HM Geräte? 
Aber: bei den Interface wurde nur HmIP und nicht Bidcos ausgewählt.

**Comment by irqnet** [comment]
Sorry auf dem Screenshot habe ich es tatsächlich falsch rum ausgewählt, ist aber jetzt auf Bidcos konfiguriert.

Authentifzierung in der CCU ist nicht aktiv.

**Comment by irqnet** [comment]
Ich hab gerade einen zusätzlichen User in der CCU angelegt, jetzt geht es.

Hab ich das übersehen?

**Comment by SukramJ** [comment]
Kann ich nicht sagen.

**Comment by SukramJ** [comment]
Wenn es funktioniert, dann kann das Ticket ja geschlossen werden
