### ISSUE TITLE
No devices found after adding integration.  xxx is not available for backend.

### ISSUE THREAD

**Issue by Flo2410** [SukramJ/hahomematic#556]
DONT'T DELETE THIS.

Please answer all questions as good as possible.

Language: english/german

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you have read the release notes at https://github.com/danielperna84/custom_homematic/releases. 

Make sure you are running the latest version of the custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
1.12.5 (Homematic(IP) Local from HACS)

**Home Assistant version (if applicable):**
2022.07.0

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, HA-Addon ...): HA-Addon
- OS (Original, RaspberryMatic, debmatic ...): RaspberryMatic CCU
- Version: 3.65.6.20220723

**Problem-relevant configuration:**

Do you use tls? no
Do you use callback? no
Do you use username and password? yes
Which interfaces do you use (hmip/bidcos/wired)? hmip

**Describe the bug**

After installing and configuring the Homematic(IP) Local  integration, only one service and no devices or entities are discovered. 

From the logs, it appears to have something to do with SSL?
And it says that the service xxx is not available for backend.

**To Reproduce**
1. Install HACS and the  Homematic(IP) Local integration following this instructions: https://github.com/jens-maus/RaspberryMatic/wiki/HomeAssistant-Integration
2. While adding the integration, only one service is discovered.

**Screenshots (if applicable)**
- CCU firewall
<img width="510" alt="Bildschirmfoto 2022-07-31 um 16 03 08" src="https://user-images.githubusercontent.com/31217036/182030013-be0f47ad-a7f3-4493-b65e-64dc8df117ab.png">

- integrations config
<img width="413" alt="Bildschirmfoto 2022-07-31 um 16 05 00" src="https://user-images.githubusercontent.com/31217036/182030127-9c0569ce-379d-4d53-9752-e119e30119c0.png">
<img width="407" alt="Bildschirmfoto 2022-07-31 um 16 05 12" src="https://user-images.githubusercontent.com/31217036/182030132-f07ae33e-f712-408e-9043-3ecf2456618f.png">

- integrations page
<img width="269" alt="Bildschirmfoto 2022-07-31 um 16 05 25" src="https://user-images.githubusercontent.com/31217036/182030153-82c1d903-bbe9-441a-acf0-0446e456a775.png">

- integration view
<img width="1061" alt="Bildschirmfoto 2022-07-31 um 16 05 41" src="https://user-images.githubusercontent.com/31217036/182030182-b813c8d0-b6eb-41bd-9c01-4f55ce8a0270.png">

**Relevant HA log entries (full log)**
```
Logger: hahomematic.central_unit
Source: /usr/local/lib/python3.10/site-packages/hahomematic/central_unit.py:345
First occurred: 3:33:04 PM (198 occurrences)
Last logged: 4:08:50 PM

_create_clients: Interface: HmIP-RF is not available for backend.
_create_clients: Interface: VirtualDevices is not available for backend.
_create_clients: Interface: BidCos-RF is not available for backend.

```

```
Logger: hahomematic.json_rpc_client
Source: /usr/local/lib/python3.10/site-packages/hahomematic/json_rpc_client.py:183
First occurred: 3:33:04 PM (198 occurrences)
Last logged: 4:08:50 PM

_post: Error while logging in via JSON-RPC.
```

```
Logger: hahomematic.json_rpc_client
Source: /usr/local/lib/python3.10/site-packages/hahomematic/json_rpc_client.py:157
First occurred: 3:33:04 PM (406 occurrences)
Last logged: 4:08:50 PM

_do_login: Unable to open session: Cannot connect to host de838cd8-raspberrymatic:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')]
```

```
Logger: hahomematic.json_rpc_client
Source: /usr/local/lib/python3.10/site-packages/hahomematic/json_rpc_client.py:300
First occurred: 3:33:04 PM (406 occurrences)
Last logged: 4:08:50 PM

_do_post: ClientConnectorError
```

```
Logger: hahomematic.json_rpc_client
Source: /usr/local/lib/python3.10/site-packages/hahomematic/json_rpc_client.py:214
First occurred: 3:33:04 PM (208 occurrences)
Last logged: 4:08:50 PM

_post_script: Error while logging in via JSON-RPC.
```

```
Logger: hahomematic.central_unit
Source: /usr/local/lib/python3.10/site-packages/hahomematic/central_unit.py:931
First occurred: 3:33:05 PM (72 occurrences)
Last logged: 4:08:49 PM

check_connection: No clients exist. Trying to create clients for server RaspberryMatic
```

**Diagnostic Information (available on every device)**
```
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.7.7",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Vienna",
    "os_name": "Linux",
    "os_version": "5.15.32-v8",
    "supervisor": "2022.07.0",
    "host_os": "Home Assistant OS 8.4",
    "docker_version": "20.10.14",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "homematicip_local": {
      "version": "1.12.5",
      "requirements": [
        "hahomematic==2022.7.14"
      ]
    },
    "hacs": {
      "version": "1.26.2",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    }
  },
  "integration_manifest": {
    "domain": "homematicip_local",
    "name": "Homematic(IP) Local",
    "config_flow": true,
    "documentation": "https://github.com/danielperna84/custom_homematic",
    "issue_tracker": "https://github.com/danielperna84/hahomematic/issues",
    "requirements": [
      "hahomematic==2022.7.14"
    ],
    "ssdp": [
      {
        "manufacturer": "EQ3",
        "manufacturerURL": "http://www.homematic.com"
      }
    ],
    "zeroconf": [],
    "homekit": {},
    "dependencies": [],
    "codeowners": [
      "@danielperna84",
      "@SukramJ"
    ],
    "iot_class": "local_push",
    "loggers": [
      "hahomematic"
    ],
    "version": "1.12.5",
    "is_built_in": false
  },
  "data": {
    "config": {
      "entry_id": "8d1b71169082f402839d09cfc90081a8",
      "version": 1,
      "domain": "homematicip_local",
      "title": "RaspberryMatic",
      "data": {
        "instance_name": "RaspberryMatic",
        "host": "de838cd8-raspberrymatic",
        "username": "**REDACTED**",
        "password": "**REDACTED**",
        "tls": false,
        "verify_tls": false,
        "callback_host": null,
        "callback_port": null,
        "json_port": null,
        "interface": {
          "HmIP-RF": {
            "port": 2010
          },
          "BidCos-RF": {
            "port": 2001
          },
          "VirtualDevices": {
            "port": 9292,
            "path": "/groups"
          }
        }
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": "unknown",
      "disabled_by": null
    },
    "platform_stats": {},
    "devices": []
  }
}

```

**Expected behavior**

I expect the devices from RaspberryMatic to be found by the integration.

**Additional context**

After reviewing this issue. I discovered that the ```enable Homematic (Bidcos-RF)``` setting automatically re-enables after disabling it.

**Comment by SukramJ** [comment]
> [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')]

Looks like you enabled SSL/TLS in your CCU, and not in this integration.
Disable SSL/TLS in your CCU or enable it in this integration.

**Comment by Flo2410** [comment]
Thanks for the quick response.  Yup, that was my problem. I'm really embarrassed to not have tried that...

**Comment by SukramJ** [comment]
No problem
