### ISSUE TITLE
HM-PBI-4-FM Fehlt nur Batteriestatus

### ISSUE THREAD

**Issue by Blackei** [SukramJ/hahomematic#570]
Hi,

ich hätte noch ein Schalter der nicht unterstützt wird. 

HM-PBI-4-FM 

{
    "event_type": "homematic.keypress",
    "data": {
        "name": "Tuerklingel_RM",
        "param": "PRESS_SHORT",
        "channel": 1
    },
    "origin": "LOCAL",
    "time_fired": "2022-07-21T18:09:50.564893+00:00",
    "context": {
        "id": "01G8GZ77Z4JT5VPAEFXQQ5G7QT",
        "parent_id": null,
        "user_id": null
    }
}

DONT'T DELETE THIS.

Please answer all questions as good as possible.

Language: german

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you have read the release notes at https://github.com/danielperna84/custom_homematic/releases. 

Make sure you are running the latest version of the custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
1.x.x

**Home Assistant version (if applicable):**
2022.x.x

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, HA-Addon ...):
- OS (Original, RaspberryMatic, debmatic ...):
- Version: 

**Problem-relevant configuration:**

Do you use tls?
No
Do you use callback?
No
Do you use username and password?
Yes
Which interfaces do you use (hmip/bidcos/wired)?
wired killed the configuration 

**Describe the bug**

**To Reproduce**

**Screenshots (if applicable)**
- CCU firewall
- integrations view
- device view
- enity view

**Relevant HA log entries (full log)**
```


```

**Diagnostic Information (available on every device)**
```


```

**Expected behavior**

**Additional context**

**Comment by SukramJ** [comment]
Was soll denn fehlen?

**Comment by Blackei** [comment]
Guten Tag,

ich sehe keinen Schaltstatus des Schalters sondern nur den Batteriestatus.

**Comment by SukramJ** [comment]
Dann ist ja Alles richtig. Das Gerät hat keine Schalter(Zustand)
Die Eingänge sind Taster (Zustandslos), die in Automatisierungen über `device trigger` oder `events` verwendet werden können.

**Comment by SukramJ** [comment]
Ich denke das Ticket kann geschlossen werden.
