### ISSUE TITLE
Unit of Measurement missing for HB-UNI-SEN-PRESS

### ISSUE THREAD

**Issue by malt0r90** [SukramJ/hahomematic#577]
Hi,

after updating to the new Version 1.13.3 the Unit Bar for the Sensor HB-UNI-SEN-PRESS is missing. It's just showing as a numeric value. Graphing is not working anymore. 

Running on newest HA version. Please advice.

**Comment by SukramJ** [comment]
> DONT'T DELETE THIS.
Please answer all questions as good as possible.

Yes, please fill out the issue template.

**Comment by SukramJ** [comment]
I think best option is to start with a new issue and filled out template.
