### ISSUE TITLE
HB-UNI-SEN-PRESS - no unit of measurement

### ISSUE THREAD

**Issue by malt0r90** [SukramJ/hahomematic#580]
**custom_component version (if applicable):**
1.13.3

**known last working custom_component version (if applicable):**
1.12.x

**Home Assistant version (if applicable):**
2022.8.2

**CCU version:**
- Model: Raspi3B+
- OS: RaspberryMatic:
- Version: 3.65.6.20220723

**Problem-relevant configuration:**

Do you use tls? - NO
Do you use callback? - NO
Do you use username and password? - NO
Which interfaces do you use (hmip/bidcos/wired)? - BIDCOS

**Describe the bug**
After the Update to component Version 1.13.* the unit Bar ist not anymore displayed for the device HB-UNI-SEN-PRESS. Therefore I can't use the graphing anymore to see the history of the pressure.

**To Reproduce**
Open the graphing or check the Pressure value

**Comment by SukramJ** [comment]
Please export device definition as described [here],(https://github.com/danielperna84/custom_homematic#homematicip_localexport_device_definition)
and add a screenshot of the entities attributes.

**Comment by malt0r90** [comment]
Please find the screenshot attached. 

Regarding device definition: I'm not sure how to export the definition as I don't know where I need to export the files. Files are also not in the folder mentioned. I haven't configured anything manually. Only used the GUI
![HB-UNI-SEN-PRESS_attributes](https://user-images.githubusercontent.com/107195026/184010840-32fd50fa-4172-42c8-a5a1-e15fa8ae9127.PNG)
.

**Comment by malt0r90** [comment]
Additional Info:

when I add the unit of measurement Bar manually using the developer tools the graphing is correct until the value changes.
![HB-UNI-SEN-PRESS_dev_options](https://user-images.githubusercontent.com/107195026/184011944-b1d08b44-4413-4312-b6a3-713297d5cc81.PNG)
![HB-UNI-SEN-PRESS_with_unit](https://user-images.githubusercontent.com/107195026/184011972-11c08c70-8753-4b5a-8e8b-21d02e04afc5.PNG)

**Comment by SukramJ** [comment]
> Regarding device definition: I'm not sure how to export the definition as I don't know where I need to export the files. Files are also not in the folder mentioned. I haven't configured anything manually. Only used the GUI

The service `homematicip_local.export_device_definition` can by found under _development tools/services_ in the UI.
If you execute it for your device, the files will be in the mentioned folders.

**Comment by malt0r90** [comment]
Thanks for pointing me in the right direction. Please find both requested files attached:
[device_definitions.zip](https://github.com/danielperna84/hahomematic/files/9306959/device_definitions.zip)

**Comment by SukramJ** [comment]
fixed with 1.13.4
