### ISSUE TITLE
Fenstersensoren werden als Anwesenheitssensoren in Homekit weitergegeben

### ISSUE THREAD

**Issue by tornenen** [SukramJ/hahomematic#581]
DONT'T DELETE THIS.

Please answer all questions as good as possible.

Language: german

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you have read the release notes at https://github.com/danielperna84/custom_homematic/releases. 

Make sure you are running the latest version of the custom_component (and Home Assistant) before reporting an issue.

**custom_component version (if applicable):**
1.13.3

**known last working custom_component version (if applicable):**
Nicht sicher. Habe Das Plugin und HA gleichzeitig aktualisiert. Das die Fenstersensoren aufeinmal nicht mehr im Homekit als Fenstersensoren waren ist mir 2 Tage später aufgefallen.

**Home Assistant version (if applicable):**
2022.8.3

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, HA-Addon ...): CCU3
- OS (Original, RaspberryMatic, debmatic ...): RaspberryMatic
- Version: 3.65.6.20220723

**Problem-relevant configuration:**

Do you use tls? ne
Do you use callback? ne
Do you use username and password? ja 
Which interfaces do you use (hmip/bidcos/wired)? ?

**Describe the bug**
Die Fenstersensoren werden seit einem Update als Anwesenheitssensoren in Homekit angezeigt. Nicht mehr als Fenstersensor.
**To Reproduce**
1. Fensterkontakt über HA mit Homekit Bridge in Homekit einbinden
2
**Screenshots (if applicable)**
Vorher: 
![9114B272-E831-45AB-B887-673FB8927B48](https://user-images.githubusercontent.com/76594569/183906051-3a75e2c2-1ede-4962-aa3b-0ba7963f8cc9.jpeg)

Nachher:
![E6A2F5EE-3CC6-4796-B39A-E55859DC72A1](https://user-images.githubusercontent.com/76594569/183906073-332d31e9-7408-44be-aa7f-836c8e653846.jpeg)

**Comment by SukramJ** [comment]
**Dies ist eine Integration für Homematic(IP) in Home Assistant.**
Die Typen der Entitäten werden über die `device_class` gesteuert. In diesem Fall `window` oder `door`.
Was Homekit danach daraus macht kann ich nicht einschätzen und ist nicht im Scope der Integration!

Also bitte die `device_class` prüfen.

**Comment by tornenen** [comment]
Ok, danke
