### ISSUE TITLE
HmIP-SWDO (window and door sensors) - Device Class

### ISSUE THREAD

**Issue by ChristophCaina** [SukramJ/hahomematic#582]
DONT'T DELETE THIS.

**Is your feature request related to a problem? Please describe.**
I would really appreciate, if the HmIP-SWDO sensors can be classified as "device_class: door"
Within the HmIP Integration of HomeAssistant, these devices have the device_class: door attribute, and therefore, there states are: Open / Closed.

Unfortunately, after adding some of my Sensors to the Local CCU, they don't have this device class anymore and only reporting ON / OFF

![grafik](https://user-images.githubusercontent.com/26391061/184118828-3a61ad03-9d11-44ef-88d0-d9c15a8e317c.png)

HmIP Cloud integration - Sensor: HmIP_SWDO_I
![grafik](https://user-images.githubusercontent.com/26391061/184119202-5bf489b4-ca90-483c-bc3b-4de3c801702e.png)

HmIP CCU integration - Sensor: HmIP_SWDO_I
![grafik](https://user-images.githubusercontent.com/26391061/184119105-b93fa0ca-31a4-4cf2-9fdd-e93c3a85d6ba.png)
HmIP CCU integration - Sensor: HmIP_SWDO_PL
![grafik](https://user-images.githubusercontent.com/26391061/184119282-ef830f85-7764-45e3-b180-47925d22546c.png)

**Describe the solution you'd like**
add the device_class: door to the HmIP_SWDO Sensors

**Describe alternatives you've considered**

**Additional context**

**Comment by SukramJ** [comment]
Good catch. You found a bug introduced by a previous refactoring.
Version 1.13.6 should fix it.

The default `device_class` for such sensors here is `window`, but you can customize it in HA

**Comment by ChristophCaina** [comment]
thanks :)
Just updated to 1.13.7 and it is fixed 👍
