### ISSUE TITLE
homematic Störung 

### ISSUE THREAD

**Issue by sven34466** [SukramJ/hahomematic#583]
DONT'T DELETE THIS.

Please answer all questions as good as possible.

Language: german

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.
ja 
Make sure you have read the release notes at https://github.com/danielperna84/custom_homematic/releases. 
ja
Make sure you are running the latest version of the custom_component (and Home Assistant) before reporting an issue.
ja

**custom_component version (if applicable):**
letzte version

**known last working custom_component version (if applicable):**
nicht bekannt 

**Home Assistant version (if applicable):**
2022.8.3

**
- Raspberrymatic HA-Addon ..3.65.6.20220723):
- Version: .3.65.6.20220723

**Problem-relevant configuration:**

Do you use tls? nein
Do you use callback? kann ich nicht beantworten 
Do you use username and password? ja
Which interfaces do you use (hmip/bidcos/wired)? hmip bidcos

**Describe the bug**

**To Reproduce**
1. Go to '...'no
2. Click on '....'no
3. Scroll down to '....'no
4. See error no

**Screenshots (if applicable)**
- CCU firewall später
- integrations view später
- device view später
- enity view

**Relevant HA log entries (full log)**
```Traceback (most recent call last):
  File "/config/custom_components/homematicip_local/control_unit.py", line 724, in _async_fetch_data
    await self._hm_hub.fetch_sysvar_data()
  File "/usr/local/lib/python3.10/site-packages/hahomematic/hub.py", line 83, in fetch_sysvar_data
    def unit(self) -> str | None:
  File "/usr/local/lib/python3.10/site-packages/hahomematic/hub.py", line 146, in _update_sysvar_entities
    unique_id = generate_unique_id(
  File "/usr/local/lib/python3.10/site-packages/hahomematic/central_unit.py", line 671, in get_all_system_variables
  File "/usr/local/lib/python3.10/site-packages/hahomematic/client.py", line 685, in get_all_system_variables
  File "/usr/local/lib/python3.10/site-packages/hahomematic/json_rpc_client.py", line 459, in get_all_system_variables
  File "/usr/local/lib/python3.10/site-packages/hahomematic/json_rpc_client.py", line 526, in _get_system_variables_ext_markers
  File "/usr/local/lib/python3.10/site-packages/hahomematic/json_rpc_client.py", line 235, in _post_script
    }
  File "/usr/local/lib/python3.10/pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/local/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.10/site-packages/hahomematic/rega_scripts/get_system_variables_ext_marker.fn'




```

**Diagnostic Information (available on every device)**
```
bei Raspi läuft alles 

```

**Expected behavior**
wenn möglich hilfe
**Additional context**
alles läuft normal ohne fehler nach ca. 24h tritt das auf immer wenn ein Befehl ausgefürt wird kommt danach diese Meldung
z.b. thermostat von 20 auf 21 der Befehl wird ausgeführt kann man am Display sehen

**Comment by SukramJ** [comment]
> custom_component version (if applicable):
letzte version

Damit kann ich nichts anfangen! Allein heute gab es mehrere Updates.

**Comment by SukramJ** [comment]
Der _async_fetch_data(und folge Befehle) wird alle 30s ausgeführt.
Wenn der Fehler nur alle 24h auftritt kann es nicht an einer fehlenden `get_system_variables_ext_marker` Datei liegen.
Ich würde erst mal einen Fehler in der Integration ausschliessen.

Kann es sein das das die SD-Card etwas älter ist und eventuell verschliessen? 
Schau die mal die anderen Logs in HA an ob da noch was zu finden ist, aber ich denke das das Ticket hier geschlossen werden kann.

**Comment by SukramJ** [comment]
Version 1.14.0 reduziert das Lesen der Scripte, aber ich denke das dein System eher ein Problem mit der SD-Karte hat, oder mit der Auslastung

**Comment by sven34466** [comment]
hallo 
danke für die Antwort ist ein x86 system mit emmc 64 gb

**Comment by SukramJ** [comment]
Emmc sollte eigentlich keine Problem sein.
Versuche mal die 1.14.0.

**Comment by sven34466** [comment]
Hallo 

 

Werde ich machen habe aktuell 1.13.3 

Was ist immer mit bump to gemeint sorry wenn ich so was frage 

Muss mann vorher auch erst ein update machen Core oder nicht

Danke für die hilfe

Gruß

 

Sven

**Comment by SukramJ** [comment]
> Was ist immer mit bump to gemeint sorry wenn ich so was frage

Das Anheben der Version.

> Muss mann vorher auch erst ein update machen Core oder nicht

Eine Custom Component kann unabhängig von Core aktualisiert werden.

**Comment by SukramJ** [comment]
> Emmc sollte eigentlich keine Problem sein.

Trotzdem mal die Host Logs kontrollieren.

**Comment by sven34466** [comment]
Wollte emmc in ssd noch ändern verschliessen zeigt 30 % an kann man das machen mit Datenträger verschieben oder besser über Backup?
Im host steht nur was von der WLAN Schnittstelle hatte ich am Anfang benutzt jetzt Kabel

**Comment by SukramJ** [comment]
Ich mach hier keinen HA Support, aber ich würde über Backup gehen.
