### ISSUE TITLE
CCU Interface komplett belastet, Integration startet nich mehr, etc.

### ISSUE THREAD

**Issue by emufan** [SukramJ/hahomematic#586]
**custom_component version (if applicable):**
irgednwann nach > 1.13.3, war wegen der vielen Updates gestern ich meine auf 1.13.7 gegangen

**known last working custom_component version (if applicable):**
1.13.3

**Home Assistant version (if applicable):**
2022.x.x

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, HA-Addon ...): CCU3
- OS (Original, RaspberryMatic, debmatic ...): Original
- Version: 3.65.6

**Problem-relevant configuration:**

Do you use tls? nein
Do you use callback? nein
Do you use username and password? ja 
Which interfaces do you use (hmip/bidcos/wired)? hmip/bidcos

**Describe the bug**
Ich kann nicht sagen, ob es ein einmaliges Problem war, aber der Zusammenhang des Verhaltens zusammen mit dem Update von 
1.13.3 auf 1.13.7 oder 1.14 und den Updatebeschreibungen des Refaktoring der set_values, etc. traue ich mich nicht, es nochmal zu probieren.

Nach Update und Neustart war noch alles o.k. Dann habe ich eine BROLL-Gruppe versucht, zu schließen. Anstatt dass alle so near-realtime gleichzeitig runtergingen, passierte es in 2-5 Sekunden abständen. Und danach ging gar nichts mehr.

Da ich nicht wusste, woran es liegt, habe ich versucht HA neu zu starten. Dann blieb er komplett beim Laden der Integration hängen. Mehrfach. Nur Restart Host brachte dann was.

Dann habe ich mal lange gewartet und bekam irgendwann die "Interfache nicht erreichbar" Warnungen der Integration. Komisch, dachte ich mir. Login im WebUI klappte ohne Probleme, Steuerung auch. 

Dann zurück auf 1.13.3 (manuell, da ja Start hängen blieb und HACS auch nicht startete) und Reboot. Gleiches verhalten. Blieb weiter hängen und irgendwann kam wieder die "Interface nicht erreichbar"-Meldung.

Daher mal CCU neu gestartet und nun klappte ein Reboot wieder. Aber einige Rollläden waren lange noch unavailable. Weiß nicht, ob da die Integration den DutyCycle gesprengt hatte. Zumindest war das Interface anscheinend komplett belastet oder ddos like beschäftigt, da es nur mit Reboot wieder ging.

Massenöffnen der BROLL heute früh ging wie sonst immer wieder ohne Probleme mit 1.13.3 auf die ich zurückgegangen war.

Ich habe mich nun noch nicht getraut, es nochmal mit 1.13.7 oder 1.14 zu probieren, da das schon ein Akt war, es wieder zum Laufen zu bringen, und mit host-reboot, etc. auch das Risiko der db-Korruption birgt. Daher erst Mal diese Meldung.

BTW Per HACS konnte ich nun auch nicht mehr zurück auf 1.13.3, um es nochmal sauber zu setzen, da es zu viele Updates gestern waren und die Historie beschränkt ist (zumindest bekomme ich es nicht anders hin). Könntest Du bei solch weitreichenden Änderungen evtl. etwas bündeln und nicht 5 Updates am Tag einzeln senden, sodass man im Fall der Fälle zumindest per HACS schnell auf eine funktionierende Version von gestern oder vorgestern kann?

![image](https://user-images.githubusercontent.com/22775515/184294464-ef56823f-5b62-4e2c-85a4-586e9a4bf2ee.png)

**Comment by SukramJ** [comment]
> Könntest Du bei solch weitreichenden Änderungen evtl. etwas bündeln und nicht 5 Updates am Tag einzeln senden, sodass man im Fall der Fälle zumindest per HACS schnell auf eine funktionierende Version von gestern oder vorgestern kann?

Nein.

**Comment by SukramJ** [comment]
Ich nehme das mal zur Kenntnis, aber da ich hier keine relevanten Informationen (u.a. Logs) entnehmen kann, kannst Du das Ticket auch gerne schliessen.

**Comment by SukramJ** [comment]
Vielleicht hilft dir [das](https://hacs.xyz/docs/configuration/options#options).

**Comment by emufan** [comment]
> Nein.

Wirkliches Interesse: Warum? Wie gesagt, es verhindert auf eine Art stable per HACS zurückzukommen (inkl. Versionsinfo, usw.), wenn es so viele Updates an einem Tag gibt und man so noch nicht mal mehr auf gestern zurückkommt.

> Ich nehme das mal zur Kenntnis, aber da ich hier keine relevanten Informationen (u.a. Logs) entnehmen kann, kannst Du das Ticket auch gerne schliessen.

Welche Logs hätte ich denn wie bei so einem Komplettausfall abgreifen können. Ich konnte ja noch nicht mal reproduzieren, weil HA nicht mehr richtig und insb. die Integration gar nicht mehr startete. Und das Restart-Log hatte dann ja sicher nur den Folgefehler "Interface nicht erreichbar" (und Timeout ggf. zu groß.

Ich mach gern in ein paar Tagen wieder zu. Da es aber (wenn wirklich Probleme in einem der Updates von gestern) ggf. noch weitere mit den Problemen geben kann, ist es scher sinnvol dies noch etwas aufzulassen, damit sich hier andere anschließen könnten oder dies als Hilestellung sehen können (CCU neu starten).

> Ich nehme das mal zur Kenntnis, 

Und ohne Log kannst Du nur zur Kenntnis nehmen und nicht mit den Änderungen von gestern gegenchecken, ob eine davon vom Konzept her so etwas ausgelöst haben könnte? Insb. wenn ich Changelog zu 14.1 angucke, wo es ja auch um API-Calls-Reduktion geht, was ja zumindest Thematisch zum obigen Verhalten mit den Rollladen-Aktoren passt (Dauer zwischen mehreren Schaltungen, CCU-Überlastung).

**Comment by SukramJ** [comment]
Aber bitte richtig lesen:
- Es wurde der Service `set_device_value` refactored.
- es wurden die api-calls bei light reduziert und nicht bei cover
- 1.14.1 wurde heute morgen veröffentlicht und kann daher auch nicht für dein Problem relevant sein.

**Comment by SukramJ** [comment]
> Wirkliches Interesse: Warum? Wie gesagt, es verhindert auf eine Art stable per HACS zurückzukommen (inkl. Versionsinfo, usw.), wenn es so viele Updates an einem Tag gibt und man so noch nicht mal mehr auf gestern zurückkommt.

Wie gesagt HACS Doku lesen.

**Comment by SukramJ** [comment]
Zwischen [1.13.3 und 1.13.7](https://github.com/danielperna84/custom_homematic/compare/1.13.3...1.13.7) wurde die backend lib nicht gändert (Bump hahomematic), die für die Gerätekommunikation zuständig ist.
Der `set_device_value` und der neue `set_device_value_raw` verwenden die gleiche Codebasis aber setzten bei Ausführung nur einen einzigen Call ab. Die Nutzung der Services erfolgt ausschliesslich durch Benutzer erstellten Code.
Beim Rest geht die korrekte Anzeige von `device_classe`s.

Ich gehe also davon aus, das es sich um ein einmaliges Problem auf deiner Umgebung handelt.

**Comment by emufan** [comment]
Ich habe mich nun mal wieder an ein Update getraut und bin nun direkt auf 1.14.2 und habe die Zwischenversionen nicht mehr probiert. Bislang kam das Verhalten nicht wieder vor. Wenngleich mir die Reaktionszeiten bei Massenschaltungen dennoch etwas langsamer vorkommen als früher. Kann aber auch an einem der letzten HA-Punkt-Updates liegen. Daher schließe ich erst mal.
