### ISSUE TITLE
no devices after crash and re-install "HomematicIP (local)" - old entities still there, but no devices

### ISSUE THREAD

**Issue by bsafh** [SukramJ/hahomematic#588]
DONT'T DELETE THIS.

**Is your feature request related to a problem? Please describe.**
I had to reinstall the custom_component (via HACS) after a crash of the host in wich the virtual machine is running
HA supervised on debian in qemu machine
RaspberryMatic as AddOn in HA (docker container)

Home Assistant 2022.8.4
Supervisor 2022.08.3
Frontend 20220802.0 - latest

RaspberryMatic Firmware 3.63.9.20220521 (in Docker, Addon in HA)
RaspberryMatic CCU
Current version: 3.63.9.20220521
Identifying Homematic RF-Hardware: ......HmRF: RPI-RF-MOD/HB-RF-ETH@192.168.80.31, HmIP: RPI-RF-MOD/HB-RF-ETH@192.168.80.31, OK
Updating Homematic RF-Hardware: RPI-RF-MOD: 4.4.22, not necessary, OK

Homematic(IP) local cusum component installed via HACS: version 1.14.2

After reinstalling the custom component, alle HM-DEVICES are gone. 
The old entities from before the re-install are still there under entities, though.

**Describe the solution you'd like**

I would like to be able to "re-discover" all devices from RaspberryMatic into HA.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/106388187/184552728-d24994b9-bd33-48b2-9aef-fb60696fc0cd.png)
![image](https://user-images.githubusercontent.com/106388187/184552755-ea513808-808f-40d9-9513-be4fab842a01.png)

force the custom componetn to re-import all devices and entities from RaspBerryMatic

Logger: hahomematic.central_unit
Source: runner.py:119
First occurred: 21:39:32 (136 occurrences)
Last logged: 21:56:22

check_connection: No clients exist. Trying to create clients for server RaspberryMatic
_create_clients: Interface: BidCos-RF is not available for backend.
_create_clients: Interface: VirtualDevices is not available for backend.
_create_clients: Interface: HmIP-RF is not available for backend.

**Comment by SukramJ** [comment]
Duplicate #589
