### ISSUE TITLE
Setup failed for button: Integration not found. 

### ISSUE THREAD

**Issue by Lemocin** [SukramJ/hahomematic#60]
When i start Home Assistant with this integration enabled i get the error: 
![grafik](https://user-images.githubusercontent.com/4162496/143892709-461e2a18-c867-40f7-a284-5aa582723766.png)
But everything i tried, seems to work like it should, so no loss in functionality for me. 
In the logs, there is only the same message. I tried to re-setup the integration but that didn't remove this message. 

I'm using hahomematic 0.0.12, Home Assistant core-2021.11.5 and piVCCU 3.59.6-59

**Comment by SukramJ** [comment]
platform button will be available with HA 2021.12.x

**Comment by Lemocin** [comment]
Confirmed working (tested with virtual Buttons) in HA core-2021.12.0b0. Thanks
![grafik](https://user-images.githubusercontent.com/4162496/144722359-cf16b539-f47c-4093-9127-c2686552b2c5.png)
