### ISSUE TITLE
System variables are not available anymore - disabled

### ISSUE THREAD

**Issue by hklages** [SukramJ/hahomematic#601]
DONT'T DELETE THIS.

Please answer all questions as good as possible.

Language: english

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you have read the release notes at https://github.com/danielperna84/custom_homematic/releases. 

Make sure you are running the latest version of the custom_component (and Home Assistant) before reporting an issue.

**custom_component version (if applicable):**
1.16.0

**known last working custom_component version (if applicable):**
dont know - I guess last week was ok

**Home Assistant version (if applicable):**
2022.8.6

**CCU version:**
- HA-Addon
- OS RaspberryMatic
- Version: newest

**Problem-relevant configuration:**

Do you use tls? No
Do you use callback? No
Do you use username and password? Yes
Which interfaces do you use (hmip/bidcos/wired)? Only Hmip

**Describe the bug**
For some month I have been using two system variables: MyServiceMessages, LastBootTime - both declared as character string with "hahm" in description. The sensors are sensor.raspberrymatic_sv_lastboottime, .. Everything worked fine. 
Now the sensors are disabled - dont know why that changed. 

I am able to enable them but it seems that then there is a reload of the whole integration and the sensors are again disabled.

**Comment by SukramJ** [comment]
There is no need to declare character strings with `hahm`. There is no extended version of this.
Remove the hahm and everything should be fine.

**Comment by hklages** [comment]
Thanks - that works.
