### ISSUE TITLE
Target selector not in UI for services.

### ISSUE THREAD

**Issue by kwithus** [SukramJ/hahomematic#603]
DONT'T DELETE THIS.

Please answer all questions as good as possible.

Language: english/german

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you have read the release notes at https://github.com/danielperna84/custom_homematic/releases. 

Make sure you are running the latest version of the custom_component (and Home Assistant) before reporting an issue.

**custom_component version (if applicable):**
1.16.0

**known last working custom_component version (if applicable):**
last known working HA version is 2022.7.7

**Home Assistant version (if applicable):**

Home Assistant 2022.8.5
Supervisor 2022.08.3
Operating System 8.5
Frontend 20220802.0 

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, HA-Addon ...):
- OS (Original, RaspberryMatic, debmatic ...):
- Version: 
- Homematic Blue

**Problem-relevant configuration:**

Do you use tls?
Do you use callback?
Do you use username and password?
Which interfaces do you use (hmip/bidcos/wired)?

**Describe the bug**
When I use the service homematic.switch_on_time in an automation, I cannot select the entity in the UI, I have to add it via yaml

**To Reproduce**

**Screenshots (if applicable)**
- CCU firewall
- integrations view
- device view
- enity view

**Relevant HA log entries (full log)**
```


```

**Diagnostic Information (available on every device)**
```


```

**Expected behavior**

**Additional context**

**Comment by SukramJ** [comment]
Please update your used versions. latest is not helpful.

**Comment by kwithus** [comment]
Sorry, just updated
Here are two screenshots, one from ui, one from yaml
![2481E0E1-77D5-4C2B-97A1-D7BC563862DD](https://user-images.githubusercontent.com/20025320/186364330-525cf9a5-9fe4-42f4-9ae6-1cab8e9f02d5.png)
![48C38449-A49F-4F39-B0D6-E9BE170C7BC2](https://user-images.githubusercontent.com/20025320/186364342-731521fb-a2be-484f-9c0a-68d45379eace.png)

**Comment by kwithus** [comment]
Just installed 1.16.1 and double checked, still the same

**Comment by SukramJ** [comment]
Yes, i can confirm this issue with HA starting with 2022.8.0.
I don't know if it is planned to remove targets from service calls or just a bug.
As long as i haven't figured out this, i will not fix this.

**Comment by kwithus** [comment]
Ok, as long as you know about it, I am sure you will solve it somehow appropriately.
Nothing that makes big problem.
Thanks 

Von meinem iPad gesendet

**Comment by SukramJ** [comment]
Looks like the target selector does no longer accept the integration as key.

1.16.2 should fix it.

**Comment by kwithus** [comment]
1.16.2 did fix it! Thanks
