### ISSUE TITLE
Missing 'select' entities

### ISSUE THREAD

**Issue by dieterguenter** [SukramJ/hahomematic#606]
Hi,
I started to use hahomematic with version 1.13. This version provided 'select' entities in Home Assistant for the switchover between heating and cooling for my floor-heating-controllers HmIPW-Falmot-C12. Those entities disappeared (but I'm not sure if it was with version 1.14 or 1.15). I have checked all entities, even the deactivated entities and can't find an aquivalent. Only sensor entities are available now to read the heating/cooling state. Any idea why the situation is different now and how to get the possiblity to switch from heating to cooling and vice versa. Thanks in advance.
Regards Dieter

**Comment by SukramJ** [comment]
> DONT'T DELETE THIS.
Please answer all questions as good as possible.

Any idea why I write this?
Please fill out the issue template you deleted.

**Comment by dieterguenter** [comment]
Sorry for the inconvenience. Hope the information is sufficient now.


DONT'T DELETE THIS.

Please answer all questions as good as possible.

Language: english/german

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you have read the release notes at https://github.com/danielperna84/custom_homematic/releases. 

Make sure you are running the latest version of the custom_component (and Home Assistant) before reporting an issue.


**custom_component version (if applicable):**
1.15.x

**known last working custom_component version (if applicable):**
1.13.x

**Home Assistant version (if applicable):**
2022.8.x

**CCU version:**
- Model CCU3
- RaspberryMatic
- Version: 3.65.6.20220723

**Problem-relevant configuration:**

Do you use tls? No.
Do you use callback? No.
Do you use username and password? yes, but never changed them.
Which interfaces do you use (hmip/bidcos/wired)? Only wired HmIPW-Falmot-C12 and HmIPW-WTH.

**Describe the bug**
I started to use hahomematic with version 1.13. This version provided 'select' entities in Home Assistant for the switchover between heating and cooling for my floor-heating-controllers HmIPW-Falmot-C12. Those entities disappeared (but I'm not sure if it was with version 1.14 or 1.15). I have checked all entities, even the deactivated entities and can't find an aquivalent. Only sensor entities are available now to read the heating/cooling state.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'integration'
2. Click on entities on Raspberrymatic CCU3 Webui
3. Look for 'select' entities 
4. Try to find 'select.xxxx_heating_cooling'

**Screenshots (if applicable)**

**Relevant HA log entries (full log)**
Can't provide a log for unavailable entities.

**Diagnostic Information (available on every device)**
Can't provide diagnostic information.

**Expected behavior**
Im looking for a solution to switchover between heating and cooling in Home Assistant with the newer versions of hahomematic.

**Additional context**
Add any other context about the problem here.

**Comment by SukramJ** [comment]
Much better. Please add screenshots of you device in HA.

**Comment by dieterguenter** [comment]
That's my problem. How to show a screenshot of something which is missing? Do you expect me to reinstall an older version of home assistant and hahomematic? The only thing you would see are entities like 'select.[name of floor heating controller]_heating_cooling' providing the switcover between heating and cooling. And those entities or equivalent entities are no longer available in newer versions of hahomematic.
Nevertheless thanks for your incredible work for hahomematic.

**Comment by SukramJ** [comment]
Not the entity I want the **device** page

**Comment by dieterguenter** [comment]
![grafik](https://user-images.githubusercontent.com/73520115/187041315-fd615f76-8528-4c09-8d66-b182ea7df58a.png)

**Comment by SukramJ** [comment]
... click on the device and make a screenshot.

**Comment by SukramJ** [comment]
No more data needed.
Will be fixed in a future release.

**Comment by dieterguenter** [comment]
Thanks a lot. Tell me, if you need any further help.
