### ISSUE TITLE
Actual Temperature Entität ist nicht verfügbar.

### ISSUE THREAD

**Issue by trytogetme85** [SukramJ/hahomematic#611]
**custom_component version (if applicable):**
1.16.4

**Home Assistant version (if applicable):**
2022.8.7

**CCU version:**
RaspberryMatic 3.65.6

**Problem-relevant configuration:**

Hallo,
ich nutzte vor der Umstellung auf Raspberry Matic den HomematicIP Accesspoint. Nun hat die Raspy.
Das Problem ist, dass ich die Temperatur der Heizkörper nicht mehr auslesen kann mit Homeassistant. Die normalen Thermostat-Dinger zeigen die Temperatur aber korrekt an. Ich nutzte aber die Temp-Sensoren bisher um sie in einer Raumübersicht anzuzeigen. Dies geht nicht mehr. Die Geräte zeigen auch allesamt an, dass die "ActualTemperature" Entität nicht verfügbar wäre.
https://imgur.com/a/UqbqR4W

**Comment by SukramJ** [comment]
Es sollte reichen die Entität unter erweiterte Einstellungen zu aktivieren.

**Comment by trytogetme85** [comment]
Erweiterte Einstellungen? Von Was? Wo?

**Comment by SukramJ** [comment]
Was siehst Du auf deinem Screenshot?

**Comment by trytogetme85** [comment]
OMG, ich habs übersehen. Du hast recht. Das Problem ist damit gelöst :) Vielen Dank
