### ISSUE TITLE
Thermostat low_battery is false while there is a low battery service message in RaspberryMatic

### ISSUE THREAD

**Issue by multiholle** [SukramJ/hahomematic#612]
**custom_component version (if applicable):**
1.16.4

**known last working custom_component version (if applicable):**
---

**Home Assistant version (if applicable):**
2022.8.7

**CCU version:**
- HA-Addon
- RaspberryMatic 3.65.8.20220831

**Problem-relevant configuration:**
14 Homematic devices connected usin bidcos

**Describe the bug**
The RaspberryMatic WebUI displays a low battery service message for one of my HM-CC-RT-DN thermostats but the low_battery sensor in Home Assistant is false.

**To Reproduce**
HM-CC-RT-DN with a low voltage of 2.3 V

**Screenshots (if applicable)**
<img width="1074" alt="Screenshot 2022-09-02 at 20 16 56" src="https://user-images.githubusercontent.com/5654539/188263392-c22e7f8f-4cdb-4a34-8ed3-f8aba720cb92.png">
<img width="1080" alt="Screenshot 2022-09-02 at 20 17 06" src="https://user-images.githubusercontent.com/5654539/188263396-b51500f7-aa35-4c87-98b1-33eadc88c56c.png">
<img width="676" alt="Screenshot 2022-09-02 at 20 17 19" src="https://user-images.githubusercontent.com/5654539/188263401-ecf07a26-7e72-4e88-ab41-b449f0f079ad.png">

**Expected behavior**
The Home Assistant low_battery sensor is true when there is a low battery service message in RaspberryMatic.

**Comment by SukramJ** [comment]
If you click on on the entity and open attributes, what is display as value state?

**Comment by SukramJ** [comment]
In CCU WebUI:
If you hover over the column "Letzte Änderung", what is the message of the warning?

**Comment by multiholle** [comment]
> If you click on on the entity and open attributes, what is display as value state?
<img width="1072" alt="Screenshot 2022-09-03 at 18 02 15" src="https://user-images.githubusercontent.com/5654539/188278828-ac3f0c25-47b1-4dc4-9945-a96a97c25d1e.png">


> In CCU WebUI:
> If you hover over the column "Letzte Änderung", what is the message of the warning?
<img width="195" alt="Screenshot 2022-09-03 at 18 04 06" src="https://user-images.githubusercontent.com/5654539/188278851-b613e7ee-4fb9-4a05-92eb-2553e7c85b80.png">


I noticed that you can set the low battery voltage in the settings of the thermostat. It's set to 2.1 V wich is below the current reading of 2.3 V.
<img width="818" alt="Screenshot 2022-09-03 at 18 04 42" src="https://user-images.githubusercontent.com/5654539/188278865-24556d50-e497-4b44-8b90-31aaa4e74628.png">


Also in the last ours the voltage dropped to 2.1 V for some time and the low_battery sensor came on. Also there was a second "Servicemeldung" in the CCU for the low_battery threshold. So it seems to be working as intended. The only weird thing is that there is already an alert even when battery voltage is above the threshold.

**Comment by multiholle** [comment]
This is how it looks when the battery sensor in Home Assistant comes on. I'd say it's working as intended but the CCU is behaving weird?
<img width="1323" alt="image" src="https://user-images.githubusercontent.com/5654539/188279356-8411a71c-fe6b-44be-8b2a-1704332abc7f.png">
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/5654539/188279376-20286728-6f74-4543-a28a-9fb9f0b3450d.png">

**Comment by SukramJ** [comment]
I think there is nothing i could do or should do.
We depend on the CCU to generate events, that we receive.

When it comes to _secondary entities_ like `LOW_BAT` and `RSSI` especially with Bidcos devices the behaviour could be sometimes confusing as already found in #549.

Additional info can be found [here](https://github.com/danielperna84/custom_homematic#noteworthy-about-entity-states).
Maybe [this](https://github.com/danielperna84/custom_homematic#homeassistantupdate_entity) could be interesting.

**Comment by multiholle** [comment]
Yeah, I think you're right. Thanks. This issue can be closed.

SukramJ ***@***.***> schrieb am Sa., 3. Sept. 2022, 22:04:
