### ISSUE TITLE
setting state update interval of homematic variables (without delay)

### ISSUE THREAD

**Issue by ml8300** [SukramJ/hahomematic#613]
Hello,
at the moment I try to find out, how I get some variables (from CCU3) to HA without delay.
I already red about events but it dosn´t work. Also I tried to get a possibility to set "hahm".

Detailed 
Is there a possibility, to priorize some HM variables or set a small state intervall?

Thanks a lot, really good integration, I like it because a lot of my smart devices are running on ccu3.

DONT'T DELETE THIS.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SukramJ** [comment]
Without delay will never be possible, because these Sysvars have to be fetched from CCU.
These Sysvars are all fetched in one call so priorisation makes now sense.

If you need an immediate notification you could use the virtual remotes (HM-RCV-50/HmIP-RCV-50) via XXX_PRESS Events.
