### ISSUE TITLE
Systemvariablen aktualisieren sich in HA nicht

### ISSUE THREAD

**Issue by kaitomalik** [SukramJ/hahomematic#614]
DONT'T DELETE THIS.

Please answer all questions as good as possible.

Language: english/german

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you have read the release notes at https://github.com/danielperna84/custom_homematic/releases. 

Make sure you are running the latest version of the custom_component (and Home Assistant) before reporting an issue.

**custom_component version (if applicable):**
1.16.4

**known last working custom_component version (if applicable):**
1.x.x

**Home Assistant version (if applicable):**
2022.8.7

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, HA-Addon ...): CCU3
- OS (Original, RaspberryMatic, debmatic ...): original
- Version: 3.65.8

**Problem-relevant configuration:**

Do you use tls? Nein
Do you use callback? Nein 
Do you use username and password? Ja
Which interfaces do you use (hmip/bidcos/wired)? hmip

**Describe the bug**
Seit dem letzten Update auf 1.16.4 aktualisieren sich bei mir die Systemvariablen in Home Assistant nicht mehr.
Ich kann mit dem Dienst "Homematic(IP) Local: Set variable value" die Variablen in der CCU ändern, in Homeassistant bleiben sie unverändert. 
Seit welcher Version das genau ist weiß ich nicht, kann sein das ich 2-3 Versionen übersprungen habe.

**To Reproduce**

**Screenshots (if applicable)**

**Relevant HA log entries (full log)**
```


```

**Diagnostic Information (available on every device)**
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.8.7",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "5.15.32-v8",
    "supervisor": "2022.08.5",
    "host_os": "Home Assistant OS 8.5",
    "docker_version": "20.10.14",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "homematicip_local": {
      "version": "1.16.4",
      "requirements": [
        "hahomematic==2022.9.0"
      ]
    },
    "gardena_smart_system": {
      "version": "1.0.0",
      "requirements": [
        "py-smart-gardena==1.3.7"
      ]
    },
    "alexa_media": {
      "version": "4.1.0",
      "requirements": [
        "alexapy==1.26.1",
        "packaging>=20.3",
        "wrapt>=1.12.1"
      ]
    },
    "hacs": {
      "version": "1.27.1",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "dwd_weather": {
      "version": "1.2.23",
      "requirements": [
        "simple_dwd_weatherforecast==1.1.5",
        "markdownify==0.6.5"
      ]
    },
    "spotcast": {
      "version": "v3.6.29",
      "requirements": [
        "spotify_token==1.0.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "homematicip_local",
    "name": "Homematic(IP) Local",
    "config_flow": true,
    "documentation": "https://github.com/danielperna84/custom_homematic",
    "issue_tracker": "https://github.com/danielperna84/hahomematic/issues",
    "requirements": [
      "hahomematic==2022.9.0"
    ],
    "ssdp": [
      {
        "manufacturer": "EQ3",
        "manufacturerURL": "http://www.homematic.com"
      }
    ],
    "zeroconf": [],
    "homekit": {},
    "dependencies": [],
    "codeowners": [
      "@danielperna84",
      "@SukramJ"
    ],
    "iot_class": "local_push",
    "loggers": [
      "hahomematic"
    ],
    "version": "1.16.4",
    "is_built_in": false
  },
  "data": {
    "config": {
      "entry_id": "8a27e6afefb30428a02e466e73611425",
      "version": 1,
      "domain": "homematicip_local",
      "title": "ccu3-webui",
      "data": {
        "instance_name": "**********",
        "host": "192.168.*.*",
        "username": "**REDACTED**",
        "password": "**REDACTED**",
        "tls": false,
        "verify_tls": false,
        "callback_host": null,
        "callback_port": null,
        "json_port": null,
        "interface": {
          "HmIP-RF": {
            "port": 2010
          },
          "BidCos-RF": {
            "port": 2001
          }
        }
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "ssdp",
      "unique_id": "************",
      "disabled_by": null
    },
    "platform_stats": {
      "binary_sensor": 72,
      "button": 5,
      "cover": 5,
      "light": 3,
      "lock": 1,
      "number": 7,
      "select": 4,
      "sensor": 16,
      "siren": 1,
      "switch": 6
    },
    "devices": [
      "HMIP-SWDO",
      "HmIP-ASIR-2",
      "HmIP-BROLL",
      "HmIP-BSL",
      "HmIP-DLD",
      "HmIP-DSD-PCB",
      "HmIP-FDT",
      "HmIP-FROLL",
      "HmIP-FWI",
      "HmIP-HAP",
      "HmIP-KRCA",
      "HmIP-MP3P",
      "HmIP-PCBS",
      "HmIP-RC8",
      "HmIP-RCV-50",
      "HmIP-SLO",
      "HmIP-SMI",
      "HmIP-STE2-PCB",
      "HmIP-SWD",
      "HmIP-SWDO-I",
      "HmIP-WRC6"
    ]
  }
}

```

**Expected behavior**
A clear and concise description of what you expected to happen.

**Additional context**
Add any other context about the problem here.

**Comment by SukramJ** [comment]
1. Bist Du sicher das die Änderung in der CCU ankommt?
2. Um was für SysVars (Typ, mit/ohne hahm ) handelt es sich?

**Comment by SukramJ** [comment]
Ich habe das jetzt für diverse Typen getestet, und die **Änderungen** kommen spätestens nach 30s an.

**Comment by kaitomalik** [comment]
1. ja, per Dienst gehen die Änderungen unverzögert an die CCU, HA ändert sich nicht
2. Typ Logicwert ohne hahm

![image](https://user-images.githubusercontent.com/65624148/188500314-44352a25-087b-4f25-9ca9-cec55afbd820.png)

- Typ Werteliste wird an Home Assistant übertragen sie der Wert ändert, da besteht das Problem nicht

**Comment by SukramJ** [comment]
Für _Logicwert ohne hahm_ kann ich das Problem nachvollziehen.

**Comment by kaitomalik** [comment]
![image](https://user-images.githubusercontent.com/65624148/188501717-f7070500-70d6-45b5-8197-9d112279070a.png)

Gerade nochmal eine neue Variable erstellt. siehe Screenshot

Mit hahm geht's bei mir auch, aber dann als Schalter.

**Comment by SukramJ** [comment]
Version 1.16.5 sollte das Problem beheben.

**Comment by kaitomalik** [comment]
Problem mit Version 1.16.5 behoben - Danke!
