### ISSUE TITLE
No switch entity for the devices HM-LC-Sw1-FM and HM-LC-Sw1PBU-FM

### ISSUE THREAD

**Issue by centertivevier** [SukramJ/hahomematic#617]
custom_component/hahomematic version (if applicable):
1.16.5 

Home Assistant version (if applicable):
2022.9.2 latest tested version 

CCU version:

    Model Raspi3/4
    OS RaspberryMatic
    Version: 3.65.8.20220831

Describe the bug
I integraded new devices from the type HM-LC-Sw1-FM and HM-LC-Sw1PBU-FM to my Raspberrymatic. Homeassistant see this new device, but the haven't created a "switch" entity for this one.

I think the problem since solved this issue [Issue 445](https://github.com/danielperna84/hahomematic/issues/445)

**Comment by SukramJ** [comment]
Why do you think it is related to the Issue you mentioned?

**Comment by centertivevier** [comment]
I has integrated a HM-LC-Sw1-FM before this issue solved

![Vor dem Update](https://user-images.githubusercontent.com/27358890/190467786-cd298bca-7c40-447b-b107-41688793d1ba.png)

On this one, i see the switch state. 

On the new one from september, there is no switch state.

![Nach dem Update](https://user-images.githubusercontent.com/27358890/190467782-ac2329cf-629c-4aaa-8bf2-099395903469.png)

Its a presumption from me.

**Comment by SukramJ** [comment]
I don‘t think so. The switch is still available for my HM-LC-Sw1-FM.

Use the Service `Homematic(IP) Local: Delete a device` and restart HA afterwards.

**Comment by centertivevier** [comment]
I want use the service`Homematic(IP) Local: Delete a device`, but there found not the device! So i have check the paramsets.json from the cache of the plugin and compare with the old device on this one. There was many parameters not available for the new one.

I  use the `homematicip_local.clear_cache` and restart HA. After the restart of HA were published the not available parameters how the switch state.

Thanks for the food of thought :-)
