### ISSUE TITLE
HACS integration - Failed to connect

### ISSUE THREAD

**Issue by Raylands** [SukramJ/hahomematic#618]
DONT'T DELETE THIS.

Please answer all questions as good as possible.

Language: english/german

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you have read the release notes at https://github.com/danielperna84/custom_homematic/releases. 

Make sure you are running the latest version of the custom_component (and Home Assistant) before reporting an issue.

**custom_component version (if applicable):**
1.16.5

**known last working custom_component version (if applicable):**
-

**Home Assistant version (if applicable):**
2022.9.4

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, HA-Addon ...): HA-Addon in a HA OS VM in Unraid
- OS (Original, RaspberryMatic, debmatic ...): RaspberryMatic CCU
- Version: 3.65.8.20220831 

**Problem-relevant configuration:**

Do you use tls? No, but tried
Do you use callback? No
Do you use username and password? Yes, even changed the password for the "Admin" user
Which interfaces do you use (hmip/bidcos/wired)?

**Describe the bug**
No matter what configuration I choose, the integartion can't connect to the installed RaspberryMatic CCU.

**To Reproduce**
![image](https://user-images.githubusercontent.com/43676611/190703480-f9254028-593c-4d93-92b0-0185565bc74a.png)

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/43676611/190703620-d476a1d5-3793-4c95-b6ed-5268534a1e25.png)

**Relevant HA log entries (full log)**
```
2022-09-16 19:51:12.726 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-09-16 19:51:12.727 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration homematicip_local which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-09-16 19:52:58.811 WARNING (MainThread) [custom_components.homematicip_local.config_flow] Unable to connect (<ProtocolError for de838cd8-raspberrymatic:2001/RPC2: 503 Service Unavailable>,).
```

**Diagnostic Information (available on every device)**
![image](https://user-images.githubusercontent.com/43676611/190703925-9a538c76-655f-4e7f-ad50-4ea417d3e3d1.png)

**Expected behavior**
Homematic(IP) local can connect to RaspberryMatic CCU

**Additional context**

**Comment by SukramJ** [comment]
Is you RM AddOn healthy?
Please add the logs of the addon.

**Comment by ghildebrandt** [comment]
Hey, i get the same error. Tried this integration on my RPI4 and even installed a new HA to a VM and still get the same error.

**Comment by SukramJ** [comment]
Do you perhaps also have useful information such as the addon logs, for example?

**Comment by Raylands** [comment]
> Is you RM AddOn healthy?

Yes, it is. Working as intended.

> Please add the logs of the addon.

There is nothing in there. That's why I didn't sent it.
```Mounting /data as /usr/local (Home Assistant Add-On): OK
Identifying host system: oci, OK
Initializing RTC Clock: onboard, OK
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Initializing System: OK
Setup ca-certificates: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.0, OK
Identifying Homematic RF-Hardware: ....HmRF: n/a, HmIP: HMIP-RFUSB-TK/eQ-3 HmIP-RFUSB@usb-0000:00:07.0-2, OK
Updating Homematic RF-Hardware: HMIP-RFUSB-TK: 4.2.14, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: not required
Starting rfd: no BidCos-RF hardware found
Starting HMIPServer: ........OK
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting NeoServer: disabled
Starting Third-Party Addons: OK
find: /usr/local/etc/monit*.cfg: No such file or directory
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.65.8.20220831 (raspmatic_oci_amd64)```

**Comment by SukramJ** [comment]
Check the hostname with the hostname on the addon page.
Is `de838cd8-raspberrymatic` correct?

**Comment by Raylands** [comment]
Yes, as you can see in the last screenshot the name resolves correctly and the ports are open.

**Comment by SukramJ** [comment]
Try to set the `Remote Homematic-Script API` to full access. Maybe an addon restart is required.
Do you have any special characters in your password like `#`?

**Comment by Raylands** [comment]
> Try to set the `Remote Homematic-Script API` to full access. 

Didn't fix it.

> Maybe an addon restart is required.

Restarted the addon and VM multiple times. Even reinstalled all addons.

> Do you have any special characters in your password like `#`?

Nope, even tested "123"

**Comment by SukramJ** [comment]
`ProtocolError for de838cd8-raspberrymatic:2001/RPC2: 503 Service Unavailable`

Basically means that this a communication problem to the CCU.

@baxxy13 Do you have any idea?

**Comment by SukramJ** [comment]
Did you select Bidcos on the second page?
Bidcos is not supported by your stick.

**Comment by Raylands** [comment]
Oh wow. I was only looking for the compatibility on the base stick and didn't realize there is a difference between the OEM and Telekom one...
Thanks, I really did overlook this. 😅

If anyone else is ever wondering:
![image](https://user-images.githubusercontent.com/43676611/190733075-579ffa74-c99d-42ba-b901-2d01458e327c.png)

**Comment by JoMass** [comment]
Just updatet to HAS Operating System 9.0  and I'm getting the message 

HOMEMATICIP_LOCAL-Interface not reachable
No connection to interface hsccumass2-HmIP-RF

sam issue ?

**Comment by Baxxy13** [comment]
> Bidcos is not supported by your stick.

You already solved it.
No BidCosRF with the -TK Stick.
See: [Link](https://github.com/jens-maus/RaspberryMatic/issues/1934#issuecomment-1239849237)

**Comment by JoMass** [comment]
Did not change HW just updated to HAS OS 9-0 . seems to be a different issue.

**Comment by Baxxy13** [comment]
> sam issue ?

[https://github.com/jens-maus/RaspberryMatic/issues/1942](https://github.com/jens-maus/RaspberryMatic/issues/1942)

**Comment by JoMass** [comment]
Thank you Baxxy13
