### ISSUE TITLE
Duty Cycle Level CCU

### ISSUE THREAD

**Issue by kaitomalik** [SukramJ/hahomematic#619]
DONT'T DELETE THIS.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Ich vermisse einen Sensor mit dem ich Duty Cycle Level der CCU in HA anzeigen lassen kann, wie vom HMIP-HAP. 

![image](https://user-images.githubusercontent.com/65624148/190730100-7961f387-8400-422d-af9e-17db8a6296ee.png)
![image](https://user-images.githubusercontent.com/65624148/190733163-a89e8bd4-9178-4c9e-9a6c-cde1f8edd65a.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by SukramJ** [comment]
Unter RM gibt es ein Gerät vom Typ RPI-RF-MOD (Funkmodul), das diese Sensoren enthält.
Ich weiß aber nicht ob die Original CCU das auch anzeigt.

**Comment by SukramJ** [comment]
Für die CCU gibt es eventuell eine Systemvariable (deaktiviert), die den gewünschten Wert enthält.

**Comment by kaitomalik** [comment]
Hab nochmal alle Variablen durchgesehen und aktiviert, nichts passendes gefunden.

**Comment by SukramJ** [comment]
Was für eine CCU nutzt Du genau (inkl. SW Version)

**Comment by kaitomalik** [comment]
originale CCU3 
3.65.8

**Comment by SukramJ** [comment]
@emufan Nutzt Du nicht auch eine CCU3?

Hast Du einen Sensor für den `Duty Cycle` bzw. `Duty Cycle Level`?

**Comment by emufan** [comment]
Ja, [CCU3](https://github.com/danielperna84/hahomematic/discussions/127), 

Und ja, SV ist vorhanden.

![image](https://user-images.githubusercontent.com/22775515/190866492-98e1fabd-3c9d-4718-98a1-226ba4c798ce.png)
 
@kaitomalik Sicher, dass Du sie nicht einfach noch deaktiviert gelassen hast?

**Comment by Lemocin** [comment]
Hi, ich habe eine pivCCU 3, hier ist auch kein Duty Cycle vorhanden:
![grafik](https://user-images.githubusercontent.com/4162496/190869405-e35203c2-eae4-4633-a5ae-737a5cab2c30.png)

**Comment by SukramJ** [comment]
@Lemocin 
Aber Du hast ein Gerät vom Typ ein Gerät vom Typ RPI-RF-MOD (Funkmodul), sofern du ein grosses Funkmodul benutzt?

**Comment by Lemocin** [comment]
Nein, ich habe das kleine Funkmodul HM-MOD-RPI-PCB. Dafür wird kein Gerät erstellt.

**Comment by SukramJ** [comment]
Das kleine Funkmodul hat keinen eigenen Geräteeintrag, ist also so zu erwarten.

**Comment by Lemocin** [comment]
Also gibts bei meinem Setup keine Möglichkeit den Duty Cycle auszulesen? Also ich brauche es nicht, ist mir nur aufgefallen als ich den Issue hier gelesen habe.

**Comment by SukramJ** [comment]
Kauf dir ein grosses Funkmodul oder den HmIP USB Stick.

Solange die CCU oder das Derivat von sich aus kein Gerät anlegt, oder eine Sysvar schreibt, kann ich da nichts machen.

**Comment by kaitomalik** [comment]
> Ja, [CCU3](https://github.com/danielperna84/hahomematic/discussions/127),
> 
> Und ja, SV ist vorhanden.
> 
> ![image](https://user-images.githubusercontent.com/22775515/190866492-98e1fabd-3c9d-4718-98a1-226ba4c798ce.png)
> 
> @kaitomalik Sicher, dass Du sie nicht einfach noch deaktiviert gelassen hast?

Ja, eigentlich schon. So sieht es bei mir aus.

![image](https://user-images.githubusercontent.com/65624148/190895966-f8ac19b4-18a4-49d2-ad1a-73bb253ada6c.png)

**Comment by SukramJ** [comment]
> Solange die CCU oder das Derivat von sich aus kein Gerät anlegt, oder eine Sysvar schreibt, kann ich da nichts machen.

Ich denke das Issue kann geschlossen werden.
Warum keine Sysvar vorhanden ist sollte besser im HomematicForum erfragt werden.

**Comment by emufan** [comment]
@kaitomalik Wobei es mir nun gerade einfällt, dass ich mit die SV anno tuk mal selber angelegt hatte. Daran hatte ich gestern 0,0 gedacht. Sorry. Das einzige Programm, was überhaupt auf der CCU läuft, daher war das komplett in Vergessenheit geraten.

Nebst 
```
! DutyCycle mit HM Script und system.exec in Systemvariable und Fehlerprotokoll
! v 1.0 (c) by Alchy
string sysvar = "STATUS_DUTYCYCLE"; ! Name der als Zahl angelegten Systemvariable, wo ermittelter DutyCycle gespeichert werden soll 
boolean debug = false;
boolean debugzwei = false;
! Finger weg 
string stdout;
string stderr;
integer Return;
string cmd = "/bin/sh -c '" # 'echo "load tclrpc.so; puts [xmlrpc ' # interfaces.Get("BidCos-RF").InterfaceUrl() # ' listBidcosInterfaces ]" |tclsh |grep -o "DUTY_CYCLE.[0-9]*."' # "'";
if(true) {
  Return = system.Exec(cmd,&stdout,&stderr);
    if (debug) {
      WriteLine("Fehler: ");
      WriteLine(stderr);
      WriteLine("Ausgabe: ");
      WriteLine(stdout);
    }
    if (stderr) {
      WriteLine("Fehler bei Abfrage");
    } else {
      if (debugzwei) {
        string sout;
        string serr;
        system.Exec("logger -t script -p user.debug [DutyCycle "#stdout.StrValueByIndex(" ",1).ToString()#"] c DutyCycle mit HM Script und system.exec v 1.0 by Alchy", &sout, &serr);
        if (debug) {
          WriteLine("DutyCycle ["#stdout.StrValueByIndex(" ",1).ToString()#"] by_Alchy"#" ins Fehlerprotokoll eingetragen");
        }
      }
      if (dom.GetObject(ID_SYSTEM_VARIABLES).Get(sysvar)) {
        dom.GetObject(ID_SYSTEM_VARIABLES).Get(sysvar).State(stdout.StrValueByIndex(" ",1).ToFloat()); 
        if (debug) {
          WriteLine("DutyCycle von " #stdout.StrValueByIndex(" ",1).ToFloat()# " ermittelt und in Systemvariable eingetragen");
        }
      } else {
        WriteLine("Systemvariable nicht vorhanden zum eintragen");
      }
    } 
}
```
![image](https://user-images.githubusercontent.com/22775515/190919052-3b1fa0b9-4b08-49e3-bac3-dd7fd1da2be6.png)

![image](https://user-images.githubusercontent.com/22775515/190919016-a1416804-495e-40c1-bf5b-7b709dea8c83.png)

**Comment by kaitomalik** [comment]
@emufan Danke Dir, das schaue ich mir mal an :)
