### ISSUE TITLE
MOD-HO need parameter PROCESS (NOT_STABLE/STABLE)

### ISSUE THREAD

**Issue by Aggro600** [SukramJ/hahomematic#620]
The Parameter shows if the engine is stable oder not.

Details on:
https://homematic-forum.de/forum/viewtopic.php?f=58&t=57959&start=20#p675988

Documentation:
https://www.eq-3.de/Downloads/eq3/download%20bereich/hm_web_ui_doku/HmIP_Device_Documentation.pdf

**Comment by SukramJ** [comment]
Use [this](https://github.com/danielperna84/hahomematic/blob/devel/docs/unignore.md)

The parameter SECTION is used to display (State of entity) if door is opening(5)/closing(2)

**Comment by SukramJ** [comment]
Might be interesting too #286

**Comment by SukramJ** [comment]
I think this can be close.

_Thank you_ for feedback

**Comment by Aggro600** [comment]
Unfortunately I didn't make it in the unignore file.
Does the file have to have the extension .py?
"unignore.py"

**Comment by SukramJ** [comment]
> Does the file have to have the extension .py?

No it's a simple text file and contains no python code.

Follow the doc and it will work.
