### ISSUE TITLE
Various HA Core system log warnings/errors after HA start-up and load of this custom component

### ISSUE THREAD

**Issue by iHaveAstream** [SukramJ/hahomematic#622]
DONT'T DELETE THIS.

Please answer all questions as good as possible.

Language: english/german

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you have read the release notes at https://github.com/danielperna84/custom_homematic/releases. 

Make sure you are running the latest version of the custom_component (and Home Assistant) before reporting an issue.

**custom_component version (if applicable):**
1.16.5

**known last working custom_component version (if applicable):**
Don't remember, however those issues are not there since the beginning for sure.

**Home Assistant version (if applicable):**
2022.9.5

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, HA-Addon ...): CCU3
- OS (Original, RaspberryMatic, debmatic ...): Original
- Version: v3.65.8

**Problem-relevant configuration:**

Do you use tls? > Yes (w/o verification), JSON-RPC Port 443
Do you use callback? > Not configured, shall I? HA is within same subnet as the CCU3 and HA does not run inside Docker, but as real VM on Home Assistant OS v9.0
Do you use username and password? > Yes
Which interfaces do you use (hmip/bidcos/wired)? > HmIP

**Describe the bug**
Since some point (already some months ago), the HA core log throws always the same Warnings/Errors after a restart of HA and when the custom component was loaded.
Apart from those information in the log I cannot yet notice any negative side effects. Everything seems to work well incl. various related automations, etc. 

**To Reproduce**
1. Restart HA
2. Wait until it has fully started
3. Go to Settings > System > Logs
4. See errors/warnings in logs

**Screenshots (if applicable)**
- pls. refer to attached screenshots
![SmartSelect_20220919_204430_Home Assistant](https://user-images.githubusercontent.com/62019393/191095081-8ea47d6c-246f-472f-8270-a7486579eff0.jpg)

**Relevant HA log entries (full log)**
pls. refer to attached full log.
[HA_2022.9.5_full_log_after_start-up.txt](https://github.com/danielperna84/hahomematic/files/9601677/HA_2022.9.5_full_log_after_start-up.txt)

```

**Diagnostic Information (available on every device)**
```

```

**Expected behavior**
A clear and concise description of what you expected to happen.

**Additional context**
Add any other context about the problem here.

**Comment by SukramJ** [comment]
The problem is simple:
You do not read [release notes](https://github.com/danielperna84/custom_homematic/releases/tag/1.0.0) and you are still on  version 0.38.5 (<1.0.0), because `hahm` is still in the package name!


I readed a reduced version of the  [migration plan](https://github.com/danielperna84/custom_homematic/wiki/Migration--from-domain-hahm-to-homematicip_local).

Good luck
