### ISSUE TITLE
homematic_sv_alarmmeldungen is in wrong state

### ISSUE THREAD

**Issue by LinusHoppe** [SukramJ/hahomematic#625]
**custom_component version (if applicable):**
1.16.5

**known last working custom_component version (if applicable):**
-

**Home Assistant version (if applicable):**
 Home Assistant 2022.9.5
Supervisor 2022.09.1
Operating System 9.0
Frontend 20220907.2 - latest 

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, HA-Addon ...): HA-Addon
- OS (Original, RaspberryMatic, debmatic ...): RaspberryMatic 3.65.8.20220831

**Problem-relevant configuration:**

Do you use tls? No
Do you use callback? No
Do you use username and password? Yes
Which interfaces do you use (hmip/bidcos/wired)? HMIP

**Describe the bug**
After the last reboot (updating HA Supervisor & OS) and a restart of RaspberryMatic-Addon, the sensor `sensor.homematic_sv_alarmmeldungen` is on state 1 although there is no alarm message in RaspberryMatic.
Restarting HA, RaspberryMatic or the whole hardware host does not change anything.

**To Reproduce**
Go to developer tools and compare `sensor.homematic_sv_alarmmeldungen` with the `Alarmmeldungen` within RaspberryMatic.

**Screenshots (if applicable)**
![alarmmeldungen](https://user-images.githubusercontent.com/32911160/191233497-4ce4b359-369e-4e75-9d20-6cc357db2d3c.png)
![alarmmeldungen_2](https://user-images.githubusercontent.com/32911160/191233518-6721b437-f633-42a5-b649-55b56ac340b4.png)
![alarmmeldungen_3](https://user-images.githubusercontent.com/32911160/191233525-809f9116-0810-483f-8a9b-30ea71f8545f.png)

**Relevant HA log entries (full log)**
Nothing that points to an error.
```
2022-09-19 08:32:40.381 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration homematicip_local which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-09-19 08:35:35.616 INFO (MainThread) [custom_components.homematicip_local.control_unit] Started ControlUnit for Homematic
```

**Diagnostic Information (available on every device)**
```


```

**Expected behavior**

**Additional context**

**Comment by SukramJ** [comment]
The value of `sensor.homematic_sv_alarmmeldungen` is the value of the sysvar named `alarmmeldungen`.
So check the content of the sysvar on CCU.

I don't know how the CCU's UI element Alarmmeldung correlates to the sysvar `alarmmeldungen`.

**Comment by LinusHoppe** [comment]
You're right - there is some problem with my CCU. In the UI, the "Alarmmeldungen" is zero, but the sysvar `alarmmeldungen` is 1. Have to investigate within the CCU. Thanks!

**Comment by Baxxy13** [comment]
Explanation of this behaviour (only german):
[Alarmmeldung immer größer 0 ?](https://homematic-forum.de/forum/viewtopic.php?f=19&t=63542&p=731652&hilit=alarmmeldungen#p731652)
