### ISSUE TITLE
Automations using HmIP-KRCA disapeared when upgraded to version 1.17.0

### ISSUE THREAD

**Issue by Andzej-Buncol** [SukramJ/hahomematic#626]
Hi,

I'm using HmIP-KRCA to control Alarmo in HA.
After update from 1.16.5 to 1.17.0 I got it the log: "Invalid config for [automation]: Integration 'homematicip_local' does not support device automation triggers".
Temporary downgraded to 1.16.5 and it is working again

How to make buttons from HmIP-KRCA available to control anything?

**Comment by SukramJ** [comment]
If you have a problem, then fillout the issue template!

**Comment by SukramJ** [comment]
BTW: Homematic(IP) Local supports device triggers.
That could easily be tested within an automation.

**Comment by Andzej-Buncol** [comment]
Apologies due to fact that was not aware that 1.17.0 require core 2022.9.x regarding automations

**Comment by SukramJ** [comment]
That's why i always want a filled out issue template!
