### ISSUE TITLE
HmIP-BRC2 devices not selectable within the 2-button blueprint

### ISSUE THREAD

**Issue by lacalamine64** [SukramJ/hahomematic#629]
DONT'T DELETE THIS.

Please answer all questions as good as possible.

Language: english/german

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you have read the release notes at https://github.com/danielperna84/custom_homematic/releases. 

Make sure you are running the latest version of the custom_component (and Home Assistant) before reporting an issue.

**custom_component version (if applicable):**
1.17.0

**known last working custom_component version (if applicable):**
Started using the custom_component with 1.17.0

**Home Assistant version (if applicable):**
2022.9.6

**CCU version:**
- Model: Raspi4
- OS: Home Assistant OS 8.5 with RaspberryMatic-Addon 3.65.8.20220831
- Version: see above

**Describe the bug**
From the 2-button blueprint provided, I'm not able to choose HmIP-BRC2 devices. All others I have seem to be working.

With a custom automation via "Device trigger" I can select HmIP-BRC2 devices and it's working. But that way is a pain for all of them...

**Comment by lacalamine64** [comment]
I need to add that HmIP-BRC2 devices are not selectable in any of the provided blueprints.

**Comment by SukramJ** [comment]
> But that way is a pain for all of them...

How terrible. You have to enable any of the entities of the device.

**Comment by lacalamine64** [comment]
> How terrible.

It is ;)
Thanks a lot
