### ISSUE TITLE
HOMEMATICIP_LOCAL-XmlRPC-Server received no events.

### ISSUE THREAD

**Issue by smartmatic** [SukramJ/hahomematic#630]
DONT'T DELETE THIS.

Please answer all questions as good as possible.

Language: english/german

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you have read the release notes at https://github.com/danielperna84/custom_homematic/releases. 

Make sure you are running the latest version of the custom_component (and Home Assistant) before reporting an issue.

**custom_component version (if applicable):**
1.17.0

**known last working custom_component version (if applicable):**
1.x.x

**Home Assistant version (if applicable):**
2022.9.6

**CCU version:**
- OS: RaspberryMatic
- Version: 3.65.8.20220831

**Problem-relevant configuration:**

Do you use tls?
no
Do you use callback?
no
Do you use username and password?
yes
Which interfaces do you use (hmip/bidcos/wired)?
bidcos

**Describe the bug**
I get multiple times a day this HA notification: 
HOMEMATICIP_LOCAL-XmlRPC-Server received no events.

What triggers this notification?
How to disable it? 

**To Reproduce**

**Screenshots (if applicable)**
- CCU firewall
- integrations view
- device view
- enity view

**Relevant HA log entries (full log)**
```


```

**Diagnostic Information (available on every device)**
```


```

**Expected behavior**

**Additional context**

**Comment by SukramJ** [comment]
Please add the log entry (full log) 

> What triggers this notification?
We EXPECT Events from CCU within 5 minutes. If this is missing, we create a message.

> How to disable it?

Restart CCU?
Restart HA?

**Comment by smartmatic** [comment]
> Please add the log entry (full log)
> 
> > What triggers this notification?
> > We EXPECT Events from CCU within 5 minutes. If this is missing, we create a message.
> 
> > How to disable it?
> 
> Restart CCU? Restart HA?

Restart of neither CCU nor HA doesn‘t help

**Comment by SukramJ** [comment]
Please add the log entry (full log) !!!

**Comment by smartmatic** [comment]
> Please add the log entry (full log) !!!

ok, 
hopefully you can find something?
[Homematic_Log.txt](https://github.com/danielperna84/hahomematic/files/9640767/Homematic_Log.txt)

**Comment by SukramJ** [comment]
Looks like HA does not receive events (Updates) from CCU for  the HmIP Interface.
Check the logs on your CCU.

Are the devices accessible(controllable) from CCU WebUI?

**Comment by smartmatic** [comment]
I think it's a missconfiguration from my side. I do not have HmIP devices. I've reconfigured the HA Integration and checked only the box for port 2001 Bidcos-RF and not for HmIP.

Maybe this solves the issue?

Devices can be controlled from HA and CCU WebUI.

**Comment by SukramJ** [comment]
Yes
