### ISSUE TITLE
Homematic IP (Local) Integration does not show up to be added although it is reported by Home Assistant Logs

### ISSUE THREAD

**Issue by markusdd** [SukramJ/hahomematic#631]
DONT'T DELETE THIS.

Please answer all questions as good as possible.

Language: english/german

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you have read the release notes at https://github.com/danielperna84/custom_homematic/releases. 

Make sure you are running the latest version of the custom_component (and Home Assistant) before reporting an issue.

**custom_component version (if applicable):**
1.17.0
**Home Assistant version (if applicable):**
2022.9.7

**CCU version:**
- Model: HA-Addon
- OS: Original HA OVA image (used on ProxMox)
- Version: 3.65.8.20220831

**Describe the bug**
Despite follwowing the guide https://github.com/jens-maus/RaspberryMatic/wiki/HomeAssistant-Integration
I get stuck at the point where I am supposed to add the Integration to home assitant, the local homematic IP Integration does not show up:
![grafik](https://user-images.githubusercontent.com/25175069/192392715-f0f5108a-5652-4782-8571-bb1638edc5e0.png)

I do not get why, in HACS it shows as installed:
![grafik](https://user-images.githubusercontent.com/25175069/192392839-6912899b-4dc8-4580-be55-8c5dfb0c5777.png)

I have also restarted the whole VM and home assistant from the GUI multiple times.

In the logs it seems home assistant has picked up on it:
```
2022-09-27 00:18:40.448 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-09-27 00:18:40.449 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration homematicip_local which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
```

**To Reproduce**
I followed the documentation linked above step by step, same goes for the Rasperrymatic add-on and HACS.

**Expected behavior**
Homematic IP (local) can be added as an integration.

**Additional context**
This is a completely fresh setup, no backups restored or anything.

**Comment by markusdd** [comment]
Addition:

When using the 'ADD INTEGRATION' link from the Github Page, I can get the dialog, but it does not work either:
![grafik](https://user-images.githubusercontent.com/25175069/192397023-d4967a29-bd31-4e21-8a81-09cbf34342eb.png)

The Hostname I have copied as instructed:
![grafik](https://user-images.githubusercontent.com/25175069/192397069-7e805831-fb78-4353-bb84-c552e35c8428.png)

The Firewall I have completely open for testing now to exclude issues:
![grafik](https://user-images.githubusercontent.com/25175069/192397132-6008abcb-734f-4aa2-8e6f-8b804a58223a.png)

**Comment by SukramJ** [comment]
> Integration does not show

Clear Browser cache or use other browser.

Are you using HAOS 9.0: https://github.com/jens-maus/RaspberryMatic/issues/1942

**Comment by markusdd** [comment]
As mentioned, everything is completely latest/greatest, the setup is 2 days old. (versions see above, I used the official ova image to import VM into ProxMox)

After using the link, as mentioned, I can see the integration to be selected, but get the Connection failed error.

I am not sure if the linked ticket is applicable, as I have no indication that raspberrymatic is not running, I am also seeing no error in the log (see first post, I postet everithing that was in there)

**Comment by SukramJ** [comment]
No logs after `Verbindung fehlgeschlagen`?
Please add the logs of the RM-Addon.

**Comment by markusdd** [comment]
Here are the RM Logs:

```
Mounting /data as /usr/local (Home Assistant Add-On): OK
Identifying host system: oci, OK
Initializing RTC Clock: onboard, OK
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Initializing System: OK
Setup ca-certificates: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.1, OK
Identifying Homematic RF-Hardware: HmRF: n/a, HmIP: n/a, OK
Updating Homematic RF-Hardware: no GPIO/USB connected RF-hardware found
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: not required
Starting rfd: no BidCos-RF hardware found
Starting HMIPServer: ...OK
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting NeoServer: OK
Starting Third-Party Addons: OK
find: /usr/local/etc/monit*.cfg: No such file or directory
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.65.8.20220831 (raspmatic_oci_amd64)
```

(I am aware there is no RF hardware displayed yet, hardware is being shipped right now, I am just preparing the setup as far as I can)

Any other logs that might be interesting?

**Comment by SukramJ** [comment]
Sorry, but HW is required. Otherwise the services required for this Integration are not started.

**Comment by markusdd** [comment]
ok, that is an important detail you have to know hahahaha

So I would kindly change this issue to a request to update the documentation with a small hint that at least 1 device must exist I guess? 

If it wokrs then I will hopefully see later today when some of the HW arrives.

**Comment by SukramJ** [comment]
It should be obvious that something that operates as a gateway needes an Rf-Module for _normal_ operation.

**Comment by markusdd** [comment]
> It should be obvious that something that operates as a gateway needes an Rf-Module for _normal_ operation.

Yes, but it is in NO way obvious that performing the initial setup would need that to establish the connection beween the CCU and HA. (if it was I never would've tried...)
I do not think that preparing a setup in order to set up a system is such an alien use-case.

**Comment by SukramJ** [comment]
[This](https://github.com/danielperna84/hahomematic/commit/11e303aa84b7bfe54f8f2cec80b98449fb91cce8) one is for you.

**Comment by markusdd** [comment]
Haha maybe more for the next person, as I now found it out the hard way I guess :) . But thanks a lot for checking here and adding this.
