### ISSUE TITLE
Home Assistant "homematicip_local.xxx" misses unique_id

### ISSUE THREAD

**Issue by ThomDietrich** [SukramJ/hahomematic#632]
DONT'T DELETE THIS.

**Is your feature request related to a problem? Please describe.**

Hey zusammen,
mein RaspberryMatic basiertes Setup generiert eine Entity `homematicip_local.raspberrymatic` in Home Assistant. Diese Entity hat keine unique_id.

**Describe the solution you'd like**

Bitte erzeugt eine unique_id :)

**Describe alternatives you've considered**

Keine unique_id schränkt die UI Möglichkeiten von Nutzern ein und ist generell eher typisch für veraltete Integrationen.

**Additional context**

![image](https://user-images.githubusercontent.com/2870104/192842583-70cb806c-7c83-490e-8d7f-1cea7a614b46.png)

Bonus: Die Entität scheint mir generell nicht besonders sinnvoll und ist wohl eher technischer Natur. Der friendly_name könnte besser gewählt sein, außerdem ist der State (offensichtlich die Anzahl an Servicemeldungen) nicht klar und vermutlich unsinnig?

**Comment by SukramJ** [comment]
Diese Entität wird benötigt wenn man die CCU Instanz auswählen muss, wie z.Bsp. bei den Services `clear_cache`, `set_variable_value`.
Des weiteren funktionieren bei Entitäten mit domain==component die üblichen Mechanismen wie device_info und unique_id nicht.

Es wird hier also keine Änderung geben.

Der _friendly name_ entspricht dem Instanznamen, und ob der gut gewählt wird liegt im ermessen des Benutzers.

**Comment by ThomDietrich** [comment]
Verstehe, das Problem liegt auf einer anderen Ebene...

Etwas an der Domain zu ändern ist nicht möglich? Die Homematic Integration ist die einzige Integration welche eine solche Entität erzeugt. Wie lösen ZHA oder Zwave den von dir angesprochenen Anwendungsfall?

**Comment by SukramJ** [comment]
Ist das den Aufwand wirklich Wert?
Bei der alten Integration bestand diese Entität schon (auch ohne unique_id).

> Die Homematic Integration ist die einzige Integration welche eine solche Entität erzeugt. 

Nein.

> Wie lösen ZHA oder Zwave den von dir angesprochenen Anwendungsfall?

Ein Blick in den Source Code sollte alle deine Fragen beantworten können. Kannst dich ja nochmal melden, wenn Du was raus gefunden hast.

**Comment by emontnemery** [comment]
> Des weiteren funktionieren bei Entitäten mit domain==component die üblichen Mechanismen wie device_info und unique_id nicht.

I don't think there's any such limitation, the entity registry identifies an entity by the tuple `(domain, platform, unique_id)`, it doesn't matter if the elements in the tuple are same or not. The device registry needs the entity to be created by a config entry.

**Comment by SukramJ** [comment]
Maybe, but it has no effect when adding unique_id or device_info.
