### ISSUE TITLE
Autochange Entity Names based on Homematic Channel Name

### ISSUE THREAD

**Issue by ND1988** [SukramJ/hahomematic#636]
DONT'T DELETE THIS.

**Is your feature request related to a problem? Please describe.**
When initially setting up the addon, the entity names are created on the base of the Homematic device‘s name.
If new devices are added to the CCU, the addon will instantly add these devices to HA. The entity name in HA then will be based on the initial name (incl. devices unique Homematic ID)

**Describe the solution you'd like**
A service to mass update all the HA Entity names based on recent the CCU name

**Describe alternatives you've considered**
Manually changing the entity names

**Additional context**
—-

**Comment by SukramJ** [comment]
Have a lock at the [Howto](https://github.com/danielperna84/hahomematic/wiki/Howto's)

**Comment by ND1988** [comment]
Thx, didn’t find this ;)
