### ISSUE TITLE
Minor change to German sensor translation

### ISSUE THREAD

**Issue by meks007** [SukramJ/hahomematic#638]
DONT'T DELETE THIS.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
https://github.com/danielperna84/custom_homematic/blob/devel/custom_components/homematicip_local/translations/sensor.de.json

Currently for door_state sensors open and closed is being translated as "offen" and "geschlossen". I propose "Offen" and "Geschlossen" instead. Capitalizing the states would be more consistant with HA. Other hahomematic sensors like lock_state are already capitalized.

```
    "homematicip_local__door_state": {
      "closed": "geschlossen",
      "open": "offen",
      "ventilation_position": "Belüftung",
      "position_unknown": "Position unbekannt"
    },
```

whereas:

```
    "homematicip_local__srh": {
      "closed": "Geschlossen",
      "tilted": "Gekippt",
      "open": "Offen"
    },
    "homematicip_local__lock_state": {
      "unknown": "Unbekannt",
      "locked": "Verriegelt",
      "unlocked": "Unverriegelt"
    },
```

**Comment by SukramJ** [comment]
Thanks for reporting.
Please create a PR on your own next time.
Changes can be seen [here](https://github.com/danielperna84/custom_homematic/pull/324).
