### ISSUE TITLE
Using service call with homematicip_local.ccu will be removed with HA 11.2022. Use sensor.ccu instead

### ISSUE THREAD

**Issue by euDominic** [SukramJ/hahomematic#639]
This error originated from a custom integration.

Logger: custom_components.homematicip_local.services
Source: custom_components/homematicip_local/services.py:172
Integration: Homematic(IP) Local (documentation, issues)
First occurred: 18:35:02 (17 occurrences)
Last logged: 18:39:10

Using service call with homematicip_local.ccu will be removed with HA 11.2022. Use sensor.ccu instead

**Comment by SukramJ** [comment]
RTF [release notes](https://github.com/danielperna84/custom_homematic/releases/tag/1.18.0) !!!

Fill out the issue template next time, if you want support.
