### ISSUE TITLE
Add support for ALPHA-IP-RBG

### ISSUE THREAD

**Issue by Siumba** [SukramJ/hahomematic#641]
**Is your feature request related to a problem? Please describe.**
ALPHA-IP-RBG Room Control Unit is not being recognized, which is logical as this device has not been added yet for support.

**Describe the solution you'd like**
Add ALPHA-IP-RBG device. Technically this should be identical to the HMIP-WTH-2.

**Additional context**
ALPHA-IP-RBG should be identical to the HMIP-WTH-2.

**Comment by SukramJ** [comment]
Use this [HA service](https://github.com/danielperna84/custom_homematic#homematicip_localexport_device_definition) to export required device definitions.

Exported device definition (2 files) can be found under:
'Your home-assistant config directory'/homematicip_local/export_device_descriptions/{device_type}.json
'Your home-assistant config directory'/homematicip_local/export_paramset_descriptions/{device_type}.json

Please create a pull request with both files at [pydevccu](https://github.com/danielperna84/pydevccu), if the device not exists, to support future development of this component. This data can be used by the developers to add customized entities for new devices.

**Comment by SukramJ** [comment]
device is supported with version 1.19.0

**Comment by Siumba** [comment]
I'm not sure if it's not supported, but there seems to be no hvac_action state for this type of thermostat. The radiator thermostats do have this, but I can imagine this works in a different fashion.

**Comment by SukramJ** [comment]
This device does not support STATE, that can be used for hvac_action. I thinks only devices with an actor support something like STATE/LEVEL.
