### ISSUE TITLE
Cannot found servicemessages

### ISSUE THREAD

**Issue by hvorragend** [SukramJ/hahomematic#644]
Hi,
in one of your latest releases you have written that the "Servicemeldungen" are included in hub_entity.
But there is only the amount of service messages and not any content.

I am using this script (https://homematic-forum.de/forum/viewtopic.php?t=24618) and store the content in a system variable. All other variables are transfered to HA, but this one is missing.

I've tested several namings and the "hahm"-addition in the description.

I've restarted the addons and reloaded the integration multiple times. Nothing changes.

Do you have an idea why this sysvar is missing?

Thank you.

**Comment by SukramJ** [comment]
Only the count is in the new sensor mentioned in the release notes.
The sysvar `Servicemeldungen` contains only a count of service messages and not the messages.
There is no further plan for messages.

**Comment by SukramJ** [comment]
Sorry, but i don't use this script, but if you want support then don't delete the template and fill it out next time.
