### ISSUE TITLE
HM-CC-RT-DN switching off does not switch to manual mode

### ISSUE THREAD

**Issue by kl-hobbit** [SukramJ/hahomematic#650]
**custom_component version (if applicable):**
1.19.2

**known last working custom_component version (if applicable):**
n.a.

**Home Assistant version (if applicable):**
2022.10.1

**CCU version:**
- Model (Intel): debian
- OS (debmatic):
- Version: 

**Problem-relevant configuration:**

Do you use tls? no
Do you use callback?no
Do you use username and password? yes
Which interfaces do you use (hmip/bidcos/wired)?
hmip/bicos

**Describe the bug**
When switching off HM-CC-RT-DN via climate card or service climate.turn-off or climate.set_hvac_mode= off, thermostat is switched to off but "manu mode" in WebUI is not switched on (stays in auto mode).
Same with HmIP-eTRV-2 is working.

If HM-CC-RT-DN is switched off but in auto mode, it will turn on automatically at next time step in the profile definition at homematic.

**To Reproduce**
see above: Turn off HM-CC-RT-DN in home-assistant

**Screenshots (if applicable)**
na.

**Relevant HA log entries (full log)**
-
**Diagnostic Information (available on every device)**
na.

**Expected behavior**
With turn off, switch on manu mode

**Comment by SukramJ** [comment]
Please add screenshots for HA and CCU WebUI.

**Comment by Baxxy13** [comment]
![GIF 11 10 2022 18-39-47](https://user-images.githubusercontent.com/54898249/195150646-af8dd56f-3b87-43ee-bbe3-c753957ecb0d.gif)

**Comment by SukramJ** [comment]
Ein Bild sagt mehr als 1000 Worte stimmt nicht immer.

**Comment by SukramJ** [comment]
Ich hab natürlich gesehen das das Thermostat auf `auto` bleibt, aber ist das ein Problem?
Aktuell entspricht das dem Stand der Core Integration.

**Comment by Baxxy13** [comment]
Wollte nur aushelfen.
Das Problem entsteht ja dann wenn der nächste Schaltzeitpunkt eintritt und der Sollwert (dem Wochenprogramm) entsprechend gesetzt wird. Das passiert spätestens um 00:00. 

Es ist zwar nicht "mein Problem" aber ich bin ein Freund von konsistentem Verhalten. 
Ob ich also in der WebUI auf "Aus" klicke oder in HA "Aus" wähle sollte keinen Unterschied machen.

**Comment by SukramJ** [comment]
> Wollte nur aushelfen.

Danke, sonst kommt ja keine Rückmeldung.

Da ich keine HM Geräte habe, muss ich erst mal verstehen wo das Problem ist.
Da HM nicht HmIP ist sind auch die jeweils relevanten Parameter anders.

Was passiert wenn man in der WebUI auf aus klickt?
Temperatur geht auf 4,5 Grad, Gerät ist AUS und der Mode ist manuell?

Wie sind die Werte für folgende Parameter MANU_MODE, AUTO_MODE, CONTROL_MODE wenn das Gerät in der WebUI auf aus gestellt wurde?

**Comment by Baxxy13** [comment]
> Temperatur geht auf 4,5 Grad, Gerät ist AUS und der Mode ist manuell?

Korrekt. 

MANU_MODE und AUTO_MODE sind nur write, kann ich also nicht auslesen.

WebUI aus:
CONTROL_MODE steht auf 1 (= MANU)

HA aus:
CONTROL_MODE steht auf 0 (= AUTO)

**Comment by SukramJ** [comment]
Also wenn man in HA erst auf `Heizen`  und danach auf `Aus` geht, stimmt die Anzeige in der WebUI?

**Comment by Baxxy13** [comment]
Ja, dann passt das. 
Beim "Heizen" wird CONTROL_MODE auf 1 gesetzt, das anschließende "Aus" setzt den Sollwert dann auf 4.5°C.

**Comment by SukramJ** [comment]
1.19.5 sollte das so jetzt umsetzen.

**Comment by kl-hobbit** [comment]
Vielen Dank für den Fix und die Infos. Ich hatte bis jetzt keine Zeit mich um weitere Infos zu kümmern.

Ich habe den Fix gerade bei mir getestet bzgl. der unterschiedlichen Statusübergänge Auto - Heizen - Off in HA und die WebUI folgt jetzt wie erwartet und andersherum.

Ich würde ihn dann hiermit schließen.
