### ISSUE TITLE
Reporting the valve of a thermostat HmIP-eTRV-E-S

### ISSUE THREAD

**Issue by ThomasWetzel** [SukramJ/hahomematic#652]
DONT'T DELETE THIS.

**Is your feature request related to a problem? Please describe.**
The valve state of a HmIP-eTRV-E-S is not visible as attribute.

**Describe the solution you'd like**
The valve state should be reported as attribute.
For the model HM-CC-RT-DN the valve state is reported.

This way you could check if the heating if working correctly or not.

HM-CC-RT-DN attributes:

hvac_modes: auto, heat, off
min_temp: 4.5
max_temp: 30.5
target_temp_step: 0.5
preset_modes: boost, comfort, eco
current_temperature: 25.3
temperature: 23
preset_mode: none
id: OEQ208xxxx
interface: Funk
battery: 2.8
rssi_peer: -45
**valve: 6**
mode: Auto
friendly_name: Heizung Büro
supported_features: 17

HmIP-eTRV-E-S attributes:
hvac_modes: auto, heat, off
min_temp: 4.5
max_temp: 30.5
target_temp_step: 0.5
preset_modes: boost, none, Profile 1, Profile 2, Profile 3
friendly_name: Heizung Familienzimmer
supported_features: 17
interface_id: CCU3-HmIP-RF
address: 00325D89BB6xxx:1
model: HmIP-eTRV-E-S
entity_type: custom
value_state: valid
current_temperature: 23.1
temperature: 21
hvac_action: heating
preset_mode: Profile 1

**Comment by SukramJ** [comment]
.. and there is no deactivated level entity?

**Comment by SukramJ** [comment]
Looks like the attributes from your HM-CC-RT-DN are from the old integration.
In the new integration HM-CC-RT-DN also has a state entity.

**Comment by SukramJ** [comment]
The HmIP-eTRV-E**-S** is currently in our support project [pydevccu](https://github.com/danielperna84/pydevccu).

Use this [HA service](https://github.com/danielperna84/custom_homematic#homematicip_localexport_device_definition) to export required device definitions.

Exported device definition (2 files) can be found under:
'Your home-assistant config directory'/homematicip_local/export_device_descriptions/{device_type}.json
'Your home-assistant config directory'/homematicip_local/export_paramset_descriptions/{device_type}.json

Please create a pull request with both files at [pydevccu](https://github.com/danielperna84/pydevccu), to support future development of this component. This data can be used by the developers to add customized entities for new devices.

**Comment by SukramJ** [comment]
Ich denke das Ticket kann ich schliessen das der HmIP-eTRV-E in pydevccu vorhanden ist, brauchen wir den HmIP-eTRV-E-S doch nicht. Danke für die Rückmeldung

**Comment by Baxxy13** [comment]
@ThomasWetzel 
Falls der "Ventilöffnungsgrad" inzwischen noch nicht gefunden wurde, dann mal hier (#633) gucken.

**Comment by ThomasWetzel** [comment]
Hallo @Baxxy13,

vielen Dank. Gefunden.

Die Integration läuft problemlos bisher. Vielen Dank!
