### ISSUE TITLE
HmIP-FBL missing entities

### ISSUE THREAD

**Issue by grisia** [SukramJ/hahomematic#66]
The buttons and virtual channels of the HmIP-FBL are not recognized.

**Comment by SukramJ** [comment]
See this [comment](https://github.com/danielperna84/hahomematic/discussions/17#discussioncomment-1692907) regarding virtual channels and Covers.
Buttons are for the virtual remotes to be usable in automations. Normal devices should not need them.

**Comment by grisia** [comment]
I am currently trying to migrate from IOBroker to Home Assistant. I need a way to respond to the long press of the 'HmIP-FBL'.

Currently, but not the preferred way, on the Homatic side, I have put the long button press on virtual channel 6 and then act on the virtual channel in IOBroker (move all shutters up or down). The virtual channel only serves as a status holder and is not linked to channel 3 (actual status channel).

I agree with the comment that you don't necessarily need the virtual channels, but being able to respond to the buttons would be good.

**Comment by SukramJ** [comment]
~~I am not sure, if i understood what you are doing.
You use the CCU WebUI and press channel 6 long?
The XMLRPC-API has keypress events only on channel 1 and 2.~~
Still confusing.
A solution could be:
- Connect your long_press to a virtual remote channel
 --> you can use the key_press in a HA as trigger and as an action. 
- use a system variable to keep the state.

**Comment by grisia** [comment]
I want to achieve when I press the up or down button for a long time that all the shutters move  up or down.

My solution is currently very crude, i think. On the CCU portal, I have linked the long press event with virtual channel 6 for all 'HmIP-FBL'.
On the IOBroker side, I then checked the status of channel 6 in order to then raise or lower all the shutters.
I don't know why I implemented it this way, I think because the IOBroker implementation did not properly report the long key press.

A simpler solution would be to simply react to the long-press event.

But currently I can neither implement the simple solution, since no button entities are provided, nor implement my crude solution, since no virtual channels exist.

**Comment by SukramJ** [comment]
Button are used to send a key pressed to CCU and not to receive a key pressed from CCU!
I think the solution from my previous post should fullfil your need without modifying to much inside a HmIP-FBL.

**Comment by grisia** [comment]
Sorry for the misunderstanding. I think I should read a little more. ;)

It is a pity that I cannot react to the hardware buttons of the HmIP-FBL directly in HA. Ok...

A system variable could be a solution. On the CCU side, I would set a system variable by long pressing the button.
I could then react to this in a script in the HA and move all shutters up or down.

**Comment by SukramJ** [comment]
If you just need the press_long of the FBL in HA, you could use the existing device trigger in an automation:
1 open automation
2 trigger should be preselcted with device
3. select your fbl
4.  select the channel with the event

**Comment by grisia** [comment]
Automation.... That's it! I will read a lot more. ;)

My thinking is still too contaminated by IOBroker...

Again sorry for disturbing and thx for quick help.
