### ISSUE TITLE
New heating group in CCU doesn't create device / entities in HA

### ISSUE THREAD

**Issue by Bascht74** [SukramJ/hahomematic#662]
**custom_component version (if applicable):**
1.19.6

**known last working custom_component version (if applicable):**
? not sure, but it did

**Home Assistant version (if applicable):**
2022.10.3

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, HA-Addon ...): HA-Addon  (tested in both enviroments in two different houses
- OS (Original, RaspberryMatic, debmatic ...): raspberryMatic
- Version: 3.65.11.20221005

**Problem-relevant configuration:**

Do you use tls? no
Do you use callback? don't now
Do you use username and password? yes
Which interfaces do you use (hmip/bidcos/wired)? hmip

**Describe the bug**
A new heating group doesn't materialize in HA any more

**To Reproduce**
Add new heating group. Try all different stuff (restart HA OS, restart raspmatic, reload integration, combine stuff and wait some minutes)
In all cases a new heating group will not create a device / entities in HA anymore

**Screenshots (if applicable)**
- CCU firewall -> all open
- integrations view

- device view -> missing
- enity view -> missing
[config_entry-homematicip_local-1b43698376898a59a21bfc96ce291372.json.txt](https://github.com/danielperna84/hahomematic/files/9828356/config_entry-homematicip_local-1b43698376898a59a21bfc96ce291372.json.txt)

**Relevant HA log entries (full log)**
![image](https://user-images.githubusercontent.com/66269310/196911069-8cbc831d-8035-43a1-9928-c4ad9a3a814f.png)

(all other stuff is still working, I can change an existing heating group in HA and it will be changed in the CCU. I haven't change any passwords, using a seperate user for the HA integration)

**Diagnostic Information (available on every device)**
```
see above.

```

**Expected behavior**
The heating group will be created in HA

**Additional context**
I don't know if this is really an issue or if I can so something about that myself.

**Comment by SukramJ** [comment]
Did you restart?
To remove the error message: You could remove BidCos/port 2001 from your configuration. You don't have Bidcos Devices.

**Comment by Bascht74** [comment]
> Did you restart? To remove the error message: You could remove BidCos/port 2001 from your configuration. You don't have Bidcos Devices.

Thx for the tipp! I removed it:
![image](https://user-images.githubusercontent.com/66269310/196994867-2b9a20bc-7496-4d8b-b76b-1556bbb20b3f.png)


I restated the integration, the CCU, both... Is there a special order to restart after adding a heating group?
I think I tried to restart in every combination, but maybe I missed the right way or did not wait long enough...

**Comment by Bascht74** [comment]
Restart CCU
Waited 10 Minutes. 
Restart HA
Waited 10 Minutes. 

... still not there:

![image](https://user-images.githubusercontent.com/66269310/196998314-52735780-6a5f-4b7b-a33d-7a56b8776310.png)

CCU:
![image](https://user-images.githubusercontent.com/66269310/196998613-ef7299d1-968f-471d-a269-f90529d5ff92.png)

The only difference between the other entries is that the name of the group and the virtual device are the same...

Is there a way so see what the integration gets from the CCU and what it does with it...

**Comment by Bascht74** [comment]
![image](https://user-images.githubusercontent.com/66269310/196999048-458f10c6-9868-432a-9092-160950869c73.png)

**Comment by SukramJ** [comment]
I tested this this on my env without any issues and any restarts.
Please delete the group in ccu and create it again.

Any entries in the HA log (click on full log).
Any entries in the CCU log?

**Comment by Bascht74** [comment]
> Any entries in the HA log (click on full log).
no warnings or errors

> Any entries in the CCU log?

Yes, see: 

https://pastebin.com/218Az8Ni

But i cannot understand these messages if they are OK or leading to this problem.

I allready deleted the group and added it again (old group ID 6, new is 7), no change.

Is there a way to "see" what the integration is getting from CCU-API?
e.g. a curl command. I didn't find any examples to access the CCU that way (and sending the username & password)

**Comment by SukramJ** [comment]
Looks like you log entries are related to virtual devices so that could be the problem, but I am not an expert for CCU logs.
Maybe @baxxy13 as an idea.

**Comment by Baxxy13** [comment]
Hmm, ich kann da nicht wirklich helfen da ich Meldungen auch nicht korrekt deuten kann. 
Ich kenne auch niemanden der das kann, das ganze kommt ja aus dem "Closed-Source" HmIP-Server. Also aus der "blackbox" einer Zentrale.

Es sieht aber so aus als hänge es mit den virtuellen Geräten zusammen.

Im Homematic-Forum gibt es auch einen aktuellen Thread in dem es um Probleme mit den virtuellen Gruppengeräten geht.
Dort klappt aber nicht mal das Erzeugen einer solchen. Muss jetzt nicht unbedingt zusammenhängen, aber meistens gibt es bei solchen Sachen Gemeinsamkeiten.

Was tun...

- definitiv erstmal jegliche externe Steuerung die sich an die Schnittstellen hängt deaktivieren
- Zentrale einmal durchbooten, dann eine neue IP-Gruppe anlegen welche idealerweise erstmal nur ein Gerät enthält, ich empfehle einen Fenstersensor
- das Gruppengerät in > Status und Bedienung > Geräte anwählen und den Fenstersensor "bewegen"
- Kanal:3 des Gruppengerätes muss quasi instant reagieren

Gibt es beim letzten Schritt eine "instant Reaktion" ist m.E. auf Seite der Zentrale alles i.O. 

Dann kann man bspw. den Homematic-Manager mal anwerfen und gucken ob das virtuelle Gerät über die Schnittstelle sichtbar ist.

**Comment by Bascht74** [comment]
Ich probiere es nachher aus. Danke für die Tipps!

**Comment by Bascht74** [comment]
1. definitiv erstmal jegliche externe Steuerung die sich an die Schnittstellen hängt deaktivieren
Die CCU läuft als HA-Addon, externe Ports außerhalb HA sind zu (nur HA kann darauf zugreifen) und es läuft nur die HM-Integration hier von Github.
2. Zentrale durchgebootet und eine neue IP-Gruppe angelegt (Nr. 8, enthält nur ein Gerät)
3. das Gruppengerät in > Status und Bedienung > Geräte anwählen und Temperatur verändert -> Funktioniert

Jetzt ist diese Gruppe auch erschienen. Echt komisch. Vorher hatte ich gleich mehrere Geräte da reingepackt, da ging es scheinbar nicht. 
Danke für die Tipps!
