### ISSUE TITLE
Homematic Addon - Error 111 Connection Refused

### ISSUE THREAD

**Issue by tom-43** [SukramJ/hahomematic#664]
Hello,
I wanted to set up the Homematic Ip local addon with connection to my Raspberry Matic. Unfortunately after entering the iP, username and password I always get the error:
Unable to connect (ConnectionRefusedError(111, 'Connection refused'),).
in the logs.

I have Raspberry Matic running on a Pi3 inside a Docker container with the HM-MOD-RPI-PCB. I can access it flawlessly from the laptop. Also the ping inside the Docker container to the Homeassistant server and the ping from the Homeassistant server to the Raspberry Matic works. 
In Docker I have also tried to assign the Raspberry Matic its own iP via Macvlan. Unfortunately I get no connection at all (not even from the PC). 

What can I do?

Many greetings

**Comment by SukramJ** [comment]
> What can I do?

First step is fill out the issue template.

**Comment by tom-43** [comment]
Where can I find this. I opened the Issue from the discussion?

**Comment by SukramJ** [comment]
It's the thing you see if you open an issue.

**Comment by tom-43** [comment]
**custom_component version (if applicable):**
1.19.6

**known last working custom_component version (if applicable):**
I haven't installed it before

**Home Assistant version (if applicable):**
2022.10.4

**CCU version:**
- Raspi3 (Docker)
- RaspberryMatic Docker Install
- Version: 3.65.11.20221005

**Problem-relevant configuration:**

Do you use tls? No
Do you use callback? No
Do you use username and password? Yes
Which interfaces do you use (hmip/bidcos/wired)? hmip

**Describe the bug**
See above

**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'Devices'
2. Click on 'Add integration'
3. Scroll down to 'Homematic iP Local'
4. Fill everything in
5. See Error "Verbindung Fehlgeschlagen"

**Screenshots (if applicable)**
- CCU firewall
<img width="502" alt="Bildschirm­foto 2022-10-20 um 16 23 52" src="https://user-images.githubusercontent.com/79532009/196975718-55e80396-65bb-4496-afd3-6b59a79cc852.png">


**Relevant HA log entries (full log)**

<img width="1043" alt="Bildschirm­foto 2022-10-20 um 16 25 15" src="https://user-images.githubusercontent.com/79532009/196976000-8a0c093f-f7ea-4323-bf70-2c8b4033eeb6.png">





**Expected behavior**
See above

**Additional context**
See above

**Comment by SukramJ** [comment]
Your firewall is blocking, what do you expect?

**Comment by tom-43** [comment]
Ok. The one from the router , the pi or Docker?

**Comment by tom-43** [comment]
Ah, now I have it. I have changed the Raspberry Matic firewall and now it works. 
Thanks for the quick help.
