### ISSUE TITLE
Issues with Icon Color based on state

### ISSUE THREAD

**Issue by ChristophCaina** [SukramJ/hahomematic#669]
DONT'T DELETE THIS.

Please answer all questions as good as possible.

Language: english/german

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you have read the release notes at https://github.com/danielperna84/custom_homematic/releases. 

Make sure you are running the latest version of the custom_component (and Home Assistant) before reporting an issue.

ENSURE that your Backend (CCU/Homegear/...) is working as expected and connected devices are controllable.

**custom_component version (if applicable):**
latest

**known last working custom_component version (if applicable):**
unknown

**Home Assistant version (if applicable):**
2022.10.5

**CCU version:**
- ProxmoxVE
- RaspberryMatic 
- Version: latest

**Problem-relevant configuration:**

Do you use tls?
Do you use callback?
Do you use username and password?
Which interfaces do you use (hmip/bidcos/wired)?
hmip

**Describe the bug**
I am running a Window Sensor and a Window Handle sensor.
Both are reporting the state correctly - but it appears, that the sensor for the door handle does not change the Icon when it is open - nor change the color as configured in the lovelace card.

![grafik](https://user-images.githubusercontent.com/26391061/197160380-89ca72c4-9569-4977-8602-da9a46b00173.png)
![grafik](https://user-images.githubusercontent.com/26391061/197160517-7130f275-40a3-45af-8b40-0dd01ad8902e.png)

I am not sure, if this is related to this integration - but since the card does change the icon's color - I think it shouldn't be an issue inside of HA.

**To Reproduce**

**Screenshots (if applicable)**
Entity View
![grafik](https://user-images.githubusercontent.com/26391061/197160380-89ca72c4-9569-4977-8602-da9a46b00173.png)
![grafik](https://user-images.githubusercontent.com/26391061/197160517-7130f275-40a3-45af-8b40-0dd01ad8902e.png)
**Relevant HA log entries (full log)**
```


```

**Diagnostic Information (available on every device)**
```


```

**Expected behavior**
Sensor type HmIP-SRH should also change the Icon Color / the Icon based on its state.
Maybe, this isn't the case, because it can have at least three different states (closed, open, curtailed)
In this case, I would consider the curtailed state also as "open" indicator - which should change the icon color.

**Additional context**

**Comment by SukramJ** [comment]
HmIP-SRH is a special case. Unlike binary_sensors it does have a device_class that determines the icon color handling.
I will will not add a special handling for a single sensor to handle different icon colors.

You could do this on your own by using a template sensor/binary_sensor to customize this.

**Comment by SukramJ** [comment]
I found a solution that works with the existing code without having extra code for certain devices.
But this solution can only change the icon based on state.
Changing the color based on state is done in the frontend, and cannot be done by an integration.
That will be release with 1.19.9.
