### ISSUE TITLE
Renaming a device duplicates part of the name of its entities

### ISSUE THREAD

**Issue by eikowagenknecht** [SukramJ/hahomematic#671]
**custom_component version (if applicable):**
latest

**known last working custom_component version (if applicable):**
latest

**Home Assistant version (if applicable):**
latest

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, HA-Addon ...): CCU3
- OS (Original, RaspberryMatic, debmatic ...): Raspberrymatic

**Describe the bug**
Renaming a devices duplicates the name. See screencast for what I mean.

**To Reproduce**
1. Add new device
2. Rename it
3. See duplicated name

**Screenshots (if applicable)**
![issue](https://user-images.githubusercontent.com/1475672/197378338-7c0c4d12-f54f-4901-b7b4-663acfc0d32c.gif)

**Expected behavior**
Entity name should be OG.Abstell Heizung Thermostat after the rename.

**Additional context**
Not sure if it is this integration or a Home Assistant problem.

**Comment by SukramJ** [comment]
Why is renaming in the UI relevant for this integration?
Better use [Option 3](https://github.com/danielperna84/custom_homematic#rename-of-devicechannel-in-ccu-not-reflected-in-home-assistant).

**Comment by eikowagenknecht** [comment]
Call it a personal quirk, but I like to keep my naming inside one system very consistent.

In my Homematic naming scheme all devices get a " (Gerät)" at the end of their name because otherwise they cause duplicates with some channel names. In Home Assistant they have a seperate namespace (as should be) and so they only get the name of the device.

**Comment by SukramJ** [comment]
Be aware of [this](https://developers.home-assistant.io/blog/2022/07/10/entity_naming)
Here I remove the device_name from an entity_name from the beginning.

**Comment by SukramJ** [comment]
I think this can be closed

**Comment by eikowagenknecht** [comment]
How do you name things in the CCU then? E.g. for devices with a single channel?

I'd currently name it:
- EG.Wohnen Deckenlampe (Gerät) for the deviceand
- EG.Wohnen Deckenlampe for the channel

**Comment by SukramJ** [comment]
Yes. Same here.
