### ISSUE TITLE
UNREACH param is not reporting correctly

### ISSUE THREAD

**Issue by WallyDW** [SukramJ/hahomematic#672]
DONT'T DELETE THIS.

Please answer all questions as good as possible.

Language: english/german

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you have read the release notes at https://github.com/danielperna84/custom_homematic/releases. 

Make sure you are running the latest version of the custom_component (and Home Assistant) before reporting an issue.

ENSURE that your Backend (CCU/Homegear/...) is working as expected and connected devices are controllable.

**custom_component version (if applicable):**
1.19.9

**known last working custom_component version (if applicable):**
Not known

**Home Assistant version (if applicable):**
2022.10.5

**CCU version:**
- Model: CCU3:
- OS: debmatic:
- Version: 3.65.8.95

**Problem-relevant configuration:**

Do you use tls? No
Do you use callback? No
Do you use username and password? Yes
Which interfaces do you use (hmip/bidcos/wired)? HMIP

**Describe the bug**
I am trying to use the UNREACH paramset with the unignore file.
The sensor comes up fine and the reporting is set to off, when the device is reachable.
When the device is not reachable anymore, then the sensor goes to unavailable, instead of to on.
My guess is that the integration register that the device is unreachable and therefore do not set the attributes of the device.
The truth is that the device is actually found in the CCU, but the device is currently unavailable and the UNREACH paramset should then be available and set to on.
Looking at the XMLAPI printout it is also visible as such.

**To Reproduce**
1. Make an unignore file with UNREACH included
2. Check the UNREACH sensor for a device that is reachable
3. Remove the batteries and wait (running a function test on the device in the CCU might speed up the detection of UNREACH)
4. check the state of the sensor.

**Expected behavior**
When the device becomes unreachable in the CCU, then the sensor for UNREACH should be set to on and not unavailable.

**Comment by SukramJ** [comment]
This is expected behaviour.
UNREACH is used make entities available/unavailable, so the outcome is already covered.

**Comment by WallyDW** [comment]
UNREACH is created as a binary sensor in HA, which indicate a value set of on/off.
Unavailable is only when the sensor value is not available, which is not the case here.
Currently the sensor can never reach the on value.

The UNREACH paramset indicate a problem between the CCU and the device, but it also indicate that the device actually exist in the CCU.
The current way the sensor is working this difference is not possible to detect.

**Comment by SukramJ** [comment]
If the CCU indicates UNREACH (True)  the device and all entities will be marked as unavailable.

I will not add an execption for UNREACH if someone is using `unignore` to enable this parameter.

**Comment by SukramJ** [comment]
See property available in [HA docs](https://developers.home-assistant.io/docs/core/entity#generic-properties)

`Indicate if Home Assistant is able to read the state and control the underlying device.`

**Comment by WallyDW** [comment]
Sorry, I do not see the relevance.
In the docs I can see an attribute called available with the text, but UNREACH is not that attribute.
If you want to make that attribute based on the UNREACH paramset, then fine, because it should then have the states true/false and not true/unavailable.

In my opinion the UNREACH paramset should actually not be hidden and require an unignore file.
The paramset indicate a communication problem between the CCU and the device and not between the CCU and HA.
If you add a favourite in your CCU and put the channel 0 in that favourite, then the paramset will be dispalyed as the communication field.
Removing the batteries, having noise in the frequency spectrum, blockings in the signal way or other things will show up in the field as communication disturbed.

**Comment by SukramJ** [comment]
> The paramset indicate a communication problem between the CCU and the device

Yes: that's the meaning of **parameter** `UNREACH` and the property `available` of the entity in HA

> and not between the CCU and HA.

Nobody said this.

If there is a problem between HA and CCU then NO device/entity will be available and you'll  have a diffrent notification.
