### ISSUE TITLE
HmIPW-FIO6 Button presses

### ISSUE THREAD

**Issue by pjanning** [SukramJ/hahomematic#681]
Hey,
using the HmIPW-FIO6 you are not able to get the state of the input channels. You only get the SWITCH_TRANSMITTER and the SWITCH_VIRTUAL_RECEIVER for the Diode outputs. But the MULTI_MODE_INPUT_TRANSMITTER-channels are missing in this integration.

Patrick

**Comment by SukramJ** [comment]
Fill out the issue template!!!!

**Comment by pjanning** [comment]
Sorry. Where can i find it?

**Comment by SukramJ** [comment]
When you open an issue you'll get it.

**Comment by pjanning** [comment]
Now... Will make a new report.

**Comment by SukramJ** [comment]
Kann auch in deutsch sein.
Problem und Erwartung bitte klar beschreiben

**Comment by SukramJ** [comment]
[See](https://github.com/danielperna84/hahomematic/discussions/506)
