### ISSUE TITLE
unknown service: homematic.set_device_value since Homematic(IP) Local

### ISSUE THREAD

**Issue by x-dast** [SukramJ/hahomematic#686]
**custom_component version (if applicable):**
1.28.3

**known last working custom_component version (if applicable):**
1.28.3

**Home Assistant version (if applicable):**
2022.10.5

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, HA-Addon ...): CCU3
- OS (Original, RaspberryMatic, debmatic ...): Original
- Version: 3.65.11

**Problem-relevant configuration:**

Do you use tls? no
Do you use callback? no
Do you use username and password? yes
Which interfaces do you use (hmip/bidcos/wired)? hmip

**Describe the bug**
Since I switched to integration via HACS (Homematic(IP) Local) I get an error when changing the profile for radiator thermostat.
"The automation "xyz" has an action that calls an unknown service: homematic.set_device_value."

In configuration.yaml I have removed the old integration. HA uses "homematic.", but in the documentation it says "homematicip_local.". Do I have to adjust anything else? In the developer tools "homematicip_local." is correctly available. But the automation does not seem to use that.

**Screenshots (if applicable)**
- CCU firewall
![firewall](https://user-images.githubusercontent.com/56562360/198979417-8f8f2faa-2dee-4fc1-989e-43d1e19757d6.png)

- integrations view
![integration](https://user-images.githubusercontent.com/56562360/198979448-c0297840-5254-4282-ab20-340b650fcc32.png)

- device view
![device](https://user-images.githubusercontent.com/56562360/198979457-29e6c6ab-5514-4a3b-8ca5-debe3035b241.png)

- enity view
![entity](https://user-images.githubusercontent.com/56562360/198979478-c215139a-a2c2-438e-9095-defee5667a47.png)

- automation view
![automation](https://user-images.githubusercontent.com/56562360/198979523-f83cdee8-b82e-4bab-a6e4-0310aaeaea95.png)

**Relevant HA log entries (full log)**
Logger: homeassistant.components.automation.schicht_umschalten_auf_fruhschicht
Source: helpers/script.py:409
Integration: Automatisierung ([documentation](https://www.home-assistant.io/integrations/automation), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22))
First occurred: 09:21:23 (1 occurrences)
Last logged: 09:21:23

Schicht umschalten auf Frühschicht: Error executing script. Service not found for call_service at pos 2: Unable to find service homematic.set_device_value

**Expected behavior**
Change settings for radiator thermostat via automations.

**Additional context**
If I change the profile directly via the entity card, it works flawlessly.

**Comment by SukramJ** [comment]
The services for the NEW integration have different domain, names and parameters.
Please checks the [doc](https://github.com/danielperna84/custom_homematic#services) for more info.

**Comment by SukramJ** [comment]
`set_device_value` is definitly the service that should not be used.

Use [climate.set_preset_mode](https://www.home-assistant.io/integrations/climate/#service-climateset_preset_mode) instead with e.g. `Profile 2` as preset_mode

Always prefer platform specific HA services over `set_device_value`.

**Comment by x-dast** [comment]
The "homematic.set_device_value" is automatically used by the automation. I can't change this in the visual editor.

**Comment by SukramJ** [comment]
> The "homematic.set_device_value" is automatically used by the automation. I can't change this in the visual editor.

I don't think so. Please post a screenshot.
Looks like you use a blueprint for the old integration, and that won't work here.

**Comment by x-dast** [comment]
I didn't use a Blueprint, but I changed the existing automation, not created a new one. So I need to create a new automation for this to work?

**Comment by SukramJ** [comment]
Edit the existing or create a new one it's your choice, but read the docs the services are different.

**Comment by x-dast** [comment]
I have read the docs. But does not solve my problem. With a new automation it works. Editing an existing one triggers the described problem. So now I have to recreate all heating automations. I thought it would work without having to recreate all the automations.

**Comment by SukramJ** [comment]
Sorry this is not a support forum for home assistant.

> With a new automation it works

So closing this ticket, because this is not an issue with this integration.
