### ISSUE TITLE
HmIP-BWTH: `humidity` attribute should be part of `climate` entity

### ISSUE THREAD

**Issue by oliverrahner** [SukramJ/hahomematic#688]
DONT'T DELETE THIS.

**Is your feature request related to a problem? Please describe.**
When adding my [HmIP-BWTH](https://de.elv.com/homematic-ip-wandthermostat-mit-schaltausgang-hmip-bwth-fuer-markenschalter-230-v-150628) devices, the most relevant attributes get packed into the `climate` entity and the corresponding raw values (like `sensor.hmip_bwth_actual_temperature`) are disabled by the integration.

The humidity entity is also disabled, but it does _not_ get added to the climate entity.
At first glance, the implemented logic expects the attribute to be named `current_humidity`, but in fact it is only named `humidity` for these devices.

**Describe the solution you'd like**
The current humidity value should be added to the climate entity.

**Describe alternatives you've considered**
The obvious alternative is to just re-enable the humidity entity and live with that...

**Additional context**
Screenshot from one of my HmIP-BWTHs entities:
![image](https://user-images.githubusercontent.com/2277681/199531700-c436f975-3c4c-4515-aae9-16907c9ce611.png)

(it only says "Disabled by User" because I already played around with it)

**Comment by SukramJ** [comment]
It is part of the climate entity and available as a separate sensor(disabled) by default.
It's not displayed in the UI for the climate entity . Why? I don't know ask the HA frontend team.

**Comment by SukramJ** [comment]
`humidity` and `actual_temperature` are the CCU's parameter names. That's why these entities are named this way.

**Comment by oliverrahner** [comment]
Wow... I think this might be the quickest reaction to an issue I ever had :)
Ok, that's interesting... I stumbled across this because it's not even shown in the History diagram, is that also expected behavior?

**Comment by oliverrahner** [comment]
I'm very new to Home Assistant, just found where I should have looked.
Under Dev Tools, State I can check what you said:

![image](https://user-images.githubusercontent.com/2277681/199534557-a366e537-2d23-44c0-a40a-cbb9e7b954dc.png)

(as a note to others looking for the same ;)

**Comment by oliverrahner** [comment]
So, I'll try my luck with the frontend team.

Thanks for the very fast answer!

**Comment by oliverrahner** [comment]
Reference: https://github.com/home-assistant/frontend/discussions/14260
