### ISSUE TITLE
New Level sensor 1.21.1 is hidden & cant be changed.

### ISSUE THREAD

**Issue by sotatech** [SukramJ/hahomematic#700]
DONT'T DELETE THIS.

Please answer all questions as good as possible.

Language: english

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you have read the release notes at https://github.com/danielperna84/custom_homematic/releases. 

Make sure you are running the latest version of the custom_component (and Home Assistant) before reporting an issue.

ENSURE that your Backend (CCU/Homegear/...) is working as expected and connected devices are controllable.

**custom_component version (if applicable):**
1.21.1

**known last working custom_component version (if applicable):**
1.20.0

**Home Assistant version (if applicable):**
2022.11.2

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, HA-Addon ...):HA-Addon
- OS (Original, RaspberryMatic, debmatic ...):RaspberryMatic
- Version: 3.65.11.20221005

**Problem-relevant configuration:**

Do you use tls?No
Do you use callback?No
Do you use username and password?Yes
Which interfaces do you use (hmip/bidcos/wired)?hmip/bidcos

**Describe the bug**
A clear and concise description of what the bug is. After installing 1.21.1 today, I can see the new sensor.trv.level but it has a status of Hidden. The status cannot be changed and is greyed out. I have level in the unignore file, so I can see the number.trv.level OK.

**To Reproduce**
1. Go to the Homematic(IP) Local integration in Home Assistant
2. Click on Devices
3. Scroll down to a TRV device
4. Under Sensors see "Level (hidden)"
5. Click on Level and then Settings
6. Click on Advanced Settings drop-down and see that the status cannot be changed.

![image](https://user-images.githubusercontent.com/9580066/200791155-0dbec9cf-d3db-4e98-b951-bbe62f8b3c87.png)

**Screenshots (if applicable)**
- CCU firewall
- integrations view
- device view
- enity view

**Relevant HA log entries (full log)**
```


```

**Diagnostic Information (available on every device)**
```
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.11.2",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Dublin",
    "os_name": "Linux",
    "os_version": "5.15.74",
    "supervisor": "2022.10.2",
    "host_os": "Home Assistant OS 9.3",
    "docker_version": "20.10.18",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "alexa_media": {
      "version": "4.3.2",
      "requirements": [
        "alexapy==1.26.4",
        "packaging>=20.3",
        "wrapt>=1.12.1"
      ]
    },
    "adaptive_lighting": {
      "version": "1.2.0",
      "requirements": []
    },
    "emby_upcoming_media": {
      "version": "0.3.5",
      "requirements": [
        "python-dateutil"
      ]
    },
    "blueiris": {
      "version": "1.0.13",
      "requirements": []
    },
    "hacs": {
      "version": "1.28.3",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "holidays": {
      "version": "1.8.0",
      "requirements": [
        "python-dateutil>=2.8.2",
        "holidays>=0.14.2"
      ]
    },
    "watchman": {
      "version": "0.5.1",
      "requirements": [
        "prettytable==3.0.0"
      ]
    },
    "scheduler": {
      "version": "v0.0.0",
      "requirements": []
    },
    "entity_controller": {
      "version": "9.6.0",
      "requirements": [
        "transitions==0.8.8"
      ]
    },
    "nodered": {
      "version": "1.1.2",
      "requirements": []
    },
    "dahua": {
      "version": "0.5.0",
      "requirements": []
    },
    "lms_tts_notify": {
      "version": "0.3.13",
      "requirements": []
    },
    "homematicip_local": {
      "version": "1.21.1",
      "requirements": [
        "hahomematic==2022.11.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "homematicip_local",
    "name": "Homematic(IP) Local",
    "config_flow": true,
    "documentation": "https://github.com/danielperna84/custom_homematic",
    "issue_tracker": "https://github.com/danielperna84/hahomematic/issues",
    "requirements": [
      "hahomematic==2022.11.1"
    ],
    "ssdp": [
      {
        "manufacturer": "EQ3",
        "manufacturerURL": "http://www.homematic.com"
      }
    ],
    "zeroconf": [],
    "homekit": {},
    "dependencies": [],
    "codeowners": [
      "@danielperna84",
      "@SukramJ"
    ],
    "iot_class": "local_push",
    "loggers": [
      "hahomematic"
    ],
    "version": "1.21.1",
    "integration_type": "hub",
    "is_built_in": false
  },
  "data": {
    "config": {
      "entry_id": "f809c6317d2f99de1cdaafb2b97371d4",
      "version": 1,
      "domain": "homematicip_local",
      "title": "RaspberryMatic",
      "data": {
        "instance_name": "RaspberryMatic",
        "host": "172.30.33.3",
        "username": "**REDACTED**",
        "password": "**REDACTED**",
        "tls": false,
        "verify_tls": false,
        "callback_host": null,
        "callback_port": null,
        "json_port": null,
        "interface": {
          "HmIP-RF": {
            "port": 2010
          },
          "BidCos-RF": {
            "port": 2001
          },
          "VirtualDevices": {
            "port": 9292,
            "path": "/groups"
          }
        }
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": "58A992FD8F",
      "disabled_by": null
    },
    "platform_stats": {
      "binary_sensor": 46,
      "button": 1,
      "climate": 36,
      "number": 23,
      "select": 36,
      "sensor": 91,
      "switch": 7
    },
    "devices": [
      "HM-LC-Sw4-DR-2",
      "HM-WDS30-OT2-SM",
      "HMIP-WTH",
      "HMIP-eTRV",
      "HmIP-HEATING",
      "HmIP-KRC4",
      "HmIP-RCV-50",
      "HmIP-SPI",
      "HmIP-STHD",
      "HmIP-WRC6",
      "HmIP-WTH-2",
      "HmIP-eTRV-2",
      "RPI-RF-MOD"
    ]
  }
}

```

**Expected behavior**
It should be possible to enable the sensor.

**Additional context**
Tried reloading the integration and restarting HA - No change.

**Comment by SukramJ** [comment]
Sorry, this seems to be an [issue](https://github.com/home-assistant/frontend/issues/12887) with the frontend.

**Comment by sotatech** [comment]
You are correct, but it does not seem like it will be fixed. To work around this, would it be possible for you to create the level sensor as Disabled, same as the duty_cycle, RSSI, etc sensors?

**Comment by SukramJ** [comment]
That's what 1.21.2 will do, but only for newly created entites.
In your case:
Option 1:
- Wait for a frontend fix

Option 2:
- Update to 1.21.2
- Use service `homematicip_local.delete_device`
- Restart HA

Option 2 has the disadvantage of a newly created device_id, that you might have used in automation, so these must be edited.

Basically these hidden entites are working normal, except they are not added to autogenerated UIs.

**Comment by sotatech** [comment]
Thanks. If I roll back to last nights backup and then install 1.21.2, would that work?

**Comment by SukramJ** [comment]
Could work.

**Comment by sotatech** [comment]
I decided on a simpler route. I installed 1.21.2 and then edited core.entity_registry, changing the HMIP Heating Groups definitions "hidden_by": "integration", to "hidden_by": null,
Restarted HA and now I have the valve sensor entities for each group.

**Comment by SukramJ** [comment]
This is dangerous.

**Comment by sotatech** [comment]
Indeed! This can break your HA install. But I have had backups failing to restore fully before, so for me editing one file was simpler. Anyway, I have taken LEVEL out of my unignore file and adjusted my automations and Lovelace cards, so all is back to normal now.
