### ISSUE TITLE
Callback events issue with Homegear 

### ISSUE THREAD

**Issue by alibababa82** [SukramJ/hahomematic#703]
Language: english

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you have read the release notes at https://github.com/danielperna84/custom_homematic/releases. 

Make sure you are running the latest version of the custom_component (and Home Assistant) before reporting an issue.
Yes, I am.

ENSURE that your Backend (CCU/Homegear/...) is working as expected and connected devices are controllable.
It is working and controllable.

**custom_component version (if applicable):**
1.21.2

**known last working custom_component version (if applicable):**

**Home Assistant version (if applicable):**
2022.11.2

**CCU version:**
Max! EQ3 Cube flashed as per [https://community.home-assistant.io/t/converting-a-max-cube-to-cul-cun-to-use-with-home-assistant/74218](url)
Running Homegear addon with its latest version (1.0.3) [https://github.com/devRoemer/hassio-homegear-generic](url)

**Problem-relevant configuration:**

Do you use tls? no
Do you use callback? yes
Do you use username and password? yes
Which interfaces do you use (hmip/bidcos/wired)? BidCos-RF (port 2001)

**Describe the bug**
I´m using Homematicip_local integration (installed via HACS and followed instructions), but I´m recieving message below and don´t know why as everything seems to be working. Heaters/window sensors are paired (done via webui of Homegear addon). After installation of Homematicip_local integration I added entities (climate sensors for heaters, binary sensors for window sensors). I can controll it via HA. If I change temperature in HA, heater recieve this seeting. If I change temperature on heater, I can see right setting in HA.

`is_callback_alive: Callback for Homematic-BidCos-RF has not received events for 307 seconds')
reconnect: waiting to re-connect client Homematic-BidCos-RF for 120s`

`HOMEMATICIP_LOCAL-XmlRPC-Server received no events.
No callback events received for interface Homematic-BidCos-RF 300s.`

**To Reproduce**

**Screenshots (if applicable)**
- CCU firewall
- integrations view
- device view
- enity view

**Relevant HA log entries (full log)**
```
2022-11-10 20:53:17.189 WARNING (MainThread) [hahomematic.client] reconnect: waiting to re-connect client Homematic-BidCos-RF for 120s
2022-11-10 20:55:17.260 WARNING (MainThread) [hahomematic.client] reconnect: re-connected client Homematic-BidCos-RF
2022-11-10 20:55:36.876 WARNING (MainThread) [hahomematic.client] is_callback_alive: Callback for Homematic-BidCos-RF has not received events for 1709 seconds')
2022-11-10 20:55:36.911 WARNING (MainThread) [hahomematic.client] reconnect: waiting to re-connect client Homematic-BidCos-RF for 120s
2022-11-10 20:57:36.978 WARNING (MainThread) [hahomematic.client] reconnect: re-connected client Homematic-BidCos-RF
2022-11-10 20:57:56.620 WARNING (MainThread) [hahomematic.client] is_callback_alive: Callback for Homematic-BidCos-RF has not received events for 1848 seconds')
2022-11-10 20:57:56.656 WARNING (MainThread) [hahomematic.client] reconnect: waiting to re-connect client Homematic-BidCos-RF for 120s
2022-11-10 20:59:56.724 WARNING (MainThread) [hahomematic.client] reconnect: re-connected client Homematic-BidCos-RF
2022-11-10 21:04:46.889 WARNING (MainThread) [hahomematic.client] is_callback_alive: Callback for Homematic-BidCos-RF has not received events for 307 seconds')
```

**Diagnostic Information (available on every device)**
```
(String) NEQXXXXXXX:1
(String) TEMPERATURE_OFFSET
11/10/22 21:06:51.500 RPC Server (Port 2001): Info: Connection from ::ffff:172.30.32.1:50874 accepted. Client number: 18560
11/10/22 21:06:51.501 RPC Server (Port 2001): Info: RPC server client id for client number 18560 is: 18209
11/10/22 21:06:51.503 RPC Server (Port 2001): Info: Client number 18560 is calling RPC method: getValue (1) Parameters:
(String) NEQXXXXXXX:1
(String) VALVE_STATE
11/10/22 21:06:51.535 RPC Server (Port 2001): Info: Connection from ::ffff:172.30.32.1:50888 accepted. Client number: 18561
11/10/22 21:06:51.535 RPC Server (Port 2001): Info: RPC server client id for client number 18561 is: 18210
11/10/22 21:06:51.537 RPC Server (Port 2001): Info: Client number 18561 is calling RPC method: getValue (1) Parameters:
(String) NEQXXXXXXX:1
(String) WINDOW_OPEN_TEMPERATURE
11/10/22 21:06:56.455 RPC Server (Port 2001): Info: Connection from ::ffff:172.30.32.1:50892 accepted. Client number: 18562
11/10/22 21:06:56.455 RPC Server (Port 2001): Info: RPC server client id for client number 18562 is: 18211
11/10/22 21:06:56.457 RPC Server (Port 2001): Info: Client number 18562 is calling RPC method: getAllSystemVariables (1) Parameters:
11/10/22 21:07:06.570 RPC Server (Port 2001): Info: Connection from ::ffff:172.30.32.1:40600 accepted. Client number: 18563
11/10/22 21:07:06.571 RPC Server (Port 2001): Info: RPC server client id for client number 18563 is: 18212
11/10/22 21:07:06.575 RPC Server (Port 2001): Info: Client number 18563 is calling RPC method: clientServerInitialized (1) Parameters:
(String) Homematic-BidCos-RF
11/10/22 21:07:06.609 RPC Server (Port 2001): Info: Connection from ::ffff:172.30.32.1:40614 accepted. Client number: 18564
11/10/22 21:07:06.610 RPC Server (Port 2001): Info: RPC server client id for client number 18564 is: 18213
11/10/22 21:07:06.611 RPC Server (Port 2001): Info: Client number 18564 is calling RPC method: clientServerInitialized (1) Parameters:
(String) Homematic-BidCos-RF
11/10/22 21:07:12.717 MAX packet received (Max-CUNX, RSSI: 0x50): 0900060400000000000D
11/10/22 21:07:26.456 RPC Server (Port 2001): Info: Connection from ::ffff:172.30.32.1:50688 accepted. Client number: 18565
11/10/22 21:07:26.456 RPC Server (Port 2001): Info: RPC server client id for client number 18565 is: 18214
11/10/22 21:07:26.458 RPC Server (Port 2001): Info: Client number 18565 is calling RPC method: getAllSystemVariables (1) Parameters:
11/10/22 21:07:33.856 IPC Server: Info: Client number 0 is calling RPC method: lifetick Parameters:
11/10/22 21:07:42.942 MAX packet received (Max-CUNX, RSSI: 0x50): 0900060400000000000D
```

**Expected behavior**
I expect clear log without any notification.

**Additional context**

**Comment by SukramJ** [comment]
> I expect clear log without any notification.

Simply check why your Backend  is not able to connect to HA.

> ::ffff:172.30.32.1

Try to use a Ip4v setup up by setting a callback_ip in config (see docs)

I am not wiling to read a linked thread from the community forum. What is the relevant content?

**Comment by SukramJ** [comment]
Ensure that you use ipv4.

**Comment by alibababa82** [comment]
I´ve got now this. But I think, it won´t solve it...
`(String) Homematic-BidCos-RF
11/10/22 22:29:59.488 MAX packet received (Max-CUNX, RSSI: 0x50): 0900060400000000000D
11/10/22 22:30:03.391 RPC Server (Port 2001): Info: Connection from 172.30.32.1:48010 accepted. Client number: 614
11/10/22 22:30:03.391 RPC Server (Port 2001): Info: RPC server client id for client number 614 is: 585
11/10/22 22:30:03.393 RPC Server (Port 2001): Info: Client number 614 is calling RPC method: getAllSystemVariables (1) Parameters:
11/10/22 22:30:03.501 RPC Server (Port 2001): Info: Connection from 172.30.32.1:48014 accepted. Client number: 615
11/10/22 22:30:03.502 RPC Server (Port 2001): Info: RPC server client id for client number 615 is: 586
11/10/22 22:30:03.503 RPC Server (Port 2001): Info: Client number 615 is calling RPC method: clientServerInitialized (1) Parameters:
(String) Homematic-BidCos-RF
11/10/22 22:30:18.536 RPC Server (Port 2001): Info: Connection from 172.30.32.1:52098 accepted. Client number: 616
11/10/22 22:30:18.536 RPC Server (Port 2001): Info: RPC server client id for client number 616 is: 587
11/10/22 22:30:18.538 RPC Server (Port 2001): Info: Client number 616 is calling RPC method: clientServerInitialized (1) `

Edit:
To setting a callback_ip in config - you mean what exactly? To fill IP in pop-up window of integration setting?

**Comment by SukramJ** [comment]
What do you want to solve? This is all Info log level.

**Comment by alibababa82** [comment]
I want to solve this message...
`HOMEMATICIP_LOCAL-XmlRPC-Server received no events. No callback events received for interface Homematic-BidCos-RF 300s.`

**Comment by SukramJ** [comment]
What is in the HA log?
Callback_ip is only needed if you are in a containerized environment, or you have a firewall between HA and backend. Guess we don‘t need it here, if you ensure ipv4 is used.

**Comment by SukramJ** [comment]
Still you backend is not able to connect to HA. Please check this.
Anything noteworthy abort you HA setup?

**Comment by alibababa82** [comment]
HA log is showing this... I have no problem for about 30mins. :-(

`Logger: hahomematic.client
Source: runner.py:119
First occurred: 23:09:19 (2 occurrences)
Last logged: 23:09:19

is_callback_alive: Callback for Homematic-BidCos-RF has not received events for 304 seconds')
reconnect: waiting to re-connect client Homematic-BidCos-RF for 120s`

`2022-11-10 23:09:19.437 WARNING (MainThread) [hahomematic.client] is_callback_alive: Callback for Homematic-BidCos-RF has not received events for 304 seconds')
2022-11-10 23:09:19.479 WARNING (MainThread) [hahomematic.client] reconnect: waiting to re-connect client Homematic-BidCos-RF for 120s`

**Comment by SukramJ** [comment]
Again:
Your backend is not able to connect to HA. Please check this.
Anything noteworthy abort you HA setup?

**Comment by alibababa82** [comment]
I have clean log, so no problems with HA setup. Can you please help me, how can I check and what I´m looking for? I´m trying to solve it for three days

**Comment by danielperna84** [comment]
As it is unclear right now: are you using Homegear on a separate Raspberry as mentioned [here](https://github.com/devRoemer/hassio-homegear-generic/discussions/8), or are you using the Homegear addon as mentioned in this issue?

In any case, the problem seems to be, that Homegear is unable to establish a connection to Home Assistant to push events. Therefore Home Assistant can _control_ the devices, but Homegear is unable to respond to Home Assistant that the action has been executed.

As SukramJ is saying, you'll have to figure out why Homegear is unable to do this. Connectivity issues are outside the scope of what we as developers can do, as this depends on your local setup. If you're running Homegear on the Raspberry, maybe there's a firewall blocking the outgoing connection to Home Assistant. Or maybe it's related to you IPv4 / IPv6 mix. The Homegear logs are showing the remote address (Home Assistant) as `::ffff:172.30.32.1`, which is the IPv6 variant of addressing an address that is actually IPv4. This might be fixed by configuring Homegear to explicitly bind to an IPv4 address so IPv6 is not used.

That being said, the address range is looking like it's Docker. So did you move from the Raspberry installation to the Add-on? If you are using the add on, have a look at [this](https://github.com/devRoemer/hassio-homegear-generic/issues/3), which might help you to get access to the shell within the addon. From there you should check if connections to `172.30.32.1` are possible.

**Comment by alibababa82** [comment]
Hi guys, I´m sorry, but I don´t want to spend more time regarding this issue. Even after three days, I had not been able to solve it, so I´m going with classic built-in Homematic integration configured via yaml file. I found, that author of Homegear addon has posted working yaml config file and it´s working, so I´m going this way. I like your integration, but unfortunately it doesn´t work for me. To solve this issue my knowledge is also limited. Anyway thank you for your help.

**Comment by SukramJ** [comment]
I doesn't matter which integration you use, your problems will be the same. The difference is that the new integration is analysing the callbacks and displaying problems. No callbacks means no updates for your devices, that could be permanently or just shorter time slots.
Here we expect callbacks every 15s and start displaying warnings after 300s of receiving no callbacks. 

But as long as you don't answer any questions and provide more information, apart from logs, it makes no sense to go on here, and this ticket can be closed.
