### ISSUE TITLE
HmIP-PS-2 support

### ISSUE THREAD

**Issue by germama** [SukramJ/hahomematic#705]
HmIP-PS works perfectly. I have a couple of very new HmIP-PS-2 devices which are identified by HA 2022.11 as unsupported devices. Should this actually work or is additional support required for HmIP-PS-2? Thanks for the great work so far!

**Comment by danielperna84** [comment]
You really should fill out the issue template!

I assume you are still using the old integration based on [pyhomematic](https://github.com/danielperna84/pyhomematic). You have to switch to the new integration: https://github.com/danielperna84/custom_homematic

**Comment by germama** [comment]
I used the official HM 2022.11 docker container, therefore I was wondering. I will investigate what the built in pyhomematic version ist, thx so far.

**Comment by SukramJ** [comment]
I think this can be closed
