### ISSUE TITLE
custom_homematic: Should it be possible to see in HA when button of HmIP-STH is pressed?

### ISSUE THREAD

**Issue by kic68** [SukramJ/hahomematic#709]
Hi,

I am feeling stupid at the moment - but should it be possible to see in HA when the button of a HmIP-STH Thermostat is pressed?

I would very much like to use that button to trigger an automation, but in HA I cannot see the button anywhere, not in the device overview, not in the Triggers/Device list, not even while listening to all (*) events and pressing the button many times.  Using the latest Raspberrymatic version.

If that should work somehow, could you please describe how?
Thanks and best regards,
Torben

**Comment by danielperna84** [comment]
No, the button can't be used that way. There's nothing in the [paramset](https://github.com/danielperna84/pydevccu/blob/62e657e0c03c9166f24e625ba1278d75453e292c/pydevccu/paramset_descriptions/HmIP-STH.json#L10690). Typically for button-devices there's something like `PRESS_SHORT`, `PRESS_LONG` etc.. But the STH doesn't have those.

**Comment by kic68** [comment]
Hi Daniel,

thanks for the super fast answer. It's a pity they don't offer this, but at least I can now stop searching.

Virtual buttons in HA it will be then :) 

Greetings from Munich
Torben
