### ISSUE TITLE
Support for HM-MOD-EM-8

### ISSUE THREAD

**Issue by lebetz** [SukramJ/hahomematic#710]
DONT'T DELETE THIS.

**Is your feature request related to a problem? Please describe.**
I have a HM-MOD-EM-8 and like to use it in Home Assistant

**Additional context**
At the moment I only use the channels in shutter contact mode. So it would be sufficient for me if this would be supported.

**Comment by SukramJ** [comment]
This device is already supported. What are you missing?

**Comment by lebetz** [comment]
You're right. It was still using official Integration for some reason. After again enabling the custom Integration, it works.
