### ISSUE TITLE
Support for HM-LC-Sw2PBU-FM

### ISSUE THREAD

**Issue by lebetz** [SukramJ/hahomematic#711]
DONT'T DELETE THIS.

**Is your feature request related to a problem? Please describe.**
I use a HM-LC-Sw2PBU-FM for my lights and like to have it supported

**Describe the solution you'd like**
Support HM-LC-Sw2PBU-FM

**Comment by SukramJ** [comment]
This device is already supported. What are you missing?
Did you install the integration? Please post screenshots!

**Comment by lebetz** [comment]
You're right. It was still using official Integration for some reason. After again enabling the custom Integration, it works.
