### ISSUE TITLE
HmIP-SWSD is not a binary sensor and does not use device_class: smoke

### ISSUE THREAD

**Issue by ChristophCaina** [SukramJ/hahomematic#712]
**Is your feature request related to a problem? Please describe.**
The HmIP-SWSD Smoke detectors provides the sensor "Status"
This sensor is using the device_class: _homematicip_local__smoke_detector_alarm_status_

Also, it's probably not a type of "binary_sensor".

HomeAssistant does have a built in device class "smoke" for binary sensors.
It would make sense in my opinion, to assign the status to this device class, in order to get it used in blueprints and other options where entity filters for device_class: smoke are done... (example blueprint)

https://www.it-und-hausautomation-blog.de/feueralarm/

Or does the state sensor provides more information rather than on / off ?

**Describe the solution you'd like**
HmIP_SWD Smoke detectors status should be binary_sensor and device_class: smoke

**Describe alternatives you've considered**
it would probably be possible to use template sensors... ?

**Additional context**

**Comment by SukramJ** [comment]
Simply create a [template binary sensor](https://www.home-assistant.io/integrations/template/#binary_sensor) to match your desired behaviour.

**Comment by ChristophCaina** [comment]
Hi @SukramJ, yes, that would work - but is there any specific reason why the sensor does not use this device_class by default?
Creating template sensors for those devices etc. can only be considered as a workaround in my eyes - since it would be required to create additional sensors every time when a new device will be added for example.

Also, I would really like to avoid creating additional sensors and templates that only mirror an existing sensor...
So.. does the current sensor support more information than a binary state (on / off) ?

If yes - what states does it have?

**Comment by SukramJ** [comment]
1. This is  a sensor because is has multiple states, and these states can be translated by setting a custom device_class.
```
"homematicip_local__smoke_detector_alarm_status": {
      "idle_off": "Untätig",
      "primary_alarm": "Primär-Alarm",
      "intrusion_alarm": "Einbruch-Alarm",
      "secondary_alarm": "Sekundär-Alarm"
  },
```
2. `smoke` is a binary_sensor device_class and not a sensor device_class

This is an auto generated sensor with no custom handling except state translation, and every further customization should be done by the user. 
As you can see this device could also be uses as an alarm siren.

**Comment by ChristophCaina** [comment]
all right :)
thanks for this information 👍 

In this case, I fully understand and agree that it should not be a binary sensor.
I just came accross that, after switching from the homematic ip integration to this one, since the detectors were type binary and device_class: smoke in the default homematic ip integration.
