### ISSUE TITLE
HmIP-KRC4 - Buttons in Automation not working

### ISSUE THREAD

**Issue by BiasF** [SukramJ/hahomematic#713]
DONT'T DELETE THIS.

Please answer all questions as good as possible.

Language: english/german

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you have read the release notes at https://github.com/danielperna84/custom_homematic/releases. 

Make sure you are running the latest version of the custom_component (and Home Assistant) before reporting an issue.

ENSURE that your Backend (CCU/Homegear/...) is working as expected and connected devices are controllable.

**custom_component version (if applicable):**
1.21.3

**known last working custom_component version (if applicable):**
-

**Home Assistant version (if applicable):**
2022.11.x (Newest one)

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, HA-Addon ...): CCU3 as HASS Addon (RaspberryMatic)
- OS (Original, RaspberryMatic, debmatic ...): RaspberryMatic
- Version:  3.65.11.20221005
--

<br class="Apple-interchange-newline">

**Problem-relevant configuration:**

Do you use tls? Yes
Do you use callback? I think yes
Do you use username and password? yes
Which interfaces do you use (hmip/bidcos/wired)? HMIp

**Describe the bug**
The Automations is not triggert if button is pressed.
<img width="968" alt="image" src="https://user-images.githubusercontent.com/5191818/204076744-7f743cd4-6eee-4c9d-8809-fb8ee2b261bf.png">

**To Reproduce**
1. Create Automation
2. Include a trigger like this one:
```
platform: device
domain: homematicip_local
device_id: XX
event_type: homematic.keypress
interface_id: CCU3-HmIP-RF
address: XX
type: press_short
subtype: 4
```

**Screenshots (if applicable)**
- CCU firewall
<img width="448" alt="image" src="https://user-images.githubusercontent.com/5191818/204077093-26b58abc-645e-43e7-86c3-65674557ed17.png">

**Relevant HA log entries (full log)**
```
No Log available 

```

**Diagnostic Information (available on every device)**
```
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.11.4",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "5.15.61-v8",
    "supervisor": "2022.11.2",
    "host_os": "Home Assistant OS 9.3",
    "docker_version": "20.10.18",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "adaptive_lighting": {
      "version": "1.2.0",
      "requirements": []
    },
    "hacs": {
      "version": "1.28.3",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "homematicip_local": {
      "version": "1.21.3",
      "requirements": [
        "hahomematic==2022.11.2"
      ]
    },
    "auto_backup": {
      "version": "1.3.0",
      "requirements": []
    },
    "alexa_media": {
      "version": "4.3.2",
      "requirements": [
        "alexapy==1.26.4",
        "packaging>=20.3",
        "wrapt>=1.12.1"
      ]
    },
    "waste_collection_schedule": {
      "version": "1.27.0",
      "requirements": [
        "icalendar",
        "recurring_ical_events",
        "icalevents",
        "bs4"
      ]
    }
  },
  "integration_manifest": {
    "domain": "homematicip_local",
    "name": "Homematic(IP) Local",
    "config_flow": true,
    "documentation": "https://github.com/danielperna84/custom_homematic",
    "issue_tracker": "https://github.com/danielperna84/hahomematic/issues",
    "requirements": [
      "hahomematic==2022.11.2"
    ],
    "ssdp": [
      {
        "manufacturer": "EQ3",
        "manufacturerURL": "http://www.homematic.com"
      }
    ],
    "zeroconf": [],
    "homekit": {},
    "dependencies": [],
    "codeowners": [
      "@danielperna84",
      "@SukramJ"
    ],
    "iot_class": "local_push",
    "loggers": [
      "hahomematic"
    ],
    "version": "1.21.3",
    "integration_type": "hub",
    "is_built_in": false
  },
  "data": {
    "config": {
      "entry_id": "cb19df9d7a301d4774b12a0170923e5a",
      "version": 1,
      "domain": "homematicip_local",
      "title": "CCU3",
      "data": {
        "instance_name": "CCU3",
        "host": "de838cd8-raspberrymatic",
        "username": "**REDACTED**",
        "password": "**REDACTED**",
        "tls": false,
        "verify_tls": false,
        "callback_host": null,
        "callback_port": null,
        "json_port": null,
        "interface": {
          "HmIP-RF": {
            "port": 2010
          },
          "BidCos-RF": {
            "port": 2001
          },
          "VirtualDevices": {
            "port": 9292,
            "path": "/groups"
          }
        }
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": "DBE9974F84",
      "disabled_by": null
    },
    "platform_stats": {
      "binary_sensor": 11,
      "climate": 6,
      "lock": 1,
      "sensor": 20,
      "switch": 2
    },
    "devices": [
      "HmIP-DLD",
      "HmIP-FSM",
      "HmIP-FSM16",
      "HmIP-HEATING",
      "HmIP-KRC4",
      "HmIP-STHD",
      "HmIP-STHO",
      "HmIP-SWDM",
      "HmIP-eTRV-2",
      "HmIP-eTRV-B"
    ]
  }
}

```

**Expected behavior**
The Automation should be triggert if I press a button on my HmIP-KRC4

**Comment by SukramJ** [comment]
You read the [docs](https://github.com/danielperna84/custom_homematic#events-for-homematicip-devices)?

**Comment by BiasF** [comment]
Yes, but on this page: https://github.com/danielperna84/custom_homematic

There is no Hint to the "Events for HomematicIP devices" part. 

<img width="870" alt="image" src="https://user-images.githubusercontent.com/5191818/204081172-d766db9c-afd6-4263-acaa-e56e40053d62.png">

**Comment by SukramJ** [comment]
???

Check it again.

**Comment by BiasF** [comment]
ok found.
But if you explicitly search the topic "buttons", you find the upper part first and wonder why it doesn't work. The precondition should be mentioned in this section. Or the part "Events for HomematicIP devices" should be moved further up. 

But ok, now it works as aspected. Thanks for clarifying.

**Comment by SukramJ** [comment]
Just add a pull request to improve the documentation.
