### ISSUE TITLE
Interface identification over json not possible

### ISSUE THREAD

**Issue by SukramJ** [SukramJ/hahomematic#72]
Hi @danielperna84.

currently we use this code to identify the interface a device (name) belongs to:
https://github.com/danielperna84/hahomematic/blob/0ac8ef8efbca579984689dc4cf4bffdd088dd206/hahomematic/client.py#L429-L448

Result of `Interface.listInterfaces` is always:

[{'name': 'CUxD', 'port': 8701, 'info': 'CUxD'}, 
{'name': 'BidCos-RF', 'port': 32001, 'info': 'BidCos-RF'}, 
{'name': 'VirtualDevices', 'port': 39292, 'info': 'Virtual Devices'}, 
{'name': 'HmIP-RF', 'port': 32010, 'info': 'HmIP-RF'}]

This only works, if the configured port matches a port of the list (+30000,+40000, -10000 or other additions doesn't matter here).
It possible to configure (e.g. in Docker) other ports than the default one: maybe use port 12345 for hmip. In such a case name resolution doesn't work.

I haven't found any other way to identify the interface, except with a different convention that might not work either.

My solution: **Get rid of the interface for name resolution.**
The current assumption is that addresses are **unique** for an **interface**. 
My assumption is that addresses are **unique** for a **ccu** (bigger scopes don't matter here).

Did I miss something?

**Comment by danielperna84** [comment]
It's been a while since I have implemented this. But AFAIK I did it this way for performance reasons. With pyhomematic we're getting all the names on every startup, which would take too long when looping over all interfaces for every device. However with hahomematic the names can be cached, so this only would be a performance hog once. I would be fine with that.

**Comment by SukramJ** [comment]
I'd stays with the single `Device.listAllDetail` call, but the resulting names dict will be {address, name} and not {interface, {address, name}}.

**Comment by danielperna84** [comment]
Sounds ok to me. 👍

**Comment by SukramJ** [comment]
Thanks  a lot.
