### ISSUE TITLE
Problem with case sensitivity of user name

### ISSUE THREAD

**Issue by DennisWilken** [SukramJ/hahomematic#720]
DONT'T DELETE THIS.

Please answer all questions as good as possible.

Language: english or german

**custom_component version (if applicable):**
1.22.0

**Home Assistant version (if applicable):**
2022.11

**CCU version:**
- Docker running on raspberry 3
- Version:  3.65.11.20221005 

**Problem-relevant configuration:**

Do you use tls? yes
Do you use callback? no
Do you use username and password? yes
Which interfaces do you use (hmip/bidcos/wired)? hmip

**Describe the bug**
The user name in the configuration is case sensitive. In my case "Admin" would be the correct user which should be the default username. However, "admin" is also accepted in the configuration wizzard. Using "admin", the connection to the different interfaces doesn't work. Resulting in error messages like the one shown below. 

This is not an urgent request. A remark on the git website might be sufficient. However, it took me multiple hours to figure out that there is something wrong with the username even though it was accepted. One option could be to pre-fill the form with "Admin".

Example Log
```
Logger: hahomematic.json_rpc_client
Source: custom_components/homematicip_local/control_unit.py:123
Integration: Homematic(IP) Local (documentation, issues)
First occurred: 6:41:01 PM (56 occurrences)
Last logged: 9:39:02 PM

_do_login failed: Unable to open session: {'name': 'JSONRPCError', 'code': 501, 'message': 'invalid credentials or too many sessions'}
_post_script failed: Error while logging in via JSON-RPC.
_post failed: Error while logging in via JSON-RPC.
```

**Expected behavior**
If a username is accpeted, a connection to at least one interfaces should be possible.

**Comment by danielperna84** [comment]
This is not an issue in my opinion. The log message clearly indicates, that there probably is an issue with your credentials. Software that is __not__ case sensitive is the __exception__, not the norm. Hence anything else than mentioning this in the documentation is not an option.

**Comment by SukramJ** [comment]
I agree to @danielperna84
