### ISSUE TITLE
Not all button events are transmitted to home assistant

### ISSUE THREAD

**Issue by THorst92** [SukramJ/hahomematic#721]
**custom_component version (if applicable):**
1.22.0

**Home Assistant version (if applicable):**
2022.11.4

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, HA-Addon ...): HA-Addon
- OS (Original, RaspberryMatic, debmatic ...): RaspberryMatic
- Version: 3.65.11.20221005

**Problem-relevant configuration:**

Do you use tls? No
Do you use callback? Callback IP: 0.0.0.0, no XML-RPC port
Do you use username and password? yes
Which interfaces do you use (hmip/bidcos/wired)? hip

**Describe the bug**
Ich habe drei HMIP-FROLL, HMIP-BROLL und zwei HMIP-BSM. Ich möchte die Taster als Trigger in HA bzw. NodeRed nutzen. Daher nehme ich "homematic.keypress" als Trigger. Von allen Tasten kommt nur bei einer (einem HMIP-FROLL) das "homematic.keypress". Bei allen anderen nicht.

**Comment by SukramJ** [comment]
Im Teil den Du heraus gelöscht hat ist der Link zu Doku.
Bitte die Doku gelegentlich und vor öffnen eines Issues vollständig lesen, da sich natürlich von Zeit zu Zeit was ändern kann.
Entsprechen wichtig ist natürlich auch [dieser Abschnitt](https://github.com/danielperna84/custom_homematic#events-for-homematicip-devices).

**Comment by THorst92** [comment]
Danke für die Rückmeldung! Tut mir leid für das Erstellen dieses Issues. Dachte, dass dies nur auf die genannten Produkte zutrifft.
Funktioniert nun ohne Probleme.
