### ISSUE TITLE
Does not work in HA 2022.11.5?

### ISSUE THREAD

**Issue by Taxxian** [SukramJ/hahomematic#724]
DONT'T DELETE THIS.

Please answer all questions as good as possible.

Language: german

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you have read the release notes at https://github.com/danielperna84/custom_homematic/releases. 

Make sure you are running the latest version of the custom_component (and Home Assistant) before reporting an issue.

ENSURE that your Backend (CCU/Homegear/...) is working as expected and connected devices are controllable.

**custom_component version (if applicable):**
1.23.0.b0

**known last working custom_component version (if applicable):**
last before this one

**Home Assistant version (if applicable):**
2022.11.5

**CCU version:**
- OS RaspberryMatic

Do you use tls? NO
Do you use callback? NO
Do you use username and password? YES
Which interfaces do you use (hmip/bidcos/wired)? **hmip**

**Describe the bug**

Addon does not launch, says only "Fehler beim Einrichten", LOG contains nothing.

Found the information that "HA 2022.12" is required, but that is not even released yet... is that my problem? Is there any way to downgrade?

**To Reproduce**
?

**Screenshots (if applicable)**

**Relevant HA log entries (full log)**
```
nothing
```

**Diagnostic Information (available on every device)**
```


```

**Expected behavior**

**Additional context**

**Comment by SukramJ** [comment]
HA 2022.12 Beta is available.
So why do you install a version with an explicit marker in the release notes?

**Comment by SukramJ** [comment]
Yes downgrade (see HACS docs).
