### ISSUE TITLE
XML RPC callback configuration not applied

### ISSUE THREAD

**Issue by gMoellemann** [SukramJ/hahomematic#731]
DONT'T DELETE THIS.

Please answer all questions as good as possible.

Language: english/german

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you have read the release notes at https://github.com/danielperna84/custom_homematic/releases. 

Make sure you are running the latest version of the custom_component (and Home Assistant) before reporting an issue.

ENSURE that your Backend (CCU/Homegear/...) is working as expected and connected devices are controllable.

**custom_component version (if applicable):**
1.22.0

**known last working custom_component version (if applicable):**
N/A

**Home Assistant version (if applicable):**
2022.11.5

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, HA-Addon ...): Raspi 3B+ with RPI-RF-MOD
- OS (Original, RaspberryMatic, debmatic ...): RaspberryMatic
- Version: 3.65.11.20221005

**Problem-relevant configuration:**

Do you use tls? No
Do you use callback? Yes
Do you use username and password? Yes
Which interfaces do you use (hmip/bidcos/wired)? hmip

**Describe the bug**
I'm running Home Assistant inside a kubernetes cluster, with my RaspberryMatic on a dedicated rpi3 with RPI-RF-MOD. When I try to use the Homematic(IP) Local integration, I find the RaspberryMatic, but no devices are discovered.

Switching the networking mode of my homeassistant container inside kubernetes to host-network, everything works as expected. But when I hide my container behind a load balancer with a public facing IP (192.168.107.3) and specify this IP as the XML RPC callback host, along with the correct ports (50080 for XML RPC, 60080 for JSON RPC), no devices are found.

The XML RPC Server seems to be working, since I can query it under http://192.168.107.3:50080/RPC2.

Also, the logs of the RaspberryMatic lists a XmlRpc transport error calling listDevices on the IP address of my Home Assistant container inside the kubernetes cluster (i.e. 10.42.1.42:56049/RPC2)

Am I missing something here? Why is my RaspberryMatic trying to connect to the RPC server under the wrong ip/port?

**Comment by SukramJ** [comment]
It‘s better readable if you add real ips and ports.

I know its working with docker.

**Comment by SukramJ** [comment]
Best would be a plan / diagram with all relevant ips.

**Comment by gMoellemann** [comment]
Not really sure what that information adds. The basic gist is:

Give Home Assistant access to the host network and it works.
Hide Home Assistant behind a bunch of port mappings and it doesn't work, even with RPC callback configured correctly (as evident by the fact, that the server can be accessed manually).

Is there any way to log what information about the RPC server is actually send to the homematic?

**Comment by SukramJ** [comment]
If you don‘t want to add more data to make easier to understand for me and improve the communication it‘s ok, but then I am out.

Have fun with switching to debug in HA.

**Comment by danielperna84** [comment]
> Not really sure what that information adds.

> Hide Home Assistant behind a bunch of port mappings and it doesn't work

It could help to identify routing / port forwarding issues or whatever is causing the problems. Because apparently it's a connectivity problem, which is more tricky to set up with _fancy_ container environments.

**Comment by gMoellemann** [comment]
I found my mistake. I defined an arbitrary JSON RPC port in the configuration interface of the Homematic(IP) Local integration.

Am I correct that the integration only opens an XML RPC server and connects to a JSON RPC server on the homematic?

**Comment by SukramJ** [comment]
Communication to ccu uses JSONRPC and XMLRPC.

**Comment by gMoellemann** [comment]
Where are they running, respectively?

**Comment by SukramJ** [comment]
???

**Comment by gMoellemann** [comment]
Does the ccu or HA run the JSON RPC server?

**Comment by SukramJ** [comment]
CCU.

**Comment by gMoellemann** [comment]
Thanks. That was my misconception.

I assumed the JSON RPC server to be running on HA as well. So when I configured a port for it, the connection failed. Leaving it blank fixed the issue for me.

**Comment by SukramJ** [comment]
All ports are [documented](https://github.com/danielperna84/custom_homematic#firewall).
