### ISSUE TITLE
SV Alarmessage not updated

### ISSUE THREAD

**Issue by hklages** [SukramJ/hahomematic#738]
DONT'T DELETE THIS.

Please answer all questions as good as possible.

Language: english/german

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you have read the release notes at https://github.com/danielperna84/custom_homematic/releases. 

Make sure you are running the latest version of the custom_component (and Home Assistant) before reporting an issue.

ENSURE that your Backend (CCU/Homegear/...) is working as expected and connected devices are controllable.

**custom_component version (if applicable):**
1.23.0

**known last working custom_component version (if applicable):**
-

**Home Assistant version (if applicable):**
2022.12.2

**CCU version:**
Finished Boot: 3.65.11.20221005 (raspmatic_oci_arm64)

**Problem-relevant configuration:**

Do you use tls? no
Do you use callback? no
Do you use username and password? yes
Which interfaces do you use (hmip/bidcos/wired)? hmip

**Describe the bug**
The intrinsic system variable "Alarmmeldungen" is 0 (main page Alarmmeldungen) but the Home Assistant "sensor.raspberrymatic_sv_alarmmeldungen" shows state 1. 

**To Reproduce**

**Screenshots (if applicable)**
- CCU firewall
- integrations view
- device view
- enity view

**Relevant HA log entries (full log)**
```


```

**Diagnostic Information (available on every device)**
```


```

**Expected behavior**
Would expect that they are in sync

**Additional context**

**Comment by SukramJ** [comment]
> The intrinsic system variable "Alarmmeldungen" is 0 (main page Alarmmeldungen) but the Home Assistant "sensor.raspberrymatic_sv_alarmmeldungen" shows state 1.

Why do you think there must be a relation?
Does the alarmmeldungen sysvar change in CCU WebUI? `WriteLine(dom.GetObject("Alarmmeldungen").Value());`
Do other sysvars change?

**Comment by hklages** [comment]
Thanks for you fast response - I checked with the homematic forum: 

There seems to be a "bug" in CCU:  Homematic GUI and the intrinsic sysvar are sometimes not in sync and have to be manually synced - see this [discussion](https://homematic-forum.de/forum/viewtopic.php?f=19&t=63542&hilit=alarmmeldung&sid=fa73e67e151a9432405d6f4cd1b3d9da&start=40#p731652)

I did a reset and now the Homematic GUI, the sysvar and Home Assistant sensor are in sync and I can use the Home Assistant sysvar-sensor to trigger a notification to my smartphone in case of an alarm.

(Summary: not a bug in the integration but instead in HomematicIP - or maybe a feature :-)

**Comment by hklages** [comment]
Could it be that there is a typo in the sensor for the "Servicemeldungen". SV_servicemeldungen instead of Sv_servicemeldungen --> making it unavailable? 

![sv servicemeldungen](https://user-images.githubusercontent.com/17273119/207037813-3bee9add-03c9-41c6-a70c-9e9833b891e7.jpg)

**Comment by SukramJ** [comment]
Current version does not have Servicemeldungen as dedicated entity, so this is a left over of previous versions. The Servicemeldungen count is included in the `sensor.{instance_name}` hub entity.
This one can be removed. Upper lower case maked no difference in the entity_id.

1.24.0 will habe a sv_servicemeldungen again, because we no longer need the dedicated hub entity `sensor.{instance_name}`
