### ISSUE TITLE
Switching thermostate to off or trigger hvac mode to off trigger heating mode

### ISSUE THREAD

**Issue by nightwatcher74** [SukramJ/hahomematic#741]
DONT'T DELETE THIS.

Please answer all questions as good as possible.

Language: german

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.
☑️
Make sure you have read the release notes at https://github.com/danielperna84/custom_homematic/releases. 
☑️
Make sure you are running the latest version of the custom_component (and Home Assistant) before reporting an issue.
☑️
ENSURE that your Backend (CCU/Homegear/...) is working as expected and connected devices are controllable.
☑️

**custom_component version (if applicable):**
1.23.0

**known last working custom_component version (if applicable):**
- (I switched to hahomemeatic today)

**Home Assistant version (if applicable):**
2022.12.1

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, HA-Addon ...): CCU3
- OS (Original, RaspberryMatic, debmatic ...): original
- Version: 3.65.11

**Problem-relevant configuration:**

Do you use tls? No
Do you use callback? No
Do you use username and password? Yes
Which interfaces do you use (hmip/bidcos/wired)? Bidcos

**Describe the bug**
Today i switched from the integrated homematic addon to hahomemaric.
The most things work well but when i press the off button in an lovelace thermostat card or trigger hvac mode to off in a script it will be switched to heating (with the same temperature) instead to off (with 4.5 grad temperature)
With the integrated homematic addon all was working well.
Nothing other was changed

Thanks 

**To Reproduce**

**Screenshots (if applicable)**
- CCU firewall
- integrations view
- device view
- enity view

**Relevant HA log entries (full log)**
```


```

**Diagnostic Information (available on every device)**
```


```

**Expected behavior**

**Additional context**

**Comment by SukramJ** [comment]
About which device are you talking about?
What is then min temperature set in the device?

This is an integration is not an addon.

**Comment by nightwatcher74** [comment]
The device is from type HM-CC-RT-DN (Homematic classic) and in the CCU3 the minimum Temp is off (this means 4.5 Grad) here I know that i should no change something because of the "heating" and all is deafult and It worked all well with the old in HA included addon.

**Comment by SukramJ** [comment]
Hi @baxxy13, do you have an HM-CC-RT-DN?
Could you please retest?

**Comment by nightwatcher74** [comment]
FYI with a hmip device it is working but it changes first to heating and after 2-3sec then to off... and then it is and stays "off" and 4.5 degree! :)

**Comment by SukramJ** [comment]
We have to switch to heating before switching to 4.5 degree, otherwise the device will not stay off.
There is no off mode for HmIP devices!

**Comment by Baxxy13** [comment]
Hmm, for me it looks right.
![GIF 12 12 2022 15-55-20](https://user-images.githubusercontent.com/54898249/207077401-50470a2f-5304-470b-aab9-9bbef66366f3.gif)

**Comment by nightwatcher74** [comment]
I'm sorry, but I forgott a very important thing... :( 
I testet a little bit on differnt thermostats it and make some screen records...
on the thermostat itself it's working well but... it's on the group device.. because i have a thermostat on the wall and tho thermostats for heating.. till now i used the (from the ccu3 created) group and here it is not working... ont the wall or heating thermostats all is working well and on the group it's also working well with the "old" addon.

Sorry
Frank

**Comment by nightwatcher74** [comment]
FYI
A group with hmip devices is working well.. it's only a group with classic bidcos devices which have this probelm... (on the same CCU)

**Comment by SukramJ** [comment]
Read [this](https://github.com/danielperna84/hahomematic/issues/554) about heating groups.

Please provide **helpful** information like already mentioned. "is not working" is useless!
It would be helpful, if you would care for the difference between an integration and an addon.

**Comment by nightwatcher74** [comment]
Sorry, for my wrong wording :(
I read the bug/article and when I understand it correctly, on this the probelm is, that in HA the information about the heating group status are nut updated.... 

I checked it again... on the "new" hahomematic addon switch to "off" changes the group at the ccu3 to manual (heating) with the same temperature as before the "switch off" (makes no difference if it is on autmatic 20degree or if it is switched to manually and 23 before or automatic override to 23degree).
So it looks like there is no problem with the feedback... it looks like the temperture is not set to 4.5degree (off) ?!

PLease correct me if I'm wrong.

Thanks
Frank

**Comment by Baxxy13** [comment]
Ich mache mal auf deutsch weiter, hoffe das ist ok.
Kann das Problem bei Ansteuerung der HM-Heizgruppe bestätigen.

"Übeltäter" ist mal wieder eQ-3. 
Die haben die Metadaten bei `SET_TEMPERATURE` versemmelt, nämlich `MIN 5.0` anstatt `MIN 4.5`

Das sieht man auch schön im Log:

```
Logger: hahomematic.generic_platforms.number
Source: custom_components/homematicip_local/climate.py:268
Integration: Homematic(IP) Local (documentation, issues)
First occurred: 17:49:39 (3 occurrences)
Last logged: 17:56:33

number.float failed: Invalid value: 4.5 (min: 5.0, max: 30.0, special: None)
```

Mittels Aus-Button in der WebUI wird MIN 5.0 aber ignoriert und korrekt auf 4.5 gesetzt.

**Comment by nightwatcher74** [comment]
Deutsch ist  mir auch lieber... :) habe leider nicht oft die möglichkeit Englisch zu sprechen, dementsprechnd fällt es mir immer etwas schwer...
Bin beruhigt, das es nicht mein Fehler war... :)

Blöde frage zu diesem Problem...
lässt sich das evtl. sogar nicht auch konfigurierbar machen?
Hintergrund ist der, das man ja ein probelm hat wenn man die "min" Temperatur nicht auf aus (4.5 bzw. 5.0 Grad) sondern auf einen anderen Wert stellen möchte... dann hat man galube ich das gleiche Problem... 
Unabhängig von dieser Problematik mit hm-Heizgruppen mit dem unterschied zu hmip-Heizgruppen... 

VG
Frank

ps. Ich brauche das mit dem konfigurieren nicht, aber es könnte ggfs. anderen helfen?!

**Comment by Baxxy13** [comment]
"Problem" würde ich nicht sagen.
Wenn man bewusst die MIN-Temperatur auf z.B. 10°C setzt dann gibt es halt kein "aus". 
Nutzt man dann "aus" geht das Thermostat eben in Manu / 10° und wird in HA als "heating" angezeigt.

Ich finde das so ok wie es ist.

Wie und ob @SukramJ das Problem mit der HM-Heizguppe angeht kann ich nicht sagen.

Vielleicht eine spezielle Anpassung für den Gerätetyp:

`HssType / Label = HM-CC-VG-1`

**Comment by SukramJ** [comment]
@baxxy Ich sehe das genau so. Grundsätzlich gibt es keine Optionen

Komisch ist, das in der WebUI Off und 5° ausgewählt werden können.

**Comment by Baxxy13** [comment]
Die WebUI Buttons nutzen irgendwie andere Methoden.
Ich frage mal meinen Insider.

Also die MIN/MAX Werte über die WebUI-Buttons sind "hard coded".
https://github.com/eq-3/occu/blob/211b71217d97957e46e86e2dd12950d574e5b2a1/WebUI/www/rega/esp/controls/heating_control.fn#L4-L5

**Comment by SukramJ** [comment]
~~Welche Temperatur wird angezeigt, wenn Du in der WebUI auf OFF schaltest?~~
Hattest Du schon geschrieben.

**Comment by SukramJ** [comment]
> number.float failed: Invalid value: 4.5 (min: 5.0, max: 30.0, special: None)

Das Problem ist, das wir Werte vorm Senden anhand der ParamsetDescription Min/Max validieren, und da steht für `set_temperature` ein Wertebereich von 5-30 Grad drin, also ist die Fehlermeldung korrekt.
Für ein HM OFF müsste man jetzt ein 4.5 Grad senden, und das liegt aber ausserhalb der Validierungsgrenzen.
 
In der nächsten version werde ich die Validierung für den OFF Wert deaktivieren

**Comment by SukramJ** [comment]
Sollte mit der 1.24.1 jetzt funktionieren.
@Baxxy13 kannst Du bitte noch mal testen.

**Comment by nightwatcher74** [comment]
Hallo,

wollt nur noch aml feedback geben... ihr seid einfach spitze :) Funktioniert :)

Ganz viele liebe Grüße
Frank

**Comment by Baxxy13** [comment]
Bin erst jetzt zum testen gekommen.
Auch hier sieht's gut aus!
