### ISSUE TITLE
Control Elements for HMIP-WRC2 not available

### ISSUE THREAD

**Issue by Columbus1964** [SukramJ/hahomematic#742]
DONT'T DELETE THIS.

**Is your feature request related to a problem? Please describe.**
For the HomematicIP Device HMIP-WRC2 is no Control Element available.

**Describe the solution you'd like**
Please provide the controls for the two channels for short press and long press respectively

**Describe alternatives you've considered**

**Additional context**
![Bild](https://user-images.githubusercontent.com/92277454/207010182-e79972c0-1ac3-4715-8896-3137de255ccd.JPG)

**Comment by Baxxy13** [comment]
HmIP "RC's" can only pushed physically at the device. 
There ist no other way. 
Try to push it from the WebUI. ;-)

**Comment by SukramJ** [comment]
This is not a bug in this integration. Pressed buttons on remotes can be used by device triggers in automations (see HA docs).
Also read this integration's [docs](https://github.com/danielperna84/custom_homematic#events-for-homematicip-devices) carefully.
