### ISSUE TITLE
I like to report a new thermostat HmIP-WTH-1

### ISSUE THREAD

**Issue by vanzelf** [SukramJ/hahomematic#744]
DONT'T DELETE THIS.

**Is your feature request related to a problem? Please describe.**
The new thermostat is not supported yet and not visible in home assistant

**Describe the solution you'd like**
Can you add HmIP-WTH-1 to the supported HW?

**Describe alternatives you've considered**
currently I see no other options

**Additional context**
I cannot make a screenshot because I am in the process of installing Homematic(IP) local

**Comment by nightwatcher74** [comment]
I using hahomematic since two days and have also this device (HmIP-WTH-1) and here it is working well and I switched to the hahomatic addon because of a lot of unsuported devices in the Homematic intergration.

Frank

**Comment by SukramJ** [comment]
???
> not visible in home assistant

> in the process of installing Homematic(IP) local

What is your status? You need to install an integrationn to  have devices in Ha

**Comment by SukramJ** [comment]
Please provice data for pydevccu. Description can be found [here](https://github.com/danielperna84/custom_homematic#homematicip_localexport_device_definition).

**Comment by vanzelf** [comment]
Sorry I am very new to GitHub and the different ways to connect Homematic with homeassistant. I have used home assistant on a raspberry pi 3 for quite some time and a separate raspberry pi with raspberrymatic. Now I completely started new and installed HA in proxmox using the same settings but 1 thermostat was missing. The new one. Because I read that sometimes new hardware is not supposed yet I needed to report it here. Does that make sense?

**Comment by SukramJ** [comment]
No, install the desired integration and check carefully. Then report.

**Comment by SukramJ** [comment]
@nightwatcher74 Could you please provide data for pydevccu. 
Description can be found [here](https://github.com/danielperna84/custom_homematic#homematicip_localexport_device_definition).

**Comment by nightwatcher74** [comment]
@SukramJ in the attachment you can find the files :)
but in hahomematic the device is already available... ;)

[homematicip_local.zip](https://github.com/danielperna84/hahomematic/files/10252841/homematicip_local.zip)

**Comment by SukramJ** [comment]
Thanks. It's required for documentation in pydevccu and not for the integration.

**Comment by nightwatcher74** [comment]
Always happy, unfortunately I didn't saw the first request....
