### ISSUE TITLE
Klima Entitäte für ein HmIP-eTRV-C-2 nicht verfügar

### ISSUE THREAD

**Issue by oschmidteu** [SukramJ/hahomematic#756]
Language: as you like -> DEUTSCH 

**custom_component version (if applicable):**
1.24.2

**known last working custom_component version (if applicable):**
1.x.x

**Home Assistant:**
- Version: 2022.12.5
- Installation method (HAOS, supervised, core, venv, Docker): HAOS

**CCU:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, HA-Addon ...): CCu2
- OS (Original, RaspberryMatic, debmatic ...): Original
- Version: 2.61.7

**Problem-relevant configuration:**

Do you use tls? No
Do you use callback? No
Do you use username and password? YES
Which interfaces do you use (hmip/bidcos/wired)? hmip & bidcos

**Describe the bug**
Für ein HmIP-eTRV-C-2 ist die Klima entitäte nicht vorhanden. Bei einem anderen (Baugleichen) Thermostat, wird diese jedoch angezeigt.

**To Reproduce**

**Screenshots (if applicable)**
![Snag_291ca1a](https://user-images.githubusercontent.com/13415307/207558719-698b520c-a566-468a-9058-47c3f5b5730b.png)
![Snag_291e1d8](https://user-images.githubusercontent.com/13415307/207558734-bf6e486b-44c8-472e-9f69-fa9327eaab00.png)

**Relevant HA log entries (press full log) VERY IMPORTANT**
```



```

**Diagnostic Information (available on every device)**
```
[config_entry-homematicip_local-ab6618552178d2008f3c9724557b3bf7.json.txt](https://github.com/danielperna84/hahomematic/files/10226422/config_entry-homematicip_local-ab6618552178d2008f3c9724557b3bf7.json.txt)


```

**Expected behavior**
Klimate & Temp Entität verfügbar.

**Additional context**

**Comment by SukramJ** [comment]
Bitte noch mal die Diagnose Datei richtig anhängen.

Mal folgenden Service ausführen und HA neustarten: `Homematic(IP) Local: Clear the cache`
Zu finden unter Einstellungen --> Dienste

**Comment by oschmidteu** [comment]
Cache leeren & restart hat geholfen 👌
