### ISSUE TITLE
HM-Sen-Wa-Od shows 7.500% instead of 75%

### ISSUE THREAD

**Issue by Guenni9** [SukramJ/hahomematic#767]
Hi, since a week or the like, my HM-Sen-Wa-Od is reporting the filling level with a point. The level is e.g. 75% and it is shown as 7.500%. Don't know what was changed, but is has already shown the correct level in the past.

![image](https://user-images.githubusercontent.com/101923813/208496653-6d84b819-5688-4df2-9ded-2b8858754c6e.png)
![image](https://user-images.githubusercontent.com/101923813/208496357-b41ee414-a3e2-4934-babb-0572c63cd9e3.png)
![image](https://user-images.githubusercontent.com/101923813/208497169-a68c531a-ee47-40b4-ad7a-9ffcad8930e3.png)
Up to about 15 December, it was reported fine, as I can see..
![image](https://user-images.githubusercontent.com/101923813/208497250-ca2a539a-dc96-4c50-b155-68694478a99d.png)
Any idea? It's no great problem, no need to hurry..
Have a nice day,
Günter

**Comment by SukramJ** [comment]
> DONT'T DELETE THIS.

Fill out the issue template!

**Comment by Guenni9** [comment]
Sorry...

**custom_component version (if applicable):**
1.24.3

**known last working custom_component version (if applicable):**
1.x.x (unknown)

**Home Assistant:**
- Version: 2022.12.7
- Installation method:  Home Assistant OS

**CCU:**
- Model: Raspi4
- OS: Raspberrymatic
- Version: 3.65.11.20221218

**Problem-relevant configuration:**

Do you use tls? no
Do you use callback? no
Do you use username and password? yes
Which interfaces do you use (hmip/bidcos/wired)? hmip+bidcos

**Describe the bug**
Level has a point, so it was reported x100 >> 75% was reported as 7.500%

**To Reproduce**
Steps to reproduce the behavior:
Always visible

**Screenshots (if applicable)**
- CCU firewall in CCU
- device config in CCU
- integrations view in HA
- device view in HA
- enity view in HA

**Relevant HA log entries (press full log) VERY IMPORTANT**
```
no errors

```

**Diagnostic Information (available on every device)**
`{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.12.7",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "5.15.76-v8",
    "supervisor": "2022.11.2",
    "host_os": "Home Assistant OS 9.4",
    "docker_version": "20.10.19",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "dwd_weather": {
      "version": "1.2.24",
      "requirements": [
        "simple_dwd_weatherforecast==1.1.5",
        "markdownify==0.6.5"
      ]
    },
    "homematicip_local": {
      "version": "1.24.3",
      "requirements": [
        "hahomematic==2022.12.5"
      ]
    },
    "hacs": {
      "version": "1.29.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "fullykiosk": {
      "version": "1.1.0",
      "requirements": [
        "python-fullykiosk==0.0.11"
      ]
    },
    "nodered": {
      "version": "1.1.2",
      "requirements": []
    },
    "tractive_custom": {
      "version": "0.3.1",
      "requirements": []
    },
    "nuki_ng": {
      "version": "0.2.1",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "homematicip_local",
    "name": "Homematic(IP) Local",
    "config_flow": true,
    "documentation": "https://github.com/danielperna84/custom_homematic",
    "issue_tracker": "https://github.com/danielperna84/hahomematic/issues",
    "requirements": [
      "hahomematic==2022.12.5"
    ],
    "ssdp": [
      {
        "manufacturer": "EQ3",
        "manufacturerURL": "http://www.homematic.com"
      }
    ],
    "zeroconf": [],
    "homekit": {},
    "dependencies": [],
    "codeowners": [
      "@danielperna84",
      "@SukramJ"
    ],
    "iot_class": "local_push",
    "loggers": [
      "hahomematic"
    ],
    "version": "1.24.3",
    "integration_type": "hub",
    "is_built_in": false
  },
  "data": {
    "config": {
      "entry_id": "17060bf6b6f890a15fcc68a549fe5efd",
      "version": 1,
      "domain": "homematicip_local",
      "title": "RaspberryMatic",
      "data": {
        "instance_name": "RaspberryMatic",
        "host": "de838cd8-raspberrymatic",
        "username": "**REDACTED**",
        "password": "**REDACTED**",
        "tls": false,
        "verify_tls": false,
        "callback_host": null,
        "callback_port": null,
        "json_port": null,
        "interface": {
          "HmIP-RF": {
            "port": 2010
          },
          "BidCos-RF": {
            "port": 2001
          }
        }
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": "9D89909640",
      "disabled_by": null
    },
    "platform_stats": {
      "binary_sensor": 23,
      "climate": 2,
      "cover": 8,
      "light": 8,
      "lock": 1,
      "sensor": 22,
      "switch": 31
    },
    "devices": [
      "HM-LC-Dim1T-FM",
      "HM-LC-Dim1T-FM-LF",
      "HM-LC-Sw1-FM",
      "HM-LC-Sw1-Pl-2",
      "HM-LC-Sw2-FM",
      "HM-LC-Sw4-PCB",
      "HM-PB-2-WM55",
      "HM-RC-4-3",
      "HM-RC-8",
      "HM-Sec-MDIR-2",
      "HM-Sen-Wa-Od",
      "HmIP-BSL",
      "HmIP-BWTH",
      "HmIP-CCU3",
      "HmIP-DLD",
      "HmIP-DRBLI4",
      "HmIP-DRSI4",
      "HmIP-FCI6",
      "HmIP-FDT",
      "HmIP-FSI16",
      "HmIP-PS-2",
      "HmIP-SMI55",
      "HmIP-SRH",
      "HmIP-SWDM",
      "HmIP-SWO-PL",
      "HmIP-WTH-2"
    ]
  }
}
`

**Expected behavior**
shown again in percent, not with factor x100

**Additional context**
Maybe some language-setting specific problem?

**Comment by SukramJ** [comment]
Much better. I don't like to ask the same questions again and again.

Any idea what the last working version was?
Do you update regularly?

**Comment by Guenni9** [comment]
Again sorry..
I usually update always as soon as possible, and:

With the latest 1.24.4 it work's again fine!!

Thank you!!

**Comment by SukramJ** [comment]
I recommend not to use the beta channel of this integration.
