### ISSUE TITLE
cover.open_cover_tilt does not work with multiple covers or cover groups (HmIP-FBL)

### ISSUE THREAD

**Issue by Alex-ala** [SukramJ/hahomematic#772]
**custom_component version (if applicable):**
1.24.4

**known last working custom_component version (if applicable):**
I migrated from pyhomematic

**Home Assistant:**
- Version: 2022.12.7
- Installation method: venv

**CCU:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, HA-Addon ...): CCU3
- OS (Original, RaspberryMatic, debmatic ...): Original
- Version: 3.65.11

**Problem-relevant configuration:**

Do you use tls? No
Do you use callback? Yes
Do you use username and password? Yes
Which interfaces do you use (hmip/bidcos/wired)? Local homematic for debugging. All should be done via HA

**Describe the bug**
Since upgrading HA from 2022.10 to 2022.12 AND migrating from pyhomematic to hahhomeatic+homematicip_local blinds (HmIP-FBL) do not work anymore when grouped or called for multiple entities.
Controling a single blind via Homeassistant works fine for both level and tilt. Calling any of the tilt services (open, close, set, toggle, stop) on multiple covers or a group of covers does not do anything. It does not set the tilt position, so that even changing the covers level afterwards will not change to the desired tilt. 

All single covers work perfectly fine when called (via service) or controlled exclusively. The group panel shows all neccessary controls and even displays the current tilt correctly, but controlling it has no effect. 

**To Reproduce**
1. Call a service like
```
service: cover.open_cover_tilt
data: {}
target:
  entity_id:
    - cover.storen_terrasse_links
    - cover.storen_terrasse_rechts
 ```
2. Nothing happens

**Relevant HA log entries (press full log) VERY IMPORTANT**
```
I did not manage to get any relevant log by setting 
"homeassistant.components.homematicip_local": info
"homeassistant.components.hahomematic": info
```

**Expected behavior**
Controling the tilt of multiple covers/blinds should work both via multiple entities in a service aswell as with cover groups.

**Additional context**
I am very unsure if this is an issue with hahomematic, the custom component or maybe even HA itself, as I upgraded both at the same time.
I could not manage to get any logs, so I'm tapping in the dark.

**Comment by SukramJ** [comment]
Cover groups are not part of this integration. 
If a single cover can be controlled by this integration, then this is not a bug in this integration.

**Comment by Alex-ala** [comment]
Alright thanks. I'll test it with HA's current dev branch and report the issue over there if it persists (maybe I'll try it with the old core integration to make sure).
