### ISSUE TITLE
Keine Geräte / skipping interface

### ISSUE THREAD

**Issue by sebudde** [SukramJ/hahomematic#780]
**custom_component version:**
1.25.1

**Home Assistant:**
2022.12.7 (Docker)

**CCU:**
CCU2,  Original, 2.61.7

**Problem-relevant configuration:**
Do you use tls? No
Do you use callback? No
Do you use username and password? yes
Which interfaces do you use? hmip/bidcos

**Describe the bug**
Es werden bei mit nur die Entitäten angezeigt, keine Geräte. 
Auch mehrmaliger Neustart hat nicht geholfen. 
Im Log erhalte ich die Meldungen
`DEBUG (MainThread) [hahomematic.central_unit] create_devices: Starting to create devices for CCU2.`
`DEBUG (MainThread) [hahomematic.central_unit] create_devices: Skipping interface CCU2-HmIP-RF, missing paramsets.`
`DEBUG (MainThread) [hahomematic.central_unit] create_devices: Skipping interface CCU2-BidCos-RF, missing paramsets.`
`DEBUG (MainThread) [hahomematic.central_unit] create_devices: Finished creating devices for CCU2.`

In einer [Diskussion](https://github.com/danielperna84/hahomematic/issues/156#issue-1098468524) hatte ich gelesen, dass das nur Warnungen sind und es wurden in dem Fall auch Geräte gefunden.
Allerdings für mich als Python-Noob liest sich der Code an der Stelle so, dass das `continue` (central_unit.py, Z476) dafür sorgt, dass die Schleife hier für das item beendet wird und das device gar nicht mehr erstellt werden kann. Oder sehe ich das falsch?

Wie könnte ich ansonsten rausfinden, warum meine Geräte nicht erstellt werden?

Danke für eure Hilfe!

**Screenshots**
<img src="https://user-images.githubusercontent.com/651147/209407292-ccb8cb93-c1f3-41b4-88f6-8d9704a69b77.png" width="500">
<img src="https://user-images.githubusercontent.com/651147/209407301-b6ef8621-ca1c-4511-a325-fd8849f77772.png" width="300">
<img src="https://user-images.githubusercontent.com/651147/209407309-ba38261b-f8fc-404f-a32e-2ba7c7b22efd.png" width="300">

**Diagnostic Information**
[config_entry-homematicip_local.json.txt](https://github.com/danielperna84/hahomematic/files/10297501/config_entry-homematicip_local.json.txt)

**Comment by SukramJ** [comment]
> 2022.12.7 (Docker)

Ich denke mal wieder das Standartproblem bei Docker.
Hier ein Auszug aus der Doku:
> If running HA on docker it is recommended to use network_mode: host, or specify [callback host/port](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port).

**Comment by SukramJ** [comment]
Lade bitte noch folgendes hoch:
>**Diagnostic Information (available on every device an)**

**Comment by sebudde** [comment]
> Ich denke mal wieder das Standartproblem bei Docker. Hier ein Auszug aus der Doku:
> 
> > If running HA on docker it is recommended to use network_mode: host, or specify [callback host/port](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port).

Hab's mit Callback versucht, aber das hat nichts verändert. Ich werd' mal versuchen auf host umzustellen.


> Lade bitte noch folgendes hoch:
> 
> > **Diagnostic Information (available on every device an)**

Habe ich ergänzt.

**Comment by SukramJ** [comment]
> Hab's mit Callback versucht, aber das hat nichts verändert

Hierbei muss natürlich auch ein Port forwarding in Docker erstellt werden.

`network_mode: host` wird auch in der HA Beispiel [compose](https://www.home-assistant.io/installation/linux#docker-compose) Datei verwendet.

**Comment by sebudde** [comment]
`network_mode: host` hat funktioniert. Alle Geräte sind da. Danke!
