### ISSUE TITLE
HmIP-MOD-HO lacks state "unknown"

### ISSUE THREAD

**Issue by ivo7B4** [SukramJ/hahomematic#788]
DONT'T DELETE THIS.

This is for issues only
If you have a feature request, add it as a new discussion, or add your point of view to an existing discussion.

Please answer all questions as good as possible.

Language: as you like -> english/DEUTSCH: FYI, both is fine for your reply. Deutsch is my native language.

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you have read the release notes at https://github.com/danielperna84/custom_homematic/releases. 

Make sure you are running the latest version of the custom_component (and Home Assistant) before reporting an issue.

ENSURE that your Backend (CCU/Homegear/...) is working as expected and connected devices are controllable.

**custom_component version (if applicable):**
1.25.1

**known last working custom_component version (if applicable):**
not applicable

**Home Assistant:**
- Version: 2022.12.8
- Installation method (HAOS, supervised, core, venv, Docker): HAOS

**CCU:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, HA-Addon ...): CCU3
- OS (Original, RaspberryMatic, debmatic ...): Original
- Version: 3.65.11

**Problem-relevant configuration:**

Do you use tls? default setting
Do you use callback? default setting
Do you use username and password? yes
Which interfaces do you use (hmip/bidcos/wired)? hmip (wired and Funk)

**Describe the bug**
HmIP-MOD-HO is used for the Hörmann Garagentor. The functionality is mapped to the cover functionality.
Instead of the cover position as with other covers (e.g. for "Jalousien" or "Markisen"), CCU3 reports 3 different states: open, closed, unknown. Hörmann supports humidity control with a so calls "Lüftungsposition". This position is mapped to "unknown" by the CCU (I hope that at some point in time this will be mapped to the right wording if possible, but that's not related to this integration).

With the official integration, those 3 states get reported correctly. With this new custom integration (wich is much better otherwise, thank you!), any other state that closed gets reported to open state, also this unknown state. 
With this new integration, it is thus not possible to separate between an open door and the "Lüftungsposition", which is relevant (as with the Lüftungsposition, the door is actually closed, except the small opening for the "Lüftung".

Is it possible to use both integration at the same time on the same home assistant installation? If yes, I probably would do this as a work-around until this is available also with the new integration.

(FYI: I currently have the official homematic integration with my running home assistant system and I'm currently testing this custom integration on a test Home Assistant installation to decide whether I'll migrate on my running system to the custom integration. Especially as the cover functionality has otherwise some issues in the official integration.)

**To Reproduce**
1. HmIP-MOD-HO integrated and Hörmann garage door in "Lüftungsposition".

**Screenshots (if applicable)**
- CCU firewall in CCU
- device config in CCU
- integrations view in HA
- device view in HA
- enity view in HA

**Relevant HA log entries (press full log) VERY IMPORTANT**
```


```

**Diagnostic Information (available on every device)**
```


```

**Expected behavior**
"Lüftungsposition" reported separately (as also the information is separate in the CCU3 with unkown state and as this unkown state is also reported in the official integration).

**Additional context**

**Comment by SukramJ** [comment]
If the position is between 10% and 50% Lüftungsposition should be displayed.

**Comment by ivo7B4** [comment]
That would be great. But I also don't see any % position in the CCU (only open, closed or unknown) and the unkown state is mapped to open with this custom integration.
Maybe this also depends on the Hörmann garage door version? I have a series 4 and thus, also require the HAP1 HCP Adapter in between. Maybe the position information is available in % with series 3 garage doors? 
WIth this adapter and my series 4 Hörmann garage door, I only get these 3 states. And unknown mapped to open.

**Comment by SukramJ** [comment]
Please post a screenshot of the entity attributes (Developertools -> States)

**Comment by SukramJ** [comment]
I'll lean out the window and claim that the entity you complained about comes from the old integration.
According to the source code, this does not support position and should always return unknown as status.

**Comment by ivo7B4** [comment]
This is quite sure not from the old integration. I can most likely exclude this is I have two separate installations currently: 
One system as test system wit the custom integration (where I don't have the old integration configured) and the productive system with the old integration (where I don't have the custom installation, not even HACS, installed).

Screenshots:
In the CCU3:
![grafik](https://user-images.githubusercontent.com/96831385/209841814-0dab43f9-c254-4c4f-81d2-30340abc19eb.png)

From the custom integration:
![grafik](https://user-images.githubusercontent.com/96831385/209842279-59c5427e-3b84-4de5-a8e1-c7b4e69d263a.png)

From my productive system with the official integration (where unkown is reported correctly):
![grafik](https://user-images.githubusercontent.com/96831385/209842661-a868cfdc-3ae9-4666-9c5c-b49f5c123786.png)

**Comment by SukramJ** [comment]
We use the GARAGE_DOOR_STATE to report the position/state in HA:

```
        if self._e_door_state.value == GARAGE_DOOR_STATE_OPEN:
            return 100
        if self._e_door_state.value == GARAGE_DOOR_STATE_VENTILATION_POSITION:
            return 10
        if self._e_door_state.value == GARAGE_DOOR_STATE_CLOSED:
            return 0
```

To the state, from an HA perspective is OK. Why should we not use it?

**Comment by ivo7B4** [comment]
I don't know why I get "unkown" in the CCU when the position is actually in the ventilation position. I assume (but just a guess) that the HmIP-MOD-HO is maybe not yet fully compatible with the newer series 4 from Hörmann and thus, reports "unknown" when the garage door is in the ventilation position.
Would be great if unknown  could be mapped as well. Thank you!

**Comment by ivo7B4** [comment]
I just see that there is a hidden entity door state which I can activate with the custom integration.
Yes, this one I can use as a work around. That's currently sufficient for me as I mainly hope that the CCU will display the states correctly as well (ventilation position instead of unknown) and this then also would solve this issue here correctly.

Thank you again! And thus, fine for me to close this issue. Should I click on close? I think this information is still helpful for someone else having this issue that activating this hidden entity is a good temporary solution.

**Comment by SukramJ** [comment]
Cover entities don't support textual states, so, As already mentioned above, the VENTILATION_POSITION will be displayed as position 10%.
There will be now further action from my side.
