### ISSUE TITLE
HmIP-FSM nutzt mA anstatt A?

### ISSUE THREAD

**Issue by Bascht74** [SukramJ/hahomematic#803]
**custom_component version (if applicable):**
1.25.1

**known last working custom_component version (if applicable):**
./.

**Home Assistant:**
- Version: 2023.01.b5
- Installation method (HAOS, supervised, core, venv, Docker): HAOS

**CCU:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, HA-Addon ...): HA-Addon
- OS (Original, RaspberryMatic, debmatic ...): RaspberryMatic
- Version: 3.65.11.20221218

**Problem-relevant configuration:**

Do you use tls? no
Do you use callback? no
Do you use username and password? yes
Which interfaces do you use (hmip/bidcos/wired)? hmip

**Describe the bug**

Ich habe das hier im Log gefunden: 

* Entity sensor.xyz_current (<class 'custom_components.homematicip_local.sensor.HaHomematicSensor'>) is using native unit of measurement 'mA' which is not a valid unit for the device class ('current') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

Lt. Dokumentation ist nur "A" gültig: 

> current: Current in A

Es ist ein HmIP-FSM

**To Reproduce**
./.

**Screenshots (if applicable)**
./.

**Relevant HA log entries (press full log) VERY IMPORTANT**
```
* Entity sensor.xyz_current (<class 'custom_components.homematicip_local.sensor.HaHomematicSensor'>) is using native unit of measurement 'mA' which is not a valid unit for the device class ('current') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
```

**Diagnostic Information (available on every device)**
```
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.1.0b1",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "5.15.80",
    "supervisor": "2022.12.1",
    "host_os": "Home Assistant OS 9.4",
    "docker_version": "20.10.19",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "battery_sim": {
      "version": "1.0",
      "requirements": []
    },
    "homematicip_local": {
      "version": "1.25.1",
      "requirements": [
        "hahomematic==2022.12.8"
      ]
    },
    "hacs": {
      "version": "1.29.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "homematicip_local",
    "name": "Homematic(IP) Local",
    "config_flow": true,
    "documentation": "https://github.com/danielperna84/custom_homematic",
    "issue_tracker": "https://github.com/danielperna84/hahomematic/issues",
    "requirements": [
      "hahomematic==2022.12.8"
    ],
    "ssdp": [
      {
        "manufacturer": "EQ3",
        "manufacturerURL": "http://www.homematic.com"
      }
    ],
    "zeroconf": [],
    "homekit": {},
    "dependencies": [],
    "codeowners": [
      "@danielperna84",
      "@SukramJ"
    ],
    "iot_class": "local_push",
    "loggers": [
      "hahomematic"
    ],
    "version": "1.25.1",
    "integration_type": "hub",
    "is_built_in": false
  },
  "data": {
    "config": {
      "entry_id": "1b43698376898a59a21bfc96ce291372",
      "version": 1,
      "domain": "homematicip_local",
      "title": "HmIP",
      "data": {
        "instance_name": "HmIP",
        "host": "de838cd8-raspberrymatic",
        "username": "**REDACTED**",
        "password": "**REDACTED**",
        "tls": false,
        "verify_tls": false,
        "callback_host": null,
        "callback_port": null,
        "json_port": null,
        "interface": {
          "HmIP-RF": {
            "port": 2010
          },
          "VirtualDevices": {
            "port": 9292,
            "path": "/groups"
          }
        }
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": "1F2995E4B3",
      "disabled_by": null
    },
    "platform_stats": {
      "binary_sensor": 35,
      "climate": 31,
      "sensor": 91,
      "switch": 15
    },
    "devices": [
      "HmIP-BWTH",
      "HmIP-FSM",
      "HmIP-HEATING",
      "HmIP-PSM-2",
      "HmIP-RFUSB",
      "HmIP-SRH",
      "HmIP-STE2-PCB",
      "HmIP-STHO",
      "HmIP-WTH-2",
      "HmIP-eTRV-2",
      "HmIP-eTRV-2 I9F"
    ]
  }
}

```

**Expected behavior**
keine Fehlermeldung im Log :-)

**Additional context**

**Comment by SukramJ** [comment]
Bist Du sicher das Du 2023.01.b5 verwendest? 
Ich hab den Fehler mit https://github.com/home-assistant/core/pull/84492 behoben, und der wurde mit [2023.1.b3](https://github.com/home-assistant/core/releases/tag/2023.1.0b3) veröffentlicht.

**Comment by Bascht74** [comment]
> Bist Du sicher das Du 2023.01.b5 verwendest? Ich hab den Fehler mit [home-assistant/core#84492](https://github.com/home-assistant/core/pull/84492) behoben, und der wurde mit [2023.1.b3](https://github.com/home-assistant/core/releases/tag/2023.1.0b3) veröffentlicht.

Nicht mehr :-)
Ich habe nachgesehen und diese Instanz hatte das Update tatsächlich noch nicht bekommen. Ist somit erledigt. Danke auch, dass Du Dich hier so bei den HA Gurus dafür eingesetzt hast und schön, dass das jetzt offiziell supported wird.

Zu meiner Ehrenrettung sei gesagt, ich hatte natürlich in der aktuellen RC-Homepage nachgesehen: 
https://rc.home-assistant.io/integrations/sensor#device-class

Da fehlt die Info noch, dass mA auch unterstützt wird! Sollte noch ein PR Request erfolgen.

In der Developer Doku ist es aktualisiert: (da hatte ich nicht nachgesehen)
https://developers.home-assistant.io/docs/core/entity/sensor

**Comment by SukramJ** [comment]
> Zu meiner Ehrenrettung sei gesagt, ich hatte natürlich in der aktuellen RC-Homepage nachgesehen:
https://rc.home-assistant.io/integrations/sensor#device-class

Die wird erst am Tag der Veröffentlichung aktualisiert.

**Comment by Bascht74** [comment]
Danke für den Hinweis! 
Ich dachte bislang, dass die RC-Dokumentation zur Beta-Version passt...

Wieder was gelernt.
