### ISSUE TITLE
Integration stop to work after RaspberryMatic Update

### ISSUE THREAD

**Issue by Leon55556** [SukramJ/hahomematic#810]
DONT'T DELETE THIS.

This is for issues only
If you have a feature request, add it as a new discussion, or add your point of view to an existing discussion.

Please answer all questions as good as possible.

Language: as you like -> english

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you have read the release notes at https://github.com/danielperna84/custom_homematic/releases. 

Make sure you are running the latest version of the custom_component (and Home Assistant) before reporting an issue.

ENSURE that your Backend (CCU/Homegear/...) is working as expected and connected devices are controllable.

**custom_component version (if applicable):**
1.x.x

**known last working custom_component version (if applicable):**
1.x.x

**Home Assistant:**
- Version: 2022.12.9
- Installation method (HAOS ): 

**CCU:**
- Model (Raspi3/4.):
- OS (Original, RaspberryMatic, debmatic ...):
- Version: 

**Problem-relevant configuration:**

Do you use tls?
Do you use callback?
Do you use username and password?
Which interfaces do you use (hmip/bidcos/wired)?

**Describe the bug**
Integration stop to work after RaspberryMatic Update

**To Reproduce**

**Screenshots (if applicable)**
- CCU firewall in CCU
![image](https://user-images.githubusercontent.com/97984601/210425073-a88d84b0-ba10-4f66-b219-3b2bf44b432c.png)

- device config in CCU
<img width="355" alt="image" src="https://user-images.githubusercontent.com/97984601/210424841-f3f87a4f-f1c2-4444-a91a-1a449a49498f.png">

- integrations view in HA
- 
<img width="269" alt="image" src="https://user-images.githubusercontent.com/97984601/210424400-b487841d-170b-4900-abe0-b29fb04672cf.png">

- device view in HA

- enity view in HA

**Relevant HA log entries (press full log) VERY IMPORTANT**

**Diagnostic Information (available on every device)**

2023-01-03 19:39:25.797 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration homematicip_local which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-03 19:41:44.914 WARNING (MainThread) [custom_components.homematicip_local] This release of Homematic(IP) Local requires HA version 2023.01.0.dev0 and above
2023-01-03 19:41:44.918 WARNING (MainThread) [custom_components.homematicip_local] Homematic(IP) Local setup blocked
2023-01-03 19:48:50.011 WARNING (MainThread) [custom_components.homematicip_local] This release of Homematic(IP) Local requires HA version 2023.01.0.dev0 and above
2023-01-03 19:48:50.022 WARNING (MainThread) [custom_components.homematicip_local] Homematic(IP) Local setup blocked

```

**Expected behavior**


**Additional context**
Add any other context about the problem here.

**Comment by SukramJ** [comment]
Congratulations:
- You use this integration's beta channel
- You missed to read the [release notes](https://github.com/danielperna84/custom_homematic/releases/tag/1.26.0):` This release requires HA >= 2023.01 (Beta)`
- You missed to read the logs: `This release of Homematic(IP) Local requires HA version 2023.01.0.dev0 and above`
- You only use `Version: 2022.12.9`

Rollback or update to HA beta, and please start reading provided Information

**Comment by Leon55556** [comment]
Good evening,

Thank you for quick response and your work. I am just BFU beginner.....

Leon
