### ISSUE TITLE
Small spelling mistake in release 1.26.0

### ISSUE THREAD

**Issue by SukramJ** [SukramJ/hahomematic#816]
### Discussed in https://github.com/danielperna84/hahomematic/discussions/815

<div type='discussions-op-text'>

<sup>Originally posted by **sotatech** January  4, 2023</sup>
Hi,

"Rename cache_dict to **persistant_cache**" should be **persistent_cache**.</div>

**Comment by SukramJ** [comment]
Thanks. But please don't add discussions for fixes.

**Comment by sotatech** [comment]
Understood. I just wanted to let you know as quickly as possible and I only had my phone available - which makes filling out the issue form a real pain :)
