### ISSUE TITLE
error_jammed is not exisiting in my DLD for 1.26.0 anymore

### ISSUE THREAD

**Issue by ProfDrYoMan** [SukramJ/hahomematic#829]
DONT'T DELETE THIS.

This is for issues only
If you have a feature request, add it as a new discussion, or add your point of view to an existing discussion.

Please answer all questions as good as possible.

Language: as you like -> english/DEUTSCH 

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you have read the release notes at https://github.com/danielperna84/custom_homematic/releases. 

Make sure you are running the latest version of the custom_component (and Home Assistant) before reporting an issue.

ENSURE that your Backend (CCU/Homegear/...) is working as expected and connected devices are controllable.

**custom_component version (if applicable):**
1.26.0

**known last working custom_component version (if applicable):**
1.25,x

**Home Assistant:**
- Version: 2023.1.2
- Installation method (HAOS, supervised, core, venv, Docker):  HAOS

**CCU:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, HA-Addon ...): ProxMox
- OS (Original, RaspberryMatic, debmatic ...): RaspiMatic
- Version: 3.65.11.20221218

**Problem-relevant configuration:**

Do you use tls?
Do you use callback?
Do you use username and password?
Which interfaces do you use (hmip/bidcos/wired)?

**Describe the bug**
See subject line.

**To Reproduce**

**Screenshots (if applicable)**
- CCU firewall in CCU
- device config in CCU
- integrations view in HA
- device view in HA
- enity view in HA

**Relevant HA log entries (press full log) VERY IMPORTANT**
```


```

**Diagnostic Information (available on every device)**
```


```

**Expected behavior**

**Additional context**

**Comment by SukramJ** [comment]
Die ERROR_JAMMED Entität müsste schon mit [1.25.0](https://github.com/danielperna84/custom_homematic/releases/tag/1.25.0) verschwunden sein. Das war aber nicht geplant.
Mit der Version 1.25.0 werden alle ERROR* Parameter als Event gesendet (siehe Release Notes), und entsprechend nicht mehr als Entität angezeigt. Der referenzierte Blueprint sollte dabei natürlich weiter eingeschränkt werden.
Ist das so für die verwendbar?

**Comment by ProfDrYoMan** [comment]
Hmm, das macht es jetzt komplizierter als vorher. Wieso? Ist doch ein sinnvolles Statusflag. 

ich schau mir den Blueprint wohl man an.

**Comment by SukramJ** [comment]
> Ist doch ein sinnvolles Statusflag

Was machst Du mit dem Statusflag? Verwendest Du das nur in der UI, oder verwendest Du den binary_sensor in einer Automatisierung, der dann damit irgendwas macht?

Bei den Geräten gibt es sehr viele ERROR* Parameter, die meistens aber nur sehr selten oder nie auslösen.
Alle als binary_sensor anzuzeigen war für mich keine Lösung, daher werden alle ERROR* als Event ausgelöst, und können bei bedarf (Blueprint/Automatisierung) verarbeitet werden.
Beim DLD war error_jammed eine Sonderlösung.

**Comment by ProfDrYoMan** [comment]
Ich hab’s in der UI als Block der nur eingeblendet wird, wenn Error. Ich werde es nun anders lösen. Danke.

**Comment by SukramJ** [comment]
Also ich hab nicht gesagt, das die Ausnahme für den DLD keinen Sinn macht, aber ich versuche zu verstehen wie der Parameter verwendet wird.

**Comment by ProfDrYoMan** [comment]
Wie gesagt. Ein Block in der GUI der „Schloß blockiert“ anzeigt, sofern Jammed. 

Die persistent notification ist schon auch ok dafür.
