### ISSUE TITLE
HmIP-BROLL operating voltage "unknown"

### ISSUE THREAD

**Issue by ChristophCaina** [SukramJ/hahomematic#835]
The HmIP BROLL does provide an entity for operating voltage, although it is not a battery powered device.
Therefore, the sensors value is always unknown.

#445 

**custom_component version (if applicable):**

**known last working custom_component version (if applicable):**

**Home Assistant:**
- Version: 2023.1.x
- Installation method (HAOS, supervised, core, venv, Docker): HAOS Proxmox VM

**CCU:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, HA-Addon ...): Proxmox VM
- OS (Original, RaspberryMatic, debmatic ...): RaspberryMatic
- Version: 

**Problem-relevant configuration:**

**Describe the bug**
Remove sensor "operating voltage" from HmIp Broll

**To Reproduce**

**Screenshots (if applicable)**
![grafik](https://user-images.githubusercontent.com/26391061/211542341-57ef4e2b-e9a9-4170-804b-48a54232398d.png)

**Relevant HA log entries (press full log) VERY IMPORTANT**

**Diagnostic Information (available on every device)**

**Expected behavior**

**Additional context**

**Comment by SukramJ** [comment]
Thanks for reporting
