### ISSUE TITLE
HM-PBI-4-FM only channel 1 and 2 are recognized upon press 

### ISSUE THREAD

**Issue by MPatzek** [SukramJ/hahomematic#842]
DONT'T DELETE THIS.

This is for issues only
If you have a feature request, add it as a new discussion, or add your point of view to an existing discussion.

**custom_component version (if applicable):**
1.26.2 and back 2 month ago.

**Home Assistant:**
- Version: 2023.1.4
- Installation method (HAOS, supervised, core, venv, Docker): HAOS

**CCU:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, HA-Addon ...): CCU3
- OS (Original, RaspberryMatic, debmatic ...): Original 
- Version: up to date, but persisted since two month

**Problem-relevant configuration:**

Do you use tls? No
Do you use callback? Yes
Do you use username and password? Yes
Which interfaces do you use (hmip/bidcos/wired)? Hmip,bidcos

**Describe the bug**

I have the HM-PBI-4-FM at home and noticed a problem. Obviously, pressing buttons 3 and 4 is not recognized in HA, although being recognized in the ccu3 that I am connecting to.
Buttons 1 and 2 work flawlessly.

Also, all other components (hmip and hm) work flawlessly with the addon and are controllable and updated in HA.

The problem persisted basically, since I installed home assistant and this addon.

**Expected behavior**
Short (and long) press button 1-4 and receive events on HA.

**Additional context**

I attached the config files. Maybe someone can have a look? 
`
  "l": {
    "installation_type": "Home Assistant OS",
    "version": "2023.1.4",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "5.15.76-v8",
    "supervisor": "2022.12.1",
    "host_os": "Home Assistant OS 9.4",
    "docker_version": "20.10.19",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "alexa_media": {
      "version": "4.5.1",
      "requirements": [
        "alexapy==1.26.4",
        "packaging>=20.3",
        "wrapt>=1.12.1"
      ]
    },
    "var": {
      "version": "0.15.0",
      "requirements": []
    },
    "hacs": {
      "version": "1.29.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "homematicip_local": {
      "version": "1.26.2",
      "requirements": [
        "hahomematic==2023.1.3"
      ]
    },
    "ics_calendar": {
      "version": "3.1.6",
      "requirements": [
        "ics>=0.7.2",
        "recurring_ical_events>=1.0.2b0",
        "icalendar>=4.1.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "homematicip_local",
    "name": "Homematic(IP) Local",
    "config_flow": true,
    "documentation": "https://github.com/danielperna84/custom_homematic",
    "issue_tracker": "https://github.com/danielperna84/hahomematic/issues",
    "requirements": [
      "hahomematic==2023.1.3"
    ],
    "ssdp": [
      {
        "manufacturer": "EQ3",
        "manufacturerURL": "http://www.homematic.com"
      }
    ],
    "zeroconf": [],
    "homekit": {},
    "dependencies": [],
    "codeowners": [
      "@danielperna84",
      "@SukramJ"
    ],
    "iot_class": "local_push",
    "loggers": [
      "hahomematic"
    ],
    "version": "1.26.2",
    "integration_type": "hub",
    "is_built_in": false
  },
  "data": {
    "config": {
      "entry_id": "f18cada9b924f16b267595aaec61d2d0",
      "version": 1,
      "domain": "homematicip_local",
      "title": "ccu3-webui",
      "data": {
        "instance_name": "ccu3-webui",
        "host": "192.168.178.91",
        "username": "**REDACTED**",
        "password": "**REDACTED**",
        "tls": true,
        "verify_tls": false,
        "callback_host": null,
        "callback_port": null,
        "json_port": null,
        "interface": {
          "HmIP-RF": {
            "port": 42010
          },
          "BidCos-RF": {
            "port": 42001
          },
          "VirtualDevices": {
            "port": 49292,
            "path": "/groups"
          }
        }
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "ssdp",
      "unique_id": "9A499D0EC2",
      "disabled_by": null
    },
    "platform_stats": {
      "binary_sensor": 27,
      "climate": 15,
      "cover": 5,
      "light": 2,
      "sensor": 20,
      "switch": 7
    },
    "devices": [
      "HM-LC-Sw2PBU-FM",
      "HM-PBI-4-FM",
      "HM-Sec-SD",
      "HM-Sec-SD-Team",
      "HM-Sen-DB-PCB",
      "HMIP-PSM",
      "HMIP-WRC2",
      "HMIP-WTH",
      "HMIP-eTRV",
      "HmIP-BBL",
      "HmIP-BSL",
      "HmIP-BSM",
      "HmIP-FROLL",
      "HmIP-HEATING",
      "HmIP-PCBS",
      "HmIP-SWDM-B2",
      "HmIP-SWO-B",
      "HmIP-WTH-2",
      "HmIP-eTRV-2"
    ]
  }
}
`

**Comment by SukramJ** [comment]
The issue template seems to be removed, please restore our default issue template in the issue description and fill it out.

Although you are not using HmIP do [this](https://github.com/danielperna84/custom_homematic#events-for-homematicip-devices).

**Comment by MPatzek** [comment]
Thanks. I don't know, what happened to the template. It was never displayed. I wrote on the phone.

To problem: I already executed the steps you linked back then, because of my WTH-2.

Is it possible, that the addon uses a template for the 2 button model and therefore only 2 out of 4 buttons work? I looked through the code to find the location where the models are mentioned, but failed.

**Comment by SukramJ** [comment]
> Thanks. I don't know, what happened to the template. It was never displayed. I wrote on the phone.

I think you just deleted it.

**Comment by MPatzek** [comment]
No, I just checked. I misunderstood the new issue page and in detail the following phrase: "Don’t see your issue here? Open a blank issue."

Completely missed the big green button for now Problem report ;-)

Anyway. I hope all relevant information are now in the edited starting post.

**Comment by SukramJ** [comment]
HOW do you want to use these buttons in HA? Events, device triggers ...

**Comment by SukramJ** [comment]
From the integrations point of view i cannot see a problem. All 4 channels are available as device triggers.
I would guess the CCU is not sending events for channel 3+4.

**Comment by MPatzek** [comment]
My plan is to switch lights and motion sensors.
The two working buttons are used currently to control a blind.
They also work fine and the events are logged.

**Comment by hvorragend** [comment]
By the way: It looks like that there was a change related to the events. 

I am using several trigger event entities.

```
- trigger:
    - platform: event
      event_type: homematic.keypress
      event_data:
        interface_id: Homematic-BidCos-RF
        address: LEQ1234567
        type: press_long
        subtype: 1
        device_id: dd1bexxxxxxxx9d990eb9912xxxyyyyy
        name: Codeschloss Sensor
  unique_id: event_codeschloss_sensor_rfid
  binary_sensor:
    - name: Codeschloss Sensor RFID
      auto_off: 1
      state: "true
     

```

And they are not working anymore since (about) three days. If I check your commits there was a change related to the subtype/channel_no. 

Could it be that there is a bug anywhere?

Post scriptum: I have never used "device_type" in my events. It this necessary?

**Comment by SukramJ** [comment]
Looks like a manually defined trigger, that is not created by the UI.
Remove name from the trigger and it should work.

**Comment by SukramJ** [comment]
> From the integrations point of view i cannot see a problem. All 4 channels are available as device triggers.
I would guess the CCU is not sending events for channel 3+4.

Closing this for now

**Comment by hvorragend** [comment]
I have changed name to device_name. That fixed it. 

But could you tell me how it we could turn an event into a trigger based sensor by the UI?

**Comment by SukramJ** [comment]
Name /device_name is not needed! Remove it.

I will be name again in 1.26.4

**Comment by SukramJ** [comment]
> But could you tell me how it we could turn an event into a trigger based sensor by the UI?

Can be read in the [HA docs](https://www.home-assistant.io/docs/automation/trigger/#device-triggers):
Create a new automation -> select trigger_type device -> select the device -> select the event.

**Comment by hvorragend** [comment]
Ah, that is what you mean. 
I know it but I don't use it here. 

Thank you for your help.
