### ISSUE TITLE
Support für HmIP-DSD-PCB

### ISSUE THREAD

**Issue by Phil7989** [SukramJ/hahomematic#855]
Hallo Daniel, 

danke für deine Arbeit an der Homematic Integration.
Wenn das möglich ist, hätte ich gerne Support für HmIP-DSD-PCB und das Attribut Press Short, Press Long. 
Das wird mit bisher nicht im Gerät & Logbuch angezeigt. Nur die Standard Attribute wie Battery. Duty Cycle etc.

Ist das möglich mit einzubinden? 

Danke & Gruß Philipp

**Comment by SukramJ** [comment]
Das ist kein Issue!

Das PRESS_SHORT und PRESS_LONG zustandslos sind werden diese nicht als Entitäten erstellt. ([Siehe](https://github.com/danielperna84/custom_homematic#devices-with-buttons))
Die Verwendung von PRESS_* erfolgt über device trigger in Automationen (Auslöser Gerät).
Damit das ganze funktioniert musst Du noch [Doku](https://github.com/danielperna84/custom_homematic#events-for-homematicip-devices) lesen.
