### ISSUE TITLE
Alle SysVars sofort "aktiviert" bei Integrierung einer neuen Zentrale, soll das so?

### ISSUE THREAD

**Issue by SukramJ** [SukramJ/hahomematic#870]
### Discussed in https://github.com/danielperna84/hahomematic/discussions/867

<div type='discussions-op-text'>

<sup>Originally posted by **Baxxy13** January 19, 2023</sup>
Ich hatte gestern mal wieder ein neues Testsystem (testweise) integriert und mich gewundert das sofort alle SysVars "aktiv" waren.
Soweit ich mich erinnere waren die sonst immer "versteckt" und "deaktiviert" und man musste sie aktivieren wenn man sie benutzen wollte.

Ist das SysVar sofort "aktiv" jetzt Standard und so gewollt?

Den alten Use-Case ("versteckt" + "deaktiviert") fand ich da wesentlich praktischer, vor allem wenn man viele SysVars hat und die nicht in HA braucht.

Installierte Version ist die 1.26.5
![HA_SysVars_default_Aktiv](https://user-images.githubusercontent.com/54898249/213514667-55a7ed1e-90d3-4efa-9a70-fa5bc2e27ee8.JPG)

 </div>

**Comment by Baxxy13** [comment]
Ich wollte zuerst erfahren ob es vielleicht ein gewünschtes Verhalten ist, daher erstmal die Frage im Diskussionsteil.
Im Changelog hatte ich diesbezüglich nichts gefunden.

Das neue Verhalten tritt ab 1.26.0 auf. (alle Einstellungen im Config-Flow default)

Interessant auch, wenn ich bei der "Erstintegration" (ab1.26.0) im Config-Flow den Sysvar-Scan deaktiviere gibt es keine Steuerelemente, Sensoren oder korrekte Dienst Informationen.
![HA_SysVars_scan_inaktiv](https://user-images.githubusercontent.com/54898249/213652314-3f79853c-b40d-49ea-950d-0058f3d21383.JPG)


Mit der 1.25.1 bekommt man noch das alte Verhalten.

**Comment by SukramJ** [comment]
Eine gewünschte Veränderung hätte ich normalerweise im Changelog dokumentiert.

> Interessant auch, wenn ich bei der "Erstintegration" (ab1.26.0) im Config-Flow den Sysvar-Scan deaktiviere gibt es keine Steuerelemente, Sensoren oder korrekte Dienst Informationen.

Wenn der Sysvar-Scan deaktiviert ist werden keine SysVars geladen, und somit auch keine Entitäten angelegt.
Die Dienst(Geräte) Informationen werden bei aktiviertem Scan von den Entitäten zur Verfügung gestellt.
Wenn also keine Entitäten vorhanden sind, d.h. auch keine Deaktivierten, dann wird nur eine Roh-Version der Dienstinformationen angezeigt.

**Comment by Baxxy13** [comment]
Also wäre die "beste Vorgehensweise" bei der "Erstintegration" den Sysvar-Scan aktiv zu lassen und dann im Nachgang nochmal den Config-Flow mit deaktiviertem Sysvar-Scan durchzulaufen?

**Comment by SukramJ** [comment]
Um was zu erreichen?

**Comment by Baxxy13** [comment]
Das der "Dienst" korrekt "initialisiert" wird, also mit Versionsinformation, und den Steuerelementen (deaktivierte WebUI-Programme). So wie im obersten Screenshot.

Das die SysVars nicht auftauchen ist für mich plausibel wenn ich den Sysvar-Scan gleich deaktiviere.
Das aber alles andere auch "fehlt" ist etwas gewöhnungsbedürftig.

**Comment by SukramJ** [comment]
Beim Sysvar Scan werden nicht nur die Sysvars sondern auch die Programme periodisch abgeholt, und das sind dann zusammen alle Entitäten, die unter dem Dienst angezeigt werden. Wenn es also keine Entitäten gibt, dann braucht man natürlich auch keine Steuerelemente (macht das HA Frontend).
Wenn der Sysvar Scan deaktiviert wird, dann werden auch die Entitäten (die aktivierten) gelöscht.

Wenn Du die SysVar und Program Entitäten haben, aber deinen Datenverbrauch reduzieren willst, dann kann Du das Scan- Interval auf einen sehr hohen Wert setzten.

Die Anzeige von Modell und Version schau ich mir gerade noch an, damit auch die angezeigt werden.

**Comment by Baxxy13** [comment]
Ah, danke. 
Jetzt ist es klar, mir fehlte der Zusammenhang zwischen dem Sysvar-Scan und den Programmen.
