### ISSUE TITLE
FR HM-OU-LED16 no possibility to switch LEDs

### ISSUE THREAD

**Issue by SukramJ** [SukramJ/hahomematic#871]
### Discussed in https://github.com/danielperna84/hahomematic/discussions/868

<div type='discussions-op-text'>

<sup>Originally posted by **peterwup** January 19, 2023</sup>
Hi, I move my home automation from FHEM to RaspberryMatic and Home Assistant. 
I starting to move the different devices amd now have an issue with the HM-OU-LED16. 
The device is detected but only has 16 decativated entitys for buttons. 
I am not able to switch the LEDs to the possible states: off,red,green.orange
Do I smething wrong or is it a missing feature ? 

thank you 
</div>

**Comment by SukramJ** [comment]
@peterwup
Looks like nobody cared about this device before.
i will add the LED_STATUS for the next release

**Comment by peterwup** [comment]
Thought "Next release" means some week and not some minutes. 👍 
Works great. :
Thanky very much.
