### ISSUE TITLE
deleted CCU variable still in use

### ISSUE THREAD

**Issue by botfixer** [SukramJ/hahomematic#909]
**custom_component version (if applicable):**
1.26.2

**known last working custom_component version (if applicable):**
1.26.2

**Home Assistant:**
- Version: 2023.1.5
- Installation method (HAOS, supervised, core, venv, Docker): HAOS on NUC 

**CCU:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, HA-Addon ...): CCU3
- OS (Original, RaspberryMatic, debmatic ...): Original
- Version: 3.65.11

**Problem-relevant configuration:**

Do you use tls? yes
Do you use callback? yes
Do you use username and password? yes
Which interfaces do you use (hmip/bidcos/wired)? hmip/bidcos

**Describe the bug**

In the log there is a reference to a CCU variable that I have already deleted. It also no longer appears as an entity. Nevertheless, this log entry is generated. How can I eliminate this?

**To Reproduce**
just log at the logs

**Relevant HA log entries (press full log) VERY IMPORTANT**
[home-assistant_2023-02-01T19-05-33.706Z.log](https://github.com/danielperna84/hahomematic/files/10560786/home-assistant_2023-02-01T19-05-33.706Z.log)

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: hahomematic.central_unit
Source: custom_components/homematicip_local/services.py:336
Integration: Homematic(IP) Local (documentation, issues)
First occurred: 19:21:07 (192 occurrences)
Last logged: 19:37:42

Variable Haus Gesamtleistung not found on ccu3-webui. Sending directly to backend

```

**Diagnostic Information (available on every device)**
```

```

**Expected behavior**
no log entrys for non existing CCU variables

**Additional context**

**Comment by SukramJ** [comment]
> DONT'T DELETE THIS.

Das Issue-Template scheint entfernt worden zu sein. Bitte stelle das Issue-Template in der Problembeschreibung wieder her und füllen es aus.

**Comment by botfixer** [comment]
ok, hoffe es passt so.

**Comment by SukramJ** [comment]
Ich geh davon auf, das da noch eine Automatisierung läuft, die alle 5s den Service zum Schreiben einer Systemvariablen aufruft.

**Comment by botfixer** [comment]
oh mann, Du hast natürlich Recht. Automatisierung bei der Umstellung nicht deaktiviert und dann verwechselt.

Sorry und danke für den Hinweis.
