### ISSUE TITLE
minor issue

### ISSUE THREAD

**Issue by WallyDW** [SukramJ/hahomematic#915]
The valve state variable seems to have been used to present valve level (the percent of opening of the valve) back in times.
Now it is used to show the state in the adaption run, like ADAPTION_DONE.
The variable have maintained its unit of measurement in HA as % and HA do not like that unit in combination with a text string.

It works, but just gives warnings in the logs.

**Comment by SukramJ** [comment]
> DONT'T DELETE THIS.

Why am I writing this in the template?
Do I have to query every relevant piece of information again?
There is no usable context left in your "issue"!
