### ISSUE TITLE
Garagedoor: opening / closing wrong on HmIP-MOD-HO

### ISSUE THREAD

**Issue by fugazzy** [SukramJ/hahomematic#918]
This is for issues only
If you have a feature request, add it as a new discussion, or add your point of view to an existing discussion.

# DON'T DELETE THIS.
Issue without this template will be closed.

## Please answer all questions as good as possible.

Language: as you like -> english/DEUTSCH 

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you have read the release notes at https://github.com/danielperna84/custom_homematic/releases. 

Make sure you are running the latest version of the custom_component (and Home Assistant) before reporting an issue.

ENSURE that your Backend (CCU/Homegear/...) is working as expected and connected devices are controllable.

**custom_component version (if applicable):**
1.x.x

**known last working custom_component version (if applicable):**
1.x.x

**Home Assistant:**
- Version: 2022.x.x
- Installation method (HAOS, supervised, core, venv, Docker): 

**CCU:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, HA-Addon ...):
- OS (Original, RaspberryMatic, debmatic ...):
- Version: 

**Problem-relevant configuration:**

Do you use tls?
Do you use callback?
Do you use username and password?
Which interfaces do you use (hmip/bidcos/wired)?

**Describe the bug**
The STATUS of opening and closing is turned around. 
showing closing when opening and 
Opening when closing
HmIP-MOD-HO

**To Reproduce**

**Screenshots (if applicable)**
- CCU firewall in CCU
- device config in CCU
- integrations view in HA
- device view in HA
- enity view in HA

**Relevant HA log entries (press full log) VERY IMPORTANT**
```


```

**Diagnostic Information (available on every device)**
```


```

**Expected behavior**

**Additional context**

**Comment by SukramJ** [comment]
I will give support with empty template!
