### ISSUE TITLE
HmIP-MOD-HO sensor state coloring

### ISSUE THREAD

**Issue by zunixnuz** [SukramJ/hahomematic#937]
This is for issues only
If you have a feature request, add it as a new discussion, or add your point of view to an existing discussion.

# DON'T DELETE THIS.

Issue without this template will be closed.

## Please answer all questions as good as possible.

Language: as you like -> english/DEUTSCH

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you have read the release notes at https://github.com/danielperna84/custom_homematic/releases.

Make sure you are running the latest version of the custom_component (and Home Assistant) before reporting an issue.

ENSURE that your Backend (CCU/Homegear/...) is working as expected and connected devices are controllable.

**custom_component version (if applicable):**
2023.2.5

**known last working custom_component version (if applicable):**
none

**Home Assistant:**

- Version: 2023.2.2
- Installation method (HAOS, supervised, core, venv, Docker): HAOS

**CCU:**

- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, HA-Addon ...): piVCCU
- OS (Original, RaspberryMatic, debmatic ...):
- Version:

**Problem-relevant configuration:**

Do you use tls? no
Do you use callback? no
Do you use username and password? yes
Which interfaces do you use (hmip/bidcos/wired)? hmip, bidcos, wired

**Describe the bug**

The sensor state of the garage tor opener HmIP-MOD-HO does not change the icon color for open/close in a entity list.
Other entities in the same list, like window states, are changing the state color as expected.

**To Reproduce**

Add entity to dashboard entity list
Enable "Symbole je nach Zustand einfärben"
Open garage door
State changed from "Geschlossen" to "Offen"
Icon color does not change

**Screenshots (if applicable)**

- CCU firewall in CCU
- device config in CCU
- integrations view in HA
- device view in HA
- entity view in HA

**Relevant HA log entries (press full log) VERY IMPORTANT**

```


```

**Diagnostic Information (available on every device)**

```


```

**Expected behavior**

Icon color at state "Offen" should change from "Primärfarbe" to "Akzentfarbe"

**Additional context**

**Comment by SukramJ** [comment]
This is an integration that integrates devices into HA.
All we do here is to add the device class `garage` to the cover entity.
The frontend part is done in the HA [frontend](https://github.com/home-assistant/frontend) or additionally by custom cards installed over HACS.

**Comment by zunixnuz** [comment]
I just took a look into the attributes and compared that with HM-IP window sensors and i am wondering, why the "Function" attribute is empty here.
For the window sensors i have the option to select "Anzeigen als" -> "Fenster" (here i also see "Garagentor" in the drop down list) but i do not have this config option with the garage door opener state entity.

Is the function attribute a part of the device class or is this attribute set by the integration?

**Comment by SukramJ** [comment]
The function attribute is the "Gewerk" from CCU. 
Please post screenshots.

**Comment by zunixnuz** [comment]
![1](https://user-images.githubusercontent.com/105199289/217250683-69885f02-979a-4d78-86f0-d4f7c39ea691.jpg)

**Comment by zunixnuz** [comment]
Garage state compared to window state config:
![2](https://user-images.githubusercontent.com/105199289/217252173-84b7d1cf-afe2-40f6-8d8d-c49db9e5b213.jpg)
![3](https://user-images.githubusercontent.com/105199289/217252202-c604786e-59a2-4d8a-a35e-2588f6556232.jpg)

**Comment by SukramJ** [comment]
DOOR_STATE is a `sensor` with an `enum` device_class, that supports translations for the fixed value list, and as far as i now, no coloring.
The window is a `binary_sensor` with a device_class that supports coloring.

But as already mention this is not an issue in the integration, so this issue can be closed

**Comment by zunixnuz** [comment]
Thank's for clarification
