### ISSUE TITLE
HMIP-Heating Groups not visible in Home Assistant

### ISSUE THREAD

**Issue by therky04** [SukramJ/hahomematic#940]
This is for issues only
If you have a feature request, add it as a new discussion, or add your point of view to an existing discussion.

# DON'T DELETE THIS.

Issue without this template will be closed.

## Please answer all questions as good as possible.

Language: as you like -> /DEUTSCH

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you have read the release notes at https://github.com/danielperna84/custom_homematic/releases.

Make sure you are running the latest version of the custom_component (and Home Assistant) before reporting an issue.

ENSURE that your Backend (CCU/Homegear/...) is working as expected and connected devices are controllable.

**custom_component version (if applicable):**
1.x.x

**known last working custom_component version (if applicable):**
Never worked

**Home Assistant:**

- Version: 2023.2.3
- Installation method (HAOS, supervised, core, venv, Docker): 
HAOS as VM in proxmox

**CCU:**

- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, HA-Addon ...): Raspi3
- OS (Original, RaspberryMatic, debmatic ...): RaspberryMatic
- Version: 3.67.10.20230114

**Problem-relevant configuration:**

Do you use tls? No
Do you use callback? No
Do you use username and password? Yes
Which interfaces do you use (hmip/bidcos/wired)? HMIP

**Describe the bug**
Firewall testweise komplett geöffnet,
Heizgruppen bei Konfiguration des Addons aktiviert.

Bei den Geräten finde ich die einzelnen Heizkörper und Fenstersensoren, die HMIP-Heizgruppen sind nicht auffindbar, es wird auch kein Fehler im Log ausgegeben.

**To Reproduce**

1. Go to Home Assistant Einstellungen
2. Click on Geräte und Dienste
3. Scroll down to Homematic(IP) local, auf neu laden klicken, Heizgruppen werden nicht gefunden.
4. Kein Fehler in den Logs.

**Screenshots (if applicable)**

- CCU firewall in CCU
- 
- device config in CCU: 
![grafik](https://user-images.githubusercontent.com/121687860/217563797-c730d9b8-4454-47f5-9abd-414096504f08.png)
- integrations view in HA: 
![grafik](https://user-images.githubusercontent.com/121687860/217563999-85d5ed09-054e-4aaa-a144-c08a385d27ef.png)
- device view in HA:
![grafik](https://user-images.githubusercontent.com/121687860/217564220-4bfe0659-7e93-4e35-8f31-a0ea1e0cb189.png)
- entity view in HA
![grafik](https://user-images.githubusercontent.com/121687860/217564411-02b13c58-01e0-4a4c-a484-433101cdf955.png)

**Relevant HA log entries (press full log) VERY IMPORTANT**
`2023-02-08 15:55:10.090 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-02-08 15:55:10.091 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration homematicip_local which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant`

**Diagnostic Information (available on every device)**
```
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.2.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "5.15.90",
    "supervisor": "2023.01.1",
    "host_os": "Home Assistant OS 9.5",
    "docker_version": "20.10.22",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "waste_collection_schedule": {
      "version": "1.35.0",
      "requirements": [
        "icalendar",
        "recurring_ical_events",
        "icalevents",
        "bs4"
      ]
    },
    "hacs": {
      "version": "1.30.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "homematicip_local": {
      "version": "1.30.1",
      "requirements": [
        "hahomematic==2023.2.7"
      ]
    }
  },
  "integration_manifest": {
    "domain": "homematicip_local",
    "name": "Homematic(IP) Local",
    "config_flow": true,
    "documentation": "https://github.com/danielperna84/custom_homematic",
    "issue_tracker": "https://github.com/danielperna84/hahomematic/issues",
    "requirements": [
      "hahomematic==2023.2.7"
    ],
    "ssdp": [
      {
        "manufacturer": "EQ3",
        "manufacturerURL": "http://www.homematic.com"
      }
    ],
    "zeroconf": [],
    "homekit": {},
    "dependencies": [],
    "codeowners": [
      "@danielperna84",
      "@SukramJ"
    ],
    "iot_class": "local_push",
    "loggers": [
      "hahomematic"
    ],
    "version": "1.30.1",
    "integration_type": "hub",
    "is_built_in": false
  },
  "data": {
    "config": {
      "entry_id": "7dd8e9f28b41a67d827a9743f78f6f0e",
      "version": 1,
      "domain": "homematicip_local",
      "title": "ccu3-webui",
      "data": {
        "instance_name": "ccu3-webui",
        "host": "192.168.2.238",
        "username": "**REDACTED**",
        "password": "**REDACTED**",
        "tls": false,
        "verify_tls": false,
        "sysvar_scan_enabled": true,
        "sysvar_scan_interval": 30,
        "callback_host": null,
        "callback_port": null,
        "json_port": null,
        "interface": {
          "HmIP-RF": {
            "port": 2010
          },
          "VirtualDevices": {
            "port": 9292,
            "path": "/groups"
          }
        }
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "ssdp",
      "unique_id": "16FB5330FE",
      "disabled_by": null
    },
    "platform_stats": {
      "binary_sensor": 17,
      "climate": 7,
      "sensor": 5,
      "switch": 3
    },
    "devices": [
      "HMIP-PS",
      "HMIP-PSM",
      "HMIP-SWDO",
      "HMIP-eTRV",
      "HmIP-STH",
      "HmIP-eTRV-2",
      "HmIP-eTRV-2 I9F"
    ]
  }
}
```
Exemplarisch ein Heizkörperthermostat.

**Expected behavior**
Nach Konfiguration und neu laden der Integration sollte die HMIP-Heizgruppe in Home Assistant sichtbar sein.

**Additional context**

**Comment by therky04** [comment]
https://github.com/danielperna84/hahomematic/discussions/928#discussion-4827147

**Comment by SukramJ** [comment]
Für mal bitte folgenden Service (Einstellungen --> Services) aus:`Homematic(IP) Local: Clear the cache`

Danach bitte HA neustarten.

**Comment by therky04** [comment]
![grafik](https://user-images.githubusercontent.com/121687860/217571748-a9c6dfa6-01c9-4235-a760-f34ba91aa4a0.png)
Sorry, finde die Option nicht. Oder suche ich an der falschen Stelle?

**Comment by SukramJ** [comment]
>Oder suche ich an der falschen Stelle?

Ja.
Einstellungen findest Du auf der HA Startseite Links

**Comment by therky04** [comment]
Ja, unter Einstellungen und dann Geräte & Dienste oder eben Devices & Services meinst du, oder? Dort finde ich keine Möglichkeit, den Cache zu clearen.

**Comment by SukramJ** [comment]
Sorry unter Entwicklerwerkzeuge --> Dienste.

**Comment by therky04** [comment]
Ich werde verrückt! Die Funktion war mir gänzlich unbekannt! Sorry für die Umstände, es funktioniert jetzt!

Tausend Dank!

**Comment by SukramJ** [comment]
Gerne. 
Der Unterschied hier im Issue ist, das du jede Menge Informationen zusammen getragen hast, und ich so erst mal feststellen konnte, das die Konfiguration so stimmig ist, was häufig nicht der Fall ist.
Das Ganze einzeln in einer Diskussion abzufragen ist mir mittlerweile zu nervig.

**Comment by winblank58** [comment]
Hi, just got a **success message** after some problems while setting up a new HA system and import from a CCU3 based RaspberryMatic system: maybe helpful to delete a certificate in the imported RaspberryMatic file and clear the SSL and authentication check boxes in the RaspberryMatic/settings/security. This should cause no security issues while running  RaspberryMatic as an Add-on.
Thanks for all the wonderful work and support here by Daniel Perna and Jens Maus!

**Comment by SukramJ** [comment]
Please don't comment on closed issues.

**Comment by SukramJ** [comment]
@winblank58 If you want to share your experiences please use the discussions part of the repo.
