### ISSUE TITLE
Connection Refused / Access denied Errors since the last two versions

### ISSUE THREAD

**Issue by andbez** [SukramJ/hahomematic#941]
Hi,

using the Integration for some months now and worked without any problems. Since 2 days (always the most recent update), the Integration has following errors:

Logger: hahomematic.json_rpc_client
Source: runner.py:128 
First occurred: 21:03:54 (2 occurrences) 
Last logged: 21:07:02

GET_ALL_DEVICE_DATA failed: ClientException [('post_script: error: {\'name\': \'JSONRPCError\', \'code\': 400, \'message\': \'access denied ("ADMIN" needed )\'}',)]
GET_ALL_DEVICE_DATA failed: ClientException [('post_script: error: 503',)]

Logger: hahomematic.xml_rpc_proxy
Source: runner.py:128 
First occurred: 21:07:02 (2 occurrences) 
Last logged: 21:10:18

OSError on Raspmatic-BidCos-RF: (111, 'Connection refused')

Raspberrymatic is running as Add-On in HAOS (as VM on ProxMox). 

After Reboot of HAOS I can control Homematic Devices via HA for a few seconds. But then the errors occurs. Controlling Homematic-Devices via Raspmatic directly (Web-Frontend) is working without any issues.

I checked the following things:
- I used a special User for HA -> RaspMatic with admin rights. Changed to built in Admin-User -> Errors still exists
- Reboot of Proxmox / HAOS several times -> Errors still exists
- Reconfigure Integration -> Errors still exists

Any Hints?

Thank you.

**Comment by SukramJ** [comment]
>  DON'T DELETE THIS.
Issue without this template will be closed.
Please answer all questions as good as possible.

Why is it such a problem just to answer a few questions?

> OSError on Raspmatic-BidCos-RF: (111, 'Connection refused')

This is a problem with your Raspberrymatic Add-On that blocks the connection, so this issue can be closed here.

**Comment by andbez** [comment]
Sorry. Do want to be rude. When I created this issue, there was no template given (After clicking "New Issue" I logged in into GitHub and was forwarded to the "clean" issue screen).
