### ISSUE TITLE
Removed valve_state entities from HmIP-FALMOT-C12 cannot be deleted

### ISSUE THREAD

**Issue by botfixer** [SukramJ/hahomematic#947]
Language: as you like -> no matter

**custom_component version (if applicable):**
1.30.2

**known last working custom_component version (if applicable):**
1.27.1

**Home Assistant:**

- Version: 2023.2.3
- Installation method (HAOS, supervised, core, venv, Docker): HAOS

**CCU:**

- CCU3
- OS (Original)
- Version:

**Problem-relevant configuration:**

Do you use tls? yes
Do you use callback? yes
Do you use username and password? yes
Which interfaces do you use (hmip/bidcos)

**Describe the bug**
In newer Version of the INtegrazion valve_satet has been removed. This results in not delatable entities.

**To Reproduce**

1. Go to the entity
2. Activate it
3. Wait for 30 seconds
4. Delete button is greyed out

**Screenshots (if applicable)**
![valve](https://user-images.githubusercontent.com/79414225/218172491-707ef0fa-1ebc-4e4d-afde-4099929fea33.jpg)

**Comment by SukramJ** [comment]
Deactivated entities are not under control of the integration.
1. Activate the entity
2. Restart HA
3. Delete the entity

**Comment by botfixer** [comment]
Thank you! Worked!
