### ISSUE TITLE
HOMEMATICIP_LOCAL-XmlRPC-Server received no events.

### ISSUE THREAD

**Issue by SciLor** [SukramJ/hahomematic#957]
This is for issues only
If you have a feature request, add it as a new discussion, or add your point of view to an existing discussion.

# DON'T DELETE THIS.

Issue without this template will be closed.

## Please answer all questions as good as possible.

Language: as you like -> english/DEUTSCH

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you have read the release notes at https://github.com/danielperna84/custom_homematic/releases.

Make sure you are running the latest version of the custom_component (and Home Assistant) before reporting an issue.

ENSURE that your Backend (CCU/Homegear/...) is working as expected and connected devices are controllable.

**custom_component version (if applicable):**
Latest

**known last working custom_component version (if applicable):**
Unknown, some in the middle / end 2022

**Home Assistant:**

- Version: 2023.2.7
- Docker

**CCU:**

- Raspi3 with Homegear

**Problem-relevant configuration:**

Do you use tls?
Do you use callback?
Do you use username and password? Yes
Which interfaces do you use (hmip/bidcos/wired)? Bidcos

**Describe the bug**
Home Assistant shows an error several times a day, beside that everything works fine.
I'm am earlier version from last year this problem didn't occur.
I am using a KeyMatic and Ring sensor.

HOMEMATICIP_LOCAL-XmlRPC-Server received no events.

**To Reproduce**

Wait some minutes.

**Screenshots (if applicable)**

- CCU firewall in CCU
- device config in CCU
- integrations view in HA
- device view in HA
- entity view in HA

**Relevant HA log entries (press full log) VERY IMPORTANT**

```


```

**Diagnostic Information (available on every device)**

```


```

**Expected behavior**
Don't throw this error or make the timeout configurable / disablable.

**Additional context**

**Comment by SukramJ** [comment]
The mechanism to check for incoming events is active for more then a year and  a description can be found [here](https://github.com/danielperna84/custom_homematic#what-is-the-meaning-of-this-persistant-notification-homematicip_local-xmlrpc-server-received-no-events).
It is not an error in the integration, but a warning that the backend system, in your case Homegear, is currently not responding as expected or is unable to send updates.
So check Homegear for abnormalities.
I will increase the warning interval to 10 minutes in future versions.
