### ISSUE TITLE
HmIP-PDT contains invalid control

### ISSUE THREAD

**Issue by chrste90** [SukramJ/hahomematic#96]
I'm trying out the new integration with my setup and i think i found an issue.

For the HmIP-PDT, it seems like there is an invalid control, i believe a wrong channel is shown (HmIP-PDT 000...:4), so it's probably channel 4

![HmIP-PDT](https://user-images.githubusercontent.com/6923277/147467948-ab2182ba-41f0-4988-b941-0dff320fe2f5.PNG)

I also think that actual temperature is not needed as it doesn't contain any value.

**Comment by SukramJ** [comment]
Hi
actual_temperature has already been removed from integration, so this is a leftover in your installation. Just click on the entity and click remove.

Stehlampe should be the correct on channel 3 and the other entity could als be deleted. 
After a restart the entities should not come back.

**Comment by chrste90** [comment]
Hi,

i just made a fresh install of the integration and now everything looks fine:

![HmIP-PDT](https://user-images.githubusercontent.com/6923277/147472182-d7883a7c-f9c1-4210-9008-424d0225db38.PNG)

I installed the integration shortly after it was available in hacs and updated it since then, just didn't find any time to try it out.
But now everything is set up correctly for a new installation, thanks.
