### ISSUE TITLE
Heating groups don't contain all values

### ISSUE THREAD

**Issue by chrste90** [SukramJ/hahomematic#97]
I have a heating group in my setup which contains two heating devices (HmIP-eTRV), a thermostat (HMIP-WTH) and a windows sensor (HmIP-SRH).

But the group is missing some properties or values for existing properties, e.g. the humidity is missing or the diagnose properties are empty. It would also be nice if the entity for the window state would be shown if available.

**Heating Group:**
![heating_group](https://user-images.githubusercontent.com/6923277/147468664-e7b36d8d-5605-4fde-a350-f1cf88daab55.PNG)

**Thermostat:**
![thermostat](https://user-images.githubusercontent.com/6923277/147468810-c4f436f6-8412-4e18-8825-5c0609d30ce2.PNG)

**Window Sensor**
![window_sensor](https://user-images.githubusercontent.com/6923277/147469151-9260c268-4f42-4820-aafb-25b94aca5df9.PNG)

**Heating Group in CCU containing all information**
![heating_group_ccu](https://user-images.githubusercontent.com/6923277/147469233-d5498d5c-4eb1-4410-8f22-cc4c1a07eb9a.PNG)

**Comment by SukramJ** [comment]
This integration is in an early stage to there can be lots of changes.
The thermostat device should contain all the additional entities, whereby the climate device only contains the climate entity.

To get rid off the grayed out entities, you could also delete them on the entity overview page.

**Comment by chrste90** [comment]
Yeah, i know about the early stage, i just wanted to give some early feedback :)

I'm also not using this integration for my production installation for now, i just used a test instance to play a bit with the new integration, so no need to get rid of any entities yet.

I made a fresh installation and the heating group now looks like this:
![heating_group](https://user-images.githubusercontent.com/6923277/147472460-cb5ac30d-4ea8-4a01-9372-5dafa90614d6.PNG)

So no more wrong entities, but i think it would be good to add the corresponding entities for the properties which are shown for the heating group in the ccu, so i'm leaving this issue open, but i think it's more a feature request than a bug now.

**Comment by SukramJ** [comment]
Thanks a lot for testing.

Adding duplicate entities doesn't make sense. What is informational purpose of duty_cycle, low_bat, sabotage, window_state for a group?

**Comment by chrste90** [comment]
I'm more thinking about aggregating some information of the different devices of the group, like temperature, humidity of the thermostate, open/close-state of the window sensor, opening level of the climate device and sth. like this so that you can see all relevant information in one place.

**Comment by SukramJ** [comment]
You can create an entity card for this.

Please close this issue , because this is no issue.
If you want do discuss this, open a new discussion or follow an existing.
