### ISSUE TITLE
When I use the Homeassistant mobile app, I often cannot control some shutters

### ISSUE THREAD

**Issue by silvermd** [SukramJ/hahomematic#971]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hello,

For example, when I use the Homeassistant mobile app, I often cannot control some shutters.
What can be the reason and what can I do about it?

I have another APP (Home24) from earlier which addresses the ccu2 directly via http login.
I do that and then the shutters can be contacted in the Homassistant app.

Does it have anything to do with the documentation statement?

( https://github.com/danielperna84/custom_homematic#additional-information )
Additional information
What is the meaning of this persistent notification HOMEMATICIP_LOCAL-XmlRPC-Server received no events?

This integration does not fetch new updates from the CCU, it receives state changes and new values for devices from the CCU by the XmlRPC server.

### What version of HomematicIP (local) has the issue?

1.31.0

### What type of installation are you running?

Home Assistant Core

### What type of installation are you running for your homematic backend?

CCU2

### Which version of your homematic backend are you running?

2.61.7

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Can you tell me what kind of shutter you use, or should I guess?
Are there log (full log) entries?
Please add diagnostic information.

> I often cannot control some shutters.

How often? There must be log entries

**Comment by silvermd** [comment]
Hello,

sorry I don't want to annoy you.

Attached is the log from setting -> integration -> ccu2
Homematic(IP) Local --> download diagnostic information

[config_entry-homematicip_local-1a5edc5f76feb5c961197cdac243d4df.json.txt](https://github.com/danielperna84/hahomematic/files/10805858/config_entry-homematicip_local-1a5edc5f76feb5c961197cdac243d4df.json.txt)

how often:
almost daily, today i made some updates in homeassistant and restart. Now 2 of 14 shutters are not available again. I don't know where I can find the log for the connections.
Are more logs needed? Can you please tell me where i can find it.

Thank you very much for your patience

**Comment by SukramJ** [comment]
Setting / System / Logs  --> Load Full Log

**Comment by silvermd** [comment]
[home-assistant_2023-02-22T16-20-06.308Z.log](https://github.com/danielperna84/hahomematic/files/10806080/home-assistant_2023-02-22T16-20-06.308Z.log)

Thanks
the information that the following entity cannot be reached helps perhaps:

Entity ID: cover.badezimmer

**Comment by silvermd** [comment]
Here are some more pictures, I can't think of more at the moment

![cover badezimmer](https://user-images.githubusercontent.com/109596879/220693583-a2b01d5d-1e33-47e9-b299-aad2f825108d.png)
![cover badezimmer_details](https://user-images.githubusercontent.com/109596879/220693628-86b0f673-802a-4f8e-a4e8-da03dd5a060b.png)
![cover badezimmer_details_log](https://user-images.githubusercontent.com/109596879/220693663-1cd70e43-df8c-4405-8ac9-7cc18a62ec14.png)

**Comment by SukramJ** [comment]
Looks like you have no problems in the logs.
When a device is not reachable, then the CCU (!) sends an `UNREACH` event to HA that there is a communication problem to the device, and the entity gets unavailable in HA.
This is not a problem within this integration!



Solution 1: Fix your communication problem between CCU and shutter.
Solution2: To ignore an `UNREACH` event from CCU and to be able (to try) to control the device, there is a service named [homematicip_local.force_device_availability](https://github.com/danielperna84/custom_homematic#homematicip_localforce_device_availability). 

This service can also be used in a [blueprint](https://github.com/danielperna84/custom_homematic/blob/devel/blueprints/automation/homematicip_local_reactivate_single_device.yaml).

**Comment by silvermd** [comment]
Thanks for the quick help. I can always contact the devices from the ccu2 (web frontend), that works.

I'll take a look at your other suggestion.

Thanks so much

**Comment by SukramJ** [comment]
I think this can be closed for now.
