### ISSUE TITLE
homamatic lokal erkannt, aber keine Geräte oder Entitäten

### ISSUE THREAD

**Issue by tompanj** [SukramJ/hahomematic#973]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Ich habe homeassistant auf einem PI4 zu laufen und Raspberrymatic auf einem PI3. Raspberrymatic funktioniert einwandfrei.
Die Installation von homematic lokal wird als erfolgreich angezeigt, es werden aber keine Geräte und Entitäten erkannt. Alle Ports auf der Raspberrymatic sin offen, die Anmeldung vom Raspberrymatic auf homematic lokal erfolgt als Admin und Passwort ohne weitere Einträge. Was habe ich falsch gemacht bzw. vergessen? Ich bitte um Mithilfe um das Problem zu lösen. Danke

[home-assistant_2023-02-22T07-59-14.789Z.log](https://github.com/danielperna84/hahomematic/files/10811193/home-assistant_2023-02-22T07-59-14.789Z.log)

### What version of HomematicIP (local) has the issue?

1.30.2

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.67.10.20230114

### What hardware are you running for your system?

Pi4,Pi3

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[home-assistant_2023-02-22T07-59-14.789Z.log](https://github.com/danielperna84/hahomematic/files/10811229/home-assistant_2023-02-22T07-59-14.789Z.log)

### Additional information

CHECK_CONNECTION failed: No clients exist. Trying to create clients for server RaspberryMatic
08:38:35 – (WARNUNG) runner.py - Die Nachricht ist zum ersten Mal am 22. Februar 2023 um 08:57:54 aufgetreten und erscheint 11200 mal
DO_POST failed: ClientConnectorError: Cannot connect to host 192.168.178.21:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')]
08:38:35 – (FEHLER) runner.py - Die Nachricht ist zum ersten Mal am 22. Februar 2023 um 08:57:54 aufgetreten und erscheint 33474 mal
CREATE_CLIENTS failed for RaspberryMatic
22. Februar 2023 um 09:08:29 – (WARNUNG) Homematic(IP) Local (benutzerdefinierte Integration) - Die Nachricht ist zum ersten Mal am 22. Februar 2023 um 08:57:54 aufgetreten und erscheint

**Comment by SukramJ** [comment]
Automatic redirection to HTTPS is activated in your CCU (Settings/Control Panel/Security).

Either disable or enable TLS in the integration. You can find the ports to be configured in the documentation.

**Comment by SukramJ** [comment]
Und noch mal auf Deutsch:

In deiner CCU ist automatische Umleitung auf HTTPS aktiviert (Einstellungen/Systemsteuerung/Sicherheit).

Entweder deaktivieren, oder TLS in der Integration aktivieren. Die entsprechend freizugebenen Ports findest Du in der Dokumentation.

**Comment by SukramJ** [comment]
Ich denke das Ticket kann erst mal geschlossen werden

**Comment by tompanj** [comment]
Vielen Dank für die schnelle Hilfe, läuft jetzt alles nach Wunsch
