### ISSUE TITLE
Der Konfigurationsfluss konnte nicht geladen werden: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by Ulfmerbold2000** [SukramJ/hahomematic#974]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

While tried to start integration of Homematic(IP) local AFTER restart of the server,
got an message "Der Konfigurationsfluss konnte nicht geladen werden: 500 Internal Server Error Server got itself in trouble"

HACS working, custom integration in HACS done

Log "homeassistant.util.package" shows
"Unable to install package hahomematic==2023.2.10: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fd7d2767520>: Failed to establish a new connection: [Errno 101] Network unreachable')': /packages/89/ab/a5480702928ff75b21513b5a8b91ac8a597482fb8bcc66b3d1db399fb23d/hahomematic-2023.2.10-py3-none-any.whl WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fd7d2764730>: Failed to establish a new connection: [Errno 101] Network unreachable')': /packages/89/ab/a5480702928ff75b21513b5a8b91ac8a597482fb8bcc66b3d1db399fb23d/hahomematic-2023.2.10-py3-none-any.whl WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fd7d2767550>: Failed to establish a new connection: [Errno 101] Network unreachable')': /packages/89/ab/a5480702928ff75b21513b5a8b91ac8a597482fb8bcc66b3d1db399fb23d/hahomematic-2023.2.10-py3-none-any.whl WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fd7d27d7ee0>: Failed to establish a new connection: [Errno 101] Network unreachable')': /packages/89/ab/a5480702928ff75b21513b5a8b91ac8a597482fb8bcc66b3d1db399fb23d/hahomematic-2023.2.10-py3-none-any.whl WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fd7d25b4040>: Failed to establish a new connection: [Errno 101] Network unreachable')': /packages/89/ab/a5480702928ff75b21513b5a8b91ac8a597482fb8bcc66b3d1db399fb23d/hahomematic-2023.2.10-py3-none-any.whl ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/89/ab/a5480702928ff75b21513b5a8b91ac8a597482fb8bcc66b3d1db399fb23d/hahomematic-2023.2.10-py3-none-any.whl (Caused by NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fd7d25b46d0>: Failed to establish a new connection: [Errno 101] Network unreachable')) [notice] A new release of pip available: 22.3 -> 23.0.1 [notice] To update, run: pip install --upgrade pip
"

seems i need help :)

### What version of HomematicIP (local) has the issue?

1.30.1

### What was the last working version of HomematicIP (local)?

none

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.67.10

### What hardware are you running for your system?

Intel NUC

### Which config details do you use

- [ ] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [X] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Looks like a problem with internet connection, dns, pypi or whatever.

This is not related to this integration.

**Comment by Ulfmerbold2000** [comment]
valid point, BUT...all reachable, malware filtering only, fully working dns 
10 minutes before i did the initial install of hacs, added the custom repo without problems

**Comment by SukramJ** [comment]
100% not this integration. pip is not able to download from pypi
This is long before the integration starts.
