### ISSUE TITLE
BWTH can't set target temperature that matches current temperature

### ISSUE THREAD

**Issue by iridium2001** [SukramJ/hahomematic#976]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

BWTH Devices cannot be set to a temperature that matches the actual room temperature (target value = current room temperature). E.g.  when the measured room temperature is 20.0°C the target temperature can be set to 19.5 or 20.5°C, but not to 20.0°C. The value is ignored. As soon as the room temperature deviates by 0.1 °C from the setpoint, the values are transmitted. 
I can set the value to 20.0 via the CCU3 or e.g. the mediola app, but not via Home Assistant / hahomematic. 
Same behaviour with other temperature constellations.

Speculation: hahomematic aims to reduce traffic to the devices and hence would not send a new target value that matches the current target value. But it actually checks for the acutal value and not for the configured target value..?!

Using hahomematic 1.32.0 and HA 2023.2.5 on OS 9.5.

### What version of HomematicIP (local) has the issue?

1.32.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.67.10 (Raspberrymatic)

### What hardware are you running for your system?

NAS

### Which config details do you use

- [ ] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Thanks for reporting, there will be a fix in the next release.
