### ISSUE TITLE
HmIP-eTRV shows Heating while Off

### ISSUE THREAD

**Issue by Lemocin** [SukramJ/hahomematic#98]
I have noticed a small display error if i turn off the heating. In the old integration lovelace shows off, here it stays on Heating.
![grafik](https://user-images.githubusercontent.com/4162496/147485820-ad3197bd-269c-4e9e-9bf2-20a66ec133a4.png)

Also, i have noticed, that if the window is opened, I have to press off two times to really turn off the thermostat. After the first time, it goes from Automatic 12°C to Heating 12°C. If I press off another time, it works and turns to 4,5°C. But thats the same with the old integration, so maybe it's a CCU limitation.

**Comment by SukramJ** [comment]
Good Point.

**Comment by SukramJ** [comment]
Turn off issue should be fixed with latest release.

**Comment by Lemocin** [comment]
Yes, now it is showing the state correctly.  Thanks
