### ISSUE TITLE
HmIP-SWO-PR HowTo

### ISSUE THREAD

**Issue by derlbear** [SukramJ/hahomematic#983]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hi,
I installed the HmIP-SWO-PR and connected it to my CCU3. That worked and I can see all the data.

I run HA in my ProxmoxVE and every other device works fine.. but the HomematicIP (local) integration doesn't create any entities for HmIP-SWO-PR.

I restarted the server, restarted the CCU3.. nothing works. Is the HmIP-SWO-PR device supported?

### What version of HomematicIP (local) has the issue?

1.33.1

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [X] Username and password
- [X] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Try service 'Homematic(IP) Local: Clear the cache' and restart HA.

**Comment by derlbear** [comment]
That's it. Thank you!
