### ISSUE TITLE
Battery powered devices fully supported ?

### ISSUE THREAD

**Issue by Jack77777777** [SukramJ/hahomematic#988]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hi Guys,

are battery powered devices fully supported. I see only Low battery state but not the buttons of the device in HA.
For example HmIP-FCI6 and HmIP-WRCC2
![image](https://user-images.githubusercontent.com/64719909/223681243-3b515f5a-20c6-4c87-987a-510f2131d4e7.png)
![image](https://user-images.githubusercontent.com/64719909/223681622-0ab80723-6115-4c67-82cc-a5f39d495a05.png)

### What version of HomematicIP (local) has the issue?

1.33.0

### What was the last working version of HomematicIP (local)?

1.33.0

### What type of installation are you running?

Home Assistant Container

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.67.10.20230114

### What hardware are you running for your system?

HA Synology. Raspberrymatic Pi3

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[config_entry-homematicip_local-8cbca1f7e88c2f6261e5c2237809e268.json.txt](https://github.com/danielperna84/hahomematic/files/10919442/config_entry-homematicip_local-8cbca1f7e88c2f6261e5c2237809e268.json.txt)
[config_entry-homematicip_local-8cbca1f7e88c2f6261e5c2237809e268.json (1).txt](https://github.com/danielperna84/hahomematic/files/10919443/config_entry-homematicip_local-8cbca1f7e88c2f6261e5c2237809e268.json.1.txt)

**Comment by SukramJ** [comment]
These devices are fully supported.

These devices emit events, which are stateless, so no entities are created.
You could use device triggers within automations, or use the blueprints referenced in the docs.
