### ISSUE TITLE
HM-ES-TX-WM does not change the RSSI information

### ISSUE THREAD

**Issue by ChristophCaina** [SukramJ/hahomematic#989]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

It seems that the HM-ES-TX-WM does not change the value for the RSSI-PEER information...

Today, I've set up an HM-ES-TX-WM device.
While I was playing around with it, it was showing the Information "RSSI-PEER": -49 dBm, and this value changed to -48 dBm

After I installed the device on my meter (I know, currently it is placed within a Metal-Cabinet, which is not really an ideal way) - this information did not change anymore.
I do receive meter readings, so the communication is still working - and within the RaspberryMatic, I am getting an RSSI information of - 74 dBm...

In HomeAssistant, this value did not change...

Until:
I've enabled RSSI_DEVICE just to check, if this is showing any information.
After enabling this sensor, the value of RSSI_PEER changed in HomeAssistant and is showing the correct information compared to the information from the CCU.

It seems, that somehow the RSSI_DEVICE seems to be linked to the RSSI_PEER (which is, afaik an information if the device is directly linked to another one...?)

![image](https://user-images.githubusercontent.com/26391061/224447557-1a55a0cc-68eb-444b-a052-4df8a5fb0899.png)

![image](https://user-images.githubusercontent.com/26391061/224447785-1c2fba07-354f-444b-867c-978166677e10.png)

![image](https://user-images.githubusercontent.com/26391061/224447895-81eeb596-2b31-4ffd-a82b-48bd540d5452.png)

btw: I also just noticed, that the wrong firmware is shown...
1.2 was installed, when I added the device, but I've updated to 2.5 today.

![image](https://user-images.githubusercontent.com/26391061/224447816-7a14a375-b5bd-4b7e-bef4-b10bc56883db.png)

### What version of HomematicIP (local) has the issue?

1.33.0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.67.10.20230225

### What hardware are you running for your system?

proxmox

### Which config details do you use

- [ ] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
See #549
