### ISSUE TITLE
Integration changes connection information to raspberrymatic upon HA restart / can't connect after restart

### ISSUE THREAD

**Issue by BenjaminAt10SQ** [SukramJ/hahomematic#992]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

On the same machine:
- Homeassistant running in a container (host networking)
- Raspberrymatic Container with mapped ports (port 80 is remapped to **8234**)

I've configured the integration with IP 127.0.0.1 and JSON port 8234. This works fine until I restart Home Assistant. After some time or after a reboot the integration is unable to connect to raspberrymatic. Opening the "configure" dialog shows a different IP address e.g. 172.21.0.2 which is the IP address from the docker network created for the raspberrymatic container.
To clarify this is not a newly discovered instance - I don't get any notifications about new instances found so I cannot just skip them. The integration just changes my existing setup to the other IP address and fails to connect to it because it doesn't listen on port 8234.

After reconfiguring with the original IP address 127.0.0.1 and setting the port (field is always empty) it is able to connect again.

### What version of HomematicIP (local) has the issue?

1.33.1

### What type of installation are you running?

Home Assistant Container

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.67.10.20230225

### What hardware are you running for your system?

Small Server PC with Ubuntu Server. HA / RM running as docker container

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Anything in the logs that might be useful for us?

```txt
homeassistant    | 2023-03-15 17:17:18.127 ERROR (MainThread) [hahomematic.json_rpc_client] DO_POST failed: ClientConnectorError: Cannot connect to host 172.21.0.2:8234 ssl:default [Connect call failed ('172.21.0.2', 8234)]
homeassistant    | 2023-03-15 17:17:19.151 ERROR (MainThread) [hahomematic.json_rpc_client] DO_POST failed: ClientConnectorError: Cannot connect to host 172.21.0.2:8234 ssl:default [Connect call failed ('172.21.0.2', 8234)]
homeassistant    | 2023-03-15 17:17:19.152 WARNING (MainThread) [hahomematic.json_rpc_client] POST failed: Error while logging in via JSON-RPC
homeassistant    | 2023-03-15 17:17:20.175 ERROR (MainThread) [hahomematic.json_rpc_client] DO_POST failed: ClientConnectorError: Cannot connect to host 172.21.0.2:8234 ssl:default [Connect call failed ('172.21.0.2', 8234)]
homeassistant    | 2023-03-15 17:17:21.199 ERROR (MainThread) [hahomematic.json_rpc_client] DO_POST failed: ClientConnectorError: Cannot connect to host 172.21.0.2:8234 ssl:default [Connect call failed ('172.21.0.2', 8234)]
homeassistant    | 2023-03-15 17:17:21.200 WARNING (MainThread) [hahomematic.json_rpc_client] POST failed: Error while logging in via JSON-RPC
homeassistant    | 2023-03-15 17:17:21.201 WARNING (MainThread) [hahomematic.central_unit] CREATE_CLIENTS failed for bali
homeassistant    | 2023-03-15 17:17:23.603 ERROR (MainThread) [hahomematic.json_rpc_client] DO_POST failed: ClientConnectorError: Cannot connect to host 172.21.0.2:8234 ssl:default [Connect call failed ('172.21.0.2', 8234)]
homeassistant    | 2023-03-15 17:17:24.623 ERROR (MainThread) [hahomematic.json_rpc_client] DO_POST failed: ClientConnectorError: Cannot connect to host 172.21.0.2:8234 ssl:default [Connect call failed ('172.21.0.2', 8234)]
homeassistant    | 2023-03-15 17:17:24.624 WARNING (MainThread) [hahomematic.json_rpc_client] POST failed: Error while logging in via JSON-RPC
homeassistant    | 2023-03-15 17:17:25.651 ERROR (MainThread) [hahomematic.json_rpc_client] DO_POST failed: ClientConnectorError: Cannot connect to host 172.21.0.2:8234 ssl:default [Connect call failed ('172.21.0.2', 8234)]
homeassistant    | 2023-03-15 17:17:26.671 ERROR (MainThread) [hahomematic.json_rpc_client] DO_POST failed: ClientConnectorError: Cannot connect to host 172.21.0.2:8234 ssl:default [Connect call failed ('172.21.0.2', 8234)]
homeassistant    | 2023-03-15 17:17:26.673 WARNING (MainThread) [hahomematic.json_rpc_client] POST failed: Error while logging in via JSON-RPC
homeassistant    | 2023-03-15 17:17:26.673 WARNING (MainThread) [hahomematic.central_unit] CREATE_CLIENTS failed for bali
homeassistant    | 2023-03-15 17:17:26.677 WARNING (MainThread) [hahomematic.central_unit] CHECK_CONNECTION failed: No clients exist. Trying to create clients for server bali
```

**Comment by SukramJ** [comment]
This problem is related to your docker setup.

Don't use the loopback to access a docker container from the same host.
Instead use the **name** of the RM-Container on the docker network. In this scenario a port mapping is not needed and the default can be used.
Further information can be found [here](https://docs.docker.com/network/).

**Comment by BenjaminAt10SQ** [comment]
Indeed, using loopback felt weird but using the kind of random IP address of the bridged network didn't feel better either.

Both containers are created using seperate docker-compose files. HA with `host` network, RM with standard bridge networking. 
Therefore I can't connect HA to RM using the name of the container. Any other suggestions?

**Comment by SukramJ** [comment]
What i described is how HAOS works.
I'd recommend to switch to HAOS (maybe virtualized).

This is not a docker support forum!

**Comment by BenjaminAt10SQ** [comment]
The problem is that the configuration of the hahomeatic integration **changes to a different IP**, maybe due to a discovery mechanism. I read the docs for a way to disable this but didn't find any solution. That's the issue here IMHO, can't see the specific problem with my docker setup.

**Comment by SukramJ** [comment]
I really don't want to spend my time on individual docker setups and docker support.
