### ISSUE TITLE
ccu3 device discovery not working - ccu3 log flooded with errors

### ISSUE THREAD

**Issue by oestreicher42** [SukramJ/hahomematic#993]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

After installation of homematic local through HACS the ccu3 is automatically detected.
After running the configuration the integration finds 1 service and 10 entities, but no devices.
The homematic log shows Java errors when configuring the integration in home assistant. See logs. attached.

Homematic IP devices in use:
HmIP-FALMOT-C12 (3x)
HmIP-PSM-2 (3x)
HmIP-SWSD (7x)
HmIP-WTH-2 (10x)

I tried with and without TLS.
Also I had the FALMOT and WTH-2 configured in heating groups and with direct connections. No difference.

### What version of HomematicIP (local) has the issue?

1.3.1

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which version of your homematic backend are you running?

3.67.10

### What hardware are you running for your system?

Home Assistant Yellow

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[home-assistant_2023-03-18T13-23-57.764Z.log](https://github.com/danielperna84/hahomematic/files/11008616/home-assistant_2023-03-18T13-23-57.764Z.log)
[ccu3-2023-03-18.log](https://github.com/danielperna84/hahomematic/files/11008617/ccu3-2023-03-18.log)

### Anything in the logs that might be useful for us?

```txt
Restart of HomeAssistant around 14:20.
"Configure" homematic integration around 14:21.
```

**Comment by SukramJ** [comment]
Please add integration diagnostic.

**Comment by oestreicher42** [comment]
[config_entry-homematicip_local-e7447f99e708994850bfe2fa4f4625ba.json.txt](https://github.com/danielperna84/hahomematic/files/11008920/config_entry-homematicip_local-e7447f99e708994850bfe2fa4f4625ba.json.txt)

**Comment by SukramJ** [comment]
The CCU errors don't mean anything to me and I can't reproduce them on any of my systems. Maybe restart the CCU.

Nothing unusual in the HA logs, except one warning. Run the service `Homematic(IP) Local: Clear the cache`, and restart HA afterwards.

**Comment by oestreicher42** [comment]
I already did a full reinstall of the homeassistant and several reboots of the ccu3.
Also when the ccu3 stalls, the home assistant becomes unresponsive. I need to reboot the whole system.

It looks like the integration is asking something from the ccu3 which triggers the whole problem.
Perhaps this is a ccu3 software bug, but it would be good to know which request is starting this.

Is there a way to debug the requests send by the integration and perhaps enable/disable them step by step?

**Comment by SukramJ** [comment]
I never heard of a CCU stall in context of this integration so far.
I personally use RaspberryMatic on my systems.

The only relevant warning is `WARNING (MainThread) [hahomematic.json_rpc_client] GET_DEVICE_DETAILS failed: ClientException [()]`. 

Maybe you have a problem with your CCU's sd-card, but i am not an expert for CCU things.

You use a HA Yellow and a dedicated CCU, which are on the same network segment (172.19.2.0/24)?

> Is there a way to debug the requests send by the integration and perhaps enable/disable them step by step?

I don't think the integration is the problem.

**Comment by oestreicher42** [comment]
"same network": yes, they are. Sitting right beside each other.
I also have another installation with HomeAssistant Core running in VM and a raspberrymatic beside it. That works absolutely fine.

At this moment I also think, that the integration is not the real problem. But it causes the ccu3 to create errors.
It would be really helpful to understand which requests the integration is issuing to see when doing the initial setup:

2023-03-18 14:21:25.067 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: homematicip_local
2023-03-18 14:21:36.645 WARNING (MainThread) [hahomematic.json_rpc_client] GET_DEVICE_DETAILS failed: ClientException [()]
2023-03-18 14:21:36.666 DEBUG (MainThread) [hahomematic.client] FETCH_DEVICE_DETAILS: Unable to fetch device details via JSON-RPC

I could simulate this then and perhaps find the problem on the homematic end of things.

**Comment by SukramJ** [comment]
I think this is not worth the effort. 
Hundreds of others installation don't have the problem you describe, so i assume this problem is related to your CCU.

I would recommend to backup your CCU, install a **NEW** sd card with raspberrymatic(or orig. CCU) and restore the backup.

**Comment by SukramJ** [comment]
Currently i don't see an issue in this integration.
Closing this for now.

**Comment by oestreicher42** [comment]
ok. I have not yet reinstalled the ccu3 yet. I think it is config related, so now backup restore for me then.
Anyhow, thanks for your support. I will come back if I found the root cause this way.
