### ISSUE TITLE
Python 3.10 really required?

### ISSUE THREAD

**Issue by idl0r** [SukramJ/hahomematic#994]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [ ] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hi,

is 3.9 really not enough and it really needs to be >=3.10?
If you run a raspian (Debian 11 based) with HA you'll have 3.9 only, at least until Debian 12 has been released. Isn't it possible to support it for some more months until Debian 12 + Raspian is out?

6ff264ae15620284222fc2ca45bfc1ec46130baf (custom_homematic) runs fine, anything after that seems to require >=3.10 for hahomematic

### What version of HomematicIP (local) has the issue?

>1.33.0

### What was the last working version of HomematicIP (local)?

1.33.0

### What type of installation are you running?

Home Assistant Container

### What type of installation are you running for your homematic backend?

CCU3

### Which config details do you use

- [ ] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Yes, the integration requires python 3.10, as does the current HA version.
